### ISSUE TITLE
cant render image on editor after upload to own server

### ISSUE THREAD

**Issue by deepakpapola** [KillerCodeMonkey/ngx-quill#100]
after upload image to own server how to render it on the editor?

**Comment by KillerCodeMonkey** [comment]
Ehhhm, i think quilljs adds an base64 string with the common image module.

Sorry but this is a question you should ask in the quilljs repository.

Am 15.01.2018 4:44 nachm. schrieb "deepak singh papola" <
notifications@github.com>:

**Comment by jaisharmaimcl** [comment]
@deepakpapola can you help us with - https://github.com/h2non/videoshow/ we can pay you for this everything is working fine for us expect caption
