### ISSUE TITLE
Quill editor could be query only after a long time

### ISSUE THREAD

**Issue by nirkai** [KillerCodeMonkey/ngx-quill#1000]
Hi, thanks for your tool.

### Bug description
The quill DOM elements initial takes a long time in V12.

In previous version (V8) I had a directive with simple query selector that worked fine in `AfterViewInit` function, but in the current version (V12) I have a regression.

Checked on Angular 10 with both `ngx-quill`, V8 worked as expected but V12 didn't worked.

### Reproduce steps
Build a simple directive, like:

```
@Directive({
  selector: "quill-editor"
})
export class MyContentDirective implements AfterViewInit {
  constructor(private elementRef: ElementRef) {}

  ngAfterViewInit(): void {
    const buttons = this.elementRef.nativeElement.querySelectorAll("button");
    console.log(buttons);
  }
}
```

The console will print empty node list.
In `ngx-quill` V8 on the `AfterViewInit` you already could query the document.

I wonder if it cause because of the addition of the `ng-content` on the Quill component or because of the SSR support.

**Comment by KillerCodeMonkey** [comment]
the initialisation if quilljs is async and happens after the afterViewInit hook.

check out the readme you can listen on the "onEditorCreated" output. there you get the editor as $event data and work directly with it + you know the editor is instantiated.
