### ISSUE TITLE
Delta import error

### ISSUE THREAD

**Issue by fveltmann** [KillerCodeMonkey/ngx-quill#1007]
ngx-quill/lib/quill-editor.component.d.ts:3:21 

import QuillType, { Delta } from 'quill';
-> causes an error because no export for Delta is found

**Comment by KillerCodeMonkey** [comment]
Just use the correct typings von quilljs

V1.x for quilljs 1.x
Typings v2.x for quill 2.x.

The third issue about this today... Just use issue search next time.

Florian Veltmann <notifications@github.com> schrieb am Di., 25. Aug. 2020,
17:15:

**Comment by fveltmann** [comment]
Currently I have v2.x of the types. So I need v1.x for ngx-quill?

**Comment by KillerCodeMonkey** [comment]
Yes

Florian Veltmann <notifications@github.com> schrieb am Di., 25. Aug. 2020,
18:18:

**Comment by KillerCodeMonkey** [comment]
Quilljs 1.x needs typings Version 1

Bengt Weiße <bengtler@googlemail.com> schrieb am Di., 25. Aug. 2020, 18:21:

**Comment by fveltmann** [comment]
Ok, thanks. Sorry for bothering you with that ^^
