### ISSUE TITLE
Unable to set the size of uploaded image

### ISSUE THREAD

**Issue by brijeshpant83** [KillerCodeMonkey/ngx-quill#1009]
Unable to set the size of uploaded image & there is no way to put that at required place something like ckeditor, I accidentally uploaded big image and tried to adjust in the editor container.
please guid if I am missing anything.

**Comment by KillerCodeMonkey** [comment]
just ask at the quilljs repo. but i would guess you can do it via css by just setting the max-height/-width for images.

+ you could use the image-resize-module. you can find a demo in my example repo.
