### ISSUE TITLE
Replace <strong> by <b> and others

### ISSUE THREAD

**Issue by ialex90** [KillerCodeMonkey/ngx-quill#101]
Hi there,

First of all, thanks for contributing with this cool component to the Angular community, we are grateful for that.

It's not really an issue, but I guess it was ok to throw it here, feel free to close it as soon as you reply to it if you want to.

Wondering if there is any way of replacing the strong label generated around the text when clicking into the "B" (Bold) button in the editor, by the <b> tag. Same way, for italic uses <em> instead of <i>.

I see the idea of using these labels as they are html5 standar, however, not really sure if that's the best, since those tags are providing a semantic meaning versus the old ones, when in a text makes no sense to provide semantic version most of the time, but probably there are some use cases and reasons for this.

I would need to use those old tags just because they are more known standar and for some third party libraries they just accept those instead the new ones.

Thanks,
Regards,

**Comment by KillerCodeMonkey** [comment]
You should mention this in the quilljs repo. This is only an angular
wrapper.

Am 16.01.2018 09:40 schrieb "Alejandro" <notifications@github.com>:

**Comment by ialex90** [comment]
Just in case someone can get benefit of this, solution has been this:

```
import Quill from 'quill';

...

private registerFormatting() {
    const Inline = Quill.import('blots/inline');

    class BoldBlot extends Inline { }
    BoldBlot.blotName = 'bold';
    BoldBlot.tagName = 'b';

    class ItalicBlot extends Inline { }
    ItalicBlot.blotName = 'italic';
    ItalicBlot.tagName = 'i';

    Quill.register(BoldBlot);
    Quill.register(ItalicBlot);
  }



```

**Comment by KillerCodeMonkey** [comment]
You could do this even directly after importing quilljs.

Quill.register changes the global quill settings, so no need to do it later
or in a component function :).

Thanks for sharing your solution.

Am 17.01.2018 12:00 schrieb "Alejandro" <notifications@github.com>:

**Comment by patchworkfish** [comment]
Very similar to your solution @ialex90, the following was the solution in my use case:
I took the info available here: https://quilljs.com/guides/how-to-customize-quill/#customizing-blots and extended it to include italic also.
Using Quill in chrome, using the HTML extracted using quill.root.innerHTML, the use of `<strong>` and `<em>` did not bold or italic the text.

The following code is run after the quill library is loaded and solves my version of this issue:

`// set Quill to use <b> and <i>, not <strong> and <em>

var bold = Quill.import('formats/bold');
bold.tagName = 'b';   // Quill uses <strong> by default
Quill.register(bold, true);

var italic = Quill.import('formats/italic');
italic.tagName = 'i';   // Quill uses <em> by default
Quill.register(italic, true);`
