### ISSUE TITLE
When I use formControl, initialize the form, it triggers valueChange. How do I avoid that

### ISSUE THREAD

**Issue by EonchGao** [KillerCodeMonkey/ngx-quill#1011]
```html
<form>
    <quill-editor [styles]="{height: '150px'}" formControlName="emailContent"></quill-editor>
</form>
```

```ts
ngOnInit(): void {
     this.inquiryInformationForm = this.fb.group({
          emailContent: [null]
        });
    this.inquiryInformationForm.valueChanges.subscribe(
      (res: any) => {
        console.log('📧📧📧📧', res); // here will trigger
        this.propagateChange(res);
      });
}
```

**Comment by KillerCodeMonkey** [comment]
which ngx-quill version do you use.

But i think i played  around a little bit long time ago, and i can not avoid it.
Instead of subscribing the control you could just subscribe the `onContentChanged` output of the quill-editor component

**Comment by EonchGao** [comment]
> which ngx-quill version do you use.
> 
> But i think i played around a little bit long time ago, and i can not avoid it.
> Instead of subscribing the control you could just subscribe the `onContentChanged` output of the quill-editor component
> 
> and btw. could you try to pass valid editor content as default value?
> So instead if `null` something like `<p><br /></p>` null is something like "there is no default value", because the content of the empty editor is `<p><br/></p>`

```
version:"ngx-quill": "^11.1.0",
```
I've tried to pass valid editor content as default value,but it's still going to trigger.The reason for this listening is that i want to detect if the form has changed to give a save hintt

**Comment by KillerCodeMonkey** [comment]
as a workaround i would try to listen on `onContentChanged` and `onEditorCreated`. 

And show you hint, when the content really changes

**Comment by EonchGao** [comment]
> as a workaround i would try to listen on `onContentChanged` and `onEditorCreated`.
> 
> And show you hint, when the content really changes

Thanks.I'll try it
