### ISSUE TITLE
Toolbar not hiding the non specified fields.

### ISSUE THREAD

**Issue by ElAndy94** [KillerCodeMonkey/ngx-quill#1017]
I am happy with the tool but we want to limit the amount of options the text editor shows and I have tried this:

```
public modules: {
        syntax: true;
        toolbar: [
            ['bold', 'italic', 'underline', 'strike'], // toggled buttons
            [{ list: 'ordered' }, { list: 'bullet' }],
        ];
    };
```

![image](https://user-images.githubusercontent.com/34091709/91832573-7e0a8400-ec3d-11ea-935b-e89d350cd154.png)

There is no change on the front end it is still showing the whole toolbar, I have been searching to try find how to only show the options above and hide the rest but I have not been able to find it, since this does not make an effect on the text editor, I believe this might be an issue. Any feedback would be appreciated.

**Comment by ketanambekar1** [comment]
Hey hello, I also faced issue like this.. It basically occurs due to Angular version and package version. i decreases the version of quill to 5.1.0 .. As I was using angular 8. Like wise you compare what version of angular you are using.
They have properly given the compatibility version like below..
Check this link for version 5.1.0 : https://www.npmjs.com/package/ngx-quill/v/5.1.0

**Comment by ElAndy94** [comment]
> Hey hello, I also faced issue like this.. It basically occurs due to Angular version and package version. i decreases the version of quill to 5.1.0 .. As I was using angular 8. Like wise you compare what version of angular you are using.
> They have properly given the compatibility version like below..
> Check this link for version 5.1.0 : https://www.npmjs.com/package/ngx-quill/v/5.1.0

I reduced the version and it is still not hiding the other toolbar elements.

**Comment by ElAndy94** [comment]
> > Hey hello, I also faced issue like this.. It basically occurs due to Angular version and package version. i decreases the version of quill to 5.1.0 .. As I was using angular 8. Like wise you compare what version of angular you are using.
> > They have properly given the compatibility version like below..
> > Check this link for version 5.1.0 : https://www.npmjs.com/package/ngx-quill/v/5.1.0
> 
> I reduced the version and it is still not hiding the other toolbar elements.

Works if I add the toolbar via the forRoot actually so that is some good news. Question is will it work with the newer version if I do it via the forRoot.

**Comment by KillerCodeMonkey** [comment]
just checkout my demo repo. it is using angular 10 and latest ngx-quill version:

https://killercodemonkey.github.io/ngx-quill-example/
Check the: "Formula & image resize editor & Keybinding on 'b' and 'shift + b', CodeBlock + Syntax Highlighting" editor
there i am using a toolbar only with a view defined formats.

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/formula/formula.component.ts#L19

**Comment by ElAndy94** [comment]
So it works with the newest version of ngx-quill but in order for the toolbar to work with Angular 8 from what I can see and have tried is it will only work if you set it via the module.ts

```
QuillModule.forRoot({
            modules: {
                toolbar: [
                    ['bold', 'italic', 'underline', 'strike'], // toggled buttons
                    [{ list: 'ordered' }, { list: 'bullet' }]
                ]
            }
        })
```
