### ISSUE TITLE
Copy paste doesn't work

### ISSUE THREAD

**Issue by Eyegabry99** [KillerCodeMonkey/ngx-quill#1019]
I have a quill-editor that is valued by the server binded with an ngmodel. My problem is i can't copy-paste text inside the quill. I saw a clipboard module but i didn't realize how to integrate it with angular 10. Can someone help me solve this please?

Quill version: 1.3.10

Angular version: 10.0.2

**Comment by KillerCodeMonkey** [comment]
If you are using quilljs directly and not ngx-quill... Ask at the quilljs
repository.



Eyegabry99 <notifications@github.com> schrieb am Di., 1. Sept. 2020, 16:27:

**Comment by Eyegabry99** [comment]
Sorry i'm using ngx-quill not quilljs

**Comment by KillerCodeMonkey** [comment]
And what die you wanna do with Copy and Paste? This ist working Out of the
box?

Eyegabry99 <notifications@github.com> schrieb am Di., 1. Sept. 2020, 16:55:

**Comment by Eyegabry99** [comment]
Yeah it works out of the box. I want to copy-paste a text inside the quill's text-area

**Comment by KillerCodeMonkey** [comment]
I think you have to explain it a little Bit more in Detail .

If i Copy Something in quilljs and Paste IT.. IT IS working.

Eyegabry99 <notifications@github.com> schrieb am Di., 1. Sept. 2020, 17:06:

**Comment by KillerCodeMonkey** [comment]
any news on this?

**Comment by Eyegabry99** [comment]
sorry for my delaying in replying. The problem is in ngx-quill (for angular). If there's some text inside the box and i try to copy and paste another text, i can't do this action. The event ctrl+v doesn't work at all. For example:

Ngx-quill's box contain:  "hello world!"
And i want to paste inside a random text for example " random".

The results that i expect after pasting is "hello world! random"
The results obtained: "hello world!"

it seems like i didn't paste anything
