### ISSUE TITLE
How do I use inline styling instead of classes?

### ISSUE THREAD

**Issue by adamdport** [KillerCodeMonkey/ngx-quill#1028]
The docs say 

> You need to have the quill css files loaded, when using classes and not inline styling (https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline)

I'm using the output to send an email, and so would prefer inline styling if possible (or alternatively include css in the html output). The link you posted suggests that quill supports it but I can't tell if there's a way that ngx-quill has exposed that for me to modify. How can I make the output html all inclusive of the styling being used?

It would be great to update the docs with any solution provided here. thanks.

**Comment by KillerCodeMonkey** [comment]
just follow the guide i linked. it is working the same. 

register stylings as inline e.g.

```JS
var ColorClass = Quill.import('attributors/class/color');
var SizeStyle = Quill.import('attributors/style/size');
Quill.register(ColorClass, true);
Quill.register(SizeStyle, true);
```

**Comment by adamdport** [comment]
- There's no mention in the docs of how to import `Quill` into Angular's typescript. I was able to use `import * as Quill from "quill";`. 
- The available size attributors are `attributors/style/align`, `attributors/style/background`, `attributors/style/color`, `attributors/style/direction`, `attributors/style/font` and `attributors/style/size`

@KillerCodeMonkey If I register the SizeStyle as per your example, the UI no longer permits size changes. I see the menu, I can select a different size, but neither the preview nor the output reflect the size change. Align worked great using the same pattern so I don't think it's my fault.

**Comment by alex737876** [comment]
For those coming here later: For me this also worked:

https://stackoverflow.com/a/75559027/13152100

**Comment by applex90** [comment]
@odonML I had the same problem and now found a solution. Personally, I only use selected styles (whitelist - not necessary) and also have customized buttons for the colors. My html output now has inlinestyles instead of classes.
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/102141977/73df1f03-797f-47b3-a926-a1c21b71f24d)

```typescript

import { QuillModule } from 'ngx-quill';
import Quill from 'quill';
let ColorClass = Quill.import('attributors/class/color');
let ColorStyle = Quill.import('attributors/style/color');
let fontSizeStyle = Quill.import('attributors/style/size');
fontSizeStyle.whitelist = ['14px', '18px', '22px'];
ColorStyle.whitelist = ['black', 'red', 'orange', 'yellow', 'green', 'blue'];
Quill.register(ColorClass, true);
Quill.register(ColorStyle, true);
Quill.register(fontSizeStyle, true);
```
I hope it helps.

**Comment by ghaydarov** [comment]
> just follow the guide i linked. it is working the same.
> 
> register stylings as inline e.g.
> 
> ```js
> var ColorClass = Quill.import('attributors/class/color');
> var SizeStyle = Quill.import('attributors/style/size');
> Quill.register(ColorClass, true);
> Quill.register(SizeStyle, true);
> ```
> 
> there is no magic option in ngx-quill to achieve it.
> 
> if you need the css in emails -> just add the content of the css files to email-templates. :)

Thank you
