### ISSUE TITLE
How to add a custom dropdown to the quill toolbar?

### ISSUE THREAD

**Issue by loremaps** [KillerCodeMonkey/ngx-quill#103]
I've been trying to add a custom dropdown in the toolbar without any luck so far.
There is a similar question here quilljs/quill#1817 but the proposed solution did not worked out for me (and it seems a bit strange).
I have already customized my toolbar with some custom buttons like this:

```
<quill-editor #editor [formControl]="body" (onEditorCreated)="onEditorCreated($event)">
  <div quill-editor-toolbar>

    <!-- Basic buttons -->
    <span class="ql-formats">
      <button class="ql-bold" [title]="'Bold'"></button>
      <button class="ql-italic" [title]="'Italic'"></button>
      <button class="ql-underline" [title]="'Underline'"></button>
      <button class="ql-strike" [title]="'Strike'"></button>
    </span>

    <!-- Size -->
    <span class="ql-formats">
      <select class="ql-size" [title]="'Size'">
        <option value="small"></option>
        <option selected></option>
        <option value="large"></option>
        <option value="huge"></option>
      </select>
    </span>

    <!-- Custom actions -->
    <span class="ql-formats">
      <button [title]="'Signature'" (click)="onAddSignature()">
        <mat-icon fontSet="fontawesome" fontIcon="fa-pencil"></mat-icon>
      </button>
      <button [title]="'Unsubscribe'" (click)="onAddUnsubscribeLink()">
        <mat-icon fontSet="fontawesome" fontIcon="fa-optin-monster"></mat-icon>
      </button>
    </span>

  </div>
</quill-editor>
```
But when I try to add a custom dropdown using the markup, the dropdown is shown without any options.
To provide a bit more context I am trying to achieve a line spacing solution similar to this: https://github.com/quilljs/quill/issues/197#issuecomment-306092948

**Comment by KillerCodeMonkey** [comment]
did you tried to use simple text instead of special icon-components?

**Comment by loremaps** [comment]
I am really sorry for the confusion. The above customization is my current one and buttons works just fine. 
My issue is that I cannot add a custom dropdown with options. For example if I customize it like this...it does add a dropdown but without any options:

```
<quill-editor #editor [formControl]="body" (onEditorCreated)="onEditorCreated($event)">
  <div quill-editor-toolbar>

    <!-- Basic buttons -->
    <span class="ql-formats">
      <button class="ql-bold" [title]="'Bold'"></button>
      <button class="ql-italic" [title]="'Italic'"></button>
      <button class="ql-underline" [title]="'Underline'"></button>
      <button class="ql-strike" [title]="'Strike'"></button>
    </span>

    <!-- Size -->
    <!-- <span class="ql-formats">
      <select class="ql-size" [title]="'Size'">
        <option value="small"></option>
        <option selected></option>
        <option value="large"></option>
        <option value="huge"></option>
      </select>
    </span> -->

    <!-- Custom actions -->
    <span class="ql-formats">
      <button [title]="'Salutation'" (click)="onAddSalutation()">
        <mat-icon fontSet="fontawesome" fontIcon="fa-bullhorn"></mat-icon>
      </button>
      <button [title]="'Signature'" (click)="onAddSignature()">
        <mat-icon fontSet="fontawesome" fontIcon="fa-pencil"></mat-icon>
      </button>
      <button [title]="'Unsubscribe'" (click)="onAddUnsubscribeLink()">
        <mat-icon fontSet="fontawesome" fontIcon="fa-optin-monster"></mat-icon>
      </button>
    </span>

    <!-- THIS ADDS DROPDOWN BUT NO OPTIONS -->
    <span class="ql-formats">
      <select class="ql-lineheight" [title]="'Line Height'">
        <option selected></option>
        <option value="1.0">1.0</option>
        <option value="2.0">2.0</option>
      </select>      
    </span>

  </div>
</quill-editor>
```
This is the dropdown I get:

![image](https://user-images.githubusercontent.com/18003912/35181694-8b9d3fa4-fdcf-11e7-86d7-a0fd449291e2.png)

Does it make sense?

**Comment by KillerCodeMonkey** [comment]
i think quill searchs for a format called "lineheight" and does not found it. So it does not know how to handle and render it.

So create your custom format and use `Quill.register` to register it to Quill.

Look into.
https://github.com/quilljs/quill/blob/a9f99fed7e1c34c1ce9851c33e90f85451cd57ef/quill.js

There the formats are imported and registered afterwards
Checkout exisitng formats, how to write them

**Comment by loremaps** [comment]
It appears I was missing some CSS. Please check `styles.css` [here](https://stackblitz.com/edit/ngx-quill-custom-picker)

I still have a few issues with the default value, but hopefully I am on the right track now.

**Comment by KillerCodeMonkey** [comment]
nice you got this one thing going for you :)

**Comment by natterstefan** [comment]
Hi @KillerCodeMonkey, do you probably also know how to create a  `select`/`custom dropdown`, which is not based on the quill's snow theme? I am struggling creating my very own dropdown based on custom css. I thought you might know something about it :)

**Comment by KillerCodeMonkey** [comment]
never done it :D, sorry 

But it should not that difficult, but i think you will need JS + CSS ;)

**Comment by natterstefan** [comment]
@KillerCodeMonkey thank you :) I figured it out and had to modify/apply custom css to apply my custom style.

**Comment by foo-baar** [comment]
Hey @KillerCodeMonkey good work on Component, I am trying to add custom buttons (for e.g Button to insert a link) but no luck yet, Wondering if there is an example posted anywhere for it ?
Especially to get the instance of the editor (& cursor position) to insert custom text.

Appreciate your time & help,
Danke

**Comment by KillerCodeMonkey** [comment]
Just Look in the quilljs documentation there are some Guides for custom
formats and modules.

If this IS to triggy for you. Just use good old Javascript. Build a custom
toolbar with custom dropdown Elements (Check Out the readme or quill
toolbar doc) and add click listeners to Them and the Buttons.

To get latest or current selection You get the quill Editor instance with
the onEditorCreated Output or the selections and Ranges with the
onSelectionChanged Event. Once You have the Editor instance You can use it
in your custom eventlisteners and manipulate the content :).

I do Not have an example ready for that, but o am Sure there are similar
questions in the quilljs repository

Am Fr., 30. Nov. 2018, 16:42 hat Vishal <notifications@github.com>
geschrieben:

**Comment by foo-baar** [comment]
Thank for reply @KillerCodeMonkey yup I looked into https://codepen.io/anon/pen/rrzpGx wondering if the same will work in ng > 2.
I'll dig in further, Thanks anyways.

**Comment by yevhenshashnin** [comment]
https://medium.com/@genyadstph/react-quill-add-line-height-to-custom-toolbar-91a8717394c8 this article maybe be helpful if you use react

**Comment by aplongh** [comment]
> It appears I was missing some CSS. Please check `styles.css` [here](https://stackblitz.com/edit/ngx-quill-custom-picker)
> 
> I still have a few issues with the default value, but hopefully I am on the right track now.

First of all, A BIG THANK YOU to @KillerCodeMonkey for a great component.
@loremaps, any change you can share the html, component and CSS? I've not been able to display the select title and/or options.

**Comment by MartirosyanMarat** [comment]
Finally I have found a solution, not the best one, but I hope this is good solution, and **it works for 100%** in my case.

If short **you need add this 2 lines** 



```
::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-label[data-label]:not([data-label=""])::before {
  content: attr(data-label);
}

::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-item[data-label]:not([data-label=""])::before {
  content: attr(data-label);
}
```



**_Here is my full code_** 

**`component.ts`**

```import {Component, ViewChild} from '@angular/core';
import {QuillEditorComponent, QuillModules, QuillViewComponent, QuillViewHTMLComponent} from "ngx-quill";
import {FormsModule} from "@angular/forms";
import {JsonPipe} from "@angular/common";

@Component({
  selector: 'app-ngx-quill-demo',
  standalone: true,
  imports: [
    QuillEditorComponent,
    QuillViewComponent,
    QuillViewHTMLComponent,
    FormsModule,
    JsonPipe
  ],
  templateUrl: './ngx-quill-demo.component.html',
  styleUrl: './ngx-quill-demo.component.css'
})
export class NgxQuillDemoComponent {
  @ViewChild(QuillEditorComponent, {static: false}) quillEditor!: QuillEditorComponent;

  lineHeight = '1'
  content: any = '<p>Hello World</p>'
  modules: QuillModules = {
    toolbar: {container: '#custom-toolbar'},
  };


  setLineHeight(value: string) {
    if (this.quillEditor) {
      const editorElement = this.quillEditor.editorElem?.querySelector('.ql-editor') as HTMLElement;
      if (editorElement) {
        editorElement.style.lineHeight = value;
      }
    }
  }

  lineHeightChanged() {
    this.setLineHeight(this.lineHeight);
  }
}
```

**`component.html`**

```<quill-editor
  style="width: 100%"
  [style.line-height]="lineHeight"
  [(ngModel)]="content"
  [modules]="modules"
  format="object">
</quill-editor>

<div id="custom-toolbar">
    <span class="ql-formats">
      <button type="button" class="ql-bold"> </button>
      <button type="button" class="ql-italic"> </button>
      <button type="button" class="ql-align" value=""></button>
      <button type="button" class="ql-align" value="center"></button>
      <button type="button" class="ql-align" value="right"></button>
      <button type="button" class="ql-align" value="justify"></button>
    </span>

  <select class="ql-size">
    <option value="small">Small</option>
    <option selected value="normal">Normal</option>
    <option value="large">Large</option>
    <option value="huge">Huge</option>
  </select>

  <!-- Custom Line Height Dropdown -->
  <select class="ql-custom-line-height"
          data-label="'My Line Height'"
          [title]="'Line Height'"
          [(ngModel)]="lineHeight"
          (ngModelChange)="lineHeightChanged()">
    <option value="1" selected>Default</option>
    <option value="1.5">1.5</option>
    <option value="2">2.0</option>
    <option value="2.5">2.5</option>
    <option value="3">3.0</option>
  </select>
</div>
```

**`component.css`**
```::ng-deep .ql-snow .ql-picker.ql-custom-line-height {
  /*This is not must*/
  min-width: 150px;
}

::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-label[data-label]:not([data-label=""])::before {
  content: attr(data-label);
}

::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-item[data-label]:not([data-label=""])::before {
  content: attr(data-label);
}
```

Note
The only case that I didn't like in this code is that I use the` ::ng-deep`

Wish you the best, I hope this will help you, when I was struggleing I can't fount that will work. 🎉🎉🎉

**Comment by erperejildo** [comment]
> Finally I have found a solution, not the best one, but I hope this is good solution, and **it works for 100%** in my case.
> 
> If short **you need add this 2 lines**
> 
> ```
> ::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-label[data-label]:not([data-label=""])::before {
>   content: attr(data-label);
> }
> 
> ::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-item[data-label]:not([data-label=""])::before {
>   content: attr(data-label);
> }
> ```
> 
> **_Here is my full code_**
> 
> **`component.ts`**
> 
> ```
> import {QuillEditorComponent, QuillModules, QuillViewComponent, QuillViewHTMLComponent} from "ngx-quill";
> import {FormsModule} from "@angular/forms";
> import {JsonPipe} from "@angular/common";
> 
> @Component({
>   selector: 'app-ngx-quill-demo',
>   standalone: true,
>   imports: [
>     QuillEditorComponent,
>     QuillViewComponent,
>     QuillViewHTMLComponent,
>     FormsModule,
>     JsonPipe
>   ],
>   templateUrl: './ngx-quill-demo.component.html',
>   styleUrl: './ngx-quill-demo.component.css'
> })
> export class NgxQuillDemoComponent {
>   @ViewChild(QuillEditorComponent, {static: false}) quillEditor!: QuillEditorComponent;
> 
>   lineHeight = '1'
>   content: any = '<p>Hello World</p>'
>   modules: QuillModules = {
>     toolbar: {container: '#custom-toolbar'},
>   };
> 
> 
>   setLineHeight(value: string) {
>     if (this.quillEditor) {
>       const editorElement = this.quillEditor.editorElem?.querySelector('.ql-editor') as HTMLElement;
>       if (editorElement) {
>         editorElement.style.lineHeight = value;
>       }
>     }
>   }
> 
>   lineHeightChanged() {
>     this.setLineHeight(this.lineHeight);
>   }
> }
> ```
> 
> **`component.html`**
> 
> ```
>   style="width: 100%"
>   [style.line-height]="lineHeight"
>   [(ngModel)]="content"
>   [modules]="modules"
>   format="object">
> </quill-editor>
> 
> <div id="custom-toolbar">
>     <span class="ql-formats">
>       <button type="button" class="ql-bold"> </button>
>       <button type="button" class="ql-italic"> </button>
>       <button type="button" class="ql-align" value=""></button>
>       <button type="button" class="ql-align" value="center"></button>
>       <button type="button" class="ql-align" value="right"></button>
>       <button type="button" class="ql-align" value="justify"></button>
>     </span>
> 
>   <select class="ql-size">
>     <option value="small">Small</option>
>     <option selected value="normal">Normal</option>
>     <option value="large">Large</option>
>     <option value="huge">Huge</option>
>   </select>
> 
>   
>   <select class="ql-custom-line-height"
>           data-label="'My Line Height'"
>           [title]="'Line Height'"
>           [(ngModel)]="lineHeight"
>           (ngModelChange)="lineHeightChanged()">
>     <option value="1" selected>Default</option>
>     <option value="1.5">1.5</option>
>     <option value="2">2.0</option>
>     <option value="2.5">2.5</option>
>     <option value="3">3.0</option>
>   </select>
> </div>
> ```
> 
> **`component.css`**
> 
> ```
>   /*This is not must*/
>   min-width: 150px;
> }
> 
> ::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-label[data-label]:not([data-label=""])::before {
>   content: attr(data-label);
> }
> 
> ::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-item[data-label]:not([data-label=""])::before {
>   content: attr(data-label);
> }
> ```
> 
> Note The only case that I didn't like in this code is that I use the` ::ng-deep`
> 
> Wish you the best, I hope this will help you, when I was struggleing I can't fount that will work. 🎉🎉🎉

How can you have QuillEditorComponent loaded from a standalone component? I get this:

> The component 'QuillEditorComponent' appears in 'imports', but is not standalone and cannot be imported directly. It must be imported via an NgModule.(-992011)
