### ISSUE TITLE
Quill - Mentions Plugin is not returning text onContentChanged event.

### ISSUE THREAD

**Issue by SaiTeja2904** [KillerCodeMonkey/ngx-quill#1030]
Hello,

I have an issue with mentions in ngx-quill.

When I add a new mention and listen for onContentChanged event and try to extract text from it, it is not returning the mentioned value. Let's say my text is " Hello @XYZ(mention), How are you?"  and when I'm trying to extract text from onContentChanged, the text is being returned as "Hello ,How are you?".

This is the configuration I'm using for mentions: 
```
mention: {
      allowedChars: /^[A-Za-z\sÅÄÖåäö]*$/,
      onSelect: (item, insertItem) => {
        const editor = this.editor.quillEditor;
        insertItem(item);
        // necessary because quill-mention triggers changes as 'api' instead of 'user'
        editor.insertText(editor.getLength() - 1, "", "user");
      },
      source: (searchTerm, renderList) => {
        const values = [
          { id: 1, value: "Fredrik Sundqvist",  },
          { id: 2, value: "Patrik Sjölin" },
        ];

        if (searchTerm.length === 0) {
          renderList(values, searchTerm);
        } else {
          const matches = [];

          values.forEach((entry) => {
            if (
              entry.value.toLowerCase().indexOf(searchTerm.toLowerCase()) !== -1
            ) {
              matches.push(entry);
            }
          });
          renderList(matches, searchTerm);
        }
      },
    },

```

and extracting text using:

```
onContentChanged(content) {
    console.log(content.text);
  }
```

Can anyone help me how to update the text?

Thanks in advance.

**Comment by KillerCodeMonkey** [comment]
then just do not use content.text... try content.html or content.object/json..

then the quill mention plugin has no text representation ;-)

**Comment by SaiTeja2904** [comment]
Thanks for the quick response @KillerCodeMonkey. I was able to retrieve plain from content.html.
