### ISSUE TITLE
Misaligned buttons on the toolbar

### ISSUE THREAD

**Issue by sergiober73** [KillerCodeMonkey/ngx-quill#1032]
Hello,
I have implement ngx-quill editor and there are tree especific buttons that seems aligned on the bottom of the toolbar: color, background color and alignment.
![ngx_quill_issue](https://user-images.githubusercontent.com/18353494/93328464-0b440000-f81c-11ea-8cca-da28fe0db7bf.png)

This is my code:

`<quill-editor
        formControlName="elementValue"
        format="html"
        [modules]="quillModules"
      >
</quill-editor>`

```
this.quillModules = {
      toolbar: [
        ['bold', 'italic', 'underline', 'strike'],
        [{ 'font': [] }],
        [{ 'size': ['small', false, 'large', 'huge'] }],
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
        [{ 'list': 'ordered' }, { 'list': 'bullet' }],
        [{ 'indent': '-1' }, { 'indent': '+1' }],
        ['link'],
        [{ 'color': [] }, { 'background': [] }],
        [{ 'align': [] }],
        ['clean'],
      ]
    }
```
The same happens with the modules configuration by defaults.
Any suggestion about this behaviuor, please?

**Comment by KillerCodeMonkey** [comment]
strange, because i do not have any special css in my project Oo.

does this happen, when you use the default modules (do not pass custom toolbar formats)?

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by sergiober73** [comment]
Sorry for the delay, I'm on other business right now.
About your question, yes, the same thing happens when I use the default modules.
I suspect there may be some layout styles affecting, but in this case they should do it with all the buttons.
I will continue to investigate when I return to this task.
Thanks for your interest.

**Comment by KillerCodeMonkey** [comment]
any news on this?

**Comment by KillerCodeMonkey** [comment]
feel free to update the issue. i close it for now
