### ISSUE TITLE
mat-quill problem with modules configuration

### ISSUE THREAD

**Issue by berndlackinger** [KillerCodeMonkey/ngx-quill#1034]
Hi, it seems mat-quill does not support [modules] input.

1. If 'mat-quill' is an Angular component and it has 'modules' input, then verify that it is part of this module.
2. If 'mat-quill' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

<mat-quill #quillEditor [modules]="editorModules" format="html" formControlName="webcontentBody"></mat-quill>

how do you configure the editor modules when using the mat-quill and reactive forms?

**Comment by KillerCodeMonkey** [comment]
there is no "official" map-quill implementation here.
https://github.com/KillerCodeMonkey/ngx-quill/tree/master/projects/ngx-quill/src/lib

it is just a demo in ngx-quill-example repository. 

if you need it - just extend it :D
