### ISSUE TITLE
Question about the usage of forRoot()

### ISSUE THREAD

**Issue by alexbjorlig** [KillerCodeMonkey/ngx-quill#1036]
In the readme it says:

> HINT: If you are using lazy loading modules, you have to add QuillModule.forRoot() to your imports in your root module to make sure the Config services is registered.

But if we add the `forRoot()` in the root module, is the Quill bundle not included? Is the point of lazy loading not to avoid Quill in the main bundle?

**Comment by KillerCodeMonkey** [comment]
only the quill module is included + your root config. the ngx-quill service is created as a single service in your your app, but QuillJS is imported/required only when and where the component is used.

And it is only required once:
https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill.service.ts#L21

this has two effects:
- just load quilljs scripts only when needed
- only load it once
