### ISSUE TITLE
Problems unit testing

### ISSUE THREAD

**Issue by danwellman** [KillerCodeMonkey/ngx-quill#1038]
I'm using ngx-quill 8.1.8, and have wrapped the editor in a component to make reusing it around the app easier. It's working in the app perfectly, but I can't get the unit tests to even run and see the following error in the cmd line:

> TypeError: _this.observer.observe is not a function

The spec file is pretty standard-angular, but I'm importing the Quill module and calling forRoot in the imports array:

```
import { QuillModule } from 'ngx-quill';
...
TestBed.configureTestingModule({
    imports: [ReactiveFormsModule, QuillModule.forRoot()],
    ...
});
```

Seems to be coming from `ScrollBlot`

**Comment by KillerCodeMonkey** [comment]
in general it should work, as it works for testing my own components here:
https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.spec.ts

if it is coming out of ScrollBlot i think i can not help you. :S 

What testing framework do you use? karme, jest ...?

Maybe something you need to mock.

**Comment by danwellman** [comment]
Thanks, it doesn't look like I'm missing anything compared to your example tests.

For reference, I'm using Angular 10, with Jest.

I have tried mocking ScrollBlot, which can be imported from Quill, but it hasn't made a difference.

**Comment by KillerCodeMonkey** [comment]
You should Check maybe The Feature that is existing in real Browser envs
ist Missing in jsdom/jest.

So your tests are failing, but working with karma

Dan Wellman <notifications@github.com> schrieb am Mi., 23. Sept. 2020,
18:21:

**Comment by danwellman** [comment]
👍

**Comment by billyjov** [comment]
@danwellman  Did you solve it with Jest unit test ? if so how ?

**Comment by danwellman** [comment]
@billyjov in the component (not spec file), I just had to import BlotFormatter and provide empty config for that. It’s some quill extension that can be installed via NPM 👍

**Comment by sguin3395** [comment]
`beforeEach(waitForAsync(() => {

    TestBed.configureTestingModule({
      declarations: [ JobCommentsComponent ],
      imports: [
        TestHelperModule,
        AngularMaterialIntegrationModule,
        QuillModule,
        TranslateModule.forRoot({
          loader: {
            provide: TranslateLoader, useClass: TranslateLoaderFactoryMock
          }
        })
      ],
      providers: [
        { provide: DomSanitizer, useValue: sanitizerMock },
        QuillModule.forRoot().providers
      ],
      schemas: [
        NO_ERRORS_SCHEMA,
      ],
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(JobCommentsComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  beforeEach(inject([Store], (store: Store<IAppState>) => {
    storeMock = store;
    storeCallFake = new StoreCallFake(storeMock);
    storeCallFake.spyOn();
  }));

  it('should create', () => {
    expect(component).toBeTruthy();
  });`
  
  That is the code in my spec.ts file and I'm running it with Karma
  
  However, I keep encountering this issue
  
  `TypeError: injector.get is not a function
    at new QuillService (http://localhost:9876/_karma_webpack_/vendor.js:392238:30)
    at Object.QuillService_Factory [as factory] (http://localhost:9876/_karma_webpack_/vendor.js:392277:10)
    at R3Injector.hydrate (http://localhost:9876/_karma_webpack_/vendor.js:288126:29)
    at R3Injector.get (http://localhost:9876/_karma_webpack_/vendor.js:288027:23)
    at ChainedInjector.get (http://localhost:9876/_karma_webpack_/vendor.js:292050:32)
    at lookupTokenUsingModuleInjector (http://localhost:9876/_karma_webpack_/vendor.js:283487:31)
    at getOrCreateInjectable (http://localhost:9876/_karma_webpack_/vendor.js:283530:10)
    at Module.ɵɵdirectiveInject (http://localhost:9876/_karma_webpack_/vendor.js:290084:10)
    at NodeInjectorFactory.QuillEditorComponent_Factory [as factory] (http://localhost:9876/_karma_webpack_/vendor.js:392990:961)
    at getNodeInjectable (http://localhost:9876/_karma_webpack_/vendor.js:283701:38)`

**Comment by Subrata19777** [comment]
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/104012151/b01d4146-d2a9-45da-bdf4-c140ad44d6bc)
[text-editor.zip](https://github.com/KillerCodeMonkey/ngx-quill/files/12816688/text-editor.zip)

Here we are using ngx-quill editor library and we are unable to cover the test cases for the code which is used in the attached files. Can anyone guide us to have 100% code coverage to writing unit test cases.
I have attached my code snippets.

Please provide support.

**Comment by Subrata19777** [comment]
My Library versions:
"ngx-quill": "^15.0.0",
"quill": "^1.3.7",
