### ISSUE TITLE
Dynamic imports are not compiled down in UMD bundle 

### ISSUE THREAD

**Issue by AlexBachmann** [KillerCodeMonkey/ngx-quill#1039]
Hey,

thank you for this great library. 

In the QuillService you use a dynamic import which causes problems when your library is lazy loaded via an UMD bundle at runtime. 

```
const quillImport = await import('quill')
```

This dynamic import is not compiled into an `require()` function call in the UMD bundle. I was therefore wondering if it would be conceivable for you to load the Quill Module via an import statement at the top.

```
import * as QuillModule from 'quill';
```
and use it later like this:
```
const quillImport = QuillModule;
```

Do you see any downsides to this approach?

**Comment by KillerCodeMonkey** [comment]
why would you load the module "lazy loaded" at all?

what is your usecase?

**Comment by AlexBachmann** [comment]
This is a very special use case I admit. We create a large application, that is supposed to dynamically load various kinds of components based on the contents of the page (loaded from the database). The number of possible variations is so large, that we do not want to declare these components in the main application at all, but load them dynamically via UMD modules.

**Comment by KillerCodeMonkey** [comment]
puh.. so i must say, i can not do this, because this would break the out of the box SSR support of ngx-quill. :S.

And why do you use umd bundles? 🙃 Need Support IE11 and below?

**Comment by AlexBachmann** [comment]
Unfortunately yes. But no worries. I was just wondering if that would be an easy change to make. We'll just create a custom solution that fits our needs. Thank you for your time and quick responses.

**Comment by KillerCodeMonkey** [comment]
let me know when you need help or find a solution that i can support :).
