### ISSUE TITLE
addHandler not working Properly

### ISSUE THREAD

**Issue by agam16** [KillerCodeMonkey/ngx-quill#104]
Hello, I am having issue while adding addHandler. I am adding a custom button like this

```
   <quill-editor (onEditorCreated)="getEditorInstance($event)" [modules]="{toolbar: [['link', 'image', 'omega'] }]]}"
```
& in Component below is my code

```
getEditorInstance(editorInstance: any) {
    let toolbar = editorInstance.getModule('toolbar');
    toolbar.addHandler('omega', this.fileHandler.bind(this));
    this.editor = editorInstance;
  }

 fileHandler() {
    console.log('i am here')
 }

```

The issue is i am not able to receive  the console log value & the error i get is 

> quill:toolbar ignoring attaching to nonexistent format omega <button type=​"button" class=​"ql-omega">​…​</button>​

However, when i change the addHandler to existing button like video, then its working fine. 
`    toolbar.addHandler('video', this.fileHandler.bind(this));
`
What could be the issue?

**Comment by KillerCodeMonkey** [comment]
i think omega should be an existing toolbar component if you are add it to the toolbar:

```
[modules]="{toolbar: [['link', 'image', 'omega'] }]]}"
```

Width AddHandler you can override existing handlers like image, link, ....
https://quilljs.com/docs/modules/toolbar/#handlers

If there is no omage format registered on quill, this error appears.
