### ISSUE TITLE
Unable to add the same image twice using the image handler approach.

### ISSUE THREAD

**Issue by shabbyk** [KillerCodeMonkey/ngx-quill#1040]
I am using the handler approach to handler image click - exactly like [this](https://github.com/KillerCodeMonkey/ngx-quill/issues/89#issuecomment-542907588) approach

A sample of handler code:

`config: { 
        handlers: {
          image: () => this.quillFileContainer.nativeElement.click()
        },
}`

Once I select an image, that image is uploaded to server via the code written in the handler. But when I select the **same image** again nothing happens i.e, the handler is not invoked. This may be due to the same image present in context.

Angular versions:

`   
"@angular/cdk": "^9.2.4",
    "@angular/common": "^10.1.2",
    "@angular/compiler": "^10.1.2",
    "@angular/core": "^10.1.2",`

**Comment by KillerCodeMonkey** [comment]
I think you should Test If this is working with native quilljs.

Because i do Just Wrap quilljs in an angular context.
So i am Not touching anything regarding The quilljs modules.

shabbyk <notifications@github.com> schrieb am Do., 24. Sept. 2020, 16:05:

**Comment by shabbyk** [comment]
@KillerCodeMonkey Thank you for the quick reply. Turns out I was not removing image from my native element after uploading the image or file you we need to do something like this

`this.quillFileHandlerInput.nativeElement.value = ''`
