### ISSUE TITLE
Getting application hang on cut text operation.

### ISSUE THREAD

**Issue by sujeetjaiswara** [KillerCodeMonkey/ngx-quill#1046]
Hi, 
I just enter some text in editor & selected text then press `ctrl+x`
Whole application getting hang.

**Comment by KillerCodeMonkey** [comment]
tested in my demo: https://killercodemonkey.github.io/ngx-quill-example/ in firefox,safari and chrome. everything works and nothing hangs...

so i guess you have some browser addons installed or produced an endless loop/JS error in your app.

**Comment by sujeetjaiswara** [comment]
I have fixed.
Problem was, I had scripted inside (onContentChanged)="contentChanged($event)".
```js
contentChanged(context) {
        /* Validate blank input */
        if (context.text.trim().length === 0) {

            /* Commented this code because getting system hang when user press ctrl+x shortcut */
            // const element = document.getElementsByClassName('ql-editor');
            // element[0].innerHTML = '';
            // this.foucsInput();

        } 
    }
```
