### ISSUE TITLE
when I installed , I import {QuillEditorModule} ,there was a error

### ISSUE THREAD

**Issue by setsunahao** [KillerCodeMonkey/ngx-quill#106]
when I installed , I import {QuillEditorModule} ,there was a error

`
 ERROR in node_modules/ng2-quill-editor/quillEditor.component.ts(14,15): error TS2304: Cannot find name 'require'.
`

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {RouterModule} from '@angular/router';
import {editorRoutes} from './editor.routes';
import {ReactiveFormsModule} from '@angular/forms';
import { QuillEditorModule } from 'ng2-quill-editor';
@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    QuillEditorModule,
    RouterModule.forChild(editorRoutes)
  ],
  declarations: []
})
export class EditorModule { }`

**Comment by setsunahao** [comment]
oh! I must be blind,I made a mistake。Thank you for your patient reply

**Comment by KillerCodeMonkey** [comment]
No probs ;).

Please close this issue if your problem is sovled

Am 25.01.2018 10:02 schrieb "setsunahao" <notifications@github.com>:
