### ISSUE TITLE
 Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by flynn-eye** [KillerCodeMonkey/ngx-quill#1067]
I follow the README example but it doesn't work
![image](https://user-images.githubusercontent.com/23251324/97284546-2161c900-187c-11eb-94b6-0ae428aeb9d0.png)

```
"ngx-quill": "^4.7.1",
"@angular/cdk": "^7.2.5",
"@angular/common": "^7.2.5",
"@angular/compiler": "^7.2.5",
"@angular/core": "^7.2.5",
"@angular/forms": "^7.2.5",
```

**Comment by KillerCodeMonkey** [comment]
then check the readme for supported/maintained angular and ngx-quill versions. ;-) 

And https://angular.io/guide/releases
even Angular 9 is only in LTS mode and v8 support will be dropped in the end of november.
