### ISSUE TITLE
Question: How to use angular services in custom modules.

### ISSUE THREAD

**Issue by Eraldo** [KillerCodeMonkey/ngx-quill#1068]
Is there a way to use my angular services in my custom quill module classes?

Why? I want to use my already existing logic and UI selection dialogs.

Any other ideas?

**Comment by KillerCodeMonkey** [comment]
depends what your service is doing. :)

Since angular services only exist in the angular env and needs a dependency injector to create or get correct instances of the service would say: no.

Do you have an example of a service?

**Comment by Eraldo** [comment]
E.g. I have a service that can open the users gallery to select or upload an image and return the image object.

I would for instance like the use that service instead of the default image handler if the image button is present in the toolbar module.

Does that make sense to you? :)

**Comment by KillerCodeMonkey** [comment]
The users gallery is the gallery of the smartphone or file system of the pc or a custom angular modal or something else where you have your "in app" gallery?

In general if you break it down - an angular service is nothing more than a typescript class + dependency injection in general without any UI handling.
In that case you could try to use it - create an instance of that service and use it.

or you could try to build move everything that is possible to just a typescript class. So you share as much common code as possible :).

**Comment by Eraldo** [comment]
> The users gallery is the gallery of the smartphone or file system of the pc or a custom angular modal or something else where you have your "in app" gallery?
It is a custom angular modal.

I did not find an easy way to inject my angular service into the custom typescript module class.
So I ended up not using the quill modules and instead wrapping ngx-quill and injecting my services in there.
It does seem to work but it also feels quite hacky and I would prefer a cleaner approach if possible.

**Comment by KillerCodeMonkey** [comment]
i think there is no cleaner approach.

In general it depends if you are really using something of angular in your services. If you have just logic in there you want to share you could just use ts-classes and create instances and dependencies on your own.

**Comment by LazeKer** [comment]
@KillerCodeMonkey One relatively clean way could be to use the services in the quill config callbacks.
In the exemple bellow, I use the config to declare how images are uploaded using an external library.

First we provide a custom factory injecting the needed services or the angular injector:
```typescript
@NgModule({
	declarations: [],
	imports: [
		CommonModule,
		QuillModule,
	],
	providers: [
		{provide: QUILL_CONFIG_TOKEN, useFactory: getQuillConfig, deps: [Injector]},
	],
})
export class CustomQuillModule {
}
```
I split the config provider in two function, allowing me to use getQuillModules for the `quill-editor` components "[modules]" input, if you need to override some behaviors.
```typescript
export function getQuillConfig(injector: Injector): QuillConfig {
	return {
		modules: getQuillModules(injector),
		customModules: [
			{implementation: ImageUploader, path: 'modules/imageUploader'},
		],
	};
}
```
```typescript
export function getQuillModules(injector: Injector): QuillModules {
	const quillService = injector.get(QuillService);

	return {
		imageUploader: {
			upload: (file: File) => new Promise((resolve, reject) => {
				quillService.upload(file).subscribe(
					upload => resolve(API_DOMAIN_URL + upload.url),
					error => reject(error),
				);
			}),
		},
	};
}
```
