### ISSUE TITLE
How to add toolbar handlers dynamically?

### ISSUE THREAD

**Issue by Eraldo** [KillerCodeMonkey/ngx-quill#1070]
I have a service that has access to the quill editor. (`quill` variable below)
```ts
co-links-module.ts
    ...
    const toolbar = quill.getModule('toolbar');
    if (toolbar) {
      // toolbar.addHandler('quickadd', this.handleQuickadd.bind(this.quill));  // <==== This does not work
      toolbar.addHandler('quickadd', (value) => {  // <==== This does not work
        this.handleQuickadd(value);
      });
    }
    ...
```
The code snippet runs without errors, however when I click on the custom toolbar button, nothing happens.

If I instead add that handler directly to the config:
```ts
editor.component.ts
    ...
    toolbar: {
      container: [
        ['bold', 'italic', 'underline', 'strike'], // toggled buttons
        ...
        ['quickadd'], // link and image and video
      ],
      handlers: {
        ...
        'quickadd': (value) => {
          this.coLinksModule.handleQuickadd(value);  // <==== This does work
        },
      },
    },

```
And then click the button, it does work.
I do not understand why. Not even after hours of trying to wrap my head around it.

I am wondering why I cannot add a handler outside of the config?
Any ideas what is going on?

**Comment by KillerCodeMonkey** [comment]
could you please share the full code of `co-links-module.ts`?

**Comment by Eraldo** [comment]
```ts
import {Injectable} from '@angular/core';
import {NotificationService} from '../../../notifications/notification.service';
import {QuickActionService} from '../../../quick-action/quick-action.service';
import QuillType from 'quill';
import Quill from 'quill';
import {Icon} from '../../../../../models/icon';
import {Color} from '../../../../../models/color';

const quillIcons = Quill.import('ui/icons');
quillIcons['quickadd'] = `<ion-icon name="${Icon.ADD}" color="${Color.MEDIUM}"></ion-icon>`;
Quill.register('modules/coLinks', class coLinks {});

@Injectable()
export class CoLinksModule {
  quill;
  options;

  constructor(
    private notificationService: NotificationService,
    private quickActionService: QuickActionService,
  ) {
  }

  init(quill: QuillType, options = {}) {
    this.quill = quill;
    this.options = options;

    // NOTE: This only works when the toolbar module already has a handler with that name.
    // In that case it will overwrite it.
    const toolbar = quill.getModule('toolbar');
    if (toolbar) {
      toolbar.addHandler('quickadd', (value) => {
        this.handleQuickadd(value);
      });
    }

    // Handler that looks for insert deltas that match specific characters
    this.quill.on('text-change', (delta, oldContents, source) => {
      for (let i = 0; i < delta.ops.length; i++) {
        if (delta.ops[i].hasOwnProperty('insert')) {
          if (delta.ops[i].insert === '?') {
            this.onTrigger()
          }
        }
      }
    })

    this.addKeyboardShortcuts();
  }

  onTrigger() {
    this.notificationService.showSuccess('CoLinks');
  }

  addKeyboardShortcuts() {
    this.quill?.keyboard.addBinding({key: 'q', altKey: true}, (range, context) => {
      this.handleQuickadd(true);
    });
  }

  async handleQuickadd(value) {
    if (value) {
      const range = this.quill.getSelection(true) || {index: 0};
      const data = await this.quickActionService.present(undefined);
      if (data?.outcome) {
        const name = data?.outcome?.name;
        const url = `/palace/outcomes/${encodeURIComponent(data?.outcome?.id)}`;
        // Inserting the outcome link.
        this.quill.insertText(range.index, name, 'link', url);
        // Setting cursor after link.
        this.quill.setSelection(range.index + name.length);
      }
    }
  }

}
```

And I hook into `onEditorCreated` in my wrapper:
```
  editorCreated(quill: QuillType) {
    this.onEditorCreated.emit(quill);
    this.quillEditor = quill;

    // TODO: Moving this to Plugin service and add a registerPlugin function.
    const coLinks = quill.getModule('coLinks');
    if (coLinks) {
      this.coLinksModule.init(quill);
    }
  }
```

**Comment by KillerCodeMonkey** [comment]
General hint about your service:

if you have multiple editors your quill instance will be overwritten i think, when your service is only registered in your main app.module

**Comment by Eraldo** [comment]
It won't because a new one is provided along with each component. ;)

**Comment by KillerCodeMonkey** [comment]
okay, so how do you create those instances (just for curiosity)

**Comment by Eraldo** [comment]
I don't, angular does that for me via DI in the wrapper.

PS: I'd really enjoy showing you my code and talk about what might be better ways and maybe other people using ngx-quill would also be interested in having an easier time integrating your library with existing angular services. ;)

**Comment by KillerCodeMonkey** [comment]
i am curious because creating new instances with DI only works, when you have wrapped your component in a module where you add your service as a provider. per default angular does not create new instances per default i think.

**Comment by Eraldo** [comment]
You are correct when it comes to the default.

As you can see above I used:
```
@Injectable()
```
Instead of the default:
```
@Injectable({
  providedIn: 'root'
})
```

**Comment by KillerCodeMonkey** [comment]
okay, but then you will get a new instance per `module` not per component usage in that module (as far as i know).

So if you use multiple editors in one angular module they will overwrite each other.

If you want to have a new instance per usage of your editor-component, you need to add the service as a provider to that component.

But maybe you have it implemented in that way.

**Comment by Eraldo** [comment]
> But maybe you have it implemented in that way.

Yes, that is what I am doing.

**Comment by KillerCodeMonkey** [comment]
nice, then back to the issue:

Is your handler not executed at all, or is just the `handleQuickadd` not called.
And is the toolbar found?

See: https://github.com/KillerCodeMonkey/ngx-quill/issues/1070#issuecomment-719265864

**Comment by Eraldo** [comment]
Regarding #1070: I turned off the custom toolbar template for now, so that should not have to do with it at the moment.

> Is your handler not executed at all, or is just the handleQuickadd not called.

It is not executed at all.

**Comment by GitHubish** [comment]
@Eraldo I am very interested in the outcome of this exchange. Unfortunately, I have no idea how to help you solve this problem. Maybe you could create an example on Github that we can retrieve for test/debugging?

**Comment by AntonCooper** [comment]
I had a similar issue with registering dynamic toolbar handlers. The solution for me was to ensure that the editor has an appropriate blot for the handler registered. Without this blot registered with Quill the 

eg: register the blot, then register the handler.
```js
Quill.register({ "formats/emoji": EmojiBlot });
```

```js
this.quill
    .getModule("toolbar")
    .addHandler("emoji", this.handleEmojiClick);
```

Hope this helps someone!
