### ISSUE TITLE
Text with special character was cleared when input

### ISSUE THREAD

**Issue by MinhPhuPham** [KillerCodeMonkey/ngx-quill#1072]
I imported ngx-quill follow docs, but when i typing my language (Vietnamese) it was clear. 
Example: "Các" => "ác" and when input into it, it format like that. 
Image when input:
![image](https://user-images.githubusercontent.com/51711158/97774302-1a42ff80-1b89-11eb-9bbe-6cea3f47a1c7.png)
Image import ngx-quill and init form:
![image](https://user-images.githubusercontent.com/51711158/97777918-f3df8d00-1ba5-11eb-98e2-159ff0ac0217.png)
![image](https://user-images.githubusercontent.com/51711158/97777923-fe018b80-1ba5-11eb-87e0-395098349fd8.png)

**Comment by KillerCodeMonkey** [comment]
You should ask this in the quilts repo

I have no logic in there to strip characters. Quilljs does it do only allow supported formats, html and chars.

Thanks

**Comment by KillerCodeMonkey** [comment]
But for example, if i enter `Các` into https://killercodemonkey.github.io/ngx-quill-example/ everything works fine :)

**Comment by MinhPhuPham** [comment]
Yeah, but in my project, i haven't import anything to it, i seperate it into a module, but it not working follow my hope =( 
This must be my fault, I will refer to it on the stackover. Thanks
