### ISSUE TITLE
RouterLink in custom blots

### ISSUE THREAD

**Issue by Eraldo** [KillerCodeMonkey/ngx-quill#1073]
How can I user/trigger angular navigation as a reaction to clicking on a custom embed blot?

**Comment by KillerCodeMonkey** [comment]
Just try to use angular router If this does nothing without any Error. Try
to Wrap The Routing piece of Code in ngZone.run.

Or IT depends how you configured your Router Just try to use a tags or
change the Windows.location directly.

Eraldo Energy <notifications@github.com> schrieb am So., 1. Nov. 2020,
01:11:

**Comment by Eraldo** [comment]
> PS: Those question are hard to answer, since quilljs is native js and executes everything outside of angular context.

Yes, they truly are, I agree. I hope I am not stressing you with them. I would just like to find a nice way for quill and angular to play together. I am experimenting a lot that last days.
