### ISSUE TITLE
altKey modifier in QuillType

### ISSUE THREAD

**Issue by Eraldo** [KillerCodeMonkey/ngx-quill#1074]
According to quill's documentation: https://quilljs.com/docs/modules/keyboard/#key-bindings,
there are multiple key modifiers available (5 to be exact) and `altKey` is one of them.
However I get a compiler error because addBinding of QuillType (`this.quill.keyboard.addBinding`) does only support `shortKey`:
```ts
export interface Key {
    key: string;
    shortKey?: boolean;
}
```

This is what I am doing as a hacky workaround:
```ts
{key: 'q', altKey: true} as Key
```

**Comment by KillerCodeMonkey** [comment]
since i am using quilljs types you should create a PR there :) https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/quill/index.d.ts

**Comment by Eraldo** [comment]
Makes sense to me. Thanks.
