### ISSUE TITLE
Adding a button to the Quill editor using global module and having handler for the button

### ISSUE THREAD

**Issue by rammahpour** [KillerCodeMonkey/ngx-quill#1075]

**Comment by rammahpour** [comment]
I am trying to put a button in the editor along with it's handler using ```QuillModule.forRoot```.

**Comment by KillerCodeMonkey** [comment]
If you want to do it this way you need to add a custom format and add it to the toolbar.

Checkout: https://github.com/quilljs/quill/blob/1.3.7/modules/toolbar.js#L29 (this is how quill toolbar calls handler for formats.
And https://github.com/quilljs/quill/blob/1.3.7/formats/image.js for a custom format.

**Comment by rammahpour** [comment]
Actually, my project is Angular 10. Not sure if you have any example regarding that. Also need to add an icon to the button. The point is that I will want to use ``QuillModule.forRoot({... `` to add the module in the editor globally.
I looked into "count" example, not sure if that can be helpful really.
"count" example : 
``
QuillModule.forRoot({
      customModules: [{
        implementation: Counter,
        path: 'modules/counter'
      }],
      customOptions: [{
        import: 'formats/font',
        whitelist: ['monospace']
      }]
    }),
``

**Comment by KillerCodeMonkey** [comment]
my demo repo is using angular 10 and so all examples in there are implemented with angular 10.
sadly i can not answer you the question if it is possible to add  a custom icon to it.

but i think you can just use css to add it as ":before" or ":after" element of the button.

**Comment by rammahpour** [comment]
Let me ask my question more clearly. I am trying to customize your "count" example to have a button in the toolbar and handling the handler... The issue is that the handler is not working when the button is clicked... Any idea please?
Toolbar : 
```
        const defaultToolbar = [
            ['bold', 'italic', 'underline', 'strike'],  
            ['quickadd'] // the added button
        ];
```


and counter.ts

```
export default class Counter {
  quill: QuillInstance
  options: Config

  constructor(quill, options) {
      debugger;
    this.quill = quill
    this.options = options

    const container = document.querySelector(this.options.container)

    this.quill.on('editor-change', () => {
      debugger;
      const length = this.calculate()
    })

    const toolbar = quill.getModule('toolbar')
    toolbar.addHandler('quickadd', this.calculate); // HERE NOT WORKING
  }

```
