### ISSUE TITLE
Created custom module can not interact with other components in Angular

### ISSUE THREAD

**Issue by rammahpour** [KillerCodeMonkey/ngx-quill#1078]
I have added a button in the toolbar with it's handler as a custom module and everything working until here. The only issue is that not able to interact with other components. e.g. not able to expand a bottom sheet/pop up which has been defined in the Angular project and gets an error. Any idea, please?

My implementation for the module is:

```
import * as QuillNamespace from 'quill';
const Quill: any = QuillNamespace;
// tslint:disable-next-line: no-empty-interface
export interface Config {}
// tslint:disable-next-line: no-empty-interface
export interface QuillInstance {}

export default class StampHandler {
  quill: QuillInstance;
  options: Config;

  constructor(quill: any, options: any) {
    this.quill = quill;
    this.options = options;

    const toolbar = quill.getModule('toolbar');
    toolbar.addHandler('insertStamp', this.insertStamp.bind(this));
  }

  insertStamp(): void {
    console.log('insertStamp!', this);
  }
}
```

**Comment by KillerCodeMonkey** [comment]
Please build a complete example in stackblitz or in a github repo.
This is just a ts file and a quill module. Nothing angular related. + if you get an error you should share it... and not just saying "i get an error" ;-)

and in general you can not simply use angular components in quilljs modules.
