### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by trdmitry** [KillerCodeMonkey/ngx-quill#1081]
Compilation error: 

    Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:34 - error TS7016: Could not find a declaration file for module 'quill'. 'node_modules/quill/dist/quill.js' implicitly has an 'any'
 type.
      Try `npm install @types/quill` if it exists or add a new declaration (.d.ts) file containing `declare module 'quill';`
    
    3 import QuillType, { Delta } from 'quill';
                                       ~~~~~~~
    node_modules/ngx-quill/lib/quill-view.component.d.ts:1:23 - error TS7016: Could not find a declaration file for module 'quill'. 'node_modules/quill/dist/quill.js' implicitly has an 'any' type.
      Try `npm install @types/quill` if it exists or add a new declaration (.d.ts) file containing `declare module 'quill';`
    
    1 import QuillType from 'quill';
                            ~~~~~~~

**Comment by KillerCodeMonkey** [comment]
You Need to Install The correct quill typings 

V1.3.x Same goes for quilljs itseld
