### ISSUE TITLE
How to customize the toolbar?

### ISSUE THREAD

**Issue by cssberries** [KillerCodeMonkey/ngx-quill#1082]
There are examples of how to use a custom html but this html still must have certain classes in order to work properly.
My question is: is there any way to use arbitrary html and communicate with quill trough API?

**Comment by KillerCodeMonkey** [comment]
sadly i do not know other ways to use custom html.

You could try to register your own formats/blots to not even need to write the complete toolbar on your own.
i mean at leas you could create you custom toolbar and use click listeners to communicate with the quill over the api and toggle formats and so on. but this would be much more work then just following the quilljs guide to build a custom toolbar.

**Comment by cssberries** [comment]
I'm trying to apply a different styling to the whole thing and currently I'm overriding a lot of CSS which feels wrong and potentially unmaintainable. Dropdown menus are especially hard to handle. So, I just wanted to verify this approach. Is the overriding is the best way to go here?

**Comment by KillerCodeMonkey** [comment]
I think this is the correct way.

think about just using quill.core.css and add you own "theme" for the toolbar instead if using snow or bubble theme and overwriting everything there.

PS: i never tried it, but looking at:

https://cdn.quilljs.com/1.3.6/quill.snow.css
https://cdn.quilljs.com/1.3.6/quill.bubble.css

just replace the `-snow|bubble` with your theme name.

**Comment by cssberries** [comment]
Hm... that sounds better.
I'll try it.
Thanks a lot!
