### ISSUE TITLE
Keyboard closes when tapping text in editor with Ionic 4

### ISSUE THREAD

**Issue by Zinga9** [KillerCodeMonkey/ngx-quill#1088]
Hi @ShaneJohnsonCC or  @KillerCodeMonkey can you elaborate how you have set no-blur, Please.

_Originally posted by @Zinga9 in https://github.com/KillerCodeMonkey/ngx-quill/issues/538#issuecomment-733697760_

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/538#issuecomment-733877084
