### ISSUE TITLE
Dragging image into textarea not working

### ISSUE THREAD

**Issue by srigar** [KillerCodeMonkey/ngx-quill#109]
Most of RTE supports dragging an image into textarea instead of clicking upload image icon every time. Please try to include that feature.

**Comment by KillerCodeMonkey** [comment]
Guuuuuys please ask those Feature request at the quilljs repo.

I will not add Features that the Base quill Editor does not Support.

This is only an angular wrapper with some easy to use functionalities for
the quilljs editor.

So... Sorry Dude.

Am 06.02.2018 06:31 schrieb "Srigar Sukumar" <notifications@github.com>:
