### ISSUE TITLE
Image inline styles is removed

### ISSUE THREAD

**Issue by denisr-w** [KillerCodeMonkey/ngx-quill#1091]
I'm using `ngx-quill` with `quill-image-resize` in my app. When I resize the image and position it on the right some inline styles is added to the image. I then store the html content from editor to my database and when I try to open an editor with this content, inline style on image is removed. I saw multiple issues being posted about this. I also found [this](https://github.com/kensnyder/quill-image-resize-module/issues/10) solution that seemed to work for a lot of pepole. Since I'm using angular and typescript I get an error about `this.domNode` not beeing found. Can you help me?

**Comment by KillerCodeMonkey** [comment]
quilljs works with class styles and will remove inline stylings per default.

so maybe you need to switch to inline styles:
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

i will not add ugly workarounds for poor written and outdated stuff. sorry ;-)

**Comment by vbobroff-app** [comment]
Solution for Angular app (and other typeScript one), and I recomend to use 'blotFormatter' instead 'quill-image-resize'
```
import Quill from 'quill';

interface EmbedBlot {
  new(...args: any[]): EmbedBlot;
  domNode: any;
  format(name, value);
}

const Image: EmbedBlot = Quill.import('formats/image');
const ImageFormatAttributesList = [
  'alt',
  'height',
  'width',
  'style'
];

class StyledImage extends Image {
  static formats(domNode) {
    return ImageFormatAttributesList.reduce(function (formats, attribute) {
      if (domNode.hasAttribute(attribute)) {
        formats[attribute] = domNode.getAttribute(attribute);
      }
      return formats;
    }, {});
  }
  format(name, value) {
    if (ImageFormatAttributesList.indexOf(name) > -1) {
      if (value) {
        this.domNode.setAttribute(name, value);
      } else {
        this.domNode.removeAttribute(name);
      }
    } else {
      super.format(name, value);
    }
  }
```

**Comment by SeyedMostafaHosseinian** [comment]
> quilljs works with class styles and will remove inline stylings per default.
> 
> so maybe you need to switch to inline styles: https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline
> 
> i will not add ugly workarounds for poor written and outdated stuff. sorry ;-)

You do not respond well at all. There are inline styles in the output, so quill doesn't delete them. If we use the same output for a normal element and sanitize it before use, those styles will be applied, but when we set it for quill-view or quill-editor, the styles will be deleted.
