### ISSUE TITLE
 How do I reset tool bar to back to my app.module settings?

### ISSUE THREAD

**Issue by nullptrerror** [KillerCodeMonkey/ngx-quill#1096]
I'm currently trying to add the image and video buttons to the toolbar only in one lazy loaded module that needs images and videos. The rest don't support images or videos.

I was able to set it up in a child angular module but when I navigate to other areas of the applications the settings are permanently changed. How can I reset the toolbar back to the original settings from a child angular module?
I tried setting the settings back to normal when the component calls onDestroy but I still see the icons everywhere. I can't seem to understand the solutions I found online so this is my last resort.

![image](https://user-images.githubusercontent.com/59756494/101164870-b38b8880-3603-11eb-8fac-23adda9f11a3.png)

**Comment by KillerCodeMonkey** [comment]
in general in your base module you set it up with `QuillModule.forRoot()` and your config their.
In the lazy loaded module you need to use just `QuillModule`.
And then change the toolbar setting on component level.

In general .forRoot is storing the config in a service.
If you are changing it in one place, it is changed everywhere.

**Comment by nullptrerror** [comment]
I'm not able to change it at the component level currently. I opened another ticket with more details.
