### ISSUE TITLE
Configurable block tag (div, paragraph)

### ISSUE THREAD

**Issue by jadamconnor** [KillerCodeMonkey/ngx-quill#11]
Any ideas on how to implement the solution found [here](https://github.com/quilljs/quill/issues/228#issuecomment-219261128) in an Angular 2 project? I'm not fond of the `<p><br></p>` line on enter. I think the output should look the same as what's shown in the editor.

**Comment by KillerCodeMonkey** [comment]
you can try if it is working when you do it like described by jason chen. 

without the 

```// Create your Quill editor like before
var quill = new Quill('#editor');```

part.

if you install ngx-quill you get quill and parchment as dependencies.

```
import Quill from 'quill';
const Parchment = Quill.import('parchment');
let Block = Parchment.query('block');

Block.tagName = 'DIV';
// or class NewBlock extends Block {}; NewBlock.tagName = 'DIV';
Quill.register(Block /* or NewBlock */, true);
```

**Comment by KillerCodeMonkey** [comment]
I added the example to the ngx-quill-demo repository:
- line 3 - 10 
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts

if you open the demo (https://killercodemonkey.github.io/ngx-quill-example/) --> use the last editor an check you JS-Console. There you can see the changes in that editor instance --> no p-tags. Only divs ;)

<img width="572" alt="bildschirmfoto 2017-02-05 um 08 52 00" src="https://cloud.githubusercontent.com/assets/2264672/22624575/6dc4e106-eb80-11e6-8231-c7d87970f400.png">

**Comment by jadamconnor** [comment]
Excellent, thank you.

**Comment by jadamconnor** [comment]
Apparently, I'm using ng2-quill-editor. Ha!. And I know the reason now. `[config]="editorConfig"` passes a config object to the element with ng2-quill-editor. I couldn't figure out how to pass a config object to ngx-quill. Looking at the component, there is no input for such an object.

**Comment by MickL** [comment]
As of 2021, is there a more elegant way of doing this @jadamconnor ? E.g. within the .forRoot() function?

**Comment by MickL** [comment]
As of 2021, is there a more elegant way of doing this @KillerCodeMonkey  ? E.g. within the .forRoot() function?

**Comment by psy21d** [comment]
I very important to use DIVs in this editor.
I need to create pages via divs
how I can do it?

**Comment by KillerCodeMonkey** [comment]
just check the demo repo. it is using divs https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/app.component.ts#L7
