### ISSUE TITLE
GROUP DROP DOWN BUTTONS TOOLBAR

### ISSUE THREAD

**Issue by miguelcornelli** [KillerCodeMonkey/ngx-quill#1101]
Hi,
I would like to know how to group the buttons on the toolbar by decreasing the responsiveness of the screen, making a drop-down list so that the buttons do not fall in a line ... as shown in the image below:
![WhatsApp Image 2020-12-08 at 11 43 30](https://user-images.githubusercontent.com/35777596/101498253-a267b200-394a-11eb-8878-b4f59bac9774.jpeg)
![WhatsApp Image 2020-12-08 at 11 42 10](https://user-images.githubusercontent.com/35777596/101498255-a3004880-394a-11eb-82ce-81b7330d6e71.jpeg)

**Comment by KillerCodeMonkey** [comment]
just ask this at the quilljs repo ;-)
  
​
