### ISSUE TITLE
When using Numbering unable to continue if i use sub numbering 

### ISSUE THREAD

**Issue by raoshahid799** [KillerCodeMonkey/ngx-quill#1105]

**Comment by KillerCodeMonkey** [comment]
maybe ask this at the quilljs repo?

**Comment by KillerCodeMonkey** [comment]
working fine in my demo:

https://killercodemonkey.github.io/ngx-quill-example/

just use "shift+tab" and you will go a level up

**Comment by raoshahid799** [comment]
its not following the standard  like ms word, other editors
see this example  
https://ckeditor.com/ckeditor-5/demo/
![image](https://user-images.githubusercontent.com/13733062/101873535-e9eb7980-3ba8-11eb-95d4-d96d6be3762b.png)

**Comment by raoshahid799** [comment]
are you able to produce this issue

**Comment by KillerCodeMonkey** [comment]
yes but that is how quilljs works. ;-) You can create your own numbered list format/blot

**Comment by raoshahid799** [comment]
Thanks can you guide  me  which  repo should is use for this modification,
