### ISSUE TITLE
Adding Custom Module

### ISSUE THREAD

**Issue by JKing-B16** [KillerCodeMonkey/ngx-quill#1108]
Hi, I'm working on integrating Quill into a custom CMS built with AngularMaterial (AM). I would like to update the link or add a custom link button that would pop-up a box where the user could enter a link to another site, as is now the case, or select from an autocomplete of the pages already in the CMS. I have gotten as far as extending the base Link class with my CMSLink, see below. However, I don't know how to best call trigger an Angular element to open. I'm would probably try to do this with the included AutoComplete and/or Dialog modules in AM. Any suggestions as to what the next steps would be or where I should look?

```
export class CMSLink extends Link {
  blotName = 'link';
  tagName = 'A';
  SANITIZED_URL = 'about:blank';
  PROTOCOL_WHITELIST = ['http', 'https', 'mailto', 'tel'];

  static create(value) {
    let node = super.create(value);
    console.log(`CMSLink`, node);
    return node;
  }
}
```

**Comment by KillerCodeMonkey** [comment]
i think this will be a hard one. you could try to a a custom handle where you pass in your logic to opening something.

but you need to handle change detection and so on on your own.

So just add a CMSLink handler where you do you stuff.
Or add custom click listener on your toolbar button
