### ISSUE TITLE
multiple cascade blockquote insted of groupped

### ISSUE THREAD

**Issue by kernyden** [KillerCodeMonkey/ngx-quill#1110]
lets say we have a string like: `<blockquote><p>1st one<br />2nd one</p></blockquote>`.

**expected one**:
<blockquote>
<p>asdsadad<br />
asdasdads</p>
</blockquote>

**current result**:
<blockquote>1st one</blockquote>
<blockquote>2nd one</blockquote>

![blockquote](https://user-images.githubusercontent.com/25119196/102017651-e1459f80-3d70-11eb-9c3d-c3c8345551f0.png)

**Comment by KillerCodeMonkey** [comment]
please open those issues at the quilljs repository. i am just providing an angular wrapper and do not handle any formatting

**Comment by kernyden** [comment]
ah, thx, [opened](https://github.com/quilljs/quill/issues/3252)
