### ISSUE TITLE
Formatting issue in tab control

### ISSUE THREAD

**Issue by jpett** [KillerCodeMonkey/ngx-quill#1112]
Hi @KillerCodeMonkey,

first of all: Thanks for all your great work! :)

I stumbled upon an issue that might also be related to #982 and others. When the quill editor is displayed in a tab control which is not visible at startup, the HTML contained in it lacks its formatting. I have created a Stackblitz sample to illustrate the issue:

https://stackblitz.com/edit/angular-ngx-quill-tabs-issue

You can see that the same HTML string is rendered correctly within the first tab which is initially visible while the content in the second tab is displayed without correct formatting.

Best regards,

Justus

**Comment by KillerCodeMonkey** [comment]
i will not try to find the root case in angular material.
  
​just ask there, why this is happening :).
  
​Or just check the material tab source code what is happening there.
  
​
  
​If you have some findings let me know, if i need to change something.

**Comment by jpett** [comment]
It's not an Angular Material issue, it also happens in the tab control in our application, which is not based on Angular Material but is a custom implementation (nothing fancy, just showing/hiding divs). I guess it's more related to the quill implementation or it might have to do with quill's angular integration.

**Comment by KillerCodeMonkey** [comment]
workaround:

https://stackblitz.com/edit/angular-ngx-quill-tabs-issue-7hi8jj?file=src%2Fapp%2Fapp.component.ts

Just patch the value after the tab has changed
i do nothing special if something is hidden or anything else. Maybe it is a general quilljs issue.
I just take the control value and throw it into the quilljs editor (more or less).

**Comment by KillerCodeMonkey** [comment]
i think it has something todo, that the tab or whatever has its own logic to remove or add the tab content. Maybe there is happening something strange. 

But in my tests using ngIf for hiding and showing the editor or using display: none and block is working fine.

So i would just make sure that the editor is not initialised when it is not visible:

https://stackblitz.com/edit/angular-ngx-quill-tabs-issue-99wbiz?file=src%2Fapp%2Fapp.component.html

**Comment by jpett** [comment]
Thanks @KillerCodeMonkey for your quick response. I see your points and understand why you are not investigating this further.
