### ISSUE TITLE
Image Upload to server

### ISSUE THREAD

**Issue by Mahathmaece** [KillerCodeMonkey/ngx-quill#1116]
Using ngx-quill-upload, Upload image to the server in an angular app. My code is below

this.fileUploadService.uploadFile(formData).pipe(takeUntil(this.destroy$)).subscribe(result => {
          console.log('Text Editor file Uploaded');
}, (error) => {
          console.log('Upload failed'=== error);
});

Image upload successfully to the server. But I'm getting below error

![image](https://user-images.githubusercontent.com/76250385/102689125-c3b97f80-4221-11eb-9720-938df3d20879.png)

**how to resolve this issue?**

**Comment by KillerCodeMonkey** [comment]
This hast totally nothing to so with ngx-quill.

Just read The Error Message and Check your Code abd Calls in ngx-quill-upload line 161.

Seems Like you are using promise then where you do Not have an promise...
