### ISSUE TITLE
Write Custom Module inside of angular

### ISSUE THREAD

**Issue by jdgamble555** [KillerCodeMonkey/ngx-quill#1120]
I am trying to write a custom module like so:

```typescript
import { NgModule } from "@angular/core";
import * as Quill from "quill";
import { QuillModule } from "ngx-quill";
import { ImageDrop } from "quill-image-drop-module";
import ImageResize from "quill-image-resize";


const SyntaxCodeBlock = Quill.import("formats/code-block");

export class CustomSyntaxCode extends SyntaxCodeBlock {

  insertInto(...args: any) {
    console.log("My custom code...");
    super.insertInto(...args);
  }

}

@NgModule({
  imports: [
    QuillModule.forRoot({
      customModules: [
        {
          implementation: ImageDrop,
          path: "modules/ImageDrop",
        },
        {
          implementation: ImageResize,
          path: "modules/ImageResize",
        },
        {
          implementation: CustomSyntaxCode,
          path: "modules/CustomSyntaxCode",
        },
      ],
...
```
Everything works as expected with **ImageResize** and **ImageDrop**, but I get this error when I add the **CustomSyntaxCode** module:

![quill](https://user-images.githubusercontent.com/8333090/103123082-9a955680-4648-11eb-8b09-d0a78c29b50e.png)

Any suggestions?  

**Is it possible to write custom code within Angular like that?**

Thanks,

J

**Comment by KillerCodeMonkey** [comment]
sure, but you are defining a format and not a module. 

If you want to extend SyntaxModule you should create a custom module not a format:
https://github.com/quilljs/quill/blob/e9f628b5562e78126291bb25f63d0dfc3f6c6f86/modules/syntax.js#L168

i transformed the word count module (https://quilljs.com/guides/building-a-custom-module/#counting-words) in my demo repo:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/counter.ts
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/f60296ca4ac5c8bbbc2b4f04f150a24d21b38e84/src/app/app.module.ts#L68

**Comment by jdgamble555** [comment]
Good point.  What I was looking for was this:

```typescript
import { NgModule } from "@angular/core";
import * as Quill from "quill";
import { QuillModule } from "ngx-quill";
import { ImageDrop } from "quill-image-drop-module";
import ImageResize from "quill-image-resize";


const SyntaxCodeBlock = Quill.import("formats/code-block");

export class CustomSyntaxCode extends SyntaxCodeBlock {

  insertInto(...args: any) {
    console.log("My custom code...");
    super.insertInto(...args);
  }

}

Quill.register(CustomSyntaxCode, true);

@NgModule({
  imports: [
    QuillModule.forRoot({
      customModules: [
        {
          implementation: ImageDrop,
          path: "modules/ImageDrop",
        },
        {
          implementation: ImageResize,
          path: "modules/ImageResize",
        },
      ],
...
```
So I had to simply register it instead of declare it as a module...
