### ISSUE TITLE
Cannot rendered video embed URL

### ISSUE THREAD

**Issue by StevRoger** [KillerCodeMonkey/ngx-quill#1129]
Hi, I am using **ngx-quill** version **4.0.0** with my **angular 7 project**. So I want to use the option which is **video embed** so I go to youtube, then copied the embed link, and pasted it to the box. It displays correctly in the text editor but when I get that data back to show on the website. I didn't see anything rendering. Is there anything I have to configure or what? I have tried with the image and it's working fine.

**Comment by KillerCodeMonkey** [comment]
1. i am not supporting that old versions of angular and ngx-quill (check the readme)
2. depends on what you store in your database or wanna show - maybe there are some stylings missing, some cors errors or angular strips the video content. And you do not even share how you try to show the content at all ;-)

**Comment by StevRoger** [comment]
Hi. I also tried with this demo and it seems not to display either.
[https://killercodemonkey.github.io/ngx-quill-example/](Demo)
