### ISSUE TITLE
HTML string fetched from db is not binding all tags are getting stripped

### ISSUE THREAD

**Issue by zen-mind** [KillerCodeMonkey/ngx-quill#1132]
I am using quill editor for comments. After creating formatted comment and saving. I am storing in db. When I bind the comment from db in quiill editor those html tags are getting stripped off. Where as when i bind the text in div tags are coming without fine.
Please help me with configuration how to bind the html string to the editor so that it can be further edited if required

**Comment by KillerCodeMonkey** [comment]
please provide a stackblitz that shows the problem

**Comment by zen-mind** [comment]
https://stackblitz.com/edit/angular-ivy-d8qbnc?file=src/app/app.component.ts

Please find the above link. In the code. If I directly bind the bolded content to the rich text editor. It is showing as plain.

**Comment by KillerCodeMonkey** [comment]
it is getting stripped because of your clipboard matchers

i fixed your example and commented it out: https://stackblitz.com/edit/angular-ivy-p55kmf?file=src%2Fapp%2Fapp.module.ts
