### ISSUE TITLE
quill-view-html is empty in the dialog

### ISSUE THREAD

**Issue by temofey1989** [KillerCodeMonkey/ngx-quill#1133]
Hello,

I've tried to use `<quill-view-html [content]="content"></quill-view-html>` in the dialog. It shows no content.
I've solved the problem with:
```
<div class="ql-container ql-snow" style="border-width: 0;">
  <div class="ql-editor" [innerHTML]="content"></div>
</div>
```
Nevertheless, I don't know what is wrong with it...
Displaying `quill-view-html` on the page is ok.

**Comment by KillerCodeMonkey** [comment]
do you use angular material?

**Comment by temofey1989** [comment]
Yep, I'm using Angular Material...

**Comment by KillerCodeMonkey** [comment]
So in general you should wrap it in an ngIf and make sure that the quill components are rendered after the modal is open or initialised.

Then it should work.

Like listening on ngAfterViewInit and then set a flag that adds the component
