### ISSUE TITLE
setting a custom font as default

### ISSUE THREAD

**Issue by effiko** [KillerCodeMonkey/ngx-quill#1142]
I have a special private font (woff) and need to change the default font to use it. I also need to add it to the font selector on the toolbar

**Comment by KillerCodeMonkey** [comment]
Checkout:
https://quilljs.com/guides/how-to-customize-quill/#customizing-attributors

Code:
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/custom-toolbar

And live example: 
https://killercodemonkey.github.io/ngx-quill-example/ -> search for "Custom Toolbar"

Here you see where i changed everything to register and style custom fonts:
https://github.com/KillerCodeMonkey/ngx-quill-example/search?q=mirza
