### ISSUE TITLE
Unit Testing with Jest & Angular 10: "Uncaught (in promise): Error: Not supported"

### ISSUE THREAD

**Issue by acgrama** [KillerCodeMonkey/ngx-quill#1144]
I cannot unit test a component that uses Quill as I am getting this error:

> Uncaught (in promise): Error: Not supported
    Error: Not supported
>      at QuillService.<anonymous> (projects/ngx-quill/src/lib/quill.service.ts:25:29)

I am configuring Quill like this in my spec.ts file:

```
import { QuillModule } from 'ngx-quill';
...
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ ... ],
      imports: [ ... ],
      providers: [QuillModule.forRoot().providers],
      schemas: [CUSTOM_ELEMENTS_SCHEMA]
    })
    .compileComponents();
    fixture = TestBed.createComponent(...);
    component = fixture.componentInstance;
    fixture.detectChanges();
 }));

```

I am not testing Quill elements; at this point, even a dummy test does not pass because of this error.
If I comment out the `fixture.detectChanges()` line above, the test passes correctly.

Thank you for any suggestions!

**Comment by KillerCodeMonkey** [comment]
sounds like a missing polyfill for promises?

which version of angular and ngx-quill do you use?

my unit tests are running without any problem

**Comment by acgrama** [comment]
Angular 10.0.4, ngx-quill 12.0.1 but updated to 13.0.1. and I am getting the same error.
But is the ngx-quill setup in the spec.ts file ok in principle? 

Thank you for the very fast reaction! :-)

**Comment by KillerCodeMonkey** [comment]
yes it looks fine.

i think maybe it has something todo with your jest config.

maybe you could identify the real cause. i would guess that jest can not handle the `async import` in the service.

**Comment by acgrama** [comment]
Thanks for the suggestions!

**Comment by acgrama** [comment]
Update: your intuition was correct, if the imports are not async, it works!
