### ISSUE TITLE
Systemjs integration example

### ISSUE THREAD

**Issue by 333ashraff333** [KillerCodeMonkey/ngx-quill#1147]
I'm facing issue while rendering quill editor in my project, which I think might be due to some configuration miss with legacy systemjs. https://github.com/KillerCodeMonkey/ngx-quill/issues/4#issuecomment-271809977 shows an example of configuring ngx-quill using systemjs. With the same configuration, latest ngx-quill is throwing error:
![image](https://user-images.githubusercontent.com/70016062/105664437-abacde00-5efa-11eb-8ce3-734323e1fc20.png)

The stack-trace points to importing `quill` using dynamic import statement `import()`.
![image](https://user-images.githubusercontent.com/70016062/105664695-4f968980-5efb-11eb-8241-33f9ef0488da.png)

When I tried to replace it with `require()` it's working fine. I'm not sure if this is a problem with Systemjs loader.

My project is using Angular 11, quilljs 1.3.7, & Systemjs 0.20.10(legacy).

I wanted to know if there's anyway to get it working with the above legacy version of systemjs. If not, will upgrading to latest systemjs or migrating to webpack solve the problem?

**Comment by KillerCodeMonkey** [comment]
i think this will not work with systemjs in latest versions, because of dynamic import.

if your buildtarget is not common js you could try if it is working when you are using the esm2015 or fesm2015 files.

Since i am not supporting systemjs anymore i will close it.
