### ISSUE TITLE
Clipboard matcher dont work

### ISSUE THREAD

**Issue by wiistriker** [KillerCodeMonkey/ngx-quill#1148]
I want to clear all formatted text in clipboard and paste only plain text as described here:
https://github.com/KillerCodeMonkey/ngx-quill/issues/939

I instantiate editor as follow:
`<quill-editor theme="snow" [(ngModel)]="value" (onEditorCreated)="quillEditorCreated($event)" (onFocus)="quillEditorFocused($event)" (onBlur)="quillEditorBlur($event)">`

quillEditorCreated:
`quillEditorCreated(quillEditor)
    {
        this.quillEditor = quillEditor;

        this.quillEditor.clipboard.addMatcher(Node.ELEMENT_NODE, (node, delta) => {
            console.log('Delta ops', delta.ops);

            let ops = [];

            delta.ops.forEach(op => {
                if (op.insert && typeof op.insert === 'string') {
                    ops.push({
                        insert: op.insert
                    });
                }
            });

            delta.ops = ops;

            return delta;
        });
    }`

My method dont even called.
My versions:
"ngx-quill": "^12.0.1",
"quill": "1.3.7",

**Comment by KillerCodeMonkey** [comment]
i think this is more a quilljs thing, because the editor instance is just plain quilljs.
