### ISSUE TITLE
Dynamically inject Component inside Quill Editor

### ISSUE THREAD

**Issue by Frank-The-Tank** [KillerCodeMonkey/ngx-quill#115]
How can you dynamically inject a component into the Quill editor so that it sits inside the text box. How for example could you have a component inside the Quill editor that mimics other text inside the quill editor and changes dynamically as you type new text? 

In other words I can easily put the quill component inside another component but how can I but another component inside the quill component? **How could I put the DOM elements of another component directly in the text box of the quill component?**

**Comment by KillerCodeMonkey** [comment]
This is not possible.

Keep in mind --> this is only a wrapper of the standard QuillJS editor.
You could add native Dom-Elements. 
Like your model or formControl is a HTML-String you could manipulate this and the editor will try to render it. 

But you have to do the work to use ViewContainer, to create components and put the native htmlcontent as string to the ngx-quill component as model or form control.

**Comment by toniengelhardt** [comment]
@Frank-The-Tank did you manage by now implement something like that? I'm trying to do the same...

**Comment by Frank-The-Tank** [comment]
Hey @toniengelhardt we actually ended up using a different work around inside our project instead of actually injecting a component into the Quill editor so no sorry :(
