### ISSUE TITLE
Question - How to toggle html/rich text?

### ISSUE THREAD

**Issue by joshi-anshul** [KillerCodeMonkey/ngx-quill#1154]
Hi @KillerCodeMonkey 

Could you please let me know that how can I add toggle html/rich text functionality? I have checked all exampled but not able to found this functional.

I want a button, so on click that button editor should show HTML and then again click it should change to normal text editor.
Thanks

**Comment by KillerCodeMonkey** [comment]
this is just a wrapper of quilljs.

if you find something there about such a toggle it is possible. if not... well then not :D.

In general i would avoid such things, because quilljs only allows known formats (tags + attributes), so the user will definitely not see what he expect :)

**Comment by joshi-anshul** [comment]
Thanks for the response.

also, is there any way to add image same as video, mean using URL? I don't want to select image from local, i just want image option same as video link?

**Comment by KillerCodeMonkey** [comment]
same answer: check quilljs documentation and repo issues. Maybe there is a plugin :)

**Comment by KillerCodeMonkey** [comment]
https://github.com/quilljs/quill/issues/2044#issuecomment-603630374

**Comment by joshi-anshul** [comment]
:) Ok, thanks
