### ISSUE TITLE
ERROR in The target entry-point "ngx-quill" has missing dependencies:  - quill

### ISSUE THREAD

**Issue by erqk** [KillerCodeMonkey/ngx-quill#1159]
I cannot get it running on my angular project...
My angular version is 10.0.8

**Comment by KillerCodeMonkey** [comment]
then follow the instructions (readme and error message) and install quill 1.3.7 and the fitting typings @types/quill 1.3.10

**Comment by erqk** [comment]
I see! sorry for my noob question.
