### ISSUE TITLE
Add onCreated event to quill-views

### ISSUE THREAD

**Issue by Yexan** [KillerCodeMonkey/ngx-quill#1165]
Hi Bengt, 

On my current project I need a `onCreated` method on `quill-view` component returning the event containing the quill object like we got with the `quill-editor` component.
I could make a fork of the project but I think it might be useful to other people as it's similar to quill-editors.

It's not an issue but more of an addition. What do you think about it? 

Have a great day!

**Comment by KillerCodeMonkey** [comment]
PRs and useful additions are always welcome :)

maybe you can reuse the naming of the editor-component.

Like `onEditorCreated`, thx!

**Comment by Yexan** [comment]
Thanks for allowing this addition! 🥳 🙏
