### ISSUE TITLE
Angular Quill issue in angular 11 project

### ISSUE THREAD

**Issue by poojaTheottercoders** [KillerCodeMonkey/ngx-quill#1169]
When we established Angular-Quill and Quill in the Angular 11 project, we saw sharp differences related to Quill's node-module and errors.
Quill node-module quill-delta in the dist folder delta.d.ts. We add * to import spacing faster
And in the quill-editor-component.ts file we add @ts-ignore to the delta import

**Comment by KillerCodeMonkey** [comment]
and you have installed the correct typings and quill version? types should be 1.3.10 so the major versions of quill and the typings should match

**Comment by dimeloper** [comment]
@poojaTheottercoders same issue here. Downgrading the typings version fixed it for me. 🎉
