### ISSUE TITLE
Add custom component to toolbar module

### ISSUE THREAD

**Issue by Frank-The-Tank** [KillerCodeMonkey/ngx-quill#117]
How can I add a custom element to the module toolbar that displays the DOM elements in another component? 
```
this.modules = {
    	toolbar: {
        container:
        [
            ['formula'],
            [{'indent': '-1'}, {'indent': '+1'}],
            [{ 'placeholder': ['[GuestName]', '[HotelName]'] }], // custom dropdown
        ],
        handlers: {
            "placeholder": function (value) {
                if (value) {
                    const cursorPosition = this.quill.getSelection().index;
                    this.quill.insertText(cursorPosition, value);
                    this.quill.setSelection(cursorPosition + value.length);
                }
            }
        }
      }
    };
  }
```

Or how can I add sections to my current 'placeholder' dropdown? Right now it shows a dropdown with no values in it: 

![screen shot 2018-02-22 at 5 00 29 pm](https://user-images.githubusercontent.com/10601523/36572669-f93bf276-17f1-11e8-8771-66e8f6076755.png)

Also, how can I force the selection to open whenever enter is pressed so that users can then pick an option with the arrow keys, and then click enter again to cause more formating to happen below?

For reference I used this as inspiration: https://jsfiddle.net/q7jferw3/

**Comment by KillerCodeMonkey** [comment]
Do not know? Add something to the toolbar and check if it is working. :)

Am 23.02.2018 01:17 schrieb "Frank" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
You need to add all javavscript to get it working:

```
  // We need to manually supply the HTML content of our custom dropdown list
   const placeholderPickerItems = Array.prototype.slice.call(document.querySelectorAll('.ql-placeholder .ql-picker-item'));

  placeholderPickerItems.forEach(item => item.textContent = item.dataset.value);

  document.querySelector('.ql-placeholder .ql-picker-label').innerHTML = 'Insert placeholder' + document.querySelector('.ql-placeholder .ql-picker-label').innerHTML;
```

**Comment by KillerCodeMonkey** [comment]
@Frank-The-Tank any updates?

**Comment by Frank-The-Tank** [comment]
Hey I just got back from vacation I will work on implementing this today. Where should i include the java script in an angular setup?
