### ISSUE TITLE
Material Quill

### ISSUE THREAD

**Issue by 123NeNaD** [KillerCodeMonkey/ngx-quill#1170]
Hi, how to style Quill to look like **Material Quill** in your example here:  **https://killercodemonkey.github.io/ngx-quill-example/**

**Comment by KillerCodeMonkey** [comment]
just checkout the repo of it: https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/styles.scss#L48

**Comment by 123NeNaD** [comment]
Thanks
