### ISSUE TITLE
ReferenceError: document is not defined - Angular universal

### ISSUE THREAD

**Issue by sisindrymedagam** [KillerCodeMonkey/ngx-quill#1172]
Hello @KillerCodeMonkey , I'm using ngx-quill with Angular Universal but it's not working.

My server log shows 

![Screenshot](https://user-images.githubusercontent.com/24821639/108408240-cf89e800-724a-11eb-8ab4-6f6c08350783.jpg)

Here are my dependencies
```json
"dependencies": {
    "@angular/animations": "~11.0.5",
    "@angular/common": "~11.0.5",
    "@angular/compiler": "~11.0.5",
    "@angular/core": "~11.0.5",
    "@angular/forms": "~11.0.5",
    "@angular/platform-browser": "~11.0.5",
    "@angular/platform-browser-dynamic": "~11.0.5",
    "@angular/platform-server": "~11.0.5",
    "@angular/router": "~11.0.5",
    "@nguniversal/express-engine": "^11.0.1",
    "express": "^4.15.2",
    "express-rate-limit": "^5.2.3",
    "localstorage-polyfill": "^1.0.1",
    "ngx-infinite-scroll": "^10.0.1",
    "ngx-quill": "^13.2.0",
    "quill": "^1.3.7",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.3",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.5",
    "@angular/cli": "~11.0.5",
    "@angular/compiler-cli": "~11.0.5",
    "@angular/language-service": "~11.0.5",
    "@nguniversal/builders": "^11.0.1",
    "@types/express": "^4.17.9",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.19.9",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "^6.1.3",
    "typescript": "^4.0.5"
  }
```

I have set `suppressGlobalRegisterWarning: true` in app.module.ts

```ts
imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
    FormsModule,
    QuillModule.forRoot({
      suppressGlobalRegisterWarning: true
    })
]
```

I don't know what went wrong, please help...

**Comment by KillerCodeMonkey** [comment]
If you have an Import of quilljs somewhere in Your Code you Need to Mock
The document Object when it IS SSR.

Check The readme and The Info for angular Universal + angular 9.

If you are Registering modules and Options Checkout The customModules and
customFormats Inputs.


Am 18.02.2021 in 20:22, sisindry medagam <notifications@github.com>
schrieb:

Hello @KillerCodeMonkey <https://github.com/KillerCodeMonkey> , I'm using
ngx-quill with Angular Universal but it's not working.

My server log shows

[image: Screenshot]
<https://user-images.githubusercontent.com/24821639/108408240-cf89e800-724a-11eb-8ab4-6f6c08350783.jpg>

Here are my dependencies

"dependencies": {
    "@angular/animations": "~11.0.5",
    "@angular/common": "~11.0.5",
    "@angular/compiler": "~11.0.5",
    "@angular/core": "~11.0.5",
    "@angular/forms": "~11.0.5",
    "@angular/platform-browser": "~11.0.5",
    "@angular/platform-browser-dynamic": "~11.0.5",
    "@angular/platform-server": "~11.0.5",
    "@angular/router": "~11.0.5",
    "@nguniversal/express-engine": "^11.0.1",
    "express": "^4.15.2",
    "express-rate-limit": "^5.2.3",
    "localstorage-polyfill": "^1.0.1",
    "ngx-infinite-scroll": "^10.0.1",
    "ngx-quill": "^13.2.0",
    "quill": "^1.3.7",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.3",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.5",
    "@angular/cli": "~11.0.5",
    "@angular/compiler-cli": "~11.0.5",
    "@angular/language-service": "~11.0.5",
    "@nguniversal/builders": "^11.0.1",
    "@types/express": "^4.17.9",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.19.9",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "^6.1.3",
    "typescript": "^4.0.5"
  }

I have set suppressGlobalRegisterWarning: true in app.module.ts

imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
    FormsModule,
    QuillModule.forRoot({
      suppressGlobalRegisterWarning: true
    })]

I don't know what went wrong, please help...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/1172>, or unsubscribe

**Comment by sisindrymedagam** [comment]
Got it, I have used `domino` in my server.ts. It's working like a charm 😉.

Thanks

**Comment by yogeshbansal** [comment]
Hi @sisindrymedagam and @KillerCodeMonkey 

I am trying to register the image resize module in Angular 14 + angular universal + ngx-quill, but it's giving me the document is undefined. Could you please share a code snippet, if any one of you has tried to register an external module?
I checked @KillerCodeMonkey  angular universal project it does not have a sample of external module registration
