### ISSUE TITLE
Inline style quill editor

### ISSUE THREAD

**Issue by wawahuy** [KillerCodeMonkey/ngx-quill#1174]
![image](https://user-images.githubusercontent.com/16779694/108488511-0c012680-72d3-11eb-82c7-6aca4b35fae8.png)
![image](https://user-images.githubusercontent.com/16779694/108488594-263b0480-72d3-11eb-9637-f46d0bf59e9b.png)
Can I convert li, ul, ol to inline style eg
![image](https://user-images.githubusercontent.com/16779694/108489020-a7929700-72d3-11eb-8faa-1a0d3fe1053e.png)

**Comment by KillerCodeMonkey** [comment]
Just search through quilljs repository. There is a bunch of similar questions.

In The quilljs Homepage is some little example how to Switch from classbased to Inline Styling.

https://quilljs.com/playground/#class-vs-inline-style
