### ISSUE TITLE
Quill not being rendered in Angular 11 project

### ISSUE THREAD

**Issue by kryogenyk** [KillerCodeMonkey/ngx-quill#1179]
I have issues regarding displaying quill in an Angular 11 project.

I have the following packages installed (ctrl + f in my package-lock.json file)
@types/quill: 1.3.10
ngx-quill: 13.2.0
quill: 1.3.7
quill-delta: 3.6.3

I have imported QuillModule.forRoot() in my app.module.ts, and used quill in my html with the default html from the example repo (ngx-quill-example):
<quill-editor [styles]="{height: '200px'}" (onFocus)="focus($event)" (onEditorChanged)="changedEditor($event)"
        (onBlur)="blur($event)" (onEditorCreated)="created($event)"></quill-editor>

The events do not fire at all, and the DOM only contains this:
![image](https://user-images.githubusercontent.com/9081225/108702977-a7cca580-7512-11eb-8b4c-e27a9aa2a163.png)

The height and width are both set to 100%. 

The stylings are added in styles.scss, as in the documentation.

**Comment by KillerCodeMonkey** [comment]
since it is working in the demo repo i think you are doing something wrong. could you create a stackblitz for it?

And did you checked your JS-Console of the browser? Maybe you have a js error somewhere in your project.

**Comment by kryogenyk** [comment]
I had no errors in the JS console, yet I found something in the output of VSCode:
![image](https://user-images.githubusercontent.com/9081225/108704352-8d93c700-7514-11eb-91fe-9126f4a8cbe6.png)

I removed the event listeners from html, yet nothing seems to change, except that the errors have disappeared from output.

I created a stackblitz, and there's an error, too.

_Error in /turbo_modules/ngx-quill@13.2.0/bundles/ngx-quill.umd.js (418:29)_

**Comment by KillerCodeMonkey** [comment]
your stackblitz is inavlid.. you are using angular 5 there...

**Comment by kryogenyk** [comment]
You're right, sorry! This was the first time I created a stackblitz by myself.

[Here's another working one, with Angular 11](https://stackblitz.com/edit/angular-7taovk?file=src/app/app.component.html).

I also found the problem: I imported QuillModule in the wrong place, as it used in a lazily loaded child module. Moved it from app module to the other one, and now it works! Thanks!

**Comment by XxQuickSilverZz** [comment]
@kryogenyk Can you tell me exactly what you did? I also use Lazy Modules and I've been trying for days....

**Comment by kryogenyk** [comment]
I have a SharedModule which is imported in the AppModule, and there i imported QuillModule.forRoot().
But in any case, importing QuillModule.forRoot() in app.module.ts should work.

**Comment by XxQuickSilverZz** [comment]
@kryogenyk i try it like your step. But when i only import QuillModule.forRoot() in app.module.ts he tell me 'quill-editor' is not a known element. I need to export it?

**Comment by kryogenyk** [comment]
Maybe install quill like this? 
`npm i ngx-quill --save`

Does that help?

**Comment by XxQuickSilverZz** [comment]
"@types/quill": "^1.3.7",
   "ngx-quill": "^13.2.0",
   "quill": "^1.3.7",
 "peerDependencies": {
    "quill": "^1.3.7",
    "rxjs": "^6.5.0"
  }

How your´s look? angular.json has nothing with quill. only styles.scss has 
@import "~quill/dist/quill.core.css";
@import "~quill/dist/quill.bubble.css";
@import "~quill/dist/quill.snow.css";

**Comment by XxQuickSilverZz** [comment]
@kryogenyk 

"@types/quill": "^1.3.7",
"ngx-quill": "^13.2.0",
"quill": "^1.3.7",
"peerDependencies": {
"quill": "^1.3.7",
"rxjs": "^6.5.0"
}

How your´s look? angular.json has nothing with quill. only styles.scss has
@import "~quill/dist/quill.core.css";
@import "~quill/dist/quill.bubble.css";
@import "~quill/dist/quill.snow.css";

**Comment by kryogenyk** [comment]
Only `"@types/quill":` "^1.3.10" is different in my package.json file.

Try creating a stackblitz with your specs and see what's different from your project. There is also one above in this comment thread, made by me. It has the same package versions as my local project.

**Comment by XxQuickSilverZz** [comment]
@kryogenyk You not touched your Child Lazy Module ? Your Stackblitz has no  Child Lazy Module.

**Comment by kryogenyk** [comment]
Yes, it does not have.

So I have a shared module that is imported in my app module.
Then I got another 3 child modules, where I import that shared module, aswell.

**Comment by XxQuickSilverZz** [comment]
@kryogenyk But if you import the module in app.module.ts then each module has the elements inside if they are needed or not? I thought the SharedModule is a package only for child modules

**Comment by kryogenyk** [comment]
No, SharedModule is just a module which I use to keep my AppModule clean (only for external modules).

**Comment by XxQuickSilverZz** [comment]
@kryogenyk Do you have a Stackblitz example with Child Modules? I've been trying to find the problem for 3 days now..

**Comment by kryogenyk** [comment]
I'll make one tonight, after work. Please remind me in 3.5 hours.

**Comment by XxQuickSilverZz** [comment]
@kryogenyk Thanks. I will do

**Comment by XxQuickSilverZz** [comment]
@kryogenyk reminder my friend :)

**Comment by sergeyglazyrindev** [comment]
@KillerCodeMonkey 
hey guys...
Any idea why none of the tags are rendered in my angular 10 project.
