### ISSUE TITLE
custom toolbar alignment

### ISSUE THREAD

**Issue by gonzoRay** [KillerCodeMonkey/ngx-quill#118]
Hi, we're using your component and we're really appreciating the ability to easily customize the toolbar. Our design team (for some reason) is asking for the toolbar to appear at the bottom of the text input area. Is there currently an easy way to accomplish this? I was able to get it to appear this way by placing the custom toolbar div outside the `<quill-editor>` tag but when the data is bound (using reactive forms) the 2nd instance of the toolbar is not rendered properly (styles not applied). TIA for any guidance.

**Comment by KillerCodeMonkey** [comment]
Öhhm i am not that CSS guru, but maybe you can achieve this by overwriting
quill CSS or something like this. Giving the toolbar flex-end and the
editor flex-start. Our positonate the toolbar absolutely

Am 23.02.2018 19:55 schrieb "gonzoRay" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
@gonzoRay any updates?

**Comment by gonzoRay** [comment]
Thank you for the quick response. I'm going to pass the information along to our CSS wizard and see if he is able to work his magic. I was just looking for a quick fix or a hidden feature but no problem. Please feel free to close this issue. Also thank you for the great component!

**Comment by KillerCodeMonkey** [comment]
@gonzoRay push :) ?!

**Comment by KillerCodeMonkey** [comment]
closed due to inactivity. feel free to comment your solution/problems if needed
