### ISSUE TITLE
Extra div and br added before list 

### ISSUE THREAD

**Issue by rekhubs** [KillerCodeMonkey/ngx-quill#1186]
We are using **html output format**. Usually we need to edit the same content multiple times.
When the saved content is loaded, an extra `div` (and a `br` inside it) is added before list, so will have to manually delete the extra line every time we save the new edits, or the gap between will keep growing wider.

Same behavior happeing on the demo site as well:
https://killercodemonkey.github.io/ngx-quill-example/

![210303-091803-MOR3Ra](https://user-images.githubusercontent.com/5567035/109710423-8484b300-7c02-11eb-9a57-2d9d589ad9c9.gif)

**Comment by KillerCodeMonkey** [comment]
i think this is quilljs issue. I just use the quilljs api to transform the content :S. So i think you should ask this there.

**Comment by KillerCodeMonkey** [comment]
but you can try to set `matchVisual: false` for the clipboard module:
https://jsfiddle.net/DmitrySkripkin/pjgc5zws/

**Comment by rekhubs** [comment]
> but you can try to set `matchVisual: false` for the clipboard module:
> https://jsfiddle.net/DmitrySkripkin/pjgc5zws/

Thank you, Bengt! just tried `matchVisual` option, I think that's the feasible solution for us for now.
