### ISSUE TITLE
Angular (10+) with ngx-quill - content loaded event

### ISSUE THREAD

**Issue by Lertis** [KillerCodeMonkey/ngx-quill#1187]
Hello, everyone!

I use ngx-quill with Angular 10. I found an onEditorCreated event that will inform me that content has been loaded/created.

I insert a long text into the quill and it's thinking for a while (~15s). And only then load already rendered content. Before initialization - I'm still waiting. I'm looking for a good approach to how can I render a quill and only then insert data?

I have an idea that after the first initialization editor isn't destroyed.

Here is a text:  [text.txt](https://github.com/KillerCodeMonkey/ngx-quill/files/6076443/text.txt)

**Comment by KillerCodeMonkey** [comment]
you could just init the editor without the content.

listen onEditorCreated -> set the value and listen to the change event.
for example when you are using ngModel -> init the model with empty string and set your long text on the model after the editor is created (show loading spinner or what ever).

**Comment by Lertis** [comment]
@KillerCodeMonkey as we did after trying to resolve an issue. Thanks for the reply!)

**Comment by KillerCodeMonkey** [comment]
i see no other solution for your problem. sadly wysiwyg editors are really slow when working with huge contents.
