### ISSUE TITLE
Highlighting issue

### ISSUE THREAD

**Issue by AlexanderM-dev** [KillerCodeMonkey/ngx-quill#1194]
Hello! Sorry for my bad english

When we using highlight.js for highlighting code block in Quill editor - it adds hljs CSS classes for html, so we see beauty colored code:
- example input string:
"let x = 100"
- example output html: 
"< pre class="ql-syntax" spellcheck="false">< span class="hljs-keyword">let</ span> x = < span class="hljs-number">100 < /span></ pre >"

But, Quill form **VALUE** will be updated with this classes only if i will push any button in input **AFTER** highlight.js detect code and add classes. 
If i wont push any button after highlight.js detect code and add classes - Quill form VALUE will not be updated with hljs classes: "< pre class="ql-syntax" spellcheck="false">let x = 100</ pre>" and it will not be highlighted.

It is a problem with Quill editor? Can we fix it?

**Comment by KillerCodeMonkey** [comment]
maybe ask this at quilljs repository?

and please create stackblitz or codepens so maintainers can easy reproduce the issue ;-)

**Comment by KillerCodeMonkey** [comment]
i will close due to inactivity. 

in general you can find a highlightjs example with ngx-quill in the demo repo. it is working there while typing.

**Comment by AlexanderM-dev** [comment]
In your demo there is no Div with innerHtml or <quill-view-html> that i am using... So u cant see that problem

If that issue interesting to you - You can add **BUTTON** to log quill form value (in my project `this.quillForm.get('content')?.value`) and u will see what i am talking about: 
- just copy and paste "let x = 100" into code block _(dont type any button in quill input after paste code)_
- wait untill HLJS will add classes 
- then push this **BUTTON** with log value
