### ISSUE TITLE
Update rxjs to release version (^5.0.1)

### ISSUE THREAD

**Issue by rgajam** [KillerCodeMonkey/ngx-quill#12]
Can you please update rxjs version to ^5.0.1 to be able to work latest versions of angular which require rxjs ^5.0.1?
Thanks!

**Comment by KillerCodeMonkey** [comment]
DO you mean v5.1.0? There is no 5.0.1...

**Comment by KillerCodeMonkey** [comment]
changed with v0.3.2

**Comment by rgajam** [comment]
Thank you very much @KillerCodeMonkey ! 💯

**Comment by KillerCodeMonkey** [comment]
i release v0.3.3 with quilljs 1.2.0 because of many fixes :)
