### ISSUE TITLE
beyond-grammar with ngx-quill

### ISSUE THREAD

**Issue by hannan665** [KillerCodeMonkey/ngx-quill#1205]
can we use beyond grammar with ngx-quill? @KillerCodeMonkey

**Comment by KillerCodeMonkey** [comment]
what is beyond grammar? if it is working with quilljs it will work with ngx-quill

**Comment by hannan665** [comment]
its like a dictionary or spell checker. @KillerCodeMonkey

**Comment by hannan665** [comment]
i have implemented it with quilljs but not able to do with ngx-quill.

**Comment by KillerCodeMonkey** [comment]
I only know that Browser Extensions Like grammarly lead to some Problems with quilljs and ngx-quill.

If you got IT working with plain quilljs, IT should work with ngx-quill The Sand way.
