### ISSUE TITLE
customise quill-mention-list

### ISSUE THREAD

**Issue by binal-chovatiya** [KillerCodeMonkey/ngx-quill#1206]
How can we add customise quill-mention-list  with id ,values parameters? @KillerCodeMonkey

**Comment by KillerCodeMonkey** [comment]
That is Not really a ngx-quill issue.

But maybe The Demo repo helps:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/mention/mention.component.ts#L24
