### ISSUE TITLE
Option to debounce textChangeHandler

### ISSUE THREAD

**Issue by kdaniel21** [KillerCodeMonkey/ngx-quill#1217]
Hi! 👋

With @st3h3n we're experiencing performance problems while using the editor with somewhat large (>3-4MiB) images and content. As far as we've seen the underlying cause for this is that the internal `editorChangeHandler` runs for every single keystroke, which occupies resources and makes typing not particularly smooth.

As far as we've seen debouncing this method (or Quill's `emit` that triggers it) could help to improve performance significantly. What would you think about such feature?

PS: Congratulations for maintaining the library and for the 0 (technically, now 1) active issue(s).

**Comment by KillerCodeMonkey** [comment]
In general i do not have anything against it, but when you are using angular FormControls and models it would do the same on every key stroke. So it is a little bit hard to decide what to do with that.

First of all, i would assume that you have an optimized image upload handling (not storing base64 directly in the content).

**Comment by kdaniel21** [comment]
Right now we're just storing the images as base64 strings, still, we believe that the issue persists when having an equally big amount of text as well (which can be considered an edge).

Regarding the `FormControls`: isn't it somehow possible to debounce that as well? If not, then as a last resort falling back to `onContentChanged` and writing a debounced wrapper around that could be a viable option as well. What do you think?

**Comment by KillerCodeMonkey** [comment]
you could use rxjs to debounce the formControls valueChange subscription.
https://www.tektutorialshub.com/angular/debouncetime-debounce-in-angular/#debounce-example

I do not like to build tooo much magic around the native quilljs behaviour.

If you like you can try to create a PR with some debounce logic:
Or another idea from my side: to deactivate the all change-outputs at all? So you would just use the formControl and use formControl.valueChanges.pipe(debounce(...)).subscribe() to get notified for changes?

**Comment by kdaniel21** [comment]
We're using rxjs to debounce the `valueChange` property on our form, still, the problem remains as the underlying `textChangeHandler` (which triggers `onModelChange`) runs for every keystroke regardless of what we do with the form value. And this `textChangeHandler` is what we'd want to debounce (in my initial comment I wrote `editorChangeHandler` but it should have been `textChangeHandler` - `editorChangeHandler` doesn't seem to be connected to the value accessor), as this is an expensive operation if dealing with large deltas.

**Comment by KillerCodeMonkey** [comment]
yeah, but like i said: feel free to create a pr for that if you need it :)

**Comment by kdaniel21** [comment]
Sure, we'll work something out in the coming days, just wanted to make sure that we're on the same page about what the issue is.
