### ISSUE TITLE
Class on input focus 

### ISSUE THREAD

**Issue by shyamal890** [KillerCodeMonkey/ngx-quill#122]
For bubble theme how to set class on input focus/active?

**Comment by KillerCodeMonkey** [comment]
if you click in the editor / focus the editor OnSelectionChanged event is fired with `oldRange = null`.

After that add a custom css to the quill-editor which styles something like this:

CSS
```
quill-editor.active ql-editor {
   ...
}
```

HTML
```
<quill-editor ... (onSelectionChanged)="handleSelectionChanged($event)" [ngClass]="{active: hasFocus}"></quill-editor>
```

TS
```
@Component({})
class XXXX {
  hasFocs = false;
  
  ...
  
  handleSelectionChanged(data: any) {
    // range is set --> you are inside of the editor
    if (data.range) {
      this.hasFocus = true;
    } else {
      this.hasFocus = false;
    }
  }
}
```

I did not tested this code... so maybe there are some things wrong. But i think you can get the idea what to do
