### ISSUE TITLE
Pre-loading quill

### ISSUE THREAD

**Issue by jeserkin** [KillerCodeMonkey/ngx-quill#1221]
I am having a bit of an issue with my component. It initially is not in DOM (`*ngIf`), but once it comes into view it renders `quill-editor` component and therefore creates editor instance, which in turn import Quill `const quillImport = yield import('quill');`

When all of it happens, then there is small time amount (milliseconds), when component has some ugly buttons. Basically something like this
![image](https://user-images.githubusercontent.com/183512/115494925-3f2e4a80-a26f-11eb-98fe-b4706f98895a.png)

So my question is: "Is it possible to pre-load/pre-create/pre-import quill, prior to it rendering?"

Thank you in advance.

**Comment by KillerCodeMonkey** [comment]
you could preload it by your self or instead of ngIf just set the style display: none?

it is loaded async to not break on server side rendering
