### ISSUE TITLE
Not Supporting angular 11 version

### ISSUE THREAD

**Issue by 9491340980** [KillerCodeMonkey/ngx-quill#1223]
Hi 

Getting below when i trying use ngx-quill in angular 11...

![image](https://user-images.githubusercontent.com/19782563/115826039-efdf4a00-a427-11eb-9aa8-fca66869187e.png)

**Comment by KillerCodeMonkey** [comment]
dude, just read the error message... you are using image-resize, but you have not registered it. that has nothing to do with ngx-quill-

just check the demo repo linked in the readme. there you find examples of many usecases... registering modules and even using image resize.
