### ISSUE TITLE
Unable to use text-decoration: underline and text-decoration: line-through (report from quilljs) and other stuff

### ISSUE THREAD

**Issue by OlivierBeaud** [KillerCodeMonkey/ngx-quill#1229]
Hi,
I encounter a problem when filling ngx-quill with html data i receive from database.
some decoration like style="text-decoration: line-through; or underline are not suported nor font-size

here is the issue for the patch with quilljs for text-decoration :
https://github.com/quilljs/quill/pull/3149/commits/493402a5c0735b3321b2e3f4686c41f3798efc0f

thanks by advance

**Comment by KillerCodeMonkey** [comment]
and what should i do here, when it is a known quilljs bug?

**Comment by KillerCodeMonkey** [comment]
since i am using quilljs and have no custom implementation for that. But quilljs does not released a version for their changes ;-)
