### ISSUE TITLE
How do you get the caret position?

### ISSUE THREAD

**Issue by nimabrownlee** [KillerCodeMonkey/ngx-quill#1232]
I've searched the documentation and haven't found any solution. 

`(onSelectionChanged)` does not fulfill my needs, because it only works if the user changes it's caret position using the mouse. I want the caret position even when using enter and space too.

I know Quill supports this by using [getSelection](https://quilljs.com/docs/api/#getselection). Is that something this library supports?

**Comment by KillerCodeMonkey** [comment]
just grab the quilljs instance from onEditorCreated and for each change
call the native quilljs api function you need.

Am Mo., 3. Mai 2021 um 10:14 Uhr schrieb nimabrownlee <
***@***.***>:

**Comment by nimabrownlee** [comment]
@KillerCodeMonkey Thanks dude! 2 unrelated questions:

1. Can you change the link placeholder? There is `[linkPlaceholder]` but I am not sure where to put it.
2. The quill-emoji module is old and very buggy. Do you recommend any specific way, how someone could make their own custom module and add it. I have had it difficult finding any documentation on this.

**Comment by KillerCodeMonkey** [comment]
the linkPlaceholder was added by a contributor. never used it^^.

i would guess just add <quill-editor [linkPlaceholder]="'my placeholder'">

to the second one -> just checkout other custom modules like quill emoji or
base quilljs modules like link or image.

Am Mo., 3. Mai 2021 um 12:57 Uhr schrieb nimabrownlee <
***@***.***>:

**Comment by nimabrownlee** [comment]
@KillerCodeMonkey That doesn't work sadly. Also it's missing in the typescript types. My original issue is solved so I'll close it. Thanks!
