### ISSUE TITLE
How do i extend my own Typescript theme from BaseTheme and BaseTooltip?

### ISSUE THREAD

**Issue by jwjuele** [KillerCodeMonkey/ngx-quill#1233]
Hey, i'm currently trying to create my own custom javascript theme based on the quill BaseTheme and BaseTooltip in an angular environment.

I just copied the existing SnowTheme from the quill repository and slightly migrated it for typescript to compile.
I double checked my imports and did not overwrite any values but i guess i noticed a bug here.

When i use "my-wysiwyg-theme" i can not click on links in the editor to open the tooltip and url editor anymore.
https://stackblitz.com/edit/angular-ivy-etchfy?file=src%2Fapp%2FMyWysiwygTheme.ts

It's usually opened by the snow tooltip which gets triggered on "Emitter.events.SELECTION_CHANGE," in:
MyWysiwygTheme.ts:123
but only if the descendant is of Type LinkBlot. Unfortunately this condition fails and at this point i cant find out why.

Do you have an idea, what i'm doing wrong here?

Thanks in advance!

**Comment by KillerCodeMonkey** [comment]
puh sadly i have no idea. never built something like that on my own. Sounds like a stack overfow. what i know in general:
you should avoid angular click listeners in the toolbar html. Quilljs is using this html to add all its magic and everything is then executed outside of the angular context.

Just try to use native document.addEventListeners to your buttons.
Maybe this does the trick.

**Comment by jwjuele** [comment]
So far my listeners work finde here. Already build other modules and even the link can get triggered that way. Just doesn't work inside the editor itself.
Thanks anyway!
