### ISSUE TITLE
selection-change event does not count html code

### ISSUE THREAD

**Issue by nimabrownlee** [KillerCodeMonkey/ngx-quill#1234]
I had opened an issue about how to get the caret position: https://github.com/KillerCodeMonkey/ngx-quill/issues/1232
I followed what KillerCodeMonkey said and it works perfectly fine. There is just one problem. It doesn't count the html code as part of the index. If I select this in the formatter: `<p>hi</p> ` then I will get `{ index: 0, length: 2 }`. Which is "hi". Now this probably works as expected. But how would I insert text/html before/after "hi". Because now it cuts the html. Index 2 is <p. Not after hi.

Quill has getContents and setContents. But I don't think library supports it because of Angular.
https://codepen.io/DmitrySkripkin/pen/yPEzbE?editors=1111

Any help is appreciated.

**Comment by KillerCodeMonkey** [comment]
i just provide a wrapper of the native quilljs selection-change event.

But if you need access to the native quilljs api, just grab the instance from the onEditorCreated output.
As $event you get the quill editor instance and so you have full access to the editor ;-).

Greets and hope that helps

**Comment by nimabrownlee** [comment]
@KillerCodeMonkey Hey, I found a solution. So I got the quill instance from `quillEditor` and use that insert the text using the function `insertText`. There is just one slight problem. Angular does not know about the changes because its through the DOM. Do you recommend any specific way to fix this?

**Comment by KillerCodeMonkey** [comment]
use ChangeDetectorRef to manually trigger change detection or mark your component for changes?

**Comment by nimabrownlee** [comment]
@KillerCodeMonkey I have tried that but sadly it doesn't work.

**Comment by KillerCodeMonkey** [comment]
then grab the new content by quill api and set it on your formControl or
ngModel

Am Mi., 5. Mai 2021 um 15:28 Uhr schrieb nimabrownlee <
***@***.***>:
