### ISSUE TITLE
Add option to sanitise HTML in QuillViewHTMLComponent

### ISSUE THREAD

**Issue by rajeshwarkohli** [KillerCodeMonkey/ngx-quill#1235]
Hi 👋 

Both QuillEditorComponent and QuillViewComponent have an option for HTML sanitation unlike QuillViewHTMLComponent. Angular's DomSanitizer can be used before passing it to `content` parameter, but would be nicer to have `sanitise` input parameter available.

It's not an issue, but more of an addition. What do you think about it?

**Comment by KillerCodeMonkey** [comment]
just send me a pr ;-)

Am Mi., 5. Mai 2021 um 08:51 Uhr schrieb Rajeshwar ***@***.***
