### ISSUE TITLE
How to add custom Blots on SSR with angular universal

### ISSUE THREAD

**Issue by jwjuele** [KillerCodeMonkey/ngx-quill#1238]
Hey! Me again ;)

I'm currently trying to register my custom blot classes while i'm using angular universal.
The Readme file says, that there is no further action required for ssr. Has it been tested with custom blots?
I already created a replacement for the QuillModule itself, by adding a fake value to the providers inside an AppServerModule.

```

@NgModule({
    imports: [
        AppModule,
        ServerModule,
        ServerTransferStateModule,
    ],
    bootstrap: [AppComponent],
    providers: [
        { provide: QuillModule, useClass: MyQuillServerModule },
    ],
})
export class AppServerModule {}
```

Unfortunately this does not prevent the synchronous load of dependencies which are passed to my `.forRoot(config)`.
In there, i have my customModules which themeselves extends a class imported from 'quill'.

```
import * as Quill from 'quill'
const Embed = Quill.import('blots/embed');
              ___________________________

export class MyCustomBlot extends Embed {
    // ...
```

Of course initially i have to avoid importing 'quill' here, since `window`, `document` etc. are not defined during SSR of angular universal. My Blot class is not created in context of an Injectable - so i can not call `QuillService.getQuill()` from ngx-quill.

Is there a way to solve this?

Thanks in advance!

**Comment by jwjuele** [comment]
I somehow created a working Frankenstein here... but i'm not happy 😆 

```
let MyQuillImageBlot: any;

function createMyQuillImageBlotClass(Embed: any) {
    if(!Embed || MyQuillImageBlot) {
        return MyQuillImageBlot;
    }
    
    MyQuillImageBlot = class MyQuillImageBlot extends Embed {
        // ...
    }

    return MyQuillImageBlot;
}

@NgModule({
    imports: [
        CommonModule,

        QuillModule.forRoot({
            debug: 'log',
            theme: 'snow',
            // Removed this ... 
            // customModules: [{ implementation: MyQuillImageBlot, path: 'formats/my-quill-image' }],
        }),
    ],
})
export class MyWysiwygModule {
    // for somethins like this .... :/
    static QuillLoaded: boolean = false;

    constructor(
        private quillService: QuillService,
        @Inject(PLATFORM_ID) private platformId: string,
    ) {
        // This constructor can't be asynchronous. 
        // The QuillModule should already be initialized,
        // but i guess its just lucky that my component initializes 
        // the actual quill editor when this promise is resolved ...
        if (!MyWysiwygModule.QuillLoaded && isPlatformBrowser(this.platformId)) {
            MyWysiwygModule.QuillLoaded = true;
            this.quillService.getQuill().then((quill: typeof QuillType) => {
                const MyQuillImageBlot = createMyQuillImageBlotClass(quill.import('blots/embed'));
                quill?.register('formats/my-quill-image', MyQuillImageBlot);
            });
        }
    }
}
```

**Comment by jwjuele** [comment]
... actually i'm a genius 😄 

If i'm right, the Promise chain may call my method synchronously directly after the first `.then()` execution in the ngx-quill `Quillservice.getQuill()` method. That way quill may already be set up with is passed configuration coming with `QuillModule.forRoot(config)` and should not execute any other executions in the promise chain which may follow with the use of my custom `MyWysiwygComponent` implementations exported in the same module. 

So i'd guess that no editor would be rendered without my custom blots being extended by `Quill.import('blots/embed')` and registered with the same `Quill` instance.

But still, this is implementation os pretty hacky and extending a class from an incoming function parameter is probably one of the ugliest things i've written this year. Another possible hook offered by the `QuillService` wouldn't change my way of creating the class though...

**Comment by KillerCodeMonkey** [comment]
ahh sorry i just forget to answer.

In general the ssr and async loading of quill is just there to get ngx-quill ready for ssr out of the box.
If it needs some changes or additions to make it easier to work with custom blots - send me a pr :)

but in general you could just try to split up your module in a browser-app.module and server-app.module.
on serverside you could just shim/mock modules that are depending on the dom.

So in your browser module you just would not load your custom blots.

There are many tutorials and guides out there:
https://medium.com/upstate-interactive/how-to-build-an-angular-app-with-server-side-rendering-f7f415b851c8
