### ISSUE TITLE
Bug: onSelectionChange event is triggered outside of ngZone

### ISSUE THREAD

**Issue by shyamal890** [KillerCodeMonkey/ngx-quill#124]
Checkout this example: https://stackblitz.com/edit/ngx-quill

If you remove the `ngZone.run` code the updates won't work as expected.

**Comment by KillerCodeMonkey** [comment]
Feel free to open a pull request ;)

Am 27.02.2018 19:30 schrieb "Shyamal Parikh" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
should be fixed in v2.1.2
