### ISSUE TITLE
Mac spelling correctness doesn't work - "addRange(): The given range isn't in document."

### ISSUE THREAD

**Issue by yanivfa** [KillerCodeMonkey/ngx-quill#1251]
Hi,

I'm using ngx-quill version 13.2.0, angular 11 and chrome 90.0.4430.93.
When I past text from outer source into the text editor and trying to fix spelling, the word is getting deleted (see attached video).
In addition, the warning "addRange(): The given range isn't in document." is printed to the console.

How to reproduce: 
1) Copy from gmail some text with spelling error. for example: "hre are th msitaks".
2) Past it into the text editor and try to fix spelling using mac spelling checker (right click).

https://user-images.githubusercontent.com/79040987/118779726-04cac400-b894-11eb-88d4-76280f034086.mov

**Comment by KillerCodeMonkey** [comment]
i think this is a general problem with quilljs

https://github.com/quilljs/quill/issues/2527
