### ISSUE TITLE
A vulnerability in the Quill (XSS)

### ISSUE THREAD

**Issue by Lertis** [KillerCodeMonkey/ngx-quill#1253]
Hi, there! Is that possible to know that Quill inside of his own implementation prevents or check somehow any possible injections? If it do it - what exactly is checking?

![MicrosoftTeams-image](https://user-images.githubusercontent.com/24374130/119101874-21950200-ba22-11eb-9511-c1b0a3eeeef5.png)

Text: A vulnerability in the HTML editor of Slab Quill allows an attacker to execute arbitrary JavaScript by storing an XSS payload (a crafted onloadstart attribute of an IMG element) in a text field. No patch exists and no further releases are planned.

**Comment by KillerCodeMonkey** [comment]
in ngx-quill you can activate "sanitize" so angulars html santize is used to strip such content ;-).

In my demo repo you have an example for exactly this usecase:

there is an editor without sanitizing the content -> an html alert is opened.
the editor with sanitizing strips that script part.

**Comment by Lertis** [comment]
Thanks for the answer!
