### ISSUE TITLE
How to integrate quill-emoji

### ISSUE THREAD

**Issue by shyamal890** [KillerCodeMonkey/ngx-quill#126]
I am not able to work this out. Would appreciate your help here.

https://github.com/contentco/quill-emoji

**Comment by KillerCodeMonkey** [comment]
duuude, please do not spam this repo with problems you have which does not depend on ngx.quill... 
install the module.

And learn to check the project itself --> there you will see, that quill-emoji expects the Quill-Object globally.
Then extend your webpack.conf to provide quill-globally.

You can see how to do it in the webpack conf in my ngx-quill-example repo ;)

**Comment by villanuevadani** [comment]
Hey @shyamal890 , did you find a way to make it work? With Quill 1

**Comment by KillerCodeMonkey** [comment]
Just check out the commit history of my example repo. It ls linked in the Readme.

Choose a commit prior the quill 2 changes and you will see :)

Am 19. September 2024 16:15:45 MESZ schrieb Daniel Villanueva ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
E.g.

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/v14.3.0/src/app/emoji/emoji.component.ts
