### ISSUE TITLE
How to get img tag in Content when click to this image?

### ISSUE THREAD

**Issue by tranhao167** [KillerCodeMonkey/ngx-quill#1264]
Hi guy,
I want to click 1 image in content which can get `<img src = /> ` call another function to remove this from content.
Thank you so much!

**Comment by KillerCodeMonkey** [comment]
your question has nothing to do with ngx-quill. if you need a custom functionality check quilljs docs how to create custom blots, modules and formats.
https://quilljs.com/guides/how-to-customize-quill/#customizing-blots

Or just checkout some image modules like https://github.com/kensnyder/quill-image-resize-module

how they implement a custom module.

Simple solution is something like -> grab the quill instance from the onEditorCreated output and add a good old javascript event listener to the quill root element. Check if the click is on an image -> do your logic here.
E.g. https://github.com/kensnyder/quill-image-resize-module/blob/master/src/ImageResize.js#L39
