### ISSUE TITLE
Quill API doesn't detected in angular forms

### ISSUE THREAD

**Issue by vKuka** [KillerCodeMonkey/ngx-quill#1268]
[Demo](https://stackblitz.com/edit/angular-ivy-2xknxc?file=src/app/app.component.html)
If you change format of text by default button, control detect changes and update value but if you change format by custom button witch call quill API, value won't change and valueChanges won't call

**Comment by KillerCodeMonkey** [comment]
that is the expected default behaviour.
Due to performance reasons only real "user" changes are tracked for the form control.

check the readme. there is an `trackChanges` input. you can set it to "all" or better, pass 'user' as source when you call `.format()`
