### ISSUE TITLE
links without http or https don't work

### ISSUE THREAD

**Issue by vhe1** [KillerCodeMonkey/ngx-quill#129]
Hi!
When I insert a link with a url that just goes like "google.de", and, later, click on that html, I get the authority just appended to url of the page I'm viewing:

https://myspa.com/api/v1/offers/serve/myapp/preview/google.de
which gives me a "resource not found".

**Comment by KillerCodeMonkey** [comment]
Yeah, because the Browser sees a relative Url... Add a leading "HTTPS://"
or "http://" . Browsers automatically adds the current Domain to the URL ;)

Close #129

**Comment by prakash-patel** [comment]
Does this can be done grammatically if user forgot to add "http" or "https"?

**Comment by KillerCodeMonkey** [comment]
This Bug should be mentioned at the quilljs repository.

You can solve this by adding a custom handler for the links Blot.

Or listen to the onContentChanged ouput where you get notified about all
changes by the User. There you get the whole content and Delta. So Here you
can validate your links and fix them :)

Prakash Patel <notifications@github.com> schrieb am Fr., 22. Feb. 2019,
22:41:
