### ISSUE TITLE
Can't Run on ng11

### ISSUE THREAD

**Issue by Crypt0Graphic** [KillerCodeMonkey/ngx-quill#1291]
I tried with types, to use wrapper but i always get this kind export/import errors:

`import QuillType, { Delta } from 'quill';`

P.S. I use version 13.4.0 for ng11.

**Comment by KillerCodeMonkey** [comment]
you are using the wrong quill types i guess. they should fit the quilljs version 1.3.x

**Comment by KillerCodeMonkey** [comment]
issue search is your friend:
https://github.com/KillerCodeMonkey/ngx-quill/issues/1107
https://github.com/KillerCodeMonkey/ngx-quill/issues/1092
https://github.com/KillerCodeMonkey/ngx-quill/issues/1007
