### ISSUE TITLE
Argument of type 'ElementRef<any>' is not assignable to parameter of type 'Injector'.   Property 'get' is missing in type 'ElementRef<any>' but required in type 'Injector'.

### ISSUE THREAD

**Issue by begandroide** [KillerCodeMonkey/ngx-quill#1298]
Hi @KillerCodeMonkey, recently I installed ngx-quill and extends the QuillEditorBase to implement a mat-form-field that supports reactive forms with error handling.

Im facing a issue related with the extension of quill-base-editor, locally i dont have issues but when i upload my application to Azure Static Website y made a build and i has this output:
![image](https://user-images.githubusercontent.com/22018004/124487503-d0945f80-dd7c-11eb-86a5-1f9aec74a480.png)

I followed the guides to extend a matformcontrol: [https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/mat-quill](https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/mat-quill).

Which could be the error?

Regards

**Comment by KillerCodeMonkey** [comment]
I think IT IS an Error in The example Code ;-).

But since IT IS in The example repo, please Open an issue there.

**Comment by begandroide** [comment]
Thanks you, i opened a issue: [https://github.com/KillerCodeMonkey/ngx-quill-example/issues/775](https://github.com/KillerCodeMonkey/ngx-quill-example/issues/775)
