### ISSUE TITLE
Is there a way to "clean" text as it is pasted in?

### ISSUE THREAD

**Issue by rodneyjoyce** [KillerCodeMonkey/ngx-quill#13]
I do not have the Clean button enabled in the toolbar. Many users copy and paste rich HTML (From Word etC) into the textbox and then they can't remove the formatting.

Is there a way to clean it on paste? (ie. it removes all formatting and then they can reformat as they want?)

Thanks

**Comment by KillerCodeMonkey** [comment]
Uhhh. I think this is a general issue of wysiwyg editors.

Here is a related issue of QuillJS.
https://github.com/quilljs/quill/issues/1184

And it is sad, that people does not learn, that most editors in the web has nothing to do with office products :).

In a dreamworld everyone would use the same formatting and technology^^

think even the big players like ckeditors are having problems with such things.
Like jason wrote you could try to add you own paste-module --> try to strip all markup stuff. but this will lead to a single line of text.

**Comment by rodneyjoyce** [comment]
Ok, thanks - I think the most-close solution would be to put the Clean button back onto the toolbar in my app - I will do this...

**Comment by nqtoancusc** [comment]
<div>aa</div>
