### ISSUE TITLE
Create and Register Custom Dropdown On Toolbar That Inserts Text Into Editor

### ISSUE THREAD

**Issue by Frank-The-Tank** [KillerCodeMonkey/ngx-quill#130]
How do I create and register my own custom dropdown that inserts text based on what was chosen in the drop down? I am currently implementing my toolbar through DOM elements in my HTML as such: 

**HTML**
```
<quill-editor
  [(ngModel)]="title"
  [modules]="modules"
  (onEditorCreated)="addBindingCreated($event)"
  (onSelectionChanged)="logSelection($event)">
    <div quill-editor-toolbar>
      <span class="ql-formats">
        <button class='ql-indent' value = "-1"></button>
        <button class='ql-indent' value = "+1"></button>
      </span>
      <span class="ql-formats">
        <div id="counter"></div>
      </span>
      <span class="ql-formats">
        <app-autocomplete-box></app-autocomplete-box>
      </span>
      <span class="ql-formats">
        <div [hidden]="hideSymbols">
          <select class="ql-size" >
            <option id="equalsBtn" value="equals">=</option>
            <option id="impliesBtn" value="implies">=></option>
          </select>
        </div>
        <!-- <div [hidden]="hideSymbols">
          <button id="equalsBtn" class="symbolBtn">=</button>
          <button id="impliesBtn" class="symbolBtn">=></button>
        </div> -->
      </span>
    </div>
</quill-editor>

```
Right now my select tag has the class 'ql-size' because it is a default class and loads the values in my select statement to show on screen, but I assume I have to create my own reference and use Quill.register to add it to my quill instance as I did before when I did simple button presses that were not nested in a select tag. **How do I create and register something to my modules object that  allows for text to be inserted upon selecting an element in the dropdown?**

**modules specific code**
```
Quill.register('modules/counter', Counter);
Quill.register('modules/equalsSymbol', SymbolPicker);
Quill.register('modules/impliesSymbol', SymbolPicker);

this.modules = {
      keyboard: {
        bindings: this.bindings
      },
      formula: true,
      toolbar: true,
      counter: { container: '#counter', unit: 'word' },
      equalsSymbol: { container: '#equalsBtn', selector: 'equals' },
      impliesSymbol: { container: '#impliesBtn', selector: 'implies' }
    };

```
![screen shot 2018-03-06 at 4 57 16 pm](https://user-images.githubusercontent.com/10601523/37067612-75fc72ec-215f-11e8-8e19-67b976ef36a1.png)

**Comment by KillerCodeMonkey** [comment]
this is more or less a direct quilljs question. i never did something like this. I would only guessing :S

Maybe this helps: https://github.com/quilljs/quill/issues/1817

Please check this out. If the quilljs approach how to solve this problem is not possible with ngx-quill, come back and reopen the issue.

**Comment by T-vK** [comment]
@Frank-The-Tank What you're proposing could be done using my [DynamicQuillTools](https://github.com/T-vK/DynamicQuillTools) library as long as you have access to the quill instance variable.

``` JavaScript
const dropDownItems = {
    'Mike Smith': 'mike.smith@gmail.com',
    'Jonathan Dyke': 'jonathan.dyke@yahoo.com',
    'Max Anderson': 'max.anderson@gmail.com'
}

const myDropDown = new QuillToolbarDropDown({
    label: "Email Addresses",
    rememberSelection: false
})

myDropDown.setItems(dropDownItems)

myDropDown.onSelect = function(label, value, quill) {
    // Do whatever you want with the new dropdown selection here

    // For example, insert the value of the dropdown selection:
    const { index, length } = quill.selection.savedRange
    quill.deleteText(index, length)
    quill.insertText(index, value)
    quill.setSelection(index + value.length)
}

myDropDown.attach(quill)
```

**Comment by MartirosyanMarat** [comment]
Finally I have found a solution, not the best one, but I hope this is good solution, and it works for 100% in my case.

If short **you need add this 2 lines** 

`::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-label[data-label]:not([data-label=""])::before {
  content: attr(data-label);
}

::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-item[data-label]:not([data-label=""])::before {
  content: attr(data-label);
}`


_Here is my full code_ 

**`component.ts`**

`import {Component, ViewChild} from '@angular/core';
import {QuillEditorComponent, QuillModules, QuillViewComponent, QuillViewHTMLComponent} from "ngx-quill";
import {FormsModule} from "@angular/forms";
import {JsonPipe} from "@angular/common";

@Component({
  selector: 'app-ngx-quill-demo',
  standalone: true,
  imports: [
    QuillEditorComponent,
    QuillViewComponent,
    QuillViewHTMLComponent,
    FormsModule,
    JsonPipe
  ],
  templateUrl: './ngx-quill-demo.component.html',
  styleUrl: './ngx-quill-demo.component.css'
})
export class NgxQuillDemoComponent {
  @ViewChild(QuillEditorComponent, {static: false}) quillEditor!: QuillEditorComponent;

  lineHeight = '1'
  content: any = '<p>Hello World</p>'
  modules: QuillModules = {
    toolbar: {container: '#custom-toolbar'},
  };


  setLineHeight(value: string) {
    if (this.quillEditor) {
      const editorElement = this.quillEditor.editorElem?.querySelector('.ql-editor') as HTMLElement;
      if (editorElement) {
        editorElement.style.lineHeight = value;
      }
    }
  }

  lineHeightChanged() {
    this.setLineHeight(this.lineHeight);
  }
}
`

**`component.html`**

`<quill-editor
  style="width: 100%"
  [style.line-height]="lineHeight"
  [(ngModel)]="content"
  [modules]="modules"
  format="object">
</quill-editor>

<div id="custom-toolbar">
    <span class="ql-formats">
      <button type="button" class="ql-bold"> </button>
      <button type="button" class="ql-italic"> </button>
      <button type="button" class="ql-align" value=""></button>
      <button type="button" class="ql-align" value="center"></button>
      <button type="button" class="ql-align" value="right"></button>
      <button type="button" class="ql-align" value="justify"></button>
    </span>

  <select class="ql-size">
    <option value="small">Small</option>
    <option selected value="normal">Normal</option>
    <option value="large">Large</option>
    <option value="huge">Huge</option>
  </select>

  
  <select class="ql-custom-line-height"
          data-label="'My Line Height'"
          [title]="'Line Height'"
          [(ngModel)]="lineHeight"
          (ngModelChange)="lineHeightChanged()">
    <option value="1" selected>Default</option>
    <option value="1.5">1.5</option>
    <option value="2">2.0</option>
    <option value="2.5">2.5</option>
    <option value="3">3.0</option>
  </select>
</div>
`

**`component.css`**
`::ng-deep .ql-snow .ql-picker.ql-custom-line-height {
  /*This is not must*/
  min-width: 150px;
}

::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-label[data-label]:not([data-label=""])::before {
  content: attr(data-label);
}

::ng-deep .ql-snow .ql-picker.ql-custom-line-height .ql-picker-item[data-label]:not([data-label=""])::before {
  content: attr(data-label);
}
`

Note
The only case that I didn't like in this code is that I use the` ::ng-deep`
