### ISSUE TITLE
npm package vulnerabilities

### ISSUE THREAD

**Issue by ViktorMedvedchuk** [KillerCodeMonkey/ngx-quill#1301]
Hello
Are you going to fix this https://www.npmjs.com/advisories/1695

**Comment by KillerCodeMonkey** [comment]
it is already. check the readme about "sanitize". there is even an example in my demo repo where unsafe and safe insert is shown ;-).

Under the hood it is using angulars sanitation.

**Comment by KillerCodeMonkey** [comment]
And btw. when you are using not the "html" format there is no possible xss, because you are working with plain json and not html ;-)-

Using HTML is not recommended at all

**Comment by ViktorMedvedchuk** [comment]
Yeah, I really tried to hack manually, but I can't), we are using Object mode, thanks for the fast response :-)
