### ISSUE TITLE
quill-editor component without display propertie defined in host cause some bugs

### ISSUE THREAD

**Issue by aslamcode** [KillerCodeMonkey/ngx-quill#1306]
Hey Guys!

 I had some problems with the **height** of component **quill-editor**. The quill-editor component child called **quill-editor-element** exceed the initial height of the parent causing some bugs in height of the **quill-editor** and in others elements in page.
 
 I believe this problem occurs because the quill-editor componet don't have display in host css.
 
 I fixed this problem using display as block in host component.
 
Maybe the **quill-editor** component could have the display block on the host by default.

**Comment by KillerCodeMonkey** [comment]
feel free to send a PR :)

**Comment by aslamcode** [comment]
> feel free to send a PR :)

Sent!

I set the host display as **inline-block** like native HTML input.

But maybe display could be block. Tell me what you think and anything i change.

**Comment by KillerCodeMonkey** [comment]
i think it is okay :). i will try to release a new version this week. Thanks
