### ISSUE TITLE
[Feature reques] Allow the "required" validation to check for any content, instead of only text

### ISSUE THREAD

**Issue by Maximaximum** [KillerCodeMonkey/ngx-quill#1309]
Currently the "required" validation only checks if there's any text present. I'm not sure what the original cause for that decision was, but I believe that in many cases (my case including) it would be extremely useful to check for any content presense, instead of text presence. Ie, if a user inserts an image into a "required" quill editor (but does not type any text), there should be no "required" error.

It looks like this could be achieved by replacing this line: https://github.com/KillerCodeMonkey/ngx-quill/blob/d5b418f10a625f30baf0ac60332907a49344f7e9/projects/ngx-quill/src/lib/quill-editor.component.ts#L635

with something like `if (this.required && this.quillEditor.getContents().length() === 1) {`

**Comment by Maximaximum** [comment]
FWIW, I guess it would make sense to make the "requiredChecksForTextOnly" option configurable

**Comment by KillerCodeMonkey** [comment]
the background is, that the default value of quilljs in html is "<p><br/></p>" ;-)

**Comment by KillerCodeMonkey** [comment]
Maybe it would be an approach to check the json representation (or Delta) of the content. If there is anything else than the empty block

**Comment by Maximaximum** [comment]
Opps, sorry, I meant something like this `if (this.required && this.quillEditor.getContents().ops.length() === 1 && !textLength) {`

**Comment by KillerCodeMonkey** [comment]
feel free to create a PR

**Comment by KillerCodeMonkey** [comment]
@Maximaximum i pushed some changes to the master branch. maybe you can check them?

**Comment by Maximaximum** [comment]
@KillerCodeMonkey Seems like there's a typo in your variable name, `onyEmptyOperation` should be `onlyEmptyOperation`? Other than that, LGTM.

Thanks for the effort! :)

**Comment by KillerCodeMonkey** [comment]
released in 14.2.0
