### ISSUE TITLE
How to take the toolbar out of the tab sequence

### ISSUE THREAD

**Issue by AlanObject** [KillerCodeMonkey/ngx-quill#1311]
I am using a quill-editor element in my Materials form as follows:

```
        <mat-form-field appearance="fill">
          <mat-label>Title</mat-label>
          <input matInput type="text" name="title" [(ngModel)]="docCopy.title">
        </mat-form-field>

        <quill-editor [(ngModel)]="docCopy.text" name="content"></quill-editor>
```

When the user enters text in the title field, then hits the tab key, the input focus lands on the first button on the toolbar.  I have all the buttons on the toolbar so tabbing through them all is not very practical.  And tabbing into the toolbar isn't very useful anyway.  So the user has to go to the mouse to click on the document area.

Is there any way to fix the tab order so that a tab bypasses the toolbar and goes from the title and straight to the text area?

**Comment by KillerCodeMonkey** [comment]
i would guess creating your custom toolbar and set tabindex to -1 for each button

**Comment by KillerCodeMonkey** [comment]
maybe those quilljs topics are helpful:

https://github.com/quilljs/quill/issues/110
https://github.com/quilljs/quill/issues/2038
