### ISSUE TITLE
How to access the full QuillJS API

### ISSUE THREAD

**Issue by Neimhin** [KillerCodeMonkey/ngx-quill#1316]
This might be a noob question, I'm still wrapping my head around both quill and ngx-quill.

I haven't figured out how to access the full quill API when using the `<quill-editor>` component. I'm using @ViewChild to get a reference to the quill-editor component and it has all the functions documented in your README etc. but I can't find a way to use any of the functions documented in the QuillJS API. In particular I'd like to be able to use the `.getLines()` method rather than manually parsing the `[(ngModel)]`'d html description of the contents. `.getLines()` is a lot more convenient in my use case because I need to know where the line breaks are.

What would your method be for accessing the native QuillJS API?

**Comment by KillerCodeMonkey** [comment]
editor instance is passed as first parameter to all outputs/events.

just listen to onEditorCreated and use the quilljs api.

**Comment by jefftudorbenbria** [comment]
I have set up a function which is bound to the event emitter "onEditorCreated", but none of the functions quilljs api are available on the object I receive in that function.

            (onEditorCreated)="onEditorCreated($event)"

**Comment by KillerCodeMonkey** [comment]
Just check the demo repo there you have even console logs where you see the
output data + it's usage.

jefftudorbenbria ***@***.***> schrieb am Mo., 31. Jan. 2022,
21:50:
