### ISSUE TITLE
Getting  error  " @angular/core/index  has no exported member 'Renderer2'.

### ISSUE THREAD

**Issue by ShubhamTANDF** [KillerCodeMonkey/ngx-quill#1318]
trying to integrate ngx-quill with angular 2 application
Angular core version: 2.0.0
ngx-quill :1.6.0
quill:1.3.7

But getting this error
ERROR in [at-loader] ./node_modules/ngx-quill/src/quill-editor.component.ts:10:3 
node_modules/@angular/core/index"' has no exported member 'Renderer2'.

Which version of ng-quill we should with angular 2.0.0

**Comment by KillerCodeMonkey** [comment]
Please Close The issue. No Support for outdated and not maintained /
supported angular Versions.

ShubhamTANDF ***@***.***> schrieb am So., 1. Aug. 2021, 10:13:

**Comment by ShubhamTANDF** [comment]
Thank you, will close this, just  let me know which version should we update our angular app so that we can make use of this library,
