### ISSUE TITLE
Show bubble theme toolbar on right click

### ISSUE THREAD

**Issue by Spaceman2019** [KillerCodeMonkey/ngx-quill#1319]
For the user to see the Bubble theme toolbar he has to select text first.
However, to insert an image and to 'turn on' bold or italic writing there is no need to select text.

So, I think, it would be nice to have an option to let the toolbar show on a right click in the editor area.

**Comment by KillerCodeMonkey** [comment]
This should be requested at The quilljs repo and Not Here ;-)
