### ISSUE TITLE
Imported the quill module, but css does not seem to get applied

### ISSUE THREAD

**Issue by karthikkp** [KillerCodeMonkey/ngx-quill#132]
![image](https://user-images.githubusercontent.com/2613418/37107226-cff6c914-2259-11e8-962c-2a772d14fed7.png)

This is how it looks for me. There are no console errors and I also tried including them in the angular-cli.json file.

**Comment by KillerCodeMonkey** [comment]
You need to import the quill theme CSS and core CS on your own. Import the
CSS Files in your CSS/scss or If you are using angular+cli add them to
Styles in the angular CLI json. Or simply load them in your index.HTML.
check my demo repo for an example

**Comment by maenthoven** [comment]
Just adding because this took me a sec to figure out, in case anyone else stumbles on this thread. For some reason, I missed that there's a difference between core.js and core.css

There are **three files** you need to include to get this fully working with angular-cli

In `.angular-cli.json`:
`"styles": [
        ...
        "../node_modules/quill/dist/quill.snow.css",
        "../node_modules/quill/dist/quill.core.css"
        ...
],
"scripts": [
        "../node_modules/quill/dist/quill.core.js"
],`

**Comment by RscAnonymous** [comment]
I have imported the bubble.css but still facing the same issue.

**Comment by KillerCodeMonkey** [comment]
did you checked out my example repo? there you see how to integrate quill with an angular cli projec.t it is linked in the readme

**Comment by RscAnonymous** [comment]
yes I did. The snow theme is working fine as expected but the bubble theme is not. I'm seeing the same ui as posted by OP.

**Comment by KillerCodeMonkey** [comment]
strange because in my example it is working fine https://killercodemonkey.github.io/ngx-quill-example/ checkout the "bubble theme" editor

**Comment by KillerCodeMonkey** [comment]
strange because in my example it is working fine https://killercodemonkey.github.io/ngx-quill-example/ checkout the "bubble theme" editor

Check your javascript console in the browser or cli output if there is a hint, that the bubble.css is not found.

Maybe you have missed something in the path or name.

**Comment by RscAnonymous** [comment]
It is including the bubble.css but I must be doing something wrong since its working fine in your example. Let me check and will get back to you. Thank you

**Comment by KillerCodeMonkey** [comment]
You have to include it in your global css. because if you import it only in a component all css classes are getting prefixed because of view encapsulation ;)

**Comment by RscAnonymous** [comment]
works fine now. I was overwriting some of the CSS in my styles.css (for snow theme) which was not letting the floating toolbar work when I changed the theme to bubble. Thank you.

**Comment by KillerCodeMonkey** [comment]
no probs. glad it is working now :)

**Comment by kyracalvert** [comment]
Thanks for sticking with the issue, @KillerCodeMonkey!

**Comment by Ramaq007** [comment]
dasasd

**Comment by Ramaq007** [comment]
> dasasd

dasdasd

**Comment by kyabroudi** [comment]
> Just adding because this took me a sec to figure out, in case anyone else stumbles on this thread. For some reason, I missed that there's a difference between core.js and core.css
> 
> There are **three files** you need to include to get this fully working with angular-cli
> 
> In `.angular-cli.json`:
> 
> "styles": [
> ...
> "../node_modules/quill/dist/quill.snow.css",
> "../node_modules/quill/dist/quill.core.css"
> ...
> ],
> "scripts": [
> "../node_modules/quill/dist/quill.core.js"
> ],

I did added styles and scripts to angular.json but the quilljs scripts loading when first time using quill editor in my component which cause delay when showing quill editor first time ,I've checked browser network I saw a request call "https://localhost:44316/quill.js" take time, why this call request even I don't have quill.js file in this path? any how I solved my problem with loading same request into index.html but this not best solution, why this happened and why not loading from angular.json scripts !!?

**Comment by sarfiraz** [comment]
how to change the width of the editor?

**Comment by KillerCodeMonkey** [comment]
css? or pass styles via `styles` config property of the editor component
