### ISSUE TITLE
Text html is not put correctly

### ISSUE THREAD

**Issue by hotequil** [KillerCodeMonkey/ngx-quill#1323]
# Problem
I received this value from back-end `<p>items:</p><ul><li>item 1</li><li>item 2</li></ul>` and in quill-editor element is put `items:item 1item 2`. When i input in editor works, but when i receveid from back-end no.

### Set
![Set value](https://user-images.githubusercontent.com/46814712/128344855-85d974c0-d452-49f6-8c17-507b71890d19.png)

### Receiving (from back-end)
![Receiving value](https://user-images.githubusercontent.com/46814712/128344952-aae4957e-68b8-4816-9a74-066f99c95893.png)

### Received
![Received value](https://user-images.githubusercontent.com/46814712/128345032-5b6bd1f2-8ec5-4386-8c4f-34fc9a4e2c43.png)

## My HTML component:
    <quill-editor class="editor__content"
                  theme="snow"
                  [linkPlaceholder]="'form.editor.link.placeholder' | translate"
                  [modules]="modules"
                  [required]="required"
                  [readOnly]="disabled"
                  [placeholder]="placeholder | translate"
                  [attr.aria-label]="label | translate"
                  [formControl]="field">
    </quill-editor>

## Browser:
Google Chrome: 92.0.4515.107.

## Tools
- Angular version: 11.2.6;
- quill: 1.3.7;
- @types/quill: 1.3.7;
- ngx-quill: 14.1.2.

**Comment by KillerCodeMonkey** [comment]
this should work in my demo https://killercodemonkey.github.io/ngx-quill-example/

there are editors with format html and a listing.
Maybe you can create a stackblitz to reproduce the issue?

**Comment by hotequil** [comment]
I fix this using the innerHTML property of ngx-quill :sweat_smile:
