### ISSUE TITLE
Toolbar option svg preventing selection toggle

### ISSUE THREAD

**Issue by IsaacSomething** [KillerCodeMonkey/ngx-quill#1329]
I am currently using `"ngx-quill": "^14.2.0",` with `@import '../node_modules/quill/dist/quill.snow.css';`

I have a custom toolbor

```
<div quill-editor-toolbar>
    <span class="ql-formats"> <button class="ql-bold" title="Bold"></button> </span>
    <span class="ql-formats"> <button class="ql-italic" title="Italic"></button> </span>
    <span class="ql-formats"> <button class="ql-underline" title="Underline"></button> </span>
    <span class="ql-formats"> <button class="ql-strike" title="Strike"></button> </span>
    <span class="ql-formats"> <button class="ql-blockquote" title="Blockquote"></button> </span>
</div>
 ```
 
 This works fine on the first set of the option. So bold text turns into bold text. However if i try and remove the bold text it will only work if i click in a very specific space, space that is not taken up by the svg element. It seems like the svg icon that is added is preventing the removal of the selected option.
 
If i remove the icon completely with `display:none` the toggle between the 2 states works fine.

![something-in-the-way](https://user-images.githubusercontent.com/25283027/129474964-b7d2c23d-9fc0-4a52-acd2-4ddb16d29123.gif)

 A quick fix is to add `pointer-events:none` to the nested `svg`'s css

**Comment by KillerCodeMonkey** [comment]
never had such issues. Since quilljs does the magic here. could you check if it also occurs with plain quilljs and a custom toolbar and if you have custom stylings that adds styling to buttons/svgs?

**Comment by IsaacSomething** [comment]
I do have custom styles, however i have tested this functionality with the custom styles removed from the project as well
![notes-default](https://user-images.githubusercontent.com/25283027/129865953-f905f38c-3019-4e01-b9f6-57fe014b34ca.gif)

If this is not an issue for anyone else then it might have to do with some other configuration i have, maybe with the global `svg` or something. 

Ill close the issue, the fix is fairly simple so it is not a train smash

**Comment by KillerCodeMonkey** [comment]
i extended my live demo with custom toolbar with a bold button.

works fine:
https://killercodemonkey.github.io/ngx-quill-example search for "custom toolbar"
