### ISSUE TITLE
Quill works in Safari and Chrome but doesn't show up in Firefox

### ISSUE THREAD

**Issue by siyavash4812** [KillerCodeMonkey/ngx-quill#133]
**Steps for Reproduction**

1- Add quill to angular component 
2- Visit the component from browser

**Expected behavior**:
Quill should show up

**Actual behavior**:
Quill doesn't show up in Firefox but works fine in Safari and chrome. 

**Platforms**:
Tested on Safari and chrome. It works fine
Tested on Mac, Ubuntu and Window 10 and Firefox doesn't show anything. 

<img width="1440" alt="screen shot 2018-03-07 at 22 37 36" src="https://user-images.githubusercontent.com/22658677/37122806-bd7d5686-2259-11e8-820b-0c1b0fafc038.png">

This is the code I use 

```
    <quill-editor [(ngModel)]="user_input_text" (onContentChanged)="logChange($event);" (onSelectionChanged)="logSelection($event);" style="height: 80%;">
    </quill-editor>
```

**Comment by KillerCodeMonkey** [comment]
I am using Firefox as my Main Browser in Mac OSX and it IS working. Please
Check your js console for errors

**Comment by KillerCodeMonkey** [comment]
check my demo page: https://killercodemonkey.github.io/ngx-quill-example/

it is working also in the current firefox.

**Comment by siyavash4812** [comment]
I tried installing it again and I got this error 
```

ERROR in ./node_modules/ngx-quill/src/quill.module.ts
Module build failed: Error: /xx/xx/xx/xx/xx/xx/xx/xx/app/xx/xx/ngx-quill/src/quill.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/xx/xx/xx/xx/xx/xx/xx/xx/app/xx/xx/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/xx/xx/xx/xx/xx/xx/xx/xx/app/xx/xx/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./node_modules/ngx-quill/index.js 1:0-35
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts


```

**Comment by KillerCodeMonkey** [comment]
Yeah and as you can read in english sprechen your build process does mit
include quill :). So Check your build process.
