### ISSUE TITLE
Not working from a Flutter Mobile application.

### ISSUE THREAD

**Issue by pradeeptakhatoi** [KillerCodeMonkey/ngx-quill#1330]
Hi Team,

I am using this to enter data from backend & consume it from both web & mobile application. It's working fine from web but not working for mobile application.

Thanks!

**Comment by KillerCodeMonkey** [comment]
Since this is an angular Module IT IS working only on web or pwas / mobile Crossplatform Apps based on webtechnologies e.g. Ionic....
