### ISSUE TITLE
How I can import Link formatter?

### ISSUE THREAD

**Issue by r3st1k25** [KillerCodeMonkey/ngx-quill#134]
Something like this: https://codepen.io/Poky85/pen/PQoPrV

**Comment by KillerCodeMonkey** [comment]
do it like in the example. simply create a custom quill module like the link. register it on Quill.

and pass the module configuration to the modules-input of the quill-editor component.
checkout my demo-repository linked in the readme. 
There is an example with a "word-count" module :)
