### ISSUE TITLE
Color and BackgroundColor no show when [santize] = "true"

### ISSUE THREAD

**Issue by TLKG** [KillerCodeMonkey/ngx-quill#1348]
First, really appreciate this great product!!
Running demo locally, substituting the dangerous HTML (generated from the editor) with  

`<p> rich <strong style="color: rgb(230, 0, 0);" class="ql-size-large">$</strong><strong style="color: rgb(255, 255, 255); background-color: rgb(102, 163, 224);" class="ql-size-large">35.40</strong><span style="background-color: rgb(102, 163, 224); color: rgb(255, 255, 255);"> </span>yes.</p>`

[sanitize]="true" only shows **bold** only:

Any thought? Thank you in advance

![image](https://user-images.githubusercontent.com/22269729/131269931-19886d26-d591-44be-afee-cac4e8a1f3bd.png)

**Comment by KillerCodeMonkey** [comment]
i would guess because you are using inline styles with sanitize

Am Mo., 30. Aug. 2021 um 02:10 Uhr schrieb Tom Larry <
***@***.***>:

**Comment by TLKG** [comment]
The inline styles is not by me, it's by Quill Editor, which is totally legit and correct else won't be compatible with other editors or when toolbar is hidden. It can be easily reproduced. What I'm interested is how to display color while sanitizing it? Does the component have built-in sanitizer? Thank you.

**Comment by KillerCodeMonkey** [comment]
The component just uses angular sanitizer for html.

Tom Larry ***@***.***> schrieb am Mo., 30. Aug. 2021, 17:48:

**Comment by TLKG** [comment]
Research confirms [Angular Sanitizer does strip off many things including all inline styles](https://www.google.com/search?rlz=1C1CHBF_enUS824US824&q=angular+sanitize+lost+color&spell=1&sa=X&ved=2ahUKEwiZiqD6n9nyAhV6QjABHWIEDyoQBSgAegQIARAw&biw=1536&bih=794). @KillerCodeMonkey Thank you!

**Comment by KillerCodeMonkey** [comment]
no probs. ;-)
in general you should not use html format. just use object/json format to get all content as delta representations = no stripping at all and you are able to write migrations to other wysiwyg editors ;-)

**Comment by TLKG** [comment]
What's the consideration of using `object` or `json`?

**Comment by KillerCodeMonkey** [comment]
like i described above. you are storing and working with deltas and not html code. So you can migrate every content to another editor or e.g. markdown without hacking parsing html, e.g. `{ops: [{ insert: "test" }]}` instead of `<p>test</p><p><br/><p>`

**Comment by TLKG** [comment]
Really appreciate it, `object` works out beautifully. What I meant is `object` and `json` same, if not which is better? This is because README lacks of details. Thank you.
