### ISSUE TITLE
Quill imports Error

### ISSUE THREAD

**Issue by vladimirpetukhov** [KillerCodeMonkey/ngx-quill#1349]
Error: node_modules/@types/quill/node_modules/quill-delta/dist/Delta.d.ts:1:8 - error TS1259: Module '"F:/Code/ANGULAR/new-age-blog/node_modules/@types/quill/node_modules/fast-diff/diff"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import diff from 'fast-diff';
         ~~~~

  node_modules/@types/quill/node_modules/fast-diff/diff.d.ts:20:1
    20 export = diff;
       ~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:21 - error TS2614: Module '"quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "quill"' instead?

3 import QuillType, { Delta } from 'quill';

**Comment by KillerCodeMonkey** [comment]
Check closed issues. There should be something for you ;-)

Vladimir ***@***.***> schrieb am Mo., 30. Aug. 2021, 18:02:

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/1342#issuecomment-906697799

**Comment by dcvieira** [comment]
I have the same issue after upgrade to Angular 12. 
@vladimirpetukhov  Do you solve this?
