### ISSUE TITLE
Wrong scroll (overlap) while clicking toolbar icons

### ISSUE THREAD

**Issue by loqiue** [KillerCodeMonkey/ngx-quill#135]
This problem occurs on IOS chrome/safari/mozilla browsers. If we are **outside** of editor and clicking any icon from toolbar then virtual keyboard overlaps editor. There is a [gif](https://gyazo.com/094d3bc82543e31f961b07efc1eb5cd8) representing a problem. 
Also if focus already inside editor then clicking ql-color or ql-background icons do the same problem. Thank you!

**Comment by KillerCodeMonkey** [comment]
Is this also happening in quilljs (without ngx-quill)? Then it is a general
quilljs problem.

But it seems to be working as expected in my demo repo
https://killercodemonkey.github.io/ngx-quill-example/ on mobile devices.

Maybe your page has special styling or scroll containers

**Comment by loqiue** [comment]
I got it. Quilljs itself do it wrong. Also at your demo page behavior is not correct. Thank you for reply.
