### ISSUE TITLE
trimOnValidation not working for whitespace-only

### ISSUE THREAD

**Issue by TLKG** [KillerCodeMonkey/ngx-quill#1352]
For this editor, it works out great if input has at least one non-blank character "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Xyz" is invalid, but "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" (10 white space) is valid.

```
<quill-editor formControlName="rtnote" [sanitize]="true" placeholder="Input notes, minimum 10" 
[modules]="config" theme="snow" [minLength]="10" [trimOnValidation]="true" required="true">
</quill-editor>
```

**Comment by KillerCodeMonkey** [comment]
Feel free to send a fix PR ;-)

Tom Larry ***@***.***> schrieb am Mi., 1. Sept. 2021, 20:48:

**Comment by TLKG** [comment]
Never worked on a node library, but believe that's what's needed. Thanks

**Comment by TLKG** [comment]
See PR

**Comment by KillerCodeMonkey** [comment]
btw: i think the validation is correct -> if you trim an empty string on validation the length = 0 and since you are not setting your model as required it is marked as valid :).

so the usage for the validation is this:

- required = there needs to be some content
- minLength = if there is content, it needs to have a minimum length
- maxLength = if there is content, it needs to have a max length

so i guess: just add [required]="true"

**Comment by TLKG** [comment]
Ah, it's the brackets. It was required="true". After adding the bracket to [required] it works as expected!
Issue closed. Thank you very much!


On September 2, 2021 at 11:15 AM, Bengt Weiße ***@***.***> wrote:






btw: i think the validation is correct -> if you trim an empty string on validation the length = 0 and since you are not setting your model as required it is marked as valid :).

so the usage for the validation is this:

required = there needs to be some content
minLength = if there is content, it needs to have a minimum length
maxLength = if there is content, it needs to have a max length

so i guess: just add [required]="true"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
