### ISSUE TITLE
Create a new ngx-quill editor dynamically 

### ISSUE THREAD

**Issue by TLKG** [KillerCodeMonkey/ngx-quill#1358]
I need to create a ngx-quill editor dynamically upon request. Can't figure out which object to use and how.

```
<div id="newQE"></div>
<button (click)="addQE()">Add Note</button>

import { QuillModules, QuillService, QuillEditorBase, QuillEditorComponent, QuillModule } from 'ngx-quill';
import { Renderer2} from '@angular/core'; 

constructor(r2: Renderer2){}
var where = document.getElementById("newQE");
// need some help to create a ngx-quill editor instance, say "qe"
this.r2.appendChild(where, qe);
```

**Comment by KillerCodeMonkey** [comment]
Just something like that:
https://github.com/KillerCodeMonkey/ngx-quill/pull/1320

Tom Larry ***@***.***> schrieb am Fr., 3. Sept. 2021, 20:55:

**Comment by TLKG** [comment]
Works like a charm!
Next question, if the place/container is also dynamic, `@ViewChild()` may not be sufficient. Any advice? Thank you.

**Comment by TLKG** [comment]
I'll do some research and get back to you later. Thanks

**Comment by KillerCodeMonkey** [comment]
Just use ViewChild({ static: false })... i will close this issue for now, because it has nothing to do with ngx-quil... more with angular itself.
