### ISSUE TITLE
Can we please get an access to the Quill instance used by the component?

### ISSUE THREAD

**Issue by damien-CFS** [KillerCodeMonkey/ngx-quill#136]
Hi,
In order to register new blots or other extensions to the quill editor like this:
Quill.register({ 'blots/boltTwo':EmojiBlotTwo});
we need access to the Quill instance used by the editor. The instance is declared in vendor.bundle.js once webpack has done his job and it is hard to access it there.
Can we have a new method on the editor that would look something like this:
    QuillEditorComponent.prototype.getQuillInstance = function () {
	return Quill;
    }
and the related declaration in quill-editor-component.d.ts?
I will try and do a pull request ...
Thank you,
Damien

**Comment by KillerCodeMonkey** [comment]
You do not need the instance for registering New modules. This is done by
the global quill object.

You can Grab the quill instance after its creation. Simply listen to
oneditorcreated output and Grab the instance :). Checkout the readme

**Comment by damien-CFS** [comment]
Thanks for your super-fast reply!
The problem is that what we receive in that event is the instance of the editor and not the global quill instance. What we receive does not have the "register" method that allows this call:
    <quill-editor #editor (onEditorCreated)="addBindingCreated($event)" >

    addBindingCreated(quill) {
        quill.register({ 'blots/boltTwo':EmojiBlotTwo});
    }
Thanks

**Comment by KillerCodeMonkey** [comment]
Yeah, but you can import it? Like I do in my quill-editor-component??? Oo

QuillJS is installed by nix-quill, so you can import it, like any other 3rd party lib

**Comment by damien-CFS** [comment]
Yes but if I import it like this:
- Add it to .angular-cli.json:
     "scripts": [
        "../node_modules/quill/dist/quill.js"
      ],
 -Refer to it in my .ts:
declare var Quill: any;;
Quill.register({ 'blots/boltTwo':EmojiBlotTwo});

The code works but it uses a different instance of Quill (and the "types" array) because webpack has packed quill.js twice (one for the one in ngx-quill, one for the one requested in .angular-cli.json) and therefore the declaration is not done on the instance used by the component. I do not see a way to access the instance used by the ngx-quill-component from my component other than through the getter I was asking for.
Thanks for your help.

**Comment by KillerCodeMonkey** [comment]
And if you do not add quilljs to your scripts?

**Comment by damien-CFS** [comment]
Then Quill is undefined wether I do this:
declare var Quill: any;;
or this:
import Quill from 'quill';

**Comment by KillerCodeMonkey** [comment]
Maybe the correct solution would be, to set quilljs AS peer dependency for
ngx-quill. So you will have only one quilljs instance

**Comment by damien-CFS** [comment]
Yes that sounds like a good solution. Does that need an evolution in ngx-quill or is there a way I can do that on my side?

**Comment by KillerCodeMonkey** [comment]
You can do nothing :)

**Comment by damien-CFS** [comment]
Ok I'll be waiting to hear from you then :) Thanks for your help

**Comment by KillerCodeMonkey** [comment]
i have a local project with angular-cli and it is working without any error?
Please try the following: remove quill from your angular-cli.json and import it in this way:

```
import * as Quill from 'quill';
console.log(Quill);
```

now you should see the Quill-Object in your JS-Console and work with it :)

**Comment by KillerCodeMonkey** [comment]
nope or i need to remove the typings from this repo.

check my quill-editor-component.
I do the same :)
