### ISSUE TITLE
Support quill-v2.0.0-dev.3

### ISSUE THREAD

**Issue by FOWind** [KillerCodeMonkey/ngx-quill#1363]
When I upgrade quill from 1.3.7 to 2.0.0-dev.3. Change the editor value by `[(ngModel)]` , the contents can't be displayed.

I found that the `return quillEditor.clipboard.convert(value)` in `quill-editor.component.ts` has no longer support.

I inherit `QuillEditorBase` and overwirte the `writValue` method ,  using  `this.quillEditor.clipboard.dangerouslyPasteHTML(currentValue);`  api, then the editor can successfully display the content after set value.

``` typescript
  writeValue(currentValue: any): void {
    // optional fix for https://github.com/angular/angular/issues/14988
    if (this.filterNull && currentValue === null) {
      return;
    }

    this.content = currentValue;

    if (!this.quillEditor) {
      return;
    }

    const format = getFormat(this.format, this.service.config.format);

    if (currentValue) {
      if (format === 'text') {
        this.quillEditor.setText(currentValue);
      } else {
        this.quillEditor.clipboard.dangerouslyPasteHTML(currentValue);
      }
      return;
    }
    this.quillEditor.setText('');
  }
```

**Comment by KillerCodeMonkey** [comment]
i am not supporting 2.0.0-dev... because... it is just a years old dev version. nothing stable...
