### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by kulisdominik** [KillerCodeMonkey/ngx-quill#137]
I try add to my project custom fonts. 

app.components.ts file: 
import Quill from 'quill';
  constructor() {
    const Font = Quill.import('formats/font');
  }

When i add this code to my project. Browser return this error code: 

> ERROR 
> TypeError: quill_1.default is undefined
> Stack trace:
> AppComponent@webpack-internal:///./src/app/app.component.ts:19:13
> createClass@webpack-internal:///./node_modules/@angular/core/esm5/core.js:12653:20
> createDirectiveInstance@webpack-internal:///./node_modules/@angular/core/esm5/core.js:12500:37
> createViewNodes@webpack-internal:///./node_modules/@angular/core/esm5/core.js:13958:53
> createRootView@webpack-internal:///./node_modules/@angular/core/esm5/core.js:13847:5
> callWithDebugContext@webpack-internal:///./node_modules/@angular/core/esm5/core.js:15272:39
> debugCreateRootView@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14555:12
> ComponentFactory_.prototype.create@webpack-internal:///./node_modules/@angular/core/esm5/core.js:11452:37
> ComponentFactoryBoundToModule.prototype.create@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4239:16
> ApplicationRef.prototype.bootstrap@webpack-internal:///./node_modules/@angular/core/esm5/core.js:6070:40
> PlatformRef.prototype._moduleDoBootstrap/<@webpack-internal:///./node_modules/@angular/core/esm5/core.js:5797:74
> PlatformRef.prototype._moduleDoBootstrap@webpack-internal:///./node_modules/@angular/core/esm5/core.js:5797:13
> PlatformRef.prototype.bootstrapModuleFactory/</</<@webpack-internal:///./node_modules/@angular/core/esm5/core.js:5718:21
> ZoneDelegate.prototype.invoke@webpack-internal:///./node_modules/zone.js/dist/zone.js:388:17
> onInvoke@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4965:24
> ZoneDelegate.prototype.invoke@webpack-internal:///./node_modules/zone.js/dist/zone.js:387:17
> Zone.prototype.run@webpack-internal:///./node_modules/zone.js/dist/zone.js:138:24
> scheduleResolveOrReject/<@webpack-internal:///./node_modules/zone.js/dist/zone.js:858:52
> ZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:421:17
> onInvokeTask@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:24
> ZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:420:17
> Zone.prototype.runTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:188:28
> drainMicroTaskQueue@webpack-internal:///./node_modules/zone.js/dist/zone.js:595:25

im using Angular 5. Someone know how can i fixed this problem? 

Thanks for help. 
D.K.

**Comment by KillerCodeMonkey** [comment]
Check how I import quillJS in my example repo ;): should be something like that "import * as Quill from“
Because the typings from definitely typed are wrong.

**Comment by kulisdominik** [comment]
im looking at this example https://github.com/KillerCodeMonkey/ngx-quill-example and i didnt saw this solution.

**Comment by KillerCodeMonkey** [comment]
are you using the types?

if so, simply remove them.


sorry i meant the implementation of quill-editor-component in this repo
```
import * as QuillNamespace from 'quill';
let Quill: any = QuillNamespace;
```

**Comment by kulisdominik** [comment]
I tried this code:

**Comment by kulisdominik** [comment]
Thanks dude! 

Close this issue.
