### ISSUE TITLE
The "untouchable" bug is back

### ISSUE THREAD

**Issue by angelaki** [KillerCodeMonkey/ngx-quill#1371]
Like I found in the old version (https://github.com/KillerCodeMonkey/ng-quill/issues/40) control does not get "touched" on lost focus. A fix would be nice.

Btw: 0 opened issues? Wow! 👍

**Comment by KillerCodeMonkey** [comment]
When I check my code touched should be set on blur of the editor.

Btw ng-quill is totally different to ng-quill


Tristan ***@***.***> schrieb am Mi., 22. Sept. 2021, 16:07:

**Comment by angelaki** [comment]
I'm using the latest version and it doesn't seam to work? Are you working with ngModel or formControl?

Btw.: if you'd implement `AbstractControl` some nice features like 'markTouched' etc. would be available, too. This would be quite nice 🙂
I'll check for a reason that `touched` is not working for me.

**Comment by angelaki** [comment]
Oh come on ... I cannot reproduce it. I'm sorry, must be mistaken ... Anyway - some methods (e.g. `markAsTouched`) would be great 😄
