### ISSUE TITLE
using quill in repeater

### ISSUE THREAD

**Issue by Davidthe-Great** [KillerCodeMonkey/ngx-quill#1374]
Hi, I'm using quill in a repeater , every time it repeats, I should refresh my new generated textarea to become a quill textarea. Is there something like refreshing or resetting in this lirbrary?

**Comment by KillerCodeMonkey** [comment]
Do you have some more info. I do not understand what you mean with
refreshing or generated textarea.

In general you would use ngFor and put a quill editor in there

Davidthe-Great ***@***.***> schrieb am So., 26. Sept. 2021,
14:08:

**Comment by Davidthe-Great** [comment]
sorry my bad, I had mistaken.
