### ISSUE TITLE
Not able to set focus 

### ISSUE THREAD

**Issue by tyagiggaurav** [KillerCodeMonkey/ngx-quill#1382]
Hello 
I am not able to type anything in the editor as it does not have focus when I open it.
I get the focus only if I click any button from the toolbar (eg. bold, italic).
I tried to set the focus by calling the editor.focus() on onEditorCreated output emitter but that also does not work.
Any idea how it could be resolved ?
Thanks.

**Comment by KillerCodeMonkey** [comment]
so i am not doing anything special.
in my demo app:

https://killercodemonkey.github.io/ngx-quill-example/

an editor is focused. so just open the site and start typing.
