### ISSUE TITLE
Possible to set min and max-height?

### ISSUE THREAD

**Issue by TLKG** [KillerCodeMonkey/ngx-quill#1387]
To set height, can do `[styles]="{height:'100vh'}"`

Possible to set the min and max height like `"{minheight:'10vh'; maxheight:'50vh'}"`?

**Comment by KillerCodeMonkey** [comment]
sure, but i guess you need to use camcelCase minHeight and maxHeight or 'min-height' 'max-height', because there is no minheight or maxheight css property ;-)
