### ISSUE TITLE
need help with customOptions please

### ISSUE THREAD

**Issue by chami007** [KillerCodeMonkey/ngx-quill#139]
Hi,

I want to do the exact thing as below

https://jsfiddle.net/q7jferw3/

but i couldn't figure it out how to register the custom dropdown. Can someone help me please ?

**Comment by KillerCodeMonkey** [comment]
Do it like in this example?
pass the modules configuration with your custom toolbar entry and handler to the modules input of ngx-quill.

**Comment by chami007** [comment]
thanks for the reply. but i'm not quite sure how to do that... i don't know what module to import with customOptions.

customOptions = [{
        import: '??',
        whitelist: ['[GuestName]', '[HotelName]']
    }];

///////////////////

modules = {
            toolbar: [
                [{ 'placeholder': ['[GuestName]', '[HotelName]'] }], // my custom dropdown
                ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
                ['blockquote', 'code-block'],

                [{ 'header': 1 }, { 'header': 2 }],               // custom button values
                [{ 'list': 'ordered' }, { 'list': 'bullet' }],
                [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
                [{ 'indent': '-1' }, { 'indent': '+1' }],          // outdent/indent
                [{ 'direction': 'rtl' }],                         // text direction

                [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
                [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

                [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
                [{ 'font': [] }],
                [{ 'align': [] }],

                ['clean']                       
            ]
        };

////////

<quill-editor [modules]="modules" [customOptions]="customOptions"></quill-editor>

this is how i did it. but complaining about the module (i know i did wrong)... thanks for your help

**Comment by KillerCodeMonkey** [comment]
where do you get the custom options? i can not find them in the fiddle.

**Comment by KillerCodeMonkey** [comment]
@chami007 any updates?

**Comment by chami007** [comment]
@KillerCodeMonkey no luck yet.. still trying... :)

**Comment by KillerCodeMonkey** [comment]
are you using a custom module? because i think you can only whitelist formats. So you could create a Placeholder-Format an Whitelist these values

**Comment by KillerCodeMonkey** [comment]
inactivity closed

**Comment by srinivasthutika** [comment]
Any luck i also need the same thing

**Comment by nicolacardi** [comment]
I need that too, how do you import customOptions/a custom dropdwon in ngx-quill?
