### ISSUE TITLE
Integrating with Directives?

### ISSUE THREAD

**Issue by jfbguy** [KillerCodeMonkey/ngx-quill#14]
Wondered if there was anyway to integrate the editor with directives? I've been trying to use [this example](https://github.com/quilljs/quill/issues/109) for auto including link tags on regex match but instead trying to auto include some directive or locator for Angular2 to use. Tried adding attributes like [custom] or adding custom tags <custom> to tie certain words to angular hooks but just constantly get "[Parchment] Cannot insert custom into block," 'custom' is whatever I try build either the attribute/blot/embed/inline/etc.  Wondered if this was actually possible, or just incompatible.

**Comment by KillerCodeMonkey** [comment]
sure.

there is an output called `onEditorCreated` there you can grab the editor instance and add matchers like you want.

If you want to execute special logic when the editor text changed --> there is the onContentChanged output, where you get again the editor instance, current editor text and current editor content as html.

**Comment by jfbguy** [comment]
Been trying that. I tried copy and pasting the Parchment example from the [github ](https://github.com/quilljs/parchment) and just changed the name to create a new inline blot.

```
editorCreated(event){
    console.log("editorCreated quill:", event);

    class CustomBlot extends Parchment.Inline {
      static create(url) {
        let node:any = super.create(url);
        node.setAttribute('href', url);
        node.setAttribute('target', '_blank');
        node.setAttribute('title', node.textContent);
        return node;
      }

      static formats(domNode) {
        return domNode.getAttribute('href') || true;
      }

      format(name, value) {
        if (name === 'custom' && value) {
          this.domNode.setAttribute('href', value);
        } else {
          super.format(name, value);
        }
      }

      formats() {
        let formats = super.formats();
        formats['custom'] = CustomBlot.formats(this.domNode);
        return formats;
      }
    }
    CustomBlot.blotName = 'custom';
    CustomBlot.tagName = 'A';
    Quill.register(CustomBlot);

    this.quillEditorComponent.quillEditor.on('text-change', (delta: any, oldDelta: any, source: any) => {

      let regex = /test$/;
      if(delta.ops.length === 2 && delta.ops[0].retain) {

        let endRetain = delta.ops[0].retain;
        let text = this.quillEditorComponent.quillEditor.getText().substr(0, endRetain);
        let match = text.match(regex);

        if(match !== null) {
          let textMatch = match[0];
          console.log('textMatch -->', textMatch);

          let ops = [];
          if(endRetain > textMatch.length) {
            ops.push({ retain: endRetain - textMatch.length });
          }

          ops = ops.concat([
            { delete: textMatch.length },
            { insert: textMatch, attributes: { custom: true } }
          ]);

          this.quillEditorComponent.quillEditor.updateContents({
            ops: ops
          });
        }
      }

    });
  }
```

Always the same error, "EXCEPTION: [Parchment] Cannot insert custom into block"
The textchange event works if I change the operations to a non-custom attribute.
```
ops = ops.concat([
            { delete: url.length },
            { insert: url, attributes: { link: url } }
          ]);
```

**Comment by KillerCodeMonkey** [comment]
eeehm i do not how to extend quill you could try your code without ng-quill and use native quilljs for testing, but some hints --> never ever define a class in a function class.

Make a new file or put this code above your component class and use onContentChanged to handle changed content --> i would try to avoid the updateContents call and manipulate your model directly:

```
class CustomBlot extends Parchment.Inline {
      static create(url) {
        let node:any = super.create(url);
        node.setAttribute('href', url);
        node.setAttribute('target', '_blank');
        node.setAttribute('title', node.textContent);
        return node;
      }

      static formats(domNode) {
        return domNode.getAttribute('href') || true;
      }

      format(name, value) {
        if (name === 'custom' && value) {
          this.domNode.setAttribute('href', value);
        } else {
          super.format(name, value);
        }
      }

      formats() {
        let formats = super.formats();
        formats['custom'] = CustomBlot.formats(this.domNode);
        return formats;
      }
}
CustomBlot.blotName = 'custom';
CustomBlot.tagName = 'A';
Quill.register(CustomBlot);

....
@Component({ ... })
exports yourComponent {
  yourModel: string;

  contentChanged(editor, html, text, delta, oldDelta, source) {
    let regex = /test$/;
      if(delta.ops.length === 2 && delta.ops[0].retain) {

        let endRetain = delta.ops[0].retain;
        text = text.substr(0, endRetain);
        let match = text.match(regex);

        if(match !== null) {
          let textMatch = match[0];
          console.log('textMatch -->', textMatch);

          let ops = [];
          if(endRetain > textMatch.length) {
            ops.push({ retain: endRetain - textMatch.length });
          }

          ops = ops.concat([
            { delete: textMatch.length },
            { insert: textMatch, attributes: { custom: true } }
          ]);

          editor.updateContents({
            ops: ops
          });
        }
      }
  }
}
```

**Comment by jfbguy** [comment]
I originally had the class outside of it. This was the 20th or so iteration and was just sticking everything in the created method. I can change my strategy to manipulate the dom/html directly but I was originally worried that in Quill, on certain operations, for example, pressing backspace, it could break the logic, like it wouldn't know how to handle the html I inserted inside of it.

contentChanged(editor, html, text, delta, oldDelta, source) //this could be helpful but only the first 3 arguments are passed in the emitted event object. The deltas are not passed along.

**Comment by KillerCodeMonkey** [comment]
yeah, then checkout version 1.0.0 i release yesterday :).

I added the deltas and source + there is now an output for text-selection changed.
Hope this helps

**Comment by jfbguy** [comment]
Well looks like I can get simple tags working using 
```
var Custom: any = Quill.import('blots/inline');
Custom.blotName = 'custom';
Custom.tagName = 'custom-tag';
Quill.register(Custom, true);
```
Actually extending the Parchment.Inline class seems super buggy. Perhaps typings are off... not exactly sure.
For now this might be enough to go forward with my ideas. Thanks.
