### ISSUE TITLE
Uncaught TypeError: Cannot read property 'imports' of undefined

### ISSUE THREAD

**Issue by kennyho-code** [KillerCodeMonkey/ngx-quill#140]
I'm trying to include the image resizing but I keep getting 
`Uncaught TypeError: Cannot read property 'imports' of undefined`.

I see saw the solution of you fixing this with ['imports' of undefined #7](https://github.com/kensnyder/quill-image-resize-module/issues/7). 

I somehow can't replicate the solution.

I have this in my component:
```
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import Quill from 'quill';

// add image resize module
import ImageResize from 'quill-image-resize-module';

// Uncaught TypeError: Cannot read property 'imports' of undefined  (ERROR HERE)
// Quill.register('modules/imageResize', ImageResize);

```

My webpack:
```
var path = require('path');
var webpack = require('webpack');

module.exports = {
    entry: "./src/ImageResize.js",
    output: {
        path: __dirname,
        library: 'ImageResize',
        libraryTarget: 'umd',
        filename: "image-resize.min.js"
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                include: path.join(__dirname, 'src'),
                exclude: /(node_modules|bower_components)/,
                use: [{
                    loader: 'babel-loader',
                    options: {
                        "presets": [["es2015", { "modules": false }]],
                        "plugins": ["babel-plugin-transform-class-properties"]
                    }
                }]
            },
            {
                test: /\.svg$/,
                use: [{
                    loader: 'raw-loader'
                }]
            }
        ]
    },
	plugins: [
		new webpack.ProvidePlugin({
			'window.Quill': 'quill/dist/quill.js'
		})
};

```

**Comment by KillerCodeMonkey** [comment]
Check my example repo there is a working demo of the image resize module.

Try importing quilljs like this:

import * as QuillNamespace from 'quill';
let Quill: any = QuillNamespace;

**Comment by viniciusaugutis** [comment]
People who are having difficulty using the quill image resize module with **ANGULAR-CLI e ANGULAR 2+**
Here's a way to not have to tinker with the webpack.config.ts file

**terminal**
```
npm install quill --save
npm install quill-image-resize-module --save
```

**angular-cli.json**
```
"scripts": [
        ...,
        "../node_modules/quill/dist/quill.min.js"
 ]
```

**Componente.ts**
```
import * as QuillNamespace from 'quill';
let Quill: any = QuillNamespace;
import ImageResize from 'quill-image-resize-module';
Quill.register('modules/imageResize', ImageResize);

this.editor_modules = {
      toolbar: {
        container: [
          [{ 'font': [] }],
          [{ 'size': ['small', false, 'large', 'huge'] }],
          ['bold', 'italic', 'underline', 'strike'],
          [{ 'header': 1 }, { 'header': 2 }],
          [{ 'color': [] }, { 'background': [] }],
          [{ 'list': 'ordered' }, { 'list': 'bullet' }],
          [{ 'align': [] }],
          ['link', 'image']
        ]
      },
      imageResize: true
    };

```
**Componente.html**
`<quill-editor [modules]="editor_modules" [(ngModel)]="content"></quill-editor>`

**Comment by sairathb** [comment]
Hi, I tried the above steps but am still getting the same error "Cannot read property 'imports' of undefined"
"ngx-quill": "^3.2.0",
"quill": "^1.3.6",
"quill-image-resize-module": "^3.0.0"
I am using angular 6.0.7. Can someone please guide me as to what I am doing wrong. 

This error occurs when I try to register the ImageResize
`Quill.register('modules/imageResize', ImageResize);`

**Comment by KillerCodeMonkey** [comment]
check image-resize-module repository, i posted a solution there ;)

**Comment by sairathb** [comment]
can you please provide a link as to where I can the solution

**Comment by sairathb** [comment]
I found the solution, thanks for the quick reference. The solution is [here](https://github.com/kensnyder/quill-image-resize-module/issues/27)

**Comment by KillerCodeMonkey** [comment]
There is this issue
https://github.com/kensnyder/quill-image-resize-module/issues/16

And I posted my solution here
https://github.com/kensnyder/quill-image-resize-module/issues/7#issuecomment-354960573

Sairath Bhattacharjya <notifications@github.com> schrieb am Fr., 6. Juli
2018, 15:41:

**Comment by KillerCodeMonkey** [comment]
Damn seconds to late ;)

Sairath Bhattacharjya <notifications@github.com> schrieb am Fr., 6. Juli
2018, 15:50:

**Comment by KillerCodeMonkey** [comment]
Thank you :).

Am Sa., 2. Feb. 2019, 21:43 hat Brian Noyes <notifications@github.com>
geschrieben:

**Comment by Maddy2894** [comment]
Hi @briannoyes, I tried your solution, but still, the error is visible.

**Comment by nehadhiman6** [comment]
i had the same problem. it is resolved by declaring Quill in window object Globally

**Comment by SalmaaRagab** [comment]
I solved it by adding `"node_modules/quill/dist/quill.min.js"` to angular.json scripts array.

**Comment by jdgamble555** [comment]
For angular universal, add this as well:

**main.server.ts**
```typescript
(global as any)['window'] = {
  Quill: {
    imports: {
      parchment: {
        Attributor: {
          Style: function() {}
        }
      }
    },
    register: () => {}
  }
};
```

**Comment by thomasgebets** [comment]
If anyone comes across this issue in the @KillerCodeMonkey resizor module, i had to add `"node_modules/quill/dist/quill.js"` in th test -> scripts section of the angular.json.

**Comment by acgrama** [comment]
> If anyone comes across this issue in the @KillerCodeMonkey resizor module, i had to add `"node_modules/quill/dist/quill.js"` in th test -> scripts section of the angular.json.

Unfortunately, doesn't work. My setup is Angular 18.

**Comment by pavelpie** [comment]
> > If anyone comes across this issue in the @KillerCodeMonkey resizor module, i had to add `"node_modules/quill/dist/quill.js"` in th test -> scripts section of the angular.json.
> 
> Unfortunately, doesn't work. My setup is Angular 18 and quill 2.0.2.

Did you find any solution ?, my setup is also angular 18 and qulll 2.0.2 - many hours trying to set it now.

**Comment by KillerCodeMonkey** [comment]
image resize-module is not compatible with quill 2. i released a package called "quill-image-resizor". it is used in my demo repo for an example

**Comment by pavelpie** [comment]
> image resize-module is not compatible with quill 2. i released a package called "quill-image-resizor". it is used in my demo repo for an example.
> 
> Do not install any quill types and check of you use any other incompatible quill addons/modules.
> 
> this should also work with angular 18... just check the commit history of my demo repo. it was also working there.

I’ve just found it, thanks—it's working now. One thing worth mentioning is that Quill.js must be added to the application. For example, you can include it in angular.json like this: "./node_modules/quill/dist/quill.js". (found this info in your other [comment](https://github.com/KillerCodeMonkey/ngx-quill/issues/1858#issuecomment-2137989117)) I spent some time figuring out this imports error."

**Comment by KillerCodeMonkey** [comment]
for the image resizor it should be possible to use `import Quill from 'quill'` without any global quill available.
