### ISSUE TITLE
Can't be used with latest @types/quill

### ISSUE THREAD

**Issue by farin** [KillerCodeMonkey/ngx-quill#1407]
@types/quill doesn't export Delta
which cause compile error 

Module '"quill"' has no exported member 'Delta'
node_modules/ngx-quill/lib/quill-editor.component.d.ts
`import QuillType, { Delta } from 'quill';`

it should be replaced with
```
import QuillType from 'quill'
import Delta from 'quill-delta'
```

**Comment by KillerCodeMonkey** [comment]
latest types are for v2 it think. you should stay with 1.x

**Comment by farin** [comment]
ah, you're right, sorry for wrong issue
