### ISSUE TITLE
Mention List has a nested Dropdown list

### ISSUE THREAD

**Issue by tranhao167** [KillerCodeMonkey/ngx-quill#1411]
Hi KillerCodeMonkey,
I have a problem with Quill-Mention, I want to hover in 1 item in dropdown when I mention "@", so I can have a nested dropdown , which is a child of the parent item I hovered. Can I do that?
 Sorry my English is not good. Thank u so much, Master!

**Comment by KillerCodeMonkey** [comment]
since this is a quill-mention question it would be the best to ask it at the their repository :).

I am not an expert on how to customize or use quill-mention. Just added it to my demo repo for preview purposes.
