### ISSUE TITLE
Compatibility with Angular 13

### ISSUE THREAD

**Issue by PavelChugreev** [KillerCodeMonkey/ngx-quill#1414]
I have a problem with download ngx-quill for ng 13 version
quill, types etc have installed according tto guide

![image](https://user-images.githubusercontent.com/67838245/140883248-611e981c-77c7-43c8-9c81-73bddaaa3784.png)

**Comment by KillerCodeMonkey** [comment]
@PavelChugreev i stayed at rxjs 6.5.x so for now just downgrade rxjs.

Feel free to send me a pr with upgraded rxjs version. I think i missed it during manually upgrading

**Comment by PavelChugreev** [comment]
@KillerCodeMonkey  Thanks, but I tried 6.5v rxjs - unfortunately the same result

**Comment by KillerCodeMonkey** [comment]
strange check my demo repo. i am using it already in my demo repo and it is working

**Comment by KillerCodeMonkey** [comment]
@PavelChugreev could you try v16.0.1? i set the peerDependency for rxjs to the same versions angular did

**Comment by PavelChugreev** [comment]
@KillerCodeMonkey 
Ok, thanks, I will try
But now i solve it by install with --legacy-peer-deps flag

**Comment by KillerCodeMonkey** [comment]
feel free to close the issue, if it is working for you
