### ISSUE TITLE
Display styles in ngModel

### ISSUE THREAD

**Issue by pcusi** [KillerCodeMonkey/ngx-quill#1416]
Hi, it is possible set styles in ngModel?
![Captura de Pantalla 2021-11-12 a la(s) 11 48 46](https://user-images.githubusercontent.com/46265371/141503812-d67bf3f7-b101-456d-85b1-af8f7bc71b0e.png)

**Comment by KillerCodeMonkey** [comment]
yes should be possible.

If you are using the format html you can just pass a valid quilljs html content string to the model

**Comment by pcusi** [comment]
hi Killer, thanks for the answer.

Currently i have the format in HTML, i can't pass any styles to my html tags.

**Comment by KillerCodeMonkey** [comment]
depends on how you pass it. if they are valid quilljs formattings and classes then it should work.

**Comment by pcusi** [comment]
where can i see an example? please

**Comment by KillerCodeMonkey** [comment]
just grabbed a stackblitz from someone else:
https://stackblitz.com/edit/angular-ivy-3gdxlw?file=src%2Fapp%2Fapp.component.ts

**Comment by KillerCodeMonkey** [comment]
you can checkout https://quilljs.com/docs/formats/#inline colors are need to be set inline
