### ISSUE TITLE
ngx quill crashed on huge pictures

### ISSUE THREAD

**Issue by franconeilglovasa** [KillerCodeMonkey/ngx-quill#1423]
ngx-quill crashed if you attach around 3mb pictures. has anyone tried to get it over?

Thanks

**Comment by KillerCodeMonkey** [comment]
this is a quilljs limitation. in general it is not a good idea to use the default quilljs image implementation, since it adds base64 string for the images.

You should use a custom module to upload files and only use urls.

**Comment by KillerCodeMonkey** [comment]
e.g. https://github.com/quilljs/quill/issues/2980
