### ISSUE TITLE
fixture.detectChanges() leads to unresolvable Problem in fakeAsync zone

### ISSUE THREAD

**Issue by activenode** [KillerCodeMonkey/ngx-quill#1425]
Angular Version: 12 

"ngx-quill": "^14.3.0",
"quill": "^1.3.7",

The problem is pretty easy to reproduce. Create a test component containing any quill instance.

Then if you do

```
beforeEach(() => {
  fixture.detectChanges()
})
```

everything works fine.

However if you do:

```
beforeEach(fakeAsync(() => {
  fixture.detectChanges();
});
```

it will always fail with a `timer still in queue` problem.

**Comment by activenode** [comment]
It also seems to be somehow troublesome to provide a demo since the newest versions of `ngx-quill` do not properly work in CodeSandbox nor in Stackblitz e.g. see here https://stackblitz.com/edit/angular-ivy-cqfy7t?file=package.json

My assumption is that both problems could be due to the dynamic loading but I am really not entirely sure.

**Comment by activenode** [comment]
So. Considering the Sandbox problems: It seems the only version that is still working in Sandboxes is 12.x especially 12.0.1 I tested succesfully with this fork in angular v9 https://stackblitz.com/edit/ngx-quill-example-rdindu?file=package.json

**Comment by activenode** [comment]
As a matter of fact I tested it locally now since the Sandboxes were troublesome, especially for testing. Now with `ngx-quill@12.0.1` and `quill@1.3.7` in combination with Angular 9.1.13 i cannot reproduce the bug.

**Comment by activenode** [comment]
Okay the problem that we experience also exists with earlier versions: Here is a repository you can checkout which will show you the "timer problem" when running npm test

https://github.com/activenode-bugs/ngx-quill-fakeAsync-problem

**Comment by KillerCodeMonkey** [comment]
Maybe it has something to do that during initialisation requestAnimationFrame is used to trigger change detection after init.

I would try to run `tick()` before or after change detection.

**Comment by activenode** [comment]
Unfortunately that does not help. We tried multiple different ways.

![image](https://user-images.githubusercontent.com/9058762/143400857-9db92093-4633-4d23-949f-8bbe28f4f536.png)


Feel free to clone the above sample repo.

**Comment by activenode** [comment]
If you call `flush()` then another quill error reveals: Loading chunk failed -> which is due to the `await import('quill');` such that it is probably in the process of `await import('quill')` (< timer) and then when it is flushed obviously the import will be canceled and hence the chunk loading fails. 

The problem however is WHY it even leads to that problem. Should the `await import('quill')` maybe be a top-level import instead of a dynamic one?

```
beforeEach(async() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [QuillModule.forRoot()]
    }).compileComponents();

    fixture = TestBed.createComponent(AppComponent);
    await fixture.whenStable();
    await fixture.whenStable();
  });

  it('shows a flake', fakeAsync(() => {
    tick();
    fixture.detectChanges();
    tick();
    expect().nothing();
    flush();
  }));
```

![image](https://user-images.githubusercontent.com/9058762/143402405-fdd5245e-2468-45a7-a1dd-d682262c3853.png)

**Comment by KillerCodeMonkey** [comment]
Strange because I do not have any problems in my unit tests.

There are some with fakeasync as well.

Since this project is growing over years I forget some implementation
details :).

I knew that there is an optional debounce timer for change detection in the
editor.

Maybe this debouncing is running and you need to add a tick() with some
milliseconds as Parameter.


David Lorenz ***@***.***> schrieb am Do., 25. Nov. 2021,
08:50:

**Comment by activenode** [comment]
In your unit tests you are always calling a `fixture.detectChanges()` BEFORE in a NON-fakeAsync zone as far as I could see. This will allow `await import('quill')` to be resolved outside the fakeAsync zone. If you then call another `detectChanges()` afterwards INSIDE a `fakeAsync` zone then yes, it will work.

The problem is however: This is not a solution if you are e.g. fetching data in `ngOnInit` because then you need the first `detectChanges()` to be already in the `fakeAsync` zone.

So it is about the really first one.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by activenode** [comment]
Unfortunately no. We did do a workaround but it's pretty "over-engineered" IMO:

Apparently quill/ngx-quill needs `fixture.detectChanges()` to be ran outside of fakeAsync to ensure proper loading.

But that also triggers `ngOnInit`. Hence we do this:

```
// 1. catch the init call to avoid the actual call
const initSpy = spyOn(component, 'ngOnInit');

// 2. detectChanges for ngx-quill
fixture.detectChanges();

// 3. fall back again
initSpy.and.callThrough()
```

**Comment by KillerCodeMonkey** [comment]
since i do not see what i can do here, i will close this issue.
