### ISSUE TITLE
intercept insert image ngx-quill on angular

### ISSUE THREAD

**Issue by franconeilglovasa** [KillerCodeMonkey/ngx-quill#1428]
Hi!

Is there a way to intercept image before posting it to ngx-quill? I wish to compress the base64 image before posting it to ngx-quill. I tried to changing the pictures by onContentChanged by looking at the json and compress it but its a bad idea.

Here's my attempt:

https://stackblitz.com/github/franconeilglovasa/quill-test

**Comment by KillerCodeMonkey** [comment]
you need to specify and pass an imageHandler to the quilljs module config.

https://quilljs.com/docs/modules/toolbar/#handlers

just search through the quilljs issue.
You will find many issues and example handlers, .e.g uploading an image before inserting and so on
