### ISSUE TITLE
Help needed to use in server side rendering project

### ISSUE THREAD

**Issue by coderrepo** [KillerCodeMonkey/ngx-quill#143]
How to use in SSR environment?

**Comment by KillerCodeMonkey** [comment]
Just search through the issues with keywords SSR or angular universal.
There are some issues with workarounds. Short answer:

Quilljs uses the document object which does not exist on serverside. So you
need to mock it.

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/91
https://github.com/KillerCodeMonkey/ngx-quill/issues/71
