### ISSUE TITLE
Angular 9

### ISSUE THREAD

**Issue by guypeled1** [KillerCodeMonkey/ngx-quill#1432]
How do I install the ngx-quill editor for an angular app?

**Comment by guypeled1** [comment]
I mean angular 9, 
it write me an error :
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">=13.0.0" from ngx-quill@16.0.1


I can't update my angular version it will cause me a lot of errors.

**Comment by KillerCodeMonkey** [comment]
Install a version <12. But keep in mind - I only support maintained version by angular. ;-).

So no fixes or help or updates for outdated ones.

**Comment by KillerCodeMonkey** [comment]
Yes .... And I mean ngx-quill version <12...
