### ISSUE TITLE
ngx-quill error while implementing

### ISSUE THREAD

**Issue by facundoBungee** [KillerCodeMonkey/ngx-quill#1437]
Hi KCM ,

Experiencing these errors while trying to implement your solution in my Angular project. Any clue to why this is happening will be highly appreciated. Already followed Readme instructions and tried deleting node_modules and re-installing. Thks!

ERROR in ./node_modules/ngx-quill/fesm2015/ngx-quill.mjs 610:191-211
[ng] Can't import the named export 'ChangeDetectorRef' from non EcmaScript module (only default export is available)

**Comment by KillerCodeMonkey** [comment]
which ngx-quill and angular version do you use?

**Comment by facundoBungee** [comment]
I am using Angular 9.

**Comment by facundoBungee** [comment]
I am now experiencing a different error: 
ERROR in ./node_modules/ngx-quill/fesm2015/ngx-quill.mjs 610:191-211
[ng] Can't import the named export 'ChangeDetectorRef' from non EcmaScript module (only default export is available)

**Comment by KillerCodeMonkey** [comment]
Which ngx-quill version?

Check the releases page and search for an ngx-quill version that supports
angular 9.

I only support maintained angular versions ... Angular 9 is not supported
anymore And angular V10 is only supported til Christmas this year.



facundoBungee ***@***.***> schrieb am Fr., 10. Dez. 2021,
15:36:

**Comment by facundoBungee** [comment]
thks!
