### ISSUE TITLE
How to override css  inside quill-editor? 

### ISSUE THREAD

**Issue by jagabs** [KillerCodeMonkey/ngx-quill#144]
![screen shot 2018-03-25 at 1 46 43 pm](https://user-images.githubusercontent.com/17292042/37872111-104c048e-3033-11e8-953b-75d58cb32bd6.png)

![screen shot 2018-03-25 at 1 46 39 pm](https://user-images.githubusercontent.com/17292042/37872114-2a77d34c-3033-11e8-9a82-65f2b181a0a7.png)

![screen shot 2018-03-25 at 1 49 38 pm](https://user-images.githubusercontent.com/17292042/37872121-75487868-3033-11e8-8882-97f91356c869.png)

The last pic, it automatically gets left -40:px when clicking the add vid URL.

**Comment by KillerCodeMonkey** [comment]
Just pass another "bounds" property to the editor component. I lately added
the Option to pass bounds="'self'". So every box opens inside the editor
container.

Default bound is documenta.body ;)

**Comment by jagabs** [comment]
thanks, works like a charm. One more thing, how can i override the css for the ql-blockqoute ql-active, like the pic ive uploaded.

**Comment by KillerCodeMonkey** [comment]
Do not know. Such question should be asked in the quilljs repo :)
