### ISSUE TITLE
add quill editor to div

### ISSUE THREAD

**Issue by guypeled1** [KillerCodeMonkey/ngx-quill#1441]
Hi, I am using ngx-quill om angular 13.
How can I add quill to a div?
I need to be able to add div to edit the content of a div in the content. like this:
```
<div id="content">
      content 1
     content 2
     ...
</div>
```

to edit the content of the div with id content. and that it will look like in the example here: https://quilljs.com/

Thanks,
Guy

**Comment by KillerCodeMonkey** [comment]
sorry but i do not understand your question.

In general the quill editor is initialised on a div
`<div quill-editor-element></div>`

**Comment by guypeled1** [comment]
so how can I make it looks like in the example here: 
https://quilljs.com/
I want this example: https://prnt.sc/22saoho

Thanks

**Comment by KillerCodeMonkey** [comment]
the editor looks very similar to: https://killercodemonkey.github.io/ngx-quill-example/

Just make css changes if you want to make it look differently.
