### ISSUE TITLE
inline editor

### ISSUE THREAD

**Issue by guypeled1** [KillerCodeMonkey/ngx-quill#1446]
Hi,
do you have the option to add an inline-editor?

**Comment by KillerCodeMonkey** [comment]
What do you mean with online editor?

guypeled1 ***@***.***> schrieb am Fr., 17. Dez. 2021, 13:19:

**Comment by KeithGillette** [comment]
@guypeled1 — You could use `ngx-quill` with a template-driven inline editor like [the PrimeNG InPlace component](https://www.primefaces.org/primeng/showcase/#/inplace) to accomplish rich-text in-line editing.
