### ISSUE TITLE
v16.1.1: Quill Editor is not a known element

### ISSUE THREAD

**Issue by ln56b** [KillerCodeMonkey/ngx-quill#1450]
Hi, 

I installed `ngx-quill`  package to` v16.1.1` but I could not get `<quill-editor>` recognized by my component (Quill editor is not know element)
As I initially followed the process installation, I tried to downgrade ngx-quill and it now works (I am now on `v14.3.0`)

Has there been any change in the installation process that could explain this difference ?

Thanks

**Comment by KillerCodeMonkey** [comment]
You are using angular 13?

Hélène Baudrand ***@***.***> schrieb am Mi., 29. Dez. 2021,
15:11:

**Comment by ln56b** [comment]
Angular 12

**Comment by KillerCodeMonkey** [comment]
And if you check the readme you will find the info that v16 only supports
angular 13

Hélène Baudrand ***@***.***> schrieb am Mi., 29. Dez. 2021,
17:00:

**Comment by ln56b** [comment]
Ok sorry I forgot to read it again, thanks for your prompt answer !
