### ISSUE TITLE
Question: DragNDrop of custom items into the editor

### ISSUE THREAD

**Issue by Latanyor** [KillerCodeMonkey/ngx-quill#1455]
I've tried to implement an editor with a list aside of it. In the list some items are shown and I want to dragnDrop them into the editor and represent them with a custom Blot (a rectangle around some of data and an icon).

I've got the Blot kinda working ( it can be displayed via a shortcut in the editor) but I've not found a way to make the dragged item transform into the Blot at drop or at least get the position within the editor, where the Blot shall be displayed. 

Is there any easy way to do this? All I can find are Image drag and drop functions, which are not helpful for my case. 

Thanks in advance :) 

I'm working on Angular 11. 

PS. Some images of my work so far:
![person_list](https://user-images.githubusercontent.com/35563666/148522397-a28bb0c1-42fb-43cf-af9c-3c9096073d0c.PNG)
The List of Item(s) aside the editor

![editor_icon](https://user-images.githubusercontent.com/35563666/148522464-1e9c2a9e-039d-45d6-a7a9-1bbc39ff03cd.PNG)
The Custom Blot within the editor with some text around it.

**Comment by KillerCodeMonkey** [comment]
hey there,

sadly i do not have much experiences with that.
I would guess you should check the quilljs repo for similar questions.

**Comment by Latanyor** [comment]
Thanks for the reply I will do that.
