### ISSUE TITLE
(onEditorCreated) is not executed properly if i have [ngModel] at the same time

### ISSUE THREAD

**Issue by basilismt8** [KillerCodeMonkey/ngx-quill#1458]
Hi! I'm facing an issue, I have a function inside that activates the right to left orientation for the text. 

function code:
```
    activateRTL(editor){
        editor.format('align', 'right');
        editor.format('direction', 'rtl');
    }
```

if i have [(ngModel)] at the same time in quill directive the rtl direction is not activated. Also the quill editor is inside a mat expansion panel.

Here is my template code:

```
    <mat-expansion-panel *ngFor="let text of ageCategoriesTranslastions; let i = index">
        <mat-expansion-panel-header >
            <mat-panel-title>{{'exhibit.Exhibit description for the age category' | translate}} {{text.name}}</mat-panel-title>
        </mat-expansion-panel-header>
                <quill-editor (onEditorCreated)="activateRTL($event)" [styles]="{'max-height': '15rem','min-height': '1rem','overflow-y': 'scroll' }" [ngModel]="exhibitdata.description[i].description" [placeholder]="quillplaceholder">
                </quill-editor>
...
```

My angular cli version is 7.3.10 and ngx-quill version is 5.2.0.

I would greatly appreciate it if you could help me solve this problem. 

Thanks!!!

**Comment by KillerCodeMonkey** [comment]
You should definitely update your project.

I do not support such old versions.
Many things have changed. Check the readme for supported angular and
compatible ngx-quill versions

basilismt8 ***@***.***> schrieb am Do., 13. Jan. 2022, 13:09:

**Comment by basilismt8** [comment]
Thanks for your quick reply!!! I know i know :p, you have right!!! I will upgrade my project because I have been saying to do it for a long time, so I hope my problem will be solved! Thank you very much again for your quick reply!!!

**Comment by KillerCodeMonkey** [comment]
i will close this issue and feel free to come back later, if the issue exists after upgrading angular
