### ISSUE TITLE
Quill Unexpected token export in Angular5

### ISSUE THREAD

**Issue by skuzmin** [KillerCodeMonkey/ngx-quill#146]
Hi,
I have similar problem. I have used Angular2 and ngx-quill-1.2 before, and everything was good.
Today I have updated project to Angular5 and ngx-quill-2.2.0 and I got next error:

Uncaught SyntaxError: Unexpected token export at Object.<anonymous> (app.js:2934) at __webpack_require__ (polyfills.js:53) at eval (eval at <anonymous> (app.js:1804), <anonymous>:26:17) at Object.<anonymous> (app.js:1804) at __webpack_require__ (polyfills.js:53) at eval (eval at <anonymous> (app.js:136), <anonymous>:32:23) at Object.<anonymous> (app.js:136) at __webpack_require__ (polyfills.js:53) at eval (eval at <anonymous> (app.js:87), <anonymous>:7:12) at Object.<anonymous> (app.js:87) at __webpack_require__ (polyfills.js:53) at Object.<anonymous> (app.js:6) at __webpack_require__ (polyfills.js:53) at webpackJsonpCallback (polyfills.js:24) at app.js:1

I use simple webpack project. (no SystemJs stuff)
Any suggestions ?

P.S. I reverted quill to version 1.2, I have warnings in npm, but at least it works with Angular5

Thank you!

**Comment by KillerCodeMonkey** [comment]
sounds like a build process problem of your project. Maybe you are missing some Polyfills?
checkout my demo repository. it is a simple webpack and it works.

**Comment by skuzmin** [comment]
Thx, for super quick response. I will deeply investigate this, and give you feedback tomorrow :)

**Comment by skuzmin** [comment]
Hi,
I spent coupe of house, but haven't figure out problem yet. It seems problems with webpack.
After some changes in webpack, I got new error :) **Quill is not a constructor**

So for now I'm planning to use version 1.2. It works with angular5 but with warning. I will rewrite webpack in future, and I hope the latest version of editor will work.

anyway thank you for your time :)
