### ISSUE TITLE
Formatting doesn't inherits while pasting inside text inside quill editor

### ISSUE THREAD

**Issue by Eshap09** [KillerCodeMonkey/ngx-quill#1461]
While pasting in my local host formatting works perfectly, but after production build it breaks i.e formatting doesn't inherit. It is not getting the attributes.

**Comment by KillerCodeMonkey** [comment]
could you explain it a little bit more in detail.

Since i have no special handling for copy and paste i would guess it is an Quill or an Angular issue.

could you check copy and paste on the quilljs page and on my demo page?
