### ISSUE TITLE
Quill being initialized too early

### ISSUE THREAD

**Issue by jpike88** [KillerCodeMonkey/ngx-quill#1462]
While a component is being loaded, it seems that quill is initing a split second too early and doesn't pick the #toolbar div that sits next to ngx-quill. The toolbar div isn't being an ngIf or anything, so there's no reason why it shouldn't be visible to quill as it initializes.

Temp workaround is to put ngx-quill behind an ngIf flag, and toggle that flag with setTimeout of 300 ms. Obviously not an ideal workaround.

**Comment by KillerCodeMonkey** [comment]
but that is nothing i can solve. instead of the timeout you could try to grab your toolbar container as @ViewChild as template var `#toolbar` and just check with *ngIf at the quill-editor component if the viewchild or template var is defined
