### ISSUE TITLE
quill not displaying

### ISSUE THREAD

**Issue by depperm** [KillerCodeMonkey/ngx-quill#1467]
Neither the quill-editor or quill-view display anything.

angular v11
ngx-quill v13

package.json
```
"dependencies": {
  "@angular/common": "11.0.0",
  "@angular/core": "11.0.0",
  "@angular/forms": "11.0.0",
  "@angular/platform-browser": "11.0.0",
  "ngx-quill": "13.0.0",
  "rxjs": "6.3.3",
  ...
"devDependencies": {
  ...
  "quill": "^1.3.7"
```
style.scss
```
@import '~quill/dist/quill.core.css';
...
```
app.module.ts
```
imports: [
  ...
  QuillModule.forRoot()
```
my-component.html
```
<p>{{faq.answer}}</p>
<quill-view [content]="faq.answer"></quill-view>
<quill-editor [(ngModel)]="faq.answer"></quill-editor>
```
![image](https://user-images.githubusercontent.com/8761660/150807068-13b59a42-45dd-44e2-a686-0ce76183dd22.png)

**Comment by KillerCodeMonkey** [comment]
I guess it is because of the material component it is in.

There are some closed issues about material ui and ngx-quill.

Try to use it outside any mui component.

depperm ***@***.***> schrieb am Mo., 24. Jan. 2022, 15:51:

**Comment by KillerCodeMonkey** [comment]
if i would guessing around -> just add the component with ngIf after the panel gets active/visible. i think the dom node is not rendered before, so quilljs could not find the element

**Comment by depperm** [comment]
adding a ngIf doesn't change anything. I also tried moving it outside of the expansion panel and mat-card, without success.

**Comment by depperm** [comment]
If there are some issues with material ui, I'll look for a different markdown editor. Yours did look quite clean/minimalist compared to others.

**Comment by KillerCodeMonkey** [comment]
And any error in your console?

Maybe just some missing styles?

depperm ***@***.***> schrieb am Mo., 24. Jan. 2022, 16:19:

**Comment by vrxj81** [comment]
I only see you importing the core.css, also import the snow.css (snow is the default theme)

**Comment by KillerCodeMonkey** [comment]
i will close this for now... since no answer for 4 days

**Comment by KillerCodeMonkey** [comment]
it is working for me:
![Bildschirmaufnahme vom 2022-02-01 19:28:00](https://user-images.githubusercontent.com/2264672/152028697-e335ce41-d565-43b6-9da2-1e00b96b7f6e.png)

Maybe a browser addon is blocking it?

**Comment by sergeyglazyrindev** [comment]
hey @KillerCodeMonkey 
I've figured it out. Now it works in my project, the issue was I didn't import it in whole module hierarchy. the project is really complicated...
Thank you for the help!
