### ISSUE TITLE
Documentation Update regarding CSS 😄

### ISSUE THREAD

**Issue by dertuerke** [KillerCodeMonkey/ngx-quill#1470]
Hi, I noticed that there is an issue in the documentation.

You don't need to import all 3 CSS files.
It is enough if one of the 3 files is loaded.

Bubble/Snow are themes and they already contain the core styles.

This makes a difference of about 15kb (minify).

🤟

**Comment by KillerCodeMonkey** [comment]
Feel free to add that and send me a pr ;-)

dertuerke ***@***.***> schrieb am Mi., 26. Jan. 2022, 14:04:

**Comment by KillerCodeMonkey** [comment]
closed with #1471
