### ISSUE TITLE
Question: Is it possible to set a character limit on quill-view?

### ISSUE THREAD

**Issue by andliang** [KillerCodeMonkey/ngx-quill#1474]
The `quill-editor` has a `maxLength` attribute but does `quill-view` have a similar attribute? I would like to display a limit of 50 characters.

Thanks!

Big shout out to KillerCodeMonkey for his amazing work!

**Comment by KillerCodeMonkey** [comment]
Just listen to the onContentChanged output. There you get the editor
instance, text, html and delta content.

Now you can check if the length is > your max length and cut it.

Or if you are using formcontrols just subscribe on the formcontrols "value
changes" event and patch the value when it is to long.

Some works with ngModel and ngModelChanged

andliang ***@***.***> schrieb am Sa., 29. Jan. 2022, 17:09:

**Comment by andliang** [comment]
> Just listen to the onContentChanged output. There you get the editor
> instance, text, html and delta content.

onContentChanged doesn't seem to work on quill-view. Her's my sample code

`<quill-view  [content]="content" format="json" theme="snow" [formats]="formats" (onContentChanged)="onContentChanged($event)"></quill-view>`


Also, I'm using quill-view and not quill-editor so would I be able to get the editor instance? Is quill-view a subtype of quill-editor component? 

Thanks!

**Comment by KillerCodeMonkey** [comment]
Ah sorry did not see it is about quill-view.

It is not supported directly via angular Input.

But I think you can use onEditorCreated event and use the native quill API
to get the text length (quillInstance.getText().length).

Or you can use quill-editor component. Set toolbar to false and set
read-only to true ;-)

andliang ***@***.***> schrieb am So., 30. Jan. 2022, 14:53:
