### ISSUE TITLE
Strange behavior (lines are merged)

### ISSUE THREAD

**Issue by lorien** [KillerCodeMonkey/ngx-quill#1479]
Hello guys. Please, do you have any ideas why such thing happen?

### How to Reproduce
Write ten lines, one char per line. Click "Save" button.
Reload page. Reload page. Keep reloading until you see the bug.
 I am referring here to our UI which we use to edit a message. By each reloading the page we just load the editor component with SAME content. Most of times the editor component renders HTML correctly. But some time it fails.

### Normal rendering

![image](https://user-images.githubusercontent.com/35171/150965503-769ecd02-682b-435f-92c5-d29685b626cd.png)

### Invalid rendering

![image](https://user-images.githubusercontent.com/35171/150965565-f6f8edbd-d921-4a50-8f76-a836a2531f8c.png)

**Comment by KillerCodeMonkey** [comment]
looks like a timing problem. do you use something like material ui tabs?

It is a known problem. You have to render the editor after the tab is getting active.

**Comment by apocarteres** [comment]
> looks like a timing problem. do you use something like material ui tabs?
> 
> It is a known problem. You have to render the editor after the tab is getting active. i found and old quilljs issue as well: [quilljs/quill#2393](https://github.com/quilljs/quill/issues/2393)

hi @KillerCodeMonkey thanks for quick reply. No, we don't use Angular Material, just plain old bootstrap tabs. However, what you are saying makes sense, cause  issue is clearly reproducible on traversing the tabs. It also reproducible when page gets reloaded but reproduce rate is much lower. 

I also came up with assumption  about timing, for now seems setTimeout() with does the trick for us.

**Comment by KillerCodeMonkey** [comment]
okay thanks for the answer.

case closed :D
