### ISSUE TITLE
How to add a new button to the tool bar 

### ISSUE THREAD

**Issue by vibingopal** [KillerCodeMonkey/ngx-quill#148]
Is there any way to add a new button to the tool bar like SAVE.
Below is my requirement

![image](https://user-images.githubusercontent.com/17860925/38165213-c142f620-34d5-11e8-9d32-356439bac42a.png)

**Comment by KillerCodeMonkey** [comment]
Check out quill documentation. You could pass custom HTML code AS toolbar
(check the read me)

Maybe this works. Or you habe to add a custom module for that (check my
demo repository and the word count module )

Greets.

**Comment by vibingopal** [comment]
Thanks for the response. I will try that out. Will this module works with new Angular Version. Currently iam using Angular 5.

**Comment by KillerCodeMonkey** [comment]
i think so. hopefully there are not so many breaking changes ;).

I will close this issue, because it is not module related (more quilljs) related.
If you need further help, you can comment to the closed topic, and i will try to check this out.

**Comment by vibingopal** [comment]
Sure .Will do. Thank you for your quick response always . Take care :)
