### ISSUE TITLE
Code entered in the code block is rendered as a string instead of elements

### ISSUE THREAD

**Issue by firedrake08** [KillerCodeMonkey/ngx-quill#1485]
When I enter some code in the code block of the quill editor, it renders in the browser as a string. Though it looks ok, but I am unable to apply some styles to the view. When code is displayed in the browser, ngx-quill puts the starting and ending tags in a span with class "hljs-name". But for me, when I am entering some code, it is not putting them in the .hljs-name span. Instead, it is rendered as a string like,
![quill-code](https://user-images.githubusercontent.com/53935837/154017619-f843a163-edfc-45b2-b823-e8e5fb524313.JPG)

**Comment by KillerCodeMonkey** [comment]
can you share some code? or just check my demo repo? there you have examples for code highlighting

**Comment by firedrake08** [comment]
yes, of course. Below are the CDNs that I have used in the `index.html` :
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/monokai-sublime.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>`

Below is the modules object I am using:
`this.modules = {
      formula: true,
      imageResize: {},
      syntax: true,
      toolbar: [
        ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
        ['blockquote', 'code-block'],    
        [{ 'header': 1 }, { 'header': 2 }],               // custom button values
        [{ 'list': 'ordered'}, { 'list': 'bullet' }],
        [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
        [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
        [{ 'direction': 'rtl' }],                         // text direction    
        [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],    
        [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
        [{ 'font': [] }],
        [{ 'align': [] }],    
        ['clean'],                                         // remove formatting button    
        ['link', 'image', 'video']                         // link and image, video
      ]
    };`
One day it was working fine but now it is not working.

**Comment by KillerCodeMonkey** [comment]
so your problem exists when you render it outside of ngx-quill editor?

**Comment by KillerCodeMonkey** [comment]
btw: do you configured your supported language?

```JS
<script>
    hljs.configure({
      languages: ['javascript', 'ruby', 'bash']
    });
  </script>
```

**Comment by firedrake08** [comment]
yes, it is configured
`<script>
    hljs.configure({
      languages: ['javascript', 'ruby', 'bash']
    });
  </script>`

**Comment by KillerCodeMonkey** [comment]
but it seems you are passing html code to the codeblock... and html is not configured then

**Comment by KillerCodeMonkey** [comment]
and it seems your doctype is not closing

**Comment by firedrake08** [comment]
It is working perfectly fine. Thank you very much. Do I need to add the `<!DOCTYPE html>` everytime?

**Comment by KillerCodeMonkey** [comment]
do not know it is your editor content you are passing^^. If you want to add it.. do it, if not... then remove^^

**Comment by firedrake08** [comment]
ok...but there is a small doubt. You can see that the body tag is not highlighted.
![issue-2](https://user-images.githubusercontent.com/53935837/154074553-2e4b31a9-7635-47e5-ac5b-90faafc53566.JPG)
.

**Comment by firedrake08** [comment]
The html and body tag are not included in the 'hljs-tag' span.
![issue-3](https://user-images.githubusercontent.com/53935837/154074859-d7aa8c64-da31-4942-a0cf-7e83282960f7.JPG)
n

**Comment by KillerCodeMonkey** [comment]
yeah but thats not a business of ngx-quill. more of the hljs i think.

**Comment by firedrake08** [comment]
So, I should use a different highlighter CDN, right?

**Comment by firedrake08** [comment]
Please let me know of any highlighters that will not break with ngx-quill.

**Comment by firedrake08** [comment]
I think this issue needs to be closed. Thank you very much
