### ISSUE TITLE
Custome font size is not applied to the quill content at version 15.0.0

### ISSUE THREAD

**Issue by zhonglin94** [KillerCodeMonkey/ngx-quill#1486]
I register a custom font size list via the following.

1. In angular module.
> `		QuillModule.forRoot({
> 			customOptions: [
> 				{
> 					import: 'attributors/style/size',
> 					whitelist: FontSizeList
> 				}
> 			]
> 		}),
> `
2. In angular component
> `	readonly modules = {
> 		toolbar: [
> 			[{ 'size': FontSizeList }], 
> 		]
> 	};
> `
3. The font size list

> `export const FontSizeList: string[] = ['10px', '12px', '14px', '16px'];
> `

But the font size option in the list **cannot** be applied the quill content
![image](https://user-images.githubusercontent.com/32061513/154041632-01242ab6-0ac2-4682-b606-2d8f64dc55c1.png)

If I **downgrade the ngx-quill to 14.0.0, it works again**. So I guess there are some bugs relating to this feature in version 15.0.0

Btw, my quill version is **1.3.7**.

**Comment by KillerCodeMonkey** [comment]
any update?

**Comment by KillerCodeMonkey** [comment]
close due to inactivity
