### ISSUE TITLE
How can I drop text to mouse position?

### ISSUE THREAD

**Issue by YSFKBDY** [KillerCodeMonkey/ngx-quill#1488]
I am using Quill Editor Component in my Angular project. And I want to drop some texts to the editor. While dropping, editor loses focus, so **getSelection()** is always null for me. Because of that, I want to drop text to mouse's cursor position.

How can I do that?

**Comment by KillerCodeMonkey** [comment]
just listen on selection changed output all the time and store the last position? if the selection gets null you now you lost focus, but you know the selection before.

**Comment by YSFKBDY** [comment]
I just did that and that works. But still I can't drop it where the mouse is. I don't know that is possible though?

**Comment by KillerCodeMonkey** [comment]
do not know. i am just building the angular wrapper of native quilljs. Check the issues there.
I think there are many about drag and drop
