### ISSUE TITLE
Usage of Quill modules in angular universal

### ISSUE THREAD

**Issue by Jeremias-Nater** [KillerCodeMonkey/ngx-quill#1492]
I have already read all of the content of the following related Issues: #91 and #57.

## Error:
When running dev:ssr i get the following error:  
`ReferenceError: document is not defined`  

Solutions from above mentioned issues did not help as following.
#### Code i need to implement
I need to implement the following code to add icons to my custom "undo" and "redo" actions.
```typescript
const isBrowser = isPlatformBrowser( platformId );
if ( isBrowser ) {
    const icons = Quill.import( 'ui/icons' );
    icons[ 'undo' ] = quillUndoIcon;
    icons[ 'redo' ] = quillRedoIcon;
}
```
#### Mocked "document" global in server.ts (not helping)
i have tried mocking the document with domino, but somehow its still saying document is not defined..
```
const template = fs
  .readFileSync( path.join( join( process.cwd(), 'dist/lebenslauf-generator/browser' ), 'index.html' ) )
  .toString();

// Shim for the global window and document objects.
const window = domino.createWindow( template );
global[ 'window' ] = window;
global[ 'document' ] = window.document;
```

#### Usage of quill with require
I have also tried avoiding the quill import by requiring Quill in an `if isBrowser` statement:
```
  const Quill = require( 'quill' );
  const icons = Quill.import( 'ui/icons' );
  icons[ 'undo' ] = quillUndoIcon;
  icons[ 'redo' ] = quillRedoIcon;
```
while this resolved the error on compilation, it broke quill on the client.

### What next?

So should i mock a quill component somehow? How would i do that? Could you provide a mocked version for the server or something?

Also i dont quite understand: We would mock the ngx-quill component but i dont think this would fix the problem which is caused by the following import: 
`import Quill from 'quill';`

**Comment by KillerCodeMonkey** [comment]
which ngx-quill version do you use?

it should work since some versions.
i created a demo repo some time ago: https://github.com/KillerCodeMonkey/ngx-quill-universal-example

**Comment by KillerCodeMonkey** [comment]
But do you use ngx-quill at all?

**Comment by Jeremias-Nater** [comment]
@KillerCodeMonkey Oh im sorry, yes i am. im importing the module in app.module with `withRoot` and config etc.

The version for ngx-quill is: "[ngx-quill](https://npmjs.com/package/ngx-quill)": "[^16.1.2](https://npmjs.com/package/ngx-quill)",`

Should i be adding those icons in the config passed to QuillModule.withRoot or something?

**Comment by KillerCodeMonkey** [comment]
I could try. I do not exactly if it is working with icons. But in general you could use the QuillService to get the l global quill instance and be ssr read. Check the source of the quill-editor.component.ts

Greets

**Comment by Jeremias-Nater** [comment]
Allright, i think you are referring to `this.service.getQuill()` in [quill-editor.component.ts](https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.ts) on line 214.

So i would be using
```
constructor(private quillService: QuillService) {
}
...
 const icons = this.quillService.getQuill().import( 'ui/icons' );
  icons[ 'undo' ] = '';
  icons[ 'redo' ] = '';
```
And this should be working with SSR?

Since its already evening where i live, i will be trying this tomorrow. Please inform me if this is not what i should try.

**Comment by Jeremias-Nater** [comment]
@KillerCodeMonkey  I just noticed that getQuill returns an observable, but if everything else is right i will get it working.

**Comment by KillerCodeMonkey** [comment]
Keep in mind to check if you are in browser and the service function is returning an observable you need to subscribe ;-).

**Comment by Jeremias-Nater** [comment]
Thanks for your help, heres the working code for Angular Universal SSR:

```typescript
constructor(  private quillService: QuillService,
              @Inject( PLATFORM_ID ) private platformId: Object ) {
  this.isBrowser = isPlatformBrowser( platformId );
  this.configQuillModules();
}

configQuillModules(): void {
  if ( !this.isBrowser ) {
    return;
  }
  this.quillService.getQuill().pipe( first() ).subscribe( ( quill ) => {
      const icons = quill.import( 'ui/icons' );
      icons[ 'undo' ] = quillUndoIcon;
      icons[ 'redo' ] = quillRedoIcon;
    },
  );
}
```

**Comment by Jeremias-Nater** [comment]
@KillerCodeMonkey Thanks again! It might be helpful to add a section about how to get the Quill instance in the documentation (maybe specifically at universal, since it doesnt matter if you import it like i did first otherwise)

**Comment by KillerCodeMonkey** [comment]
Feel free to send a pr :)

Jeremias Nater ***@***.***> schrieb am Di., 1. März 2022,
09:37:
