### ISSUE TITLE
How to add title labels in ngx quills

### ISSUE THREAD

**Issue by SujayDas1999** [KillerCodeMonkey/ngx-quill#1493]
I wanted to know if there is any way we can add some labels. 
For example when a user hovers on B button for bold he/she should see a bold tooltip. 
Or B(Bold) something like that.

**Comment by KillerCodeMonkey** [comment]
Use good old Javascript and or build your own custom toolbar.

Sadly that it's how it's done

Inu(フェニックス) ***@***.***> schrieb am Mo., 28. Feb. 2022, 11:49:
