### ISSUE TITLE
Auto detecting URL as the user types or paste a url

### ISSUE THREAD

**Issue by anvaymishra1** [KillerCodeMonkey/ngx-quill#1498]
I have been using this p[ackage for a project and it has been super helpful. I wanted to integrate the ability to detect as a user types in a URL but I am unable to do so. I tried using [quill magic URL ](https://www.npmjs.com/package/quill-magic-url)but it does not provide typings and I could not use it with ngx-quill. Is there a way to do so if I have missed the documentation?

**Comment by KillerCodeMonkey** [comment]
check out the readme and the demo repo.
you can pass custom modules in the forRoot config or per editor instance.

**Comment by KillerCodeMonkey** [comment]
e.G. https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/app.module.ts#L67

passing a custom module

```TS
import MagicUrl from 'quill-magic-url'

@NgModule({
  bootstrap: [AppComponent],
  declarations: [
    ...
  ],
  imports: [
    ...,
    QuillModule.forRoot({
      customModules: [{
        implementation: MagicUrl,
        path: 'modules/magicUrl'
      }]
    })
  ],
  providers: [],
  schemas: []
})
export class AppModule { }
```

**Comment by KillerCodeMonkey** [comment]
Same goes then for the "modules" config described in the readme of quillmagicurl. you can add this per default or pass it to the editor component.

Similar to this one using emoji module - https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/emoji/emoji.component.ts#L15
