### ISSUE TITLE
  Function calls are not supported in decorators but 'QuillModule' was called

### ISSUE THREAD

**Issue by chandiralekhasankar** [KillerCodeMonkey/ngx-quill#1499]
I am using 
   ```
"ngx-quill": "^9.2.0",
    "quill": "^2.0.0-dev.4",
    "quill-better-table": "^1.2.10",
    "quill-blot-formatter": "^1.0.5",
    "quill-delta-to-html": "^0.12.0",
```

Angular version
```
Angular CLI: 8.3.29
      Node: 14.18.1
      Angular: 8.2.14
```

 used QuillModule in library module for lazy loading.
```
import: [
    QuillModule.forRoot()
]
```

when I try to take build of my application I am getting the following issue.
**ERROR in Error during template compile of 'RequisitionModule'
  Function calls are not supported in decorators but 'QuillModule' was called.**
  
Could anyone help me to sort out this issue? please

**Comment by KillerCodeMonkey** [comment]
No support for quill 2 dev versions and check the readme for supported
angular versions.

chandiralekhasankar ***@***.***> schrieb am Do., 10. März
2022, 05:52:

**Comment by chandiralekhasankar** [comment]
@KillerCodeMonkey I used quill: 1.3.7 and that time also I faced this issue.  After that I found this issue occurred due to **forRoot()** [I imported QuillModule in my lazy loading module]

Do you have any idea to lazy load QuillModule without using **forRoot()**  any other way to solve this issue
