### ISSUE TITLE
Delta in reactive forms and a debounceTime

### ISSUE THREAD

**Issue by Marius-Romanus** [KillerCodeMonkey/ngx-quill#1514]
Hello!

The delta that is returned with the reactive forms and a debounceTime is not correct, it seems that it only returns the last letter instead of the whole set.

You can see it in your git examples: https://github.com/killerCodeMonkey/ngx-quill-example
In: src\app\reactive-forms\reactive-forms.component.ts line 52.

Example:

```
this.editor
  .onContentChanged
  .pipe(
	debounceTime(400),
	distinctUntilChanged()
  )
  .subscribe((data: ContentChange) => {
	// tslint:disable-next-line:no-console
	console.log('Delta', data.delta)
	// tslint:disable-next-line:no-console
	// console.log('view child + directly subscription', data)
  })

```

Thank you! a greeting.

**Comment by KillerCodeMonkey** [comment]
now i get your question. yes because it is hard to get the whole delta, because i do not know how to safely merge all changes made in the meantime

**Comment by Marius-Romanus** [comment]
oops, sorry, I did not remember that I had already posted a similar topic. 😅

I've been looking at the code and I'm sorry I can't help, but I think it would be something similar to what this library does, controlling the states?
https://github.com/quilljs/delta#compose

Regards!

**Comment by KillerCodeMonkey** [comment]
yep but i do not know exactly how i know how many changes are happening for a subscription.
But you can implement it for your single subscription.

just add a counter to your component and init it with 0. add a "tap" operator of rxjs before your debounce and increase the count. is you subscribe is called you can then retrieve the right count of changes and reset the counter

**Comment by Marius-Romanus** [comment]
Thanks! with tap it can be done perfectly!

**Comment by KillerCodeMonkey** [comment]
But in the example I explicitly use the ngx-quill event onEditorChanged and
not the formControl

Marius-Romanus ***@***.***> schrieb am Do., 31. März 2022,
13:46:
