### ISSUE TITLE
ngx-quill get the custom module

### ISSUE THREAD

**Issue by yoniyard** [KillerCodeMonkey/ngx-quill#1516]
im using ngx-quill with mat-quill. (as in ur example)

ive registered a 'mention' module inside the mat-quill-base using the syntax:

![image](https://user-images.githubusercontent.com/93582866/161438334-4cc8cd8a-b2ed-4222-a08b-d79c4fd58f3c.png)

how do i get the module mention to trigger an event? (iam adding a custom button to the toolbar that on clickes to trigger 'openMenu' function that belongs to the quill-mention module)

![image](https://user-images.githubusercontent.com/93582866/161438194-595b2100-5a05-4805-b270-f65c9be99365.png)

but for this example ive should initialize quill like:

![image](https://user-images.githubusercontent.com/93582866/161438366-c2e2d7ef-eae0-4529-a2d1-f0d215696ce2.png)

and then use the 'quill'.

in ngx-quill we initilaze the modules like ive described above.

what am i missing ?

**Comment by KillerCodeMonkey** [comment]
What do you want to achieve with the button?

Or what should happen when clicking it? In general just add a plain
JavaScript click listener to the button.

Yonatan Yardeni ***@***.***> schrieb am So., 3. Apr. 2022,
18:30:

**Comment by yoniyard** [comment]
@KillerCodeMonkey 
i wanted to open the quill menu, by adding handler to the custom toolbar button. like:
![image](https://user-images.githubusercontent.com/93582866/161438685-7357a468-88f6-4e9c-8c7e-ad26fac4e3f9.png)
the quill-mention export this function already. i just cant get the mention module so i can trigger it

**Comment by KillerCodeMonkey** [comment]
just checkout the quill documentation.

if you have a handler and define the callback not as fat arrow you can use "this.quill" to get the quill instance and then make

```TS
{
  handlers: {
    at: function () {
      this.quill.getModule('mention').openMenu()
    }
}
```

or if you wan to be more independent how how to write the callback, just initialize quill without any handler. And after that:

```TS
const quill = Quill({...})

const mention = quill.getModule('mention')
quill.getModule('toolbar').addHandler('at', () => menthion.openMenu())
```

In general this is not an ngx-quill question more a quilljs one ;-).

https://quilljs.com/docs/modules/toolbar/#handlers
