### ISSUE TITLE
Add a custom button to text area of quill editor

### ISSUE THREAD

**Issue by PratyushaDirectPath** [KillerCodeMonkey/ngx-quill#1518]
I would like to add two custom buttons to the text area of the editor, on click of those buttons I want to display the innerHtml of the text entered of the text-area. Could you please tell me how to add a button to the text area of the quill editor ?

**Comment by KillerCodeMonkey** [comment]
I do not know why you want to add. Button to the text area. I would say you
can just add buttons to the toolbar of the editor (check quilljs
documentation how to do it) or just put them outside of the text area with
click listeners

That's it.

To get access to the quill instance just listen on the onEditorCreated
output and store the editor reference.

In the quill documentation you can find how to get the content of the
editor.

That's it :).



PratyushaDirectPath ***@***.***> schrieb am Mi., 6. Apr.
2022, 15:23:
