### ISSUE TITLE
Got a compiler error

### ISSUE THREAD

**Issue by MyMarvel** [KillerCodeMonkey/ngx-quill#1519]
`Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:21 - error TS261
4: Module '"quill"' has no exported member 'Delta'. Did you mean to use 'import
Delta from "quill"' instead?

3 import QuillType, { Delta } from 'quill';
`
Didn't use this module before, tried to install it and got this issue. Any idea how to fix?
    "@types/quill": "^2.0.9",
    "ngx-quill": "^16.2.0",
    "quill": "^1.3.7",

**Comment by KillerCodeMonkey** [comment]
Please first search for similar issues .. and check the readme and how
semantic versionings works...

Types of quilljs 2.x will not work with quilljs 1.x

Nikita Petrov ***@***.***> schrieb am Do., 7. Apr. 2022,
08:29:

**Comment by MyMarvel** [comment]
Thanks for such a quick answer and patience :) How about to add an example of installation command to the readme so people would not forget to use the correct versions for all dependencies? Like `npm install ngx-quill quill@1.x @types/quill@1.x`

**Comment by MyMarvel** [comment]
And I think this line is not clear for a lot of users:
>>do not forget to include quill + theme css in your buildprocess, module or index.html!
Because we already think that we included quill when importng this angular module. How about at least to change it to this:
>>do not forget to include quilljs + theme css in your buildprocess, module or index.html (see https://www.npmjs.com/package/quill)!

**Comment by KillerCodeMonkey** [comment]
if you check the readme in the repo here:

https://github.com/KillerCodeMonkey/ngx-quill#installation

`install @angular/core, @angular/common, @angular/forms, @angular/platform-browser, quill v1.x, @types/quill v1.x and rxjs - peer dependencies of ngx-quill`

**Comment by norbertnagy** [comment]
the readme file is not written properly. Instead of repeating the same comment to check the readme file on all the raised issues, how about you update the readme file ?
