### ISSUE TITLE
Uncaught TypeError: Cannot read property 'import' of undefined

### ISSUE THREAD

**Issue by jdubsmith** [KillerCodeMonkey/ngx-quill#152]
I am ultimately trying to get the `<br>` tags to not be surrounded by `<p>` tags.

I get the above error when trying to get a reference to the parchment object using the code below.

I am using Angular 5, Angular CLI and the latest ngx-quill.  I have tried to follow the example project you have here in GitHub, but have not been able to get it to work.  I tried to run the example application with npm install... then ng serve and kept getting errors.

```
import Quill from 'quill';

// override p with div tag
const Parchment = Quill.import('parchment');
let Block = Parchment.query('block');

Block.tagName = 'DIV';
// or class NewBlock extends Block {}; NewBlock.tagName = 'DIV';
 Quill.register(Block /* or NewBlock */, true);
```

**Comment by KillerCodeMonkey** [comment]
Check out the quill editor component it self here in the repo. There is
another way to import it.
I think there are other closed issues related to this topic.

Ps: do not forget to add quill to your angular-cli.json

**Comment by jdubsmith** [comment]
Using:
```
import * as QuillNamespace from 'quill'; 
let Quill: any = QuillNamespace;
```
instead of:
```
import Quill from 'quill';
```

resolved the issue

**Comment by KillerCodeMonkey** [comment]
Great!

Please close the issue :)

**Comment by jdubsmith** [comment]
Closing issue
