### ISSUE TITLE
span with ql-editor class has infinite width

### ISSUE THREAD

**Issue by kevingy** [KillerCodeMonkey/ngx-quill#1522]
I'm seeing a problem on Safari (only - this works on Chrome, Firefox and Edge). When I'm displaying text that was created or edited by Quill and displayed like this:

`<span class="ql-editor" [innerHTML]="trustHtml(text)"></span>`

The span initially displays within the expected 600px width, but as soon as I move the mouse, the span grows infinitely. The more the mouse moves, the wider the span gets - tens of thousands of pixels. The trustHtml method does what many examples of using this technique with DomSanitizer.

I don't know if this has anything to do with it, but the span is in a cell of a mat-table. The issue behaves as though it's JavaScript DOM manipulation that's setting the width, but I can't be sure.

**Comment by kevingy** [comment]
This problem also appears (again, only on Safari on Mac) on any Quill editor. The width expands into infinity on mouse move over the component.

**Comment by KillerCodeMonkey** [comment]
in general this looks more like a quilljs problem and not one with my angular wrapper :)

**Comment by kevingy** [comment]
I'll take this issue there. Danke!

**Comment by KillerCodeMonkey** [comment]
Then... just test it outside if a mat cell :). So we know if it is mat-cell
related

Kevin Yochum ***@***.***> schrieb am Mo., 18. Apr. 2022,
02:00:
