### ISSUE TITLE
moderate severity vulnerabilities

### ISSUE THREAD

**Issue by raymak23** [KillerCodeMonkey/ngx-quill#1527]
Hello, I am getting the following error when installing `ngx-quill`. I am using `"ngx-quill": "^16.2.0"` version. 

npm audit report:

quill  <=1.3.7
Severity: moderate
Cross-site Scripting in quill - https://github.com/advisories/GHSA-4943-9vgg-gr5r
No fix available
node_modules/quill
  ngx-quill  *
  Depends on vulnerable versions of quill
  node_modules/ngx-quill

2 moderate severity vulnerabilities

Here is are the packages I have in the `package.json` file

`
  "dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/cdk": "^13.3.2",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/fire": "^7.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/material": "^13.3.2",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "ngx-quill": "^16.2.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  
`

Any recommendations on how to fix these 2 moderate severity issue?

**Comment by KillerCodeMonkey** [comment]
Nope. Since they are in quilljs you have to live with it.

Ray ***@***.***> schrieb am Fr., 29. Apr. 2022, 19:15:

**Comment by raymak23** [comment]
Thank you. I will open an issue in quilljs space. BTW, really appreciate making this awesome plug-in.
