### ISSUE TITLE
Failed to execute 'insertAdjacentHTML' on 'Element': This document requires 'TrustedHTML' assignment

### ISSUE THREAD

**Issue by aalbericio** [KillerCodeMonkey/ngx-quill#1528]
Hello,

I have just added some security headers for my Angular application and I'm getting this error when I initialize a "quill-editor" component:

`Failed to execute 'insertAdjacentHTML' on 'Element': This document requires 'TrustedHTML' assignment`

I have tried setting the "sanitize" input to "true" but it doesnt help much:

```
<quill-editor
      [modules]="modules"
      [sanitize]="true"
      [(ngModel)]="newNotesHtml">
</quill-editor>
```

Help is much appreciated.

Thanks.

**Comment by KillerCodeMonkey** [comment]
@aalbericio could you check out my repo here and build the sources and use them. i replaced the insertAdjustHTML with an angular solution. Maybe it works. But i have no time to test it, so there is no release, yet.

Would be nice if you could test it some how. so i would release a new version this evening

**Comment by aalbericio** [comment]
Hello again,

I have built and tested with master and now the error is different, and this time it directly points to Quill project:

```
Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
    at new Quill (node_modules_quill_dist_quill_js.js:1149:30)

line: this.container.innerHTML = '';

```
Anyway, we have just found a workaround (as specified here: https://web.dev/trusted-types/?utm_source=devtools) using DOMPurify and security policies.

Thanks for your help!

**Comment by KillerCodeMonkey** [comment]
But can you verify it is working with your fix and my latest changes?

Because the changes are made should make the ngx-quill code less hacky ^^

aalbericio ***@***.***> schrieb am Mo., 9. Mai 2022, 16:50:

**Comment by KillerCodeMonkey** [comment]
nevermind i updated my demo repo and published 16.2.1 ;)

**Comment by aalbericio** [comment]
Hello again.

I did tested your fix but didn't actually work. I mean, the "insertAdjacentHTML" error didn't trigger but then another error coming from Quill fired at line:

`this.container.innerHTML = '';`

We finally workarounded this by creating a custom trustedType policy and allowing these exceptions for the quill-editor:

`['quill-editor-element', 'href', 'target']`

I hope that helps for anyone dealing with this issue.

Thanks again for your quick support.

**Comment by KillerCodeMonkey** [comment]
yeah i know that but know the problem is not there because of ngx-quill ;-). and now my code does not contain any native dom manipulation.

**Comment by KillerCodeMonkey** [comment]
and feel free to send a PR with a little section about it for the readme?

**Comment by f-aubert** [comment]
@aalbericio could you please document your workaround as we are facing the same issue.  Where and how to define this specific exception for quill-editor-component? Thks
