### ISSUE TITLE
Issue in installing quill in angular

### ISSUE THREAD

**Issue by ashirwad8858** [KillerCodeMonkey/ngx-quill#1530]
I follow these steps. I want to insert a table but I am getting issues at starting stage.
1. ng new project-name
2. npm install ngx-quill quill 
3. npm i quill-better-table
4. paste code in angular.json   
     "styles": [
              "src/styles.scss",
              "./node_modules/quill/dist/quill.core.css",
              "./node_modules/quill/dist/quill.bubble.css",
              "./node_modules/quill/dist/quill.snow.css",
              "./node_modules/quill-emoji/dist/quill-emoji.css",
            ],
            "scripts": [
              "./node_modules/quill/dist/quill.min.js"
            ]

5. in app.module.ts
    import { QuillModule } from 'ngx-quill'

@NgModule({
  ...
  imports: [
    ...
    QuillModule.forRoot()
  ]
})
export class AppModule { }

6. ng serve.

But I  am getting Error
![Screenshot from 2022-05-12 16-01-21](https://user-images.githubusercontent.com/30556645/168052153-9b615bd7-3c86-4f45-b147-e72b9394341a.png)

if I tried to npm i --save-dev @types/quill and run the project. then I am getting this error

![Screenshot from 2022-05-12 16-04-05](https://user-images.githubusercontent.com/30556645/168051914-504bfa53-ae61-49cd-a999-449a947e43af.png)

How we can fix it?

please write steps if possible.

**Comment by AlejandroTorresR** [comment]
@ashirwad8858  Downgrading to @types/quill ^1.3.10 worked for me.
