### ISSUE TITLE
Focus loses when add link

### ISSUE THREAD

**Issue by dmitriantipov1** [KillerCodeMonkey/ngx-quill#1534]
Hello, I didn't find a solution to this problem, so I turn to you.

I have a logic of sending a request to the server when bluring. When I try to add a link, the focus disappears and happend a request. 

![problem](https://user-images.githubusercontent.com/85520553/169645629-df26e817-6ec2-479a-b957-a3f4948019aa.gif)
How can I make the request happen after adding the link?
Using Angular **12.0.0**
Ngx Quill **14.0.0**

**Comment by KillerCodeMonkey** [comment]
You should ask this at quilljs repo. But in general when another input or
contenteditable block element gets the focus the focus/selection of the
current element gets lost / blurred

dmitriantipov1 ***@***.***> schrieb am Sa., 21. Mai 2022,
11:38:

**Comment by dmitriantipov1** [comment]
Ok, thanks for your quick reply
