### ISSUE TITLE
Issue in building on Angular 8

### ISSUE THREAD

**Issue by jlameira** [KillerCodeMonkey/ngx-quill#1536]
I had this issue when i tried to build my application, but in ng serve works normally.
My application use Angular 8 and    "ngx-quill": "^9.2.0",  "quill": "^1.3.6"

![image](https://user-images.githubusercontent.com/8197441/169704771-29cb7306-fe75-4a48-9fd5-2d2366407694.png)

Angular Version.
![image](https://user-images.githubusercontent.com/8197441/169704865-62136734-6038-42ed-8c73-00cbc9a05f35.png)

How we can fix it?

**Comment by KillerCodeMonkey** [comment]
sorry no support for that old angular and ngx-quill versions.

just check in the release/commit history if you ngx-quill version is matching your angular version.
