### ISSUE TITLE
TypeError: n.appendChild is not a function

### ISSUE THREAD

**Issue by vickyrathee** [KillerCodeMonkey/ngx-quill#1538]
The editor throw error for some HTML examples, when I loaded from API.

**This works fine**
```
<p>This is a <strong>test</strong> description</p>
```

**This doesn't works**
```
<p><em>This </em>is a <strong>test</strong> <u>description</u></p>
```
While both HTML are created with same editor only. After saving, I can't open it back in the editor. It crashes with error `TypeError: n.appendChild is not a function`

![image](https://user-images.githubusercontent.com/6106479/169803557-7ee81922-2dcd-4e78-ba14-15ddd3710b49.png)

Here is my code:

**component.html**
```
 <div class="form-group">
              <label for="description">Description</label>          
              <quill-editor [modules]="quillOptions" id="description" [(ngModel)]="event.description" name="description"></quill-editor>
            </div>
```

**component.ts**
```
 quillOptions = {
      toolbar: [['bold', 'italic', 'underline'], [{ list: 'ordered' }, { list: 'bullet' }], ['link']],
    }
```

However, this simple example works fine - 
![image](https://user-images.githubusercontent.com/6106479/169805994-75f08416-d27a-4395-b5a3-0cbaf1c401a8.png)

- Here is the version details

![image](https://user-images.githubusercontent.com/6106479/169806280-204ae7ff-5a3b-4a4e-9d7c-bd07c4e8f258.png)

**Comment by KillerCodeMonkey** [comment]
but it seems to be triggered from quilljs? I would guess something is not correctly cleaned up.
so quilljs wants to do something with the editor container element, but the element is not there or gets kicked of the dom

**Comment by KillerCodeMonkey** [comment]
i found: https://github.com/quilljs/quill/issues/3150

and please try to use the latest version of ngx-quill fitting your angular version.

https://github.com/KillerCodeMonkey/ngx-quill#compatibility-to-angular-versions

**Comment by vickyrathee** [comment]
@KillerCodeMonkey could be an issue with `*ngIf`, as my editor is in steps wizard ?

**Comment by KillerCodeMonkey** [comment]
maybe :)

**Comment by vickyrathee** [comment]
I upgraded to Angular 13 and latest "ngx-quill": "^16.2.1"
Also extracted the  `<quill-editor` out of ngIf, but still same error for some HTMLs
