### ISSUE TITLE
Embedding custom components doesnt render the child nodes

### ISSUE THREAD

**Issue by visualbuffer** [KillerCodeMonkey/ngx-quill#1539]
Hi Bengt,

First of all thanks for writing the wrapper around quill makes integrating a breeze. 
I was trying to embed a custom component into the quill editor, it does include the selector however the child nodes (of the custom component) are not rendered. Same in the quill view as well.

### Editor component
`class CustomComponentModule extends blockEmbed {}
CustomComponentModule.blotName = 'image';
CustomComponentModule.tagName = 'content-figure';

Quill.register(CustomComponentModule);`

### Selector Tag:
`@Component({
  selector: 'content-figure',
  template: '<h1>Do you see this?<h1>',
  styleUrls: [],
})`

Rendered html in Quill editor on clicking image:
`    <div class="ql-editor" data-gramm="false" contenteditable="true" data-placeholder="Add case note here">
        <content-figure> </content-figure>
        <p><br></p>
    </div>`

**Comment by visualbuffer** [comment]
Thanks for the quick response !  Will post on quilljs.
Is there anything in the ngx-quill api which might help ?

**Comment by visualbuffer** [comment]
Leaving a link to the quill issue: https://github.com/quilljs/quill/issues/3587

**Comment by JoanCodinachUoc** [comment]
@KillerCodeMonkey @visualbuffer  But this problem in ngx-quill is solved ? 
If the answer is yes, can you show us an example please?

Thank you

**Comment by KillerCodeMonkey** [comment]
there was never a problem in ngx-quill.

native quilljs is rendering the content of the editor... since it does not know anything about angular or angular components this never will work out of the box.

just follow the linked quills issue.

1. make sure you generate your angular component as ordinary web component
2. register it to quilljs

**Comment by visualbuffer** [comment]
You absolutely can

**Comment by KillerCodeMonkey** [comment]
yes but then you need to generate your components as native web components (buzzword: angular elements) and register it that quilljs knows it. just follow the already posted quilljs issuehttps://github.com/slab/quill/issues/3587
