### ISSUE TITLE
Enable code-block by default

### ISSUE THREAD

**Issue by mani0608** [KillerCodeMonkey/ngx-quill#154]
Sorry. I'm very new to Quill. I need help in enabling the code-block format in the toolbar by default so that when the editor is opened it displays the content in code-block

**Comment by mani0608** [comment]
Thanks for the suggestions.
I did add the formats and modules this way

`this.formats = ['code-block'];`
`this.modules = {
      formula: false,
      toolbar: [
        ["blockquote", "code-block"]
      ],
      syntax: true
    }`

Then in my HTML,

`<quill-editor #editor (onEditorCreated)="onEditorCreated($event)" (onContentChanged)="onContentChanged($event)"  
        [ngModel]="editorText" [formats]="formats" [modules]="modules"></quill-editor>`

But still i couldn't get this to be enabled by default

**Comment by KillerCodeMonkey** [comment]
Strange an sorry did not tested the code-block stuff. There is maybe an
issue in the quilljs repo?

**Comment by mani0608** [comment]
I tried 
`quill.format("code-block", true)`
and that didn't work-out as well. Like it could have been an issue with the quill repo. 
Let me try to post this there directly.

**Comment by KillerCodeMonkey** [comment]
checkout https://killercodemonkey.github.io/ngx-quill-example/ the codeblock should be there per default. The `</>`symbol in the toolbar

**Comment by mani0608** [comment]
For me it is displayed, but not activated. I want the code block mode/format to be activated when i open my editor. For e.g. i want this view 
![image](https://user-images.githubusercontent.com/20502054/38270803-2b1e00a2-37a2-11e8-97a0-3b742eb1ec2a.png)
when i open my editor

**Comment by KillerCodeMonkey** [comment]
Ahhh now i get it. I think you can set the Format through the quill API.
Checkout the quilljs Documentation.

But that is totally a quilljs issue.

Please close this issue here, but feel free to post your solution if you
got one.

**Comment by mani0608** [comment]
Sure thanks for the help :)

**Comment by mani0608** [comment]
Found the solution,
`this.editor.quillEditor.formatLine(0, this.editor.quillEditor.getLength(), { 'code-block': true });`
in OnContentChaged event did the trick :)

**Comment by KillerCodeMonkey** [comment]
nice!
