### ISSUE TITLE
How to SpellCheck Turn on in ionic angular.

### ISSUE THREAD

**Issue by fahad-cinnova** [KillerCodeMonkey/ngx-quill#1541]
Working On windows and browsers by default but not working on mobile end (Android or iPhone)
I'm using this versions 

```JSON
{
 "ngx-quill": "^13.2.0",
 "@angular/core": "~10.0.0",
}
```

 I'm using these below
 TS File :

```TS
  constructor() {
    modules = {
      'toolbar': [
        [
          'bold', 'italic', 'underline', 
          { 'list': 'ordered' }, { 'list': 'bullet' },
          { 'indent': '-1' }, { 'indent': '+1' },
          { 'direction': 'rtl' }, { 'align': [] },
          { 'header': [1, 2, 3, 4, 5, 6, false] },
        ],
      ],
      spellcheck:false
    }
  }
```

HTML File:
```HTML
  <quill-editor
        [styles]="{height: '200px', width: '100%'}"
        [formControlName]="field._id"
        class="quill-editor-custom"
        [(ngModel)]="field.value"
        trackChanges="all"
        [modules]="modules"
        (keyup)="consoleValue($event)"
      ></quill-edi
tor>
```
**Can You guide me, how can I add this spellCheck featured in my app**

**Comment by KillerCodeMonkey** [comment]
seems like this is working:
https://github.com/quilljs/quill/issues/2225#issuecomment-411986304

Option 1:
You can listen to the onEditorCreated event/output.
There you get the editor instance and can do the: `quill.root.setAttribute` part from the link above.

Option 2:
grab the ngx-quill component instance by using angular "@ViewChild" decorator.
There you get access to the editor element or the quill instance.
With that you can do the same thing - setting the attribute.

Good luck :)

**Comment by fahad-cinnova** [comment]
Hi @KillerCodeMonkey 
I followed option1 :

Html File :
 <quill-editor
      (onEditorCreated)="logInit($event)"
        [styles]="{height: '200px', width: '100%'}"
        spellCheck="true"
        [formControlName]="field._id"
        class="quill-editor-custom"
        [(ngModel)]="field.value"
        trackChanges="all"
        [modules]="modules"
        (keyup)="consoleValue($event)"
      ></quill-editor>
      
TS File:
logInit(quill) {
  let editorInstance =  quill.editor;
  editorInstance.root.setAttribute('spellcheck', true)
  }
  
  So here  In editorInstance variable got this below
![image](https://user-images.githubusercontent.com/102585302/170678356-ba802bf3-55e5-4505-8f07-00a275dcac56.png)
 
But **editorInstance.root.setAttribute('spellcheck', true)**  line creating undefined.

**Comment by KillerCodeMonkey** [comment]
then just log and debug where root element is stored. i do know now everything about quilljs ;-) 

or use option 2

**Comment by fahad-cinnova** [comment]
@KillerCodeMonkey I followed second option and solution is here 💯 
 Thanks a lot . I have found root 
Solution :
HTML:

 <quill-editor
      (onEditorCreated)="onCreation()"
      ></quill-editor>

TS: 
onCreation(){
  this.editor.editorElem.spellcheck = true;
  }

**Comment by KillerCodeMonkey** [comment]
Nice!
