### ISSUE TITLE
Cannot use namespace 'QuillType' as a type

### ISSUE THREAD

**Issue by MahdiyarTH** [KillerCodeMonkey/ngx-quill#1543]
I'm using Quill in a angular v11 project but i got this error:

```
Error: node_modules/ngx-quill/lib/quill-view.component.d.ts:30:32 - error TS2709: Cannot use namespace 'QuillType' as a type.

valueSetter: (quillEditor: QuillType, value: any) => any;

Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:97:49 - error TS2709: Cannot use namespace 'Delta' as a type.

97     textChangeHandler: (delta: Delta, oldDelta: Delta, source: string) => void;
       
```
and many others like this. My versions are like bellow. 
I deleted my node_modules directory and package_lock.json file and run `npm install` but nothing changed. 

I saw other related issues but they weren't helpful 
     

    "@angular/animations": "11.2.14",
    "@angular/cdk": "^9.0.0",
    "@angular/common": "11.2.14",
    "@angular/compiler": "11.2.14",
    "@angular/core": "11.2.14",
    "@angular/forms": "11.2.14",
    "@types/quill": "^1.3.10",
    "ngx-quill": "^13.4.0",
    "quill": "^1.3.7",

npm -v
6.14.17

node -v
v16.15.0

**Comment by KillerCodeMonkey** [comment]
please make sure the correct quill typings are installed in your node module.

try remove node_modules folder (check package-lock or yarn.lock) and reinstall

**Comment by MahdiyarTH** [comment]
So what is correct quill typing for "ngx-quill": "^13.4.0"? I installed "@types/quill": "^1.3.10" before, and as is said, i remove my node_modules folder and package-lock.json and tried again but nothing happened.

**Comment by KillerCodeMonkey** [comment]
strange, because the error occurs in general, when you are mixing quill v2 typings with quill v1.
