### ISSUE TITLE
Add variable placeholder

### ISSUE THREAD

**Issue by MahdiyarTH** [KillerCodeMonkey/ngx-quill#1544]
I want to be able to add some variable placeholder. 
<img width="1392" alt="Screen Shot 2022-05-30 at 9 37 46 AM" src="https://user-images.githubusercontent.com/25479661/170920961-9179512f-eb31-4b7a-a2cd-cede6c345b75.png">

I want to add a button that by clicking on it, a placeholder like 'variable' insert to my editor. When i get the content, i want to this placeholder replaced with some text like '${variable}'. Bot there is nothing about this 'variable' in my content when is passed it as ([NgModel]). How can i achieve this?

I added this variable place holder to editor using extending a custom class from 'Inline Blot' and setting `tagName=variable` and `blootName=variable` and code like below:

`this.editor.quillEditor.clipboard.dangerouslyPasteHTML(
            this.editor.quillEditor.getSelection().index,
            " <variable>Variable</variable> "
        );`

**Comment by KillerCodeMonkey** [comment]
@MahdiyarTH i am not that deep in to quill how to correctly build your own blots and modules.

But as a hint: checkout the "quill-mention" module.
There you have some nice ability to add "names/users" by typing `@` in the editor. This would maybe a nice way to add custom variables. Or quill emoji module is doing the same. You can find examples for both in my demo repo.

I would suggest you check how they are solving it and maybe adapt it.

**Comment by MahdiyarTH** [comment]
Yea i think "quill-mention" is perfect in my case. Thank you
