### ISSUE TITLE
Quill sanitize, removes styles of html

### ISSUE THREAD

**Issue by VoidTallica** [KillerCodeMonkey/ngx-quill#1546]
Hello. 
I was using Quill and everything works fine, except when i try to style my text. Since Angular has its DOMSanitizer, when i try to show the output of the html generated by quill, it removes any kind of element with the style attribute.
In Quill editor i have this:
![image](https://user-images.githubusercontent.com/48948797/170956030-8fce3e85-4e4d-43d3-8f9e-7d8533cde958.png)
If i use the tag [sanitize] on Quill, it also removes styles (since it uses Angular Dom Sanitizer it's expected).
Is there a way to keep text styles using sanitize?

**Comment by KillerCodeMonkey** [comment]
just check my demo repo. i provide view components, where you can deactivate santizing.
And keep in mind in general you need quill css on the page you show the result
