### ISSUE TITLE
Redundant initial formControl valueChanges emit from quill-editor

### ISSUE THREAD

**Issue by yuwu9145** [KillerCodeMonkey/ngx-quill#1547]
When using `[formControl]` to `<quill-editor>`, it emit the default value through `valueChanges` observable. 

This behaviour is inconsistent with the default Angular reactive form (no initial value emit but only emits when there are user changes)

## Steps to reproduce

1. Open [demo link ](https://stackblitz.com/edit/angular-ivy-ti3tcx?file=src/app/app.component.ts)
2. Open developer tool
3. The default value can been found in console log
4. By comparing the default Angular reactive form behaviour (found from this [link](https://stackblitz.com/edit/angular-ivy-nnx3nv?file=src/app/app.component.ts)). There is no initial value in console log

**Comment by KillerCodeMonkey** [comment]
feel free to contribute and send me a pr :)

**Comment by KillerCodeMonkey** [comment]
sadly i have no solution for that. This change is triggered, because i try to keep validators in sync after the quill editor is initialized. So the control/modal does have the correct valid state and classes.

Seems like this triggers a change

**Comment by IsaacSomething** [comment]
Maybe skip(1) to mimic angular valueChanges

```
this.profileForm.valueChanges
    .pipe(skip(1))
    .subscribe((value) => console.log(value));
```

**Comment by KillerCodeMonkey** [comment]
@IsaacSomething and maybe check if the model is marked as touched and reset it, if needed

**Comment by imaliouris** [comment]
I have the same problem, is there any update on this? I mean why would you emit valuechanges when nothing has changed? I have a formControl that has the default value and when I pass it to the quill editor it emits the same value...

**Comment by KillerCodeMonkey** [comment]
like described by IsaacSomething use the rxjs operator "skip" to ignore the first trigger.

**Comment by imaliouris** [comment]
Thats not the proper way.. I have a formGroup that I track its changes and I dont always have a quill editor, or I may have more than one, so I can't just skip the first value.. Furthermore its not good for developer experience as it's not clear why this skip happens..

**Comment by KillerCodeMonkey** [comment]
you can try to solve the issue and send a pr. but as i described above i have not idea how to solve it without breaking other functionality

**Comment by titusfx** [comment]
> sadly i have no solution for that. This change is triggered, because i try to keep validators in sync after the quill editor is initialized. So the control/model does have the correct valid state and classes.
> 
> Seems like this triggers a change

Could you provide the lines where is trigger ( so we can try help the project, starting from there)
