### ISSUE TITLE
Anyway to add both quill modules from typescript and html

### ISSUE THREAD

**Issue by vibingopal** [KillerCodeMonkey/ngx-quill#155]
Hi,

Iam able to add the quill tool bar successfully using the below format.

Html:

> <quill-editor id="qeditor" [style]="{'height': '400px'}" [modules]="modules " placeholder="Add your Story Here... ">
> </quill-editor>

TS:
 

> this.modules = {
>       toolbar: [
>         ['bold', 'italic', 'underline'],
>         ['blockquote', 'code-block'],
>         [{ size: ['small', false, 'large', 'huge'] }],
>         [{ align: 'justify' }, { align: 'center' }, { align: 'right' }],
>         [{ list: 'ordered' }, { list: 'bullet' }],
>         [{ color: [] }, { background: [] }],
>         ['image', 'video']
>       ],
>       imageResize: {
>        },
> }

Now i need a couple of buttons to the existing tool bar. Now when i try to add the custom buttons in the below format , iam not able to see my default tool bar which is defined in the ts file. iam able to see only the new buttons in the tool bar

 ```
 <quill-editor id="qeditor" [style]="{'height': '400px'}" [modules]="modules " 
           placeholder="Add your Story Here... ">
          <div quill-editor-toolbar>
            <a class="btn btn-floating">
              <i class="material-icons">add</i></a>
            <a class="btn btn-floating">
              <i class="material-icons">edit</i></a>
          </div>
        </quill-editor>

```

![image](https://user-images.githubusercontent.com/17860925/38281460-53fdde52-3770-11e8-90e8-cc1179f0db58.png)

Anything iam missing here ?

**Comment by KillerCodeMonkey** [comment]
yep because these are two different approaches to different approaches to define a toolbar ;).
CHeckout the quilljs documentation.

**Comment by vibingopal** [comment]
You mean we can't define the modules(existing tool bar) from typescript and create new buttons using quill-edit-toolbar at the same time?

**Comment by KillerCodeMonkey** [comment]
right
