### ISSUE TITLE
quill-editor doesn't show mentions with sanitize enabled

### ISSUE THREAD

**Issue by guerreroje** [KillerCodeMonkey/ngx-quill#1555]
Hello, 
**quill-editor** doesn't show mentions with sanitize enabled:

<img width="1114" alt="quill-editor" src="https://user-images.githubusercontent.com/423470/173255261-9ce8197e-1cc0-4b09-8639-d4416849b9c9.png">

but with **quill-view-html** it is displayed correctly:

<img width="782" alt="quill-view-html" src="https://user-images.githubusercontent.com/423470/173255308-ccbac1c4-7569-4fec-9260-fe8d5cce6201.png">

HTML code example:

`<p>Hello <span class="mention" data-index="1" data-denotation-char="@" data-id="guerreroje" data-value="Jorge Guerrero">﻿<span contenteditable="false"><span class="ql-mention-denotation-char">@</span>Jorge Guerrero</span>﻿</span> </p>`

**Comment by KillerCodeMonkey** [comment]
Yeah, but this is not a problem of ngx-quill.
It just uses angulars Dom sanitizer it removes all possible dangerous code.

If it does not fit your needs disable it and try to sanitize it by yourself.

Greets

Jorge Guerrero ***@***.***> schrieb am Mo., 13. Juni 2022,
00:00:
