### ISSUE TITLE
Any specific handler for Video Upload

### ISSUE THREAD

**Issue by vibingopal** [KillerCodeMonkey/ngx-quill#156]
Hi Team,

I am trying to implement video upload handler not only embeded video but also where users can upload their videos from specific location same as image, but not able to see any examples on that. Do you have any specific example for handling videos ?

Please let me know

**Comment by KillerCodeMonkey** [comment]
plllllease dude. ask those question in the quilljs repository and only there if you already opened an issue.

https://github.com/quilljs/quill/issues/2055

there are issues for images:
https://github.com/quilljs/quill/issues/1089
