### ISSUE TITLE
Facing issue while using ngx-quill and ngx-tribute

### ISSUE THREAD

**Issue by susmoy-macgill36** [KillerCodeMonkey/ngx-quill#1561]
Hi, I want to use [ngx-tribute](https://www.npmjs.com/package/ngx-tribute) with **ngx-quill**, but I am facing an issue, selected item (from tribute's dropdown) is not inserting properly.  I am attaching two screenshots related to this problem. Am I doing something wrong? 

`<quill-editor  id="quillEditor" [ngxTribute]="options" [(ngModel)]="input" [styles]="{height: '300px'}" #tributeDirective="ngx-tribute"></quill-editor>`

```
options: TributeOptions<TributeValue> = {
    trigger: "@",
    values: [
        { key: 'test1', value: 'test1' },
        { key: 'test2', value: 'test2' },
        { key: 'test3', value: 'test3' }
    ],
    selectTemplate: function (item) {  
      return item.original.key;
    },
   
};

```
 
<img width="814" alt="image" src="https://user-images.githubusercontent.com/43792886/175980311-e59073db-91ea-4ab6-960f-d91f3b316a21.png">
<img width="885" alt="image" src="https://user-images.githubusercontent.com/43792886/175980577-03d374e0-65a3-46f8-b07c-18666d0ca2b3.png">

**Comment by KillerCodeMonkey** [comment]
i do not know how ngx-tribute works, but i guess since quilljs is plain javascript and only allows specific html and formats it will not work perfectly.

I would use quill-mention https://github.com/quill-mention/quill-mention
