### ISSUE TITLE
Latest version not importing correctly

### ISSUE THREAD

**Issue by jpike88** [KillerCodeMonkey/ngx-quill#1565]
angular 14.0.4
typescript 4.7.4

<img width="897" alt="Screen Shot 2022-06-30 at 15 34 06" src="https://user-images.githubusercontent.com/9585787/176631740-cdef1ca3-ff82-4250-92b0-9782acf2f910.png">

**Comment by jpike88** [comment]
current workaround: `import { QuillModule } from 'ngx-quill/src/public-api';`

**Comment by jpike88** [comment]
actually no, that results in an empty object being imported.

<img width="427" alt="Screen Shot 2022-06-30 at 15 49 54" src="https://user-images.githubusercontent.com/9585787/176635049-c7fae942-812d-4e39-86e7-9e2100fc1ad5.png">

**Comment by jpike88** [comment]
To clarify, this is the only lib out of many imports I have going on with this issue, there's definitely something wrong here

**Comment by KillerCodeMonkey** [comment]
thanks. i just published not the dist , but the src folder. thanks for letting me know.

please try 17.1.1
