### ISSUE TITLE
Custom button example while retaining <quill-editor> tag in html alongside its [modules] config

### ISSUE THREAD

**Issue by OhEmQ** [KillerCodeMonkey/ngx-quill#1571]
Hi, I am using Angular 11 and I am trying to create a custom button on the Quill Toolbar for grammar correction. I want to retain as much of my current code as possible as it took me a long time to set up and get working.

I am using the html tag <quill-editor> method of displaying the quill editor, with the [modules] config that displays the toolbar options as defined in the corresponding typescript file.

Any help would be greatly appreciated.

```html
<quill-editor 
          class="text-editor"
          [(ngModel)]="htmlText"
          placeholder="Enter Note *"
          [modules]="quillConfig">
</quill-editor>
```

```typescript
quillConfig = {
    toolbar: {
      container: [
        [{ header: [1, 2, 3, 4, 5, 6, false] }],
        ['bold', 'italic', 'underline', 'strike'],
        [{ list: 'check' }, { list: 'ordered' }, { list: 'bullet' }],
        [{ color: [] }, { background: [] }],
        ['clean'],
      ],
    },
  };
```

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/1013
https://github.com/quilljs/quill/issues/2611#issuecomment-492178978

you need to register the button as custom format to use it with module-config or you need to create our own toolbar with html and listeners

**Comment by OhEmQ** [comment]
Sorry but both examples are for creating a whole new toolbar with html and listeners. Do you have an working example for registering the button as custom format to use with module-config?

**Comment by OhEmQ** [comment]
> #1013 [quilljs/quill#2611 (comment)](https://github.com/quilljs/quill/issues/2611#issuecomment-492178978)
> 
> you need to register the button as custom format to use it with module-config or you need to create our own toolbar with html and listeners

Aren't these examples for creating a whole new toolbar? I want to just add a custom button to an existing one, thus retaining the <quill-editor> html tag with its [modules] configuration.

**Comment by KillerCodeMonkey** [comment]
seems like that. But you have the opportunity to ask this directly at the quilljs repo. Maybe there are more "native quill" experts.

**Comment by iKrishnaSahu** [comment]
> > #1013 [quilljs/quill#2611 (comment)](https://github.com/quilljs/quill/issues/2611#issuecomment-492178978)
> > you need to register the button as custom format to use it with module-config or you need to create our own toolbar with html and listeners
> 
> Aren't these examples for creating a whole new toolbar? I want to just add a custom button to an existing one, thus retaining the html tag with its [modules] configuration.

Hi @OhEmQ , 
Did you find any way to add new custom button using modules configuration?
