### ISSUE TITLE
How to Clear Editor via code?

### ISSUE THREAD

**Issue by chobo2** [KillerCodeMonkey/ngx-quill#1576]
Hi

I am wondering how would I clear everything in the editor. I am not seeing anything in the documentation.

**Comment by KillerCodeMonkey** [comment]
https://angular.io/api/forms/NgModel
https://angular.io/api/forms/FormControl
https://quilljs.com/docs/api/#setcontents

For angular examples how form controls and ngmodel can be used, check my linked demo repo in the readme
