### ISSUE TITLE
insertText in an empty form doesn't update the state of the form

### ISSUE THREAD

**Issue by synopss** [KillerCodeMonkey/ngx-quill#1578]
When using `formControlName` to `quill-editor`, and using `insertText` method from the quill library, it doesn't update the state of the form.

For example, if the form is required, the user would need to write one extra character after the inserted text added thanks to the `inserText` method to change the form state as valid.

I tried something like this without any success : 

```
this.editor.quillEditor.insertText(currentPosition, value);
this.formGroup.get('test').clearValidators();
this.formGroup.updateValueAndValidity();
```

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill#quilleditorcomponent ;-)
