### ISSUE TITLE
NG0303: Can't bind to x since it isn't a known property of 'quill-editor'.

### ISSUE THREAD

**Issue by Kabug** [KillerCodeMonkey/ngx-quill#1582]
# Error
I'm getting the following errors when I run ng test:

- NG0303: Can't bind to '_maxLength_' since it isn't a known property of 'quill-editor'.
- NG0303: Can't bind to '_placeholder_' since it isn't a known property of 'quill-editor'.
- NG0303: Can't bind to '_modules_' since it isn't a known property of 'quill-editor'.

### Versions
    "@types/quill": "^1.3.10",
    "ngx-quill": "^14.3.0",
    "quill": "^1.3.7",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jest": "27.0.4",
    "jest-junit": "^13.0.0",
    Angular: 12.0.5

This is how I have the editor set up.

```
<quill-editor [modules]="quillConfig" id="input-{{FORM_TYPE}}"
    (onContentChanged)="onChange($event)" [ngClass]="{'form-error-input': formErrors[ID]}"
    [formControl]="form.controls[ID]" maxLength="{{MAX_LENGTH}}" placeholder="{{TITLE}}"
    sanitize="true">
</quill-editor>
```

I've also tried binding using [maxLength] = "MAX_LENGTH" and it's throwing the same errors.
Functionally, these three bindings work, but running the test throws errors.

# Test File
<details>
 <summary>Click to expand</summary>

> import { ComponentFixture, TestBed } from '@angular/core/testing';
> import { ReactiveFormsModule, FormsModule } from '@angular/forms';
> import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
> 
> import { RichTextComponent } from './rich-text.component';
> import { QuillModule } from 'ngx-quill';
> 
> describe('RichTextComponent', () => {
>   let component: RichTextComponent;
>   let fixture: ComponentFixture<RichTextComponent>;
> 
>   beforeEach(async () => {
>     await TestBed.configureTestingModule({
>       declarations: [RichTextComponent],
>       imports: [ReactiveFormsModule, FormsModule, QuillModule],
>       schemas: [CUSTOM_ELEMENTS_SCHEMA],
>       providers: [...QuillModule.forRoot().providers]
>     }).compileComponents();
>   });
> 
>   beforeEach(() => {
>     fixture = TestBed.createComponent(RichTextComponent);
>     component = fixture.componentInstance;
>     fixture.detectChanges();
>   });
> 
>   it('should create', () => {
>     expect(component).toBeTruthy();
>   });
> });

</details>

# Error Log
<details>
  <summary>Click to expand</summary>
  

> FAIL  <redacted>/create-group-new.component.spec.ts (30.882 s)
>   ● Console
> 
>     console.error
>       NG0303: Can't bind to 'maxLength' since it isn't a known property of 'quill-editor'.
> 
>       at logUnknownPropertyError (../packages/core/src/render3/instructions/shared.ts:1127:11)
>       at elementPropertyInternal (../packages/core/src/render3/instructions/shared.ts:1009:9)
>       at ɵɵpropertyInterpolate1 (../packages/core/src/render3/instructions/property_interpolation.ts:89:5)
>       at ɵɵpropertyInterpolate (../packages/core/src/render3/instructions/property_interpolation.ts:48:3) 
>       at RichTextComponent_div_8_Template (ng:/RichTextComponent.js:244:5)
>       at executeTemplate (../packages/core/src/render3/instructions/shared.ts:517:5)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:370:7)
>       at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)
> 
>     console.error
>       NG0303: Can't bind to 'placeholder' since it isn't a known property of 'quill-editor'.
> 
>       at logUnknownPropertyError (../packages/core/src/render3/instructions/shared.ts:1127:11)
>       at elementPropertyInternal (../packages/core/src/render3/instructions/shared.ts:1009:9)
>       at ɵɵpropertyInterpolate1 (../packages/core/src/render3/instructions/property_interpolation.ts:89:5)
>       at ɵɵpropertyInterpolate (../packages/core/src/render3/instructions/property_interpolation.ts:48:3)
>       at RichTextComponent_div_8_Template (ng:/RichTextComponent.js:245:5)
>       at executeTemplate (../packages/core/src/render3/instructions/shared.ts:517:5)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:370:7)
>       at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)
> 
>     console.error
>       NG0303: Can't bind to 'modules' since it isn't a known property of 'quill-editor'.
> 
>       at logUnknownPropertyError (../packages/core/src/render3/instructions/shared.ts:1127:11)
>       at elementPropertyInternal (../packages/core/src/render3/instructions/shared.ts:1009:9)
>       at ɵɵproperty (../packages/core/src/render3/instructions/property.ts:42:5)
>       at RichTextComponent_div_8_Template (ng:/RichTextComponent.js:246:5)
>       at executeTemplate (../packages/core/src/render3/instructions/shared.ts:517:5)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:370:7)
>       at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:397:5)
> 
>   ● CreateGroupNewComponent › should create
> 
>     No value accessor for form control with unspecified name attribute
> 
>       at _throwError (../packages/forms/src/directives/shared.ts:284:9)
>       at setUpControl (../packages/forms/src/directives/shared.ts:37:29)
>       at FormControlDirective.Object.<anonymous>.FormControlDirective.ngOnChanges (../packages/forms/src/directives/reactive_directives/form_control_directive.ts:125:7)
>       at FormControlDirective.rememberChangeHistoryAndInvokeOnChangesHook (../packages/core/src/render3/features/ng_onchanges_feature.ts:79:10)
>       at callHook (../packages/core/src/render3/hooks.ts:270:12)
>       at callHooks (../packages/core/src/render3/hooks.ts:230:9)
>       at executeInitAndCheckHooks (../packages/core/src/render3/hooks.ts:174:5)
>       at selectIndexInternal (../packages/core/src/render3/instructions/advance.ts:60:9)
>       at ɵɵadvance (../packages/core/src/render3/instructions/advance.ts:40:3)
>       at RichTextComponent_div_8_Template (ng:/RichTextComponent.js:248:5)
>       at executeTemplate (../packages/core/src/render3/instructions/shared.ts:517:5)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:370:7)
>       at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:397:5)
>       at refreshComponent (../packages/core/src/render3/instructions/shared.ts:1726:7)
>       at refreshChildComponents (../packages/core/src/render3/instructions/shared.ts:116:5)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:427:7)
>       at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:397:5)
>       at refreshComponent (../packages/core/src/render3/instructions/shared.ts:1726:7)
>       at refreshChildComponents (../packages/core/src/render3/instructions/shared.ts:116:5)
>       at refreshView (../packages/core/src/render3/instructions/shared.ts:427:7)
>       at renderComponentOrTemplate (../packages/core/src/render3/instructions/shared.ts:494:5)
>       at tickRootContext (../packages/core/src/render3/instructions/shared.ts:1911:5)
>       at detectChangesInRootView (../packages/core/src/render3/instructions/shared.ts:1934:3)
>       at RootViewRef.Object.<anonymous>.RootViewRef.detectChanges (../packages/core/src/render3/view_ref.ts:312:5)
>       at ComponentFixture.Object.<anonymous>.ComponentFixture._tick (../packages/core/testing/src/component_fixture.ts:113:28)
>       at ../packages/core/testing/src/component_fixture.ts:127:14
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
>       at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
>       at Object.onInvoke (../packages/core/src/zone/ng_zone.ts:405:29)
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
>       at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
>       at NgZone.Object.<anonymous>.NgZone.run (../packages/core/src/zone/ng_zone.ts:184:50)
>       at ComponentFixture.Object.<anonymous>.ComponentFixture.detectChanges (../packages/core/testing/src/component_fixture.ts:126:19)
>       at <redacted>/create-group-new.component.spec.ts:61:13
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
>       at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
>       at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
>       at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)

</details>

**Comment by KillerCodeMonkey** [comment]
just remove testwise `CUSTOM_ELEMENTS_SCHEMA` i would guess that ngx-quill is not correctly imported in your test, but custom elements schema is suppressing the warning/error for it.

**Comment by Kabug** [comment]
Removed `CUSTOM_ELEMENTS_SCHEMA`
Here's the import error

```
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

import { RichTextComponent } from './rich-text-translations.component';
import { QuillModule } from 'ngx-quill';

describe('RichTextComponent', () => {
  let component: RichTextComponent;
  let fixture: ComponentFixture<RichTextComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [RichTextComponent],
      imports: [ReactiveFormsModule, FormsModule, QuillModule],
      providers: [QuillModule.forRoot().providers]
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(RichTextComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

# Error Log
<details>
  <summary>Click to expand</summary>
  

>  ● RichTextComponent › should create
> 
>     Unexpected value 'QuillModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.
> 
>       at verifySemanticsOfNgModuleDef (../packages/core/src/render3/jit/module.ts:198:13)
>       at ../packages/core/src/render3/jit/module.ts:209:5
>           at Array.forEach (<anonymous>)
>       at verifySemanticsOfNgModuleDef (../packages/core/src/render3/jit/module.ts:207:58)
>       at Function.get (../packages/core/src/render3/jit/module.ts:167:13)
>       at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.applyProviderOverridesToModule (../packages/core/testing/src/r3_test_bed_compiler.ts:414:49)    
>       at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.compileTestModule (../packages/core/testing/src/r3_test_bed_compiler.ts:677:10)
>       at R3TestBedCompiler.Object.<anonymous>.R3TestBedCompiler.finalize (../packages/core/testing/src/r3_test_bed_compiler.ts:245:10)
>       at TestBedRender3.get (../packages/core/testing/src/r3_test_bed.ts:370:43)
>       at TestBedRender3.Object.<anonymous>.TestBedRender3.inject (../packages/core/testing/src/r3_test_bed.ts:268:25)
>       at TestBedRender3.Object.<anonymous>.TestBedRender3.createComponent (../packages/core/testing/src/r3_test_bed.ts:325:40)
>       at Function.Object.<anonymous>.TestBedRender3.createComponent (../packages/core/testing/src/r3_test_bed.ts:177:33)
>       at <redacted>/rich-text-translations.component.spec.ts:20:23
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
>       at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
>       at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
>       at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
>       at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)


FAIL <redacted>create-listing.component.spec.ts (165.794 s)
  ● Console

    console.error
      NG0303: Can't bind to 'maxLength' since it isn't a known property of 'quill-editor'.

      at logUnknownPropertyError (../packages/core/src/render3/instructions/shared.ts:1127:11)
      at elementPropertyInternal (../packages/core/src/render3/instructions/shared.ts:1009:9)
      at ɵɵpropertyInterpolate1 (../packages/core/src/render3/instructions/property_interpolation.ts:89:5)
      at ɵɵpropertyInterpolate (../packages/core/src/render3/instructions/property_interpolation.ts:48:3)
      at RichTextComponent_div_8_Template (ng:/RichTextComponent.js:244:5)
      at executeTemplate (../packages/core/src/render3/instructions/shared.ts:517:5)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:370:7)
      at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)

    console.error
      NG0303: Can't bind to 'placeholder' since it isn't a known property of 'quill-editor'.

      at logUnknownPropertyError (../packages/core/src/render3/instructions/shared.ts:1127:11)
      at elementPropertyInternal (../packages/core/src/render3/instructions/shared.ts:1009:9)
      at ɵɵpropertyInterpolate1 (../packages/core/src/render3/instructions/property_interpolation.ts:89:5)
      at ɵɵpropertyInterpolate (../packages/core/src/render3/instructions/property_interpolation.ts:48:3)
      at RichTextComponent_div_8_Template (ng:/RichTextComponent.js:245:5)
      at executeTemplate (../packages/core/src/render3/instructions/shared.ts:517:5)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:370:7)
      at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)

    console.error
      NG0303: Can't bind to 'modules' since it isn't a known property of 'quill-editor'.

      at logUnknownPropertyError (../packages/core/src/render3/instructions/shared.ts:1127:11)
      at elementPropertyInternal (../packages/core/src/render3/instructions/shared.ts:1009:9)
      at ɵɵproperty (../packages/core/src/render3/instructions/property.ts:42:5)
      at RichTextComponent_div_8_Template (ng:/RichTextComponent.js:246:5)
      at executeTemplate (../packages/core/src/render3/instructions/shared.ts:517:5)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:370:7)
      at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:397:5)

  ● CreateListingComponent › should create

    No value accessor for form control with unspecified name attribute

      at _throwError (../packages/forms/src/directives/shared.ts:284:9)
      at setUpControl (../packages/forms/src/directives/shared.ts:37:29)
      at FormControlDirective.Object.<anonymous>.FormControlDirective.ngOnChanges (../packages/forms/src/directives/reactive_directives/form_control_directive.ts:125:7)
      at FormControlDirective.rememberChangeHistoryAndInvokeOnChangesHook (../packages/core/src/render3/features/ng_onchanges_feature.ts:79:10)
      at callHook (../packages/core/src/render3/hooks.ts:270:12)
      at callHooks (../packages/core/src/render3/hooks.ts:230:9)
      at executeInitAndCheckHooks (../packages/core/src/render3/hooks.ts:174:5)
      at selectIndexInternal (../packages/core/src/render3/instructions/advance.ts:60:9)
      at ɵɵadvance (../packages/core/src/render3/instructions/advance.ts:40:3)
      at RichTextComponent_div_8_Template (ng:/RichTextComponent.js:248:5)
      at executeTemplate (../packages/core/src/render3/instructions/shared.ts:517:5)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:370:7)
      at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:397:5)
      at refreshComponent (../packages/core/src/render3/instructions/shared.ts:1726:7)
      at refreshChildComponents (../packages/core/src/render3/instructions/shared.ts:116:5)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:427:7)
      at refreshEmbeddedViews (../packages/core/src/render3/instructions/shared.ts:1676:9)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:397:5)
      at refreshComponent (../packages/core/src/render3/instructions/shared.ts:1726:7)
      at refreshChildComponents (../packages/core/src/render3/instructions/shared.ts:116:5)
      at refreshView (../packages/core/src/render3/instructions/shared.ts:427:7)
      at renderComponentOrTemplate (../packages/core/src/render3/instructions/shared.ts:494:5)
      at tickRootContext (../packages/core/src/render3/instructions/shared.ts:1911:5)
      at detectChangesInRootView (../packages/core/src/render3/instructions/shared.ts:1934:3)
      at RootViewRef.Object.<anonymous>.RootViewRef.detectChanges (../packages/core/src/render3/view_ref.ts:312:5)
      at ComponentFixture.Object.<anonymous>.ComponentFixture._tick (../packages/core/testing/src/component_fixture.ts:113:28)
      at ../packages/core/testing/src/component_fixture.ts:127:14
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Object.onInvoke (../packages/core/src/zone/ng_zone.ts:405:29)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at NgZone.Object.<anonymous>.NgZone.run (../packages/core/src/zone/ng_zone.ts:184:50)
      at ComponentFixture.Object.<anonymous>.ComponentFixture.detectChanges (../packages/core/testing/src/component_fixture.ts:126:19)
      at <redacted>/create-listing.component.spec.ts:79:13
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)
</details>

**Comment by Kabug** [comment]
Sorry, I forgot to add, the binding errors are from the parent. I've added the spec file below to see if I'm doing anything wrong. I've just imported the child component that had the quill-editor inside the HTML. 

```
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ReactiveFormsModule } from '@angular/forms';
import { MatAutocompleteModule } from '@angular/material/autocomplete';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatMenuModule } from '@angular/material/menu';
import { MatSelectModule } from '@angular/material/select';
import { RouterTestingModule } from '@angular/router/testing';
import { UiLibraryModule } from '@cxp/angular-ui-library';
import { of } from 'rxjs/internal/observable/of';
import { IconComponent } from '../../../components/icon/icon.component';
import { RichTextComponent } from '../../../components/rich-text-translations/rich-text-translations.component';
import { SpinnerComponent } from '../../../components/spinner/spinner.component';
import { DataService } from '../../../services/data.service';
import { ToastService } from '../../../services/toast.service';

import { CreateGroupNewComponent } from './create-group-new.component';

describe('CreateGroupNewComponent', () => {
  let component: CreateGroupNewComponent;
  let fixture: ComponentFixture<CreateGroupNewComponent>;

  const DataServiceStub = {
    getRegions: () => of([])
  };

  const ToastServiceStub = {
    error: () => '',
    success: () => '',
    info: () => '',
    warning: () => ''
  };

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [CreateGroupNewComponent, SpinnerComponent, IconComponent, RichTextComponent],
      imports: [
        RouterTestingModule,
        HttpClientTestingModule,
        ReactiveFormsModule,
        MatIconModule,
        MatMenuModule,
        UiLibraryModule,
        MatSelectModule,
        MatFormFieldModule,
        MatAutocompleteModule,
        MatInputModule
      ],
      providers: [
        { provide: DataService, useValue: DataServiceStub },
        { provide: ToastService, useValue: ToastServiceStub }
      ]
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(CreateGroupNewComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

```

**Comment by KillerCodeMonkey** [comment]
and in this test case you are not adding QuillModule to your imports. so your test does not know nothing about ngx-quill components.

**Comment by Kabug** [comment]
Thank you for taking the time to reply, appreciate it!

In case anyone else is having this error in the parent component, after I did this it stopped throwing.
Rich-text is the child and I had to add the quill editor component as well.

```
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ReactiveFormsModule } from '@angular/forms';
import { MatAutocompleteModule } from '@angular/material/autocomplete';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatMenuModule } from '@angular/material/menu';
import { MatSelectModule } from '@angular/material/select';
import { RouterTestingModule } from '@angular/router/testing';
import { UiLibraryModule } from '@cxp/angular-ui-library';
import { of } from 'rxjs/internal/observable/of';
import { IconComponent } from '../../../components/icon/icon.component';
import { SpinnerComponent } from '../../../components/spinner/spinner.component';
import { DataService } from '../../../services/data.service';
import { ToastService } from '../../../services/toast.service';
import { RichTextComponent } from '../../../components/rich-text-translations/rich-text-translations.component';
import { QuillEditorComponent } from 'ngx-quill';
import { CreateGroupNewComponent } from './create-group-new.component';

describe('CreateGroupNewComponent', () => {
  let component: CreateGroupNewComponent;
  let fixture: ComponentFixture<CreateGroupNewComponent>;

  const DataServiceStub = {
    getRegions: () => of([])
  };

  const ToastServiceStub = {
    error: () => '',
    success: () => '',
    info: () => '',
    warning: () => ''
  };

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [CreateGroupNewComponent, SpinnerComponent, IconComponent, RichTextComponent, QuillEditorComponent],
      imports: [
        RouterTestingModule,
        HttpClientTestingModule,
        ReactiveFormsModule,
        MatIconModule,
        MatMenuModule,
        UiLibraryModule,
        MatSelectModule,
        MatFormFieldModule,
        MatAutocompleteModule,
        MatInputModule
      ],
      providers: [
        { provide: DataService, useValue: DataServiceStub },
        { provide: ToastService, useValue: ToastServiceStub }
      ]
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(CreateGroupNewComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```
