### ISSUE TITLE
ngx-quill editor not showing as expected after deployment 

### ISSUE THREAD

**Issue by akhilapnair** [KillerCodeMonkey/ngx-quill#1588]
![quill](https://user-images.githubusercontent.com/30194751/183650924-398b2e50-a5ba-4f8e-8d07-0066cebae77e.png)

added  in style.css
@import '~quill/dist/quill.snow.css';

added in angular.json
"scripts": ["./node_modules/quill/dist/quill.min.js"]

Editor work Locally issue is with when deploying .

**Comment by KillerCodeMonkey** [comment]
yeah then i guess your css or script is not bundled linked correctly in production bundles.

check my demo repo linked in the readme. there you can see a production ready project + that it is working deployed to github pages

**Comment by KillerCodeMonkey** [comment]
If so I would guess your css is not resolved in production. Check if the
css sources are really loaded on production. Then it is more a
misconfiguration of your app and not of ngx-quill.


akhilapnair ***@***.***> schrieb am Di., 9. Aug. 2022, 14:53:
