### ISSUE TITLE
Feature request: Make SSR friendly

### ISSUE THREAD

**Issue by cbernth** [KillerCodeMonkey/ngx-quill#159]
**The Case**
ngx-quill is the best overall choice for angular 5+ applications in my opinion, however usage is strongly limited by the various hacks you need in order to make it Server Side Rendering friendly, which is a key property of Angular because of it's SEO compatibility.

There 's a hack here to make it work by mocking #91 

However, Angular itself supports the mocking internally as described [here](https://stackoverflow.com/questions/45331909/angular-4-universal-different-component-module-for-server-and-browser) but for ngx-quill, this needs to be done internally.

Requiring every ngx-quill user has to spend hours hacking their way around using it properly (which makes it error prone) is not the most efficient way around it.

**The Request**
Embed the mocking directly in ngx-quill using the angular properties isPlatformBrowser/isPlatformServer  so both Browser and Server side works out of the box.

Thank you very much :)

**Comment by KillerCodeMonkey** [comment]
@cbernth hey there i added a ngIf that makes sure, that quill is only rendered if not ssr.

i even use the angular-way to grab the document instance.
Could you test this with Angular Universal?

**Comment by helix46** [comment]
https://github.com/helix46/test-cli-quill

Sorry, my previous link was broken
Code above uses mocks for quill and ngx-quill, webpack replaces them for the server side code
I've tested it successfully with Angular 5 but haven't tested with Angular 6

**Comment by thefliik** [comment]
Added PR #190 which fixes this (I think). Unlike your solution, @helix46, this change doesn't require the user of the package to do anything special with webpack. As I mention in the PR though, I'm not sure what affect, if any, using `require` vs `import` will have on tree shaking / code optimization.

**Comment by KillerCodeMonkey** [comment]
woooooooow, thanks @thefliik !!!

**Comment by KillerCodeMonkey** [comment]
could someone check the 3.2.0 release with ssr?

**Comment by thefliik** [comment]
@KillerCodeMonkey Just tested using the [angular universal starter repo](https://github.com/angular/universal-starter) and it works.

*note: I had to update the starter repo's `package.json` to use the latest versions of all dependencies (a few dependencies were locked to specific, old, versions--i.e. missing the `^`--and this was causing some strange bug that went away when I upgraded everything to the latest version)*

**Comment by thefliik** [comment]
And by works, I mean it defers initializing quill until loaded on the browser side.

**Comment by KillerCodeMonkey** [comment]
Feel free to create a pull request and thanks for testing and detaiks

thefliik <notifications@github.com> schrieb am Sa., 9. Juni 2018, 04:22:

**Comment by helix46** [comment]
@KillerCodeMonkey Yes I've tested 3.2.0 with the latest V6, works well thank you.
The code for the test is here:
https://github.com/helix46/test-quill-universal

**Comment by helix46** [comment]
And thanks @thefliik !

**Comment by KillerCodeMonkey** [comment]
@thefliik do you have time or in the mood to create such a service to solve up ssr compatibility with your approach?

**Comment by cbernth** [comment]
Thanks @KillerCodeMonkey  I was a bit late to the testing party, but v. 3.2.0 works like a charm (in my Angular 5.2.10 project) so I have now removed my servermocks.

Thanks 👍

**Comment by thefliik** [comment]
@KillerCodeMonkey not at the moment.

**Comment by amir-Yegane** [comment]
Hi, I have a problem with Quill.register ('modules / imageResize', ImageResize);
when I use it with angular universal, I am facing with "ReferenceError: document is not defined    at Object.DIFF_DELETE"
How should I solve it?

**Comment by KillerCodeMonkey** [comment]
Require and Register after the document objects IS available.

The document IS Not available in Serverside.
I am Not an expert with SSR. But You can Check the Code of the
quill-editor.component.ts how quilljs IS loaded there.

Am Mi., 28. Nov. 2018, 02:17 hat amir-Yegane <notifications@github.com>
geschrieben:
