### ISSUE TITLE
will onEditorCreated emit for several times or should it complete?

### ISSUE THREAD

**Issue by KingMario** [KillerCodeMonkey/ngx-quill#1590]
Hi @KillerCodeMonkey,

I'd like to know if onEditorCreated will be emitted multiple times?

If onEditorCreated is emitted at most once, should its complete method be called?

Otherwise, in practice, I would unsubscribe the subscription in ngOnDestroy of my component.

Thanks for your great work and looking forward to your answer.

**Comment by KillerCodeMonkey** [comment]
In General it should complete but i think it is not implemented like this.

But it's only triggered once after initialisation of the quill editor
itself.

But it would be a nice improvement to not just use a simple subject for it

Changyu Geng ***@***.***> schrieb am Di., 16. Aug. 2022,
16:58:

**Comment by KillerCodeMonkey** [comment]
in v19.0.1 the subject is closed right after emitting that editors or initialized.
