### ISSUE TITLE
The quill mention display 'undefined' in quill-view using 'html' format

### ISSUE THREAD

**Issue by zhonglin94** [KillerCodeMonkey/ngx-quill#1591]
Reproduce steps:
1. I established a project using the following dependencies. 
>  "@angular/animations": "^12.2.13",
    "@angular/cdk": "^12.2.13",
    "@angular/common": "^12.2.13",
    "@angular/compiler": "^12.2.13",
    "@angular/core": "^12.2.13",
    "@angular/forms": "^12.2.13",
    "@angular/material": "^12.2.13",
    "@angular/platform-browser": "^12.2.13",
    "ngx-quill": "^14.0.0",
    "quill": "^1.3.7",
    "quill-emoji": "^0.2.0",
    "quill-mention": "^3.1.0",
2. I import the quill module with a config `{format: 'html', theme: 'snow'}`
3. I import quill-editor and quill-view in an Angular component
4. I  @ a people in the quill-editor and It functions correctly
5. I send the content from the quill-editor for quill-view for display.
6. Then it shows a 'undefined' as the following image
![image](https://user-images.githubusercontent.com/32061513/185839989-69ba43c5-1bf7-4f09-a8c0-082bbef1bc1a.png)
7. If I switch the format from 'html' to 'json', the mention would behave correctly
8. Further, I inspected the content sent for the quill-view for display
> <p>
    <span class="mention" data-index="6" data-denotation-char="@" data-id="p***@***.com" data-value="P*** F***">﻿<span
            contenteditable="false">
        <span class="ql-mention-denotation-char">@</span>
        P*** F***
    </span>﻿
    </span>
</p>

**Comment by KillerCodeMonkey** [comment]
Check my demo repo

There is an example for quill mention.

Per Default quill mention triggers changes when inserting names as "API" not as user. 

So you can do the workaround shown in the demo repo or you can set the config or input to track all changes and not only "user" ones.

**Comment by guerreroje** [comment]
This may be the reason: #1555

**Comment by zhonglin94** [comment]
> This may be the reason: #1555
It's pretty the same. Any workaround
