### ISSUE TITLE
Quill can't find custom toolbar

### ISSUE THREAD

**Issue by popastefan10** [KillerCodeMonkey/ngx-quill#1592]
I want to have a custom toolbar for my quill editor, and it worked at some point. I  started with the example from [here](https://quilljs.com/docs/modules/toolbar/), and I managed to add a custom save indicator. Then I merged the develop branch (which doesn't use ngx-quill anywhere) from the project I'm working on into my editor branch and I get the following error:
![Screenshot 2022-08-24 at 09 19 14](https://user-images.githubusercontent.com/54329613/186351100-bce38edd-d527-4aec-8aec-423d2baf6a4f.png)

The editor looks like this:
![Screenshot 2022-08-24 at 10 08 42](https://user-images.githubusercontent.com/54329613/186353832-182494c7-fa89-438c-9637-db2ed2117161.png)

Expected behaviour:
![Screenshot 2022-08-24 at 10 10 34](https://user-images.githubusercontent.com/54329613/186354159-29483f8f-391b-462d-88ec-b8312fbc68d3.png)

If I replace my code with the one from quilljs docs I still get these errors. Current code (basically copy-pasted from the docs):

- component.html
```ts
<div id="toolbar">
  <!-- Add font size dropdown -->
  <select class="ql-size">
    <option value="small"></option>
    <!-- Note a missing, thus falsy value, is used to reset to default -->
    <option selected></option>
    <option value="large"></option>
    <option value="huge"></option>
  </select>
  <!-- Add a bold button -->
  <button class="ql-bold"></button>
  <!-- Add subscript and superscript buttons -->
  <button class="ql-script" value="sub"></button>
  <button class="ql-script" value="super"></button>
</div>
<div id="editor"></div>
<quill-editor [modules]="modules"></quill-editor>
```
- component.ts:
```ts
export class MyComponent {
  ...
  public readonly modules = {
    toolbar: '#toolbar'
  }
  ...
}
```
- modules versions:
```
ngx-quill@18.0.0
quill@1.3.7
@types/quill@1.3.10
```

Later edit:
The issue is related to Material Tabs. The editor is not on the default tab, so it is initialized but the toolbar is not inserted into DOM so it can't find it and throws the error.

**Comment by KillerCodeMonkey** [comment]
In General you need to make sure, that your dom node is rendered and
accessible when quill gets initialized

Stefan Popa ***@***.***> schrieb am Mi., 24. Aug. 2022, 09:12:

**Comment by KillerCodeMonkey** [comment]
And check the readme You can add a custom toolbar with a custom projection.
So no need to pass the custom toolbar selector

Bengt Weiße ***@***.***> schrieb am Mi., 24. Aug. 2022, 10:57:

**Comment by popastefan10** [comment]
Thank you, I modified to use content projection instead of toolbar selector
