### ISSUE TITLE
Handler for removing an image

### ISSUE THREAD

**Issue by DennisBoanini** [KillerCodeMonkey/ngx-quill#1594]
I've an handler when I add an image, but there is also an handler for the removing image?

When someone remove an image from the editor I need to call the server to remove the saved image

**Comment by KillerCodeMonkey** [comment]
this is more a quill question and not ngx-quill.

solution i can think of:

subscribe to changes of the content of the editor with the onContentChanged output (https://github.com/KillerCodeMonkey/ngx-quill#outputs). There you get the new and old delta. Make a diff and check if an image got removed.

or diff the whole content when you save your changes in the backend. Select the old value from the database, compare it to the new one e.g. if you store html just grab all image tags and parse the src. if you store json -> make json stringify and grab all image contents and the src attribute.

compare both lists and remove not existing ones
