### ISSUE TITLE
Import Delta module error

### ISSUE THREAD

**Issue by sandeepso** [KillerCodeMonkey/ngx-quill#1596]
I downloaded and installed all dependency for ngx-quill in my angular project and was getting below compilation error. my project is using angular v14.2.0 .

_Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:21 - error TS2614: Module '"quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "quill"' instead?_

So to fix this issue, I have to modify import in quill-editor.component.d.ts component in node_modules as per below:
import QuillType from 'quill';
import Delta from 'quill';

I think its know issue, but I don't see it addressed in angular component, can you please include fix for this issue in upcoming builds.
Thanks!

**Comment by KillerCodeMonkey** [comment]
No you have to install the correct version of @types/quill... Please read
the readme carefully and search for similar issues first.

You even find the correct versions in the linked demo repo...

Sandeep Sonawane ***@***.***> schrieb am Fr., 2. Sept. 2022,
18:28:

**Comment by sandeepso** [comment]
yes, installing  version 1.3.10 of @types/quill fixed it. 

Thanks!
