### ISSUE TITLE
How can we switch quill-editor-element  and quill-editor-toolbar ?

### ISSUE THREAD

**Issue by bondchan921** [KillerCodeMonkey/ngx-quill#160]
I go it integrated with Ionic, want to put quill-editor-toolbar at the bottom.

**Comment by KillerCodeMonkey** [comment]
wooooot. maybe you can describe you problem in a whole sentence.

quill-editor-toolbar is only a part of the quill-editor and needs to be a child of quill-editor.
Checkout the last code-block in the config section of the readme:
https://github.com/KillerCodeMonkey/ngx-quill#config

or check this example code:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts#L64

you can see the examples here:
https://killercodemonkey.github.io/ngx-quill-example/

**Comment by bondchan921** [comment]
- See the attached, I want to have the tool-bar at the bottom of the screen.

![Uploading 2.PNG…]()

**Comment by bondchan921** [comment]
- See the attached, I want to have the tool-bar at the bottom of the screen.
---------------------------------------------
|                                                                |
|                                                                |               -->editor-element at the top.
|                                                                |
---------------------------------------------
|   B _i_      XX  YY ...                                  |                 -->tool bar at the bottom
---------------------------------------------

**Comment by bondchan921** [comment]
@KillerCodeMonkey -- sorry for the ugly diagram above, tried to upload an image - no ideal failed all the time...

Not sure why this issue was closed.

**Comment by KillerCodeMonkey** [comment]
@bondchan921 i do not know if this is possible, please ask this in quilljs. Are use CSS/JavaScript.

e.g. you could try to move the toolbar with flexbox layouting to the end (flex-direction: column-reverse)

**Comment by bondchan921** [comment]
Thanks @KillerCodeMonkey -- but for running in Mobile, the toolbar is good to be placed at the bottom.

**Comment by KillerCodeMonkey** [comment]
Yeah but the usability of a rich text editor on mobile is not a good approach at all, yet
Because to format input with open keyboard on smaller screens is very frustrating.
I would expect a more native way.

But go on. I think I saw some examples with the toolbar at the bottom lately.

**Comment by dfromero** [comment]
@KillerCodeMonkey I was also looking for this but I just settle with flex reverse approach. But It is possible to swap them on quilljs if you define the toolbar and container elements separately see [codepen](https://codepen.io/dfromero/pen/MGZOZY) . you would just need to swap the order ie. put the toolbar after the editor element, but this needs to have the toolbar as element, can't be done with the object syntax.
