### ISSUE TITLE
ngModel does not update after insertEmbed with source 'user'

### ISSUE THREAD

**Issue by dineshkumar02** [KillerCodeMonkey/ngx-quill#1601]
While upload the image to the editor and via `insertEmbed` method,
the `ngModel` is not reflecting the changes.

But the `insertText` is working as expected.

Would you share some inputs and suggestions on this please.

```
Angular version : 14.0.0
ngx-quill : 18.0.0
```

Code, which is not working as expected

```
const range = this.editor.getSelection(true);
this.editor.insertEmbed(range.index, 'image', url, 'user');



  <quill-editor [styles]="{height: '200px'}" [(ngModel)]="description" (onEditorCreated)="editorCreated($event)">
  </quill-editor>


```

Note: On the editor, it's rendering the image but on the `ngModel` it's not reflecting the changes.

Please let me know If I miss anything here

**Comment by KillerCodeMonkey** [comment]
I only have the opportunity to listen on quilljs events when the content
changes. You could test with plain quilljs if the quilljs event
https://quilljs.com/docs/api/#events Text-Change is called + the correct
source is set. If this is not working you should check the quilljs repo for
issues.

I have no other possibility to get informed for changes

Dinesh Kumar ***@***.***> schrieb am Fr., 9. Sept. 2022,
17:59:

**Comment by dineshkumar02** [comment]
Thanks for the response.

If I remember correctly, it was working fine with the Angular 13 and the problem is started with the 14 version.
Need to further investigation from my side, and will post some findings.

**Comment by KillerCodeMonkey** [comment]
Thanks. I guess i changed nothing in the "base handling" in that part. But
thanks again for your investigating.

Dinesh Kumar ***@***.***> schrieb am Sa., 10. Sept. 2022,
19:54:

**Comment by KillerCodeMonkey** [comment]
do you have any findings?

**Comment by dineshkumar02** [comment]
Apologies for the delay, I may need some more time to test this functionality.
Probably in the next couple of days.

**Comment by dineshkumar02** [comment]
With below versions, things are working fine as expected 

Angular version:     
```
    "@angular/animations": "^13.3.8",
    "@angular/common": "^13.3.8",
    "@angular/compiler": "^13.3.8",
    "@angular/core": "^13.3.8",
    "@angular/fire": "^7.2",
    "@angular/forms": "^13.3.8",
    "@angular/platform-browser": "^13.3.8",
    "@angular/platform-browser-dynamic": "^13.3.8",
    "@angular/router": "^13.3.8",
```

devDeps
```
    "@angular-devkit/build-angular": "^13.3.5",
    "@angular/cli": "^13.3.5",
    "@angular/compiler-cli": "^13.3.8",
```

ngx-quill:

` "ngx-quill": "^15.0.0",
`

**Comment by dineshkumar02** [comment]
My sincere apologies,

The root cause of this issue is, whenever I config the QuillModule with the required options with below, then insertEmbed is not working.

**Not Working**
```
QuillModule.forRoot(

         {
         format: 'text',
         modules: {
           toolbar: [
             ['bold', 'italic', 'underline', 'strike'],
             ['blockquote', 'code-block'],
             [{ 'header': 1 }, { 'header': 2 }],
             [{ 'list': 'ordered' }, { 'list': 'bullet' }],
             [{ 'script': 'sub' }, { 'script': 'super' }],
             [{ 'indent': '-1' }, { 'indent': '+1' }],
             [{ 'direction': 'rtl' }],
             [{ 'size': ['small', false, 'large', 'huge'] }],
             [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
             ['link', 'image'],
             ['clean'],
           ],
         },
       }
    ),
```

If I remove the options, and just use QuillModule.forRoot() then, image binding with the model is working.

Please let me know if you see any issues with the options which I have

**Comment by dineshkumar02** [comment]
You are right. 

By removing format: 'text', it's working :-) 

Thanks for your help and suggestions, apologies for the delay

**Comment by KillerCodeMonkey** [comment]
No problem. Nice that your issue is resolved

Dinesh Kumar ***@***.***> schrieb am Sa., 17. Sept. 2022,
09:46:
