### ISSUE TITLE
registering additional quill modules *extremely* unintuitive

### ISSUE THREAD

**Issue by uther-p** [KillerCodeMonkey/ngx-quill#1605]
I have been searching but cannot find *how* to register a new Quill module when loading quill through this angular module.

how is this accomplished?  these details should not have to be discovered by digging through the code

**Comment by KillerCodeMonkey** [comment]
Therefore you have the readme and "customModules" option and the demo
repository ;-).

If something is missing, feel free to create a PR with additional Info

uther-p ***@***.***> schrieb am Di., 13. Sept. 2022, 20:20:

**Comment by uther-p** [comment]
I did eventually find how it's done, I think it would be helpful if, rather
than just say "use customModules...", You describe *how* you add them. i.e.
what object properties the customModules configuration requires (path and
implementation).

Also considering it overwrites the existing list, maybe just add a function
to the default export for registering them, like quill does with the
'register' function

**Comment by KillerCodeMonkey** [comment]
btw. you can even go for the quill way. just import quill before the usages of ngx-quill components and register your stuff at quill.

i added examples to the readme and linked the demo repo directly.

And in the readme were hints, that those options override the modules and options globally.

**Comment by KillerCodeMonkey** [comment]
And in the readme it says:


   - use customOptions for adding for example custom font sizes --> this
   overwrites this options *globally* !!!
   - use customModules for adding and overwriting modules --> this
   overwrites this modules *globally* !!!

But as I said. If you think an example makes sense in the readme - add it
and send me a PR. ;-)

uther-p ***@***.***> schrieb am Di., 13. Sept. 2022, 22:00:

> I did eventually find how it's done, I think it would be helpful if, rather
> than just say "use customModules...", You describe *how* you add them. i.e.
> what object properties the customModules configuration requires (path and
> implementation).
>
> Also considering it overwrites the existing list, maybe just add a function
> to the default export for registering them, like quill does with the
> 'register' function
>
