### ISSUE TITLE
disable a button takes too long to grey out

### ISSUE THREAD

**Issue by bondchan921** [KillerCodeMonkey/ngx-quill#161]
when disabling button(click it after turned blue), it takes quite a long time to turn to grey 

steps:
1) click button 'B' to enable Bold, the button turns blue.
2) click button  'B' again after typing some bold words, expect to be grey right away, but actually takes quite a long time.

**Comment by KillerCodeMonkey** [comment]
https://killercodemonkey.github.io/ngx-quill-example/

can not reproduce your issue in latest safari, chrome, firefox on my demo page.
.. build a plunkr or codepen which shows the problem.

Maybe you have some browser extensions installed, which causes the problem.

even check the quilljs.com editor first, if you got the problem there ;)

**Comment by bondchan921** [comment]
https://killercodemonkey.github.io/ngx-quill-example/
@KillerCodeMonkey -- with Chrome , Pressing F12 , then Ctrl + Shit +M, switch to mobile mode. then you should see.

**Comment by KillerCodeMonkey** [comment]
nope, like i said it works - you should keep in mind the hove/active state of the format-buttons are also styled in blue.

so if you touch, but the element has the active/hover state it stays blue..

**Comment by bondchan921** [comment]
Weird - but after re-focus by touching anywhere of element quill-editor-element, the button did change its color as expected.

**Comment by KillerCodeMonkey** [comment]
;) yeah because the element stays active/hover on mobile.
