### ISSUE TITLE
QuillService with providedIn: 'root' seems to be bad idea

### ISSUE THREAD

**Issue by visitek** [KillerCodeMonkey/ngx-quill#1611]
It seems to be impossible to have multiple configurations of quill on the page.

even with:
`providers: [
        {
            provide: QUILL_CONFIG_TOKEN, useValue: {
                formats: [
                    'bold',
                    'code',
                    'italic',
                    'link',
                    'strike',
                    'script',
                    'underline', ....
                ]
            } as QuillConfig
        }
    ]`

the service is instantiated once in the root

**Comment by KillerCodeMonkey** [comment]
That was the initial idea, to just have a global config :).

You could pass custom config to the editor-component via customModules and
customOptions.

**Comment by KillerCodeMonkey** [comment]
or you just create your own instance and use it as described here when using angular-elements.

https://github.com/KillerCodeMonkey/ngx-quill/issues/1481#issuecomment-1280999446
