### ISSUE TITLE
Stripping html tags from editor.

### ISSUE THREAD

**Issue by 5t41k3r** [KillerCodeMonkey/ngx-quill#1612]
I have used quill editor for a while. Normally this would work fine but after recent updates it appears to work different. 
I am setting the value of the formControl in angular as normal .setValue(. 
When I log the formControl value it shows the html tags. But the formatting is not reflected in the editor WYSIWYG box. 
On keydown or valueChange within the editior, it strips the html values from the formControl.value (however the formatting displayed is all inline even when the formControl value reflects different html content). 

Before:
`<p><span class="ql-font-serif">test 2 update</span></p><p><span class="ql-font-monospace">Another test to see how good </span><strong class="ql-font-monospace">the editor works </strong></p><ol><li><strong class="ql-font-monospace">it works fine</strong></li><li><strong class="ql-font-monospace">so it works fine</strong></li><li><strong class="ql-font-monospace">it works better </strong></li></ol>`

After: (editor always looks like this even when value entered above should show number points)
`<p><span class="ql-font-serif">test 2 update</span><span class="ql-font-monospace">Another test to see how good </span><strong class="ql-font-monospace">the editor works it works fineso it works fineit works better  </strong></p>`

I have tried to bypass sanitization of the input and it is making no difference. Am i setting the value of the editor incorrectly? Has the wider formGroup playing a part in this?
 Any suggestions on other ways to input the html value into the editor and maintain its formatting?

**Comment by KillerCodeMonkey** [comment]
could you share an example to reproduce like a stackblitz?

in my live demo everything is working fine.
maybe you set the format to text instead of html?

**Comment by 5t41k3r** [comment]
So currently it is on a large closed application however. I have moved the editor outside of a mat-tab-group/mat-tab module and now the html is being mapped fine... this appears to be a problem with material tab sanitizing... Sorry for pointing the finger in the wrong direction. 

For anyone else having similar issues with html stripping, ensure its not the parent component doing it.

**Comment by KillerCodeMonkey** [comment]
ahh i remember. there where other issues with material ui and tabs.

I guess you only make sure to render quill after the tab becomes active in visible. Then it should work again

**Comment by KeithGillette** [comment]
Thanks for posting your findings, @5t41k3r and for your fix suggestions, @KillerCodeMonkey. I was having the same issue of HTML markup disappearing when embedding `quill-editor` in a PrimeNG `p-dialog` (using template outlets). I was able to fix the issue by adding to the `ng-container` inside the `p-dialog` an `*ngIf` bound to the controller property controlling dialog visibility.
