### ISSUE TITLE
onBlur is falsely fired 

### ISSUE THREAD

**Issue by krema** [KillerCodeMonkey/ngx-quill#1614]
I configured the toolbar to be outside of the editor:

    <quill-editor (onBlur)="onBlur($event) "[modules]="{toolbar: '#toolbar'}"> </quill-editor>

When I click the toolbar formatting buttons, the onBlur event fires incorrectly. This doesn't happen with the default toolbar that resides within the editor.

Is this a bug within ngx-quill or in quill itself?

**Comment by KillerCodeMonkey** [comment]
I think it is more a quill thing. I am just wrapping the "selection
changed" event of quill to evaluate if it is just a selection change or
focus and blur.

Everytime the new range is null I trigger blur. If the old range is null,
but not the current it is focus.

André Kremser ***@***.***> schrieb am Sa., 15. Okt. 2022,
20:59:
