### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by alienforhumans** [KillerCodeMonkey/ngx-quill#1617]
Error says:

![image](https://user-images.githubusercontent.com/50145645/198032759-fcc86b8c-f94e-4e87-8d18-502a57cd00c1.png)

Solved when i change in ngx-quill/lib/quill-editor.component.d.ts

from

```
import QuillType, { Delta } from 'quill';
```

to 

```
import QuillType from 'quill';
import Delta from 'quill';
```

**Comment by KillerCodeMonkey** [comment]
again... please read the readme or check for already closed issues... install the correct version of the typings..

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill#installation

> install @angular/core, @angular/common, @angular/forms, @angular/platform-browser, **quill v1.x, @types/quill v1.x** and rxjs - peer dependencies of ngx-quill
