### ISSUE TITLE
Handler for image removing

### ISSUE THREAD

**Issue by DennisBoanini** [KillerCodeMonkey/ngx-quill#1624]
I was able to add an handler on the image upload and upload the image on the server and paste the returned link on the editor but how I can handle the image removal? How I can be able to intercept the removal of the image from the editor and then remove it also from the server?

**Comment by KillerCodeMonkey** [comment]
thats a question for the quilljs repository ;-).

but in general you had to listen on changes and check if there was an image in that place.
