### ISSUE TITLE
rxjs v7 not supported by angular/core

### ISSUE THREAD

**Issue by delboy1978uk** [KillerCodeMonkey/ngx-quill#1630]
ngx-quill has v7 of rxjs listed as a dependency, yet angular core only supports up to v6:

https://github.com/angular/angular/blob/main/package.json#L159 

<img width="819" alt="image" src="https://user-images.githubusercontent.com/2684575/205628401-db6b4bf5-8b1f-4de3-8c47-9176c8bbef9c.png">

The last fully compatible version is ngx-quill v16.0.0, which uses rxjs v6.6.7, yet that is not compatible with v14 of Angular, v17 and above of ngx-quill are all using v7 of rxjs.

Is it possible for you to lower the dependency back? I don't really want to 
`--force or --legacy-peer-deps  to accept an incorrect (and potentially broken) dependency resolution.`
as that would mean software with BC breaks causing potential problems

**Comment by delboy1978uk** [comment]
Actually this could be a false alarm, my screenshot says ^6.5.3 || ^7.4.0 for angular core, yet at the same time the package json i linked above says only v6, I'll close this with apologies if I manage to get it up and running.

**Comment by KillerCodeMonkey** [comment]
no probs. i am confused all the time about the strange deps... so no probs. :D. More than a thx for checking it again :D

**Comment by delboy1978uk** [comment]
Yes, we have it resolved, thanks.

**Comment by KillerCodeMonkey** [comment]
To avoid it you could install a ngxquill version >=17 and <= 20.

Or use overrides in your package.json for rxjs. Beside of that angular/core
quill and rxjs are the only peer deps of ngx-quill


emma-one ***@***.***> schrieb am Di., 14. März 2023, 12:06:
