### ISSUE TITLE
"syntax" module incorrect typings

### ISSUE THREAD

**Issue by 123NeNaD** [KillerCodeMonkey/ngx-quill#1633]
Right now, `syntax` module is of type **boolean**.

While that works, we are required to insert `highlight.js` library in the `index.html` so Quill can work properly. The actual typings for `syntax` should be `boolean` or `object`:
```
syntax?: boolean | object;
```
This is because Quill internally uses object for the `syntax`, where the object will have `highlight` property, which is a function. This can be leveraged in order to use `highlight.js` inside the module, and not globally, which would increase the performance in case of lazy-loaded modules.

**Example:**
```typescript
import hljs from 'highlight.js';
...
modules: {
  syntax: {
    highlight: (text: any) => hljs.highlightAuto(text).value,
  }
}
```

**Comment by KillerCodeMonkey** [comment]
should be fixed in v20.0.1 thx for the pr
