### ISSUE TITLE
Image issue

### ISSUE THREAD

**Issue by golu7679** [KillerCodeMonkey/ngx-quill#1637]
When I remove image button from toolbar config, then I paste an image then it shows in me text editor, show how can I solve this issue?

**Comment by KillerCodeMonkey** [comment]
Just hiding a button in the toolbar changes nothing of supported formats.

You need to set the formats as well.
Remove the image from the allowed formats and it should work as expected.

golu ***@***.***> schrieb am Mo., 12. Dez. 2022, 16:24:

**Comment by golu7679** [comment]
I don't have any idea how can I do this? can you please guide me about this

**Comment by KillerCodeMonkey** [comment]
Check the readme. I think you can pass a formats array to the forRoot
method of the QuillModule.


golu ***@***.***> schrieb am Mo., 12. Dez. 2022, 19:54:
