### ISSUE TITLE
quill loses selected text in IE after color change or font family change

### ISSUE THREAD

**Issue by ShadowQueen** [KillerCodeMonkey/ngx-quill#164]
Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0
"ngx-quill": "2.2.0"

Hello, 

I have noticed one strange behavior in IE browser.  Steps for reproducing the issue:

1. Open the quill editor in IE
2. Type some text, for example - ngx-quill is a very nice library.
3. Now select the words "very nice" in the sentence and try to color this words in say green color.
4.  Somehow quill loses selection and nothing happens.
5. The same thing happens if I try to change font family.

 In Chrom and Mozilla everything is working like a charm. In IE this only works if I choose color or font family first and then type the text.

 Any idea how to fix this issue?

Thank you.

**Comment by KillerCodeMonkey** [comment]
could you check if this is a general quilljs error?
in quilljs.com example editor.
It sounds more like a general quill issue. If so, open this issue there:
https://github.com/quilljs/quill/issues

**Comment by ShadowQueen** [comment]
Of course. It's not a general quilljs error.
 I have tried in IE 11 with https://quilljs.com/playground/#quill-playground
Unfortunately, I can not open your demo-page in IE 11.

**Comment by KillerCodeMonkey** [comment]
strange i did no change anything for that. And unfortunatly i do not have a test device for IE ;). Never tried it with Edge or IE11.

My demo-repo is missing some polyfills - so it is not working in IE11.

Maybe you can investigate the problem and send me a PR

**Comment by ShadowQueen** [comment]
Ok. I will try.
I need to clone the project and investigate the code.
I will get back to you...

**Comment by KillerCodeMonkey** [comment]
please do not say sorry for trying to make things better ;)
