### ISSUE TITLE
 Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments

### ISSUE THREAD

**Issue by Johnsonojo** [KillerCodeMonkey/ngx-quill#1647]
Hi,

I am currently working on an angular project built with version 15.
I installed ngx-quill and added the QuillModule in the app.module.ts imports array, but then when I serve the app, I get this error:

```
Error: node_modules/ngx-quill/lib/quill-view.component.d.ts:38:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

38     static ɵcmp: i0.ɵɵComponentDeclaration<QuillViewComponent, "quill-view", never, { "format": "format"; "theme": "theme"; "modules": "modules"; "debug": "debug"; "formats": "formats"; "sanitize": "sanitize"; "beforeRender": "beforeRender"; "strict": "strict"; "content": "content"; "customModules": "customModules"; "customOptions": "customOptions"; "preserveWhitespace": "preserveWhitespace"; }, { "onEditorCreated": "onEditorCreated"; }, never, never, true, 
never>;
```

Please how can I fix this?

**Comment by KillerCodeMonkey** [comment]
I do not know. Maybe you can create a demo repo or Stackblitz?

You can even check my demo repo + live preview. It is using angular 15 as
well

And check if you installed the correct ngx-quill version for angular 15
(there is a little table in the readme)

Johnson Ojo ***@***.***> schrieb am Mi., 11. Jan. 2023, 12:51:

**Comment by Johnsonojo** [comment]
Hi  @KillerCodeMonkey ,

It works now.

So apparently mix-up was from my end. 

I am working on two angular projects with angular versions 14 and 15 respectively.

So the project I thought was angular 15 was actually 14, hence ngx-quill installed was the wrong version.

Basically I installed ngx-quill version 20 in angular ver 14.

I'm so sorry for the mix-up.

Thanks for the assist.
