### ISSUE TITLE
Material Component Toolbar gets cut off from parent component

### ISSUE THREAD

**Issue by fabioloreggian** [KillerCodeMonkey/ngx-quill#1648]
From the live demo when there is no content the material parent component cuts off the toolbar when it is opened

![image](https://user-images.githubusercontent.com/31480768/212042167-3bf606fd-5860-4964-af4b-e6faea6942cf.png)

**Comment by KillerCodeMonkey** [comment]
please open this issue at the demo repo and not here :), because it is not an issue if the ngx-quill.

And keep in mind the demo is just a hacky example how to use it with material and not for production.

Feel free to send a PR with a fix. 

Thanks!
