### ISSUE TITLE
quill text adds ?

### ISSUE THREAD

**Issue by sumitkumarray** [KillerCodeMonkey/ngx-quill#1650]
In the rich text description type "anthing thing"
Make "anthing thing" bold and red
Add the follwing text"
1
2
3
" (ending with empty newline)
 Select 1 2 3 and make them an ordered list

**Save**

This has hidden corrected once we UTF conversion, That become "?"

**Comment by TomHaenen** [comment]
quill.root.innerHTML will give this:
![image](https://user-images.githubusercontent.com/8086700/213442298-b3ab13d1-b1df-4afa-a6d9-d38af83e3269.png)

**Comment by KillerCodeMonkey** [comment]
hey sorry for the late response. this sounds like quilljs issue. Could you open an issue there?

**Comment by TomHaenen** [comment]
Technically this is valid HTML, we just weren't expecting invisible unicode characters. The question marks is a conversion issue on our end.

The "ql-cursor" span is not necessary when saving the value. I don't know if you consider that a bug, but for us this is not so important and we are no longer actively looking for a fix.

In case it interests you, we also found that this span appears when making a line bold, adding 2 new lines and then saving.

**Comment by KillerCodeMonkey** [comment]
This is more interesting for the quilljs project and not my angular
wrapper, since I try not to fix or intercept native quilljs behaviour.

Tom Haenen ***@***.***> schrieb am Di., 7. Feb. 2023, 15:49:
