### ISSUE TITLE
ngx-quill with formula issue

### ISSUE THREAD

**Issue by benengi** [KillerCodeMonkey/ngx-quill#1654]
I added formula to ngx-quill

 modules = {

toolbar: [      
  [{ header: [1, 2, false] }],
  ['bold', 'italic', 'underline'],
  ['formula'], 
  ['image', 'code-block']
]

when I enter a formula, it displays 2 times in the editor

https://i.stack.imgur.com/SnmwN.png
https://i.stack.imgur.com/E8ezN.png

Here a link of the issue

[stackblitz](https://stackblitz.com/edit/angular-quill-editor?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html)

**Comment by KillerCodeMonkey** [comment]
just create valid html files and follow katex instructions... use up to date versions of external deps...

https://stackblitz.com/edit/angular-quill-editor-xagotw?file=src%2Findex.html,src%2Fapp%2Fapp.module.ts
