### ISSUE TITLE
[readOnly] doesn't seem to work

### ISSUE THREAD

**Issue by TomMettam** [KillerCodeMonkey/ngx-quill#1658]
The "readOnly" attribute doesn't seem to actually make quill-editor readonly.

**Comment by KillerCodeMonkey** [comment]
check the example repo https://killercodemonkey.github.io/ngx-quill-example/ search for "readonly" and toggle it there - it is working

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/no-toolbar/no-toolbar.component.html

if readOnly is set you can not type in, but are allowed to mark the content and copy it.

**Comment by TomMettam** [comment]
Here's the repro 

https://angular-n6teeq.stackblitz.io

**Comment by TomMettam** [comment]
https://stackblitz.com/edit/angular-n6teeq?file=src/main.ts

**Comment by KillerCodeMonkey** [comment]
yeah, but the issue is related that quilljs is throwing hard js errors, because module is not registered, so i guess quilljs is not working as expected after that.
