### ISSUE TITLE
Typing period using SHIFT displays colon

### ISSUE THREAD

**Issue by josouf** [KillerCodeMonkey/ngx-quill#1661]
Hi, I'm facing an issue on Firefox. When I type period using SHIFT + associated key (using an AZERTY keyboard), the editor displays a colon instead.
This happens only for the first period but it does it again after a SPACE. 
On Chrome, it's working perfectly.

![image](https://user-images.githubusercontent.com/107841652/220567694-81ff624b-2197-4f57-a7a8-6966749b3045.png)

**Comment by KillerCodeMonkey** [comment]
This sounds like a quilljs issue. Could you check the quilljs repository
for an issue?

Julien Osouf ***@***.***> schrieb am Mi., 22. Feb. 2023,
09:43:
