### ISSUE TITLE
Cannot use inline style with Angular Universal

### ISSUE THREAD

**Issue by Ben555555** [KillerCodeMonkey/ngx-quill#1662]
Using this with Angular Universal:

```
import * as Quill from "quill";
var ColorClass = Quill.import('attributors/class/color');
    var SizeStyle = Quill.import('attributors/style/size');
    Quill.register(ColorClass, true);
    Quill.register(SizeStyle, true);
```

produces the following exception:

Error: Uncaught (in promise): ReferenceError: document is not defined
ReferenceError: document is not defined
    at call (webpack:///node_modules/quill/dist/quill.js:7661:12)

It would be nice to have a way to set the inline style also with an input parameter. Also it doesn't seem to work for font-size even on browser side since, the html tags style attribute is not adapting.

**Comment by KillerCodeMonkey** [comment]
Any time you import quilljs this way and not async with a check if you are
on browser env, will break your app.

Quilljs directly access document which is only defined in browser env.

So check the ngx-quill source code how to safely import quill.

Ben555555 ***@***.***> schrieb am Fr., 24. Feb. 2023, 15:07:

**Comment by KillerCodeMonkey** [comment]
You can try if you can pass those imports as customOptions input of
ngx-quills editor componen.

Bengt Weiße ***@***.***> schrieb am Fr., 24. Feb. 2023, 15:09:
