### ISSUE TITLE
google doc pasting compatibility

### ISSUE THREAD

**Issue by Eraldo** [KillerCodeMonkey/ngx-quill#1665]
### Current Behavior

When copied from [ngx-quill](https://killercodemonkey.github.io/ngx-quill-example/) and then pasted:

---

<img width="195" alt="image" src="https://user-images.githubusercontent.com/73378/222957858-99133317-c250-4b51-9ba2-093edb5d8bdb.png">

---

When copied from [quilljs](https://quilljs.com/) and then pasted:

---

<img width="200" alt="image" src="https://user-images.githubusercontent.com/73378/222957877-fe166d9d-0e3d-4bf6-88f8-7c96caf474e0.png">

---

### Expected Behavior

I would like to see list items in google docs after copying lists from the editor.

---

<img width="210" alt="image" src="https://user-images.githubusercontent.com/73378/222958099-33905d4a-b5e9-4ac7-a3dc-54e25c14fd6c.png">

---

#### Side note

Neither one keeps the nested list item when pasting.
This seems to be a general quill/gdoc compatibility issue.
Ideally I would be able to get that too. 😊

### References

[Actual demo of pasted html](https://docs.google.com/document/d/1wVSdYB0hN-aarUdkBmvOIDrmNAheV1Bq_BrARbObwiQ/edit#).

**Comment by KillerCodeMonkey** [comment]
But if it is not supported by quilljs then ngx-quills will not support it.


Eraldo Energy ***@***.***> schrieb am So., 5. März 2023,
12:37:

**Comment by Eraldo** [comment]
Maybe I was not clear, sorry. 🙈 
On the vanilla **quilljs** website the paste **does** show as list items in google doc.
Using **ngx-quill** it **does not** anymore.

I understand that nested lists will not be supported, if that is what you meant. 😊 
I made that note more as a nice to have if you have any ideas of how I might easily get that as well.
Feel free to ignore the side comment. 😉 

Thanks for the prompt reply. Thanks for keeping up the great work. 🙏

**Comment by KillerCodeMonkey** [comment]
Ahhh did you try to deactivate sanitizing

Eraldo Energy ***@***.***> schrieb am So., 5. März 2023,
14:07:

**Comment by KillerCodeMonkey** [comment]
@Eraldo i rechecked it. ngx-quill is sets the property "strict" to true per default. this only allows known formats and so on.

You can set it to "false" and it is working as expected :)

**Comment by Eraldo** [comment]
Thank you @KillerCodeMonkey for investigating and finding the reason. 😃 

Actually I do want the sanitizing step. I am a bit confused why list items would not be a known format and how I can make sure it is. 🤔

**Comment by KillerCodeMonkey** [comment]
@Eraldo read the last comment :D `strict` is the input you need to set to false. sanitize can stay activated.

**Comment by Eraldo** [comment]
I set strict to false and I still don't get list bullets when pasting. :/
I don't know what I'm doing wrong. 🤷‍♂️

**Comment by KillerCodeMonkey** [comment]
sorry for the confusion i rechecked it again... i had some more local changes...

you do not need to set those inputs.

But in my example i am overriding the default tag quilljs uses with:

```JS
const parchment = Quill.import('parchment')
const block = parchment.query('block')
block.tagName = 'DIV'
// or class NewBlock extends Block {} NewBlock.tagName = 'DIV'
Quill.register(block /* or NewBlock */, true)
```

if i am removing this - copy and paste works.
Maybe you are using divs instead of p-tags as well?

**Comment by KillerCodeMonkey** [comment]
![ngx-quill-gdocs](https://user-images.githubusercontent.com/2264672/222985992-5a05bd14-4d36-4fd9-a85a-edd6a515a963.gif)

**Comment by Eraldo** [comment]
Yes, good prediction. I am using `div`s as well. 👏
Thank you for helping me figure out what is going on. Now I understand the challenge. 🙏 

So google does not like those it seems. I understand. Hmmm. 🤔 
I remember I changed to divs because otherwise I had things nested inside `<p>` elements which seems to be discouraged in terms of html tags standard.
I wonder if there is a way to stay conform with html standards and get google to be compatible. 😅

**Comment by KillerCodeMonkey** [comment]
i tried to understand what is going on inside of quilljs.. but it would take more time. i do not have at the moment.

hacky idea -> if you only need google docs support for your internal usage -> create a special editor for it -> paste it there and then copy it again. maybe it works.

**Comment by Eraldo** [comment]
I confirm that reverting the default block back to paragraphs does solve the "Google => Quill" pasting.
The reverse still does not work (meaning there are no list tags when pasting from Quill to Google docs. I will think about this. 🤔 

Thanks for your hack idea. I think as a workaround I will create an editor button that aims to transform the editor html to hopefully conform with what google expects and then copies that to the clipboard.
Essentially a "Copy for Google" button.

Regarding the default block, I have not yet decided what is more important to me. I will think about it further.
Thanks for your support and I totally understand your limitations and thank you for the time you already spent on this.
Wishing you a good start of the next week. 🙏
