### ISSUE TITLE
Problem with bubble theme

### ISSUE THREAD

**Issue by nicolacardi** [KillerCodeMonkey/ngx-quill#1668]
I have installed ngx-quill, incuding the snow and bubble css like

```
@import '~quill/dist/quill.bubble.css';
@import '~quill/dist/quill.snow.css';
```

Now if I simply
 `<quill-editor></quill-editor>`
it gets easily the snow theme and works perfectly
but when I
 `<quill-editor theme="bubble"></quill-editor>`
it doesn't work at all, this is how it shows:
![Schermata 2023-03-08 alle 18 22 50](https://user-images.githubusercontent.com/16313205/223784859-a3ca901e-b60d-4c70-971e-1d43595acb36.png)
it's as if the bubble css was not working at all.
Am I doing anything wrong? 
I had a look at the example page, but in the "bubble theme" section I can't see the theme in action...
I would like to understand if I am doing anything wrong or how I should import the bubble theme but I see no guide.

My setup
Angular 15.2.0
    "ngx-quill": "^20.0.1",
    "quill": "^1.3.7",

Thanks

**Comment by hojjat-afsharan** [comment]
Maybe your component is inside ShadowDom view encapsulation mode. If yes, just change it to Emulated mode.

**Comment by nicolacardi** [comment]
After thousands of attempts I finally found that the problem was due to the "display: inline-block" css property which is automatically set on the <quill-editor> tag. This blocked the rendering. 
It was in the end sufficient to force it like <quill-editor style="display: block"...>
I hope it helps anybody else who should encounter the same problem.
