### ISSUE TITLE
Bubble theme have issues with scrolling

### ISSUE THREAD

**Issue by jmbaliero** [KillerCodeMonkey/ngx-quill#1669]
When you select some text and the bubble toolbar is displayed, if you scroll on the text editor, the bubble toolbar doesn't close, so you can move it outside the text editor container

![image](https://user-images.githubusercontent.com/71397032/227733381-f99cf490-a7af-434d-90c8-1df3589eda9e.png)

Any ideas how to resolve this? 

here is an example in stackblitz to replicate the issue

https://stackblitz.com/edit/angular-markdown-editor-jira-f8ovvg

**Comment by KillerCodeMonkey** [comment]
it is just a general styling thing. and is more a quilljs thing.
https://quilljs.com/

just check how they did it on the homepage (first slide of the slider is the bubble theme). wrap the editor and give it the style attribute `overflow: hidden`.

**Comment by jmbaliero** [comment]
Thank you for the quick response! That it, that fix the issue
