### ISSUE TITLE
Bubble theme having issues with the toolbar when the options displayed overlaps another editor

### ISSUE THREAD

**Issue by jmbaliero** [KillerCodeMonkey/ngx-quill#1671]
When you have two editors with the bubble theme, and in the first editor you open for example the color picker or the headers list, these options are not clickable if they fall in the second text editor

![image](https://user-images.githubusercontent.com/71397032/227742474-85abbeaa-5311-4192-a8f2-a60bd73ef6bd.png)

![image](https://user-images.githubusercontent.com/71397032/227742505-25594b40-58d2-41d0-9dc1-810c21988424.png)

Here a stackblitz example to replicate the issue 

https://stackblitz.com/edit/angular-markdown-editor-jira-f8ovvg

Any ideas?

**Comment by KillerCodeMonkey** [comment]
puh depends you can try to play around with z-index of the toolbar, but in general it is a quilljs thing.
