### ISSUE TITLE
How to put focus at the end of the editor?

### ISSUE THREAD

**Issue by burjua** [KillerCodeMonkey/ngx-quill#1673]
I have seen other questions about setting focus, and it works for me. However it sets the focus in the beginning of the content if there is content already. This is not user-friendly though, I would like the focus in the end, or on a new line even, so I can start typing straight away?

**Comment by KillerCodeMonkey** [comment]
maybe you can work around with something like that:
https://github.com/quilljs/quill/issues/2562#issuecomment-479951050

get the content length and set the cursor / selection to the end through quill api
