### ISSUE TITLE
Quill scrolls to the top every time when you paste a text

### ISSUE THREAD

**Issue by stas-kh** [KillerCodeMonkey/ngx-quill#1678]
**Problem**:
The editor scrolls to the top every time when I paste a text to the bottom of the editor. I cannot reproduce this issue on the quilljs playground.

**Steps to reproduce**:
This issue is reproduced on the demo page here - https://killercodemonkey.github.io/ngx-quill-example

**How to reproduce**:
1. Choose any editor that does not have a fixed height option (e.g. in `Activate rtl-direction` section)
2. Start pasting some long paragraphs
3. Paste until you fill the whole available screen height (I suppose something like 100vh is used to calculate it)
4. After that every time you paste the content to the bottom,  the editor will forcibly scroll you to the top (see the attached video)

**Video**:

https://user-images.githubusercontent.com/10476834/231481109-3290429f-9673-42bc-a22e-f615ede761d2.mov

**Comment by KillerCodeMonkey** [comment]
sadly this is a native quilljs problem. even on https://quilljs.com/ you can remove the height: 100% and overflow: hidden from `div.editor.ql-container.ql-snow`

**Comment by stas-kh** [comment]
Thank you @KillerCodeMonkey.

For the rest who will be looking for a solution, I came up with wrapping the quill-editor into a parent component that has fixed height and `overflow: hidden`. Now the scroll is a part of quill-editor itself, instead of using global viewport scrollbar.
