### ISSUE TITLE
Mat-Quill as standalone component

### ISSUE THREAD

**Issue by alex737876** [KillerCodeMonkey/ngx-quill#1679]
Hi @arturovt , highly appreciate your work and investment in transitioning to standalone components!

Could you also include the material form wrapper?

**Comment by arturovt** [comment]
Can you elaborate more?

**Comment by arturovt** [comment]
I think this is more a question to @KillerCodeMonkey and if he considers this might be a part of the core library. We could've made it as a subpackage, e.g. `ngx-quill/mat-*********...`.

**Comment by KillerCodeMonkey** [comment]
well since i am not using angular material i am not quite familiar with it. and as far as i know (considering the issues you have with quill + material ui, e.g. in tabs, dialogs) it would be hard to maintain.
