### ISSUE TITLE
ERROR in Metadata version mismatch for module found version 4 expected 3

### ISSUE THREAD

**Issue by sanjeevkumarthakur** [KillerCodeMonkey/ngx-quill#168]
Hi, I am facing below issue when i try to run my angular 4 application. It would be great if someone can assist what going wrong in this case.
-------------------------------------------------------------------------------------
ERROR in Metadata version mismatch for module C:/Projects/xxx/node_modules/mobx-angular/dist/mobx-angular.d.ts, found version 4, expected 3, resolving symbol TreeModule in C:/Projects/xxx/ui/examples/xxx/node_modules/angular-tree-component/dist/angular-tree-component.d.ts, resolving symbol TreeModule in C:/Projects/xxx/node_modules/angular-tree-component/dist/angular-tree-component.d.ts
-----------------------------------------------------------------------------------------------
Package.json file is below :- 

{
  "name": "@xxx/ui",
  "version": "1.0.0",
  "description": "xxxx",
  "main": "xxxx",
  "module": "xxx",
  "types": "xxx.d.ts",
  "scripts": {
    "lint": "tslint \"lib/**/*.ts\"",
    "build:aot": "gulp inline-templates && npm run aot",
    "launch": "gulp build:watch",
    "aot": "ngc -p ./tsconfig-ngc.json",
    "watch": "gulp watch",
    "copy": "node tools/copy-package.js && node tools/cleanup.js",
    "bundle": "tsc -p ./tsconfig-ngc.json && npm run aot && webpack",
    "prebundle": "rimraf dist && gulp inline-templates",
    "build": "npm run bundle && npm run copy",
    "doc": "typedoc --module commonjs --out doc src/api/public.api.ts",
    "docs": "node_modules/.bin/compodoc -p tsconfig.json -d docs",
    "serve-docs": "node_modules/.bin/compodoc -s -d docs",
    "angular-app": "cd examples && cd manageportfolio-angular && npm run start",
    "build:run": "npm run build && npm run angular-app",
    "test": "karma start ./config/karma.conf",
    "coverage": "karma start ./config/karma.conf --coverage true",
    "precoverage": "rimraf coverage/",
    "postcoverage": "npm run cover",
    "cover": "istanbul report --include=**/coverage/coverage.json text text-summary",
    "postinstall": "npm run build && cd examples && cd manageportfolio-angular && npm install"
  },
  "keywords": [
    "mmb",
    "ui",
    "manage",
    "portfolio"
  ],
  "author": "XXX",
  "license": "MIT",
  "dependencies": {
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.6"
  },
  "peerdependencies": {
    "@angular/core": ">=4.2.4",
    "moment": "^2.20.1",
    "@angular/forms": ">=4.2.4",
    "angular-tree-component": ">=6.1.0",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14",
    "bootstrap": "^3.3.7"
  },
  "devDependencies": {
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@types/jasmine": "^2.8.2",
    "@types/webpack": "^3.0.13",
    "@types/webpack-env": "^1.13.1",
    "@types/detect-browser": "^1.6.0",
    "angular-tree-component": "^6.1.0",
    "angular2-template-loader": "^0.6.2",
    "angular2-virtual-scroll": "^0.3.2",
    "awesome-typescript-loader": "^3.2.3",
    "copy-webpack-plugin": "^4.3.1",
    "core-js": "^2.4.1",
    "detect-browser": "^1.7.0",
    "moment": "^2.20.1",
    "css-loader": "^0.28.8",
    "del": "^3.0.0",
    "file-loader": "^1.1.6",
    "gulp": "^3.9.1",
    "gulp-inline-ng2-template": "^4.0.0",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.30.1",
    "istanbul": "^0.4.5",
    "istanbul-instrumenter-loader": "^3.0.0",
    "jasmine-core": "^2.8.0",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.1",
    "karma-remap-coverage": "^0.1.4",
    "karma-remap-istanbul": "^0.6.0",
    "karma-source-map-support": "^1.2.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-sourcemap-writer": "^0.1.2",
    "karma-spec-reporter": "0.0.32",
    "karma-typescript": "^3.0.9",
    "karma-typescript-angular2-transform": "^1.0.2",
    "karma-webpack": "^2.0.9",
    "loadash": "^1.0.0",
    "mkdirp": "^0.5.1",
    "ncp": "^2.0.0",
    "node-sass": "^4.5.3",
    "raw-loader": "^0.5.1",
    "reflect-metadata": "^0.1.8",
    "remap-istanbul": "^0.9.5",
    "rxjs": "^5.4.2",
    "sass-loader": "^6.0.6",
    "shx": "^0.2.2",
    "style-loader": "^0.19.1",
    "ts-lint": "^4.5.1",
    "ts-loader": "^3.2.0",
    "typedoc": "^0.8.0",
    "typescript": "^2.3.3",
    "typings": "^2.1.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.6.0",
    "webpack-merge": "^4.1.0",
    "zone.js": "^0.8.14"
  }
}

/Regards
S

**Comment by KillerCodeMonkey** [comment]
And why are you posting this here????

In the error message you get the info that the error occurs in 
mobx-angular

angular-tree-component

So please ask this question in there repo ;)

**Comment by sanjeevkumarthakur** [comment]
sure..Thanks ..be polite !
