### ISSUE TITLE
Bullet point font size

### ISSUE THREAD

**Issue by mycklemore** [KillerCodeMonkey/ngx-quill#1682]
Issue when applying a larger font size('large' or 'huge') the bullet point does not take on the same font size as the text resulting in a vertically off centered and small bullet point.

<img width="543" alt="Screenshot 2023-04-17 at 11 15 34 AM" src="https://user-images.githubusercontent.com/16581830/232560973-281bc40a-8c98-4b38-b516-3c4d89a0708c.png">

**Comment by KillerCodeMonkey** [comment]
I think this is a known quilljs problem
https://github.com/quilljs/quill/issues/3721

Mike ***@***.***> schrieb am Mo., 17. Apr. 2023, 19:18:
