### ISSUE TITLE
How can I stop links without protocols

### ISSUE THREAD

**Issue by Et3rnal** [KillerCodeMonkey/ngx-quill#1684]
Is there a simple way to stop or validate links?

As soon as I try import Quill and reference it I keep getting undefined error: `quill_1.default is undefined`

```
import Quill from 'quill';
var Link = Quill.import('formats/link');
```

I tried to use the `onContentChanged()` event to validate but I'm not able to stop the user

**Comment by KillerCodeMonkey** [comment]
in my example repo i am importing things like that and it is working: 

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/app.component.ts#L5

you can try to deactivate the link format and implement you own.

and in general i would store the editor content as object/json format. there you get the content and format of the link when the editor content changes, and it is very easy change it
