### ISSUE TITLE
Not compatible with angular 16

### ISSUE THREAD

**Issue by goodcare** [KillerCodeMonkey/ngx-quill#1686]
i cannot use quill with angular 16.

**Comment by KillerCodeMonkey** [comment]
More information would be nice.

Samy Waltersam ***@***.***> schrieb am So., 7. Mai 2023,
20:09:

**Comment by KillerCodeMonkey** [comment]
i updated my demo repo just now and everything works with angular 16 + ngx-quill 22

**Comment by KillerCodeMonkey** [comment]
https://killercodemonkey.github.io/ngx-quill-example/
https://github.com/KillerCodeMonkey/ngx-quill-example/
