### ISSUE TITLE
Documentation is missleading

### ISSUE THREAD

**Issue by ghaschel** [KillerCodeMonkey/ngx-quill#1687]
Currently the documentation states that for Angular v15 the ngx-quill version should be: `>=20.0.0 and <=22.0.0` and that is not correct. Since ngx-quill 22.0.0 is the one for angular 16

It should be either `>=20.0.0 and < 22.0.0` or `>=20.0.0 and <=21.0.0`

I was facing a lot of issues compiling because I did install 22.0.0, only to later find out that 22 is not for v15

![image](https://user-images.githubusercontent.com/5878866/236870195-8543c43e-8608-45bc-9bea-042089132a46.png)

**Comment by KillerCodeMonkey** [comment]
changed it in master branch
