### ISSUE TITLE
Append custom button in the toolbar

### ISSUE THREAD

**Issue by badcoder28** [KillerCodeMonkey/ngx-quill#169]
Currently im using the basic editor approach, i have a toolbar module defined in `editor_modules`

```
this.editor_modules = {
      toolbar: [
        ['bold', 'italic', 'underline', 'strike'],      
        [{ 'header': 1 }, { 'header': 2 }], 
       ...... omitted
      ]
};

<quill-editor [modules]="editor_modules"></quill-editor>
```

I define some custom control that will enable the toolbar to insert a **hr** tag in the editor.
I follow the instruction found [here](https://quilljs.com/guides/cloning-medium-with-parchment/#dividers).

```
import * as QuillNamespace from 'quill';
export const ngQuill: any = QuillNamespace;

ngOnInit() {
   const BlockEmbed = Quill.import('blots/block/embed');
   BlockEmbed.blotName = 'divider';
   BlockEmbed.tagName = 'hr';
   Quill.register(BlockEmbed);
}
```

And now i'm facing a solid tall brickwall of how to append this custom control to the toolbar? And whenever I do this:

```
<quill-editor [modules]="editor_modules">
  <div quill-editor-toolbar>
     <span class="ql-formats">
        <div id="divider"></div>
     </span>
  </div>
</quill-editor>
```

The toolbar is empty and pure white blank and i need to append the custom control.

 Hope someone can shed a light and break this solid brickwall im facing now and save me from a lot of hair pulling spree. 

Lot of thanks!

**Comment by KillerCodeMonkey** [comment]
First You Do Not need to wait for ngoninit
Everything You to with quilljs is angular independent. Only my component is
the angular wrapper.

And how i understand quilljs You need to Register Your New Format and and
the Name to the toolbar Object.

badcoder28 <notifications@github.com> schrieb am Di., 1. Mai 2018, 10:30:

**Comment by badcoder28** [comment]
@KillerCodeMonkey  thank you for your response, 

i simply do it on ngOnInit() method because first, i dont have a clue where is the right place to put the setting. Secondly,  i only had the editor the a particular component.

And as you can see, i was able to register a custom blockembed with a given name **divider** . and i supposed you mean toolbar object as the module settings? If so i'll be testing it.

**Comment by badcoder28** [comment]
I was able to add by appending the divider in an array.

```
this.editor_modules = {
      toolbar: [
           ['bold', 'italic', 'underline', 'strike'],      
           [{ 'header': 1 }, { 'header': 2 }], 
           ...... omitted
           ['divider'],        // Added custom toolbar
      ]
};
```

Thanks for pointing out, however, their is additional behavior with **prompt inputbox** if you can enter a value no **hr** is display otherwise its working, and the button is blank white without any label.

**Comment by KillerCodeMonkey** [comment]
Yeah but There i can Not help You. Never did something like that with
quilljs.

It World be better to Ask this in the quilljs Repo.

I only Know, that the quill default Formats have a style component (css
Classes) to Set things like ql-format-xxx.

Sorry Dude. But feel free to Post Your solution here, in You have one.

badcoder28 <notifications@github.com> schrieb am Di., 1. Mai 2018, 14:55:

**Comment by badcoder28** [comment]
Now im going in the right path just one more question, how can i access the 
```
let quill = new Quill('#editor');
```

I believe the Quill has instantiated already. How can i access the `quill` instance in your structure?

**Comment by KillerCodeMonkey** [comment]
Listen to the oneditorcreated Output.  Check the readme ;)

badcoder28 <notifications@github.com> schrieb am Di., 1. Mai 2018, 15:33:

**Comment by badcoder28** [comment]
Got my solution working for this problem

```
ngOnInit() {
   // Define the hr tag as divider. It will be used on hr option click event.
  // Note this is different from the `['hr']` in the modules
   const BlockEmbed = Quill.import('blots/block/embed');
   class DividerBlot extends BlockEmbed { }
   DividerBlot.blotName = 'divider';
   DividerBlot.tagName = 'hr';
   Quill.register(DividerBlot);

   // Define the modules config.
   this.modules = {
      toolbar: [
           ... omitted 
           ['hr'], // Added custom control with named hr
       ];
   };
}
```

Add listener to custom toolbar control **hr** 

```
ngAfterViewInit() {
   const dividerToolbarButton = document.querySelector('.ql-hr');
   dividerToolbarButton.classList.add('mdi');
   dividerToolbarButton.classList.add('mdi-minus');
   dividerToolbarButton.classList.add('mdi-18px');
   dividerToolbarButton.addEventListener('click', (e) => {
      e.preventDefault();

      const range = this.editor_instance.getSelection(true);
      
      // The editor_instance was created during onEditorCreated event.
      this.editor_instance.insertText(range.index, '\n', ngQuill.sources.USER);
      this.editor_instance.insertEmbed(range.index + 1, 'divider', true, ngQuill.sources.USER);
      this.editor_instance.setSelection(range.index + 2, ngQuill.sources.SILENT);
   });
}
```

**Comment by KillerCodeMonkey** [comment]
Some hint. Move Your blot registration Outside of Your Class, IT is
registered on the global quill Object anyways.

Than You Can move modules Definition Outside of the constructor. So maybe
Your Code gets a littlebit cleaner

And instead of Document.querySelector store the elementref of the
quillcomponent on a variabel `<quill-editor #editor... `
And Grab it with ViewChild decorator in angular. After that You Can Use the
elementref.nativeElement.querySelect... To Get the Button.

So it is a more modular and encapsulated Selection and Not a global thing
on the whole Page/Document.  ;)

badcoder28 <notifications@github.com> schrieb am Di., 1. Mai 2018, 15:53:

**Comment by badcoder28** [comment]
Thanks a lot bro.

I refactor all my code and its still great. I was confused about the ViewChild accessing the querySelector though.

instead of

```
this.quill_viewchild.nativeElement.querySelector('ql-hr);
```
i use

```
this.quill_viewchild.elementRef.nativeElement.querySelector('ql-hr);
```

**Comment by jggprudencio** [comment]
Hi @KillerCodeMonkey, I've tried to do what you said:
`<quill-editor #editor... `
`const dividerToolbarButton = this.editor.elementRef.nativeElement.querySelector('.ql-hr');`

But I've got this error:
`Property 'elementRef' is private and only accessible within class 'QuillEditorComponent'.`

What is the best way to get the element using querySelector('.ql-hr')?

**Comment by KochuraniT** [comment]
`jghjhgjhhjhjhjhjhhjhjhjhjhjhgj<script></script>`
