### ISSUE TITLE
Quill Editor toolbar does not pass lighthouse accesibility

### ISSUE THREAD

**Issue by CruddyShad0w** [KillerCodeMonkey/ngx-quill#1690]
When running a light house report against the `quill-editor` there is a finding that reports the button to select the text sizing does not pass accessibility.
I am currently utilizing ngx-quill 19.0.1 with angulr 14.

The findings are attached in the image below: 
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/38229188/a3a466c6-eb21-451f-a4c5-f9ff0fd18db1)

**Comment by KillerCodeMonkey** [comment]
you can build up your custom toolbar if you like. but in general this default toolbar is coming from quilljs, so please open the issue at the quilljs repo Thanks!
