### ISSUE TITLE
Editing link does not work when mat-quill is located in mat-form-field

### ISSUE THREAD

**Issue by arko0x** [KillerCodeMonkey/ngx-quill#1693]
Hello,
while using ngx-quill-example repository I noticed, that after creating a link it can't be edited for all Material Quill examples, toolbar just disappears instead.

**Steps to reproduce**

1. Use mat-quill component inside mat-form-field.
2. Mark text as link
3. Try to edit link

**Comment by KillerCodeMonkey** [comment]
this should not be opened here. please open it at the example repo.
