### ISSUE TITLE
Link tooltip popup out of editor rect bounds

### ISSUE THREAD

**Issue by strigefleur** [KillerCodeMonkey/ngx-quill#1696]
Link popup position seems to be calculated to center itself to the characters you pressed "add link" button on. So when that character is close to the editor border (for example the very first one in line) the popup gets something like `left: -100px ` that effectively puts it out of expected rectangle.

I'd expect it to bound to it's editor rectangle (min left == 0 px, max right == editor width or something) - otherwise it's easy to get popup cut by screen edges.

**Comment by KillerCodeMonkey** [comment]
in general this is a quilljs issue.

you can set the editor bounds element https://quilljs.com/docs/configuration/#bounds. and you can configure it through ngx-quill config. Maybe this helps.

Greets
