### ISSUE TITLE
'must provide pattern' error when building angular project with quill

### ISSUE THREAD

**Issue by koshdim** [KillerCodeMonkey/ngx-quill#1699]
Hello

I'm trying to use the package in angular 12 application. I know it is not supported, but maybe you would be so kind to help me.
So, I installed 

```

"@types/quill": "1.3.10",
    "ngx-quill": "14.3.0",
"quill": "^1.3.7",
```

but when I build I get this error:
```
[20:19:32] 'styles' errored after 2.42 s
[20:19:32] Error: must provide pattern
    at new GlobSync (C:\...\node_modules\glob\sync.js:28:11)
    at Function.globSync [as sync] (C:\...\node_modules\glob\sync.js:23:10)
    at C:\...\node_modules\wiredep\lib\detect-dependencies.js:114:14
    at Array.reduce (<anonymous>)
    at findMainFiles (C:\...\node_modules\wiredep\lib\detect-dependencies.js:112:29)
    at C:\...\node_modules\wiredep\lib\detect-dependencies.js:170:17
    at C:\...\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (C:\...\node_modules\lodash\lodash.js:3032:24)
    at C:\...\node_modules\lodash\lodash.js:4936:18
    at Function.forEach (C:\...\node_modules\lodash\lodash.js:9410:14)
```
after some investigation I noticed that this is because it tries to find something meaningful in "main" or "scripts" in package's package.json, but it is empty

```
...
    "main": "",
    "repository": {
        "type": "git",
        "url": "https://github.com/DefinitelyTyped/DefinitelyTyped.git"
    },
    "scripts": {},
    "dependencies": {
        "parchment": "^1.1.2"
    },
    "typesPublisherContentHash": "2483630ee29fdf4f03b09b41c35faff526b532bade15446ac2ce2a4a9ce5e9a3",
    "typeScriptVersion": "2.0"
```
do you have any idea how to make it work?

**Comment by koshdim** [comment]
I tried to use quill directly, but when I run the app I get "Uncaught ReferenceError: require is not defined". I tried to add "./node_modules/quill/dist/quill.js" to scripts, but it didn't help. any advice?

**Comment by KillerCodeMonkey** [comment]
sorry for the waiting... i have lots of things to do.

in you case i would check the ngx-quill-example repo history for a commit where i upgraded to angular 14.x

Check this one out and try to build/run it.

**Comment by KillerCodeMonkey** [comment]
for you second post quilljs is released as commonjs script and uses require to load external/other js files/modules.

It looks like something with your build process is not working.
Do you use some custom modifications in angular.json / tsconfig?

**Comment by koshdim** [comment]
thank you very much for the response! 
I'm stuck with Angular 12 unfortunately, any recommendations how to use it there?
I noticed back in the past for 12 Angular you used same packages I do...

```
{
  "name": "ngx-quill-example",
  "version": "14.3.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:deploy": "ng build --configuration production --base-href ngx-quill-example && gh-pages -d ./dist"
  },
  "license": "MIT",
  "private": false,
  "dependencies": {
    "@angular/animations": "^12.2.12",
    "@angular/cdk": "^12.2.12",
    "@angular/common": "^12.2.12",
    "@angular/compiler": "^12.2.12",
    "@angular/core": "^12.2.12",
    "@angular/forms": "^12.2.12",
    "@angular/localize": "^12.2.12",
    "@angular/material": "^12.2.12",
    "@angular/platform-browser": "^12.2.12",
    "@angular/platform-browser-dynamic": "^12.2.12",
    "@angular/router": "^12.2.12",
    "katex": "^0.13.20",
    "ngx-quill": "^14.3.0",
    "quill": "^1.3.7",
    "quill-emoji": "^0.2.0",
    "quill-image-resize": "^3.0.9",
    "quill-image-resize-module": "^3.0.0",
    "quill-mention": "^2.2.7",
    "rxjs": "~6.5.5",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.2.12",
    "@angular/cli": "^12.2.12",
    "@angular/compiler-cli": "^12.2.12",
    "@angular/language-service": "^12.2.12",
    "@types/node": "*",
    "@types/quill": "^1.3.10",
    "gh-pages": "^3.2.3",
    "terser": "^5.9.0",
    "ts-node": "^10.4.0",
    "tslint": "~6.1.3",
    "tslint-eslint-rules": "^5.4.0",
    "typescript": "~4.2.4"
  }
}

```

**Comment by KillerCodeMonkey** [comment]
i do not think that i can help you with that. only a package.json and that small error info can mean anything and can come from any package.

in you case i would start with my demo repo or a clean angular cli project created with v12.

may you have a custom build process with gulp. its the only place where i found some similar issues:

https://stackoverflow.com/questions/33083374/gulp-plugin-gulp-ruby-sass-not-compiling

So i will close this issue now. please ask at stackoverflow if you are not able to solve your problem on your own.
