### ISSUE TITLE
error on compiling with angular-cli (1.0.0-rc.0)

### ISSUE THREAD

**Issue by maku** [KillerCodeMonkey/ngx-quill#17]
When trying to use ngx-quill with angular-cli (1.0.0-rc.0) and angular (4.0.0-rc.2) I get an error on compiling regarding quill.module.ts

`
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function
`

**Comment by KillerCodeMonkey** [comment]
seems like it is an issue with aot. this needs a metadata-file. if you have further information. let me know.

**Comment by KillerCodeMonkey** [comment]
Again: 

tested with:
```
@angular/cli: 1.0.0-rc.1
node: 7.4.0
os: darwin x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.9
```

no problems --> works like charm.

**Comment by maku** [comment]
When you generate the cli project for ng4 it does not work (and ng4 is not far away)

.e.g. 

```
ng new ngx-quill-test --style=scss --ng4 true
```

**Comment by KillerCodeMonkey** [comment]
yeah i know... i tested it with v4. But i support this repo all on my own and in my free time. 

And before supporting a rc, i will wait until it is final

**Comment by maku** [comment]
Yeah, I see, thank you for your effort.

BTW, the funny thing is that your source works without problems with ng4. Only the distributed lib does not work with ng4...

**Comment by KillerCodeMonkey** [comment]
what do you mean with distributed lib?

**Comment by maku** [comment]
The code which is used when I install the lib via npm (vs. only copying the source in the project)

**Comment by KillerCodeMonkey** [comment]
could you try the following?:

replace in the package.json of ngx-quill in your node_modules the angular version with: `^2.4.1 || 4.0.0-rc.2`

**Comment by maku** [comment]
what I meant was: it works when you copy your sourcefiles directly in a ng4 project....

**Comment by KillerCodeMonkey** [comment]
i know, but i asked you if you may test it in your project, if you hacky set the angular versions in ngx-quill in the node_modules ;).

If you do not want to do it.. no problem

**Comment by maku** [comment]
O.k. I did this. But it has no effect (as expected).
