### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by tokaika** [KillerCodeMonkey/ngx-quill#170]
i  use  angular 5.2.10  and  i install  ngx -quill 
![image](https://user-images.githubusercontent.com/14201898/39572336-5f246546-4f01-11e8-81de-84a676375627.png)
and  my editor  is  show   
![image](https://user-images.githubusercontent.com/14201898/39572395-948a2252-4f01-11e8-8cce-c785a5a11118.png)

but  theare  hava some  error ..   Can  you  take  a  look    ...thanks

![image](https://user-images.githubusercontent.com/14201898/39572473-d8ba866a-4f01-11e8-83b1-6f99f1ddb9d4.png)
![image](https://user-images.githubusercontent.com/14201898/39572534-0c841aba-4f02-11e8-9207-b3694755d2d6.png)

![image](https://user-images.githubusercontent.com/14201898/39572682-bb149fb4-4f02-11e8-9d31-2c2a5c0b590e.png)
![image](https://user-images.githubusercontent.com/14201898/39572713-d973baf8-4f02-11e8-85fb-417ab3b5778c.png)
 is  my  jquery problem ?

**Comment by tokaika** [comment]
![image](https://user-images.githubusercontent.com/14201898/39572814-46d20294-4f03-11e8-8714-f9c47cf07779.png)
  and  this   problem photo

**Comment by KillerCodeMonkey** [comment]
Seems like a Problem with Your build process... Never had this Problem with
Systemjs, webpack or ngcli

tokaika <notifications@github.com> schrieb am Do., 3. Mai 2018, 12:53:

**Comment by KillerCodeMonkey** [comment]
Seems like You are using angular universal. There are some Closed issues
here to Get IT Working. It does Not work out of the Box, because quilljs
needs the Document

Bengt Weiße <bengtler@googlemail.com> schrieb am Do., 3. Mai 2018, 12:59:

**Comment by tokaika** [comment]
ok。。。thank  you。。。

**Comment by KillerCodeMonkey** [comment]
@tokaika any updates? could you fix it?

**Comment by tokaika** [comment]
![image](https://user-images.githubusercontent.com/14201898/39645437-dfc1cc66-500a-11e8-96f7-596d82283d7b.png)
sorry reply  you  later。。I don't want to use webpack in the Angula environment. I didn't configure it. Anyway, that mistake does not affect  that use of this editor. I didn't deal with this mistake on  my own  website。😄

**Comment by fergalmoran** [comment]
I am getting the same problem with angular 6 and I'm not using universal.

**Comment by KillerCodeMonkey** [comment]
Than You should Check Your buildprocess

Check my Demo Repo. It is also Working with angular cli

Fergal Moran <notifications@github.com> schrieb am Sa., 5. Mai 2018, 20:31:

**Comment by fergalmoran** [comment]
Yeah - I just figured the issue. I had added  "../node_modules/ngx-quill/bundles/ngx-quill.umd.js" to the scripts section in .angular-cli.json. The README suggested I should, I obviously misread it.

**Comment by tokaika** [comment]
i  cannot  understand your  sentence。。i had  added  "../node_modules/ngx-quill/bundles/ngx-quill.umd.js" in angular-cli.json.  i  have  this issue。。。you  mean  delete  it and will  be  right？@fergalmoran

**Comment by KillerCodeMonkey** [comment]
nope you have to add it. maybe you missed some other thirdparty libraries?

**Comment by fergalmoran** [comment]
@tokaika I'm using angular cli so I don't need to add it, it's already added by the module loader.
All I have to add in .angular-cli.json is

    "../node_modules/quill/dist/quill.js",

**Comment by lichkovskyi** [comment]
I have the same issue with angular 6. I include 2 scripts to angular.json
"scripts": [
              "node_modules/quill/dist/quill.js",
              "node_modules/ngx-quill/bundles/ngx-quill.umd.js"
]

<img width="553" alt="2018-05-07 21 03 05" src="https://user-images.githubusercontent.com/21039970/39716863-34d8133c-523a-11e8-9be8-946bfac138e1.png">

**Comment by KillerCodeMonkey** [comment]
Try to remove ngx-quill.umd.js from the scripts array, like the others did :)

**Comment by tokaika** [comment]
ok。。i will  try。。。let me  give this project  a  star。。。

**Comment by KillerCodeMonkey** [comment]
:D and close this issue if you resolved it. really strange. i don't got this during my tests with angular-cli

**Comment by lichkovskyi** [comment]
@KillerCodeMonkey yes require fixed, but INLINE_BLOT is present. I have this when build with production mode

**Comment by tokaika** [comment]
ok   let  me  find  the  close  button。。

**Comment by KillerCodeMonkey** [comment]
one step after another:
check this out: https://github.com/KillerCodeMonkey/ngx-quill/issues/172
An issue to angular-cli is linked.

**Comment by anu1rag** [comment]
Like everyone said, I had to remove "node_modules/ngx-quill/bundles/ngx-quill.umd.js" from the angular.json in angular v6 to get rid of the error....

**Comment by KillerCodeMonkey** [comment]
I added already a Note in the readme ;). Glad You solved it

anu1rag <notifications@github.com> schrieb am Mi., 6. Juni 2018, 19:23:
