### ISSUE TITLE
Scrolling top when pasting or removing link

### ISSUE THREAD

**Issue by kubahorochowski** [KillerCodeMonkey/ngx-quill#1700]
Hello,
while using ngx-quill in my project I noticed that after pasting or removing link from editor, the page scrolls to the top of the component. I noticed the same behavior in ngx-quill-example repository.

Steps to reproduce
1. Open ngx-quill-example
2. Scroll page below the top of editor window.
3. Paste content or remove link in scrolled down editor window.

**Comment by KillerCodeMonkey** [comment]
this scroll top is just a side effect of my demo app.
one component is changing the content on init with a debounce.
if you wait for the change to happen nothing scrolls on paste.
