### ISSUE TITLE
Error in type definitions

### ISSUE THREAD

**Issue by joshting** [KillerCodeMonkey/ngx-quill#1701]
I am using Angular 16 and when I am building I get the following error.  I am suspecting that Delta should be DeltaOperation instead?

Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:1:21 - error TS2614: Module '"quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "quill"' instead?

1 import QuillType, { Delta } from 'quill';

**Comment by KillerCodeMonkey** [comment]
install correct typings of quill.. v1 belongs to v1 of quill.
Check the readme and for similar already closed issues, please
