### ISSUE TITLE
is 22.0 compatible with Angular 15.x?

### ISSUE THREAD

**Issue by horodynskyi** [KillerCodeMonkey/ngx-quill#1705]

**Comment by K0ST4S** [comment]
Compiling ngx-quill : es2015 as esm2015
(node:11094) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
⠙ Generating browser application bundles (phase: building)...node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);

**Comment by KillerCodeMonkey** [comment]
nope. i think v22 is using a newer rxjs major version compatible only für angular 16, when i remember it correctly.

**Comment by horodynskyi** [comment]
i tried and not) 
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/72071697/4f689f52-e55b-41e5-b122-01a7b5a7e34e)
i just asked cuz in ReadMe we have 15 <= 22.0.0 😊

**Comment by KillerCodeMonkey** [comment]
uhhh i changed the readme. thanks for pointing it out :D
