### ISSUE TITLE
custom div and classes both are getting removed when binding it as HTML to the quill editor

### ISSUE THREAD

**Issue by kalandher** [KillerCodeMonkey/ngx-quill#1712]
custom div and classes both are getting removed when binding it as HTML to the quill editor
(https://stackoverflow.com/questions/76744440/custom-div-and-classes-both-are-getting-removed-when-binding-it-as-html-to-the-q)

Steps for Reproduction

in Ts file i have

`this.htmlText = "<span class="my-thing"><a href="http://help.com" rel="noopener noreferrer" target="_blank">help.com</a></span>" `

Quill editor code in HTML

`<quill-editor  (onEditorCreated)="onEditorCreated($event)" [(ngModel)]="htmlText"   #headerElement  [modules]="modules" [styles]="{height: '200px'}" (onFocus)="focus($event)" (onEditorChanged)="changedEditor($event)" (onBlur)="blur($event)" (onEditorCreated)="created($event)"></quill-editor>`

after rendering custom classes and custom span are getting removed.

I have created a custom bolt to create a custom span and custom class which is working fine. I'm able to add and save. While initializing quill editor with the saved HTML. custom span and custom classes are getting removed.

```
this.modules = {
        toolbar: {
          container: [
            ['my-thing']
          ]
      }
    }


    var Block = Quill.import('blots/block');
    
    class MyThing extends Block {}
    MyThing.blotName = 'my-thing';
    MyThing.className = 'my-thing';
    MyThing.tagName = 'span';
    
    Quill.register(MyThing);
    
```
 
Expected behavior:
I should see custom divs and classes which were added to the content should be shown after initializing quill editer with HTML
Actual behavior:
Custom elements and classes are getting removed
Platforms:

Version:
ngx-quill : 22.0.0
quill: 1.3.7,

**Comment by KillerCodeMonkey** [comment]
let me know if you got it working

**Comment by kalandher** [comment]
I created new Parchment something like this

```
let CustomClass = new Parchment.Attributor.Class('custom', 'ql-custom', {
    scope: Parchment.Scope.INLINE
});

Quill.register(CustomClass, true);

//added custom control to toolbar

        this.modules = {
            toolbar: {
              container: [
                ['custom'],
              ]
           }
         }
         
         
        

         //add handler for custom control in onEditorCreated() method
         const toolbar = quill.getModule('toolbar');
          toolbar.addHandler('custom', (value) => {
            var range = this.quillEditor.getSelection();
            var format = this.quillEditor.getFormat(range);
             if(format.custom) {
                this.quillEditor.format('custom', '');
            } else {
                this.quillEditor.format('custom', 'test');
            }   
          });


```

this worked for me. I used same for custom dropdown also.

**Comment by KillerCodeMonkey** [comment]
thanks for sharing the solution. feel free to close the issue :)
