### ISSUE TITLE
get raw HTML instead of Delta/quil parsed object

### ISSUE THREAD

**Issue by farisT** [KillerCodeMonkey/ngx-quill#1715]
Hi! I am trying to get the raw html typed in but it seems like all the emitted values from `quill-editor` are a Delta object with parsed HTML e.g. 
<img width="634" alt="Screenshot 2023-08-08 at 15 09 00" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/33259789/81b2d02d-44df-45c5-8306-c4e3e10983ae">

This is my setup - I am just using a form builder group

```
      <quill-editor
        customToolbarPosition="bottom"
        format="object"
        [modules]="{ syntax: true }"
        [formControl]="getFormControl('userReaction')"
      >
        >
        <div quill-editor-toolbar>
          <span class="ql-formats">
            <button class="ql-bold"></button>
            <button class="ql-list" value="ordered"></button>
            <button class="ql-list" value="bullet"></button>
          </span>
        </div>
      </quill-editor>
```

TS file
```
  public ngOnInit(): void {
    this.caseMessagesForm = this.formBuilder.group({
      userReaction: ['', [Validators.required, validator()]],
    });
  }

  public getFormControl(key: string): FormControl | null {
    return this.caseMessagesForm.get(key) as FormControl;
  }
```

What I have noticed is that if I just use the output emitters on the quill component e.g. `(onContentChanged)="test($event)"` i do get the raw html emitted

**Comment by KillerCodeMonkey** [comment]
you are using format object so the object respresentation is stored on the control

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill#config check the `format` option
