### ISSUE TITLE
Add custom table

### ISSUE THREAD

**Issue by quan1997ap** [KillerCodeMonkey/ngx-quill#1717]
Hi team, I want to add custom table to ngx-quill. Looks like it's currently not supported.
How can i do it.
Thanks.
--- Sorry about my english ---

**Comment by KillerCodeMonkey** [comment]
tables will be supported with quilljs v2. but since it is not stable it is not supported with ngx-quill.

you can try to ignore that and install the dev quilljs v2 and the v2 typings.

Or you build your own Blot and Module with table support.

**Comment by quan1997ap** [comment]
thank you. Let me try it.

Vào Th 5, 10 thg 8, 2023 vào lúc 18:30 Bengt Weiße <
***@***.***> đã viết:
