### ISSUE TITLE
 Module '"quill"' has no exported member 'Delta'. 

### ISSUE THREAD

**Issue by parthupadhye** [KillerCodeMonkey/ngx-quill#1718]
Error: node_modules/@types/quill/node_modules/quill-delta/dist/Delta.d.ts:1:8 - error TS1259: Module '"C:/Users/parth/workspaces/impromptu/node_modules/@types/quill/node_modules/fast-diff/diff"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import diff from 'fast-diff';
         ~~~~

  node_modules/@types/quill/node_modules/fast-diff/diff.d.ts:20:1
    20 export = diff;
       ~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:2:21 - error TS2614: Module '"quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "quill"' instead?

2 import QuillType, { Delta } from 'quill';

**Comment by parthupadhye** [comment]
Thought I'd share the following too:

"dependencies": {
    "@angular/animations": "^15.2.9",
    "@angular/common": "^15.2.9",
    "@angular/compiler": "^15.2.9",
    "@angular/core": "^15.2.9",
    "@angular/fire": "^7.6.1",
    "@angular/forms": "^15.2.9",
    "@angular/platform-browser": "^15.2.9",
    "@angular/platform-browser-dynamic": "^15.2.9",
    "@angular/router": "^15.2.9",
    "ngx-quill": "8.1.3",
    "quill": "^1.3.7",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.2.9",
    "@angular/cdk": "^15.2.9",
    "@angular/cli": "^15.2.9",
    "@angular/compiler-cli": "^15.2.9",
    "@angular/material": "15.2.9",
    "@ngx-formly/core": "^6.1.8",
    "@ngx-formly/material": "^6.1.8",
    "@types/jasmine": "~4.3.0",
    "@types/quill": "^2.0.10",
    "@types/uuid": "^9.0.2",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.9.3",
    "uuid": "^9.0.0"
  }

**Comment by KillerCodeMonkey** [comment]
please use the issue search... or google... and follow the install steps in the readme and install the correct version of the quill typings. if you install @types... the major version should match with the lib version
