### ISSUE TITLE
Unable to get property 'INLINE_BLOT' of undefined or null reference

### ISSUE THREAD

**Issue by JohnGalt1717** [KillerCodeMonkey/ngx-quill#172]
When a full ng build --prod is done the following error starts to appear on our site with Angular 6 and ngx-quill 3.0.0

It's fine with development.

All of the default instructions have been followed, QuillModule is imported in the app.module.ts file and again it all works in development mode.

**Comment by KillerCodeMonkey** [comment]
Yeah i am Not an angular cli Experten, maybe You need to add quill to the
includes in the angular.json?



James Hancock <notifications@github.com> schrieb am Fr., 4. Mai 2018, 16:11:

**Comment by JohnGalt1717** [comment]
It appears that this is a bug in angular-cli/compiler.

I've opened a bug here: https://github.com/angular/angular/issues/23712
