### ISSUE TITLE
Add Auth Header to Image Request

### ISSUE THREAD

**Issue by lavaloop-official** [KillerCodeMonkey/ngx-quill#1723]
Is it possible to add headers to the image request of the quill editor if they point to a certain url? My regular Angular interceptor is not called when an image is loaded in the editor and I would like to authenticate users before giving them access to the images.

**Comment by KillerCodeMonkey** [comment]
per default image sources in quilljs are base64. If you have a logic to upload / use urls for images it is technical not possible to add anything to an "img-src" as far as i know.

In general you would have to load your image beforehand and set the auth headers and transform the results to an URL.
