### ISSUE TITLE
Feature: Inject ViewContainerRef Into Editor Component

### ISSUE THREAD

**Issue by tommyc38** [KillerCodeMonkey/ngx-quill#1725]
Please inject `ViewContainerRef` in the `<quill-editor>` component so it's easier to inject custom components into the view (e.g. mentions, other panels, etc.).

I will create a pull request if you'd like?

**Comment by KillerCodeMonkey** [comment]
can you share an example?

**Comment by tommyc38** [comment]
I actually figured out a way around this using Portals from `@angular/cdk`.  Thanks for commenting!
