### ISSUE TITLE
Delta import error of 'quill'

### ISSUE THREAD

**Issue by kaikdandrade** [KillerCodeMonkey/ngx-quill#1727]
Name: Bug Report

About: Error Found in Project. This error occurs when importing Delta from 'quill'.

**The error is occurring in version v22.0.0.**

Error Message:
![Error Image](https://drive.google.com/uc?id=1755ImNi4O4m5FD6Fnt9fUKOyFGe-ll6A)

Labels: [bug] [import]

---

## **Steps to Reproduce:**
After installation, in the `tsconfig.json` file, I added the line "allowSyntheticDefaultImports": true" after "compilerOptions". In the "imports" section of `app.module.ts`, I added the "QuillModule" and imported it. In the component where I was going to add the editor in the .html, I included `<quill-editor></quill-editor>`. And, of course, I added the following lines to styles.scss: 
```scss
@import '~quill/dist/quill.core.css'; 
@import '~quill/dist/quill.snow.css';
```
Other than that, I didn't get to the configuration part itself.

## **Environment:**
- Operating System: Windows 10
- Browser: Google Chrome
- Angular Version: v16.2.0
- ngx-quill Version: v22.0.0

## **Possible Solutions:**
Change the import to:
```javascript
import QuillType, { DeltaOperation as Delta } from 'quill';
```
or change all occurrences of `Delta` to `DeltaOperation` and leave the import like this:
```javascript
import QuillType, { DeltaOperation } from 'quill';
```

**Comment by KillerCodeMonkey** [comment]
Incorrect types of quilljs... Install v1

kaikdandrade ***@***.***> schrieb am Fr., 25. Aug. 2023,
21:06:
