### ISSUE TITLE
attributes missing after insertText function

### ISSUE THREAD

**Issue by Hig4tower** [KillerCodeMonkey/ngx-quill#1728]
Steps for Reproduction

create an insert statement like this -> insertText(0,insert,attributes,"api")
insert is the text and attributes the attributes to add to the text.

after insertion use the getContext() Method. Some attributes are gone. See pictures below

before insertion:
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/124250085/4db3db04-9dc7-49ce-a4dd-01bd8099b504)

after insertion:
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/124250085/1838d7d8-f08e-4d62-b475-4d78b2bdee51)

Expected behavior:

Every attribute should be visible all the time

Actual behavior:

Some attributes are being removed

Platforms:
Angular 15
Chrome,
Windows 11,

Version:

"ngx-quill": "^20.0.1",
"@types/quill": "^1.3.10",

**Comment by Hig4tower** [comment]
So is it possible to add a Tag or something like that to the text that i want to insert?

I need to get the Data at a later point (e.g. after manual editing) and match them to corresponding areas

**Comment by Hig4tower** [comment]
How to register with the ngx-quill ?
I got this in my module.ts

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/124250085/649ba536-2e55-4a39-b09b-343c6ad42f5a)


I cant register a format here... and inside my component where i use the quilleditor i have this

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/124250085/5b029ac8-a659-40c6-8ddc-0a756ba6de06)

And here i also cant register a format to handle my case... 

What do i miss here? =/

The documentation cant help me that much since im using ngx-quill

**Comment by Hig4tower** [comment]
Hey @KillerCodeMonkey i saw your customOptions with the section

`customOptions: [{
        import: 'formats/font',
        whitelist: ['mirza', 'roboto', 'aref', 'serif', 'sansserif', 'monospace']
      }]`
but i dont know how to achieve it, to add a Tag to my Text insertions...
some basic information is missing in my opinion and i cant figure it out, how to solve this issue. I was gambling around with containers and adding attributes to the div elements. But that doesnt seem to be correct from my perspective. 

I realy dont want a complete solution, but what do i have to put in for the imports and whitelist when i want to add a customAttribute to my text as a tag (this attribute should only be in the background and not visible) in the editor.

Is it even the correct way, to add a customOption to achieve what i want?

Best regards!

**Comment by KillerCodeMonkey** [comment]
you need to create a new custom format/blot https://quilljs.com/guides/how-to-customize-quill/#customizing-blots
