### ISSUE TITLE
Insert text in specified index

### ISSUE THREAD

**Issue by goluunified** [KillerCodeMonkey/ngx-quill#1732]
I want to insert where is my cursor 
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/144777862/0963c166-8f39-4ed5-a4ae-235ba9828710)

like my  cursor after `1500s ` so I want to insert text that point, so how can I insert text at that position?

**Comment by KillerCodeMonkey** [comment]
just grab store the current position you get in https://github.com/KillerCodeMonkey/ngx-quill#outputs selectionChange or editorChange output.

after that you can manipulate the editor content, e.g. by using the quilljs api https://quilljs.com/docs/api/#insertembed
