### ISSUE TITLE
Highlighting Colored and Formatted Text Bug

### ISSUE THREAD

**Issue by jack-burns1** [KillerCodeMonkey/ngx-quill#1734]
In my use of the ngx-quill text editor, I encountered an error when I highlight and try to replace colored text with the following parameters:

one or more characters + one or more characters with a text transformation (bold, italic, etc).

**Note all text must have a color property.

When I highlight this text and then start typing (as one normally would to replace text), then the whole line is deleted, and the new text does not appear.

This showed up in my implementation of the text editor, so I tried it on https://killercodemonkey.github.io/ngx-quill-example/
and I still see the issue. 

Here are some images replicating the issue:
Starting text
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/73075227/ce863715-f138-4715-a5b9-8d28a88b0cc8)

Highlighted:
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/73075227/3656ca61-4439-48d5-8b2a-4c578b84a51f)

After typing "Hello" while the text is highlighted:
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/73075227/c325713d-5a94-47e0-a868-26b68bfa3840)

**Note I used the "Text" format example in this instance, but the problem is present with all formats

**Comment by KillerCodeMonkey** [comment]
Sadly i can not reproduce your issue...

1. with not selecting the text to replace again -> format stays
  
![test2](https://github.com/KillerCodeMonkey/ngx-quill/assets/2264672/5faeacce-aa85-4a57-bcb8-c610d767a9b7)

2. with selecting the text to replace again -> format goes

![test](https://github.com/KillerCodeMonkey/ngx-quill/assets/2264672/547579ac-0321-4cd3-9d0d-c0c6a316807f)

Works in chrome and firefox

**Comment by KillerCodeMonkey** [comment]
Any updates on that?
