### ISSUE TITLE
Invalid quill container after upgrading to Angular 14 from 13

### ISSUE THREAD

**Issue by akaMisha** [KillerCodeMonkey/ngx-quill#1735]
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/54476114/0b8cc64c-6958-4491-9ddb-ba6e6a09ded2)
Made a new demo project and migrated and it seems to work but in my project it doesn't matter wherever i put it, it gives me this error. I tried a new component and just a blank mat-quill and i still get this. I am using mat-quill and i changed as in the commit for migrating to angular 14 in the mat-quill-base `stateChanges = new Subject<void>();`  also i added in there `this.contentCreatedSubscription = this.onEditorCreated.subscribe(() => {
      this.updateErrorState();
      this.stateChanges.next();
    });` (i dont know if relevant).  These are my dependencies `"ngx-quill": "^19.0.1",
"quill": "^1.3.7",
    "quill-cursors": "^4.0.2",
    "quill-image-compress": "^1.2.30",
    "y-quill": "^0.1.5",`  and this is my module `QuillModule.forRoot({
      modules: {
        cursors: true,
        history: {
          userOnly: true,
        },
        imageCompress: {
          quality: 0.7,
          maxWidth: 200,
          maxHeight: 200,
          imageType: 'image/jpeg', // default
          debug: false,
          suppressErrorLogging: true,
          insertIntoEditor: undefined, // default
        },
      },
    }),` tried even with a blank one and still not working. I thought about maybe its called before being rendered.

**Comment by KillerCodeMonkey** [comment]
please create a demo repo or stackblitz to reproduce.

here you can find the state of my demo repo for angular 14: https://github.com/KillerCodeMonkey/ngx-quill-example/tree/63a3b59aefdeb0ed660672a52574ad18772a62a5 it is working

try to remove third party modules n check if it is working then.

BTW: i do not officially maintain the mat-quill things. it is more like a small and dump example how it goes ;-). 

And yes it seems quill is initialised but the container/element is not ready or got removed

**Comment by akaMisha** [comment]
Thank you for replying! Seems like I cannot replicate it on a demo project.. Do you have any idea on how to attach the container manually? As I stated in the mat-quill-base ` get value() ` editorElem is null as well as Quill.container.

> please create a demo repo or stackblitz to reproduce.
> 
> here you can find the state of my demo repo for angular 14: https://github.com/KillerCodeMonkey/ngx-quill-example/tree/63a3b59aefdeb0ed660672a52574ad18772a62a5 it is working
> 
> try to remove third party modules n check if it is working then.
> 
> BTW: i do not officially maintain the mat-quill things. it is more like a small and dump example how it goes ;-).
> 
> And yes it seems quill is initialised but the container/element is not ready or got removed

**Comment by KillerCodeMonkey** [comment]
i would just debug why you element is not there or gone :).

because in general `quill-editor` inits everything the quilljs editor needs.

**Comment by KillerCodeMonkey** [comment]
any updates

**Comment by akaMisha** [comment]
Hey, yes thanks for asking, seems like it was just bad upgraded to the newer version, the implementation was fine!
