### ISSUE TITLE
How dynamically change the toolbar configuration of ngx-quill based on the results of HTTP requests ?

### ISSUE THREAD

**Issue by haykoaghababyan** [KillerCodeMonkey/ngx-quill#1737]
<quill-editor
  (onEditorCreated)="onCreated($event)"
  [formControl]="control"
  [modules]="editorConfig"
  [placeholder]="'placeholder.' + 'newMessage' | transloco"
  [preserveWhitespace]="true"
  [readOnly]="disabled"
  [sanitize]="true"
  [styles]="styles"
  class="w-full"
  quillPaste
>
</quill-editor>

when I changing the modules , nothing is changed,  the very first configuration remains

**Comment by KillerCodeMonkey** [comment]
this is not possible. quilljs is plain js and after initialization it is not possible to change it. 
so you have to re-render the whole component.

**Comment by haykoaghababyan** [comment]
Got it, thanks
