### ISSUE TITLE
Quill using deprecated DOMNodeInserted mutation event

### ISSUE THREAD

**Issue by xsegrity** [KillerCodeMonkey/ngx-quill#1739]
Quilljs is using deprecated DOMNodeInserted mutation events in their 1.3.6+ code. These calls will be removed from chrome in the future (July 2024). The quilljs team is currently working on v2, which will remove these deprecated calls and resolve the issue. Adding this issue here since ngx-quill will need to upgrade to use quilljs v2 when it comes out and to help any other that see the warning and are trying to track down why it's happening. Here is the relevant info:

https://github.com/quilljs/quill/issues/3806
https://chromestatus.com/feature/5083947249172480

<img width="976" alt="Screenshot 2023-09-23 at 12 47 29 PM" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/4366841/d7b591f2-4a05-4a51-bfc1-5b70e4562902">

**Comment by KillerCodeMonkey** [comment]
i think an issue is not needed, since it is a quilljs issue.

if quill is releasing a rc release. an issue can be opened to upgrade to that version.
