### ISSUE TITLE
ngx-quill with formula

### ISSUE THREAD

**Issue by benengi** [KillerCodeMonkey/ngx-quill#1740]
Hello, 
I am using ngx-quill with angular 14. I have already added the math formula and it works. However, I am facing an issue when I am storing the data after using formula. combined with reactive form, it save a long html text for a small equation.
 I just entered this equation \frac{2}{4} + \sum_{4}^{4}4 and in return , in the database I got thee text below to stored which seems very long for. a small equation

is that a normal quill behaviour or I need to consider some configuration

Thank you for the support

here the link for the text
[https://docs.google.com/document/d/1XT7BlUlldSICouGiVBEYylDKqU7pNG1CpnB6l63fhQw/edit?usp=sharing](url)

**Comment by KillerCodeMonkey** [comment]
You can change the output format to object or json instead of html.

The produced output is how quill formats the formula.
So even if you use the object format of the editor. The quill-view
component of ngx-quill would produce those html when rendering.

benengi ***@***.***> schrieb am Mo., 2. Okt. 2023, 07:04:

**Comment by benengi** [comment]
thank you for the answer.  if i am saving the content as object it will not possible to render that in html using a simple tag ( exemple h1 or p tags : exemple
 <h3 class="fs-4 fw-bold" [innerHTML]="byPassHTML(quillContent )">

in your exemple you have less text for the formula which is acceptable  when you are passing it from TS . when I changed it and log it in the console, the texte became ver long ( 3 Word google doc pages : add it a link for that )

your example
---

<p> <span class=\"ql-formula\" data-value=\"\\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}\"> \\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x} </span> -------------------- (1) </p> <p> <span class=\"ql-formula\" data-value=\"\\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}\"> \\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x} </span> -------------------- (2) </p>

-----

if enter that to formula I got a lot of other additional information form Latex library or just by adding another word on the quill editor :  here a result of the same equation by entering it from the quill formula :  here a image show from the inspector the log that i am getting : 

link show how long text : 3 Word document pages to save for small equation [https://docs.google.com/document/d/1H_jg3s0LN_UTx9DcyYcLOtN8YUhwgpMhejh5V_Pd2lU/edit?usp=sharing](url)\

will be possible to simplify this texte and remove all additionnal infomation that added and just keeoing the formula text ( the same as your exemple above 

-----

" <div>Consider the point P on the curve y = f (x) whose coordinates are (x, y) and another point Q where coordinates are (x + Δx, y + Δy). The slope of the line joining P and Q is given by:</div><div><span class="ql-formula" data-value="\tan\theta = \frac{\triangle y}{\triangle x}=\frac{(y+\triangle y)-y}{\triangle x}">﻿<span contenteditable="false"><span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>tan</mi><mo>⁡</mo><mi>θ</mi><mo>=</mo><mfrac><mrow><mi mathvariant="normal">△</mi><mi>y</mi></mrow><mrow><mi mathvariant="normal">△</mi><mi>x</mi></mrow></mfrac><mo>=</mo><mfrac><mrow><mo stretchy="false">(</mo><mi>y</mi><mo>+</mo><mi mathvariant="normal">△</mi><mi>y</mi><mo stretchy="false">)</mo><mo>−</mo><mi>y</mi></mrow><mrow><mi mathvariant="normal">△</mi><mi>x</mi></mrow></mfrac></mrow><annotation encoding="application/x-tex">\tan\theta = \frac{\triangle y}{\triangle x}=\frac{(y+\triangle y)-y}{\triangle x}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height: 0.6944em;"></span><span class="mop">tan</span><span class="mspace" style="margin-right: 0.1667em;"></span><span class="mord mathnormal" style="margin-right: 0.0278em;">θ</span><span class="mspace" style="margin-right: 0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right: 0.2778em;"></span></span><span class="base"><span class="strut" style="height: 1.4133em; vertical-align: -0.4811em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height: 0.9322em;"><span class="" style="top: -2.655em;"><span class="pstrut" style="height: 3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">△</span><span class="mord mathnormal mtight">x</span></span></span></span><span class="" style="top: -3.23em;"><span class="pstrut" style="height: 3em;"></span><span class="frac-line" style="border-bottom-width: 0.04em;"></span></span><span class="" style="top: -3.4461em;"><span class="pstrut" style="height: 3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">△</span><span class="mord mathnormal mtight" style="margin-right: 0.0359em;">y</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height: 0.4811em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span><span class="mspace" style="margin-right: 0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right: 0.2778em;"></span></span><span class="base"><span class="strut" style="height: 1.4911em; vertical-align: -0.4811em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height: 1.01em;"><span class="" style="top: -2.655em;"><span class="pstrut" style="height: 3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">△</span><span class="mord mathnormal mtight">x</span></span></span></span><span class="" style="top: -3.23em;"><span class="pstrut" style="height: 3em;"></span><span class="frac-line" style="border-bottom-width: 0.04em;"></span></span><span class="" style="top: -3.485em;"><span class="pstrut" style="height: 3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mopen mtight">(</span><span class="mord mathnormal mtight" style="margin-right: 0.0359em;">y</span><span class="mbin mtight">+</span><span class="mord mtight">△</span><span class="mord mathnormal mtight" style="margin-right: 0.0359em;">y</span><span class="mclose mtight">)</span><span class="mbin mtight">−</span><span class="mord mathnormal mtight" style="margin-right: 0.0359em;">y</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height: 0.4811em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span></span></span></span></span>﻿</span> -------------------- (1) </div><div><span class="ql-formula" data-value="\tan\theta = \frac{\triangle y}{\triangle x}=\frac{(y+\triangle y)-y}{\triangle x}">﻿<span contenteditable="false"><span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>tan</mi><mo>⁡</mo><mi>θ</mi><mo>=</mo><mfrac><mrow><mi mathvariant="normal">△</mi><mi>y</mi></mrow><mrow><mi mathvariant="normal">△</mi><mi>x</mi></mrow></mfrac><mo>=</mo><mfrac><mrow><mo stretchy="false">(</mo><mi>y</mi><mo>+</mo><mi mathvariant="normal">△</mi><mi>y</mi><mo stretchy="false">)</mo><mo>−</mo><mi>y</mi></mrow><mrow><mi mathvariant="normal">△</mi><mi>x</mi></mrow></mfrac></mrow><annotation encoding="application/x-tex">\tan\theta = \frac{\triangle y}{\triangle x}=\frac{(y+\triangle y)-y}{\triangle x}</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height: 0.6944em;"></span><span class="mop">tan</span><span class="mspace" style="margin-right: 0.1667em;"></span><span class="mord mathnormal" style="margin-right: 0.0278em;">θ</span><span class="mspace" style="margin-right: 0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right: 0.2778em;"></span></span><span class="base"><span class="strut" style="height: 1.4133em; vertical-align: -0.4811em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height: 0.9322em;"><span class="" style="top: -2.655em;"><span class="pstrut" style="height: 3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">△</span><span class="mord mathnormal mtight">x</span></span></span></span><span class="" style="top: -3.23em;"><span class="pstrut" style="height: 3em;"></span><span class="frac-line" style="border-bottom-width: 0.04em;"></span></span><span class="" style="top: -3.4461em;"><span class="pstrut" style="height: 3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">△</span><span class="mord mathnormal mtight" style="margin-right: 0.0359em;">y</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height: 0.4811em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span><span class="mspace" style="margin-right: 0.2778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right: 0.2778em;"></span></span><span class="base"><span class="strut" style="height: 1.4911em; vertical-align: -0.4811em;"></span><span class="mord"><span class="mopen nulldelimiter"></span><span class="mfrac"><span class="vlist-t vlist-t2"><span class="vlist-r"><span class="vlist" style="height: 1.01em;"><span class="" style="top: -2.655em;"><span class="pstrut" style="height: 3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mord mtight">△</span><span class="mord mathnormal mtight">x</span></span></span></span><span class="" style="top: -3.23em;"><span class="pstrut" style="height: 3em;"></span><span class="frac-line" style="border-bottom-width: 0.04em;"></span></span><span class="" style="top: -3.485em;"><span class="pstrut" style="height: 3em;"></span><span class="sizing reset-size6 size3 mtight"><span class="mord mtight"><span class="mopen mtight">(</span><span class="mord mathnormal mtight" style="margin-right: 0.0359em;">y</span><span class="mbin mtight">+</span><span class="mord mtight">△</span><span class="mord mathnormal mtight" style="margin-right: 0.0359em;">y</span><span class="mclose mtight">)</span><span class="mbin mtight">−</span><span class="mord mathnormal mtight" style="margin-right: 0.0359em;">y</span></span></span></span></span><span class="vlist-s">​</span></span><span class="vlist-r"><span class="vlist" style="height: 0.4811em;"><span class=""></span></span></span></span></span><span class="mclose nulldelimiter"></span></span></span></span></span></span>﻿</span> -------------------- (2)</div>"

**Comment by benengi** [comment]
Hi Bengt, 

hope you are doing well
Did you have chance to see the video related to the length of the text ? what do you think ?
here a video show the difference : [https://www.youtube.com/watch?v=0JENr-HsimA]

Thanks

**Comment by KillerCodeMonkey** [comment]
yes but i have no influence about it, because i am not the maintainer of quilljs. ngx-quill is just an angular wrapper for quilljs and i do not change native quilljs behaviour. So in general ask at quilljs for optimizations.

So there is nothing i can do for you here.

**Comment by benengi** [comment]
Thank you for the clarification. I will consider Mathjax as a workaround 
Good work for the nice quill wrapper

**Comment by benengi** [comment]
Thank you for the clarification. I will consider Mathjax as a workaround
Good work for the nice quill wrapper
