### ISSUE TITLE
Code coverage issue with ngx-quill editor.

### ISSUE THREAD

**Issue by Deepika-lm** [KillerCodeMonkey/ngx-quill#1741]
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/114415826/3aa7e8f8-2427-4372-9b3a-bc138a5d836c)
[text-editor.zip](https://github.com/KillerCodeMonkey/ngx-quill/files/12813137/text-editor.zip)
Here we are using ngx-quill library and we are unable to cover the test cases for the code which is used in the attached files. Can anyone guide us to have 100%  code coverage to writing unit test cases.
We are using this library and followed the documentation from this website: https://www.npmjs.com/package/ngx-quill-editor

**Comment by KillerCodeMonkey** [comment]
not the right place to ask for, sorry. ;-)

**Comment by Subrata19777** [comment]
@KillerCodeMonkey - We are facing the issue, where we can post this ?

**Comment by KillerCodeMonkey** [comment]
just ask at stackoverflow or where ever... i mean i do not see, what a question about your code coverage is depending on the libraries you use. 

Just mock library depending things and do not aim just for 100% coverage... if your tests are testing nothing and just calling the component methods ;-).
