### ISSUE TITLE
[readOnly] does not work when using formControl

### ISSUE THREAD

**Issue by chrisdfh** [KillerCodeMonkey/ngx-quill#1744]
i tried marking the <quill-editor> as readOnly, but it doesnt work  when using formControl 

```
<quill-editor [readOnly]="isReadOnly" [modules]="quillToolbar" formControlName="description" (paste)="paste($event)" ></quill-editor>
```

the formControl state is initialized as disabled

i saw the examples in stackblitz and there, using ngModel it works fine

is there any way to achieve the readOnly state using formControl ?

**Comment by KillerCodeMonkey** [comment]
can you please create a stackblitz or something for reproduction. as far as i can see i have no logic to disable the control:
https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.ts#L608

If it is readonly, only the quill-api is called to disable/enable the editor

**Comment by KillerCodeMonkey** [comment]
@chrisdfh any updates?

**Comment by chrisdfh** [comment]
Sorry dont know how to replicate my setup on stackblitz, version of angular for example, googling a way to do so. it always defaults to latest version of angular and angular/form in which this problem doesnt occur. i use version 15.2

**Comment by chrisdfh** [comment]
On angular 7 this doesnt occur also. This is the one used on your example. also has a different approach, in this version 7 i could use readOnly="isReadOnly" without the brackets

**Comment by chrisdfh** [comment]
it must be something particular with my setup. you can close this issue if you want. i mimicked the readOnly status with css, using a "no-edit" class

.no-edit .ql-editor{
  color:rgba(0, 0, 0, 0.38);
}
.no-edit{
  user-select:none;
  pointer-events: none;
}

**Comment by KillerCodeMonkey** [comment]
alrighty then. thanks for the response and your workaround.
