### ISSUE TITLE
Reactive forms onEditorCreated when quill.format() is called, the editor control is marked as touched

### ISSUE THREAD

**Issue by dumitrascuSorin** [KillerCodeMonkey/ngx-quill#1745]
Steps to reproduce:

1. Use the [reactive-forms](https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/reactive-forms) example from the demo
2. In the component, subscribe to the onEditorCreated event and call the format method
```javascript
this.editor
      .onEditorCreated
      .subscribe((quill: Quill) => {
        quill.format('font', 'monospace')
      })
```
3. In the template, check if the control has been touched
```html
Is the control touched? {{form.get('editor').touched}}<br>
```
4. Click anywhere on the page and outside the editor or its toolbar.

### 📗 Expected Behavior
I would expect the editor control to not be marked as touched.
`form.get('editor').touched` should return **false**

### 📕 Actual Behavior

`form.get('editor').touched` is going to return **true**

**Comment by KillerCodeMonkey** [comment]
can you check, if you have set the input `trackChanges` to `all` - try to set it to 'user'.
per default ngx-quill only recognizes changes of "source" `user` as changes.
You can can try to pass "silent" as source to your call `quill.format('font', 'monospace', 'silent')` 

https://quilljs.com/docs/api/#format

**Comment by KillerCodeMonkey** [comment]
@dumitrascuSorin could you please try 23.0.0-beta.1 ? i implemented the selectionChange handling similar to the textChange handling (considering the trackChanges input). Per default only selection changes done by the "user" are effecting onBlur, onFocus, onSelectionChanged calls and setting "touched".

when using trackChange "all" the behavior should be like it was before.

**Comment by dumitrascuSorin** [comment]
Hi, 
I gave it a try and doesn't seem to work for me.
I think we can leave it as it is.
Thank you very much for your time.

**Comment by KillerCodeMonkey** [comment]
i think i will release it anyway since the handling is more unified between text and selection changes.

thanks for the response.
Feel free to create a PR if you have something that would solve your problem
