### ISSUE TITLE
Module '"quill"' has no exported member 'Delta'.

### ISSUE THREAD

**Issue by iabu94** [KillerCodeMonkey/ngx-quill#1746]
```bash
Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:1:21 - error TS2614: Module '"quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "quill"' instead?

1 import QuillType, { Delta } from 'quill';
                      ~~~~~




** Angular Live Development Server is listening on localhost:4300, open your browser on http://localhost:4300/ **


× Failed to compile.
```

I'm getting this error while tried to use it in my app.

@angular/cli": "~16.2.0
"ngx-quill": "^22.1.0"
"@types/quill": "^2.0.12"

**Comment by KillerCodeMonkey** [comment]
check you @types version and your installed quilljs version... major versions should match between types and dep... and use issue search first

**Comment by iabu94** [comment]
All I got the latest versions, but getting this error still

**Comment by KillerCodeMonkey** [comment]
you are not reading my answer correctly

you never use simply the "latest" version of everything..

1. check the readme installations guides
2. @types/... version needs to match the dependency version of the library you want to install typings for... so types/quill v2 may not work with quilljs v1...
