### ISSUE TITLE
Enhancement?: Separate Toolbar and Editor Elements

### ISSUE THREAD

**Issue by ddelapp** [KillerCodeMonkey/ngx-quill#1749]
I would like to separate the toolbar element and editor element, so I can add content between the elements.

Example:
```
<quill-editor>
    <div quill-editor-toolbar>
        <span class="ql-formats">
            <button class="ql-bold" [title]="'Bold'"></button>
            <button class="ql-italic" [title]="'Italic'"></button>
            <button class="ql-underline" [title]="'Underline'"></button>
        </span>
        <span class="ql-formats">
            <select class="ql-align" [title]="'Aligment'">
                <option selected></option>
                <option value="center"></option>
                <option value="right"></option>
                <option value="justify"></option>
            </select>
        </span>
    </div>

    <div>
        <h1>Hello World</h1>
    </div>

    <div quill-editor-element></div>
</quill-editor>
```
To look something like:
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/6888138/72bc65bf-a687-48b9-a8a5-9770c7f4d2b9)

Is this currently possible, or could this be easily implemented?

**Comment by KillerCodeMonkey** [comment]
in general you can pass a css selector to quilljs toolbar config, e.g.

```TS
modules: {
  toolbar: '#toolbar'
}
```

where `#toolbar` can be a dom node with `id="toolbar"` attribute.
But keep in mind. quilljs does not know anything about angular. So the toolbar should be rendered before and methods you are calling within angular may not work or you need to do something like this in your angular component/page

```ts
constructor() {
  this.myCallback = this.myCallback.bind(this)
}
```

**Comment by KillerCodeMonkey** [comment]
If it is not working for you i could create an additional projection part to put something between editor and toolbar - depending if the toolbar is placed above or below :)

**Comment by KillerCodeMonkey** [comment]
@ddelapp try v23.0.0

i added two new projection-targets there

```HTML
<quill-editor>
  <div above-quill-editor-toolbar>above</div>
  <div below-quill-editor-toolbar>above</div>
</quill-editor>
```

**Comment by KillerCodeMonkey** [comment]
example is deployed to the demo page

**Comment by ddelapp** [comment]
Thank you @KillerCodeMonkey!  This is exactly what I was looking for.
