### ISSUE TITLE
Why is node locked to version 8?

### ISSUE THREAD

**Issue by princemaple** [KillerCodeMonkey/ngx-quill#175]
```
error ngx-quill@3.0.0: The engine "node" is incompatible with this module. Expected version "8".
error An unexpected error occurred: "Found incompatible module".
```

**Comment by princemaple** [comment]
Angular development/build requires a specific node version. The distributed Angular package does not require such thing. It happily compiles on node 9+. And there is no such restriction https://github.com/angular/angular/blob/master/packages/core/package.json

**Comment by KillerCodeMonkey** [comment]
yeah maybe i have to extend my buildprocess to remove the engines lines of the package.json

Feel free to send me a PR. because i need to set the engines for development ;)

**Comment by princemaple** [comment]
Are you happy with >= 8?

**Comment by KillerCodeMonkey** [comment]
yeah maybe. But i want to learn and the interesting part for me here is, how other small libraries, without this are doing it.

E.g. is it possible to simply add a second package.json to the src folder or something like that.
Beacuse this is not a special case i think... how do other projects that?

**Comment by princemaple** [comment]
They don't care?

https://github.com/swimlane/ngx-graph/blob/master/package.json
https://github.com/DethAriel/ng-recaptcha/blob/master/package.json

You are not building Angular itself from src. You are using the already built Angular. You don't need to care about node version.

**Comment by KillerCodeMonkey** [comment]
yeah but so are you, with ngx-quill :D

**Comment by princemaple** [comment]
Yeah, hence we don't need to care about node version.

**Comment by KillerCodeMonkey** [comment]
v3.1.0 released

**Comment by princemaple** [comment]
thanks
