### ISSUE TITLE
Can't get shortname to show selection menu

### ISSUE THREAD

**Issue by Slanfan** [KillerCodeMonkey/ngx-quill#1751]
When typing short names `:smiley:` I expected a menu to be shown but nothing happened.
Would you happen to know if I misconfigured it or is this an issue?

I checked the demo at https://killercodemonkey.github.io/ngx-quill-example/ and this does not support this either.

I have a completely separate set of custom icons with a custom emoji picker. I have no problems adding the emojis
from this, and they are rendered correctly.

```
this.editorModules = {
  'emoji-toolbar': false,
  'emoji-textarea': false,
  'emoji-shortname': {
    emojiList: emojis,
    fuse: {
      shouldSort: true,
      threshold: 0.1,
      location: 0,
      distance: 100,
      maxPatternLength: 32,
      minMatchCharLength: 1,
      keys: [
        'shortname'
      ]
    },
    onOpen: () => {
      console.log('EditorComponent:: emoji short list opened')
    },
    onClose: (emojiListItem: any) => {
      console.log('EditorComponent:: emoji short list, item selected', emojiListItem)
    }
  },
  toolbar: this._editorToolbar,
}
```

**Comment by KillerCodeMonkey** [comment]
I am not an quill-emoji expert so it would be better to ask at their
repository.

But it is quite inactive so I guess nothing will happen.

I found an old and still open issue:
https://github.com/contentco/quill-emoji/issues/131

Slanfan ***@***.***> schrieb am Mo., 16. Okt. 2023, 15:07:

**Comment by Slanfan** [comment]
Oh. I will have a look at this an see what happens when I switch keyboard layout. Thanks.

**Comment by Slanfan** [comment]
This seems to be the issue you referred to @KillerCodeMonkey
