### ISSUE TITLE
Disable auto play of video throughout editor

### ISSUE THREAD

**Issue by Gourishmesta** [KillerCodeMonkey/ngx-quill#1752]
Hi there,

I'm working with the Quill editor and have encountered an issue with added videos using iframes. By default, it seems that videos added via iframes autoplay, and I'd like to disable this autoplay behavior.

Is there a way to configure Quill or utilize any specific settings or plugins to prevent videos from autoplaying when added through iframes? I've gone through the documentation, but I couldn't find a solution.

Any guidance or assistance on this matter would be greatly appreciated.

Thank you in advance for your help.

**Comment by KillerCodeMonkey** [comment]
I think this is a browser/native quill issue.

I would extend the video blot and add the attributes I need.

An example how you could do it can be found in the quill guides:
https://quilljs.com/guides/cloning-medium-with-parchment/#videos

There they try to clone the medium editor an need to change some
modules/formats/blots and are changing the video blot.

It should be possible to do it the same way and add some extra attributes
to the Iframe like Autoplay to false and so on.


Gourishmesta ***@***.***> schrieb am Mo., 16. Okt. 2023,
16:49:

**Comment by Gourishmesta** [comment]
@KillerCodeMonkey  that's great i was able to implement that using video blot. But one thing came up after this change is i am not able to format the added video 
Below u can see a image added in editor which has this default overlay which comes when u click on it using which we can either resize or align it, so this overlay is not showing up for video blot
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/16563121/024a91c4-d989-46a2-b8d7-5c2c7a37065a)

**Comment by KillerCodeMonkey** [comment]
@Gourishmesta i will close this issue, since it is not directly connected to ngx-quill.
But feel free to share our solution :)
