### ISSUE TITLE
Segmentation fault while migrating to Jest & Web Runner 

### ISSUE THREAD

**Issue by shivkumar86** [KillerCodeMonkey/ngx-quill#1758]
We are migrating to Jest & Web Runner Framework getting /c/Program Files/nodejs/npm: line 44: 181 Segmentation fault "$NODE_EXE" "$NPM_CLI_JS" "$@" during running unit test in angular 15 we are using quill module inside component which fails.

```
Issue is only for jest it was working for karma Jasmin.
  test('termsCreationModal form label text should be present and all required label should contain asterik class', () => {
    let termslbl = native.querySelector('#termslbl');
    let descriptionlbl = native.querySelector('#descriptionlbl');
    expect(termslbl?.textContent).toEqual('Name');
    expect(descriptionlbl?.textContent).toEqual('Description');
    expect(termslbl?.classList).toContain('asterik');
    expect(descriptionlbl?.classList).toContain('asterik');
  });
```

**Steps for Reproduction**
  1. Run single component which have quill module which verify description text.
  2. npm run test
  3. it gives /c/Program Files/nodejs/npm: line 44: 181 Segmentation fault "$NODE_EXE" "$NPM_CLI_JS" "$@"
  4. Other test cases are working, issue is for quill editor module cases.
  5. Expected behavior:
  6.  It should pass because it was passed in karma Jasmin

**Actual behavior:**
Getting /c/Program Files/nodejs/npm: line 44: 181 Segmentation fault "$NODE_EXE" "$NPM_CLI_JS" "$@"

**Platforms:**
  Window 11

**Version:**
  Node -> v18.12.1
  Angular 15
  Jest & Web Runner:
  "jest": "^29.7.0"
  "jest-preset-angular": "^13.1.2"

**Tried**
  1. Node version updated but it does not work
  2. Delete node_modules and try installing again it also no work.
  3. By Passing mock object of quill inside test it also not work.

**Comment by KillerCodeMonkey** [comment]
in general that error indicates that your node process is running out of memory.
Did you tried something to increase the memory for the tests?

And please provide a minimal reproduction repo. so the best would be create a new angular 15 project add the quill module and a simple jest test and check if it is working

**Comment by KillerCodeMonkey** [comment]
just google for your error and you will get a bunch of results. 
Because you have enough memory on your machine does not mean that the node-process enough ;-).

https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes

**Comment by KillerCodeMonkey** [comment]
And in general when your QuillModule mock is working in our testcases then the problem is not really a problem with ngx-quill.

so a minimal reproduction repo would be nice. with quillmodule + jest

**Comment by shivkumar86** [comment]
It was not an issue in karma jasmine. It should relate to jest with ngx-quill. I will try to give more memory to node process and will check.

**Comment by KillerCodeMonkey** [comment]
or it depends on jest only... when you already mocked the quill module...
as the maintainer i am not here to build reproduction examples on my own, when you have a problem in your project...

so you can decide... build a minimal repo or solve your problems on your own...

**Comment by KillerCodeMonkey** [comment]
i added jest and a simple example test without mocking quillmodule to my demo repo:
https://github.com/KillerCodeMonkey/ngx-quill-example/actions/runs/6586327493/job/17894455403

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/default/default.component.spec.ts

no error and problems, so i guess jest consumes to much memory.
maybe play around with jest configs - just run two test in parallel or "--runInBand".
