### ISSUE TITLE
Focus not visible on some elements of the toolbar

### ISSUE THREAD

**Issue by emma-one** [KillerCodeMonkey/ngx-quill#1760]
I'm using ngx-quill for a project but have some issue with the visible focus on elements of the toolbar.
The problem is on the elements with a select with option like the selectors for colors, headers...

I can't get arround where and how in the code the visible focus is set in the visible span.
I understand that the select/option is hidden and a pretty display is made.

On the live demo it works fine, but not on my project, maybe we overrules something or overwrite some css but as I can't understand where the visible focus, I can't even have a lead.

**Comment by KillerCodeMonkey** [comment]
with out sharing your code nobody can help you. sure maybe you have some style overridings. just check the browser dev console and the styles for the toolbar/editor.

there you see from which css the styling is coming from and you can even active element states like "focus" "active" "hover".

**Comment by KillerCodeMonkey** [comment]
i guess it comes from your system/browser style when an element gets the ":focus-visible" state?

i am using firefox
![Screenshot_20231020_114931](https://github.com/KillerCodeMonkey/ngx-quill/assets/2264672/93fefe38-6126-43c9-85e4-e6a00a1c1f2c)

**Comment by emma-one** [comment]
Thanks for your help :)
In fact I had rules in my project as `outline: none` and therefore, I could not have the default outline set by browser.

Still need to figure out how to stillizing according to the graphical charter of my project, but I'll do it on my own.
Thanks again for your time, have a great day

**Comment by emma-one** [comment]
I spoke too fast, but I'll figure on myself. Will post a comment on a resolution here.

**Comment by KillerCodeMonkey** [comment]
Noice :)

emma-one ***@***.***> schrieb am Fr., 20. Okt. 2023, 13:22:
