### ISSUE TITLE
Selected line-height option does not show as selected in dropdown.

### ISSUE THREAD

**Issue by maulikprajapati** [KillerCodeMonkey/ngx-quill#1764]
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/16587174/2ee5e07c-4a99-4c23-bca1-37e2d8463b5d)
In above image, The applied line height is 2.5 but it shows 1 as default option is 1.

**Comment by KillerCodeMonkey** [comment]
And? i guess you build your own toolbar, since there is no default quilljs option about line-height.

So i guess your custom toolbar implementation is wrong.
