### ISSUE TITLE
Ability to open enlarged image when clicked

### ISSUE THREAD

**Issue by alicelebidev** [KillerCodeMonkey/ngx-quill#1766]
Hello,

Thanks for your hard work on the ngx-quill solution.

Is there an ability to open stored images when you click on them such that they're enlarged? Please see the example with this [link](https://inboxs.canny.io/changelog/keyboard-shortcuts).

I use the 'object' format to store the output of ngx-quill where the image is stored in base64 format.

Many thanks,
Ali Celebi

**Comment by KillerCodeMonkey** [comment]
This is Not Part of default quilljs. You could extend the Image Blot and add your custom functionality or add a clicklistener on the quilleditor, check if the node is an image and Do your logic
