### ISSUE TITLE
Update form value when link is removed using toolbar button

### ISSUE THREAD

**Issue by dana-c0914** [KillerCodeMonkey/ngx-quill#1769]
Hi. First of all, thanks for maintaining this component! 

Second, the quill editor seems to support removing a link by using again the link format button from the toolbar, but by using that, the form control value doesn't get updated.

Removing the link using the 'Remove' from the tooltip that appears next to a link, works as expected. I would expect that also removing it from the toolbar would update the value of the control.

You can find a reproduction case here: https://codesandbox.io/p/sandbox/broken-brook-87nhsz. 
Steps:
1. select 'link' text from the editor
2. click the link button from the toolbar 
3. check console/value of the form

After step 2, the editor no longer shows the 'link' text as a link.
After step 3, there is no change logged in the console/the value of the form control remains the same.

**Comment by KillerCodeMonkey** [comment]
Problem seems to be related to quilljs.
any change through the toolbar should be triggered as "user". but if you remove the link over the toolbar it is triggered by quilljs with "api".

Per default ngx-quill just recognize changes from source "user" as model or control changes.

You can try to use the "trackChanges" config/input to track all changes of quilljs, even if it is "silent" or "api"
