### ISSUE TITLE
Quill toolbar dropdowns are within mat-form-field because of overflow

### ISSUE THREAD

**Issue by richardsengers** [KillerCodeMonkey/ngx-quill#1772]
It's easy to reproduce, go to the demo
https://killercodemonkey.github.io/ngx-quill-example/

remove the two angular images and select the font-size dropdown.

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/810038/9b1d2ed4-0fd7-451f-9b17-1a5054a5fc16)

It is possible to remove the overflow from the form-field but when you have 2 quill editor, the menu goes behind the second mat-form-field

**Comment by KillerCodeMonkey** [comment]
and yes you can just style the editor as like, e.g. set `overflow: auto;` for `.mdc-text-field`

**Comment by richardsengers** [comment]
For those who are interested, change the property will-change to unset within the .mdc-text-field 
Otherwise all other form fields will be placed on top of the toolbar menu
