### ISSUE TITLE
Can't de-select toolbar option

### ISSUE THREAD

**Issue by AdrianQJohnson** [KillerCodeMonkey/ngx-quill#1773]
**Expectation**
Given user selects an option on the toolbar (i.e. Strikethrough)
When the user selects the option again
Then the option should be deselected

**Reality**
Given user selects an option on the toolbar (i.e. Strikethrough)
When the user selects the option again
Then the option remains selected

**Comment by KillerCodeMonkey** [comment]
Quick checked it in the live Demo and it works like expected.

Type something, select the Word, click strike and strike again. It is toggeling the Format.

Android 14, Firefox and Chrome.

Am 20. November 2023 20:46:54 MEZ schrieb Adrian Johnson ***@***.***>:

**Comment by AdrianQJohnson** [comment]
Just verified that you are correct in the demo. Do you happen to know what could be causing the issue locally?

**Comment by KillerCodeMonkey** [comment]
Maybe you have a js error in your Implementation. Just check your Browsers JS console for warnings and errors.

**Comment by AdrianQJohnson** [comment]
Not seeing any errors. The only difference I _could_ have is that I'm not using formControl.

**Comment by KillerCodeMonkey** [comment]
i have examples for many use cases in the live demo. it is even working for NgModel and without any "form" handling. It working as well.

maybe checkout my demo repo and start it locally to find the difference.
Or create a minimal reproduction repository/demo.

**Comment by AdrianQJohnson** [comment]
Think I found the real issue (locally), but don't know the cause. When you click the option's box, it deselects, but when you click the letter in the box, it doesn't. I have started from scratch with no modifications to the quill-editor and even changed my versions of ngx-quill, and am still having the issue. 

Does that sound like an issue that you are familiar with?

**Comment by KillerCodeMonkey** [comment]
nope not to me.

**Comment by KillerCodeMonkey** [comment]
an updates?

**Comment by KillerCodeMonkey** [comment]
Hallo?
