### ISSUE TITLE
code block doesn't work in a fresh project

### ISSUE THREAD

**Issue by its-dibo** [KillerCodeMonkey/ngx-quill#1779]
when you press the code icon, the code block appears for a second and disappears immediately with this error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at Scroll2.update (quill.js:4401:22)
    at MutationObserver.<anonymous> (quill.js:7191:19)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at _Zone.runGuarded (zone.js:139:47)
    at MutationObserver.<anonymous> (zone.js:123:29)
```

**steps for reproduction:**
1- create a new Angular project v17 and enable ssr
2- install quill, ngx-quill, @types/quill
3- import `QuillModule`
4- place `<quill-editor></quill-editor>` without any inputs in app.component.html (no routing is needed)

**additional info:**
- creating the same reproduction but without SSR, it worked as expected

**Comment by KillerCodeMonkey** [comment]
i did it and it worked..

https://github.com/KillerCodeMonkey/angular-ngx-quill-ssr
![Screenshot_20231211_182145](https://github.com/KillerCodeMonkey/ngx-quill/assets/2264672/4138bc75-c2b9-47cd-b7ac-dd80d9f79e89)

**Comment by its-dibo** [comment]
same issue
the issue is with the 'code-block' button, when you click it it appears for a moment and Immediately disappears. other buttons work fine

https://github.com/KillerCodeMonkey/ngx-quill/assets/57308531/a3b75c35-8811-41fc-ada6-0fe416e8c8f0

**Comment by KillerCodeMonkey** [comment]
can not reproduce this... it is working for me in chrome and firefox.
maybe try a different clean browser without the grammarly plugin. this is causing issues with quilljs

**Comment by its-dibo** [comment]
I really really appriciate your effort, you saved my day 
the issue can be safely closed now.

**for reference:**
this issue happens only when you build and serve as ssr, not with `ng serve`.
and it cause by a browser extension (as suggested by @KillerCodeMonkey ) called "Pieces"  which allows you to save code snippets.
