### ISSUE TITLE
Ommiting theme option for easier customizations

### ISSUE THREAD

**Issue by edmundojr** [KillerCodeMonkey/ngx-quill#179]
I'm looing to omit the theme option so I have a clean slate to style my toolbar. `ngx-quill` sets the theme by default to `snow`, even if I omit the option.

From [Quill's documentation](https://quilljs.com/guides/how-to-customize-quill/#themes):

> If you would like to drastically change UI interactions, you can omit the theme configuration option, which will give you an unstyled Quill editor.

I think the issue is there because ([line 172 of quill-editor.component.ts](https://github.com/KillerCodeMonkey/ngx-quill/blob/develop/src/quill-editor.component.ts#L172)):

```javascript
theme: this.theme || 'snow',
```

How can I reset the theme option with ngx-quill? Is there any way to do that?

Thank you!

**Comment by KillerCodeMonkey** [comment]
I think If You style the editor, You should create a simple custom quill
Theme and Pass it to quill?

Therefore You have themes im quill ;)

Edmundo Santos <notifications@github.com> schrieb am Fr., 11. Mai 2018,
15:37:

**Comment by KillerCodeMonkey** [comment]
checkout https://quilljs.com/docs/themes/#themes

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
aaaand did you solved it with css?

**Comment by edmundojr** [comment]
@KillerCodeMonkey I kind of fixed it by overriding the CSS – it's not the best solution though, as instead of just writing clean CSS (something that's possible with the Quill), I instead wrote lots of CSS to override the original rules.  To replace the SVG icons on the toolbar I used `display: none` and added new ones via background image 👍
