### ISSUE TITLE
Import Seem is broken

### ISSUE THREAD

**Issue by puneetxp** [KillerCodeMonkey/ngx-quill#1792]
On ng serve or build i facing this issue.
node_modules/ngx-quill/lib/quill-editor.component.d.ts:1:21 - error TS2614: Module '"quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "quill"' instead?

1import QuillType, { Delta } from 'quill'

can work perfect with 

import Delta from 'quill';
import QuillType from 'quill';
May be this bug related to old ts but fix is easy and don't have any side-effect. I appreciate if it is fix asap.

Our Project is angular 17 updated.
So it probably not related to angular version.
Thank Dev.

**Comment by KillerCodeMonkey** [comment]
no its not broken, just install correct quill typings.

PS: please use issue search first.
