### ISSUE TITLE
Question related to quill-emoji

### ISSUE THREAD

**Issue by haykoaghababyan** [KillerCodeMonkey/ngx-quill#1795]
I have enabled quill-emoji module, why I don't get the emoji when calling editor.getText() function, is there any solution to make the emoji also embedded in the text,

**Comment by KillerCodeMonkey** [comment]
getText means get text and all html is stripped, so with getText there is no chance to grab it.

try getting the full content as json/object where you can easier parse for custom formats/contents.

**Comment by haykoaghababyan** [comment]
thanks

**Comment by KillerCodeMonkey** [comment]
i will close this issue for now. :)
