### ISSUE TITLE
Inline vs class

### ISSUE THREAD

**Issue by zrilo** [KillerCodeMonkey/ngx-quill#18]
Hi,

I would like to set my ngx-quill editor to inline styles instead of classes

I am aware of this: http://quilljs.com/playground/#class-vs-inline-style

I have attempted to do this within the constraints of the ngx-quill editor but it always saves as classes instead of inline style

Could you please help

Thanks

**Comment by KillerCodeMonkey** [comment]
you can do it like in the example, but instead of accessing "Quill" directly you can import it.

Look in the ngx-quill-example repo:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts

Example to use div blocks instead of p-tags:
```
// override p with div tag
import * as Quill from 'quill';
const Parchment = Quill.import('parchment');
let Block = Parchment.query('block');

Block.tagName = 'DIV';
// or class NewBlock extends Block {}; NewBlock.tagName = 'DIV';
Quill.register(Block /* or NewBlock */, true);
```

There you see the import of Quill an the usage of `Quill.register`. So everything you need :).
You can do this for example in your base-component so that all uses of quill editor behave the same.

**Comment by zrilo** [comment]
Cheers, worked perfectly.


As a suggestion for possible improvement, it would be nice to specify whether you wanted style or classes via an input on the editor component.


Thanks

________________________________

**Comment by KillerCodeMonkey** [comment]
yeah the problem is that another developer asks if i could implement a better way to add custom fonts, and so on.

So everything you have to directly configure through Quill will do not make it in ngx-quill ;)

**Comment by andlcool** [comment]
Thanks. Was following your example and it does work.

Any idea where to get the list of attributors that we can import. I was looking at the indent function but couldn't figure out how to make the styling inline. Thanks.

**Comment by KillerCodeMonkey** [comment]
I do not know this exactly. But you can take a look in the quilljs repository:
all the parchment stuff lives here: https://github.com/quilljs/quill/tree/develop/blots

**Comment by dzena** [comment]
Hello,
I am a bit confused. In case of adding a new font or use inline styling instead class, we need to change HTML (in case of adding a font, we need to access the `<select>` tag where fonts are listed as options and CSS code as well to add a new font) code of the quill. I don't know how do I access and change the original HTML.
It is not enough to do only:
`import * as Quill from 'quill';

let FontAttributor = Quill.import( 'formats/font' );
FontAttributor.whitelist = [
  'sans serif', 'serif', 'monospace', 'roboto'
];

let SizeStyle = Quill.import( 'attributors/style/size' );

Quill.register( FontAttributor, true );
Quill.register( SizeStyle, true );`

Could somebody share a code snippet?

**Comment by KillerCodeMonkey** [comment]
i think you have to build up your toolbar on your own:
http://quilljs.com/playground/#custom-fonts

**Comment by dzena** [comment]
I was afraid also. That is potentially a lot of code. e.g. In the API I don't see how can I get all of the available colours. So that means i need to write all of them manually. And I am afraid that there are some other similar cases as this one (where i need to specify a lot of options manually).
Thanks for the quick feedback. :)

**Comment by KillerCodeMonkey** [comment]
in any other case: please ask such question in the quilljs repository.
I only build this wrapper angular stuff and i do not know very much about how to configure or how to get quill specific stuff. Sounds strange, but so it is :D

**Comment by dzena** [comment]
Understand. Thanks again.
Cheers :)

**Comment by neural22** [comment]
@KillerCodeMonkey I'm trying to use the style inline. As suggested I tried to do:
```
import * as Quill from 'quill';
let SizeStyle = Quill.import( 'attributors/style/size' );
Quill.register( SizeStyle, true );
```
but Quill.import return me an error (Quill is undefined). Then I tried use this code
```
const Quill = require('quill');
let SizeStyle = Quill.import( 'attributors/style/size' );
Quill.register( SizeStyle, true );
```
But now the change of the font size is broken.
Do you have any idea about what is going on?

**Comment by KillerCodeMonkey** [comment]
@neural22 are you using @types/quill?

require should be avoided :)

**Comment by neural22** [comment]
@KillerCodeMonkey I know require is to be avoided.. it was just a shot. 
import * as Quill from 'quill'; does not work for me... so I don't know what to do

**Comment by KillerCodeMonkey** [comment]
are you using @types for quill? check my last comment ;)

**Comment by neural22** [comment]
Thanks for your comment @KillerCodeMonkey , I inserted "@types/quill": "1.3.3" in my dependencies but nothing is changed.
with 
```
import Quill from 'quill';
let SizeStyle = Quill.import( 'attributors/style/size' );
Quill.register( SizeStyle, true );
```
I receive that error:
<img width="738" alt="screen shot 2018-04-23 at 11 58 45" src="https://user-images.githubusercontent.com/10474831/39120205-170c8d9e-46ee-11e8-973e-a32db155d081.png">

**Comment by KillerCodeMonkey** [comment]
you need to read my comment carefully --> `import Quill from 'quill'` without types.
and if you are using them, then:

```
import * as QuillNamespace from 'quill';
let Quill: any = QuillNamespace;
```

it is important to override the namespace with any type :)

**Comment by KillerCodeMonkey** [comment]
this should be asked in quilljs repo. never tried it.
but my be you need to change the existing sizes like i did with the fonts:
```
// Add fonts to whitelist
var Font = Quill.import('formats/font');
// We do not add Aref Ruqaa since it is the default
Font.whitelist = ['mirza', 'aref', 'sans-serif', 'monospace', 'serif'];
Quill.register(Font, true);
```

**Comment by forty6and2** [comment]
Hey, I got the same problem as @neural22. I've checked out the https://github.com/KillerCodeMonkey/ngx-quill-example project to see if it works (it does). I then compared the example project with the one I'm working on and it seems that i have finally got it to work. I have added the @types as a dependency (not as dev!) and then used
```
import * as QuillNamespace from 'quill';
let Quill: any = QuillNamespace;
```

So I ended up with something like this:

```
"dependencies": {
   ...
    "@types/quill": "^1.3.3",
    "ngx-quill": "^2.2.0",
    "quill": "^1.3.6",
   ...
},
```
Using inline style for alignment seems to also be working as expected:
```
let AlignStyle = Quill.import('attributors/style/align');
Quill.register(AlignStyle, true);
```

Maybe this helps someone out there ;)

**Comment by neural22** [comment]
many thanks @forty6and2 it worked for the alignment, still not working for the font size... probably there's a bug somewhere. At least now I know I'm doing the right thing.

**Comment by maniwadhwa26** [comment]
@neural22 
I think Port for TypeScript is having some king of Bug! Anyway I was able to find a work around. Following worked for me - 

In Component File,  I defined the default Modules (defaultModules) for Toolbar but with replaced **'size'** values.

```
export class AppComponent {
 
  quillValue;
  emptyArray = [];
  defaultModules = {
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'],        
      ['blockquote', 'code-block'],
      [{ 'header': 1 }, { 'header': 2 }],               
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      [{ 'script': 'sub'}, { 'script': 'super' }],      
      [{ 'indent': '-1'}, { 'indent': '+1' }],          
      [{ 'direction': 'rtl' }],                         
      [{ 'size': ['10px', false, '18px', '32px'] }],  
      [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
      [{ color: this.emptyArray.slice() },{ background: this.emptyArray.slice() }],        
      [{ 'font': [' sans-serif', 'monospace', 'serif']}],
      [{ 'align': '' }],
      ['clean'],                                         
      ['link', 'image', 'video']                        
    ]
  };
```
New Values ==>

`'size' =  ['10px', false, '18px', '32px']`
  
Then in the Constructor while registering new Size Style, add Pixel Values here as well in the **whitelist** array.

```
let SizeStyle = quill.import( 'attributors/style/size' );
SizeStyle.whitelist =  ['10px', false, '18px', '32px'];
quill.register( SizeStyle, false );
```

Now we need to tell quill editor to use our defined modules. In Html File, add [modules] property to quill-editor in the following way - 

`<quill-editor [(ngModel)]="quillValue"  [modules]="defaultModules"></quill-editor>`

Almost Done ! Just one last thing. In global style.css file or any component css file ( your wish), add the following  - 

```
.ql-picker.ql-size .ql-picker-label[data-value="10px"]::before,
.ql-picker.ql-size .ql-picker-item[data-value="10px"]::before {
    content: 'Small' !important;
}
.ql-picker.ql-size .ql-picker-label[data-value='']::before,
.ql-picker.ql-size .ql-picker-item[data-value='']::before {
    content: 'Normal';
}
.ql-picker.ql-size .ql-picker-label[data-value="18px"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="18px"]::before {
    content: 'Large' !important;
}
.ql-snow .ql-picker.ql-size .ql-picker-label[data-value="32px"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="32px"]::before {
    content: 'Huge' !important;
}

```
This CSS will Add the Small,Normal,Large,Huge values in the Dropdown of **Size Select** in the toolbar.

You can check out the working of the same at the following repo - 
https://github.com/maniwadhwa26/angular-test-project

**Comment by jimisens** [comment]
I just found this, if it still works for someone. It works

```
export function quillInlineStyle(quill:any) {
  const AlignStyle = quill.import('attributors/style/align');
  const BackgroundStyle = quill.import('attributors/style/background');
  const ColorStyle = quill.import('attributors/style/color');
  const DirectionStyle = quill.import('attributors/style/direction');
  const FontStyle = quill.import('attributors/style/font');
  const SizeStyle = quill.import('attributors/style/size');
  quill.register(AlignStyle, true);
  quill.register(BackgroundStyle, true);
  quill.register(ColorStyle, true);
  quill.register(DirectionStyle, true);
  quill.register(FontStyle, true);
  quill.register(SizeStyle, true);
}
```

**Comment by saiyaff** [comment]
@jimisens and where or how have you called this function `quillInlineStyle(quill)`?

**Comment by ek1mb4** [comment]
> import * as Quill from 'quill';

Was looking for this solution. Thanks. my day is saved.
