### ISSUE TITLE
Suggestion to update the README

### ISSUE THREAD

**Issue by djfishe** [KillerCodeMonkey/ngx-quill#180]
Hi,
I'm looking into using custom-options to add a dropdown with custom font sizes to the editor. However I couldn't really find an example for this yet, despite that in the README there is this line:

> use custom-options for adding for example custom font sizes (see example in demo.html)

I couldn't find "demo.html". I would suggest to update the README as it's a bit misleading.

Thank you.

**Comment by KillerCodeMonkey** [comment]
feel free to fix/extend the readme with a PR ;)

**Comment by KillerCodeMonkey** [comment]
i removed the "demo" part. it was an artifact of the ng-quill repo readme

**Comment by djfishe** [comment]
Thanks!
