### ISSUE TITLE
Loading Syntax Highlighting From NPM Module

### ISSUE THREAD

**Issue by KeithGillette** [KillerCodeMonkey/ngx-quill#1800]
The [Quill 2 documentation shows](https://quilljs.com/docs/modules/syntax#use-npm-package) that to load a syntax formatter like HighlightJS, one should pass a configuration with an `hljs` property on `modules`:

```
{
  modules: {
    syntax: { hljs },
  },
}
```

However, [the typings for `ngx-quill` indicate the property is called `highlight`](https://github.com/KillerCodeMonkey/ngx-quill/blob/5cb94553f778c4c32c1f2e15edff0a813cdb659a/projects/ngx-quill/config/src/quill-editor.interfaces.ts#L56), which does not seem to work:
```
{
  modules: {
    syntax?: boolean | { highlight: any },
  },
}
```

**Comment by KillerCodeMonkey** [comment]
Dang it. I missed that one. Feel free to send a pr :)

Am 15. Februar 2024 18:55:06 MEZ schrieb Keith Gillette ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
should be working with the latest version 25.0.3

when you use { syntax: true } i guess you need to provide highlight.js on the global scope

**Comment by KeithGillette** [comment]
I confirm Highlight.JS now works in `ngx-quill@25.0.3` without providing it on the global scope using an explicit import and this `{ syntax: { hljs: hljs }` syntax. Thanks for the quick fix, @KillerCodeMonkey!
