### ISSUE TITLE
Expose setSelection

### ISSUE THREAD

**Issue by RupertAvery** [KillerCodeMonkey/ngx-quill#1803]
I want to be able to set focus to a dynamically created quill editor.

I can't seem to find the setSelection api on the component. Am I missing something?

https://quilljs.com/docs/api#setselection

**Comment by KillerCodeMonkey** [comment]
just listen to the `onEditorCreated` output and grab the editor instance from there :)https://github.com/KillerCodeMonkey/ngx-quill?tab=readme-ov-file#outputs

**Comment by KillerCodeMonkey** [comment]
i will close this, because this is the way to get the quill editor instance

**Comment by KillerCodeMonkey** [comment]
In quillv2 it should be part of the module itself. For quill v1 install @types/quill v1.x



Am 21. Februar 2024 16:39:42 MEZ schrieb David Khristepher Santos ***@***.***>:
