### ISSUE TITLE
Quill's incompatibility with SSR (Angular 17 default)

### ISSUE THREAD

**Issue by rommcb** [KillerCodeMonkey/ngx-quill#1804]
Hi there,

I tried to use ngx-quill on my Angular 17 project (with SSR enabled by default) and had issues using Quill's classes and methods:

```
 [vite] Error when evaluating SSR module /chunk-JU6QDXW2.mjs:
|- ReferenceError: document is not defined
    at eval (.../node_modules/quill/core/emitter.js:7:3)
    at Array.forEach (<anonymous>)
    at eval (.../node_modules/quill/core/emitter.js:6:8)
    at async instantiateModule (.../node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50861:9)
```
I had to disable SSR...
Is this something worth mentioning somewhere?

**Comment by KillerCodeMonkey** [comment]
it should work out of the box, but if you import quill-js directly somewhere in your code then you need to add special handling for it.

**Comment by KillerCodeMonkey** [comment]
if you need the quill instance you can load it via quill.service
