### ISSUE TITLE
Unable to update html from controller

### ISSUE THREAD

**Issue by dodomui** [KillerCodeMonkey/ngx-quill#1808]
`<quill-editor class="full-width" format="html" sanitize="true" [(ngModel)]="msg></quill-editor>`
`<quill-editor format="html" sanitize="true" formControlName="msg"></quill-editor>`

When set format to 'html', unable to set value from component, it always show blank.
Tried set sanitize to both true and false, also ried domSanitizer from component but none of it works, all showing blank.

It works only when I set format to 'text', but this doesn't serve my purpose, I need pass 'html' format.

`this.form.controls.msg.setValue(this.domSanitizer.bypassSecurityTrustHtml('test'))`

**Comment by KillerCodeMonkey** [comment]
works great in my demo:

Code: https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/components/format-html
Demo: https://killercodemonkey.github.io/ngx-quill-example/#html

**Comment by dodomui** [comment]
@KillerCodeMonkey I'm working with Ionic Angular. Try the same method as your one but no luck still showing blank.
😭😭😭😭

`this.form.get('msg').patchValue('<p>test</p>');`

**Comment by dodomui** [comment]
Problem solved.
It was because I use wrong version combination, quilljs@1 with ngx-quill@25.
Solved by using quilljs@1 with ngx-quill@24.
