### ISSUE TITLE
Some addBinding keys don't work anymore in v25

### ISSUE THREAD

**Issue by Eraldo** [KillerCodeMonkey/ngx-quill#1810]
Context: I recently upgraded to v25x aka Quill v2 and since some of my keyboard shortcuts stopped working.

Example:
```ts
    this.quill?.keyboard.addBinding(
      {
        key: "escape", // ESC
      },
      () => {
        console.log("Does not work in v25 anymore");
      }
```

First I thought that there is something wrong with the config or other things on my side, however if I simply replace the key with one that does work, it prints the message just fine when I press the combination.

I have not fully understood which keys work and which do not.

Works:
```ts
{ key: "s", shortKey: true }
{ key: "e", shortKey: true }
{ key: "7", shortKey: true, shiftKey: true }
{ key: "§", shortKey: true }
```

Does not work anymore:
```ts
{ key: "l", altKey: true, shiftKey: true }
{ key: "k", altKey: true, shiftKey: true}
{ key: "1", shortKey: true, altKey: true}
{ key: "q", altKey: true}
{ key: "escape", shortKey: true }
{ key: "escape" }
```

So far it seems anything involving the "altKey" and the "escape" key don't work anymore. 🤷 

Any ideas? Insights? Reasoning?

PS: Thanks for the work of upgrading the code base to v2. :)

**Comment by Eraldo** [comment]
You are right, it is a general Quill v2 issue.
I created a stackblitz to confirm that.

Moved the issue to a better location based on your feedback: https://github.com/quilljs/quill/issues/4030

Thanks! 🙏

**Comment by KillerCodeMonkey** [comment]
Thank you :).

Keep me in the loop when you get an answer/solution



Am 28. Februar 2024 18:25:27 MEZ schrieb Eraldo Energy ***@***.***>:
