### ISSUE TITLE
Html export : Unordered lists are saved as Ordered lists

### ISSUE THREAD

**Issue by PaulDesiles** [KillerCodeMonkey/ngx-quill#1813]
Since quillv2 it seems it uses only `<ol>` elements for its internal rendering, even when displaying unordered lists.

As described is this quilljs issue, it's therefore recommended to use `getSemanticHTML()` instead of `innerHtml` to access an exported state :
https://github.com/quilljs/quill/issues/3957#issuecomment-1945538748

From my understanding this change is not yet made in ngx-quill, at least in the valueGetter, line 165 of [quill-editor](https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.ts)

To reproduce :
- visit the demo page : https://stackblitz.com/edit/stackblitz-starters-yqbbgf?file=src%2Fmain.ts
- type an unordered list in the top editor
- the viewer based on the formControl value is an ordered list

thanks

**Comment by KillerCodeMonkey** [comment]
If this is an urgent one Feel free to send a pr :)

Am 8. März 2024 17:04:03 MEZ schrieb PaulDesiles ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
@PaulDesiles i switched to `getSemanticHTML`. it is released in v25.1.1
Feel free to close the issue, if it is working for you.

**Comment by PaulDesiles** [comment]
Nice ! the problem is fixed on my use case :)
Thanks a lot for your quick update !
