### ISSUE TITLE
Chrome browser deprecation warning

### ISSUE THREAD

**Issue by alicelebidev** [KillerCodeMonkey/ngx-quill#1816]
Currently using the ngx-quill package version 16.2.1

Chrome browser throws the following warning when `<quill-editor>....</quill-editor>` is used on a webpage.

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/13241089/e637df62-3700-40f4-8f1f-65493d098943)

**Comment by KillerCodeMonkey** [comment]
This is coming from quilljs itself. So nothing to fix from myside here.

Only way is to Upgrade to latest Version (using angular 17 and quilljs v2)

Am 12. März 2024 20:38:25 MEZ schrieb Ali Celebi ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
https://github.com/quilljs/quill/issues/3806
