### ISSUE TITLE
Keyboard module, bindings , 

### ISSUE THREAD

**Issue by haykoaghababyan** [KillerCodeMonkey/ngx-quill#1817]
I use this configuration, to handle press enter key.
   ```
keyboard: {
        bindings: {
          enter: {
            key: 13,
            handler: () => {
              // code
            },
          },
        },
      },
```
 
In v1 it was working, after upgrading from v1 to v2 it started not working

I'm currently using the latest versions
   ngx-quill - "^25.1.1",
   quill - "^2.0.0-rc.2"
   
   Has something changed in the new version?

**Comment by haykoaghababyan** [comment]
I tried this way too, it didn't work

```
 onCreated(editor): void {
    editor.getModule('keyboard').addBinding({ key: 'Enter', shiftKey: null }, () => {
     // code
    });
  }
```

**Comment by KillerCodeMonkey** [comment]
Check quilljs issues first please. There are some bindings not supported or already used by quill, now

Am 13. März 2024 14:51:07 MEZ schrieb Hayk Aghababyan ***@***.***>:

**Comment by haykoaghababyan** [comment]
Ok thanks I will check it in main quill
