### ISSUE TITLE
Customized button without icon

### ISSUE THREAD

**Issue by jggprudencio** [KillerCodeMonkey/ngx-quill#182]
Hello!

I added a customized button to my toolbar like this:
```
const BlockEmbed = Quill.import('blots/block/embed');
class DividerBlot extends BlockEmbed { }
DividerBlot.blotName = 'divider';
DividerBlot.tagName = 'hr';
Quill.register(DividerBlot);
...
this.modules = {
            toolbar: {
                container: [
                   ['bold', 'italic', 'underline'],
                   ...
                   ['hr'],
                 ]
              };
```
But the button is added on the toolbar without an icon. How can I solve this?

**Comment by KillerCodeMonkey** [comment]
Check the Dom. Quill adds css Classes for each Button. Style it with that.
And Use e.g. The css content Attribute to add Text or Symbols.

jggprudencio <notifications@github.com> schrieb am Do., 17. Mai 2018, 20:36:
