### ISSUE TITLE
 How to Remove Formatting Automatically When Copying Text?

### ISSUE THREAD

**Issue by ivanadrzaic** [KillerCodeMonkey/ngx-quill#1823]
Hello,

I have a question about copying and pasting from different websites.

When I copy text, I want it to automatically remove all formatting without having to click "clean" Currently, the background is visible, along with **bold** and other formats.

Thank you.

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/33715821/e111a63d-27ba-42de-a626-fca1506fbd59)

```
provideQuillConfig({
        modules: {
            syntax: false,
            toolbar: [
                ['bold', 'italic', 'underline', 'strike'],
                // ['link'],
                // ['blockquote', 'code-block'],
                // [{ 'header': 1 }, { 'header': 2 }],
                // [{ 'size': ['small', false, 'large', 'huge'] }],
                // [{ 'list': 'ordered' }, { 'list': 'bullet' }],
                // [{ 'color': [] }, { 'background': [] }],
                // [{ 'font': [] }],
                // [{ 'align': [] }],
                ['clean'],
            ],
            clipboard: {
                matchers: [
                                     
                ]
            }
        },
    }),
```

**Comment by KillerCodeMonkey** [comment]
there is nothing special happening. it is the same behavior as would you use native quilljs.
i will not change the default behavior of quilljs there.

Check here. https://quilljs.com/playground/snow
if it is there working that way as well.

what you can do is using quill api https://quilljs.com/docs/api/#removeformat .

so after pasting the onContentChanged event will be triggered with the delta. just use those information to directly remove the format from that delta range.
