### ISSUE TITLE
Formats not working in mat-quill implementation

### ISSUE THREAD

**Issue by ricochetbrown** [KillerCodeMonkey/ngx-quill#1825]
Do you have any examples of formats (e.g. ['bold', 'italic']) working within the mat-quill framework? It seems to just ignore them. Should I not use the mat-form-field wrapper?

**Comment by KillerCodeMonkey** [comment]
I only have what you find in the quill example repo.

There you can Format bold and italic?

**Comment by ricochetbrown** [comment]
Well it ended up being I didn't have quill all the way updated. Thanks for your quick response. It is working!

**Comment by KillerCodeMonkey** [comment]
Yes it is finally working to only allow specific Formats with quill v2 rc4 and latest ngx-quill release

Am 26. März 2024 20:58:33 MEZ schrieb Derrick Brown ***@***.***>:
