### ISSUE TITLE
zone.js:178 Uncaught TypeError: this.quillEditor.getSemanticHTML is not a function

### ISSUE THREAD

**Issue by ArishN** [KillerCodeMonkey/ngx-quill#1827]
i got this error on every key down in the text area  and i use ngx-quill latest version and quill version quill@2.0.0-rc.0

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/136902412/cad616cb-bd1d-458f-bb15-e16a54bc3b04)

**Comment by KillerCodeMonkey** [comment]
you should use rc.4 of quill when using latest ngx-quill version.

i decided to release ngx-quill versions with quill 2 support as ordinary releases and not on beta channel.

so it is a little bit confusing until quill 2 is final.

just check the releases page here on github what changed on each version.

**Comment by ArishN** [comment]
thankyou so much
