### ISSUE TITLE
Styling width by percentage is not working

### ISSUE THREAD

**Issue by olci34** [KillerCodeMonkey/ngx-quill#1831]
When I enter below styles value I got correct results:
[styles] = "{ height: '300px', width: '100px' }"

But When I use percentage for width as below, it does not work:
[styles] = "{ height: '300px', width: '100%' }"

Using Angular v15

**Comment by KillerCodeMonkey** [comment]
Depends how quill is styling the Editor and what the Editor component parent is styled.. if it is flexbox use flex 1 and so on

Am 1. April 2024 18:20:07 MESZ schrieb Murat Ogulcan Sahin ***@***.***>:

**Comment by olci34** [comment]
Thank you so much!
