### ISSUE TITLE
suppressGlobalRegisterWarning not working

### ISSUE THREAD

**Issue by Eraldo** [KillerCodeMonkey/ngx-quill#1836]
I have the following set in my `main.ts`
```
  providers: [
    provideQuillConfig({
      suppressGlobalRegisterWarning: true,
    }),
    ...
```

I still get a bunch of overwrite warnings in the console.

Example:
```js
quill Overwriting modules/imageDropAndPaste with class extends QuillImageDropAndPaste {
  constructor(quill, option) {
    super(quill, option);
    if (typeof option.autoConvert !== "boolean")
      option.autoConvert = true;
    this.quill = quill;
   …
```
<img width="639" alt="image" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/73378/18be7cd6-ec2a-490c-9583-2ef03d5d4ff4">

Version Context:
```
    "ngx-quill": "^25.1.3",
    "quill": "^2.0.0-rc.2",
    "quill-image-drop-and-paste": "^1.3.0",
    "quill-magic-url": "^4.2.0",
```

How can I get rid of these warnings?

**Comment by KillerCodeMonkey** [comment]
Can you please try to reproduce it with native quill?

it seems that the documentation is outdated https://quilljs.com/docs/api/#register
Maybe it does not exist anymore. Can not find any parameter for it in the source code

**Comment by KillerCodeMonkey** [comment]
i did a small research.
Can you try https://quilljs.com/docs/api/#debug and setting the level to "error" should hide all warnings.

**Comment by KillerCodeMonkey** [comment]
oh i see you can pass it to the quillConfig and the editor as well just pass the "debug" input/config

**Comment by KillerCodeMonkey** [comment]
@luin is this documentation still correct and up to date? https://quilljs.com/docs/api/#register

seems like register does not have a supressWarning parameter any more?

**Comment by luin** [comment]
The parameter still exists but in the source code its name is `overwrite`. You can try it in [Playground](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQAsAuBbANiAXCAHhggDcACCGAXgB0Q5i0B7AJzoD4CxiT2ap+BAM4BjFhAAOaMkJYja4aPGQArIRy6jxU9iAA0i2IiRq8IEUyhDpARwCuELFjJUyUOAHcyARQdOAFADkAMQMEMwsgXpkwPxkZBhMMHZYcEK4MXHxZMxMWABGAIYsGQDaWdlkpcBkKHCF8CVVAIzRAEzRAGaFWEJwALpkAL79ehXZpYH5eTBRZIHhPRAic4F2RixY0HCBo+PxkxAYhQDmO9GBFvAAtPlYTCIA1rtjUJV7b8Ov8RJYhSJwFAzOBNQIAYSYGAkTD6ZEKbzgEmWSBRUSyaDqGDgGUCQigTA8czAYDIrHm+Ts+TuO34QwAlABufj8ER-IRCMgAWQAnpykik4M0YkMWWyOTy+clUm1hcyoL5HFgkCw4CcINYQUFElK0mAMNzrtqBXMJfzUs06fwFU5lar1WhNYEjakhHqDc7zlzeWa4B0ciw7HA6SAhkA): try remove the `true` parameter and see the console.

**Comment by KillerCodeMonkey** [comment]
@Eraldo now i see it.

this `suppressGlobalRegisterWarning` only works when you are registering the modules as custom modules via the quillconfig or passing them to the editor component.

You see how to register them in the example repo with the counter module.
For third party libraries i can not handle it.

but like i said you can handle it by setting "debug" to error to only log errors

**Comment by Eraldo** [comment]
> this `suppressGlobalRegisterWarning` only works when you are registering the modules as custom modules via the quillconfig or passing them to the editor component.

I am registering my modules directly to the component.
I have the flag enabled in the global settings.

As suggested, I am now using debug setting.
Does not seem a very clean solution, but it works and that is better than nothing. Thanks.

Appreciation round...
Still very happy about your maintenance efforts - thank you so much, you're doing a wonderful job in my experience! 🙏🏽

**Comment by KillerCodeMonkey** [comment]
Okay please create a minimal repo or online example to reproduce the issue.

Because when passing your modules as "customModules" it should work.
