### ISSUE TITLE
modules is not working in quill-editor

### ISSUE THREAD

**Issue by Medmly20208** [KillerCodeMonkey/ngx-quill#1837]
I am trying to add mentions into my quill-editor but it's not working when I change format to text , it's working in when we have the default formai which is html but I need it for text , 
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/69359301/6ac2f76e-cc07-4e82-8765-3c13beeb4814)
  

it seems that it works fine but when I save to db , the mention don't get saved

**Comment by KillerCodeMonkey** [comment]
Text is text. And any special Format is not text because it is only represented with HTML.

Alternatively you can use json/object representation.

**Comment by Medmly20208** [comment]
thanks but I want to use text cause when I use html I have problems to save html in db , it gets changed somehow and I still didn't find any solution

**Comment by Medmly20208** [comment]
okay , thanks a lot I appreciate it
