### ISSUE TITLE
html not getting saved correctly

### ISSUE THREAD

**Issue by Medmly20208** [KillerCodeMonkey/ngx-quill#1838]
I am using ng-quill-editor with html format , I want to save html in database  ,but I got incorrect values for example in the editor I wrote this html tags 

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/69359301/654338b2-e075-4011-b9ff-da265faa93f1)

but the value that get saved in db is this 
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/69359301/c7e92734-abf5-42b9-be04-c1bf17b7cb53)

**Comment by KillerCodeMonkey** [comment]
But in the example it is working fine:
https://killercodemonkey.github.io/ngx-quill-example/

search for "Format - HTML"

so the editor returns correct data.
If the data is changed in your save process/db insert/update i can nothing do for you.

check if you have something that escapes html in your code.
And keep in mind quill only accepts allowed formats attributes and tags.

i do not even know how you mixed up p and div-tags.
In general it seems you try to display non quill html in a quill editor.

If i try to rebuild your example with my demo repo i get something like that:

```TS
  <p><img src="https://angular.io/assets/images/logos/angular/angular.svg"></p><p>Hello World</p>
```

**Comment by Medmly20208** [comment]
thanks for the explanation appreciate it

**Comment by KillerCodeMonkey** [comment]
if this answers your question, feel free to close the issue.

**Comment by kulitha** [comment]
> But in the example it is working fine: https://killercodemonkey.github.io/ngx-quill-example/
> 
> search for "Format - HTML"
> 
> so the editor returns correct data. If the data is changed in your save process/db insert/update i can nothing do for you.
> 
> check if you have something that escapes html in your code. And keep in mind quill only accepts allowed formats attributes and tags.
> 
> i do not even know how you mixed up p and div-tags. In general it seems you try to display non quill html in a quill editor.
> 
> If i try to rebuild your example with my demo repo i get something like that:
> 
> ```ts
>   <p><img src="https://angular.io/assets/images/logos/angular/angular.svg"></p><p>Hello World</p>
> ```

@KillerCodeMonkey Apologies for commenting this on a closed issue, but this technically matches the title. Please feel free to remove the comment if it's irrelevant.

I'm trying the ngx-quill example given in the https://killercodemonkey.github.io/ngx-quill-example/ and it seems like the latest versions of ngx-quill ( > v25.0.0 ) removes the line break tag `<br>` inside the `<p>` tag when the user enters a new line?

On ngx-quill v25.0.0 and quill 2.0.0-rc.0, if I enter a new line I get the HTML as:
`<p><br></p>`
I tried this on ngx-quill v25.0.0 and the latest quill version (2.0.0-rc.5), and it's still the same. This is how it has worked on older versions of ngx-quill as well. And the characters like single quotations and double quotations are given as they are.
`' "`

However, on ngx-quill v25.1.3 (also checked on v25.2.0) and on the ngx-quill-example, the HTML is given as 
`</p><p>`. Without the line break tag.
And the characters like single quotations and double quotations are given like this:
`<p>&#39; &#39;</p>`

Is this some configuration issue on my end? As I've written above, I tried with the quill 2.0.0-rc.0 and quill 2.0.0-rc.5, but only updating ngx-quill seem to trigger it.

**Comment by KillerCodeMonkey** [comment]
i guess it is because of this: https://github.com/KillerCodeMonkey/ngx-quill/issues/1813

the only way to retrieve the correct html from quill editor is using "getSemanticHTML" instead of just grabbing the innerhtml

**Comment by kulitha** [comment]
> i guess it is because of this: #1813
> 
> the only way to retrieve the correct html from quill editor is using "getSemanticHTML" instead of just grabbing the innerhtml

Got it. Thank you very much for the reply!
