### ISSUE TITLE
some props are not existing

### ISSUE THREAD

**Issue by its-dibo** [KillerCodeMonkey/ngx-quill#1839]
the [docs](https://github.com/KillerCodeMonkey/ngx-quill?tab=readme-ov-file#config-1) mentions `conig.strict`, but it seems that it has been [removed](https://github.com/KillerCodeMonkey/ngx-quill/blob/fc65ad5c7541e181296bb9a4df2f6a7f956d0ce6/projects/ngx-quill/config/src/quill-editor.interfaces.ts#L82)

**Comment by KillerCodeMonkey** [comment]
feel free to send a pr :)

**Comment by KillerCodeMonkey** [comment]
i removed it from the readme
