### ISSUE TITLE
Browser compatibility warnings

### ISSUE THREAD

**Issue by handja** [KillerCodeMonkey/ngx-quill#1842]
Hi, I'm using ngx-quill (version 25.3.2), quill (version 2.0.0) and Angular (version 17.3.5).

When a module using QuillModule is initialized, I get many warnings about browser compatibilities : 

> Module "source-map-js" has been externalized for browser compatibility.
> Module "path" has been externalized for browser compatibility.
> Module "url" has been externalized for browser compatibility.

<img width="1745" alt="Capture d’écran 2024-04-24 à 12 09 56" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/9036576/8d32f317-bd1a-43ce-a9b3-7a3c25c9a2ae">

This is an issue from Quill ? How can I remove these warnings ? 

Thx for you help

**Comment by KillerCodeMonkey** [comment]
any updates on this?

**Comment by handja** [comment]
Sorry I was working on others subjects.

Finally the error does not come from Quill, it's related to another library, so it's ok.
I thought that it was related to quill cause the other library is used on the same place, my bad.
