### ISSUE TITLE
Playwright's .fill() doesn't work in Firefox

### ISSUE THREAD

**Issue by colfin-96** [KillerCodeMonkey/ngx-quill#1844]
I'm not sure if this topic belongs here, or in a Playwright or Firefox forum, or if it is an issue with quill itself, so feel free to let me know.

When writing a UI test with Playwright, I was trying to fill the ngx quill editor with some text, using the _locator.fill()_ method. Visually, it worked, but internally the text was empty ("") and the text length was 0.

I have now found a workaround by replacing _.fill()_ with _.pressSequentially()_, which seems to work.

Here the first code I tried:
```ts
this._textArea.fill(text);
```

The workaround:
```ts
this._textArea.press('Control+a');
this._textArea.press('Backspace');
this._textArea.pressSequentially(text);
```
(pressing Control+a and Backspace is necessary as else it would just append the text)

Please note that this error only occurs in the combination Playwright + Firefox. 
In Playwright + Chrome it works fine.
In Firefox "production mode" it also works fine.
I didn't have the possibility to test this with native quill until now.

Kind regards,
Colin

**Comment by KillerCodeMonkey** [comment]
quilljs is using a contenteditable div not a classic input field/text area.

so the "fill" only seems to work, because the contenteditable allows to insert content directly by typing.

**Comment by KillerCodeMonkey** [comment]
try https://github.com/microsoft/playwright/issues/2297#issuecomment-631166745 ;-)
