### ISSUE TITLE
Adding "id" attribute to lists

### ISSUE THREAD

**Issue by pr4ctic** [KillerCodeMonkey/ngx-quill#1846]
Hey @KillerCodeMonkey 

I'm new to QuillJS, found your project and it's been of great help. I'm wondering, ¿have you ever tried adding an id attribute (or any other) to a list? It doesn't really matter if I add it to "ol" or "li" tag, the important part is getting them identified. I'm asking because I did it to "p" tags, but I haven't been able to sort it out for lists. 

Thanks in advance!

**Comment by KillerCodeMonkey** [comment]
Honestly... I neuer tried it.

My use cases for quill were very basic and since then I ty to maintain this little Baby.

But as far as I know allows quill only known tags and attributes.

Try to extend the list format/blot and allow the ID attribute

**Comment by pr4ctic** [comment]
Aight, thanks!
