### ISSUE TITLE
How to preserve white-space on QuillEditor

### ISSUE THREAD

**Issue by kasaharu** [KillerCodeMonkey/ngx-quill#1848]
When a string containing spaces is set in QuillEditor, the spaces are trimmed.
But when set to QuillViewHtml, spaces are not trimmed.

```typescript
@Component({...})
export class RichTextComponent {
  ...
  form = new FormControl('<p>     Hello world!</p>', { nonNullable: true });
}
```

```html
<quill-editor format="html" [formControl]="form"></quill-editor>

<div style="background-color: pink">
  <quill-view-html [content]="form.value" theme="snow"></quill-view-html>
</div>
```

<img width="710" alt="image" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/2771212/b9bbc9fb-5fa0-456a-8095-7bd532c84a96">

Here is a link to a sample application made with StackBlitzs.
https://stackblitz.com/edit/stackblitz-starters-frr2gw?file=src%2Fapp%2Frich-text%2Frich-text.component.html

Thanks in advance!

**Comment by KillerCodeMonkey** [comment]
Quillviewhtml just renders the HTML as it is like setting innerhtml. So white spaces are preserved.

With quill 2 the way the editor renders things changed, and the old hack to preserve whitespaces does not work anymore. Because of that the option is removed from ngx-quill.


You could try not to store HTML. Use the json/object representation. It is the recommended way, and maybe then the spaces are there.

**Comment by kasaharu** [comment]
Thank you for your comment.

We already have it stored in database as html, is there any way to migrate the format from html to json?

The method we are considering are as follows.
1. convert the data stored as html to json and set it in QuillEditorComponent
2. convert json data received from QuillEditorComponent to html

I would like to know how to convert from html to json and from json to html.
Or any other migration ideas?

**Comment by KillerCodeMonkey** [comment]
I think there is no easy way. Without using quill editor in the browser,

You could make a cut. Mark the content as HTML for all existing values in the database.

New entries will have json as type.
Based on that, Flag initialize the editor.

So you have fallback for old existing entries. 

You could even make it more complex, and if you save an old value to the DB, just convert it to json on front-end side and change the type in the db.

**Comment by kasaharu** [comment]
Thank you so much!
I understand.

**Comment by dmrickey** [comment]
@ozderko 
You're using that method how/when?

**Comment by ozderko** [comment]
@dmrickey I'm using ControlValueAccessor, so in your case you might need to add it somewhere else.
The preserveWhiteSpace() method is used inside the writeValue(). It's triggered when Angular sets an initial or external value via ControlValueAccessor. 

```
writeValue(value: string | null | undefined): void {
    const text = value || '';
    this._value = this.value ? text : QuillContentUtils.preserveWhiteSpace(text);
  }
```

**Comment by dmrickey** [comment]
> [@dmrickey](https://github.com/dmrickey) I'm using ControlValueAccessor, so in your case you might need to add it somewhere else. The preserveWhiteSpace() method is used inside the writeValue(). It's triggered when Angular sets an initial or external value via ControlValueAccessor.
> 
> ```
> writeValue(value: string | null | undefined): void {
>     const text = value || '';
>     this._value = this.value ? text : QuillContentUtils.preserveWhiteSpace(text);
>   }
> ```

I didn't look close enough before, but unfortunately this isn't functionally equivalent to the old behavior. This does not preserve line breaks.
I'd need something like `value.replaceAll('<p></p>', '<p><br></p>');` but that breaks the editor.
