### ISSUE TITLE
Editor bundles all HTML elements inside a <p> tag

### ISSUE THREAD

**Issue by SaurabhaArya** [KillerCodeMonkey/ngx-quill#1849]
Hi,

Recently migrated my angular project to v10 and was trying to implement `ngx-quill (ngx-quill -> v12.0.0 & quill -> v1.3.7)`.

It got implemented but one issue is that when I try to show HTML content inside it, after a point from where `<table>` element starts it bundles all the elements and content into a `<p>` tag.

How it should be:
<img width="570" alt="image" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/16134421/5b27e7b3-5257-407f-9c04-1c01a63fa457">

How it is coming:
<img width="580" alt="image" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/16134421/79c28d88-3eb5-4282-9df4-74d99892beca">

Here's the stackblitz [link](https://stackblitz.com/edit/angular-v12-wtbx8d?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,angular.json,src%2Fstyles.css). Apologies if the editor looks distorted, tried to fix it but not able to. If you scroll all the way down then the paragraph which has issue is there .

Thanks!!

**Comment by KillerCodeMonkey** [comment]
There is no support for such old versions. 
And quilljs v1 does not support out of the box.
All tags and stylings unknown to quill will be removed or transformed.

**Comment by SaurabhaArya** [comment]
Thanks for the update. Will update it to the newer versions.
