### ISSUE TITLE
Using br tags with ngx quill

### ISSUE THREAD

**Issue by CharlieGreenman** [KillerCodeMonkey/ngx-quill#1850]
Quill converts br tag to p tag. Was wondering if maybe we could create an example in ngx quill to override the br tag to a p tag.  Similar issue to this here: https://github.com/quilljs/quill/issues/4194

Thank you

**Comment by KillerCodeMonkey** [comment]
Nope because I want to stay as Close as possible to quilljs.



Am 10. Mai 2024 06:05:27 MESZ schrieb Charlie Greenman ***@***.***>:

**Comment by CharlieGreenman** [comment]
Ok, will close and hopefully in quill 2 we can figure out
