### ISSUE TITLE
Loaded HTML in Quill editor doesn't match actual HTML

### ISSUE THREAD

**Issue by paulchartres** [KillerCodeMonkey/ngx-quill#1851]
Hi there,  
I've been facing a pretty weird issue for the past few days. I tried fixing it a lot of different ways, to no avail, so I'm verry sorry to turn to you for help! I believe this may be a bug?  
I wrote a little formatted paragraph that displays as follows when saved to the database straight from the Quill editor:  
<img width="995" alt="image" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/5456986/c4033fc4-63c1-4b50-b6a4-c02b68997f5a">  
Now, when I try to edit the paragraph (so when I load it from the database straight into the editor, using ngModel or formControlName), I notice that the formatting isn't correct, at a seemingly arbitrary breaking point:  
<img width="491" alt="image" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/5456986/e85d3d06-231e-423a-a565-2a6ede993c1f">  
Note that the first bold title is rendered properly. I printed the HTML code and I can confirm that the title is surrounded by `<strong>` tags. It seems like Quill just completely ignores that (for the first few words, weirdly?).  
I am completely lost as to what the issue could be, so I hope a bright mind can enlighten me :)  
Thanks a lot for the work on this lib and have a great day!

**Comment by KillerCodeMonkey** [comment]
Do you use quill v2 and previously v1?

Because the are changes how quill Formats things.

Maybe this could be a reason.

Try the playground on the quilljs Homepage if it occurs there as well, when you use the quill API to Set your HTML.

I guess this is a quill problem.



Am 14. Mai 2024 21:32:11 MESZ schrieb Paul Dielenschneider ***@***.***>:

**Comment by paulchartres** [comment]
I use Quill v1, I haven't made any migrations lately. Does ngx-quill support v2? I could give it a shot and see if the problem persists.
I'll try it on the playground and get back to you later today.

**Comment by KillerCodeMonkey** [comment]
Yes latest major Version Supports angular  v17 with quill v2

Am 14. Mai 2024 21:57:18 MESZ schrieb Paul Dielenschneider ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
any update?
