### ISSUE TITLE
Cannot register a BlockBlot

### ISSUE THREAD

**Issue by rick2ricks** [KillerCodeMonkey/ngx-quill#1854]
Hi, 

I am not sure if I am missing somthing, but the following shouldn't  work?

```
//This returns unkown:
const Block = Quill.import('blots/block');

class DivBlot extends Block {
  static blotName = 'div';
  static tagName = 'div';
}

Quill.register(DivBlot);
```

How else should I extend and register a BlockBlot after upgrading to quill@2 and ngx-quill@25.

Thank you.

**Comment by KillerCodeMonkey** [comment]
This should work. There is an example in the Demo repo if I remember it correctly.

But you need to pass true as second Parameter to override an existing blot.


Am 16. Mai 2024 23:19:42 MESZ schrieb rick2ricks ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
see: https://github.com/quilljs/quill/blob/9f4e18540de93e8dec7cb7f53d8d0493714b7a09/packages/quill/src/core/quill.ts#L124

**Comment by rick2ricks** [comment]
Thanks for the response, but the problem starts before the register, when trying to extend Block, because Quill.import('blots/block') returns unkown. 

Also I could not find any references to extending a Blot or using Quill.register in any examples.

**Comment by KillerCodeMonkey** [comment]
just checked the quilljs repo and tried this:

```ts
import Block from 'quill/blots/block';

Block.tagName = "DIV";
Quill.register(Block, true);
```

it is working

**Comment by rick2ricks** [comment]
Don't know why I didn't find this import before. 

`import Block from 'quill/blots/block';"`

Thank you.
