### ISSUE TITLE
Support Quill 1 in Angular 18

### ISSUE THREAD

**Issue by Sergiobop** [KillerCodeMonkey/ngx-quill#1858]
Hi!

First of all, thanks for this awesome package.

I'm still stuck on Quill v1 since i'm using the [image-resize-module](https://github.com/kensnyder/quill-image-resize-module) and i can't make it work in Quill 2. Any chance we can add support to Quill 1 + Angular 18? I think many people is still on v1.

The other way to go would be to use quill2 and make the image resize work, but i don't know how to do this or find any example working.

In the ngx-quill-example repo, you have one section titled: "Formula & image resize editor & Keybinding on 'b' and 'shift + b', CodeBlock + Syntax Highlighting", but i can't find the example with the image resize editor.

Can we add the example there? 
Thanks

**Comment by KillerCodeMonkey** [comment]
The chances are not that high. There is no official support for quill v1 anymore and some APIs quill v1 is using are deprecated a long time ago. See chrome js console when using quill v1. So in the  future quill v1 will stop working in some major browsers anyway

Am 24. Mai 2024 10:39:16 MESZ schrieb Sergiobop ***@***.***>:

**Comment by Sergiobop** [comment]
I understand

Any chance you can add demo to the "Formula & image resize editor & Keybinding on 'b' and 'shift + b', CodeBlock + Syntax Highlighting", with the image resize working on Ngx-quill >= 26?

**Comment by KillerCodeMonkey** [comment]
Since the module is not supporting quill v2 I am not able to do it.

But you can try to Fork the image-resize module and make it compatible with v2.

Release a new package on your own or contact the maintainer to create pr for it



Am 25. Mai 2024 12:22:39 MESZ schrieb Sergiobop ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
you can try to use an old version of ngx-quill supporting quill 1 and override the angular version in  your package.json

**Comment by Sergiobop** [comment]
> you can try to use an old version of ngx-quill supporting quill 1 and override the angular version in your package.json

I guess i can do that in the meantime, as a workaround.

I hope someone with more knowledge than me in Quill, update the image-resize module (or creates a new module) to work with Quill 2, but my expectations are not high. I think image resizing is one of the most popular Quill modules (if not the most) and it would be great to have it working in Quill 2.

I saw one package with image resize working in Quill 2, but only for react and not angular 😞  (https://github.com/ludejun/quill-react-commercial)

Thanks for your fast response

**Comment by KillerCodeMonkey** [comment]
you can try https://github.com/KillerCodeMonkey/quill-image-resizor
i have not tried it with ngx-quill, but it is working with native quill v2

**Comment by KillerCodeMonkey** [comment]
i added an example usage to the ngx-quill-example-repo.

if i have time i may migrate the package to ts to get some typings.
for now you have to do the following:

1. add quill.js to the scripts sections in your angular.json
2. add quill-image-resizor.d.ts to your project and declare the module to be able to import it
3. and then import it and register it -> see https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/components/formula/formula.component.ts#L7

**Comment by KillerCodeMonkey** [comment]
i released v1.1.0 where you have now some typings for the modules, so you do not need to create a custom .d.ts  file for it
