### ISSUE TITLE
How to translate default texts?

### ISSUE THREAD

**Issue by Nexeuz** [KillerCodeMonkey/ngx-quill#186]
Like: 'Insert text Here'

'Normal'
Small, 
Large,
Huge

**Comment by KillerCodeMonkey** [comment]
Check quilljs Documentation for this. I think You it is Set by css and the
content Attribute, so You could override Them or create a custom toolbar
with html.

Nicolas Falla <notifications@github.com> schrieb am Mi., 23. Mai 2018,
22:25:

**Comment by Nexeuz** [comment]
@KillerCodeMonkey  Thanks!
