### ISSUE TITLE
"content" in the "ContentChange" with any

### ISSUE THREAD

**Issue by Marius-Romanus** [KillerCodeMonkey/ngx-quill#1861]
hello! I think that "content" in the "ContentChange" model should be a Delta

https://github.com/KillerCodeMonkey/ngx-quill/blob/d09a160ae2c27de9b460d224bda3fcd8f24c932f/projects/ngx-quill/src/lib/quill-editor.component.ts#L50C3-L50C10

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/18282247/9d6febf9-6c9e-4cc5-bc79-8c2154239b32)

greetings!

**Comment by KillerCodeMonkey** [comment]
should be fixed in 26.0.1

**Comment by Marius-Romanus** [comment]
works perfectly, thanks!
