### ISSUE TITLE
Add type to event emitter onEditorCreated

### ISSUE THREAD

**Issue by fabdeceglia** [KillerCodeMonkey/ngx-quill#1868]
Hi, 

i am currently working with ngx-quill version _23.0.2_ in a _Angular 16_ application.
I've successfully integrated the editor in the app, but i want to understand if there is a way to have the type on the emitter of the editor created.
From the api i see that _any_ is emitted:

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/10594686/fa23f7f6-5b1c-498a-8c02-ed711133a0ad)

But from the debugger i type is shown:

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/10594686/4c993653-8c43-4a16-abf6-0ea2b245b915)

It there a plan to have that class/interface exposed?
Would be nice to have the API of the component in order to access easly all the exposed method and attributes.

**Comment by KillerCodeMonkey** [comment]
The parameter is just a Quill instance.

i just avoided to type it a long time ago because each import of quill breaks server side rendering, but i guess i can just import it as "type"

**Comment by KillerCodeMonkey** [comment]
so as a workaround you can type it like `import Quill from 'quill'` and Quill is the type of the parameter

**Comment by KillerCodeMonkey** [comment]
i added the type in version 26.0.2
