### ISSUE TITLE
getSemanticHTML is missing on Quill instance, version 23.0.2

### ISSUE THREAD

**Issue by fabdeceglia** [KillerCodeMonkey/ngx-quill#1870]
Hello again,

the method `getSemanticHTML` is missing from the editor istance returned in the library version _23.0.2_.
These are the available methods:

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/10594686/9cab07c1-e0f2-4c21-b3be-9f26317454ec)

Is this something added in the newer versions? If yes, how can i access to the HTML editor's value?

Thanks

**Comment by KillerCodeMonkey** [comment]
this method is only available when used quill v2.

ngx-quill 23 is using quill v1
