### ISSUE TITLE
On setting toolbar as false getting distorted editor

### ISSUE THREAD

**Issue by ktrz290** [KillerCodeMonkey/ngx-quill#1871]
this.modules = {
  toolbar: false,
  mention: {
    allowedChars: /^.*$/,
    mentionDenotationChars: this.mentionDenotationChars,
    showDenotationChar: false,
    spaceAfterInsert: true,
    ......
}
The above is my modules configuration. When I do toolbar as false since I just want the simple editor it is breaking and not working as expected. In the previous version it is working as expected. And also if toolbar is set as true it is working as expected.

Can somebody please help? Has the configuration changed and do I need to do anything differently to achieve an editor without a toolbar? Any suggestions will be of great help.

Expected behaviour: Setting toolbar as false should give an editor without toolbar options.
<img width="275" alt="expected" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/172595442/3ff297a8-af60-49be-82cd-8647d9589f87">

Actual behavior: Setting toolbar as false gives a distorted editor.
<img width="221" alt="toolbar false" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/172595442/12ea83ca-ec1a-4cef-b4c7-0341dc47ceee">

Platforms: Chrome, Windows, quill version 2.0.2, ngx-quill version 26.0.2

**Comment by KillerCodeMonkey** [comment]
since mention plugin is now quill 2.0 compatible i readded it to my example repo.

https://killercodemonkey.github.io/ngx-quill-example/#mention

with no toolbar and there are no problems there.

**Comment by KillerCodeMonkey** [comment]
maybe you just need to add a default width of the editor container.
