### ISSUE TITLE
Question: Is it possible to toggle the toolbar

### ISSUE THREAD

**Issue by ed4becky** [KillerCodeMonkey/ngx-quill#1873]
I would like to display a form field. When the user clicks into the form, the toolbar appears. When they exit the field, the toolbar disappears, but the contents of the editor still display, with proper formatting. This is essentially an inline editor with a toggling toolbar.

**Comment by KillerCodeMonkey** [comment]
There you have the "bubble" theme. Check the quilljs docs for it 

Am 16. Juni 2024 14:48:49 MESZ schrieb Ed Thompson ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
https://quilljs.com/docs/customization/themes#bubble

Another solution would be -> play around with onFocus/onBlur or onNativeFocus/onNativeBlur and set a css class at the toolbar node to display none or block in the default snow theme
