### ISSUE TITLE
NodeJs required version should be more lenient

### ISSUE THREAD

**Issue by jrmlstf** [KillerCodeMonkey/ngx-quill#1874]
I'm upgrading my project to Angular 16 but I still have to maintain previous versions using Angular 13. 

I decided to switch to NodeJs16 that is compatible with both Angular versions (13 and 16).

But ngx-quill version 23 lock NodeJs version to 18 https://github.com/KillerCodeMonkey/ngx-quill/blob/db73d153f1971a0b16445a5d1299afc19715e2cc/package.json#L25

Npm install then breaks because of NodeJs required version (using 16 vs 18).

Node version should be more lenient : it should support the same NodeJs versions as [Angular 16 : ^16.14.0 || ^18.10.0](https://angular.io/guide/versions#actively-supported-versions).

**Comment by KillerCodeMonkey** [comment]
should be fixed in 23.0.3
