### ISSUE TITLE
Incorrect imports in Quill-editor.component.d.ts

### ISSUE THREAD

**Issue by jonas-menne** [KillerCodeMonkey/ngx-quill#1876]
Whenever i newly install the package (Version 23.0.2|3) I have to correct the imports in the "quill-editor.component.ts", so that Delta is imported from "quill/core". Would be nice to fix this because it is especially painful in pipelines. 

![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/119054328/9d5c9441-c483-484d-b8cb-a993d1f5123c)
 
Or is this a misstake on my end? I`m new to the library. 

Angular-version: 16.2.12
Node-version: 20.12.2

**Comment by KillerCodeMonkey** [comment]
I guess you installed quill v2 instead of v1 then.

There should be no Problem with quill v23 and quill v1

Am 19. Juni 2024 15:54:12 MESZ schrieb jonas-menne ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
+ you need to install @types/quill v1 and not v2 ;-)

**Comment by jonas-menne** [comment]
Thanks, that worked :)
