### ISSUE TITLE
Update to 26.0.3 generates error on `tsc`

### ISSUE THREAD

**Issue by KeithGillette** [KillerCodeMonkey/ngx-quill#1879]
Running `tsc` on a project updated to `ngx-quill@^26.0.3` with `quill@2.0.2` generates the following error:

```
node_modules/ngx-quill/lib/quill-editor.component.d.ts(55,80): error TS2694: Namespace '"/path/to/node_modules/parchment/dist/src/parchment"' has no exported member 'Registry'.
```

**Comment by kzander91** [comment]
Same issue with 26.0.4.

**Comment by KillerCodeMonkey** [comment]
can you share your tsconfig please?

**Comment by KeithGillette** [comment]
Workspace `tsconfig.json`:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": false,
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "lib": [
      "es2022",
      "dom"
    ],
    "module": "es2022",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "outDir": "./dist/out-tsc",
    "resolveJsonModule": true,
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": false,
    "target": "es2022",
    "paths": {
      "@tasktrain/node": [
        "libraries/node/src/index.ts"
      ],
      "@tasktrain/shared": [
        "libraries/shared/src/index.ts"
      ]
    }
  }
}
```
Project `tsconfig.json`:
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc/app",
    "types": [],
    "target": "ES2022",
    "useDefineForClassFields": false
  },
  "angularCompilerOptions": {
    "enableIvy": true,
    "preserveWhitespaces": false,
    "fullTemplateTypeCheck": true,
    "strictTemplates": false,
    "strictInjectionParameters": true
  },
  "include": [
    "src/polyfills.ts",
    "src/main.ts",
    "src/app/**/*.ts"
  ]
}
```
Thanks!

**Comment by KillerCodeMonkey** [comment]
strange in my example repo everything is working. and when i check the typings it is there.

**Comment by KillerCodeMonkey** [comment]
![Screenshot_20240620_184246](https://github.com/KillerCodeMonkey/ngx-quill/assets/2264672/a0fd4c79-7882-4b99-9e25-5ab40c6f84fa)

**Comment by KillerCodeMonkey** [comment]
Can somebody please check if the correct parchment version is installed in the node_modules folder?

Do you specified parchment in your package.json with a different version?

**Comment by KeithGillette** [comment]
Here's my `node_modules/parchment/dist/src/parchment.d.ts` ( "version": "1.1.4") after deleting `node_modules` & fresh `npm install`:
```typescript
import ContainerBlot from './blot/abstract/container';
import FormatBlot from './blot/abstract/format';
import LeafBlot from './blot/abstract/leaf';
import ScrollBlot from './blot/scroll';
import InlineBlot from './blot/inline';
import BlockBlot from './blot/block';
import EmbedBlot from './blot/embed';
import TextBlot from './blot/text';
import Attributor from './attributor/attributor';
import ClassAttributor from './attributor/class';
import StyleAttributor from './attributor/style';
import AttributorStore from './attributor/store';
import * as Registry from './registry';
declare let Parchment: {
    Scope: typeof Registry.Scope;
    create: typeof Registry.create;
    find: typeof Registry.find;
    query: typeof Registry.query;
    register: typeof Registry.register;
    Container: typeof ContainerBlot;
    Format: typeof FormatBlot;
    Leaf: typeof LeafBlot;
    Embed: typeof EmbedBlot;
    Scroll: typeof ScrollBlot;
    Block: typeof BlockBlot;
    Inline: typeof InlineBlot;
    Text: typeof TextBlot;
    Attributor: {
        Attribute: typeof Attributor;
        Class: typeof ClassAttributor;
        Style: typeof StyleAttributor;
        Store: typeof AttributorStore;
    };
};
export default Parchment;
```
Our project does not have Parchment as an explicit dependency, just `ngx-quill` and `quill`.

**Comment by KillerCodeMonkey** [comment]
Can you check your nodes modules folder please for parchment and the typings, please ?

**Comment by KillerCodeMonkey** [comment]
i created a fresh new repo with just installing quill and ngx-quill.. an it is working for me.

**Comment by kzander91** [comment]
I'm using `@types/quill`. Without it, my error changes to
```
Error: node_modules/ngx-quill/lib/quill-editor.component.d.ts:55:67 - error TS2307: Cannot find module 'parchment' or its corresponding type declarations.

55     readonly registry: import("@angular/core").InputSignal<import("parchment").Registry>;
                                                                     ~~~~~~~~~~~
```

I can build your example app successfully, the versions of Angular, ngx-quill, quill and parchment are the same that fail in my project...

There are other differences, trying to figure out which of these may be the problem will take some more time.

**Comment by KillerCodeMonkey** [comment]
So in general types/quill should not be needed anymore.



Am 20. Juni 2024 19:52:46 MESZ schrieb Kai Zander ***@***.***>:

**Comment by kzander91** [comment]
I got it working now, there was a weird issue with `@types/quill` and an old version of `parchment` being a dev-only transitive dependency.
With `ngx-quill` 26.0.2 and `@types/quill` currently being installed, I did:
```sh
npm r @types/quill && npm i ngx-quill@26.0.4 && npm i parchment@3.0.0 && npm r parchment
```
And now it's working.

**Comment by KeithGillette** [comment]
We removed `@types/quill` when we upgraded to Quill 2, so that's not the source of our problem. It appears that our use of `quill-emoji@0.2.1` is the issue:

```
npm ls parchment
├─┬ quill-emoji@0.2.1 (git+ssh://git@github.com/artknight/quill-emoji.git#bfff17cbb82c4ce2bb974eb657013c7133ae85fa)
│ └── parchment@1.1.4
└─┬ quill@2.0.2 invalid: "2.0.1" from the root project
  └── parchment@3.0.0
```

**Comment by KillerCodeMonkey** [comment]
If I remember correctly. Quill emoji does not support quill v2?

Am 20. Juni 2024 21:14:14 MESZ schrieb Keith Gillette ***@***.***>:

**Comment by KeithGillette** [comment]
We're using a [fork](https://github.com/artknight/quill-emoji) of `quill-emoji` updated for Quill 2. Its [`package.json` is set to     `"parchment": "*"`](https://github.com/artknight/quill-emoji/blob/master/package.json#L45C1-L46C1), so I'm not sure why it's pulling `parchment@1.1.4`.

**Comment by KeithGillette** [comment]
@kzander91's trick of `npm i parchment@3.0.0 && npm r parchment` updated `package-lock.json` and resolved the issue, allowing update to `ngx-quill@26.0.4`. 🎉 Thanks for your responsiveness, @KillerCodeMonkey!

**Comment by do-diegoortiz** [comment]
I'm having this same issue in Angular 19.2.2 with ngx-quill 27.0.1 and qiull 2.0.3
`55 │ ...import("@angular/core").InputSignal<import("parchment").Registry>;`

I provided provideQuillConfig({}), and imported `QuillEditorComponent` in the component where I use it. I don't have quill-emoji or @types/quill. Any clue why I'm having that same error?

**Comment by KillerCodeMonkey** [comment]
then check if you are using other outdated addons -> check my demo repo.. everything is working there out of the box :).

maybe remove your package-lock and node_modules folder and run npm i again

**Comment by do-diegoortiz** [comment]
Thanks, it was fixed updating `rxjs` from 7.8.0 to 7.8.2

**Comment by alicelebidev** [comment]
I took demo app as reference (i.e. ensured quill related packages and versions are consistent).
Removed the `@types/quill` package.
Removed node_modules folder.
Removed package-lock.json file
Ran `npm install`

These steps resolved the issue with shown below.

    node_modules/ngx-quill/lib/quill-editor.component.d.ts:55:79:
      55 │ ...import("@angular/core").InputSignal<import("parchment").Registry>;

**Comment by RomeoProfijt** [comment]
> I took demo app as reference (i.e. ensured quill related packages and versions are consistent). Removed the `@types/quill` package. Removed node_modules folder. Removed package-lock.json file Ran `npm install`
> 
> These steps resolved the issue with shown below.
> 
> ```
> node_modules/ngx-quill/lib/quill-editor.component.d.ts:55:79:
>   55 │ ...import("@angular/core").InputSignal<import("parchment").Registry>;
> ```

For me this was the solution. Thx!
