### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by Earthii** [KillerCodeMonkey/ngx-quill#188]
I am building my project with angular Cli. 

What i get is this: 
<img width="416" alt="screen shot 2018-05-30 at 12 19 03 am" src="https://user-images.githubusercontent.com/16367621/40698831-22606e7c-639f-11e8-8cd4-cba5f5240aaf.png">

**Comment by KillerCodeMonkey** [comment]
Show me some Code please ;)

Earthii <notifications@github.com> schrieb am Mi., 30. Mai 2018, 06:19:

**Comment by KillerCodeMonkey** [comment]
i think in the new cli (6.x) you do not need to add the ngx.quill.umd to the scripts section in the angular.json. simply import from ngx-quill

**Comment by KillerCodeMonkey** [comment]
reopened? why?

**Comment by Earthii** [comment]
That's weird lol
