### ISSUE TITLE
question about empty lines in the quill-view-html component

### ISSUE THREAD

**Issue by haykoaghababyan** [KillerCodeMonkey/ngx-quill#1883]
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/44507921/e5a734b5-a1d2-4e6b-a720-7ffeeae5d0f1)

 
 Why the empty rows between (example) words don't appear ?
 it shows like this      
 
 examples
 examples

**Comment by haykoaghababyan** [comment]
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/44507921/7badc4e6-186a-49f7-b1da-885c3eae9673)
but when using quill editor with the read only equal true, it works fine with empty lines

**Comment by KillerCodeMonkey** [comment]
Are those p-tags in your dom? so maybe it is a styling issue?

**Comment by haykoaghababyan** [comment]
when we using quill editor with the form control. and trying setValue this string with empty lines, inside empty <p> tags in the dom I noticed <br> tags, that is why it is working with (<quill-editor> [readonly]=true) fine, but the same <br> tags for  view html component I didn't notice

**Comment by haykoaghababyan** [comment]
> i extended my demo repo
> 
> https://killercodemonkey.github.io/ngx-quill-example/#view check the "View format: HTML - sanitized" example. empty lines are there.
> 
> PS: it is working with p and div tags as block blot

yes your example working , because you use quill-view,, byut my example quill-view-html

**Comment by KillerCodeMonkey** [comment]
Quillview HTML is a silly component. It just renders the HTML you pass and wrapping it in a container with the base quill css classes to get styling working.

So if your HTML misses the br tags quill-view-html will not do the quill magic for you.

If you do not have valid/complete quill HTML content use the quill-view component

**Comment by haykoaghababyan** [comment]
got it thanks

**Comment by haykoaghababyan** [comment]
Hi @KillerCodeMonkey ,
What solution can you suggest to preserve whitespaces in the quill-view component? The preservingWhiteSpaces property has been removed. it works in the quill-view-html component because it uses innerHtml , but the quill-view component uses different logic.

**Comment by KillerCodeMonkey** [comment]
There is no way with quill v2. Since it's not supported anymore. 

Quill-view just uses a quill editor in readonly mode.
