### ISSUE TITLE
QUESTION: How can I style the "bubble" for the bubble theme

### ISSUE THREAD

**Issue by ed4becky** [KillerCodeMonkey/ngx-quill#1884]
How can I style the "bubble" for the bubble theme

**Comment by KillerCodeMonkey** [comment]
I would just check the bubble.css of the quill editor and overwrite it.

I guess this is the way. 

Check the quilljs docs for theming

**Comment by KillerCodeMonkey** [comment]
i guess the bubble is the toolbar-tooltip:

a div with classes "ql-tooltip ql-flip"
