### ISSUE TITLE
How to disable links in quill editor with angular

### ISSUE THREAD

**Issue by philippeverger** [KillerCodeMonkey/ngx-quill#1885]
hello

when copy/pasting content, the user is able to add links
how to prevent links in the content ?
note: I removed the links from the toolbar

thanks

**Comment by KillerCodeMonkey** [comment]
if i remember it correctly you need to remove it form the formats.

you can pass an array of allowed formats to the quill module config or directly to the editor-component.

per default all formats are allowed.
