### ISSUE TITLE
quill content is not updated on insert from mobile keyboard hints

### ISSUE THREAD

**Issue by MxRmz** [KillerCodeMonkey/ngx-quill#1886]
Hi there. Thanks a lot for this nice repo. 
I would like to tell tell you about an issue I faced after upgrade to qull 2.0.
It happens when user inserts content from mobile keyboard (in particular SwiftKey) from hints. To insert this hint SwiftKey uses composition event. If editor is empty and user inserts a word from hint text in input appears, but quill contents is not updated. Even if user then start to type - quill will be still empty. ngModelChange, onEditorChange, onContentChange event are not fired in this case.
How do I update quill content manually?

**Comment by KillerCodeMonkey** [comment]
Maybe the changes are not recognized as User Source


Can you try to Set "trackChanges" property to "all"?

Am 1. Juli 2024 15:56:45 MESZ schrieb Max Olkhovskyi ***@***.***>:

**Comment by MxRmz** [comment]
yeah tried that. doesn't help

**Comment by KillerCodeMonkey** [comment]
Strange then I have no idea since I am just  listening to the native quilljs Events to Update the model/control

Am 1. Juli 2024 16:11:02 MESZ schrieb Max Olkhovskyi ***@***.***>:

**Comment by MxRmz** [comment]
> Strange then I have no idea since I am just listening to the native quilljs Events to Update the model/control Am 1. Juli 2024 

Issue is absent if I try to reproduce it on quillJS [official playground](https://quilljs.com/playground/snow#codeN4Ig9AlgdgJgpgDwHQCsDOIBcIDGB7KNAFwAIBHAVwgBtqSBeEqOAdxIEUraAKAcgGI4MCETwAnXgBoSwADpQSJALZ4YFanDSYZ8xYtF5qAIwCGY7QG1dexReAkAFnBPxzJCwEZpAJmkAzE2o0OABdEgBfEMlrGwteI0MYKRJeEUCIHGTeClg4MWpoOF4omL04iCUTAHMi6V58eABaI2o8HABrYuiFPRKe8O7FAAdqExw4B0S87V4AYTwlIbxgkhMFOCGMpG2payInJTgZtCg8FmSwMBJxFKMKIxai+XCASgBueXlgogBJKCI8gA3QLcbgvBgAPh0PRgbQoh3+SBqRAAohoEUQ0AAhACes1GaDQADkTIc+GJNOoiLwXhYAAwhJDQZhiAASABUALIAGQYJAAUgBlADyRKQxDE0CqED8OO4lBo1CRcCI83+cH+aDB72e0g8dINL0+UBAknA0HgyAcRCU1CwIAAPMJASQIDB6LIQEIROJPRCHWBnRD5E6IC6cAS0B6QBS0FS-SG0DhJUNSGgxDho5Bcsh0H6A0mU0QISBwkA).
In the same time it's present in ngx-quill [demo](https://killercodemonkey.github.io/ngx-quill-example/) 
So I may assume it's on ngx-quill side.

**Comment by KillerCodeMonkey** [comment]
If you like you can try to debug if the quill event listeners are executed inside ngx-quill.

I tried it on my mobile with gboard and Samsung galaxy keyboard without any issues.

Copy and pasted, used the autocorrecting features and word recommendations. Everything works there.

I tested it with my live Demo and the reactive form control example there.

**Comment by KillerCodeMonkey** [comment]
Tried it and it works

**Comment by MxRmz** [comment]
I'm with you about gboard and Samsung keyboard, everething is fine. But a lot of users have SwiftKey (Microsoft) as default keyboard on their smartphones, where both autocorrection and insert hinted word fails.

**Comment by KillerCodeMonkey** [comment]
As I wrote in my last comment. It works for me with swift keyboard.

And I do not see any problem with ngx-quill here. There are no special handlings nor changes between the quill v1 and v2 migration that should cause this.

And if other keyboards work, I doubt I can do anything here.

**Comment by MxRmz** [comment]
It's pretty easy to reproduce. Steps:
1. You have empty (!) editor
2. Insert content
Here is example. First part is with SwiftKey keydoard. The second one is on Samsung keyboard 3x4. Both are using composition event so it fails.

Video example: https://github.com/KillerCodeMonkey/ngx-quill/assets/99099545/f34e8b28-1ac7-4037-b8b3-03aa391d0f6f

**Comment by KillerCodeMonkey** [comment]
I do not get it... Exactly this is what I did on my galaxy s23...

And it is working with both keyboards.

And as I said. I changed nothing in the event handlers or form control/model handling (as far as I remember)

You could try angular v17 with quill v2. Because the only really change is with v18 the usage of input signals.

The rest was untouched.

**Comment by KillerCodeMonkey** [comment]
But what I found is this quill issue

https://github.com/slab/quill/issues/4021#issuecomment-2049166695

That quill does not recognize changes or does not remove placeholder when using correcting or word hints until you write a whitespace.

And the comment states that there is a problem with those composition events

**Comment by MxRmz** [comment]
Thank you very much for your help. Special thanks for the prompt feedback.
