### ISSUE TITLE
"sanitize"-property set in QuillModule.forRoot() is ignored in QuillEditorComponent

### ISSUE THREAD

**Issue by an-bss** [KillerCodeMonkey/ngx-quill#1887]
The call `QuillModule.forRoot({ sanitize: true })` has no effect on QuillEditorComponent instances.

It is used here:
https://github.com/KillerCodeMonkey/ngx-quill/blob/2ec7418f1ca7c7201b444a92483dd6d996f2b698/projects/ngx-quill/src/lib/quill-editor.component.ts#L199
The setting from the config in the service is only being used, if `this.sanitize()` is neither true nor false.
`this.sanitize()` is an input and defined here:
https://github.com/KillerCodeMonkey/ngx-quill/blob/2ec7418f1ca7c7201b444a92483dd6d996f2b698/projects/ngx-quill/src/lib/quill-editor.component.ts#L96

The input is initialized with false. Therefore the value from `this.service.config.sanitize` is never  used. 
My proposal is to change the initial value of the input to `undefined`. 
Any thoughts on that?

**Comment by KillerCodeMonkey** [comment]
<img src="https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExaGN4M25vbHV6dGN6YWozNHFyMGV3bzd3eTM1ZzBrY2VlMGxybGd4bSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BjHIjM2YFC3rEUaMrw/giphy.webp">

**Comment by KillerCodeMonkey** [comment]
released in v26.0.5
