### ISSUE TITLE
quill-view-html - numbered and bulleted lists

### ISSUE THREAD

**Issue by majster** [KillerCodeMonkey/ngx-quill#1888]
Example **view-html** on https://killercodemonkey.github.io/ngx-quill-example/#html is not showing numbered and bulleted lists correctly

### Wayback machine (_2023-10-18_)
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/1515816/8f78d99d-9c10-49d7-acf4-6d87c1490210)

### Current version (_2024-07-02_)
![image](https://github.com/KillerCodeMonkey/ngx-quill/assets/1515816/f0379ea6-6e11-4077-82d4-d321d977abad)

**Comment by KillerCodeMonkey** [comment]
known quill 2.0 issue, since you get html code from quill with getSemanticHTML() and there are some things missing https://github.com/slab/quill/issues/4103.

i do not touched the content of the view-html example so it uses quill v1 content instead of 2.

in general... do not store html to database... never^^

**Comment by majster** [comment]
Really appreciate a fast response. I think the issue here is that ngx-quill is advertising **quill-view-html** component which is apparently not supported as of 2.0. I would recommend marking it as deprecated.
Thanks again for clarification, i will find a suitable solution to my problems.

**Comment by KillerCodeMonkey** [comment]
yes the quill-view-html was honestly only there to have an alternative to show the content without the quill overhead.

i mean someone could extend the list formats so maybe getSemanticHTML() will return some data-attributes/inline-stylings you can use to add css-styling to get what you want.

**Comment by KillerCodeMonkey** [comment]
added a hint in the latest versions readme https://github.com/KillerCodeMonkey/ngx-quill/tree/v26.0.5?tab=readme-ov-file#quillviewhtmlcomponent---using-angular-innerhtml-deprecated-with-quill-v2

**Comment by TheEponymousBob** [comment]
For what it's worth, there is a similar-looking issue with code blocks. In the editor DOM, these are represented as a list of \<pre\> blocks, one per line. But getSemanticHTML() turns it into a single \<pre\> block. This breaks the lovely line-numbering I added to the editor.

Plan was to extend the SyntaxCodeBlockContainer class to override its html() method, but for some reason it's not being exported from the syntax module. I really don't want to fork. And I can't persist in Deltas, as the data is being shared between the current application and another older one that depends on HTML.

I may just have to go with innerHTML (unless someone else knows a better way).
