### ISSUE TITLE
Image Resizor overflow on bubble toolbar

### ISSUE THREAD

**Issue by thomasgebets** [KillerCodeMonkey/ngx-quill#1891]
Hi, i'm sorry to use this issues tab from ngx-quill for this matter, but would it be possible to adapt the image resizor project to use a css class or id. I'm struggling with bubble toolbar together with the image resizor. The resize container overflows or the bubble toolbar is cut on overflow. Therefore i would implement some custom logic to account for that in our project, but i would need some class or id to access the resize container.
Thanks in advance!

**Comment by KillerCodeMonkey** [comment]
to be honest -> create an issue at the image.resizor repo, but you can try to extend it by your self and send a PR.

i only forked the original module to have something compatible with quill v2, because this was the main reason some ngx-quill users could not upgrade to the latest version. :D

**Comment by thomasgebets** [comment]
Sure, i will try; i just didn't find any issues tab in the repository..

**Comment by KillerCodeMonkey** [comment]
ah sorry seems like github disables issues when a repo is a fork. now it is there. thanks for the info

**Comment by KillerCodeMonkey** [comment]
i released a new version of image-resizor. in v1.3.0 you can use ".ql-image-resizor" to get access to the current active image-resizor

**Comment by thomasgebets** [comment]
Thank you so much!! I really appreciate it! :)
