### ISSUE TITLE
Update to Quill v2 causing issues with embedded videos.

### ISSUE THREAD

**Issue by sarmadhadii** [KillerCodeMonkey/ngx-quill#1893]
We were using Angular 16 with v23 (quill v1). After a file upload to aws, I was embedding the video as follows: 

` @ViewChild(QuillEditorComponent) quillEditor: QuillEditorComponent; 

this.quillEditor.insertEmbed(index, 'video', url, 'user'); _where url was the url of the video_
`

After our update to Angular 17 with ngx-quill v25 (quill v2), the above code does embed the video... but both `[(ngMode)]` and `getSemanticHtml()` return an anchor tag with the href as the URL of the video rather than a video tag. That means, whenever I submit the value retrieved from either of the two above, and then refresh the page... it's actually coming in as an anchor tag.

So for example, what used to be: 

`.... html
<video src="www.video.mp4"></video>
`

is now: 

`...html
<a href="www.video.mp4">video.mp4</a>`

**Comment by KillerCodeMonkey** [comment]
Please ask this at the quilljs repository, because it seems a quilljs issue.

In general- avoid storing HTML. Using json/object representation is more safe and easier to migrate 



Am 15. Juli 2024 21:44:33 MESZ schrieb Sarmad Hadi ***@***.***>:

**Comment by sarmadhadii** [comment]
Thanks for the quick reply. I'll ask there.
