### ISSUE TITLE
List bullet and ordered 

### ISSUE THREAD

**Issue by LeonardoGoPe** [KillerCodeMonkey/ngx-quill#1896]
Hi,

I use version 25.3.2 with Angular 17.x , when I want to add the bullet format, the ordered format is added
![image](https://github.com/user-attachments/assets/06c2b69f-96dc-4b62-9a24-edf60ef616ad)

What could be the possible problem?

**Comment by KillerCodeMonkey** [comment]
I guess you upgraded from quill v1 to v2.
So there are some changes how lists are build and v2 does not recognize bullet / numbered lists as HTML from v1.

**Comment by KillerCodeMonkey** [comment]
There are already some issues about it
https://github.com/slab/quill/issues/4289

**Comment by LeonardoGoPe** [comment]
I really appreciate your time to respond, indeed, returning to v1 the problem was solved.
Thank you so much!
