### ISSUE TITLE
ModuleClass is not a constructor

### ISSUE THREAD

**Issue by sheikh-hassan** [KillerCodeMonkey/ngx-quill#1900]
I have install the ngx-qill veriosn 25.3.2 as I am using angular 17
quill version is 2.0 
all the things are working fine the text editor is showing correctly and text is edited also but a error in console every time
ModuleClass is not a constructor
maybe due to this issue the ngModel is not capturing the value and I am getting empty string in every case
the complete error of console is 
ERROR TypeError: ModuleClass is not a constructor
    at SnowTheme.addModule (theme.js:23:26)
    at SnowTheme.addModule (base.js:40:26)
    at theme.js:16:14
    at Array.forEach (<anonymous>)
    at SnowTheme.init (theme.js:14:39)
    at new Quill (quill.js:133:16)
    at ngx-quill.mjs:399:36
    at _ZoneDelegate.invoke (zone.js:365:28)
    at ZoneImpl.run (zone.js:111:43)
    at NgZone.runOutsideAngular (core.mjs:14778:28)

**Comment by KillerCodeMonkey** [comment]
I do not think it is a quilljs issue. 

Please check the Demo repo how the editor is initialized with snow theme.

Maybe you have a custom module installed or installed typings for quilljs v2

**Comment by KillerCodeMonkey** [comment]
Any updates? I would guess you use some incompatible 3rd party quill modules - maybe written for quill v1 - with will v2.

**Comment by argtarun** [comment]
@KillerCodeMonkey I am facing the same issue, with same lines of error.
