### ISSUE TITLE
Refreshed design for ngx-quill logo to be in line with new Angular brand

### ISSUE THREAD

**Issue by jjmhalew** [KillerCodeMonkey/ngx-quill#1902]
Since Angular 17 was announced last year, Angular has a new brand. They encourage the community to adapt their logo to their branding and they provided guidelines, see https://angular.dev/press-kit.

Since I use ngx-quill as it works flawlessly for me, I thought I could help with a new logo according to Angular's new brand guidelines. I made a few variations below, I hope it can help contribute towards a refreshed logo :)

<img src="https://github.com/user-attachments/assets/378bbc11-7335-42ea-b3b7-80a11ed52255" width="200">
<br />
<br />
<br />
<br />
<img src="https://github.com/user-attachments/assets/eb3d2947-903e-4a0f-a245-886a17fcf22f" width="200">
<br />
<br />
<br />
<br />
<img src="https://github.com/user-attachments/assets/a384feab-bf30-4652-83d0-6d1a88b202ff" width="200">

**Comment by KillerCodeMonkey** [comment]
wow nice :) Thanks you.
I prefer the first one. What is your fav?

**Comment by KillerCodeMonkey** [comment]
PNG: ![ngx-quill-logo-v2](https://github.com/user-attachments/assets/4360ec96-c830-40c4-aa8c-0be00473b845)

**Comment by KillerCodeMonkey** [comment]
Thanks again. i already changed it. please keep in mind, since this is open source and everything is under MIT license there are no restrictions how some one else will use your work of creativity.

Thanks again for your work :)

**Comment by jjmhalew** [comment]
I think the one you chose is a good fit, as it contains the original colors of the previous logo. You're welcome, I am glad I could help! :) Thank you for informing about the license. I am fine with it 🙂
