### ISSUE TITLE
Formatting breaks on every new line in the editor

### ISSUE THREAD

**Issue by KrishnapriyaQB** [KillerCodeMonkey/ngx-quill#1903]
Consider Bold formatting is active and user is typing in
Then clicked the Enter key for a new line
Then bold formatting is no more active

This issue applies to Italics/underline formatting

**Comment by KillerCodeMonkey** [comment]
it even occurs in native quilljs: https://quilljs.com/

so please check for issues there and optionally open a new one :) - https://github.com/slab/quill/issues.

Thanks
