### ISSUE TITLE
text color and background color is not getting patched when in editing mode

### ISSUE THREAD

**Issue by Virus35** [KillerCodeMonkey/ngx-quill#1904]
```HTML

<quill-editor
		#quillEditor
		[(ngModel)]="text"
		[modules]="quillToolbar"
		[maxLength]="100">
</quill-editor>
```

```TS
quillToolbar: any = {
		toolbar: [
			['bold', 'italic', 'underline', 'strike'], // Toggle formatting buttons
			[{ header: 1 }, { header: 2 }], // Custom button values for headers
			[{ list: 'ordered' }, { list: 'bullet' }], // List formatting
			[{ script: 'sub' }, { script: 'super' }], // Superscript/subscript
			[{ indent: '-1' }, { indent: '+1' }], // Outdent/indent
			[{ direction: 'rtl' }], // Text direction
			[{ size: ['small', false, 'large', 'huge'] }], // Font size dropdown
			[{ color: [] }, { background: [] }], // Color dropdown
			[{ font: [] }], // Font dropdown
			[{ align: [] }], // Text alignment
			['clean'], // Remove formatting button
			['link', 'image'] // Insert link and image buttons
		]
};
@Input() text: string =  `<blockquote><em style="color: rgb(255, 255, 102);"><u>vishal Rikhi</u></em></blockquote>`;
```

when i see in Dom, the style gets disappears.

**Comment by KillerCodeMonkey** [comment]
keep in mind quilljs will not allow everything. it only allows tags/classes and styles it knows.

just checkout my demo repo https://killercodemonkey.github.io/ngx-quill-example/
try to reproduce your "html" with the editor and check how it is formatted.
e.g. changing the color of something is using "spans" and so on.

**Comment by Virus35** [comment]
this is the delta's html produced by the ngx-quill-editor:-

{
    "html": "<p><strong class=\"ql-size-huge\" style=\"color: rgb(102, 163, 224);\"><em><s><u>vishal﻿</u></s></em></strong></p>",
    "delta": {
        "ops": [
            {
                "attributes": {
                    "underline": true,
                    "strike": true,
                    "italic": true,
                    "size": "huge",
                    "color": "#66a3e0",
                    "bold": true
                },
                "insert": "vishal﻿"
            },
            {
                "insert": "\n"
            }
        ]
    }
}, 


When i patch the value again, everything got patched except the color styling

**Comment by KillerCodeMonkey** [comment]
because, i guess your content of the patch is not valid quilljs content.

**Comment by KillerCodeMonkey** [comment]
Just try it out with plain quilljs: https://quilljs.com/playground/snow
use the quilljs api to set the content programmatically 

ngx-quill is using 

`const content = quill.clipboard.convert({ html: YOUR_HTML })`
`quill.setContents(content, 'silent')`

you can even just try to log, what `quill.clipboard.convert({ html: YOUR_HTML })` does with your html.

**Comment by Virus35** [comment]
the color gets applied when i apply the color
the bgColor gets applied when i apply the bgColor,

but when i patch the value again , the bgcolor and the color gets disappeared, but i apply the color/bgcolor again while editing, again it starts working fine, the issue arises when we patch the value again then the inline stylings gets disappeared.

**Comment by KillerCodeMonkey** [comment]
i updated my demo repo.

check the "Reactive Forms and patch value" i changed the patched value with something with color and background. you can change the colors and click patch. All previously colors stay applied and the new "patched" is added.

So i see no problem when patching the value with valid quilljs html.

https://killercodemonkey.github.io/ngx-quill-example/ - "Reactive Forms and patch value" - click "patchValue".
This uses the current html of the editor and just adds something. nothing is lost or gets removed. SO as i said. if you patch you control with custom html you need to make sure your html is valid html for quilljs.

and please try my approach by using quilljs playground and call quill.clipboard.convert({ html: YOUR_HTML }) with you html you want to patch, so you can check if it is valid quilljs html

**Comment by Virus35** [comment]
thanks ill check and im using angular 13 and ngx-quill version 16.1.2, your solution remains the same for this as well?

**Comment by KillerCodeMonkey** [comment]
in general i am not supporting that such old versions.

but in that case your need to use:

https://v1.quilljs.com/playground/
and if i remember it correctly:
https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml

But in general i have to say sorry, because angular support for v13 ended a long time ago so it is for ngx-quill v16
