### ISSUE TITLE
Code block style transferred to next ngModel

### ISSUE THREAD

**Issue by Earthii** [KillerCodeMonkey/ngx-quill#191]
If the code-block style is applied to a previous [ngModel], when switching to the next [ngModel], the code block style is applied to it (the pre tags are surrounding the content of the next ngModel even if they dont initially have it)
![screen shot 2018-06-05 at 7 11 20 pm](https://user-images.githubusercontent.com/16367621/41007659-db276af0-68f4-11e8-926e-8172cae3f69a.png)
![screen shot 2018-06-05 at 7 11 41 pm](https://user-images.githubusercontent.com/16367621/41007665-e2d53d7c-68f4-11e8-9995-292dee88fde8.png)

By swapping the object the [ngModel] is pointing to, back and forth (between a content that does not have code-block style, and one that does have code-block style, it would apply the code block style to the one that does not initially have it

ORIGINAL BEFORE VISITING ANOTHER NOTE:
![screen shot 2018-06-05 at 7 16 55 pm](https://user-images.githubusercontent.com/16367621/41007743-3dcc2a06-68f5-11e8-967f-47f85eb37d3a.png)
<br>
AFTER VISITING A NOTE WITH CODEBLOCK STYLE AND COMING BACK TO THE ORIGINAL NOTE:
![screen shot 2018-06-05 at 7 17 19 pm](https://user-images.githubusercontent.com/16367621/41007744-3f31c7de-68f5-11e8-90a4-56f9278e6050.png)

In this case, 'text' was surrounded with pre tags without me applying the code-block style

**Comment by KillerCodeMonkey** [comment]
what do you mean with switching to "next" ngModel?

If you change programmatically the activeNote.content and the editor has the code-Block activated it gets applied i think. I can not do anything about it. Because you are reusing the existing quilljs instance. And i can not distinguish if this is the old ngModel content or a new one.

So simply reinitialise the editor if you need to ;).

**Comment by Earthii** [comment]
Yes, sorry that was what i meant. The activeNote.content changes dynamically and gets assigned another activeNote.content if the user clicks on a button.

I haven't gotten the chance to try it out. Will get back to you

**Comment by Earthii** [comment]
To add to this topic, I noticed that Bold and Italic is not transferred even tho it is activated in the same editor instance. Only the code block style is transferred

**Comment by KillerCodeMonkey** [comment]
Okay then it Sounds like a quilljs issue. Check the quilljs Repo If there
something similar

Earthii <notifications@github.com> schrieb am Di., 12. Juni 2018, 18:14:

**Comment by KillerCodeMonkey** [comment]
But you can try to programmatically reset the active format and selection through the quilljs api:

https://quilljs.com/docs/api/#removeformat
https://quilljs.com/docs/api/#setselection
