### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by adamstret** [KillerCodeMonkey/ngx-quill#1912]
Useful library, but the documentation is just TERRIBLE.
It would be great if it was cleaner & simpler and not such a nightmare to use.

**Comment by KillerCodeMonkey** [comment]
I know :). 

Am 6. August 2024 13:07:11 MESZ schrieb adamstret ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
but feel free to create a pr with better docs :).
