### ISSUE TITLE
Use Input Decorator For Modules Until Models Is Fully Released

### ISSUE THREAD

**Issue by tommyc38** [KillerCodeMonkey/ngx-quill#1913]
I am upgrading a custom mention component but ran into an issue where I can't update the ngx-quill modules because of the new input signal syntax.  Below is a lightweight example where I am basically adding in key bindings that are actually handled by the <mp-mention> component since the instance is passed in.  Can you use `@Input()` syntax or use the new model api?  Thanks!

Usage
```html
<quill-editor ngClass="editor" [mpMentionTrigger]="mention" [modules]="modules"></quill-editor >
 <mp-mention #mention=mpMention position="contained">
   <mat-option *ngFor="let mention of mentions">
     <div class="mention-item">
       <img [src]="mention.src">
       <span >{{mention.name}}</span>
     </div>
    </mat-option>
</mp-mention>
```
Mention Trigger
```ts
@Directive({
  selector: '<quill-editor [mpMentionTrigger]>',
  exportAs: 'mpMentionTrigger',
})
export class MpMentionTriggerDirective implements OnInit, OnDestroy {
  @Input('mpMentionTrigger') mentionMenu!: MpMentionComponent;

 constructor(
    private _ngxEditor: QuillEditorComponent,
  ) {}

 private _keyboardModuleInit() {
    const { modules } = this._ngxEditor;
    let keyboard = {
      ...getKeyBindings(this),
    };
    // We don't want to overwrite any keyboard bindings passed in, so we merge.
    // See keyboard-names.ts if someone does use these names our values will overwrite them.
    if (typeof modules?.keyboard !== 'boolean') {
      keyboard = {
        bindings: {
          ...modules?.keyboard?.bindings,
          ...keyboard.bindings,
        },
      };
    }
    this._ngxEditor.modules = { ...modules, keyboard };
  }

}
```
Key Bindings Helper Fn
```ts
export function getKeyBindings(instance: MpMentionTriggerDirective) {
  const updateContextShim = (key: string, context: Context): Context => {
    const options = {
      key,
      code: key,
      keyCode: KEY_MAP[key],
      isTrusted: true
    }
   const event = new KeyboardEvent(key, options)
    return {
      ...(context || {}),
      event
    }
  }
  return {
    bindings: {
      // We overwrite the tab so that users can tab out.
      [KeybindingNames.MentionTab]: {
        key: Keys.Tab,
        handler: (range: StaticRange, context: Context) => {
          if (instance._panelIsOpen) {
            instance._handleKeydown(Keys.Tab, updateContextShim(Keys.Tab, context));
            return false;
          }
          return true;
        },
      },
```

**Comment by KillerCodeMonkey** [comment]
Nope I will stay with Signals. It is the New and recommended way by the angular Team. 

I mean you are more or less hacking around by overriding the modules of the editor that way. 

And you can fake Signals in a similar way, by just pass a Signal with your values.

But in general your Code looks really hacky ^^


Am 7. August 2024 04:22:20 MESZ schrieb tommyc38 ***@***.***>:

**Comment by tommyc38** [comment]
This was an extremely contrived example to give you a use case.  However, I am not overriding the modules unless by some crazy chance my keybinding's names overlap with the names of a consumer's keybinding (or a 3rd party) names using the exact one's I am (which I specifically chose rather gross names to be safe).  It was a choice of simplicity and elegance over the rare chance it would create a conflict.   MANY 3rd party libs do the same!  Moreover, it's the easiest way I can pass in my component instance and lock the keybindings to the instance that handles them.  Could you meet me part way and use "model" when it becomes official?  Thank you.

**Comment by KillerCodeMonkey** [comment]
Sure. If I miss it, just ping me :).



Am 7. August 2024 08:56:57 MESZ schrieb tommyc38 ***@***.***>:

**Comment by tommyc38** [comment]
Thank you kind sir!
