### ISSUE TITLE
Text color output

### ISSUE THREAD

**Issue by juankmarin** [KillerCodeMonkey/ngx-quill#192]
Hello, when I to use the color picker module, the ouput is something like `<span style="color: rgb(203, 118, 238);">`, so, is possible to use something like `<span style="color: #cacaca;">`, in hexa?

Thanks

**Comment by KillerCodeMonkey** [comment]
Do Not Know, Check the quilljs docs ;)

Juan Marin <notifications@github.com> schrieb am Do., 7. Juni 2018, 17:35:

**Comment by KillerCodeMonkey** [comment]
i think i can not help you here with a working solution.
i think quill is transforming the hex colors to rgb before inserting inline

https://github.com/quilljs/quill/blob/f75ff2973f068c3db44f949915eb8a74faf162a8/formats/color.js#L6

Please ask in the quilljs repo, but let us know, if you have an answer :)
