### ISSUE TITLE
Can't set customOptions

### ISSUE THREAD

**Issue by BBboy01** [KillerCodeMonkey/ngx-quill#1920]
https://github.com/KillerCodeMonkey/ngx-quill/blob/b5dc45772e916b26eeb85c427e054f2269b90710/projects/ngx-quill/src/lib/quill.service.ts#L50

![CleanShot 2024-08-22 at 17 29 42@2x](https://github.com/user-attachments/assets/05c81806-61ce-4103-abcb-df774fc666b8)

It's weird, `this` is `undefind`, so we can't get global configured customOptions….

Example project can reproduce too

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/184291a6a22240cffd4f6f507a23287158c08788/src/app/app.config.ts#L16C1-L19C7

**Comment by KillerCodeMonkey** [comment]
https://killercodemonkey.github.io/ngx-quill-example/

check example: Custom Toolbar (position: bottom) with toolbar title-attributes + Word counter

words are counted and the custom fonts are there as well

**Comment by BBboy01** [comment]
But custom fonts in `customConfig` doesn't match each other, you configured 6 fonts, but live demo only show 3.

![CleanShot 2024-08-22 at 17 54 26@2x](https://github.com/user-attachments/assets/64db6b2c-b26a-4255-9507-a505cad7bb66)
![CleanShot 2024-08-22 at 17 54 47@2x](https://github.com/user-attachments/assets/f9bc04aa-aaf5-47d6-bdf4-e17a23ac98f6)

**Comment by KillerCodeMonkey** [comment]
yes because whitelist just keeps a list of allowed fonts in general.
just check the template of that editor example. i created a custom toolbar for it ;-)

**Comment by BBboy01** [comment]
> It's weird, this is undefind

this is the problem of chrome development tools, after i closed source map it's worked

Thanks!
