### ISSUE TITLE
formula format content lost format info

### ISSUE THREAD

**Issue by BBboy01** [KillerCodeMonkey/ngx-quill#1925]
The formula content after `this.quillEditor.getSemanticHTML()` lost `class` and `data-value` attrs, after save the content and set that content as new content, formula can't display correctly.

![CleanShot 2024-08-27 at 16 21 17@2x](https://github.com/user-attachments/assets/875a4604-bba0-4c6f-b9a7-7b4843ca1364)

```html
<div><span>\tan\theta = \frac{\triangle y}{\triangle x}=\frac{(y+\triangle y)-y}{\triangle x}</span> -------------------- (2)</div><pre data-language="javascript">
const a = 1;
</pre><div></div>
```

**Comment by KillerCodeMonkey** [comment]
just open an issue on quilljs and or the formular module for it, please.

I want to stick to the best practices for quilljs usages and so i will stick to use getSemanticHtml.

**Comment by BBboy01** [comment]
ok, there are already some issues about it
https://github.com/slab/quill/issues/4289
