### ISSUE TITLE
slow editing after inserting large image

### ISSUE THREAD

**Issue by tsg-tthrash** [KillerCodeMonkey/ngx-quill#1927]
after inserting/pasting a large image into the editor, editing, such as typing is very slow. 

I am testing with this image (copy image and paste into editor): [large test image](https://www.bing.com/images/search?view=detailV2&ccid=F2n8lG77&id=A9F256CAD73E87EE796F52843115A9EC5F4621E4&thid=OIP.F2n8lG77WJwtWolnzDzkEwHaJ4&mediaurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.1769fc946efb589c2d5a8967cc3ce413%3Frik%3D5CFGX%252bypFTGEUg%26riu%3Dhttp%253a%252f%252fwww.publicdomainpictures.net%252fpictures%252f50000%252fvelka%252fgolden-retriever-dog-1370773977VyS.jpg%26ehk%3DbuPtMWyhKNSLmjFTl0UmLGcrLBvHmBElUWcaOSwrlFs%253d%26risl%3D%26pid%3DImgRaw%26r%3D0&exph=1920&expw=1440&q=dog+photo+&simid=608022809940554405&FORM=IRPRST&ck=6C18CE7DAF4CA83AA132C980BEA68C7E&selectedIndex=5&itb=0&cw=1451&ch=860&ajaxhist=0&ajaxserp=0)

I am upgrading from ngx-quill 24 to ngx-quill 26.0.8 (latest) and this was not happening on ngx-quill 24.

I also tested on this demo site, and I'm getting same results: https://killercodemonkey.github.io/ngx-quill-example

I also tested on quill playground site running v2, and it is working there: https://quilljs.com/playground/snow

**Comment by KillerCodeMonkey** [comment]
Could you check the Main versions in between to check when it was introduced?

Only think I can imagine is, that the "getSemanticHTML" api call from quilljs 
V2 is very slow. It is called in ngx-quill on every change. In general you should not use default Image handler of quilljs since it just Puts the base64 representation into the content.

Am 28. August 2024 20:12:17 MESZ schrieb tsg-tthrash ***@***.***>:

**Comment by tsg-tthrash** [comment]
It was introduced with version 25.0.0 and with quilljs v2.

**Comment by KillerCodeMonkey** [comment]
Yep then the usage of getSemanticHTML will be the root cause, and it will not be avoidable.

I guess with large editor content it will getting slower and slower and slower.


Am 28. August 2024 21:38:07 MESZ schrieb tsg-tthrash ***@***.***>:

**Comment by KillerCodeMonkey** [comment]
btw: tested the image on my example demo in "Formula & image resize editor & Keybinding on 'b' and 'shift + b', CodeBlock + Syntax Highlighting" and "default editor with 200px height" without any lagging. (using firefox).

But the main thing changed with the usage of quilljs v2 is that the html content is not just grabbed with "innerHTML", but with the new quilljs API. There the retrieved html is somehow changed and returned by quill.
And this will make it slower than the previous version, but as it is the new way to go with quilljs, i will not change it.

BTW: there are already many open issues with the getSemanticHTML method.

what you can try is to override the "valueGetter" (it is an input). the default one is using the new api and you can just copy and paste the function from the editor component do something else :)

https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill-editor.component.ts#L171

**Comment by KillerCodeMonkey** [comment]
any updates :)?
