### ISSUE TITLE
Encapsulate quill-editor in custom component

### ISSUE THREAD

**Issue by arquadrado** [KillerCodeMonkey/ngx-quill#193]
I have set of input components that implement the ControlValueAccessor so that I can use them with reactive forms. This works by implementing the mentioned interface and then passing the input [value] to the input element and passing a setValue function to the (input) event. The quill editor doesn't have the value attribute so this approach does not work. Is there any workaround for this? Thank you

EDIT: I was able to solve the problem by adding the @Input() decorator to the `content` property directly on the quill-editor component. @KillerCodeMonkey Do you think this has any consequence to the overrall component?

EDIT2: I extended your component and made the `content` property available through an `@Input()` and it works, so far.

**Comment by KillerCodeMonkey** [comment]
Please give me more Info what you want to achieve with that

António Quadrado <notifications@github.com> schrieb am Fr., 8. Juni 2018,
15:24:

**Comment by arquadrado** [comment]
I want a custom component that I can parameterize that uses your ngx-quill-editor component inside. 

Here's the example that I have come up with:
```<div class="custom-rich-text">
  <label class="richt-text-hint focus-label" [ngClass]="{'error': invalid}">{{ lang.trans(fieldName) }}</label>
  <div class="rich-text">
    <app-quill-editor [content]="inputValue" (onContentChanged)="setInputValue($event)" [style]="{height: '200px'}" (onEditorCreated)="setFocus($event)"></app-quill-editor>
  </div>
  <span class="error-message" *ngIf="invalid">{{ lang.trans('required_field') }}</span>
</div>```

and then I can use only my wrapper component like this:

```
<app-custom-rich-text formControlName="body" [fieldName]="'body'"></app-custom-rich-text>
```

**Comment by KillerCodeMonkey** [comment]
Simply Pass down the formcontrolname to the quill-component?

António Quadrado <notifications@github.com> schrieb am Fr., 8. Juni 2018,
16:38:

**Comment by arquadrado** [comment]
It doesn't work that way :( That was the first thing I tried

**Comment by KillerCodeMonkey** [comment]
Because the component does Not Know the parent Form. Try Pass down the
whole formcontrol and setting it with [formControl]="yourControl"

António Quadrado <notifications@github.com> schrieb am Fr., 8. Juni 2018,
17:12:

**Comment by arquadrado** [comment]
Maybe I am doing something wrong but that does not work. [formControl] isn't even a property of the quill-component.

**Comment by KillerCodeMonkey** [comment]
Check Out my example Repo. Ngx-quill is a custom control so it inherits the
Outputs and Inputs of Them.

António Quadrado <notifications@github.com> schrieb am Fr., 8. Juni 2018,
17:31:

**Comment by arquadrado** [comment]
Okay, I will check that out, but for now with extension it works as it should.
