### ISSUE TITLE
Cannot overwrite some styling using ng-deep

### ISSUE THREAD

**Issue by simonximengzhao** [KillerCodeMonkey/ngx-quill#1937]
I tried to use ng-deep to override some styling for the snow theme. However, these are not being able to update. I wanted to change the colors for the placeholder text and the icons on the toolbar. This was working on an older version of ngx-quill.

```
:host ::ng-deep .ql-editor.ql-blank::before {
  content: attr(data-placeholder);
  color: red !important;
}

/* Target all toolbar icons */
:host ::ng-deep .ql-stroke, 
:host ::ng-deep .ql-snow .ql-fill,
:host ::ng-deep .ql-snow .ql-picker-label,
:host ::ng-deep .ql-snow .ql-picker-item {
  color: red !important;
  fill: red !important; /* Change this to your desired icon color */
  stroke: red !important; /* Some icons use stroke instead of fill */
}
```

These are not updated correctly in Angular.
![image](https://github.com/user-attachments/assets/08877bb6-bdf2-4e19-aca4-89878a34e875)

**Comment by KillerCodeMonkey** [comment]
pasted your styling the in the app.component.scss of my demo repo and it is working.

![Bildschirmfoto_20241003_190336](https://github.com/user-attachments/assets/ca52669c-9381-40b7-8699-f73617d6cfc9)

**Comment by simonximengzhao** [comment]
Thanks. I was able to override the style from the global scss.
