### ISSUE TITLE
Version 25 is broken due to formats are converted to object

### ISSUE THREAD

**Issue by visitek** [KillerCodeMonkey/ngx-quill#1939]
```
            let formats = this.formats();
            if (!formats && formats === undefined) {
                formats = this.service.config.formats ?
                    Object.assign({}, this.service.config.formats) : (this.service.config.formats === null ? null : undefined);
            }
```

Quill expects to have array instead of object

**Comment by KillerCodeMonkey** [comment]
if i check the latest v25 version.. everything is fine:
https://github.com/KillerCodeMonkey/ngx-quill/blob/v25.3.2/projects/ngx-quill/src/lib/quill-editor.component.ts#L296

**Comment by KillerCodeMonkey** [comment]
@visitek do you use the latest v25 version?

**Comment by visitek** [comment]
with using injection token, then it goes into the condition above. You can see Object.assign and that's the bug.. It makes object instead of array.. so quill then says forEach is not a function.

**Comment by visitek** [comment]
and yes.. it is in 25.3.2

**Comment by KillerCodeMonkey** [comment]
sorry but i do not see it. i linked the quill-editor component code of v25.3.2 and there is no Object.assign for the formats any more. it was there in earlier version of ngx-quill v25.

Just check the code i linked in my comment.

There arrays are used

**Comment by visitek** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/blob/v25.3.2/projects/ngx-quill/src/lib/quill-view.component.ts

**Comment by KillerCodeMonkey** [comment]
alrighty. the information about the quill view component was missing :)

**Comment by KillerCodeMonkey** [comment]
try v25.3.3 please

**Comment by KillerCodeMonkey** [comment]
@visitek does it work?
