### ISSUE TITLE
Not able to import

### ISSUE THREAD

**Issue by akash-potdar7** [KillerCodeMonkey/ngx-quill#194]
Angular version : 5.2.
ngx-quill version: 3.2

ERROR in ./node_modules/ngx-quill/src/quill.module.ts
Module build failed: Error: /node_modules/ngx-quill/src/quill.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by KillerCodeMonkey** [comment]
Which build process Do You Use?

Akash <notifications@github.com> schrieb am Fr., 8. Juni 2018, 16:09:

**Comment by akash-potdar7** [comment]
I use angular-cli.

**Comment by KillerCodeMonkey** [comment]
I am using it in Demo Repo without any problems

Bengt Weiße <bengtler@googlemail.com> schrieb am Fr., 8. Juni 2018, 16:34:

**Comment by KillerCodeMonkey** [comment]
If You Use angular cli < 6 You need to add the ngx-quill.umd.js to the
Scripts section of the angular-cli.json

Bengt Weiße <bengtler@googlemail.com> schrieb am Fr., 8. Juni 2018, 16:35:

**Comment by akash-potdar7** [comment]
I am using angular cli < 6, so let me add ngx-quill.umd.js to the scripts.
And test it out.

**Comment by akash-potdar7** [comment]
By "angular cli < 6" u mean
"@angular/core": "^5.2.0", or "@angular/cli": "~1.7.2" ?

**Comment by KillerCodeMonkey** [comment]
1.7.2 is the cli Version. I think they Set angular cli Version to 6 with
angular 6. So follow my hint to add ngx-quill to the angular json

Akash <notifications@github.com> schrieb am Fr., 8. Juni 2018, 16:46:

**Comment by afernandez0196** [comment]
Hi, I'm facing a similar issue regarding with `./node_modules/ngx-quill/src/quill-editor.component.ts` 


Bellow is the complete error message: 


`ERROR in ./node_modules/ngx-quill/src/quill-editor.component.ts
Module build failed: Error: C:\Users\Lowksea-i7\Desktop\Portal Repository - Sprint\node_modules\ngx-quill\src\quill-editor.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Lowksea-i7\Desktop\Portal Repository - Sprint\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\Lowksea-i7\Desktop\Portal Repository - Sprint\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in ./node_modules/ngx-quill/src/quill.module.ts
Module build failed: Error: C:\Users\Lowksea-i7\Desktop\Portal Repository - Sprint\node_modules\ngx-quill\src\quill.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign`

I would appreciate a response ASAP, this is a critical error in the implementation into my project. 

Thanks in advance!

**Comment by KillerCodeMonkey** [comment]
Your asap Part is Invalid... Simple remove ngx-quill from Your project ;)
And try to Use native quilljs.

And what build process Do You Use.. Which angular Version, ngx-quill
Version. And so on.

Easiest way i can help, If You Provide an example repo or plunkr. :)

afernandez0196 <notifications@github.com> schrieb am Mi., 22. Aug. 2018,
19:34:

**Comment by afernandez0196** [comment]
Please dismiss my comment! 

I am working with a cloud repository and forgot to update the package.json and package-lock.json files xD that was the root cause. 


Anyway, thanks for your response and great work!

**Comment by oeem1011** [comment]
Iam Using Angular 5 Version. I also get the same error. Which version of ngx-quill is compatible with NG 5?
I installed the ngx 1.60

**Comment by KillerCodeMonkey** [comment]
Even the latest Version is compatible with angular 5. When You this error
You should Check Your build process or how You include ngx-quill.

Emre Öztürk <notifications@github.com> schrieb am So., 2. Sep. 2018, 13:26:

**Comment by oeem1011** [comment]
Okay i will try with the latest version, but your ReadMe telled me this:

for projects using Angular < v5.0.0 install npm install ngx-quill@1.6.0

Let me check it with the 3.0 Version

**Comment by KillerCodeMonkey** [comment]
Right < 5 and >= 5 newer Versions ;)

Emre Öztürk <notifications@github.com> schrieb am So., 2. Sep. 2018, 13:29:

**Comment by denys-aponiuk** [comment]
I've faced the error 
ERROR in ./node_modules/ngx-quill/fesm2015/ngx-quill.js
Module not found: Error: Can't resolve 'quill' in '/home/denys/projects/IDF/wiki-front-end/node_modules/ngx-quill/fesm2015'

I'm using Angular 6 and ngx-quill 4

**Comment by KillerCodeMonkey** [comment]
use the issue search or carefully read the readme... quilljs is now peerDepedency is not installed automatically anymore.. you have to install it on your own
