### ISSUE TITLE
Unable to Load Data into Quill Editor with HTML Format in Angular Form

### ISSUE THREAD

**Issue by hamessoft** [KillerCodeMonkey/ngx-quill#1940]
We are facing an issue where data is not loading into the Quill editor when using the format="html" property. Despite properly binding the form control to the FormGroup, the content is not being displayed within the editor. Below is the relevant code snippet:

```
<quill-editor
    #editor
    format="html"
    formControlName="commentary">
</quill-editor>
```

```
public myForm: FormGroup = new FormGroup({
    commentary: new FormControl('<div>test</div><ul><li>1</li><li class="ql-indent-1">1-1</li><li>2</li><ol><li>numbered</li><li class="ql-indent-1">numbered-1</li></ol></ul><div><br></div>')
});

```

**Expected Behavior:** The Quill editor should load and display the data in HTML format when bound to the `commentary` form control.

**Actual Behavior:** The editor appears, but the data does not load or render inside it, even though the form control is initialized and bound correctly.

**Comment by KillerCodeMonkey** [comment]
Did you check the demo repo: 
https://killercodemonkey.github.io/ngx-quill-example/

and here the code:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/components/reactive-forms/reactive-forms.component.ts

there are working examples for it

**Comment by KillerCodeMonkey** [comment]
any update?
