### ISSUE TITLE
InputSignal<number | undefined> results in InputSignal<number>

### ISSUE THREAD

**Issue by theweinzierl** [KillerCodeMonkey/ngx-quill#1942]
Hey!

I have some typing trouble in my project.

My template looks kind of this:
`<quill-editor [maxLength]=maxLength` ....></quill-editor>

and the code like this:
`@Input() maxLength?: number;`

When I run `ng build` I get the following error: `Type 'number | undefined' is not assignable to type 'number'`

A look into quill-editor.component.d.ts reveals that maxLength is defined as followed:
`readonly maxLength: import("@angular/core").InputSignal<number>;`

Changing the type definition of the input signal to `number | undefined` and my project builds again.

I can see in your code that the signal is defined as `number | undefined` (see: https://github.com/KillerCodeMonkey/ngx-quill/blob/0503a9411d067dc14c652a7b686a97b95a9d54e6/projects/ngx-quill/src/lib/quill-editor.component.ts#L89)

Do you have any idea why the resulting signal does not contain the union type?

I cannot really tell if this is an issue. I found a workaround which is ok for my project (no general fix). But I still wanted to let you now.

Best regards!

**Comment by KillerCodeMonkey** [comment]
ehm i do not know? in general inputs are "optional" in general, since i am not using `input.required()`

maybe angular thinks your are not passing the property at all when it is not "required".
But i wanted to explicit allow undefined as values there.

**Comment by KillerCodeMonkey** [comment]
@theweinzierl as a workaround just pass `0` as fallback

**Comment by KillerCodeMonkey** [comment]
@theweinzierl does it work for your usecase?

**Comment by theweinzierl** [comment]
thanks a lot for your immediate response! Sorry, I had no chance to answer during the weekend. Using `0` respectively default values as fallback sounds like a good idea. I will give it a try tonight and let you know. :)

**Comment by KillerCodeMonkey** [comment]
any update? :)

**Comment by theweinzierl** [comment]
Sorry for letting you wait. Yes, using default values as you suggested, just works fine. Thanks a lot for your help!

I really appreciate your work! :)

**Comment by theweinzierl** [comment]
Sorry for letting you wait. Yes, using default values as you suggested, just works fine. Thanks a lot for your help!

I really appreciate your work! :)
