### ISSUE TITLE
Quill view not rendering embedded videos but instead showing only links

### ISSUE THREAD

**Issue by Oussemasahbeni** [KillerCodeMonkey/ngx-quill#1948]
Im trying to use the videos feature of ngx quill by embedding videos inside a blog post , saving the content as plain HTML and rendering the content using   <quill-view/>

**Angular version :  18.0.1**
    **"ngx-quill": "^26.0.8",
    **"quill": "^2.0.2",****

This is my global qull config: 
```
 provideQuillConfig({
            modules: {
                resize: {
                    locale: {
                        altTip: 'Hold down the alt key to zoom',
                        floatLeft: 'Left',
                        floatRight: 'Right',
                        center: 'Center',
                        restore: 'Restore',
                    },
                },
                toolbar: [
                    ['bold', 'italic', 'underline', 'strike'],
                    [{ header: 1 }, { header: 2 }],
                    [{ align: [] }],
                    [{ color: [] }, { background: [] }],
                    [{ font: [] }],
                    [{ size: ['small', false, 'large', 'huge'] }],
                    [{ header: [1, 2, 3, 4, 5, 6, false] }],
                    [{ direction: 'rtl' }],
                    ['link', 'image', 'video'],
                    ['blockquote'],
                    [{ indent: '-1' }, { indent: '+1' }],
                    ['clean'],
                ],
            },
        }),
```
My create blog component HTML that uses quill editor 

```
<quill-editor
                        [placeholder]="t('blogPlaceholder')"
                        [formControlName]="'content'"
                        [required]="true"
                        [sanitize]="false"
                    />

```
This is saving the embedded videos in this format instead of an iframe 

```
<a href="https://www.youtube.com/embed/I13uAoOGU_4?showinfo=0">https://www.youtube.com/embed/I13uAoOGU_4?showinfo=0</a>
```

its getting saved in that format even tho its showing fine in the quill editor

![image](https://github.com/user-attachments/assets/e3bb8224-8c9a-4700-978d-82e184f6e585)

Later videos are getting rendered  as links instead of iframes 
![image](https://github.com/user-attachments/assets/84d5ebdc-29df-4ab7-ad4c-2c9a1b115efb)

this is my blog details component HTML 

```
                <quill-view class="mt-4" theme="snow" [sanitize]="false" [content]="post.content" [modules]="[]" />

```

**Comment by KillerCodeMonkey** [comment]
This is a known quilljs issue.
There are multiple open issues regarding the html representation.
In general i would not use html to store quill content. use the object/json representation.
And it enables you to have a chance to migrate to newer major quill version or to other wysiwyg editors.

But Check if this is a possible solution for you
https://github.com/slab/quill/issues/4186#issuecomment-2456129257
