### ISSUE TITLE
New Line Created Above Image after Resizing or Clicking (Firefox Only)

### ISSUE THREAD

**Issue by aziz-zina** [KillerCodeMonkey/ngx-quill#1949]
Description: In the Quill editor, while writing a post and uploading an image, pressing "Enter" creates a new line below the image as expected. However, when I click on the image or resize it, pressing "Enter" then creates a new line above the image instead of below. This issue occurs only in Firefox. In other browsers, such as Chrome, Arc, Microsoft Edge, and Opera GX, the expected behavior (new line below the image) works without issues.

Steps to Reproduce:

Open the Quill editor in Firefox.
Upload an image into the editor.
Press "Enter" to create a new line below the image (this works as expected).

![image](https://github.com/user-attachments/assets/539ed10d-e7a0-4ddc-bdce-f4d5d278c3d6)

Click on the image or resize it.
Press "Enter" again.
Expected Behavior: A new line should be created below the image after pressing "Enter."

Actual Behavior: A new line is created above the image after pressing "Enter."

![image](https://github.com/user-attachments/assets/165708ac-d448-44ee-9442-85439cd50550)

However, when clicking the right arrow (when the image is focused), the cursor is moved to the right.
clicking on the right space of the image won't solve the problem.

Browser: Firefox (issue not present in Chrome, Arc, Microsoft Edge, or Opera GX)

Environment:

Quill Editor Version: "ngx-quill": "^26.0.8",
Firefox Version: 132.0.1
Operating System: Windows 11

**Comment by KillerCodeMonkey** [comment]
I guess this is a quilljs issue. Please test , if it occurs with native quill as well

Am 9. November 2024 11:51:22 MEZ schrieb Aziz Zina ***@***.***>:

**Comment by aziz-zina** [comment]
I used this quilljs on firefox: https://quilljs.com/playground/snow
when I click with my mouse on the space in the right, the focus is changed.

**Comment by KillerCodeMonkey** [comment]
But it sounds you are using Image-resize maybe that is causing the issue.

So in general, since I only wrap the native quilljs in an angular component, I guess the problem is not an ngx-quill problem.

I only have custom Focus listeners, that have no Effect to the native cursor Focus behaviour.


Am 9. November 2024 11:58:06 MEZ schrieb Aziz Zina ***@***.***>:

**Comment by aziz-zina** [comment]
I disabled the image resize, but the bug is still there.

![image](https://github.com/user-attachments/assets/6e242d8e-b715-407d-ab14-c9d9f5004b47)

In Firefox, when clicking on the empty area beside the image, the cursor should focus on the right side of the image. However, it consistently focuses on the left side instead.

**Comment by KillerCodeMonkey** [comment]
do you have any addons in your firefox?

when i open my demo repo: https://killercodemonkey.github.io/ngx-quill-example/

there is an example with the angular image and i can just click on the right side of that image. tried it with different images and it works in firefox.

**Comment by aziz-zina** [comment]
Thank you for your help, it's a problem with tailwind, since it's displaying the image in "block" by default.
I changed it using:
.ql-editor img{
      display: unset !important;
}

**Comment by KillerCodeMonkey** [comment]
nice! glad you solved it
