### ISSUE TITLE
Accessing Module's API

### ISSUE THREAD

**Issue by yejodido** [KillerCodeMonkey/ngx-quill#195]
Hi all, I'm looking for the quickest example of how to access an imported module's API, namely https://quilljs.com/docs/modules/clipboard/ so that I can paste HTML back into an editor's instance.

I see mention in the docs of the "modules" like toolbar, but these seem to be simply runtime configs, and I'm looking to access these methods via something like `this.editor.clipboard.dangerouslyPasteHTML`.

Looking through ngx-quill's API I notice that you're using the Quill object itself and multiple modules, but how are these exposed through the ngx-quill editor object?

Thanks,
Joey

**Comment by yejodido** [comment]
Interesting update, it looks like the value bound to the ngModel is actually HTML, which is exactly the use case I was looking for what I posted the question!

One thing to consider is maybe adding a warning or a type given that ngModel is HTML, as this could make it ripe for injection attacks.

I'm still curious about the original question though, how do we expose individual module methods?

**Comment by KillerCodeMonkey** [comment]
The instance is passed on each Output of the component. E.g.
OnEditorCreated or onselectionchanged and so on. Check the readme ;)

Joey Di Nardo <notifications@github.com> schrieb am Sa., 9. Juni 2018,
22:59:

**Comment by yejodido** [comment]
I think so! Thanks. How do you feel about a PR that updates the readme with an example using onEditorCreated for accessing other module API's?

Or maybe a simple getter that returns the instance itself instead of binding to a reactive event?

**Comment by KillerCodeMonkey** [comment]
feel free to add an PR :)
