### ISSUE TITLE
can't delete the pic

### ISSUE THREAD

**Issue by cywforce** [KillerCodeMonkey/ngx-quill#1950]
![微信图片_20241108224649](https://github.com/user-attachments/assets/3b562ae3-bb2c-4f70-8ebc-4dbcc463614d)
![微信图片_20241108224955](https://github.com/user-attachments/assets/a00c2e49-a653-4012-8b8b-6016dcc5a373)

**Comment by KillerCodeMonkey** [comment]
this is an image-resize issue then. deleting images in an editor without image-resize is working as expected.

Open the issue at the correct repo please
