### ISSUE TITLE
quill module config doesn't apply after build app

### ISSUE THREAD

**Issue by tweety18** [KillerCodeMonkey/ngx-quill#1957]
I have such config in my app.module.ts
QuillModule.forRoot({
            modules: {
                toolbar: [
                    ['bold', 'italic', 'underline'],
                    ['clean'],
                    ['link']
                ]
            }
        }),
When i run ng serve all works as expected: i see such toolbar 
<img width="204" alt="Screenshot 2024-12-10 at 12 14 52" src="https://github.com/user-attachments/assets/5f1a1a50-57a9-4b0d-a7f8-a80ea9049181">
So, locally it looks as expected
But when i run build command - the result is without config, I see full toolbar
<img width="722" alt="Screenshot 2024-12-10 at 12 21 56" src="https://github.com/user-attachments/assets/159f1a21-9dce-485f-8bf1-2387a889066c">

**Comment by KillerCodeMonkey** [comment]
since there is no logic to do something else in production builds and it worked for years (hopefully). i would check if you really deployed or started the correct production build.

**Comment by KillerCodeMonkey** [comment]
tested with my demo repo and worked as expected with NgModules and standalone app using provideQuillConfig

**Comment by tweety18** [comment]
is it necessary to use standalone?

**Comment by KillerCodeMonkey** [comment]
nope. but the default and recommended way by angular with v19

**Comment by tweety18** [comment]
i use angular 17.3.7, "ngx-quill": "^25.3.3" and also module-federation v17 without standalone
maybe, it can't work together?

**Comment by KillerCodeMonkey** [comment]
i have not that deep experiences with module-federation, but i do not see why it should not work.

But i guess each lazy loaded Module should have those providers on its own?

**Comment by KillerCodeMonkey** [comment]
if i remember it correctly, i once had mircofrontends and added a "shared" NgModule with defines all the providers and configs used by all.
And then imported this shared module in each microfrontend NgModule.

**Comment by tweety18** [comment]
i find a way out of this issue: just move toolbar config from app module to html template like this 
 <quill-editor
                            [trimOnValidation]="true"
                            [modules]="toolbarConfig"
                            formControlName="description"
                            placeholder="Лише кирилиця"
                            data-auto-id="notif-form-description"
                        ></quill-editor>

public toolbarConfig: {toolbar: string[][]} = {
        toolbar: [
            ['bold', 'italic', 'underline'],
            ['clean'],
            ['link']
        ]};
