### ISSUE TITLE
HTML gets modified by quill

### ISSUE THREAD

**Issue by rajvinavlakha-inventyv** [KillerCodeMonkey/ngx-quill#1958]
I had provided a table to quill editor as content but it git displayed as plain text.
After debugging I came to onow that editor has converted my table into para tag.

I had faced this issue for a large template also.
It removed  some of the styles of indentation, signature and images.

**Comment by KillerCodeMonkey** [comment]
Please check the quilljs repo for the already open issue about losing formattings and so on.

Quill 2 provides an API to get the semantic HTML of the quill editor and this has currently a lot of things that are not working as expected.

And as always:

Do not store HTML in general :). Therefore, you have the object/delta representation.
