### ISSUE TITLE
Issue in rendering "Complex HTML file"

### ISSUE THREAD

**Issue by rajvinavlakha-inventyv** [KillerCodeMonkey/ngx-quill#1959]
I have made a project which uses quill editor.
The features I'm attempting to utilise are as follows:
- Table
- Email Template
- Bill Receipt
I am attaching my project with this.
I would value any assistance.
[quill-demo.zip](https://github.com/user-attachments/files/18240268/quill-demo.zip)
this is the link of the project on stackblitz
https://stackblitz.com/~/github.com/rajvinavlakha-inventyv/quilll-issue-report
p.s switch to master branch for the code

**Comment by KillerCodeMonkey** [comment]
Ask this at quilljs repo.

And you can only use formats quilljs supports per default. 

For any unsupported formats you need to implement a solution on your own or check for third party modules.

And never store HTML. Quill provides an object representation, which is easy to understand and to migrate when switching to other wysiwyg editors.
