### ISSUE TITLE
loosing tags on patchvalue

### ISSUE THREAD

**Issue by Nahask** [KillerCodeMonkey/ngx-quill#196]
Hi,

I faced a problem trying to implement your solution to my web application.

I don't really understand why but when I patch the value of the editor in my formgroup i'm loosing tags each time I patch it. 
In my app, the editor is not directly shown (I do not know if it has something related to this).

I made an example [here](https://codesandbox.io/s/5x1nx6nw6n)

Have a good day :)

**Comment by KillerCodeMonkey** [comment]
Check my example repo, there is also a patch-value example without loosing tags.

I will check your repo, as well.
But maybe you are faster to check the demo :)

**Comment by Nahask** [comment]
I checked the demo and I used `this.editForm.controls["text"].patchValue(this.text);` to update it but it doesn't seem to work as well :x

**Comment by KillerCodeMonkey** [comment]
but it which tags are you losing?

**Comment by Nahask** [comment]
The bug appears when you try to update the same text multiple time  (without reloading the page).
I'm loosing <p> <h> <ol> / <li> (although I didn't test them all)

**Comment by KillerCodeMonkey** [comment]
sorry dude,

i cannot reproduce this, even in your demo.

I added an ul and ol list... clicked submit and edit and submit and edit... nothing gets stiped away.
Everything is there.

Checkout the zip --> it is only a small video, what i did.
[clip.zip](https://github.com/KillerCodeMonkey/ngx-quill/files/2095622/clip.zip)

**Comment by KillerCodeMonkey** [comment]
Could you try to set div-tags as your block-elements instead of p-tags?
```
// override p with div tag
const Parchment = Quill.import('parchment');
let Block = Parchment.query('block');

Block.tagName = 'DIV';
// or class NewBlock extends Block {}; NewBlock.tagName = 'DIV';
Quill.register(Block /* or NewBlock */, true);
```

**Comment by KillerCodeMonkey** [comment]
maybe it has something todo with this: https://github.com/quilljs/quill/issues/1729

**Comment by KillerCodeMonkey** [comment]
I use the clipboard manager to paste content to the editor --> `quill.clipboard.convert(content)`

Seems like chromes clipboard does something strange here

**Comment by Nahask** [comment]
> maybe it has something todo with this: quilljs/quill#1729

Hmm that's, weird sup was one of the tag that still work.
Maybe it have to do with the way chrome handle js and the clipboard.

Anyway i find a workaround by not reseting and repatching the editor when i close it and reopen it 

Anyway thank's for your answers :)
