### ISSUE TITLE
History doesn't work

### ISSUE THREAD

**Issue by dmartmilln** [KillerCodeMonkey/ngx-quill#197]
Hi,
I was making a little text editor and I would like to implement and 'undo' button. 
I take a reference from ngx-quill-example, that it use the Keyboard Module. But in this case with History Module. 

In the example we can see that piece of code:

 `addBindingCreated(quill) {
    quill.keyboard.addBinding({
      key: 'B'
    }, (range, context) => {
      console.log('KEYBINDING B', range, context);
    });
  }`

In my case, using History Module. I had to add it in the constructor:

     `history: {
        delay: 1000,
        maxStack: 500,
        userOnly: true
      }`

And I add a button that clicking on it undo the work done, using `undo()` defined in QuillJS documentation:  [https://quilljs.com/docs/modules/history/](url)

The impelmentation of the button and its function is this:

`<button (click)="undoBt($event)"> UNDO </button>`

`undoBt(quill) {
    quill.history.undo();
  }`

Even so the button doesn't work and the console shows an Error "Cannot read property 'undo' of undefined", when I click on it. 

> AppComponent.html:13 ERROR TypeError: Cannot read property 'undo' of undefined
    at AppComponent.webpackJsonp.239.AppComponent.undoBt (app.component.ts:69)
    at Object.eval [as handleEvent] (AppComponent.html:13)
    at handleEvent (core.js:9953)
    at callWithDebugContext (core.js:11046)
    at Object.debugHandleEvent [as handleEvent] (core.js:10749)
    at dispatchEvent (core.js:7415)
    at core.js:7859
    at HTMLButtonElement.<anonymous> (platform-browser.js:1140)
    at ZoneDelegate.invokeTask (zone.js:367)
    at Object.onInvokeTask (core.js:3662)
    at ZoneDelegate.invokeTask (zone.js:366)
    at Zone.runTask (zone.js:166)
    at HTMLButtonElement.ZoneTask.invoke (zone.js:420)

It seeems that history is undefined. I don't know why with Keyboard Module works well and not for History Module. Did I miss something? Can I do it in a different way?

Have a good day!
David Martínez

**Comment by KillerCodeMonkey** [comment]
I Do Not Know what you Get as $event.
I would Grab the quill instance in the oneditorcreated Output. And Check
this Reference

David Martínez <notifications@github.com> schrieb am Di., 12. Juni 2018,
21:17:

**Comment by KillerCodeMonkey** [comment]
and it is working in general, because ngx-quill is using it internally like

```
this.quillEditor.history.clear();
```
