### ISSUE TITLE
Problem setting html, the paragraphs are joint

### ISSUE THREAD

**Issue by NashIlli** [KillerCodeMonkey/ngx-quill#198]
When I set the html text to ngx quill, the editor joint the paragraphs and eliminate other break lines such as headers (h1, for example). 
The following image shows how the html have to be showed  (html set to a div on its inner html) and how the html text is showed on ngx quill. 
![image](https://user-images.githubusercontent.com/6954280/41318634-5760aa44-6e6f-11e8-9dbc-24389ad137ec.png)

Note: the html text was generated by ngx quill editor.
Edit: I'm using Chrome.

**Comment by KillerCodeMonkey** [comment]
I can Not reproduce this did You tested it with Firefox and Chrome? I
Checked my Demo Repo and everything Works as Expected.

Please Provide a Demo Repo or a live example

NashIlli <notifications@github.com> schrieb am Di., 12. Juni 2018, 23:37:

**Comment by KillerCodeMonkey** [comment]
seems like a problem with chrome --> checkout #196

**Comment by KillerCodeMonkey** [comment]
could you share your code how you set your content?

each .patchValue of a control triggers a quill.clipboard.convert() internally, so the browser clipboard is used. And chrome seems to strip stuff than

**Comment by kedar9444** [comment]
@NashIlli  how to set initial value for the quill editor?

**Comment by Syam** [comment]
Meet a similar issue, paragraphes are "skipped" while loading html data

![image](https://user-images.githubusercontent.com/209219/42338341-c814dc2a-8089-11e8-8ca0-e5c382a21195.png)

Usage:
```
<div class="mat-form-field">
          <label>Message</label>
          <quill-editor theme="snow" [strict]="true" formControlName="Message"></quill-editor>
</div>
```

**Comment by KillerCodeMonkey** [comment]
Do You tested it with Chrome?

Jean Christophe Huwette <notifications@github.com> schrieb am Do., 5. Juli
2018, 19:32:

**Comment by Syam** [comment]
Yes, i am using Chrome `Version 67.0.3396.99 (Build officiel) (64 bits)`

It's working with Firefox.

Is there an official way to store full JSON delta structure instead of plain HTML with `formControl` with this Quill component ?

**Comment by Syam** [comment]
As i wrote on my previous message, it's working on Firefox

I guess using clipboard for loading/storing data is the wrong way.

Quill editor supposed to store/load parchment JSON data structure, not HTML.
And then use a renderer like https://github.com/dchenk/go-render-quill for example. (in a golang context)

It's like using a markdown editor but storing HTML, it does not make sense :(

Maybe call the `valueSetter()` function line 186 will allow devs to customize load/store JSON data instead of HTML:

```
if (this.content) {
      const contents = this.quillEditor.clipboard.convert(this.content); // <= call valueSetter()
      this.quillEditor.setContents(contents);
      this.quillEditor.history.clear();
    }
```

**Comment by KillerCodeMonkey** [comment]
I wrote this angular wrapper for the needs of Mine. Feel free to send me A
PR to allow to Set the in and Output DataType. Like an Input with
Format=html or json. If You Set json, You Use the official was to Set the
Data and retrieve json on changes. And If html the Use Current behavior.

I will need some Timo to looking Info this by my self.

A workaround would be to Pass a ngModel but Manipulate the quill instance
on Your own using the oneditorcreated Output tu Set the correct Current
content and ontextchange Output to Get informed about Updates.

Jean Christophe Huwette <notifications@github.com> schrieb am Do., 5. Juli
2018, 20:54:

**Comment by Syam** [comment]
Make sense, i will submit you a PR !

Anyway, your component is a great base, thank !

**Comment by KillerCodeMonkey** [comment]
checkout v3.3.0 ;)

**Comment by iiceman40** [comment]
Hi there. I am having the exact same problem. I can't update the content of the editor without loosing my h1 tag (chrome only). 

So my input html <h1>Hello</h1><p>World</p>always turns into <p>HelloWorld</p>.

I am using version 4.0.0. Is there a fix or workaround by now that I can use?

**Comment by KillerCodeMonkey** [comment]
I do Not know a fix or workaround. Seems like Chrome strips or sanitizes
the html :(

Am Fr., 9. Nov. 2018, 14:45 hat iiceman40 <notifications@github.com>
geschrieben:

**Comment by iiceman40** [comment]
Thanks for the quick feedback! I wonder why it works when I use the quill editor in a codepen and do the exact same thing: https://codepen.io/iice/pen/JeKKNX

If it is a true chrome issue that shouldn't work either, right?

**Comment by KillerCodeMonkey** [comment]
Because You are Using the AS deprecated marked function
"dangerouslyPasteHtml". You should Not use it. Even the quill creator does
not recommend this way.

My component uses the quill.convert function to Transform HTML to the
correct quill representation. I think this IS using the clipboard. Which
leads to this behavior in Chrome.

If You are Using quilljs You should avoid Working with HTML Strings. Use
Delta / json objects instead. If You are Using HTML IT IS Not garanteed
that your HTML will Work with newer quill Version.

Thats the great Feature of quilljs ;). Bei Update save without creating
hacky patches for your Data :).


Am Fr., 9. Nov. 2018, 14:54 hat iiceman40 <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
Using HTML IS the biggest failure when Using wysiwyg Editors because You
bind your Soul to the Editor. And If You think about IT. You bind your
Project in the worst Case to a specific Editor Version. I was in the
Situation where i Had to Patch Upgrade and replace a wysiwyg edtiro with
another one. IT took month.

You do Not know what people pasted in there and so on.

With the json objects IT is easy going. You have a Not Style/Tag based
representation of the content. Simply writing Patches or migrations. Or
converting to other formats.

Am Sa., 10. Nov. 2018, 00:25 hat iiceman40 <notifications@github.com>
geschrieben:

**Comment by hobojoe** [comment]
> UPDATE
> I think I figured out what the problem is: I am using the editor inside a custom component which is inside of a material tabs group. The tab containing my custom component with the editor is not active when I open the route. The editor component still gets initialized and stays alive during tab changes.
> 
> When I patch the content of the editor while the tab is inactive (for example when the route is opened and all components get initialized) I end up with the problem discussed here. If I switch to the tab that contains my custom component with the editor and patch the value then everything works just fine! O_o
> 
> For now my workaround is to listen to the "selectedTabChange"-Event of the mat-tab-group and trigger a patch for the editor content. I use ViewChild in the parent component (the one with the tabs group) to reference the custom component with the editor and then call a method that executes the patch/content update of the editor. Not quite happy with it since it's a bit of overhead that I would like to avoid but it seems to work for now.

Hi @iiceman40 did you find a different solution for it? I am also facing the same issue and that approach is the cleanest :(

**Comment by iiceman40** [comment]
@hobojoe no, sorry, I did not find a better solution yet I am still using the selectedTabChange event to work around the issue. Let me know if you figure out something better :)

**Comment by sebidev999** [comment]
![image](https://user-images.githubusercontent.com/38624391/58500221-fef8e700-8181-11e9-8097-76d7c9750717.png)
I used ReactiveFormsModule on Angular 4.
As you can see, HTML doesn't apply.

 <quill-editor [style]="editorStyle" formControlName="content"></quill-editor>

Please let me ASAP.

**Comment by KillerCodeMonkey** [comment]
Check quilljs how IT Formats lists and Numbered lists.

Check my Demo Repo. There is a reactive Forms Module example. Add a
Numbered list and You will See You are missing the CSS classes which adds
the correct Styling.

Before inserting the Control value quilljs Transforms the content to a
known Repräsentation. So it could also be that some Tags or Attributes are
stripped If they are unknown to quilljs



sebidev999 <notifications@github.com> schrieb am Di., 28. Mai 2019, 19:54:

**Comment by sebidev999** [comment]
Hi there,
This is the Backend data `"<ol><li>marcel html test</li><li>test</li></ol>"`
After apply this to the editor, it shows like this.
![image](https://user-images.githubusercontent.com/38624391/58566565-2bb80780-8231-11e9-83b2-0443a7d2026d.png)
I already imported the styles.
  <link href="//cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  <link href="//cdn.quilljs.com/1.3.6/quill.bubble.css" rel="stylesheet">
  <link href="//cdn.quilljs.com/1.3.6/quill.core.css" rel="stylesheet">

I'm not sure why the html tags are missed.
What should I add and where?
please help me. This is Angular 4 project.

**Comment by KillerCodeMonkey** [comment]
Like i Said IT seems that HTML does Not come from a quill Editor because
the indention classes are missing. And maybe quilljs Strips the Tags away

Just try to create a Numbered list in my reactive Forms example in the Demo
app and try to Set this content to your Formcontrol.
(Copy the content of the editor or the HTML String)

IT should work. And there You See a Numbered list has the class
"quill-indent-1" in its Li Tags.





sebidev999 <notifications@github.com> schrieb am Mi., 29. Mai 2019, 16:48:

**Comment by KillerCodeMonkey** [comment]
And btw angular 4 and 5 is Not longer supported ;).

Bengt Weiße <bengtler@googlemail.com> schrieb am Mi., 29. Mai 2019, 17:00:

**Comment by sebidev999** [comment]
<quill-editor [(ngModel)]="content"></quill-editor> 
content = '<ol><li>marcel</li><li>test</li></ol>';
I set this value, but it doesn't work on my Angular 5 project.
Is there any other way to solve this issue on the Angular 5 project?

**Comment by KillerCodeMonkey** [comment]
i do not know what you are doing, but i extended my demo repo:
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/reactive-forms

And here: "Reactive Forms and patch value"
https://killercodemonkey.github.io/ngx-quill-example/

Are you sure you have not restricted your allowed formats?

**Comment by Andrey-Nosfer** [comment]
have same problem with reactive forms  Angular 6, only solution i found: patch formControl with HTML string in AfterViewInit lifehook.

setTimeout(() => formControl.patch(blablabla), 0) also works in OnInit lifehook.

**Comment by KillerCodeMonkey** [comment]
@Andrey-Nosfer do you have a little bit more code for me or an example repo or stackblitz?

it is hard to reproduce it, because it is working in my demo repo ;)

And please check latest ngx-quill version.

**Comment by gs-mtripathi** [comment]
Hi @KillerCodeMonkey , I am facing a similar issue where tags are getting stripped. But my case is when you copy paste content into quill editor. For me, it is working fine in chrome. But not in Firefox or Edge.

This is chrome and exactly what I copied.
<img width="937" alt="Screen Shot 2020-06-11 at 5 17 20 PM" src="https://user-images.githubusercontent.com/33310799/84381955-753e7f00-ac07-11ea-9cd8-1b0d1b65d9dd.png">


But firefox seems to be doing it wrong. I see the entire text as `strong`.
<img width="1411" alt="Screen Shot 2020-06-11 at 5 18 40 PM" src="https://user-images.githubusercontent.com/33310799/84382027-a15a0000-ac07-11ea-8747-683044647082.png">

I faced this behavior in your demo app too.


PS: I am trying to copy text from google docs.

**Comment by KillerCodeMonkey** [comment]
yeah but i can not do anything for it.

there should be already some issues in the quill repo.
You can try to add your custom clipboard matchers: https://quilljs.com/docs/modules/clipboard/#api

but at the end you are limited by what the browser and quill allows to paste in ;-)

**Comment by gs-mtripathi** [comment]
I checked other editors where things work just fine. So I am assuming it's not a browser limitation :D

**Comment by KillerCodeMonkey** [comment]
then check quilljs repo. But if it is not a "browser" thing, why it is working in chrome :D.

**Comment by gs-mtripathi** [comment]
Probably there's something that needs to handled explicitly for firefox? :) Only saying this, because I checked 2-3 other RTEs that worked fine

**Comment by KillerCodeMonkey** [comment]
Maybe, but even then quilts would be the correct repo to ask. I do not want to add special workarounds and fixes. 

I just want to provide an easy way to use quill etc. with angular ;-)

**Comment by gs-mtripathi** [comment]
Absolutely. Your app was very helpful, specially around the reactive forms part. Just found this conversation where similar discussion happened, so tried to share my problem. :D
