### ISSUE TITLE
The Ways to Extract the Text From the Editor

### ISSUE THREAD

**Issue by RedCodeXD** [KillerCodeMonkey/ngx-quill#200]
Hi, I was wondering in which ways the texts can be extracted and used from the editor and how you perform them? Is is possible to directly convert to html or rich text? I am moderately new to coding but I am working on an Angular 4 project that is using ngx-quill and wondering if its possible to call on the text retrieval from the component ts/js file where the text editor is going to be or do I need to make a separate component file for the quill editor?

**Comment by KillerCodeMonkey** [comment]
My component Provides some Outputs, E.g. When You change the Text You are
getting informed with the complete editor content as a html string. But
each Output also give You the native quilljs instance. With that You Can
perform all methods documentated on the quilljs Page. Like quill.getText,
or setText

RedCodeXD <notifications@github.com> schrieb am Mo., 18. Juni 2018, 22:50:

**Comment by RedCodeXD** [comment]
awesome, thank you for the info :)

**Comment by KillerCodeMonkey** [comment]
No probs, i like the questions 😁

RedCodeXD <notifications@github.com> schrieb am Di., 19. Juni 2018, 09:59:
