### ISSUE TITLE
Smart table Issue when build project

### ISSUE THREAD

**Issue by gdthakral** [KillerCodeMonkey/ngx-quill#201]
ERROR in Error: Metadata version mismatch for module E:/node_modules/ng2-smart-table/index.d.ts, found version 4, expected 3, resolving symbol

**Comment by KillerCodeMonkey** [comment]
like the error says: ng2-smart-table is the problem

**Comment by gdthakral** [comment]
Please help

**Comment by gdthakral** [comment]
my Package .json
{
  "name": "aianew",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.7",
    "angular2-json2csv": "^1.1.2",
    "angularfire2": "^5.0.0-rc.6",
    "core-js": "^2.4.1",
    "firebase": "^4.10.1",
    "ng2-bs3-modal": "0.10.4",
    "ng2-datetime-picker": "0.15.1",
    "ng2-modal": "0.0.25",
    "ng2-order-pipe": "^0.1.5",
    "ng2-select2": "1.0.0-beta.10",
    "ng2-smart-table": "^1.3.3",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.9",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}
