### ISSUE TITLE
Formatting options (bold, italic) are still blue when I disable it on mobile view

### ISSUE THREAD

**Issue by nbogus** [KillerCodeMonkey/ngx-quill#203]
Hi,
Formatting options (bold, italic) are still blue when I disable it on mobile view.
Steps to reproduce:
1. Open a quill editor on mobile ( or jus mobile view with dev tools)  for  example your demo page with ngx-quill-example
2. Click Bold
3. Write some text
4. Click Bold again to turn off it
5. Bold icon is still blue

**Comment by KillerCodeMonkey** [comment]
Heyho,

thanks for your interest of ngx-quill!

I can reproduce this issue also in a native quilljs editor. 

1. Go to quilljs.com and empty the editor
2. Click Bold
3. Write some text
4. Click Bold again to turn off it
5. Bold icon is still blue

So this should be moved to the issues of quilljs.

**Comment by NBU0** [comment]
Hello @KillerCodeMonkey, 
I was able to reproduce the same issue, I can encounter the issue with all the buttons, after I try to deselect them, they are still blue, I am just wondering that this could be related to the version am I using?

package.json
 
   `"dependencies": {
    "@angular/animations": "19.2.15",
    "@angular/cdk": "19.2.19",
    "@angular/common": "19.2.15",
    "@angular/compiler": "19.2.15",
    "@angular/core": "19.2.15",
    "@angular/forms": "19.2.15",
    "@angular/platform-browser": "19.2.15",
    "@angular/platform-browser-dynamic": "19.2.15",
    "@angular/router": "19.2.15",
    "ngx-quill": "^27.1.2",
    "quill": "^2.0.3"
   [...]
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "19.2.19",
    "@angular/cli": "19.2.19",
    "@angular/compiler-cli": "^19.2.15",
   [...]
  }`

app.config.ts - I am using the Angular standalone features:

`provideQuillConfig({
        modules: {
          toolbar: [
            ['bold', 'italic', 'underline', 'strike'],        
            ['blockquote', 'code-block'],
            ['link'], //, 'image', 'video', 'formula'
 
            [{ 'header': 1 }, { 'header': 2 }],            
            [{ 'list': 'ordered'}, { 'list': 'bullet' }, { 'list': 'check' }],
            [{ 'script': 'sub'}, { 'script': 'super' }],      
            [{ 'indent': '-1'}, { 'indent': '+1' }],        
            [{ 'direction': 'rtl' }],                         
 
            [{ 'size': ['small', false, 'large', 'huge'] }],  /
            [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
 
            [{ 'color': [] }, { 'background': [] }],         
            [{ 'font': [] }],
            [{ 'align': [] }],
 
            ['clean']                             
          ]
        }
      })
 `
I create a custom component to integrate the ngx-quill rich text editor:

`<form [formGroup]="richTextFg">
    <quill-editor #editor
        [required]="true"
        [styles]="{ height: '200px' }"
        formControlName="content"
        ds-form-validation
    ></quill-editor>
</form>`

Thank you in advance!
