### ISSUE TITLE
Uncaught TypeError: Cannot read property 'imports' of undefined

### ISSUE THREAD

**Issue by sairathb** [KillerCodeMonkey/ngx-quill#207]
Hi, I followed the resolution given in the [issue](https://github.com/KillerCodeMonkey/ngx-quill/issues/140) to use the image resize module but I am still getting the error 
"ngx-quill": "^3.2.0",
"quill": "^1.3.6",
"quill-image-resize-module": "^3.0.0"
I am using angular 6.0.7. Can someone please guide me as to what I am doing wrong.

This error occurs when I try to register the ImageResize
`Quill.register('modules/imageResize', ImageResize);`

**Comment by KillerCodeMonkey** [comment]
Do not spam issues, if there are already ones, and this is an image-resize-module problem not ngx-quill

**Comment by faresayyad** [comment]
I have an issue like this, using angular 7 i excactly follow the code in @KillerCodeMonkey  demo. when i tried to run ng build it gives me **

> Cannot read property 'imports' of undefined

**

i figure out that this will not work for some reason, you need to run ng serve OR ng build --prod

**Comment by KillerCodeMonkey** [comment]
Did you cloned my example Repo ? I Run build --prod for every deploy for
the example GitHub Page and IT is working

I think you are Missing quill AS Peer dependency or Provider IT on the
Window object If using Image resize. Checkout the Demo carefully ;)

Am Mi., 30. Jan. 2019, 17:44 hat faresayyad <notifications@github.com>
geschrieben:
