### ISSUE TITLE
Formatting sometimes breaks when populating un-rendered editor in Chrome

### ISSUE THREAD

**Issue by mjgoethe** [KillerCodeMonkey/ngx-quill#210]
In Chrome, under certain circumstances, populating an un-rendered editor with HTML results in many tags getting incorrectly stripped out and lines being joined together.

There are a few different circumstances where I've noticed this. The first time I noticed it happening was using an ngIf around transcluded content with ng-content. I've also seen it sometimes when using an editor within an Angular Material Dialog (https://material.angular.io/components/dialog/overview). I'll provide a rough example of the former and result screenshots further down:

**app.component.ts**
```javascript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
  <app-editor-container #appEditorContainer>
    <app-editor></app-editor>
  </app-editor-container>
  <button (click)="appEditorContainer.open()">Open</button>
`
})
export class AppComponent {
}
```

**editor-container.component.ts**
```javascript
import { Component } from '@angular/core';
import { FormBuilder } from '@angular/forms';

@Component({
  selector: 'app-editor-container',
  template: `
  <div *ngIf="show">
    <ng-content></ng-content>
  </div>
  `
})
export class EditorContainerComponent {
  show = false;

  constructor() {}

  open(): void {
    this.show = true;
  }
}
```

**editor.component.ts**
```javascript
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-editor',
  template: `
  <form [formGroup]="form" >
    <quill-editor *ngIf="true" formControlName="editor" #editor></quill-editor>
  </form>
  `
})
export class EditorComponent implements OnInit {
  form: FormGroup;

  constructor(fb: FormBuilder) {
    this.form = fb.group({
      editor: []
    });
  }

  ngOnInit(): void {
    this.form.controls['editor'].patchValue('<ul><li>test</li><li>test2</li></ul><p><br></p><p><strong>bold test</strong></p><p><em>italic test</em></p><p><u>underline test</u></p><p><s>strikethrough test</s></p><p><br></p><h1>h1 test</h1><p><br></p><h2>h2 test</h2><p><br></p><ol><li>test</li><li>test2</li><li>test3</li></ol><p><br></p><p>subscript<sub>test</sub></p><p>superscript<sup>test</sup></p><p class="ql-indent-1">indent test</p><p class="ql-indent-2">indent again test</p><p class="ql-indent-2"><br></p><p><a href="https://www.google.com" target="_blank">Link test</a></p><p><br></p><blockquote>quote test</blockquote><pre class="ql-syntax" spellcheck="false">code test</pre>');
  }
}
```

In Chrome this renders as:
![image](https://user-images.githubusercontent.com/8163632/42701358-5d44e2da-8694-11e8-9649-c1e85ebdde26.png)

Whereas Edge and Firefox are fine:
![image](https://user-images.githubusercontent.com/8163632/42701408-852dbae2-8694-11e8-962c-90894f8828c1.png)

I've traced the issue down to the clipboard.convert() call. In Chrome, the returned Delta object does not have separate ops with new line characters. This appears to be due to the fact that the current stable version of Quill uses getComputedStyle to determine which elements are displayed as block or list-item. In Chrome, under the aforementioned circumstances, the value of display for these nodes is instead an empty string.

In writing this, I was reviewing the latest Quill source, and it looks like this has been addressed in a recent commit to the dev branch for the upcoming 2.0 release by using hardcoded tags to determine which nodes should form new lines (https://github.com/quilljs/quill/commit/48cd21bab0754ce45c8a88c8f014b3adfcc09d55#diff-17d666047b36e1cb3223a2e3bce28780), but not sure what the timeline is for the stable 2.0 release and when ngx-quill will follow suit.

**Comment by mjgoethe** [comment]
I should also note that I'm currently working around this with a pretty hacky approach: using a combination of *ngIf and [hidden] to make sure the editor has been rendered prior to populating it. It can be tricky to know when this extra cruft is necessary though.

**Comment by KillerCodeMonkey** [comment]
this is a chrome problem and it its clipboard implementation. They are stripping some tags and so not on.

I extended ngx-quill to work with delta objects (content as objects) instead of html-strings. This would be more the intention of using quilljs
