### ISSUE TITLE
Nested Component not responding.

### ISSUE THREAD

**Issue by jberall** [KillerCodeMonkey/ngx-quill#211]
I have a stackblitz set up:
https://stackblitz.com/github/jberall/steve-toolbar?file=src%2Findex.html

When you type in the Quill RTE you'll notice that the form.value is not updated on the inner forms.

In the index I have 
  <script src="//cdn.quilljs.com/1.0.0/quill.min.js"></script>
  <link href="//cdn.quilljs.com/1.0.0/quill.snow.css" rel="stylesheet">
  <link href="//cdn.quilljs.com/1.0.0/quill.bubble.css" rel="stylesheet">

Thanks

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by jberall** [comment]
Sorry for not responding I just got this not.
I have been very busy on a delivery.
Will look into it next week.
I'll try a control value accessor.
