### ISSUE TITLE
Entire editor is incredibly large only in Firefox.

### ISSUE THREAD

**Issue by yharaskrik** [KillerCodeMonkey/ngx-quill#212]
When I load up the demo repository the editors buttons take up an entire page each.

![image](https://user-images.githubusercontent.com/9469090/42896184-fb621e80-8a70-11e8-8a47-ee4acf3b2500.png)

This happens on both the example repo provided and if I try and implement it myself. 

Does not happen on Chrome.

**Comment by KillerCodeMonkey** [comment]
I am always developing in Firefox. But this looks like the theme css is not
loaded at this time for You. Clear Your Cache and try again.

Jay Bell <notifications@github.com> schrieb am Mi., 18. Juli 2018, 18:58:

**Comment by yharaskrik** [comment]
@KillerCodeMonkey cleared all website data then tried again. Did not help. Not sure what could be going on. Any way for me to check in the browser if the theme failed to load?

**Comment by KillerCodeMonkey** [comment]
Just Check Out my example repo and Run it locally,  but even on mobile
Firefox it looks good to me.

Jay Bell <notifications@github.com> schrieb am Do., 19. Juli 2018, 18:08:

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by yharaskrik** [comment]
Hey @KillerCodeMonkey , my apologies, got busy with work that day and forgot to come back to it. I just tried this morning and it does the same thing when running your project locally in firefox.

**Comment by KillerCodeMonkey** [comment]
Strange, i can send You a screenshot how it looks on my Firefox. Maybe You
have some Browser Extension, that could Block the styling.

Jay Bell <notifications@github.com> schrieb am Do., 26. Juli 2018, 17:30:

**Comment by yharaskrik** [comment]
![image](https://user-images.githubusercontent.com/9469090/43272370-aa0c942c-90ae-11e8-9278-07e71096e1c1.png)
Here are the extensions that I have. Maybe I could try launching firefox in safe mode (or whatever they call the mode with no extensions) and see if it works.

could be privacy badger or ublock origin?

**Comment by yharaskrik** [comment]
Yup, disabling addons fixed it. I will do a process of elimination to see what one is causing it.

**Comment by KillerCodeMonkey** [comment]
nice. Glad you got it! I close this issue, but please add a comment with the extension or your way to solve it. Thanks

**Comment by yharaskrik** [comment]
Thanks for the help! For anyone that has the same issue, open firefox in safe mode to make sure it is an addon problem, if it is then repon firefox normally and process of elimination disable addons. In my case it was Privacy Badger, which has caused problems for me in the past.

**Comment by anshumandikshit** [comment]
Hi I am also facing the same issue in every type of browser .I have checked in Chrome ,forefox and Edge .Could not able to fix this issue .Anyone can help me out in this  .I have attached the screenshots .
![Screenshot (278)](https://user-images.githubusercontent.com/12956424/65820430-60bb8180-e246-11e9-8536-00668e7a8ccc.png)

**Comment by KillerCodeMonkey** [comment]
just search through the issues. nothing special you are not loading or importing the quilljs css files correctly.

Just checkout the demo repo and the global style.css and angular.json there ;-).
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/angular.json#L25

**Comment by anshumandikshit** [comment]
Got it bro .Thanks for the help .I guess I was having some issue in css file

**Comment by KillerCodeMonkey** [comment]
no probs
