### ISSUE TITLE
Quill Editor Not Filling Parent

### ISSUE THREAD

**Issue by xTumulus** [KillerCodeMonkey/ngx-quill#213]
I have a quill editor inside a div. The div has a min-height of 350px. For some reason, the Quill Editor will not expand to fill the parent. I am using the default settings without any additional config or styling for quill.

Here is a screen shot with the editor highlighted (They are both white so it is hard to see where the editor ends in a small screenshot):
![quill-snip](https://user-images.githubusercontent.com/21695485/42975322-c3c5718a-8b78-11e8-8d72-09bdffbe0d9f.png)

and the code:
HTML:
```
<h4>Content</h4>
<div class="article-content">
	<quill-editor></quill-editor>
</div>
```
CSS:
```
.article-content{
	background-color: @app-white;
	color: @app-black;
	min-height: 350px;
}
```

**Comment by KillerCodeMonkey** [comment]
Heyho, so i do not know exactly how quilljs is styled, but when I want to change the editor hight, I style it through the .ql-editor or the .ql-container caa-class. e.g. setting editor height to 100% or flex-box layout.

**Comment by aardvark79** [comment]
Setting the .ql-editor and/or .ql-container class height to 100% does not appear to have any effect. It seems to only respond to pixel-based heights, regardless of the parent container height. Do you have a working example of filling the parent container (height: 100%)?

**Comment by xTumulus** [comment]
I have the same issue as @aardvark79. I can't get the height of either class to change with anything other than pixel values.

**Comment by KillerCodeMonkey** [comment]
you should ask this in the quilljs repo. i am not adding any styles to the editor.

i only add a div-block with attribute quill-editor-element
`div[quill-editor-element]`.

And there lives the plain angular container, toolbar and editor in it.

**Comment by xTumulus** [comment]
Got ya. That makes sense. I'll put this question over there. Thanks.

**Comment by KillerCodeMonkey** [comment]
thanks and feel free to post you solution here :)

**Comment by sereneongyy** [comment]
@aardvark79 @xTumulus Hi, i know this thread has been closed a while ago, but I was wondering if you have a solution to this problem? I can't seem to get my editor to fill the full height of my parent. Setting height to 100% does not work, only pixel-based heights do.
