### ISSUE TITLE
Set custom default style

### ISSUE THREAD

**Issue by Kollegos** [KillerCodeMonkey/ngx-quill#214]
I need to set default style for all content inside the editor (i.e. all the text blue, all links bold by default etc.). In original repo have solution like here https://quilljs.com/playground/#custom-fonts. So they create style for `#editor-container` and then put to quill costructor:
```
var quill = new Quill('#editor-container', {
  modules: {
    toolbar: '#toolbar-container'
  },
  theme: 'snow'
});
```

How could I implement the same?

**Comment by KillerCodeMonkey** [comment]
check out the demo repo there is an example like changing default fonts and so on. it works like in the example ;).
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts

And you can simply use all the quilljs apis.

i do not know exactly how classes you need to change for you approach, but maybe you can rebuild it by color your text blue and check, which classes are set.
