### ISSUE TITLE
@type/quill issue

### ISSUE THREAD

**Issue by C00per** [KillerCodeMonkey/ngx-quill#215]
Hi,
I imported Delta `import {Delta} from 'quill';`.
Then I'm trying to create a Delta and getting `ERROR TypeError: quill__WEBPACK_IMPORTED_MODULE_1__.Delta is not a constructor`.

Is there a way to fix this issue?

Thanks

**Comment by KillerCodeMonkey** [comment]
yeah the quill types are a little bit buggy. checkout the definitely typed repo:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/quill

I do not get them working correctly so i go for declaring Quill as any in my files

**Comment by HTanke** [comment]
Is there something new? I'm getting a similar error using Delta in ngx-quill.
Unfortunately I have no idea how to solve this.

**Comment by KillerCodeMonkey** [comment]
And you are using The correct Version of the typings? Should be 1.3.10

HTanke <notifications@github.com> schrieb am Mo., 29. Juni 2020, 15:55:

**Comment by HTanke** [comment]
Switching Version from 1.3.7. to 1.3.10 has no effect. As a precaution I ran recompile, but nothing changed.
