### ISSUE TITLE
onEditorCreated is emitted before content is set

### ISSUE THREAD

**Issue by C00per** [KillerCodeMonkey/ngx-quill#217]
Hi,
It looks like the onEditorCreated event is emitted before the editor's content is set from ngModel.
So when I'm trying to set cursor (selection) at the end of the content, it is not possible: the editor is empty.  Any text and selection  that entered here are overwritten by ngModel binding later;

I'm using the workaround: I'm setting the initial value and selection without ngModel in onEditorCreated. But I think that onEditorCreated should be emitted after setting the content by ngModel binding.

**Comment by C00per** [comment]
The WA doesn't look right, so I decided not to use it.  I checked the source code, and I can see that onEditorCreated is emitted after setting the content. But in fact, it doesn't work that way.

**Comment by KillerCodeMonkey** [comment]
Yeah maybe Your Model is Set After the editor is rendered, E.g. The value
is requested from an api.

Pavel Bunygin <notifications@github.com> schrieb am Do., 2. Aug. 2018,
04:26:

**Comment by KillerCodeMonkey** [comment]
@C00per do you have an idea.

angular intial values for `Inputs` are set before `ngOnInit` (the change detection makes a complete run before) and `ngAfterViewInit` is called after `ngOnInit` in the Lifecycle-Hooks.

So i did not see what can do here.
Are there some special things, when angular sets ngModel?

**Comment by KillerCodeMonkey** [comment]
But it seems to work with reactive forms.

like:

```
<quill-editor [formControl]="myControl" (onEditorCreated)="logInit($event)"></quill-editor>

public logInit(editor: any) {
  console.log(editor.getText())
}
```

**Comment by C00per** [comment]
I'm not using the reactive form functionality:
`    <quill-editor *ngIf="hasRigtToEdit && editMode" [(ngModel)]="title" theme="bubble" format="html" bounds="mat-sidenav-content"
      [placeholder]="'Document title...'" [modules]="titleModules" (onContentChanged)="titleContentChanged($event)" (onEditorCreated)="titleEditorCreated($event)">
    </quill-editor>`
I think it may be the cause. I'll try test with reactive form.

**Comment by KillerCodeMonkey** [comment]
checked it. seems to be a problem with ngModel. No probs with reactiveForms - there does not exist the problem with the ngDirty problem as well. So maybe there is an angular issue for that?

**Comment by C00per** [comment]
Yes, with reactiveForms it works fine. Of course, I was also able to set initial value before setting the clipboard matcher.
