### ISSUE TITLE
Require is not defined - Angular 5 and ngx-quill 2.2.0

### ISSUE THREAD

**Issue by OverSpeed301** [KillerCodeMonkey/ngx-quill#218]
I've installed ngx-quill version 2.2.0 (strict, the last to be supported for Angular 5). In the developper console of my browser I see this : 

```
quill.module.ts:13 Uncaught ReferenceError: require is not defined
   at Object.__decorate (quill.module.ts:13)
   at __webpack_require__ (quill.module.ts:13)
   at Object.<anonymous> (quill.module.ts:13)
   at __webpack_require__ (quill.module.ts:13)
   at Object.__decorate (quill.module.ts:13)
   at __webpack_require__ (quill.module.ts:13)
   at quill.module.ts:13
   at quill.module.ts:13
   at webpackUniversalModuleDefinition (quill.module.ts:13)
   at quill.module.ts:13
````
It does not stop the execution of the page and Quill is working fine but I see this error on the developper console.

Thanks,

**Comment by KillerCodeMonkey** [comment]
could you provide an example repo, how do you include the project?

Maybe it has something todo with your buildprocess

**Comment by OverSpeed301** [comment]
In order to install ngx-quill I do the following : 

1. Install ngx-quill with `npm install ngx-quill@2.2.0`
2. Adding JS and styles import in .angular-cli.json : 

```
      "styles": [
[...]
        "styles/quilljs/quill.bubble.css",
        "styles/quilljs/quill.snow.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/ngx-quill/bundles/ngx-quill.umd.js",
        "../node_modules/quill/dist/quill.js"
      ],
```
3. In my module I imported QuillModule
4. In my component, I've just placed `<quill-editor [...]></quill-editor>`.

I can setup a repo if you want, but I am agree with you about my buildprocess but it's not so special compared to other Angular projects :/.

**Comment by KillerCodeMonkey** [comment]
try to remove "../node_modules/ngx-quill/bundles/ngx-quill.umd.js", from the scripts and simply import it.

**Comment by KillerCodeMonkey** [comment]
btw. you can also use newer ngx-quill versions. >1.6.0 for angular 5 and >= 3.0.0 for angular 6. so 3.0.0 and above should also work with angular 5 ;)

**Comment by KillerCodeMonkey** [comment]
but if you are using angular-cli version >= 6 you do not need to add ngx-quill to the scripts section in the config file.

**Comment by OverSpeed301** [comment]
I just removed ngx-quill.umd.js and the problem gone away. What's this file ? I'm curious. :)
Also, I updated to 3.0.0 and it works like a charm. Thanks you for your patience !

**Comment by KillerCodeMonkey** [comment]
some buildprocess only allow to use already compiled dependencies, like systemjs ;).

So precompiled version to use is sometimes not bad at all :)
