### ISSUE TITLE
Setting modules input results in error

### ISSUE THREAD

**Issue by netopolit** [KillerCodeMonkey/ngx-quill#22]
Setting modules input causes error `quill Cannot import modules/0. Are you sure it was registered?` .
My exaple is:
`<quill-editor formControlName="journalEntry"  modules="{toolbar: [['bold', 'italic', 'underline', 'strike']]}")
</quill-editor>`

Thank you

**Comment by KillerCodeMonkey** [comment]
which version are you using?

**Comment by netopolit** [comment]
Version 1.0.2 with quill 1.2.2 automatically installed as dependency.

**Comment by KillerCodeMonkey** [comment]
simple:

in angular2 you have these syntax:

```
<xxx modules="StringValue">
<xxx [modules]="Expression">
<XXX (event)="eventHandler()">
```

You want to pass a javascript object, so you want to write this expression on the input/attribute "modules".

But in your case --> you simple put the string "{toolbar: [['bold', 'italic', 'underline', 'strike']]}" on it. And quill/ngx-quill can not handle a simple string as config object.

So for you --> add [] to the modules input/attribute:

```
<quill-editor formControlName="journalEntry" [modules]="{toolbar: [['bold', 'italic', 'underline', 'strike']]}"></quill-editor>
```

Please close this issue if you solved it

**Comment by netopolit** [comment]
It works. Sorry for all the confusion. Funny thing is that I know all of that and I couldn't see it. Must have been end of the workday loss of concentration  :)

Thank you

**Comment by test0017** [comment]
Its not working for me in Angular5
I have added as you added above .
[modules]="{toolbar: [['bold', 'italic', 'underline', 'strike']]}" but not working.
Also I have tried with config within app.module.ts but not working.
Thanks

**Comment by KillerCodeMonkey** [comment]
Which ngx Version and angular Version do You use. Like i wrote. I use this
in my example repos and everything IS Working...

So maybe You should Check your Javascript console for Errors..

Maybe You forgot to Install quilljs AS Peer dependency

Am Mi., 12. Dez. 2018, 13:51 hat test0017 <notifications@github.com>
geschrieben:

**Comment by test0017** [comment]
Now When i have used  "ngx-quill": "^4.4.2" its working while in previous version its showing quil editor-toolbar problem .
Thanks 
I have only one question 
I think its the update version of ngx-quill-editor so what is the reason behind you have update the name ngx-quill-editor to ngx-quill.
Thanks

**Comment by KillerCodeMonkey** [comment]
i think ngx-quill and ngx-quill-editor or different npm packages ;)
https://www.npmjs.com/package/ngx-quill

and 
https://www.npmjs.com/package/ngx-quill-editor

**Comment by test0017** [comment]
ok fine .
