### ISSUE TITLE
Binded value is not changed if onContentChanged output is not used

### ISSUE THREAD

**Issue by C00per** [KillerCodeMonkey/ngx-quill#220]
I'm using reactive forms.
`      <quill-editor formControlName="text" theme="bubble" format="html" bounds="mat-card-content" [placeholder]="'Section content...'"
        [modules]="contentModules" (onContentChanged)="textContentChanged($event)" (onEditorCreated)="textEditorCreated($event)">
      </quill-editor>`
If I remove ` (onContentChanged)="textContentChanged($event)"` and change a text in the quill then a binded value is not changed and  a form is still pristine as well until the quill losts focus or I click on another part of the text in the quill.  
After that, if I perform some changes again, the binded value won't be changed until the quill lost focus or I click on another part of the text in the quill.

**Comment by KillerCodeMonkey** [comment]
So i think then you should share some more code

Checkout my demo repo:
There is an editor with 
`Reactive Forms and patch value` as title.

If you type something you can see resulted control-value above the editor... without onContentChange
https://killercodemonkey.github.io/ngx-quill-example/

I am using the `[formControl]="xxx"` syntax, but i tested it locally and the `formControlName` works, too.

but keep in mind, if you are using `formControlName` you need to wrap your editor in a `<form [formGroup]="yourFormGroup">`

**Comment by C00per** [comment]
It was my mistake, sorry.
I used ` changeDetection: ChangeDetectionStrategy.OnPush` in my component.
