### ISSUE TITLE
themeing ngx-quill

### ISSUE THREAD

**Issue by chantimothy** [KillerCodeMonkey/ngx-quill#222]
Hello:

I am wondering if you can give me a quick example on how to theme the editor. For some reason whatever I throw at the css (eg. ql-container, ql-editor), the style doesn't seem to change at all. All other elements takes the effect but the editor.

Thank you for your time.

Tim

**Comment by KillerCodeMonkey** [comment]
i do some styling in the demo repo:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts#L101

maybe your css-selectors are not enough to override the standard themening ;)
Check the CSS-Properties and selectors in your developer console in the browser.

There you can grab the selector for the attribute you want to override.

**Comment by chantimothy** [comment]
Thank you for the quick respond.

The selector was inhered from div.ql-container.ql-bubble.ql-disabled.
When I do modify the ql-container in the dev console, the style does indeed change, I just couldn't override it in my css.

Tim

**Comment by chantimothy** [comment]
I flipped through the issues on your repo and 1 suggested a solution like "#id /deep/ .ql-container" and this works. Thanks very much for your attention. but that leads me to a question: why simply ".ql-container" doesn't work?

**Comment by KillerCodeMonkey** [comment]
Because of components viewencapsulation.

chantimothy <notifications@github.com> schrieb am Di., 7. Aug. 2018, 19:34:

**Comment by KillerCodeMonkey** [comment]
Btw please Use ::ng-deep, because /deep is deprecated i think ;)

Bengt Weiße <bengtler@googlemail.com> schrieb am Di., 7. Aug. 2018, 19:38:

**Comment by chantimothy** [comment]
Thank you very much for the suggestion. I am still quite new to all this . I will read more on viewencapsulation as suggested.
