### ISSUE TITLE
Test with Jest fails.

### ISSUE THREAD

**Issue by eduardo704** [KillerCodeMonkey/ngx-quill#223]
Hi I am having trouble running my tests with jest in the components that import the ngx-quill.
The problem seems related to [41](https://github.com/KillerCodeMonkey/ngx-quill/issues/41). Without any extra configuration I get the following error:

`

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://facebook.github.io/jest/docs/en/configuration.html

    Details:

    C:\dev\sales-hub-ui\node_modules\ngx-quill\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './src/quill.module';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      20 | import { PhoneInputComponent } from './phone-input/phone-input.component';
      21 | import { HtmlTextareaComponent } from './html-textarea/html-textarea.component';
    > 22 | import { QuillModule } from 'ngx-quill';
         |                   ^
      23 |
      24 | @NgModule({
      25 |     imports: [

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:402:17)
      at Object.<anonymous> (libs/common/form-fields/src/lib/form-fields.module.ts:22:19)
`

I tried some different approaches like mocking the module in the jest configuration, or importing it from the bundles. But they throw different error messages. I also tried adding ngx-quil to the transformIgnorePatterns config as the error message suggests but also didn`t work.

I am using angular 6 and couldn't find any extra config on th angular.json file that could help. Please let me know if you need any extra information. Thanks a lot.

**Comment by KillerCodeMonkey** [comment]
what happens if you try to import the QuillModel from 'ngx-quill/src/quill.module' ???

seems like jest grabs the index.js  instead of the index.ts

**Comment by KillerCodeMonkey** [comment]
Could you create or share an example repo. Where I can test it?

**Comment by KillerCodeMonkey** [comment]
because if compiling in dev mode and maybe production build works, it has something todo with your jest setup.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by camdenbrown** [comment]
@KillerCodeMonkey I had a similar issue and posted #236 . When I point the package.json to the compiled version of index.js everything works fine. As I mentioned there, I am not sure if this is good practice or there is a more correct way of doing this.

**Comment by KillerCodeMonkey** [comment]
I thought You should change Your build for testing to create commonjs
modules or Not.

Camden Brown <notifications@github.com> schrieb am Do., 30. Aug. 2018,
21:58:

**Comment by camdenbrown** [comment]
@KillerCodeMonkey You are correct. For some reason, I was unable to get `babel-jest` to compile it. I'm still looking into a solution for that. However, you only really should ever have to do that for packages that don't offer a transpiled version, which `ngx-quill` does offer but the `package.json` wasn't pointed at.

**Comment by camdenbrown** [comment]
@eduardo704 If you're still having issues feel free to post here but as @KillerCodeMonkey has mentioned you should be able to run Babel locally with Jest to transform any es6 packages that are in your `node_modules`

**Comment by Madhusudhan1995** [comment]
**@KillerCodeMonkey** You are correct. For some reason, you can try once 
1.  Go to node modules 
2. Search "material-ui-slider" inside "es5" file open .
3. Open index.js
4.  Comment the export * from './src ';
Know it's working fine.......
