### ISSUE TITLE
Test fails when using Quill.register

### ISSUE THREAD

**Issue by lunanigra** [KillerCodeMonkey/ngx-quill#227]
Hello,

Thanks for your nice editor integration.

We added ngx-quill to one of our projects and also included your counter example. Therefore we are registering the counter by using following code...

```
Quill.register('modules/counter', Counter);
```

This works find; except that tests are failing with an unclear error. Without including the counter module tests are running successful.

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ProductsCreateComponent should create FAILED
	TypeError: undefined is not an object (evaluating 'quill_1.default.register') in http://localhost:9876/_karma_webpack_/main.js (line 780)
```

Any idea what might be missing?

Perhaps your can update your test and also show an example for Quill.register (e.g. for using the counter module)?
https://github.com/KillerCodeMonkey/ngx-quill/blob/develop/src/quill-editor.component.spec.ts

Thanks, JC

**Comment by KillerCodeMonkey** [comment]
sry. did you solved it? maybe your test env does not know quill, so you should mock it or provide it in your tests.

**Comment by lunanigra** [comment]
Hi, thanks for the reply. So far no update... Basically tests are working; but not when adding the Counter module.

I assume it is something small/simple... Just don't know what...

If you there is some time perhaps you can add tests to your ngx-quill-example project?
I will try again... Any suggestion how to mock it would be welcome.

**Comment by Simon245** [comment]
@lunanigra Did you find a fix for this? 
I am having trouble with my tests as well.
I have Quill and the resize module working fine in my app, it's just breaking my tests.
My original error in karma was

>   {
    "message": "An error was thrown in afterAll\n[object ErrorEvent]",
    "str": "An error was thrown in afterAll\n[object ErrorEvent]"
  }

The line for me that is causing this issue is registering the imageResize module in my component
`Quill.register('modules/imageResize', ImageResize);`

If I remove that my tests work again.

**Comment by Simon245** [comment]
> @lunanigra Did you find a fix for this?
> I am having trouble with my tests as well.
> I have Quill and the resize module working fine in my app, it's just breaking my tests.
> My original error in karma was
> 
> > {
> > "message": "An error was thrown in afterAll\n[object ErrorEvent]",
> > "str": "An error was thrown in afterAll\n[object ErrorEvent]"
> > }
> 
> The line for me that is causing this issue is registering the imageResize module in my component
> `Quill.register('modules/imageResize', ImageResize);`
> 
> If I remove that my tests work again.

I managed to fix this after reading [this post](https://github.com/kensnyder/quill-image-resize-module/issues/16#issuecomment-392150611)

Here is my [Stackoverflow](https://stackoverflow.com/questions/58837396/ngx-quill-and-quill-resize-module-in-jasmine-tests/58862695#58862695) question with answer.

**Comment by KillerCodeMonkey** [comment]
If everybody would Check the Demo Repo linked in the readme ... You would
See how IT works :)



Simon Ball <notifications@github.com> schrieb am Do., 14. Nov. 2019, 18:38:
