### ISSUE TITLE
Having problems importing tables from Word

### ISSUE THREAD

**Issue by john88benson** [KillerCodeMonkey/ngx-quill#228]
Hi,

We are using ngx-quill in a custom angular Form for entering rich content into SharePoint.  Currently it seems unable to interpret tables from a Word Document.  Is there another format the document can be converted into before copying the content in that would preserve the table formatting?  Or the ability to toggle and edit the raw HTML prior to saving?

Cheers,

-JB

**Comment by KillerCodeMonkey** [comment]
Convert it before You Set IT on Your Form? Like i Know There is no Table
representation in quilljs.



John Benson <notifications@github.com> schrieb am Di., 14. Aug. 2018, 22:24:

**Comment by john88benson** [comment]
Hi,

Just to clarify, it isn't an issue with copying the content out of a Word Doc, quilljs does will not interpret a table into HTML?

Thanks for the fast response.

Cheers,
-JB
