### ISSUE TITLE
getting quill instances when quills are initialized in for-loop

### ISSUE THREAD

**Issue by habakuk23** [KillerCodeMonkey/ngx-quill#230]
Dear KCM! 

We are using ngx-quill together with ngx-bootstrap's tabs in our project (code & screenshot below).  
Quills are created within a for loop when iterating through the existing tabs. 

When we use (onEditorCreated)-event and pass the $event we get multiple instances of the quills of each tab. 

Everytime we switch from one tab to another tab, the event (onEditorCreated) of course wont be initialized and we only get the last instance.

How can we access a particular instance?
What is the best approach with ngx-quill in for loops? 

Any help would be greatly appreciated..

Here's part of the code:

****************************************************************************************************

<tab *ngFor="let tab of tabs; let i=index" [active]="tab.active" (select)="onSelectTab(tab,$event)" (deselect)="tab.active = false"
    [disabled]="tab.disabled" [customClass]="tab.customClass">
    <ng-template tabHeading>{{tab.tabname}} &nbsp;&nbsp;
        <i class="fa fa-times" *ngIf="hasPrivileges && buttonDeaktivieren" (click)="openDeleteTabModal(template,tab,$event)"></i>
    </ng-template>

    
    <div class="quill-editor">
        
        <quill-editor #editor [(ngModel)]="tab.tabcontent" [readOnly]="canEditQuill" (keyup)="quilEdited($event)" (click)="catchRange()"
            (onEditorCreated)="createdQuill($event,i)" theme="snow">

            
            <div quill-editor-toolbar class="quilltoolbar">
            </div>
            
        </quill-editor>
        
    </div>

</tab>

**************************************************************************************

And a screenshot:

![screenshot_quill_01](https://user-images.githubusercontent.com/38154253/44338916-da980d80-a47f-11e8-8950-b3092b56df11.JPG)

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by habakuk23** [comment]
Hi KCM!

Thank you for your advice, we store the instance now in the tab Object as well like you suggested and got it working fine now ;)

Best regards and thanks again for your quick response!
