### ISSUE TITLE
How to enable autofocus?

### ISSUE THREAD

**Issue by hijoncon** [KillerCodeMonkey/ngx-quill#233]
Is there any way or workaround I can integrate autofocus?

**Comment by KillerCodeMonkey** [comment]
i would say - listen on onEditorCreated output and call the `focus()` function on the quill-editor instance you yet with the output.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by yharaskrik** [comment]
@KillerCodeMonkey Update on this (not the original poster), I am able to get the focus on the editable div for a second but then it loses focus and the font selector gets the focus.

This:
```this.elementRef.nativeElement.querySelector('div.ql-editor').focus();```
Is called on (onEditorCreated).

**Comment by krishnaanaril** [comment]
Thanks to @KillerCodeMonkey. This is how i did: 
component.ts
```
editorCreated(editor) {    
    editor.focus();    
  }
```

**Comment by KillerCodeMonkey** [comment]
Yep, Like it is implemeted and shown in the example Repo and live Demo ;)

Krishna Mohan <notifications@github.com> schrieb am So., 18. Aug. 2019,
11:44:
