### ISSUE TITLE
Feature Request: Tooltips for toolbar buttons

### ISSUE THREAD

**Issue by MHillier98** [KillerCodeMonkey/ngx-quill#235]
This is something that is currently possible with QuillJS, as seen [here](https://quilljs.com/playground/#snow-toolbar-tooltips). Is this something that could please be added? Or maybe I've just missed something in adding this to my project and it already exists.

**Comment by KillerCodeMonkey** [comment]
same as in the quill example. simply use ngx-quill - and after onEditorCreated is called you can select all tooltip elements and enable them.

But instead of jquery use plain js or the angular way to do this. but i can consider to add an option to enable tooltips in an easier way. like an input

**Comment by Hubertformin** [comment]
It doesn't work, I get an error with the current Jquery snippet

**Comment by jdgamble555** [comment]
Just adding here that you can easily add tootips with **matTooltip**.

```typescript
<button class="ql-list" value="bullet" matTooltip="Bullet List"></button>
```

**Comment by KillerCodeMonkey** [comment]
sure it is easy with matTooltip, but everybody needs to add material then

You could even try to build your own tooltip directive wrapping matTooltip, but use the selector of the directive to something like `button.ql-xxxx`

**Comment by pinich** [comment]
Thanks for sharing @marceloloureiro !!!
Here is an `scss` version of your example with minor tweaks.
`
/** All toolbar buttons are inside of .ql-formats */
.ql-formats button {
    position: relative;

    /** Set a tooltip with css pseudo-elements, when buttons are hover, active or focus  */
    &:hover::after,
    &:active::after,
    &:focus::after {
        background: #0d1e42;
        color: white;
        padding: 0.5em;
        border-radius: 0.4em;
        top: -120%;
        left: -10px;
        z-index: 999999;
        position: absolute;
        font-size: 12px;

    }
}
/** Set tooltip content for bold button **/
.ql-bold {
    &:hover::after,
    &:active::after,
    &:focus::after {
        content: "Bold";
    }
}

.ql-italic {
    &:hover::after,
    &:active::after,
    &:focus::after {
        content: "Italic";
    }
}

.ql-underline {
    &:hover::after,
    &:active::after,
    &:focus::after {
        content: "Underline";
    }
}
.ql-strike {
    &:hover::after,
    &:active::after,
    &:focus::after {
        content: "Strikeout";
    }
}
.ql-link {
    &:hover::after,
    &:active::after,
    &:focus::after {
        content: "Hyperlink";
    }
}
.ql-blockquote {
    &:hover::after,
    &:active::after,
    &:focus::after {
        content: "Quote";
    }
}
.ql-list[value="bullet"] {
    &:hover::after,
    &:active::after,
    &:focus::after {
        content: "Bulleted List";
        top: -200%;
    }
}
.ql-list[value="ordered"] {
    &:hover::after,
    &:active::after,
    &:focus::after {
        content: "Numbered List";
        top: -200%;
    }
}
`

**Comment by watevadafa** [comment]
> I've achieved this by doing a simple css hack.
> 
> ```css
> /** All toolbar buttons are inside of .ql-formats */
> .ql-formats button {
>   position: relative
> }
> ​
> /** Set a tooltip with css pseudo-elements, when buttons are hover, active or focus  */
> .ql-formats button:hover:after,
> .ql-formats button:active:after,
> .ql-formats button:focus:after {
>     position: absolute;
> ​    background: black;
>     color: white;
>     padding: .5em;
>     border-radius: .5em;
>     left: -50%;
>     top: 100%;
>     width: max-content;
>     z-index: 1;
> }
> ​
> /** Set tooltip content for bold button **/
> .ql-bold:hover:after,
> .ql-bold:active:after,
> .ql-bold:focus:after {
>    content: 'Put here your hint to the Bold button';
> }
> ​
> /** Set tooltip content for Italic button **/
> .ql-italic:hover:after,
> .ql-italic:active:after,
> .ql-italic:focus:after {
>    content: 'Put here your hint to the Italic button';
> }
> 
> /** repeat foreach button in toolbar */
> ```
> 
> Suggestion: If you do it using SASS you problably gonna write less code.

This is amazing, but for some reason the scss break when used with ql-image, I wanted to mentioned content like "Attach Images" looks like this 
<img width="239" alt="image" src="https://github.com/KillerCodeMonkey/ngx-quill/assets/28387128/24d9651f-2682-4ad8-a13e-ce21c1f113e1">
