### ISSUE TITLE
Caret Position

### ISSUE THREAD

**Issue by eduardogoncalves01** [KillerCodeMonkey/ngx-quill#239]
How can I get the caret position from the text area? Quill doesnt have support for that ?

**Comment by KillerCodeMonkey** [comment]
Onselectionchanged is the Output You are looking for i think.

eduardogoncalves01 <notifications@github.com> schrieb am Fr., 31. Aug.
2018, 15:49:

**Comment by eduardogoncalves01** [comment]
Right, that helped me a lot. 
Sorry for my inexperience, but I need another help!
How is the string cleaning procedure performed? 
For example, string between <strong> Some String here </ strong>, you can render the string without the tags

**Comment by KillerCodeMonkey** [comment]
I Do Not Know. Thats more build into plain quilljs.

eduardogoncalves01 <notifications@github.com> schrieb am Fr., 31. Aug.
2018, 23:30:
