### ISSUE TITLE
Adding custom button/s

### ISSUE THREAD

**Issue by miff** [KillerCodeMonkey/ngx-quill#24]
Hi there,
how to add new buttons and functionality?
Thanks

**Comment by KillerCodeMonkey** [comment]
like you would do it with quilljs:
https://quilljs.com/guides/how-to-customize-quill/#content-and-formatting

With ngx-quill you can create your own toolbar if you want:
https://github.com/KillerCodeMonkey/ngx-quill#config

And here you can see some configurations in actions:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts

https://killercodemonkey.github.io/ngx-quill-example/
