### ISSUE TITLE
automatic add hyperlink

### ISSUE THREAD

**Issue by nickykiet83** [KillerCodeMonkey/ngx-quill#240]
Hi,

In case I copy a hyperlink text: https://abc.com

ngx-quill can auto convert that to the hyperlink?

**Comment by KillerCodeMonkey** [comment]
If quilljs can’t do it -so ngx-quill can’t :)

**Comment by nickykiet83** [comment]
no, not yet. I need to touch to the core of quilljs to resolve this, or create a plugin...

**Comment by argelj289** [comment]
any update from this? is auto convert text to hyperlink possible with this plugin?
