### ISSUE TITLE
Initializing in Ionic

### ISSUE THREAD

**Issue by ShaneMosley** [KillerCodeMonkey/ngx-quill#244]
I am really struggling trying to get this to work in my Ionic 3 app... I've tried following your example Repo and researched a ton about making Quill work with Typescript. It would mean the world to me if you can give me the absolute basic setup for getting this to work. I keep getting runtime errors trying to load quill-editor component.

I have imported the QuillModule in my app.module.ts file. 

In my home.ts file, I have added the imports:
import { QuillEditorComponent } from 'ngx-quill/src/quill-editor.component';
import * as Quill from 'quill';

I have updated the package.json file in Quill to include Typescript from other GitHub discussions.

Then I have tried many different variations of initializing the editor, including your component style of quill-editor, and have ran into every error possible it seems like. 

I hope you can help with just getting the editor up and rolling in my app. I'm sure I can take it from there. :)

ps. Both imports are importing properly because I can see them when I console.log them out

**Comment by KillerCodeMonkey** [comment]
hey, i am very busy at the moment. i have to check if i can tackle this this week.

Maybe you can create an example repo with you try to use ngx-quill with ionic?

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill-ionic-v3

**Comment by ShaneMosley** [comment]
Bengt!! Thank you so much for putting this together! I was going to open a Git but my week has been crazy busy too. I greatly appreciate this. I’m going to test this out now and get back with you!

Thanks!
Shane Johnson

**Comment by ShaneMosley** [comment]
Brother, I can’t thank you enough! I was barely off, but was also way overthinking it. I have it working now. I really appreciate your time!!

Thanks!
Shane Johnson

**Comment by KillerCodeMonkey** [comment]
no probs ;)
