### ISSUE TITLE
What is the "quill-editor-toolbar" equivalent for color pickers

### ISSUE THREAD

**Issue by bogacg** [KillerCodeMonkey/ngx-quill#245]
I wanted to make custom toolbar with `title` properites so I've used the example provided:
```
<quill-editor>
  <div quill-editor-toolbar>
    <span class="ql-formats">
      <button class="ql-bold" [title]="'Bold'"></button>
    </span>
    <span class="ql-formats">
      <select class="ql-align" [title]="'Aligment'">
        <option selected></option>
        <option value="center"></option>
        <option value="right"></option>
        <option value="justify"></option>
      </select>
      <select class="ql-align" [title]="'Aligment2'">
        <option selected></option>
        <option value="center"></option>
        <option value="right"></option>
        <option value="justify"></option>
      </select>
    </span>
  </div>
</quill-editor>
```
While it works great for given axample I couln't figure what HTML element corresponds for **color pickers** 

I've tried this: 
 `<button class="ql-color ql-picker ql-color-picker" [title]="'Char Color'"></button>` with no luck.

**Comment by KillerCodeMonkey** [comment]
I think You Can Check Out the example on quilljs Website and copy the html
for the colorpicker.

Or create it with ngx-quill and a toolbar config passed to the components.
And copy the html from it.

Bogac Guven <notifications@github.com> schrieb am So., 16. Sep. 2018, 23:40:

**Comment by bogacg** [comment]
Wow, you are right, I didn't expect it would be this easy:

```
<span class="ql-formats">
  <select class="ql-color" [title]="'Char color'">
  </select>
  <select class="ql-background" [title]="'Bg color'">
  </select>
</span>
```
I didn't expect it could be just a `select` element with options, then a search on **quilljs** and [I saw this example](https://github.com/quilljs/quill/issues/917).

**Comment by JayawardanaJTH** [comment]
> Wow, you are right, I didn't expect it would be this easy:
> 
> ```
> <span class="ql-formats">
>   <select class="ql-color" [title]="'Char color'">
>   </select>
>   <select class="ql-background" [title]="'Bg color'">
>   </select>
> </span>
> ```
> 
> I didn't expect it could be just a `select` element with options, then a search on **quilljs** and [I saw this example](https://github.com/quilljs/quill/issues/917).


My problem solved this example, Thank you
