### ISSUE TITLE
Quill Editor doesnt work in angular cli prod build

### ISSUE THREAD

**Issue by joromecox** [KillerCodeMonkey/ngx-quill#246]
When i use the page in development (ng serve) it works well however when i use ng prod this editor doesn't even appear, and this error is thrown. The only mistake i think im making is including the cdn script to the css styles in the index.html file. `<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">`  Any thoughts as to how to resolve?

![capture2](https://user-images.githubusercontent.com/38970690/45667303-96cc0e80-bae6-11e8-9ce4-c4db96bc71ef.PNG)

![error](https://user-images.githubusercontent.com/38970690/45667253-64221600-bae6-11e8-8ac1-c70f5d81eafc.PNG)

This is Dev (ng Serve)
![capture](https://user-images.githubusercontent.com/38970690/45667302-96cc0e80-bae6-11e8-8a95-5f64f89f9605.PNG)

![warning](https://user-images.githubusercontent.com/38970690/45667254-64221600-bae6-11e8-85b7-dc9784779426.PNG)

**Comment by KillerCodeMonkey** [comment]
Do you use any other third party libs?

Please change the title to `Quill Editor doesnt work in angular cli prod build` or something similar.
I have a test project on my machine and there the production build works quite well.

Maybe you can share a demo repository to reproduce this easier.

**Comment by joromecox** [comment]
The third party libs are as follows:
    "hoek": "^5.0.3",
    "joi": "^13.5.2",
    "moment": "^2.22.2",
    "ng4-loading-spinner": "^1.2.3",
    "ngx-order-pipe": "^2.0.1",
    "ngx-pagination": "^3.1.1",
    "ngx-quill": "^3.4.0",
    "ngx-webstorage": "^2.0.1",
    "quill": "^1.3.6",
    "rxjs": "^6.3.2",
    "zone.js": "^0.8.26"

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
tested the latest release with the latest angular deps 

```
"dependencies": {
    "@angular/animations": "^6.1.7",
    "@angular/common": "^6.1.7",
    "@angular/compiler": "^6.1.7",
    "@angular/core": "^6.1.7",
    "@angular/forms": "^6.1.7",
    "@angular/http": "^6.1.7",
    "@angular/platform-browser": "^6.1.7",
    "@angular/platform-browser-dynamic": "^6.1.7",
    "@angular/router": "^6.1.7",
    "core-js": "^2.5.7",
    "ngx-quill": "^3.6.0",
    "quill": "^1.3.6",
    "rxjs": "^6.3.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.2",
    "@angular/cli": "6.2.2",
    "@angular/compiler-cli": "^6.1.7",
    "@angular/language-service": "^6.1.7",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^6.0.117",
    "codelyzer": "^4.4.4",
    "jasmine-core": "~2.99.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "^5.4.1",
    "ts-node": "^6.0.5",
    "tslint": "~5.10.0",
    "typescript": ">=2.7.2 <2.10"
  }
```

and the error is gone.
i would upgrade angular cli and `@angular-devkit/build-angular`

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill-angular-cli

**Comment by EvandroBraito** [comment]
I'm having the same problem with ionic prod build.
I've tried change the versions but it still doesn't work.

Is there any known issue with ionic?

**Comment by rodrigo-sntg** [comment]
I'm having the same problem to production build on an ionic project.
Is there any known issue with ionic building?

**Comment by KillerCodeMonkey** [comment]
Without an Error. I can Not Help ;). I have an Demo repo for Ionic v3 but
never build IT for production.

Am Fr., 9. Nov. 2018, 17:51 hat rodrigo-sntg <notifications@github.com>
geschrieben:
