### ISSUE TITLE
QuillModule import error

### ISSUE THREAD

**Issue by hellboy993** [KillerCodeMonkey/ngx-quill#249]
hi,
when i add QuillModule to the imports i get this error :
ERROR in ./node_modules/ngx-quill/fesm5/ngx-quill.js
Module not found: Error: Can't resolve 'quill' in 'E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\ngx-quill\fesm5'
resolve 'quill' in 'E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\ngx-quill\fesm5'
  Parsed request is a module
  using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\ngx-quill\package.json (relative path: ./fesm5)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\ngx-quill\package.json (relative path: ./fesm5)
    resolve as module
      E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\ngx-quill\fesm5\node_modules doesn't exist or is not a directory
      E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\ngx-quill\node_modules doesn't exist or is not a directory
      E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\node_modules doesn't exist or is not a directory
      E:\Angular projects\Gheychi\node_modules doesn't exist or is not a directory
      E:\Angular projects\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./node_modules)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./node_modules/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./node_modules)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./node_modules/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
      looking for modules in E:\Angular projects\Gheychi\GheychiSalonDashboard\src
        using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src)
          using description file: E:\Angular projects\Gheychi\GheychiSalonDashboard\package.json (relative path: ./src/quill)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js doesn't exist
            as directory
              E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill doesn't exist
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\ngx-quill\fesm5\node_modules]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\ngx-quill\node_modules]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\node_modules]
[E:\Angular projects\Gheychi\node_modules]
[E:\Angular projects\node_modules]
[E:\node_modules]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\node_modules\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.ts]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill.js]
[E:\Angular projects\Gheychi\GheychiSalonDashboard\src\quill]
 @ ./node_modules/ngx-quill/fesm5/ngx-quill.js 106:20-36
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by hellboy993** [comment]
i don't know what should i do.please help!

**Comment by KillerCodeMonkey** [comment]
Read the readme.. You need to install quill as a Dependency...

ahmad <notifications@github.com> schrieb am Mo., 24. Sep. 2018, 18:53:

**Comment by hellboy993** [comment]
i did everything told in readme step by step but still get this error.

**Comment by KillerCodeMonkey** [comment]
Did You checked the Demo repositories for angular cli and so on?

ahmad <notifications@github.com> schrieb am Mo., 24. Sep. 2018, 19:07:

**Comment by hellboy993** [comment]
yes.
at the first time i installed ngx-quill it was working fine but when removed it and reinstalled i got this error

**Comment by KillerCodeMonkey** [comment]
Try to delete Your node_modules and install Them again. Check If You have
quill 1.3.x in Your packages.json.

ahmad <notifications@github.com> schrieb am Mo., 24. Sep. 2018, 19:14:

**Comment by KillerCodeMonkey** [comment]
And latest ngx-quill

Bengt Weiße <bengtler@googlemail.com> schrieb am Mo., 24. Sep. 2018, 19:18:

**Comment by hellboy993** [comment]
i test it on a new project and still have the same error exactly when add QuillModule to the imports.

**Comment by KillerCodeMonkey** [comment]
Are You using angular cli?

ahmad <notifications@github.com> schrieb am Mo., 24. Sep. 2018, 19:37:

**Comment by hellboy993** [comment]
yes

**Comment by KillerCodeMonkey** [comment]
Okay then please create a Demo Repo, because it is Working for my Demo
repositories

ahmad <notifications@github.com> schrieb am Mo., 24. Sep. 2018, 19:51:

**Comment by KillerCodeMonkey** [comment]
Did You checked my ngx-quill-angular-cli Repo?

Check it out. Run npm install and ng serve

OneUp5hroom <notifications@github.com> schrieb am Di., 25. Sep. 2018, 15:37:

**Comment by KillerCodeMonkey** [comment]
@OneUp5hroom did you get a special step you missed and not mentioned in the readme?

i guess you forgot to install quill `npm install quill --save`

**Comment by srisridhar1993** [comment]
For me npm install quill and npm install quill  i have installed and able to view the editor.
But unable to use the [options] field . @KillerCodeMonkey Please help me out.

"ngx-quill": "^3.6.0",
 "quill": "^1.3.6",

**Comment by KillerCodeMonkey** [comment]
there is no [options] field. check the readme and the demo repo with live editor examples ;)

there is a [modules]="" property and so on

**Comment by srisridhar1993** [comment]
<div id="toolbar">
          <select class="ql-size">
            <option value="small"></option>
            <option selected></option>
            <option value="large"></option>
            <option value="huge"></option>
          </select>
          <button class="ql-bold"></button>
          <button class="ql-script" value="sub"></button>
          <button class="ql-script" value="super"></button>
        </div>
        <div id="editor"></div>


var toolbarOptions = ['bold', 'italic', 'underline', 'strike'];
    var quill = new Quill('#editor', {
      modules: {
        toolbar: toolbarOptions
      }
    });
![image](https://user-images.githubusercontent.com/50732426/58023278-08a0a000-7b2d-11e9-8a4a-1e071a0058ca.png)

Am i missing something over here??

**Comment by KillerCodeMonkey** [comment]
why are you doing this:

```ts
new Quill('#editor', {
modules: {
toolbar: toolbarOptions
}
});
```

and if you read the readme, you can see a link to a repo with custom toolbar and a live preview.
the property is called "modules" and not "toolbaroptions". 

So quill-editor component expects a module config object, like you did it with `new Quill(.., MODULES)`.

**Comment by Sravankumar28** [comment]
Hi @KillerCodeMonkey i have followed all the steps. I dont have error but the Quill component was not loading...
Please help me on this..
i have imported quill.snow.css and quill.bubble.css in style.scss and also index.html also

**Comment by KillerCodeMonkey** [comment]
Just check out the linked demo repo in the readme ;-). There you have working example.

**Comment by Sravankumar28** [comment]
i have checked that and followed all the steps

**Comment by Sravankumar28** [comment]
@KillerCodeMonkey Can you please help me...

**Comment by KillerCodeMonkey** [comment]
Nobody can help without an error. Just check your Js console of your browsers dev tools. Guess there will be some Js errors then..
