### ISSUE TITLE
Quill Editor not show any control 

### ISSUE THREAD

**Issue by phantanthanh1996** [KillerCodeMonkey/ngx-quill#250]
I installed Quill Editor in my project but after run website it not show any control 
![image](https://user-images.githubusercontent.com/26193725/46342628-77e08700-c665-11e8-9e6b-55d52102e498.png)

**Comment by KillerCodeMonkey** [comment]
Yeah Check Your JS console If there any errors and Check my Demo and
example repos

How Do i help You without any further Information...

"its Not Working" and a Screenshot of an empty Page is not that helpful ;)

phantanthanh1996 <notifications@github.com> schrieb am Di., 2. Okt. 2018,
12:06:

**Comment by phantanthanh1996** [comment]
Hi sir, I am using angular cli and ngx-quill version is 2.0.4 
I try to update ngx-quill but it not fix. Am I missing something?

**Comment by KillerCodeMonkey** [comment]
Sure because it should work than ^^. I have a angular-cli ngx-quill Repo on
GitHub. Check this ;).

Which angular Cli Version Do You Use?

Read the readme.  You need to install quilljs as well and add the quilljs
stylings to You project. Search through the issues here. There some Closed
one how to Use ngx-quill with angular cli

phantanthanh1996 <notifications@github.com> schrieb am Di., 2. Okt. 2018,
12:43:

**Comment by phantanthanh1996** [comment]
Ok thank you :)

**Comment by phantanthanh1996** [comment]
Sorry, i am using angular. and when delete node_modules and then call npm install, i receive:
npm WARN ngx-quill@2.0.4 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-quill@2.0.4 requires a peer of @angular/forms@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-quill@2.0.4 requires a peer of rxjs@^5.5.2 but none is installed. You must install peer dependencies yourself.

So,do they affect editor?

**Comment by KillerCodeMonkey** [comment]
Like the warning says, You need to install angular 5 or above for ngx-quill
2.0.4

phantanthanh1996 <notifications@github.com> schrieb am Di., 2. Okt. 2018,
13:38:

**Comment by phantanthanh1996** [comment]
yes, i am using angular 6.0.1 and ngx-quill 2.0.4

**Comment by phantanthanh1996** [comment]
I am buy a angular source with template http://preview.themeforest.net/item/egret-angular-4-material-design-admin-template/full_screen_preview/20161805?_ga=2.105522499.1343758650.1537006224-984203503.1536729627
and then i move it to my source in C#.

**Comment by phantanthanh1996** [comment]
And it show a error in console:
![image](https://user-images.githubusercontent.com/26193725/46347381-7d45cd80-c675-11e8-9605-132262bb9cb3.png)

**Comment by KillerCodeMonkey** [comment]
Yeah with angular cli 6 You should Use angular 6 and ngx-quill >= 3... And
Not using an outdated angular 4 template Oo

phantanthanh1996 <notifications@github.com> schrieb am Di., 2. Okt. 2018,
14:01:

**Comment by KillerCodeMonkey** [comment]
check this issue https://github.com/KillerCodeMonkey/ngx-quill/issues/224

**Comment by KillerCodeMonkey** [comment]
quill is only working on the browser or a browser like env. 

if you are using server-side rending this is not working that easy with older ngx-quill version ;)
