### ISSUE TITLE
 Can't resolve 'quill' in 'xxx/node_modules/ngx-quill/fesm5'

### ISSUE THREAD

**Issue by patrickbattisti** [KillerCodeMonkey/ngx-quill#251]
![captura de tela 2018-10-02 as 09 27 06](https://user-images.githubusercontent.com/35247414/46348486-8dce5780-c625-11e8-88de-07ec35e0c5ad.png)
![captura de tela 2018-10-02 as 09 27 41](https://user-images.githubusercontent.com/35247414/46348487-8dce5780-c625-11e8-8770-4bd4279d5d48.png)
![captura de tela 2018-10-02 as 09 27 49](https://user-images.githubusercontent.com/35247414/46348489-8dce5780-c625-11e8-8a9a-b6b33b9a8d62.png)

**Comment by KillerCodeMonkey** [comment]
Quilljs is also a peer Dependency...

patrickbattisti <notifications@github.com> schrieb am Di., 2. Okt. 2018,
14:28:

**Comment by KillerCodeMonkey** [comment]
installing it?

`npm i -S quill` or  `yarn -S add quill`

ngx-quill does not bundle its dependencies, so you have to install it on your own. you should read the readme and also read the outputs of your shell when you install something. There useful hints like "ngx-quill requires quill xxx but nothing was installed".

These are basics if you want to develop js software for browser or server...

**Comment by SchaferPro** [comment]
install `@angular/core`, `@angular/common`, `@angular/forms`, **_quill_** and `rxjs` - peer dependencies of ngx-quill.

**Comment by pawanzZ** [comment]
npm install quill and @types/quill to the latest.

I faced the same issue when upgrading from angular 5 to 8. Hope this helps others who are watching this.
