### ISSUE TITLE
ERROR in Metadata version mismatch for module

### ISSUE THREAD

**Issue by kirkpol** [KillerCodeMonkey/ngx-quill#252]
ERROR in Metadata version mismatch for module F:/Final Projcet/TheNursingDiaryRepo/FinalProject/ng-pi-admin-master/node_modules/angular-2-local-storage/dist/index.d.ts, found version 4, expected 3, resolving symbol AppModule in F:/Final Projcet/TheNursingDiaryRepo/FinalProject/ng-pi-admin-master/src/app/app.module.ts, resolving symbol AppModule in F:/Final Projcet/TheNursingDiaryRepo/FinalProject/ng-pi-admin-master/src/app/app.module.ts, resolving symbol AppModule in F:/Final Projcet/TheNursingDiaryRepo/FinalProject/ng-pi-admin-master/src/app/app.module.ts

please help me

**Comment by KillerCodeMonkey** [comment]
It is an error of angular-2-localstorage. You should Not Use outdated
dependencies ;). You are using angular 4 and it requires 3... But the
Current Version is angular 6.x... So I would kick it and Upgrade angular

kirkpol <notifications@github.com> schrieb am Mi., 3. Okt. 2018, 17:56:

**Comment by kirkpol** [comment]
I want to update angular 6  What should I do ?? sir 
Thank You

**Comment by KillerCodeMonkey** [comment]
Update all deps in the packages.json or Use angular cli to update Your
angular stuff. Than Check Your deps If they are compatible with it. Check
angular Migration Guides ;)

kirkpol <notifications@github.com> schrieb am Mi., 3. Okt. 2018, 18:05:

**Comment by kirkpol** [comment]
please I want code update
bacause I beginner sir

**Comment by KillerCodeMonkey** [comment]
i will not update your project... and this has nothing to do with ngx-quill.

simply checkout angular migation guides and changelogs (for breaking changes). and try avoiding using outdated libraries.

Use angular-cli for your project and it will be easier to update it later.
