### ISSUE TITLE
[(ngModel)] not rendering html value version 1.6.0

### ISSUE THREAD

**Issue by sameerrswt** [KillerCodeMonkey/ngx-quill#253]
While assigning it value which contain html, it is showing it as it is and not rendering html part.

![quill_issue](https://user-images.githubusercontent.com/17155131/46456959-3c150100-c7ce-11e8-8dad-82cf4d00fc4c.PNG)
 
Please help

**Comment by KillerCodeMonkey** [comment]
You should Use the latest ngx-quill Version. There You Can Set the Format
of Your content. Check the readme. The Format Text simply inserts the
string on Your Model and html converts the value to html

sameerrswt <notifications@github.com> schrieb am Do., 4. Okt. 2018, 08:39:

**Comment by KillerCodeMonkey** [comment]
And another Problem could be when Your htmlstring is encoded or escaped
like &gt; instead of >

Bengt Weiße <bengtler@googlemail.com> schrieb am Do., 4. Okt. 2018, 08:42:

**Comment by sameerrswt** [comment]
But it written over here to use 1.6.0 if we are using angular 4.

![quill_issue_1](https://user-images.githubusercontent.com/17155131/46457260-513e5f80-c7cf-11e8-9a25-e36f63ac35f5.PNG)

**Comment by KillerCodeMonkey** [comment]
Yep then Check my other Comment. Check If Your Model really contains valid
html or escaped string. And You should Know,  i Do Not hotfix or update
older Versions of ngx-quill ;). You should keep Your projects up to date...
There is angular 6 for Months and angular 5 for a year...

sameerrswt <notifications@github.com> schrieb am Do., 4. Okt. 2018, 08:46:

**Comment by sameerrswt** [comment]
Ok Thanks.
My html string was not in right way.
Thanks

**Comment by KillerCodeMonkey** [comment]
Glad You got it Working :)

sameerrswt <notifications@github.com> schrieb am Do., 4. Okt. 2018, 10:31:
