### ISSUE TITLE
Enter + Shift keyboard binding

### ISSUE THREAD

**Issue by PhoebePan** [KillerCodeMonkey/ngx-quill#254]
I'm binding another function to enter + shift key, but it doesn't work.
If I binding key: "B", it works good. 

HTML:
```
<quill-editor #editor (onEditorCreated)="addBindingCreated($event)" [modules]="modules" [(ngModel)]="editorBody" name="body"></quill-editor>
```

TS:
```
    addBindingCreated(quill: any) {
        quill.keyboard.addbinding({
            key: 13,     //Enter key
            shiftkey: true,
        }, (range: any, context: any) => {
            console.log('keybinding enter + shift', range, context);
        });
    }
```

I referenced ngx-quill-example and issue #112

**Comment by KillerCodeMonkey** [comment]
did you checked it with native quilljs?

**Comment by KillerCodeMonkey** [comment]
i extended my example-repo for binding with "shiftKey" and "b"
https://killercodemonkey.github.io/ngx-quill-example/

it works

Your problem is this:

```
shiftkey: true,
```

it should be in lowerCamelCase

```
shiftKey: true,
```

**Comment by PhoebePan** [comment]
Thanks a lot :D 

I found the thread with native quilljs.
Support for shift + enter #252
https://github.com/quilljs/quill/issues/252
