### ISSUE TITLE
May I import katex locally?

### ISSUE THREAD

**Issue by hnxuruochen** [KillerCodeMonkey/ngx-quill#255]
Hi friends. For using fomula, I don't want to use cdn so I installed katex via npm.
Then I add the js and css into vendor.ts, a entry of webpack.
But it dosen't work. Quill can not find window.katex.
How can I do it?
```
import 'katex/dist/katex.min.js';
import 'katex/dist/katex.min.css';
```

```
entry: { 
        'polyfills': './src/polyfills.ts',
        'vendor': './src/vendor.ts',
        'app': './src/main.ts'
},
```
Need your help, thx.

**Comment by KillerCodeMonkey** [comment]
you need to make sure it is loaded before quilljs.

try to import katex at the beginning of your app.module.
But this is more a question for the katex or quilljs repository.

**Comment by hnxuruochen** [comment]
Thanks, It dose work. The webpack plugin will make the name as a global import.

But I have another question.
For using jquery I just use the name '$' or 'jquery' in ProvidePlugin, why we need a 'window' scope for katex?
