### ISSUE TITLE
initial value is not set if form control name is not `editor`

### ISSUE THREAD

**Issue by vmasek** [KillerCodeMonkey/ngx-quill#257]
The initial value is not set if the form control name is not `editor`

**Reproduction:**
 - rename the form control to somethin else (e.g. `description`)
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts#L157
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts#L48

**Comment by KillerCodeMonkey** [comment]
If You wrapped Your Form control with a Form --> Use
formControlName="editor" to Set the control.

I Do Not Know why other control names should Not work. I used the Word
editor only as an example.
 There is no restriction for control names.

Vojtech Mašek <notifications@github.com> schrieb am So., 14. Okt. 2018,
14:23:

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by vmasek** [comment]
I will try to reproduce this, with stackblitz in near future

**Comment by vmasek** [comment]
Could not reproduce on a new project, closing issue
