### ISSUE TITLE
How to bind data to the editor

### ISSUE THREAD

**Issue by RaveenDharmasiri** [KillerCodeMonkey/ngx-quill#258]
I recently updated ngx-quill and now I cannot bind the data that is coming from the db at the start of the application.

But before that I could bind the data with the old version of ngx-quill. 

For binding the data I am using `[(ngModel)]`.

`Current version is : 3.6.0`

**Is there any other method in which I could use when binding the data?**

**Comment by KillerCodeMonkey** [comment]
i changed nothing, which was your version before?

Share some code, how you set the data fom the database.
But with 3.6.0 you can set the format of the input data, like "html" - "text" check out the readme and the example repo

**Comment by RaveenDharmasiri** [comment]
html
```
<quill-editor theme="bubble" format="html" scrollingContainer="html, body" placeholder="Add content here..." [(ngModel)]="competency.content"
    [modules]="quillModules" (onEditorCreated)="editorCreated($event)" (onContentChanged)="contentChanged($event)"
    (onSelectionChanged)="selectionChanged($event)" (contextmenu)="triggerBubbleToolbar($event)">
  </quill-editor>
```
ts
```
this.route.params.takeWhile(() => this.alive).subscribe(params => {
      this.groupId = params['gId'];
      this.competencyId = params['cId'];
      this.loadingCompetency = true;
      this.competency = undefined; // to deal with the editor's rendering issue(just works with the efficiency)
      this.competencyManagementService.getCompetency(this.competencyId).takeWhile(() => this.alive)
        .subscribe(competency => {
          this.competency = competency.data;
          this.editModelService.setSelectedCompetencyData(this.competency);
          this.loadingCompetency = false;
        }, ( error ) => {
          if (error.status === 400) {
            this.editModelService.checkCompetencyExist(false);
          }
      });
    });
```

**Comment by KillerCodeMonkey** [comment]
and did you tried to simple set a value directly in ngOnInit, instead of the whole subscription stuff?

**Comment by RaveenDharmasiri** [comment]
One more thing. When I give the format as text the content of the editor is shown along with their html tags
This is what the content of the editor look like when the format is text,
`<p>Hello world</p>`

**Comment by KillerCodeMonkey** [comment]
Maybe your html is invalid?

Maybe your database returns the html-string with excaped characters like `&gt;` instead of `>` and so on.

chech my example repo, there is an example with ngModel and i pass an `<ul><li>` list, and it works

**Comment by RaveenDharmasiri** [comment]
I tried your example repo at the first moment when i started to encounter this problem. 

if i console log the variable which i have assigned to ngModel will i be able to see the character &gt;

**Comment by RaveenDharmasiri** [comment]
> Maybe your html is invalid?
> 
> Maybe your database returns the html-string with excaped characters like `&gt;` instead of `>` and so on.
> 
> chech my example repo, there is an example with ngModel and i pass an `<ul><li>` list, and it works

I tried your example repo at the first moment when i started to encounter this problem.

if i console log the variable which i have assigned to ngModel will i be able to see the character `&gt;` on it?

**Comment by KillerCodeMonkey** [comment]
i think so. Maybe you changed the wrapper element for quill? from `p` to `div` tags? And now p-tags are not allowed, because quill expects div-blocks?

**Comment by RaveenDharmasiri** [comment]
so according to what you are saying the value of competency.content should be 
`<div>Hello world</div>`

Here i have used the <div> tag instead of the <p>tag for rendering content in the editor

**Comment by RaveenDharmasiri** [comment]
currently i am using the quilljs dev version because i am trying to add tables to ngx-quill. so in the attempt to add tables to the editor i have to update the quilljs to dev version.

Once the update is done i added tables to the modules of the ngx-quill.
Below are the modules of the editor:
```
public quillModules = {
    table: true,
    toolbar: {
      container: [
        ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
        ['blockquote', 'code-block'],

        [{ 'header': 1 }, { 'header': 2 }],               // custom button values
        [{ 'list': 'ordered' }, { 'list': 'bullet' }],
        [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
        [{ 'indent': '-1' }, { 'indent': '1' }],          // outdent/indent
        [{ 'direction': 'rtl' }],                         // text direction

        [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

        [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
        [{ 'font': [] }],
        [{ 'align': [] }],

        ['clean'],                                         // remove formatting button

        ['link', 'image', 'video']                         // link and image, video
      ],
      handlers: {
        'image': this // assigned to this since this cannot be left blank. Actual thing happens in the constructor
      }
    },
    // clipboard: {
    //   'paste': this.onPaste()
    // }
  };
 
```
Once the table module is added i am getting the error 

**quill Cannot import modules/table. Are you sure it was registered?**

I am not getting this error when i update the ngx-quill and using the dev version of the quilljs

Do you think you are familiar with this kind of an issue?

**Comment by KillerCodeMonkey** [comment]
öhhh i do not know anything about tables. i only checking final versions and not pre- beta- alpha- dev- stuff ;).

**Comment by RaveenDharmasiri** [comment]
what do you mean by the default value?

**Comment by KillerCodeMonkey** [comment]
i mean the inital value of your model :).

**Comment by RaveenDharmasiri** [comment]
you mean the value that i have assigned to the ngModel?

**Comment by RaveenDharmasiri** [comment]
When I'm using `quill 1.3.6` and `ngx-quill 3.6.0` the values bound through ng-model is working without a hitch. The problem arises when I use `quill 2.0.0-dev.2` 
Do you think it might be the problem?

**Comment by KillerCodeMonkey** [comment]
yep ;). so i think you should get along with it on your own. never checked out quill 2.0.0-dev.2

3.6.0 needs a peer dependency of quill 1.3.6.

**Comment by lakshyamathur** [comment]
I am using ngx-quill: 4.6.12, quill": "1.3.6",
but for example when I am pasting data from excel like this 
![image](https://user-images.githubusercontent.com/30621009/55794426-d427d600-5ae2-11e9-9222-fbfac8ef4a15.png)

then the data is disturbed in such a way in quill editor:-
![image](https://user-images.githubusercontent.com/30621009/55794484-f7528580-5ae2-11e9-8e39-49551ad038f3.png)


So my question is this that how can I get the data in same format as in excel on copy and paste?

**Comment by KillerCodeMonkey** [comment]
@lakshyamathur just ask this on the quilljs repo. i anly provide an angular wrapper for that.

BTW: i think quilljs does not support that, because it only works with html or blot-representation.
+ quilljs has no official table support ;)

**Comment by lakshyamathur** [comment]
@KillerCodeMonkey yes I am also using it in angular...
but on pasting the data from excel it is getting distorted

**Comment by KillerCodeMonkey** [comment]
> 
> @KillerCodeMonkey <https://github.com/KillerCodeMonkey> yes I am also using it in angular...
> but on pasting the data from excel it is getting distorted
> 
Sure, but I am using Quilljs and quilljs is responsible for formatting etc.

And if the base library Quilljs is not supporting this, my wrapper won’t support this, too

So checkout the quilljs repo/issues and documentation.

**Comment by pradeepjanga** [comment]
I have the same with ngx-quill editor, not able to bind the data coming from an api call.
am using angular10 and ngx-quill 2.0.1

**Comment by KillerCodeMonkey** [comment]
Just Checkout The supported angular and related ngx-quill Versions sections
in The readme.

I do not even know how old v2.0.1 is or if IT IS existing at all


Am 30.12.2020 in 17:10, pradeepjanga <notifications@github.com> schrieb:

I have the same with ngx-quill editor, not able to bind the data coming
from an api call.
am using angular10 and ngx-quill 2.0.1

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/258#issuecomment-752675539>,
or unsubscribe
