### ISSUE TITLE
Module not found: Error: Can't Resolve 'quill'

### ISSUE THREAD

**Issue by gui679** [KillerCodeMonkey/ngx-quill#259]
I'm trying to add ngx-quill to [AngularFire2](https://github.com/angular/angularfire2) (that uses Angular 6 and Firebase)
I've installed via  "npm install ngx-quill", that automatically adds himself to package.json
and manually added ngx-quill to app.modules, as the installation guides says.

BUT 'ng serve' returns me the follow error:
` ERROR in ./node_modules/ngx-quill/fesm5/ngx-quill.js
Module not found: Error: Can't resolve 'quill' in './node_modules/ngx-quill/fesm5'
`

**Comment by KillerCodeMonkey** [comment]
Please Check already Closed issues and Take a look in the readme. You have
to install quilljs an Your own. It is a peerdependency of ngx-quill.

gui679 <notifications@github.com> schrieb am Mi., 17. Okt. 2018, 01:27:

**Comment by webcat12345** [comment]
This should be mentioned on documentation, I can't find about `quilljs` installation.

**Comment by webcat12345** [comment]
having this issue even I install the `quilljs`. My current env is
```
Angular CLI: 8.0.0
Node: 12.2.0
OS: linux x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
```
and 
```
"ngx-quill": "^5.2.0",
"quilljs": "^0.18.1",
```
and `tsconfig.json` target is 
```
"target": "es5",
```

**Comment by KillerCodeMonkey** [comment]
I think quilljs ist Not the right dependency. And yarn and npm are Warning
You, that there are missing peerdependencies ;).

And in the readme is the topic "Installation" where all Peer dependencies
are listed ... Which You have to Install in your own.. even that You have
to Install "quill" Not "quilljs".

And there are example repos what quill and Version You should Install...

webcat_black <notifications@github.com> schrieb am Do., 30. Mai 2019, 05:01:

**Comment by webcat12345** [comment]
Yes, I had to install `quill` as a peer dependency but for me, the documentation doesn't make sense...

**Comment by WaseemAhmadNaeem** [comment]
You need to Install peer dependency by your self.
For NPM use this `npm install quill@1.3.6`

**Comment by NateJBeck** [comment]
@WaseemAhmadNaeem comment was very helpful and resolved the error above, but there was a bit of leg work remaining to resolve the rest of the errors I was seeing installing quill with Angular 14.

The following worked for me:

```
$ npm install ngx-quill

$ npm install quill@1.3.6

>>> add "node_modules/quill/dist/quill.core.js" to architect "scripts" section of angular.json

$ npm i --save-dev @types/quill

>>> manually downgrade "@types/quill" in package.json to be "^1.3.10" (not 2.X)

$ npm install

>>> add the following to angular.json architect "styles"
    "./node_modules/quill/dist/quill.core.css",
    "./node_modules/quill/dist/quill.bubble.css",
    "./node_modules/quill/dist/quill.snow.css",
```

The example repo https://github.com/KillerCodeMonkey/ngx-quill-example was useful

**Comment by chintustacks** [comment]
No working stilll

**Comment by Fabiano-Franca** [comment]
Além dos comandos abaixo, é preciso insalar os types do quill1.3.

`npm i -D @types/quill@1.3`

`$ npm install ngx-quill

$ npm install quill@1.3.6

>>> add "node_modules/quill/dist/quill.core.js" to architect "scripts" section of angular.json

$ npm i --save-dev @types/quill

>>> manually downgrade "@types/quill" in package.json to be "^1.3.10" (not 2.X)

$ npm install

>>> add the following to angular.json architect "styles"
    "./node_modules/quill/dist/quill.core.css",
    "./node_modules/quill/dist/quill.bubble.css",
    "./node_modules/quill/dist/quill.snow.css",`
