### ISSUE TITLE
ngx-quill.umd.js:4 Uncaught TypeError: Cannot read property 'common' of undefined     at Quill (ngx-quill.umd.js:4)

### ISSUE THREAD

**Issue by lilworks** [KillerCodeMonkey/ngx-quill#260]
I'm trying to implement ngx-quill on my angular6 cli application

I add the js files in my angular.json, and the ngx-quill module in my app.module.ts
The editor is displayed correctly but I have the following error displayed in my console:

```
ngx-quill.umd.js:4 Uncaught TypeError: Cannot read property 'common' of undefined
    at Quill (ngx-quill.umd.js:4)
```

**Comment by KillerCodeMonkey** [comment]
i think there is no need to add ngx-quill files to angular.json.

checkout my angular-cli-ngx-quill repo.
https://github.com/KillerCodeMonkey/ngx-quill-angular-cli
