### ISSUE TITLE
setting focus to editor's edittable field

### ISSUE THREAD

**Issue by dalu** [KillerCodeMonkey/ngx-quill#261]
How would I set focus to the edit field?

I have a list of posts (in a forum thread) on the bottom I have appended a "post-create" component.

In that component is this ngx-quill component.

I can access the component via `@ViewChild()` but I don't know how to set focus on the editor's edittable area.

And why would I want to do that?

Well there's a button that, when pressed, quotes the original post or the currently selected part of the post and appends it to the editor's ngModel value. So after that is done it should scroll down to the editor and focus on its edittable element.

**Comment by KillerCodeMonkey** [comment]
Quill has Focus function. Check the quilljs Docs. There are similar closed
issues Here ;). Just use the search.

Listen to onEditorCreated Output anderen Grab the Editor instance from
there... IT IS passed on $event.

And than use quilljs set Focus function.

dalu <notifications@github.com> schrieb am Fr., 19. Okt. 2018, 16:24:

**Comment by dalu** [comment]
Ah ok sorry and thanks.
My attempt

```ts
  @ViewChild('postCreate') postCreate: PostCreateComponent;
```

then

```ts
this.postCreate.body.editorElem.focus();
```

didn't work, I'll check closed issues

**Comment by dalu** [comment]
Ok 1 more question (you should probably create a FAQ ;) ) 

after the editor is focused (the edit field anyhow) the cursor is placed on char 0, on location 0, the beginning of the edittable field.

How do I move it to the end?

**Comment by KillerCodeMonkey** [comment]
Just Check the quilljs.com documentation ;).
And there is no FAQ, because if You know quilljs and where to find the
doc/repo and know how angular works the readme is enough.

But sadly, because of the Internet are asking ans asking instead of Reading
thinking and understanding ;). This ist nothing against You.. it is more
Like a general Problem nowadays.

dalu <notifications@github.com> schrieb am Fr., 19. Okt. 2018, 16:55:

**Comment by dalu** [comment]
Well I used to think like you when I was your age, but you grow older and everything gets harder.
tech changes, methods change.
When I'm in a foreign country, I ask around, same here.
You may or may not know the answer but it's better to ask than not to.
If you don't want people asking create a link to quilljs' documentation or create a github issue template.
When you get to my age and been through a multitude of languages and frameworks and methods and interoperability you'll understand. When your brain starts degenerating because of age and EM radiation and things are not intuitively understood. You'll get there eventually.
Also personally JS was never a love of mine and now it has exploded into something, a huge fucking tree with branches and leafs and it's complicated.

quill's API doesn't really do what it should, I'm suspecting a race condition.
It's all suboptimal.
What would be optimal would be a angular native editor.
But my knowledge of Angular and JS is limited.
I tried to write my own but met my limits so I found quill and your wrapper.
