### ISSUE TITLE
Angular 7 compatibility

### ISSUE THREAD

**Issue by jed-meyer** [KillerCodeMonkey/ngx-quill#262]
During the Angular 7 update process, ngx-quill 3.6.0 complains about peer dependencies since it requires Angular 5.x or 6.x.

Is Angular 7 compatibility on its way already?

**Comment by KillerCodeMonkey** [comment]
I did Not tried it, yet. Feel free to Test it in your own. And send me a pr
:)

jed-meyer <notifications@github.com> schrieb am Sa., 20. Okt. 2018, 13:47:

**Comment by markgoho** [comment]
#263

**Comment by KillerCodeMonkey** [comment]
Nice one!

Mark Goho <notifications@github.com> schrieb am Sa., 20. Okt. 2018, 16:39:

**Comment by jed-meyer** [comment]
That's great news! Any chance the major version will be aligned with Angular's?

**Comment by KillerCodeMonkey** [comment]
Nope because i am also depending on quilljs. So it is possible to have
breaking changes between angular major releases.

jed-meyer <notifications@github.com> schrieb am So., 21. Okt. 2018, 03:10:

**Comment by markgoho** [comment]
@KillerCodeMonkey anything I can do on the PR to get it pushed through?

**Comment by KillerCodeMonkey** [comment]
What so You mean with pushed through? I will Look into it next week. ;)

Mark Goho <notifications@github.com> schrieb am So., 21. Okt. 2018, 21:49:

**Comment by markgoho** [comment]
Sorry, I mean, is there anything you need changed on the PR in order to Merge it into the project. Please let me know when you've had time to review.

**Comment by KillerCodeMonkey** [comment]
@markgoho would be nice if you could checkout the other pr for angular 7.
https://github.com/KillerCodeMonkey/ngx-quill/pull/264/files

Could you validate if this version specification is working as well? So we do not need to exclude older Angular versions.

If so, please change this in your pr :)

**Comment by markgoho** [comment]
I'm not sure how I would test that. Wouldn't folks who aren't on v7 of Angular just stick with v3.x of ngx-quill?

**Comment by KillerCodeMonkey** [comment]
checkout v4
