### ISSUE TITLE
When typing Chinese, the first letter appears in the editor

### ISSUE THREAD

**Issue by zhangjinsong** [KillerCodeMonkey/ngx-quill#267]
When typing Chinese in ie11, the first letter appears in the editor
![image](https://user-images.githubusercontent.com/12949599/47480145-fcd45000-d861-11e8-9a6d-cacfb0e401d9.png)

this is my package.json:
![image](https://user-images.githubusercontent.com/12949599/47480184-21302c80-d862-11e8-8288-6a757ac99e3d.png)
![image](https://user-images.githubusercontent.com/12949599/47480194-27bea400-d862-11e8-84ba-bb296ec6f0d4.png)

**Comment by KillerCodeMonkey** [comment]
ööhhh what do you mean?

**Comment by zhangjinsong** [comment]
When I typed Chinese, the first letter I typed was entered into the container by default.

**Comment by zhangjinsong** [comment]
https://github.com/surmon-china/vue-quill-editor/issues/56

**Comment by KillerCodeMonkey** [comment]
yeah but it seems like a problem with base quilljs editor not with my angular wrapper ;)

**Comment by zhangjinsong** [comment]
How to solve this problem

**Comment by KillerCodeMonkey** [comment]
i do not know 🙃... if i would know the answer i would let you know

So keep on track with the open issues in the quilljs repo.

**Comment by zhangjinsong** [comment]
uh  this is a visialbe
