### ISSUE TITLE
export class QuillContentChangedModel{   editor: editorInstance,   html: html,   text: text,   content: content,   delta: delta,   oldDelta: oldDelta,   source: source }

### ISSUE THREAD

**Issue by lilworks** [KillerCodeMonkey/ngx-quill#268]
I'm testing ngx-quill with
https://stackblitz.com/edit/ngx-quill?file=src%2Fapp%2Fmodels%2FQuillContentChangedModel.ts
What is the class QuillContentChangedModel for?
How is it called?

```
export class QuillContentChangedModel{
  editor: editorInstance,
  html: html,
  text: text,
  content: content,
  delta: delta,
  oldDelta: oldDelta,
  source: source
}
```

**Comment by KillerCodeMonkey** [comment]
When the Text of the Editor changes. An Output ist triggered. The data
passed to this Output ist defined with this interface

masnada lilian <notifications@github.com> schrieb am Fr., 26. Okt. 2018,
14:31:

**Comment by lilworks** [comment]
Thanks...
