### ISSUE TITLE
ERROR in node_modules/quill-delta/dist/Delta.d.ts(1,8): error TS1192: Module '"node_modules/quill-delta/node_modules/fast-diff/diff"' has no default export.

### ISSUE THREAD

**Issue by lilworks** [KillerCodeMonkey/ngx-quill#269]
I try to reproduce the https://stackblitz.com/edit/ngx-quill in my own environement. I got a new angular-cli project with all same dependency and same code. 

But I got this error:

`ERROR in node_modules/quill-delta/dist/Delta.d.ts(1,8): error TS1192: Module '"node_modules/quill-delta/node_modules/fast-diff/diff"' has no default export.
`
and 

`src/app/quill/quillAutolink.ts(1,8): error TS1192: Module '"/Users/lil-works1/Webdisk/www/npm/jolineck/node_modules/quill-delta/dist/Delta"' has no default export.`
`

**Comment by KillerCodeMonkey** [comment]
I have linked a really Up to Date angular cli Project in the readme. I
think You have installed a wrong quilljs Version or typings. Do Not Install
V2.x typings for quill 1.3.x

masnada lilian <notifications@github.com> schrieb am Fr., 26. Okt. 2018,
15:58:

**Comment by lilworks** [comment]
So which typing I should install?

**Comment by lilworks** [comment]
In your ngx-quill-angular-cli quill version is 1.3.6

**Comment by KillerCodeMonkey** [comment]
Yeah but of You Check Out semantic Versioning the Last number is the hotfix
Version ;).

masnada lilian <notifications@github.com> schrieb am Fr., 26. Okt. 2018,
18:32:

**Comment by lilworks** [comment]
sorry I don't understand...

**Comment by KillerCodeMonkey** [comment]
Then Google "semantic versioning"

masnada lilian <notifications@github.com> schrieb am Fr., 26. Okt. 2018,
18:47:

**Comment by AlanObject** [comment]
Here I am 3.5  years down the road and this happened to me.  It raises the question as to when the 2.0.8 version of @types/quill are going to be used.

**Comment by KillerCodeMonkey** [comment]
When quill V2 has a stable release and not only a 3 years old First Dev
build ;-)


Am 03.07.2021 in 06:25, Alan ***@***.***> schrieb:

Here I am 3.5 years down the road and this happened to me. It raises the
question as to when the 2.0.8 version of @types/quill are going to be used.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/269#issuecomment-873342978>,
or unsubscribe

**Comment by ankursinghagra** [comment]
I did 
`npm uninstall @types/quill`
and 
`npm install @types/quill@1.3.10 --save-dev`
This resolved my issue.
