### ISSUE TITLE
Using Angular 6, I cannot build with ngx-quill version >2.2.0

### ISSUE THREAD

**Issue by damien-CFS** [KillerCodeMonkey/ngx-quill#270]
Hi,
I am using Angular 6:

_Angular CLI: 6.2.6
Node: 10.12.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.6
@angular-devkit/build-angular     0.8.6
@angular-devkit/build-optimizer   0.8.6
@angular-devkit/build-webpack     0.8.6
@angular-devkit/core              0.8.6
@angular-devkit/schematics        0.8.6
@angular/cdk                      7.0.1
@angular/cli                      6.2.6
@angular/material                 7.0.1
@angular/pwa                      0.10.3
@angular/service-worker           7.0.1
@ngtools/webpack                  6.2.6
@schematics/angular               0.8.6
@schematics/update                0.8.6
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.23.1_

I have quill and ngx-quill in angular.json:
    _"ngx-quill": "^4.0.0",
    "quill": "^1.3.6",_

It runs fine with version 2.2.0.
When I use a version of ngx-quill > 2.2.0 (and I should be using at least 3.0.0 according to the documentation), I get the following build error:
_Module not found: Error: Can't resolve 'ngx-quill/src/quill-editor.component' in '/..../portal/src/app/shared/careplan-editor'_

Thanks for your help

**Comment by KillerCodeMonkey** [comment]
Check my angular cli Demo repo linked in the readme. IT IS Working with
angular 7. And If You Checkout the commit History You will find a Working
example with angular 6.


How do You use ngx-quill in your Project?


damien-CFS <notifications@github.com> schrieb am Sa., 27. Okt. 2018, 14:41:

**Comment by damien-CFS** [comment]
Thanks for your quick reply. 
I am looking at the example but there is no angular.json file for Angular 6+
How do you run the build?
Have you tried a standard build with an angular.json?
Thanks,
Damien

**Comment by KillerCodeMonkey** [comment]
Yes i tried it with Standard angular cli with 6 and 7. Nothing Special.

damien-CFS <notifications@github.com> schrieb am Sa., 27. Okt. 2018, 18:49:

**Comment by damien-CFS** [comment]
Yes that's strange because the build settings used to be in .angular-cli.json until angular-cli 6 and now they are in angular.json and it doesn't build without it.

**Comment by damien-CFS** [comment]
Ok I found the problem looking at the history of the sample.
From version 3.0 the import of the component mus be 
_import {QuillEditorComponent} from 'ngx-quill';_
where it was: 
_import {QuillEditorComponent} from 'ngx-quill/src/quill-editor.component';_
