### ISSUE TITLE
Not able to add ngx-quill in Angular 7 project

### ISSUE THREAD

**Issue by yogeshbansal** [KillerCodeMonkey/ngx-quill#271]
I have tried to use ngx-quill in angular 7 project as per the instruction is given. I am getting the below error and project compilation failed and I don't see any theme or css file also inside the package
ERROR in ./node_modules/ngx-quill/fesm5/ngx-quill.js
Module not found: Error: Can't resolve 'quill' in '/Users/yogesh_bansal/Yogesh_Personal/Projects/Angular/kuviknotes-ng/node_modules/ngx-quill/fesm5'

**Comment by ExplodingCow** [comment]
`install @angular/core, @angular/forms, quill and rxjs - peer dependencies of ngx-quill`

You will still need to install quill with the following command:
`npm i quill`

**Comment by KillerCodeMonkey** [comment]
dudes please read the readme first, checkout the linked examples there and search through existing issues... before opening the same issue again and again and again...

@ExplodingCow thank!
