### ISSUE TITLE
Does not work in macOS Safari

### ISSUE THREAD

**Issue by ExplodingCow** [KillerCodeMonkey/ngx-quill#272]
ngx-quill works well on other browsers but Safari on macOS. It is unresponsive and I could not enter any text into the editor. 

Tested with [https://github.com/KillerCodeMonkey/ngx-quill-ionic-v3](https://github.com/KillerCodeMonkey/ngx-quill-ionic-v3)

**Comment by KillerCodeMonkey** [comment]
yeah ionic is not optimized for web. And maybe you need some css-optimizations for get quill work with ionic. Like they disabled user-select on everything ;)

**Comment by KillerCodeMonkey** [comment]
And please open the issue at the repository of the example ;) not here

**Comment by KillerCodeMonkey** [comment]
added the necessary css to the example repo ;)

`
[contenteditable] {
    -webkit-user-select: text;
    user-select: text;
}
`
