### ISSUE TITLE
Quill Editor inside the Angular Material Tab

### ISSUE THREAD

**Issue by nhatzbulawan** [KillerCodeMonkey/ngx-quill#273]
The pre-value of the model is flattened when the quill editor is inside the Angular Material Tab.

version used :     "ngx-quill": "^3.6.0",

**Comment by KillerCodeMonkey** [comment]
do you have an example repo? or example codepen (or something similar)?

what do you mean with "flattened"

**Comment by nhatzbulawan** [comment]
Hi @KillerCodeMonkey ,

Please check on this https://stackblitz.com/edit/quill-editor-bug.

What I mean by flattened is that some HTML tags were removed.

**Comment by malek-itani** [comment]
Hi @KillerCodeMonkey ,
please when you are going to add table feature to ngx-quill ??

**Comment by KillerCodeMonkey** [comment]
Ngx-quill is a wrapper of Quilljs. I do not add additional features ;)

**Comment by malek-itani** [comment]
but quill 2.0.0-dev.3 has table feature, i'm using 
"ngx-quill": "^4.0.0",
"quill": "^2.0.0-dev.3",
and table is not showing

**Comment by KillerCodeMonkey** [comment]
yeah because i do not support beta or dev releases? simply try to pass the table-formats to the modules/formates property.

**Comment by jleonardoDeveloper** [comment]
I don't know if anyone else has had this problem, but I can tell you that it is not related to "ngx-quill" but to the implementation of the mat-tab. Check the documentation related to the "Lazy Loading" in tabs. https://material.angular.io/components/tabs/overview#lazy-loading

**Comment by Hendrikson** [comment]
@jleonardoDeveloper An entire day of debugging and fixed thanks to you! Adding `<ng-template matTabContent>...</ng-template>` wrapping fixed the html flattening for me.
