### ISSUE TITLE
Confusion on scrollingContainer

### ISSUE THREAD

**Issue by Skelyos** [KillerCodeMonkey/ngx-quill#275]
I am trying to add "scrollingContainer: '.ql-editor'," to my quill config file and it is giving me the below error. 
![image](https://user-images.githubusercontent.com/22151553/47806395-9784d100-dd31-11e8-8b3b-1f2d08889753.png)

This is my current config
```
                toolbar: [
                    [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
                    ['bold', 'italic', 'underline', 'strike'],
                    [{ 'align': [] }],
                    ['link', 'image', 'video'],
                    ['code-block']
                ],
                scrollingContainer: '.ql-editor',
```

I am unsure how i am supposed to import or use this but I can see that it was added into ngx-quill here:
https://github.com/KillerCodeMonkey/ngx-quill/issues/60

**Comment by KillerCodeMonkey** [comment]
ngx-quill does not support the config 
`scrollingContainer` ;)

In the issue you linked the solution was to set a fixed height to the ql-editor with css.

**Comment by KillerCodeMonkey** [comment]
@Skelyos i updated my previous answer

**Comment by Pieter-1337** [comment]
> 

should be scrollingContainer instead of scrollContainer!

**Comment by KillerCodeMonkey** [comment]
this issue us 4 years old. the config and property field is `scrollingContainer`
