### ISSUE TITLE
Quill with Angular Universal

### ISSUE THREAD

**Issue by petermarks12** [KillerCodeMonkey/ngx-quill#276]
I am using quill with Angular 6 and when i tried to compile it, I was getting error

> document not defined

After searching for issues in this repo, I followed the solution, posted here

> https://github.com/KillerCodeMonkey/ngx-quill/issues/91

But now, I am getting new error, can you help me with this?

```
`var Size = quill_1.default.import('attributors/style/size'); 

TypeError: quill_1.default.import is not a function`
```

**Comment by KillerCodeMonkey** [comment]
Which ngx quill Version do You use?

Am Fr., 2. Nov. 2018, 21:04 hat petermarks12 <notifications@github.com>
geschrieben:

**Comment by petermarks12** [comment]
I have installed quill 1.3.6, ngx-quill 3.6.0 and also installed the respective types for quill, but still it shows same error.

**Comment by KillerCodeMonkey** [comment]
And how do You use ngx-quill. So You have an example repo?

Am Sa., 3. Nov. 2018, 09:02 hat petermarks12 <notifications@github.com>
geschrieben:

**Comment by petermarks12** [comment]
Finally, I found the culprit code.  I want custom font size for normal, large, huge.  I used this code given below.  After removing this code, everything works fine, but I  need those custom sizes for fonts.  Can you help me to make it work?

```
import Quill from 'quill';
`var Size = Quill.import('attributors/style/size');
Size.whitelist = ['14px', '16px', '18px'];
Quill.register(Size, true);`
```

**Comment by petermarks12** [comment]
Just fixed it by following code, no idea if its the right approach because I have not deployed it to server yet.  I modified mock quill.js
```

class Quill {
    constructor(container, options = {}) {
    }

    static import(){
        return {};
    }

    static register(){}
}

export default Quill;
```

**Comment by KillerCodeMonkey** [comment]
Ahhh okay. Quill needs the document of the Browser. So You should avoid
import or requiring it on SSR.

Check ngx-quill Editor component Code how to handle SSR and Browser
execution

Am Sa., 3. Nov. 2018, 10:41 hat petermarks12 <notifications@github.com>
geschrieben:
