### ISSUE TITLE
Cannot override CSS

### ISSUE THREAD

**Issue by enalposi** [KillerCodeMonkey/ngx-quill#277]
Hi, I am trying to override style similar to: https://codepen.io/k3no/pen/GjEzvo
but the CSS is not accepted: https://stackblitz.com/edit/ngx-quill-styling

Searching the ngx-quill repo I saw this being addressed in issue #222.
However, I'd prefer not to open view encapsulation and ::ng-deep is deprecated.

Any chance to support component level styling?

Thanks.

**Comment by KillerCodeMonkey** [comment]
Not this IS Not possible with the next angular major Versions.

So You need to Go to override them in your global Stylings.
Or create a custom quilljs theme ;)

Am Fr., 2. Nov. 2018, 22:21 hat enalposi <notifications@github.com>
geschrieben:

**Comment by enalposi** [comment]
Ok, thanks for the update.
