### ISSUE TITLE
Problem when build for production

### ISSUE THREAD

**Issue by benj0c** [KillerCodeMonkey/ngx-quill#279]
Plugin work in local env, but when I build it for production just not show component on page. Console is clean. Maybe someone have the same problem? Any advices?

node: 8.11.2
npm: 6.4.1
angular: 6.0.0
typescript: 2.7.2
quill: 1.3.6
ngx-quill: 4.0.0

**Comment by KillerCodeMonkey** [comment]
Any Error? Check the angular-cli Demo repo :)

Am Fr., 9. Nov. 2018, 13:54 hat Vanja Benjocki <notifications@github.com>
geschrieben:

**Comment by benj0c** [comment]
Fixed problem with update angular on version 7.

**Comment by benj0c** [comment]
Fixed problem with update angular on version 7.
