### ISSUE TITLE
Quill Editor doesnt work in ionic prod build

### ISSUE THREAD

**Issue by rodrigo-sntg** [KillerCodeMonkey/ngx-quill#280]
I can't build in production mode with quill component.
I've tried on the demo app with ionic3 (KillerCodeMonkey/ngx-quill-ionic-v3), but it doesn't build in 
production (ionic cordova build android --prod --release) anyway.

I got this error:

```
[14:20:58]  ionic-app-script task: "build" 
[14:20:58]  Error: Ignoring local @import of "quill.core.css" as resource is missing.,Ignoring local @import of 
            "quill.snow.css" as resource is missing.,Ignoring local @import of "quill.bubble.css" as resource is 
            missing. 
Error: Ignoring local @import of "quill.core.css" as resource is missing.,Ignoring local @import of "quill.snow.css" as resource is missing.,Ignoring local @import of "quill.bubble.css" as resource is missing.
    at new BuildError (/home/murah/Documentos/teste/ngx-quill-ionic-v3/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at taskReject (/home/murah/Documentos/teste/ngx-quill-ionic-v3/node_modules/@ionic/app-scripts/dist/worker-process.js:36:22)
    at /home/murah/Documentos/teste/ngx-quill-ionic-v3/node_modules/@ionic/app-scripts/dist/worker-process.js:14:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

```

I have already tried changing versios as I've seen in other topics and it didn't work.

Does anyone have any clue?

**Comment by KillerCodeMonkey** [comment]
Yeah and AS You See your CSS Imports are Not Working. Check Out the way You
can Extend the Ionic build.

There IS the possibilty to Copy external assets to the build folder ;).

Am Fr., 9. Nov. 2018, 18:02 hat rodrigo-sntg <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
Checkout
https://github.com/ionic-team/ionic-app-scripts/blob/master/README.md

Am Fr., 9. Nov. 2018, 18:02 hat rodrigo-sntg <notifications@github.com>
geschrieben:

**Comment by rodrigo-sntg** [comment]
But the wierdest thing is that my project is working just fine when do the ionic serve, or even when I try the ionic build cordova android.

I just got this error when trying the (ionic cordova build android --prod --release.

I'll try to look what you've said. Thanks!!

**Comment by rodrigo-sntg** [comment]
The solution was to change the import to the index.html.
on the copy.config.js:
```
copyQuillCSS: {
    src: [`{{ROOT}}/node_modules/quill/dist/*.css`],
    dest: '{{WWW}}/assets/css'
  }
```
and on the index.html
`<link rel="stylesheet" type="text/css" href="/assets/css/quill.snow.css">`

Then I've removed the import from the app.scss.
And it worked just fine!

Thank you for replying!

**Comment by KillerCodeMonkey** [comment]
No Probs. Glad You got IT! Please Close the issue. Thanks for Sharing your
solution.

Am Fr., 9. Nov. 2018, 19:44 hat rodrigo-sntg <notifications@github.com>
geschrieben:
