### ISSUE TITLE
setDisabledState of ControlValueAccessor

### ISSUE THREAD

**Issue by swymmwys** [KillerCodeMonkey/ngx-quill#282]
Please, add implementation of 'setDisabledState' method of ControlValueAccessor. Method implementation is quite simple, you just need to call appropriate method of quill editor instance either .enable() or .disable, based on what you have got in 'setDisabledState' method.
Because for now there is no straightforward way to disable editor.
In my case I want to disable whole form and I need to get all instances of quill editor through the '@ViewChildred' and manually call .disable() method for each instance.
It is also will be helpful if you can add 'disabled' attribute to the host element to have a simple way to apply styles.
Thanks.

**Comment by swymmwys** [comment]
@KillerCodeMonkey please, check out my PR, please.

**Comment by KillerCodeMonkey** [comment]
I will Check it on thursday

Am Mo., 12. Nov. 2018, 21:07 hat swymmwys <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
merged #283

**Comment by KillerCodeMonkey** [comment]
check v4.1.0

Example is also added to the example repo 👍
