### ISSUE TITLE
[style] property binding not working

### ISSUE THREAD

**Issue by luizdanielmlima** [KillerCodeMonkey/ngx-quill#286]
Hi, I´m using ngx-quill in my project and first of all thank you for this awesome component!

I´m building a simple presentation app where the user selects a color among some options, through a drop-down. I´ve tried to use databinding to change it´s background-color, in my HTML, this way:

`<quill-editor [(ngModel)]="richText" [placeholder]="placeholder" [modules]="editorModules" [style]="editorStyles"></quill-editor>`

Then in my .ts file, I have  the following:

`  updateEditorBgColor() {
    this.editorStyles = {
      height: "300px",
      "background-color": this.txtBgColorValue
    };
  }`

This function is executed when the drop-down (change) event occurs. I have console.logged inside the updateEditorBgColor function, and "this.txtBgColorValue" is being changed accordingly, so I don´t know why the quill-editor is not showing the new color through the databinding.

Any help is appreciated!
Thanks.

**Comment by KillerCodeMonkey** [comment]
depends on what you expect. 

I loop over the style-object keys an use the Angular Renderer2 to set the style attributes.
Maybe you need to pass the background-color as "backgroundColor"?

And the style is added to the root editor element. If you want to only change the color of the "textarea" you need to extend/overwrite the quilljs styling.

**Comment by KillerCodeMonkey** [comment]
check the second editor on https://killercodemonkey.github.io/ngx-quill-example/

**Comment by luizdanielmlima** [comment]
Hello, I saw the example you sent, but in my application I was also able to set this value trough the property biding [style], like so:

`    <quill-editor
      [(ngModel)]="viewData.text.html"
      [placeholder]="placeholder"
      [modules]="editorModules"
      [style]="{ height: '300px', backgroundColor: txtBgColorValue }"
    ></quill-editor>`

BUT, when I change the "txtBgColorValue" dinamically (through a drop-down with preset color values), the editor is not updating its background color.

Could you update this example you sent with a case like that, where maybe there is a "random color" button that changes the editor´s bg color dinamically?

Thank you in advance!

**Comment by KillerCodeMonkey** [comment]
yep. i do not rerender the style, yet. so you can set them initially.

I will check this :)

**Comment by KillerCodeMonkey** [comment]
@luizdanielmlima checkout v4.3.2 and the example repo :)

**Comment by luizdanielmlima** [comment]
Thanks, I will take a look.  What is the easiest way to specifically update the quill module in the angular-cli? Sorry for asking...

**Comment by KillerCodeMonkey** [comment]
öhhh, bump the version in your package.json? run npm install or yarn install?

But maybe i do not get the question correct

**Comment by luizdanielmlima** [comment]
Sorry, how to install the new version you just added, via npm install

**Comment by KillerCodeMonkey** [comment]
you have ngx.quill already in your package.json right? than simply increase the version? and rerun npm install.

**Comment by luizdanielmlima** [comment]
Hello, it works! Thank you very much, you´re awesome!

**Comment by KillerCodeMonkey** [comment]
No Problems.

Am Do., 29. Nov. 2018, 20:32 hat Luiz Daniel Lima <notifications@github.com>
geschrieben:
