### ISSUE TITLE
onEditorCreated is triggered, but editor is not ready to receive content

### ISSUE THREAD

**Issue by jchatel** [KillerCodeMonkey/ngx-quill#288]
In my component, I'm listening to the onEditorCreated event. But it seems like at this moment, the editor is not ready to receive things.

```
  onEditorCreated(quill) {
    quill.clipboard.dangerouslyPasteHTML(0, 'something');
  }
```

Nothing will be added to the quill editor

But if I do this

```
  onEditorCreated(quill) {
    setTimeout(() => {
      quill.clipboard.dangerouslyPasteHTML(0, 'something');
    }, 3000);
```

"something" will be added in the Quill editor after 3 seconds.

Same goes with setContents

Any idea?

Edit: using "ngx-quill": "^3.4.0"

**Comment by KillerCodeMonkey** [comment]
i think because it is not rendered completely in this moment.

But way setting the content on your own instead of using ngModel or formControl?

**Comment by jchatel** [comment]
facepalm... Thanks you rock 👍
