### ISSUE TITLE
onContentChange() Debounce option

### ISSUE THREAD

**Issue by frankspin89** [KillerCodeMonkey/ngx-quill#29]
Would be nice to set a x number of seconds to debounce the onContentChange function. 

So when you want to save data to your back end, you can write it every x seconds.

**Comment by KillerCodeMonkey** [comment]
you could use formControls or observables at all:

like described here:
https://blog.thoughtram.io/angular/2016/01/06/taking-advantage-of-observables-in-angular2.html

I added an example of usage formConrols/Observables with debounce and distinctUntilChanged.
Observables are mighty tools.

Even the angular eventemitter is based on it.

Check out https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts

or as live example: https://killercodemonkey.github.io/ngx-quill-example/
the reactive forms example --> open dev tools ans js console to see the output.

<img width="1214" alt="bildschirmfoto 2017-04-07 um 14 27 03" src="https://cloud.githubusercontent.com/assets/2264672/24800012/84bd3112-1b9e-11e7-9da7-359a7e6258f8.png">

**Comment by KillerCodeMonkey** [comment]
Or you can simple get some ideas of this post:
http://www.talkinghightech.com/en/angular-2-creating-search-field-debounce-time/
the angular 2 part --> hang on the `onContentChanged` Event and create your own Subject --> and subcribe to it, so you can use all observable functions like debounceTime ;).

So you could pass additional info like the quill instance to it.

**Comment by KillerCodeMonkey** [comment]
And me again, there is another easy way --> use the ViewChild decorator to access the quill editor component in your dom. After that you can subscribe directly to the onContentChanged event and use the native debounce stuff before.

i added this also to the example described above

```
view child + directly subscription Object {editor: Quill, html: "<div>test asdf</div>", text: "test asdf↵", delta: Delta, oldDelta: Delta…}
```
should be in your js console if you change the reactive form editor (this approach will also work without reactive forms or anything ;))

**Comment by KillerCodeMonkey** [comment]
@frankspin89 any updates?

**Comment by frankspin89** [comment]
@KillerCodeMonkey Thanks so much for your fast and comprehensive answer. 
Try to get back to you today, little busy on work today. 

Keeping this issue open for now.

**Comment by KillerCodeMonkey** [comment]
and again... any news?
