### ISSUE TITLE
focusout when clicking toolbar

### ISSUE THREAD

**Issue by armory09** [KillerCodeMonkey/ngx-quill#290]
https://github.com/quilljs/quill/issues/1290

**Comment by KillerCodeMonkey** [comment]
so it is enough when there is one ticket ;)

And you can solve this like it is mentioned there.

In angular you could write a custom directive - add this directive to quill-editor-tag.
in your directive you can select the toolbar element, after the view is init.

`document.querySelector('.ql-toolbar').addEventListener....`

**Comment by armory09** [comment]
@KillerCodeMonkey  thank you

**Comment by harshini66** [comment]
Add This code inside your script :
         document.querySelector('.ql-picker-label').addEventListener("click", function(e){
                e.stopPropagation();
            });

It works better for me...
