### ISSUE TITLE
HTML output

### ISSUE THREAD

**Issue by tomort** [KillerCodeMonkey/ngx-quill#292]
Hello

Is it possible to get the html without the start and end <p></p> tags, and change one to <br>
for example: 
change this      <p>hello</p><p>hello</p>
to this               hello<br>hello

Can I configure this output?

regards
Tom

**Comment by KillerCodeMonkey** [comment]
nope.. only taking the whole content.

but you can switch the output format, if you only want the plain text, the whole html or a json object representation.
