### ISSUE TITLE
Sanitize isn't a known property of 'quill-editor'

### ISSUE THREAD

**Issue by zsoltuveges** [KillerCodeMonkey/ngx-quill#293]
Hello, I would like to add this html tags to the editor :
```
<div class="news-image-box">
    <img src="${image.path}" alt="${image.description}">
    <div class="row">
        <div class="col-md-9"><p>${image.description}</p></div>
        <div class="col-md-3 news-image-credit"><p>${image.credit}</p></div>
    </div>
</div>
```

I can added with ngModel two-way databinding, but the quill (I think) removes the div tags and add only the image and its details with <p> tag. I tried to off sanitize like this : 
`    <quill-editor [(ngModel)]="contentText"
                  [sanitize]="false"
                  [ngModelOptions]="{standalone: true}"
                  [modules]="quillConfig"
                  (onEditorCreated)="getEditorInstance($event)"></quill-editor>`

But this throws an error like : "ng: Can't bind to 'sanitize' since it isn't a known property of 'quill-editor'."
What am I doing wrong?

**Comment by KillerCodeMonkey** [comment]
Do You use the latest ngx-quill Version? Checkout the repo of my
example/Demo App. There IS an example with sanitizing

Am Mi., 28. Nov. 2018, 14:44 hat zsoltuveges <notifications@github.com>
geschrieben:

**Comment by zsoltuveges** [comment]
I have "ngx-quill": "^4.1.0", and "quill": "^1.3.6". I checked the example, and I think I do the same. :( 
This is your example:
> <quill-editor [(ngModel)]="dangerousModel" [sanitize]="true"></quill-editor>
And I used the sanitize also like you, and this is why I am here :D

**Comment by zsoltuveges** [comment]
Okay, I now the p tags replaced by divs.. But those are not my divs :D and its a problem because I lost my css classes, which I want to add to it... like in the html block what I sent in my Question. So my problems is not with the p tags, but the Quill remove somehow my divs with css classes. :/

**Comment by KillerCodeMonkey** [comment]
yeah and first of all, you can not pass ${image.description} bindings to the editor i think

and i do not know how you can add custom classes to quill but it should be possible, but is more a quilljs question (i am not a quilljs expert btw :D)

But for this you have to check out this guide:
https://quilljs.com/guides/how-to-customize-quill/

you can extend the known styles and formats of the editor.
Maybe this helps:
https://stackoverflow.com/questions/44219124/creating-a-custom-class-attributer-in-quilljs#44225523
