### ISSUE TITLE
Template parse errors, what I do wrong

### ISSUE THREAD

**Issue by malinich** [KillerCodeMonkey/ngx-quill#294]
I have angular 6.0.6
Dependencies:
installed 
-    "quill": "^1.3.6",
-    "ngx-quill": "^4.3.0"

Use:
```
@NgModule({
    imports: [
       ...
      QuillModule
]
export class MyModule {}

//template
  <quill-editor [(ngModel)]="agency.intro"></quill-editor>
```
`core.js:1673 ERROR Error: Uncaught (in promise): Error: Template parse errors:
'quill-editor' is not a known element:
If 'quill-editor' is an Angular component, then verify that it is part of this module.` ..........

What wrong with me.

**Comment by KillerCodeMonkey** [comment]
> What wrong with me.
> 
> 

Sorry I am not a therapist. Glad you solved the problem yourself :D
