### ISSUE TITLE
Full toolbar options from Quilljs

### ISSUE THREAD

**Issue by TauanMatos** [KillerCodeMonkey/ngx-quill#295]
Is there a way to use this full option toolbar or I have to create a custom toolbar?

![image](https://user-images.githubusercontent.com/23512680/49242734-3f052a00-f3ea-11e8-81b6-23f2e2f05e3a.png)

**Comment by KillerCodeMonkey** [comment]
You can Pass the formats and Options AS input Binding - Check the readme.

Or simply Set IT one time in the global config also mentioned in the
readme. But You have to define it one time in your own :)

Inspect the sourcecode of the quill Page and try to Grab the modules config
object.

Am Do., 29. Nov. 2018, 19:20 hat Tauan Matos <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
did you got it?

**Comment by KillerCodeMonkey** [comment]
in the quilljs example they build it up with custom toolbar config

```
modules: {
        'syntax': true,
        'toolbar': [
          [{ 'font': [] }, { 'size': [] }],
          [ 'bold', 'italic', 'underline', 'strike' ],
          [{ 'color': [] }, { 'background': [] }],
          [{ 'script': 'super' }, { 'script': 'sub' }],
          [{ 'header': '1' }, { 'header': '2' }, 'blockquote', 'code-block' ],
          [{ 'list': 'ordered' }, { 'list': 'bullet'}, { 'indent': '-1' }, { 'indent': '+1' }],
          [ 'direction', { 'align': [] }],
          [ 'link', 'image', 'video', 'formula' ],
          [ 'clean' ]
    ]
 }
```

**Comment by test0017** [comment]
I have created the above modules in component but with [modules] its not working .

**Comment by KillerCodeMonkey** [comment]
are there some errors or could you share some code?

And you can checkout the linked demo - example repositories. there you have working examples :)

**Comment by patchworkfish** [comment]
Hi guys - similarity between this thread and ["How to show *all* available buttons by default? #1335"](https://github.com/quilljs/quill/issues/1335)

I cannot find a **complete** definition of setting the tool bar options using JSON, extending what is shown by @KillerCodeMonkey above (from the [readme](https://github.com/KillerCodeMonkey/ngx-quill/blob/master/README.md)).
For example, if I want to show the align buttons next to each other rather then a list, I cannot find how to reference the LEFT align button! The below example shows center and right (found by trial and error) but left does not work! :

```
 var quillToolbarOptions = [
        ...
        [{ 'align': 'left'}, { 'align': 'center'}, {'align': 'right'}],
        ...
];
```

**Comment by KillerCodeMonkey** [comment]
this is a quill issue. and just checkout the quilljs repo and search the code for this:

https://github.com/quilljs/quill/blob/f32aa5f5360e90920d0a4ecf0d029c5135a24975/docs/index.html#L87

align left is the default alignment so it does not has a specific value... try empty string or null

**Comment by patchworkfish** [comment]
That did solve the specific text-align example there, thanks @KillerCodeMonkey. I had seen that HTML code example, but without your guidance couldn't make the leap.

**Comment by relidrissihsaini** [comment]
is there a possibility to add a table too at toolbar module ?

**Comment by KillerCodeMonkey** [comment]
This is not Part of quilljs V1. V2 is not stable and i so Not Support that
Version.

So you can Just kick out ngx-quill and use plain quilljs v2.0.0-dev.3

Or try you luck ignoring The Peer dependencies of ngx-quill and Install
quilljs v2 + typings for v2.

relidrissihsaini <notifications@github.com> schrieb am Fr., 4. Sept. 2020,
17:39:
