### ISSUE TITLE
kindly publish more examples

### ISSUE THREAD

**Issue by somombo** [KillerCodeMonkey/ngx-quill#30]
Hi could you publish more examples of how to use this package.

In particular it would me nice if there was a folder called "examples" with the source code of https://killercodemonkey.github.io/ngx-quill-example/ in it.

Thanks

**Comment by KillerCodeMonkey** [comment]
way not simply fork the example repo? i do not want to add unnecessary stuff to this source repo.

for ng-quill it is simply an html file, but with angular4 i have other webpack configs and deps.

**Comment by somombo** [comment]
Where is this example repo? it would be usefule if you included the link somewhere obvious, like right on the front page right after the link to the live site.

**Comment by somombo** [comment]
thanks!

**Comment by KillerCodeMonkey** [comment]
if you want to restructure the the examples, feel free to contribute and send a pull request ;)

**Comment by somombo** [comment]
thanks i just might :)

Somo +1(321) 222-3003
Follow me <https://plus.google.com/+ChisomoSakala> | *Sent from my
Second-countable Hausdorff space*
