### ISSUE TITLE
Unable to compile Quill 1.6.0 with Angular 4.x

### ISSUE THREAD

**Issue by knowrama** [KillerCodeMonkey/ngx-quill#304]
Hi,

Below is my project config in brief.

"@angular/cdk": "2.0.0-beta.8",
"@angular/common": "4.2.5",
"@angular/compiler": "4.2.5",
"@angular/compiler-cli": "4.2.5",

"ngx-quill": "^1.6.0",
"quill": "^1.3.6",

devDependencies": {
    "@types/hammerjs": "2.0.34",
    "@types/jasmine": "2.5.35",
    "@types/node": "6.0.45",
    "adf-tslint-rules": "0.0.3",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "^2.2.0",
    "codelyzer": "3.1.2",
    "copy-webpack-plugin": "4.0.1",
    "css-loader": "0.26.1",
    "extract-text-webpack-plugin": "2.0.0-rc.3",
    "file-loader": "0.10.0",
    "fork-ts-checker-webpack-plugin": "0.2.4",
    "happypack": "^4.0.0-beta.1",
    "html-loader": "0.4.4",
    "html-webpack-plugin": "2.28.0",
    "jasmine-core": "2.5.2",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-ajax": "0.1.13",
    "karma-jasmine-html-reporter": "0.2.0",
    "karma-mocha-reporter": "2.2.2",
    "karma-remap-istanbul": "0.6.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-webpack": "2.0.3",
    "node-sass": "4.5.3",
    "null-loader": "0.1.1",
    "raw-loader": "0.5.1",
    "rimraf": "2.6.1",
    "sass-loader": "6.0.5",
    "script-loader": "0.7.0",
    "source-map-loader": "0.1.6",
    "sourcemap-istanbul-instrumenter-loader": "0.2.0",
    "style-loader": "0.13.1",
    "to-string-loader": "1.1.5",
    "ts-loader": "2.2.1",
    "tslint": "5.5.0",
    "tslint-loader": "3.5.3",
    "typescript": "2.3.4",
    "webpack": "2.2.1",
    "webpack-dev-server": "2.3.0",
    "webpack-merge": "2.6.1",
    "wsrv": "0.1.6"
  },

I have included the quill.js like this..
```
<script src="node_modules/quill/dist/quill.core.js"></script>
<script src="node_modules/quill/dist/quill.js"></script> 
```
When I do a npm start.. I get the following error.

![quill_import issue_new](https://user-images.githubusercontent.com/3500868/50149300-d0c4d080-02e0-11e9-889c-94d131e8c6ee.PNG)

What am  I doing wrong.. I am not able to compile the project. Pls. let me know if you need more info.
It says appropriate loader, which loader should I use.
Thanks,
Ram

**Comment by KillerCodeMonkey** [comment]
1. i would update my deps ;) ... angular 4 is a way toooo old.
2. i can not remember what was working in this release. in this old releases you do not have aot or ssr support.

I think you have to configure your webpack to compile node_modules. 

You could try to checkout the ngx-quill-example repo and try to jump back to an old version, which uses ngx-quill v 1.6.0

**Comment by knowrama** [comment]
Hi,

Thanks for your help.. I shall see if I can get over this...

Regards,
Ram

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
did you solved it?
