### ISSUE TITLE
Not able to get div ,span aand body tags

### ISSUE THREAD

**Issue by sripalreddyadamala** [KillerCodeMonkey/ngx-quill#306]
I have these sample html text  in my text area which will be copied and then paste in to editor where user  will add some  tags on editor and then we  have a create button to get all these html values backinto  into my textarea box. 
Expected behavior:
I should technically get all my div and span classes in my footer tag  but now it is replaced with p tags and i am lossing all my css classes,div and span tags during conversion.
sample html:

```
<footer>
    <div class="text-center" style="padding-right: 55px;padding-left: 55px;">
        <p>I am a test footer</p>
        <p>test var 1: <span cp-text="td.extras.test1" translate="td.extras.test1"></span></p>
        <p>test var 2: <span cp-text="td.extras.test2" translate="td.extras.test2"></span></p>
        <p>test var 2: <span cp-text="td.extras.ticket.price" translate="td.extras.ticket.price"></span></p>
        <p>test var 2: <span cp-text="td.extras.event.location" translate="td.extras.event.location"></span></p>
    </div>
</footer>
```

In UI editor it diplays my content  like below:
I am a test footer

test var 1: 

test var 2: 

test var 2: 

test var 2: 

same code Once I click on create it converts everything into p tag and loose all my css classes and div tag. Not sure why editor is not understanding div footer body classes.

```
<p>I am a test footer</p><p>test var 1: </p><p>test var 2: </p><p>test var 2: </p><p>test var 2: </p>
```

Solution:
How do I get my old html snippet back after I do modification on editor like sample html

**Comment by KillerCodeMonkey** [comment]
Thats how quill Editor works ;). Checkout the Demo repo there You can See
an example how to Switch from p Tags to divs.

You should Not use quill with HTML Strings. IT IS recommended to use it
with json or quill object representation.

The Editor uses ITS own classes and Styling . This IS the only way to
garantee that You really geht what You see in the Editor.

Am Mi., 19. Dez. 2018, 21:35 hat sripal <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
Here is a simple guide how to change the editor, as part of it - how to switch to divs and use additional classNames

https://quilljs.com/guides/cloning-medium-with-parchment/#tweets

And here a little thing about inline styles vs classes
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline
