### ISSUE TITLE
在angular7下，双向绑定会报错！

### ISSUE THREAD

**Issue by qikong333** [KillerCodeMonkey/ngx-quill#309]
![image](https://user-images.githubusercontent.com/23370805/50469642-4e2ac800-09e8-11e9-8576-6a02316c9893.png)
![image](https://user-images.githubusercontent.com/23370805/50469700-93e79080-09e8-11e9-8cab-7e25dc668ead.png)
![image](https://user-images.githubusercontent.com/23370805/50469825-24be6c00-09e9-11e9-8b17-4c6f576e9f34.png)
![image](https://user-images.githubusercontent.com/23370805/50470140-6996d280-09ea-11e9-808b-083c2260ee6f.png)

删除了[ngModel]="editorContent"就正常显示

**Comment by KillerCodeMonkey** [comment]
Do You import the QuillModule in You Module?

IT IS mentioned in the readme how to include IT to your Project.



Am Do., 27. Dez. 2018, 08:03 hat qikong333 <notifications@github.com>
geschrieben:

**Comment by qikong333** [comment]
https://blog.csdn.net/plpldog/article/details/82907724

抱歉，已经解决

**Comment by KillerCodeMonkey** [comment]
Dude please Type in english...

Am Do., 27. Dez. 2018, 08:30 hat qikong333 <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
@qikong333 just follow the readme instructions and checkout the demo repos.

Sounds like you forgot to add the QuillModule to your app.module imports.

**Comment by qikong333** [comment]
> @ qikong333只需按照自述文件说明操作即可查看演示回购。
> 
> 听起来好像忘了将QuillModule添加到app.module导入中。

Sorry, I forgot to import the FormsModule
