### ISSUE TITLE
Custom Toolbar position with v. 4.4.4

### ISSUE THREAD

**Issue by bogacg** [KillerCodeMonkey/ngx-quill#310]
I just updated to v 4.4.4 and toolbar position suddenly changed to the bottom of text area.

Is there a new setting to define toolbar position?

Thanks

**Comment by KillerCodeMonkey** [comment]
which version did you use before?

**Comment by KillerCodeMonkey** [comment]
I will Check this

Am Do., 27. Dez. 2018, 10:27 hat Bogac Guven <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
i will provide a fix in v4.4.5 in some minutes
