### ISSUE TITLE
change request for Syntax Highlighting - already tested

### ISSUE THREAD

**Issue by Awatatah** [KillerCodeMonkey/ngx-quill#311]
Please update code and docs with below:

I was able to achieve syntax highlighting (Angular 6) by adding `highlight.js` dependencies and configuration to the `index.html` head:
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/monokai-sublime.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
<script>
	hljs.configure({
	    languages: ['javascript', 'ruby', 'bash']
	});
</script>
```
then editing `ngx-quill/src/quill-editor.interfaces.d.ts` with:

```
...
export interface QuillModules {
    toolbar: QuillToolbarConfig;
    syntax: boolean;
}
...
```

Then in `app.module.ts`
```
...
const toolbarOptions = [
  { size: [ 'small', false, 'large', 'huge' ]},
  {},
  'bold',
  'italic',
  'underline',
  'strike',
  'link',
  'image',
  {},
  { 'color': [] },
  { 'background': [] },
  {},
  { 'indent': '-1'},
  { 'indent': '+1' },
  { 'list': 'ordered'},
  { 'list': 'bullet' },
  { 'align': [] },
  {},
  'code-block', //<---
  'clean'
];

...

@NgModule({
  imports: [
    ...,

    QuillModule.forRoot({
      modules:{
        syntax: true,
        toolbar: [toolbarOptions]
      }
    }
    ),
  ],
  ...
})
export class AppModule { }
```

**Comment by KillerCodeMonkey** [comment]
i do not know what to change here?
in the latest version the interface contains the 'syntax' key.
https://github.com/KillerCodeMonkey/ngx-quill#global-config

everything else is describe in the quilljs documentation?
https://quilljs.com/docs/modules/syntax/#example

But i added an example to my ngx-quill-example repo:
https://killercodemonkey.github.io/ngx-quill-example/

**Comment by Awatatah** [comment]
My mistake, I see in the commits you already did this 9 days ago 😀

**Comment by KillerCodeMonkey** [comment]
No probs. You are Welcome :)

Am Sa., 5. Jan. 2019, 16:00 hat Awatatah <notifications@github.com>
geschrieben:
