### ISSUE TITLE
Text Alignment is aligned center and align left is not working

### ISSUE THREAD

**Issue by abnersouza** [KillerCodeMonkey/ngx-quill#313]
After installation the latest version "ngx-quill": "^4.5.0" with angular "^7.1.4", I notice that the text is coming aligned center, when i try to align left is not working, right is fine, center is fine, justified is fine, but left is not working, and the alignment is default to left, not sure if the same is happening for everyone, i had no problem before.

Also is there a way to set the default to be justified so I can solve the issue for the moment?

Aligned left not working:
<img width="1165" alt="screen shot 2019-01-07 at 21 56 10" src="https://user-images.githubusercontent.com/3270632/50800414-3ea05e80-12c7-11e9-8f7f-5ca361679b8e.png">

Aligned justified working:
<img width="1166" alt="screen shot 2019-01-07 at 21 56 45" src="https://user-images.githubusercontent.com/3270632/50800440-5a0b6980-12c7-11e9-842a-f8a5bc2ce17e.png">

Thanks a lot,
Abner Souza

**Comment by KillerCodeMonkey** [comment]
So You have an Demo repo or Stack Blitz ?

https://killercodemonkey.github.io/ngx-quill-example/
Uses v4.5.0 and the alignment works

Am Di., 8. Jan. 2019, 00:58 hat Abner Souza <notifications@github.com>
geschrieben:

**Comment by abnersouza** [comment]
Fixed override p with div tag, got it from your example.
Thanks
