### ISSUE TITLE
Custom toolbar + hard coded format options

### ISSUE THREAD

**Issue by mikepictor** [KillerCodeMonkey/ngx-quill#314]
I haven't yet quite found the answer to this in the other tickets. This is just a question really.

I have a custom toolbar, works fine.

What I want to do is, in addition to this custom toolbar, I went to fix a property (in this case direction). I know I can a ql-direction button and let the user control it, but I want to start on RTL (at least...I sometimes do, depending on their application preferences). 

Ideally, I would just set the component to direction=rtl and be done with it (but not via css, I need the relationship between direction and alignment that is handled through the ql-direction button)

In a pinch...I could offer the button to the user, but if I do, I need it to default to RTL (and if they want to switch it to LTR...ok). I haven't found how to "activate" a toolbar option so it starts on a non-default value.

**Comment by KillerCodeMonkey** [comment]
you could listen to `onEditorCreated` output and grab the quill-editor instance from there.

and then use:
https://quilljs.com/docs/api/#format

to activate your needed format?

**Comment by KillerCodeMonkey** [comment]
ah i checked it. 

You have to set formats:
`align: "right"` and `direction: "rtl"`

**Comment by mikepictor** [comment]
I am experimenting with editorCreated created right now..

I am not sure where to set those formats (if I am able to skip the business of doing this from the event). They aren't properties of the <quill-editor> object

**Comment by KillerCodeMonkey** [comment]
i tested it and it is working :).

```
<quill-editor (onEditorCreated)="setFormat($event)"></quill-editor>
```

```
setFormat(editor) {
  editor.format('align', 'right');
  editor.format('direction', 'rtl');
}
```

I think you could also get the QuillEditorComponent via angulars ViewChild and there is a public property `quillEditor`

**Comment by mikepictor** [comment]
ooh....that's so close.

When I try that (was just missing how to phrase those lines), it does work...briefly. If I put breakpoints on the code, I can see the formatting take effect, including the align button the toolbar flipping to right, but as soon as the code is done, it flips back to left.

**Comment by KillerCodeMonkey** [comment]
strange maybe you have to switch from p-tags to divs?

i added an example to my demo repo:
https://killercodemonkey.github.io/ngx-quill-example/

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts#L43
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts#L255

**Comment by mikepictor** [comment]
Hmm...I think it has to do with how our component demo tool is rendering them, it renders the component, and then ... draws it a second time, I think? This may not happen if I implement this "for real". I'll give it a try. The buttons stayed activated until nearly the end of the stack, so I am pretty sure the rest of it is on my end to sort out.

**Comment by KillerCodeMonkey** [comment]
maybe your content changes because of a formControl oder model binding?

**Comment by mikepictor** [comment]
I got it working with a timeout
`public editorCreated(editor: any): void {
    if (this.rtl) {
      setTimeout(() => {
        editor.format('align', 'right');
        editor.format('direction', 'rtl');
      }, 0)
    }
  }`

it works, but there is still a noticeable lag (despite the 0 count). However that is definitely related to our own architecture, not yours.

Is it possible to set these properties as part of the initial config? I mean this doesn't work..
`<quill-editor align="right">`
so I know that is overly simplistic, but something in that direction?

**Comment by KillerCodeMonkey** [comment]
You can Change the Default of the toolbar formats so You can build it this
way.

I think You can search in the quill documentation - modules - toolbar
section for it.

In my Demo repo You can See how to Change Fonts and the Default Font.

And If You Wang a switch between RTL and ltr Just add an ngIf in your
toolbar and handle both defaults :).

I do Not want to add such Inputs foreach possible Format.

Am Di., 8. Jan. 2019, 22:24 hat mikepictor <notifications@github.com>
geschrieben:

**Comment by mikepictor** [comment]
oh I know how to change default formatting options (different fonts and so on), just haven't found how to actually ACTIVATE some of the formatting options (use non-defaults). 

I go through the documentation further, see if I overlooked something

**Comment by KillerCodeMonkey** [comment]
Thats Not possible.

You should add the custom Format with your own Default if IT IS RTL Just
add another AS IT would be for ltr , switching classes and Option Order ;)

Or another and easy approach:

You could Pass a Default content which Inserts a blank newline with the
quill css classes. Or If You use Not the HTML content, You can Pass a
content object with the Formattings ;)

Am 08.01.2019 10:34 nachm. schrieb "mikepictor" <notifications@github.com>:

oh I know how to change default formatting options (different fonts and so
on), just haven't found how to actually ACTIVATE some of the formatting
options (use non-defaults).

I go through the documentation further, see if I overlooked something

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/KillerCodeMonkey/ngx-quill/issues/314#issuecomment-452459790>,
or mute the thread

**Comment by KillerCodeMonkey** [comment]
feel free to close the issue if you think it is solved
