### ISSUE TITLE
Config options?

### ISSUE THREAD

**Issue by ErraticFox** [KillerCodeMonkey/ngx-quill#315]
Hello, while using `<quill-editor></quill-editor>` how exactly do I use the config options in my components ts or html file?

**Comment by KillerCodeMonkey** [comment]
just checkout my demo repo linked in the readme:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts

and here is the live demo for it:
https://killercodemonkey.github.io/ngx-quill-example/

but all config options are simple angular inputs
https://angular.io/guide/component-interaction

**Comment by KillerCodeMonkey** [comment]
did you got it working?

**Comment by KillerCodeMonkey** [comment]
Any Updates?

**Comment by ErraticFox** [comment]
Sorry, not in my env right now. I tried using ngModel at one point iirc, but it gave me the error saying it was unknown.

**Comment by KillerCodeMonkey** [comment]
Yeah because You have to import angulars FormsModule then ;)

Am Mo., 14. Jan. 2019, 17:33 hat ErraticFox <notifications@github.com>
geschrieben:

**Comment by heinhoang** [comment]
do you mean this
```
<quill-editor
  [(ngModel)]="htmlText"
  placeholder="Enter Text"
  [modules]="quillConfig"
  (onSelectionChanged)="onSelectionChanged($event)"
  (onContentChanged)="onContentChanged($event)"></quill-editor>
```

**Comment by KillerCodeMonkey** [comment]
close due to inactivity
