### ISSUE TITLE
Focus problem with NgbModal

### ISSUE THREAD

**Issue by AlphonseDoge** [KillerCodeMonkey/ngx-quill#316]
Hello, I'm trying to use your editor inside of a ngbModal but there's a focus problem. When I try to edit the style, for example, setting the text to bold, the editor resets its cursor to the beginning without changing the style of the selected text. It works great outside of the modal, but I can't get it to work inside of the modal. I tried manually setting the focus with 
`(onEditorCreated)="setQuillInstance($event)"` 
and
`setQuillInstance(quill) {
    this.quillInstance = quill;
this.quillInstance.focus();
  }`
but the cursor keeps resetting...
Since it's related to ng-bootstrap, I guess you don't know either but maybe you have a hint!

Thanks for your time 😄

**Comment by KillerCodeMonkey** [comment]
do you have a working example for me? stackblitz, codepen or anything?

And yes, i do not know anything about ng-bootstrap and its modal :D.
Maybe you should ask there :)

**Comment by KillerCodeMonkey** [comment]
seems like ngb modal is auto focussing the first tabable element:
https://github.com/ng-bootstrap/ng-bootstrap/pull/2737#issuecomment-423518189

Try to set the focus later - maybe after the modal is fully rendered?

```
ngAfterViewInit()
```

or something. maybe the modal itself has a custom output for that.

**Comment by AlphonseDoge** [comment]
Thank you, I'll try that and get back to you asap! 😄

**Comment by AlphonseDoge** [comment]
It solved my problem! Thank you very much!

**Comment by KillerCodeMonkey** [comment]
You are Welcome ;)

Am Mi., 9. Jan. 2019, 16:47 hat AlphonseDoge <notifications@github.com>
geschrieben:
