### ISSUE TITLE
Scroll programmatically within quill-editor

### ISSUE THREAD

**Issue by knallfr0sch** [KillerCodeMonkey/ngx-quill#317]
Sorry to bother you, but is there a way to scroll programmatically within the quill-editor?

There seems to be no such input like `[scroll]` in `quill.editor.component.d.ts` and no scrolling in ngx-quill-example.

I'm talking about something like this:
`quill.container.scrollTop = bounds.top;` which i found at [this StackExchange answer](https://stackoverflow.com/questions/30294057/how-to-ensure-programmatically-selected-text-is-visible-in-quill-when-scrollbars).

My intention is to store certain scrolling positions within the quill editor (let's assume the width is keptconstant.)

**Comment by KillerCodeMonkey** [comment]
Just Grab the quilleditorcomponent with angular @ViewChild there You have
Access to the quillEditor instance after its creation.

Or Just Listen on the onEditorCreated Output (See the readme and the
example repo how to use it) and Grab the instance there.

Now You can use the full quilljs API ;)

Am Mi., 9. Jan. 2019, 16:38 hat knallfr0sch <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
```
<quill-editor (onEditorCreated)="scrollInEditor($event)"></quill-editor>
```

```
scrollInEditor(editor) {
  editor.setSelection(10, 20);
  const bounds = editor.getBounds(10, 20);
  editor.container.scrollTop = bounds.top;
}
```
