### ISSUE TITLE
Slow progress understanding

### ISSUE THREAD

**Issue by ChuckIrvine** [KillerCodeMonkey/ngx-quill#319]
I'm making slow progress understanding how to use ngx-quill. My fault, I'm sure. For one thing, it would be great if there were a ng cli example project similar to the example web pack project. I'm just now learning Angular, and I'm not very familiar with web pack, per se. It would be even better if each quill editor instance was packaged in its own component, with some way to switch between components. 

Anyway, I'll keep plugging away.

Thanks

**Comment by ChuckIrvine** [comment]
I saw the CLI example. Actually, I duplicated that on my own before I saw the example. Was pretty straight forward after reading your readme.

I couldn’t figure out how to build and run the advanced example. Instructions for doing that would be useful perhaps.

What I’m doing now is kind of what I suggested. I created a bare bones CLI app with ngx-quill integration.

Now, I’ll create a component for each of your editor instances in the web pack sample app, and then manually place the component’s selector in the app.component.html file. That should be instructive.

Thanks for your nice work.

**Comment by ChuckIrvine** [comment]
FYI - I’m working on the advanced example refactoring. It’s been a good exercise to understand everything. I should be done with it in a day or two. I can do a PR if you’d like.

-Charles

**Comment by KillerCodeMonkey** [comment]
Feel free :) thanks

Am So., 20. Jan. 2019, 00:18 hat Chuck <notifications@github.com>
geschrieben:

**Comment by ChuckIrvine** [comment]
Making good progress now. Thanks
