### ISSUE TITLE
Cant Choose image in ionic 3

### ISSUE THREAD

**Issue by codot91** [KillerCodeMonkey/ngx-quill#320]
hello sir, im using ionic. ngx quill work well,
but after i upload image, in my phone can't choose image, please look my screenshoot
![image](https://user-images.githubusercontent.com/10111459/51443109-a8ccf080-1d16-11e9-909e-5b8623c9ecdb.png)

Thanks Before

**Comment by KillerCodeMonkey** [comment]
How do you "Upload" an Image to your Phone?

Am So., 20. Jan. 2019, 18:51 hat codot91 <notifications@github.com>
geschrieben:

**Comment by codot91** [comment]
I upload using ngx-quill.. 
After i press image on tollbar, i cant select image and insert to editor

**Comment by KillerCodeMonkey** [comment]
If i use my Ionic v3 example in a Browser IT IS working fine

https://killercodemonkey.github.io/ngx-quill-ionic-v3/

But you have to allow your Browser to Access your Filesystem

If you build a Native app with cordova you should Check If you need to Set
some permissions in your cordova.config.

Am So., 20. Jan. 2019, 19:12 hat codot91 <notifications@github.com>
geschrieben:

**Comment by codot91** [comment]
https://killercodemonkey.github.io/ngx-quill-ionic-v3/ work perfect

but after i compile to apk. cant choose image

**Comment by KillerCodeMonkey** [comment]
I think quilljs IS optimized for Browsers and Not mobile Apps. If you need
File Access your need the camera or File Plugin.

So you can try to Checkout Ionic Native Docs and Install IT. Maybe this IS
enough.

But If you ASK me, you need to build your own Image toolbar Button.
Listening on a click. Then asking the User If he wants to make a Photo or
choose one.

The camera Plugin can be used and configured for both use cases.

You can even get a base64 String representation of the Image. Via the
quilljs API you can get the current Cursorposition to Insert IT.

Am So., 20. Jan. 2019, 19:38 hat codot91 <notifications@github.com>
geschrieben:

**Comment by codot91** [comment]
i using native camera and base64. 

when insert, why all code base64 not image?
this is my scritp to insert to ngmodel
`this.ThreadCredentials.isi=this.ThreadCredentials.isi+this.base64Image;`

**Comment by KillerCodeMonkey** [comment]
Checkout quilljs documentations . Just get the current Text selection when
clicking your toolbar Button (onSelectionChange) gets triggered, with the
latest Cursor Position in the Editor. Than start your camera Handling and
If you have the base64 url use quilljs Editor API to Insert the Image at
the Vorrecht Position

You get the quilljs Editor instance by listening to onEditorCreated for
example.

Check the quilljs documentations how to Insert content at a specific
Position ;)

Am Mo., 21. Jan. 2019, 19:12 hat codot91 <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
did you got it?

**Comment by KillerCodeMonkey** [comment]
inactivity
