### ISSUE TITLE
Issue with validation - it only happens once

### ISSUE THREAD

**Issue by kkulikowski** [KillerCodeMonkey/ngx-quill#322]
Hello,
I'm using latest version of quill. I'm using it with ngModel and required attribute. On component init im using setContents and/or insertText to throw some data into the control.
It all works well except validation - it looks like it only happens once, when field is empty. After i throw some data into it it is still with ng-invalid class. The strange thing is that if i change input 'by keyboard' ng-invalid vanishes. Do you have any idea what can be wrong with it..?

**Comment by KillerCodeMonkey** [comment]
Could you Share a Demo codepen or Stackblitz to Reproduce the issue?

And why do you call setContents in your own ?

You should only Change your Model.

Am Di., 22. Jan. 2019, 23:38 hat Krzysiek <notifications@github.com>
geschrieben:

**Comment by KillerCodeMonkey** [comment]
Validation IS Not triggered If you use quill API. Because IT IS Something
like an "internal content Change". The validation IS connected with
angulars Control, so you need to change the Model to Trigger validation

Am Mi., 23. Jan. 2019, 07:06 hat Bengt Weiße <bengtler@googlemail.com>
geschrieben:

**Comment by kkulikowski** [comment]
I have an old code to maintain, and thats how it was working, i will change it the proper way soon. Thanks, thats totally reasonable, ill work on the model now.
