### ISSUE TITLE
Validation fails if Validator added after empty value is added

### ISSUE THREAD

**Issue by GlasgowKid** [KillerCodeMonkey/ngx-quill#323]
Validation fails if an empty value is set before adding the `[required]`-Validator.

### Set-up:
    <form [formGroup]="formGroup">
        <quill-editor formControlName="quillEditor" [required]="true"></quill-editor>
        <input type="checkbox" formControlName="toggleValidation"/>
    </form>
    <pre><code>quillEditor.value: {{ quillEditor.value | json }}</pre</code>
    <pre><code>quillEditor.errors: {{ quillEditor.errors | json }}</pre</code>

### Steps to reproduce:
    ngAfterViewInit() {
        this.formGroup.controls.toggleValidation.valueChanges.subscribe(validationOn => {
            let validator: ValidatorFn;
            if (!validationOn) {
                validator = this.formGroup.controls.quillEditor.validator;
                this.formGroup.controls.quillEditor.clearValidators();
            } else if (!!validator) {
                this.formGroup.controls.quillEditor.setValidators(validator);
                validator = null;
            }
        }
    }

### Effect:
When I set up an empty value as initial value before adding the validator, validation will always fail, even if the user inputs text to the quill editor:

    quillEditor.value: "<div>Test value</div">
    quillEditor.errors: {
        "requiredError": {
            "empty": true
        }
    }

Tested in Chrome and IE11

(What I'm mainly trying to do is to toggle the validation dynamically depending of the value of another control. Since `[required]="formGroup.value.toggleValidation"` showed no effect, I tried it as shown above. This works fine if the initial value isn't empty, i.e. errors are null in the beginning, and if I empty the initial value validation fails with requiredError)

**Comment by GlasgowKid** [comment]
Except that I needed to update value and validity on pressing the toggle button:

    toggleRequired() {
        this.isRequired = !this.isRequired
        this.form.get('title').updateValueAndValidity({ emitEvent: true })
    }

Now everything works as expected and is much cleaner in code. Thanks!

**Comment by KillerCodeMonkey** [comment]
but why you need 
this.form.get('title').updateValueAndValidity({ emitEvent: true }) ?

do you have other validators there?

**Comment by GlasgowKid** [comment]
Yes, I have another plain text input field where I add or remove Validators.required depending on the toggle button.

Ok, it's only necessary to call updateValueAndValidity on the other control. :-)
