### ISSUE TITLE
quill editor component global Quill object

### ISSUE THREAD

**Issue by abrakadobr** [KillerCodeMonkey/ngx-quill#325]
src/quill-editor.component.js
line 5.
change from
`var Quill = undefined;`
to
`var Quill = window.Quill || undefined;`
this will make component using global Quill object, if exists, allowing configure editors with global Quill object.
for example:
```
declare var Quill:any
....
Quill.imports['formats/link'].PROTOCOL_WHITELIST = ['http','https','tg','mailto']
```

**Comment by KillerCodeMonkey** [comment]
i added an example:
i changed the block blot from p tags to div tags:
http://localhost:4200/

check the reactive forms example, there you see the content output :)

and i did it in the app.component.ts
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/app.component.ts#L3

**Comment by abrakadobr** [comment]
Thanks a lot for your help! =)
