### ISSUE TITLE
quill:toolbar ignoring attaching to nonexistent format undefined

### ISSUE THREAD

**Issue by kacime** [KillerCodeMonkey/ngx-quill#326]
Hello,
I have this error message
quill:toolbar ignoring attaching to nonexistent format undefined in the console
exactly like on your demo page (https://killercodemonkey.github.io/ngx-quill-example/).
When i work locally, everything is fine and I can see all tools in the toolbar but when I deploy the application, tools for coloring text, font, and alignment are not working.
Lot of thanks.
Maxime

**Comment by KillerCodeMonkey** [comment]
thanks for mentioning... seems like the angular cli production build.

if you use `ng build` without `--prod` it is working fine.

**Comment by KillerCodeMonkey** [comment]
@kacime should be working, now :). I changed a little thing, and it seems to work.

**Comment by kacime** [comment]
It works very well, thank you very much for your quick reply !
