### ISSUE TITLE
How can I change the toolbar color?

### ISSUE THREAD

**Issue by billyessing** [KillerCodeMonkey/ngx-quill#329]
<img width="1148" alt="screen shot 2019-02-06 at 4 14 59 pm" src="https://user-images.githubusercontent.com/37524621/52321750-68fe4c80-2a2a-11e9-940c-a19c6ae4dfea.png">

Is there a way to change the color of the toolbar? Or alternatively is there a way to change the font-color of the toolbar options?

Thanks

**Comment by KillerCodeMonkey** [comment]
Multiple ways: 
1. create your own quill theme
2. override global quill css with your styling

checkout my demo repo, i am setting some styles in the https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/styles.css file.

**Comment by billyessing** [comment]
Ok thanks :)
