### ISSUE TITLE
How to add custom handler

### ISSUE THREAD

**Issue by larxenne** [KillerCodeMonkey/ngx-quill#33]
Hi, first of all, thank you for this cool package :).

So, here is my issue: I need to add a custom handler for the images (I don't want the image to be stored in base 64)

How can I add a custom handler ?

**Comment by KillerCodeMonkey** [comment]
checkout my answer here:
https://github.com/KillerCodeMonkey/ng-quill/issues/106

**Comment by larxenne** [comment]
I've check this answer, but my question is: how can I put the options in the controller and not it the template ?

**Comment by KillerCodeMonkey** [comment]
check the second to last comment here: https://github.com/quilljs/quill/pull/995

**Comment by KillerCodeMonkey** [comment]
any updates?
