### ISSUE TITLE
Remove target="_blank" on anchor links

### ISSUE THREAD

**Issue by jedmarcnocum** [KillerCodeMonkey/ngx-quill#330]
Hi good day! Is it possible to remove the target="_blank" attribute when creating anchor links?

**Comment by KillerCodeMonkey** [comment]
This is already a native quilljs issue:

https://github.com/quilljs/quill/issues/2152
https://github.com/quilljs/quill/issues/1139

I hope the first link provides a workaround/solution for you. Implementing your own Blot by extending the default Link Blot
