### ISSUE TITLE
Accessing clipboard API - dangerouslyPasteHTML

### ISSUE THREAD

**Issue by oneEyedSunday** [KillerCodeMonkey/ngx-quill#333]
Hello there, I'm passing HTML into the editor via a default value. It keeps getting stripped to only `p` and `blockquote` tags. I need to preserve my HTML since I trust it. I've used the output from `(onSelectionChanged)` and `(onEditorCreated)` to get access to the `quill` instance. I've inspected the quill instance and there's a `clipboard` `node`, but there's no `dangerouslyPasteHTML` function. Any ideas. I've followed this [issue](https://github.com/KillerCodeMonkey/ngx-quill/issues/195) to get here. Thanks.

**Comment by KillerCodeMonkey** [comment]
yeah but if you are using quilljs api, that is not a problem of quilljs ;)

But you should check if you are using the correct quilljs version
https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml

And in quilljs 1.3.6 there is such a methond provided to the clipboard module:
