### ISSUE TITLE
Error getting while ng serve ?

### ISSUE THREAD

**Issue by PrasanthMV1987** [KillerCodeMonkey/ngx-quill#334]
I am getting the follwing error while doing ng serve . `ERROR in multi ./node_modules/chartist/dist/chartist.css ./node_modules/ng2-slim-loading-bar/style.css ./node_modules/c3/c3.min.css ./node_modules/ngx-toastr/toastr.css ./node_modules/quill/dist/quill.snow.css ./node_modules/quill/dist/quill.bubble.css ./node_modules/angular-calendar/css/angular-calendar.css ./node_modules/dragula/dist/dragula.css ./node_modules/@swimlane/ngx-datatable/release/index.css ./node_modules/@swimlane/ngx-datatable/release/themes/material.css ./node_modules/@swimlane/ngx-datatable/release/assets/icons.css ./src/assets/vendor/css-chart.css ./src/assets/scss/style.scss ./src/styles.css Module not found: Error: Can't resolve '/node_modules/chartist/dist/chartist.css' in '' ERROR in multi ./node_modules/chartist/dist/chartist.css ./node_modules/ng2-slim-loading-bar/style.css ./node_modules/c3/c3.min.css ./node_modules/ngx-toastr/toastr.css ./node_modules/quill/dist/quill.snow.css ./node_modules/quill/dist/quill.bubble.css ./node_modules/angular-calendar/css/angular-calendar.css ./node_modules/dragula/dist/dragula.css ./node_modules/@swimlane/ngx-datatable/release/index.css ./node_modules/@swimlane/ngx-datatable/release/themes/material.css ./node_modules/@swimlane/ngx-datatable/release/assets/icons.css ./src/assets/vendor/css-chart.css ./src/assets/scss/style.scss ./src/styles.css Module not found: Error: Can't resolve '/node_modules/quill/dist/quill.bubble.css' in '' ERROR in multi ./node_modules/chartist/dist/chartist.css ./node_modules/ng2-slim-loading-bar/style.css ./node_modules/c3/c3.min.css ./node_modules/ngx-toastr/toastr.css ./node_modules/quill/dist/quill.snow.css ./node_modules/quill/dist/quill.bubble.css ./node_modules/angular-calendar/css/angular-calendar.css ./node_modules/dragula/dist/dragula.css ./node_modules/@swimlane/ngx-datatable/release/index.css ./node_modules/@swimlane/ngx-datatable/release/themes/material.css ./node_modules/@swimlane/ngx-datatable/release/assets/icons.css ./src/assets/vendor/css-chart.css ./src/assets/scss/style.scss ./src/styles.css Module not found: Error: Can't resolve '/node_modules/quill/dist/quill.snow.css' in '' ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected. node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected. node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected. `

**Comment by KillerCodeMonkey** [comment]
Checkout my Demo Repo how to use quill and ngxquill with. Angular cli.

You need to Install quilljs and add the CSS and Scripts to you angular.json
AS Scripts and Styles.

But your problem IS Not ngx quill related, because Like you can read in the
Error Message you are Missing some More Styles. Ng2-slim-loading-bar,
ngx-toastr, calendar, Chartlist and so on

Are you Sure you have installed all that dependencies and added/Imported
the Stylesheets?


Am Sa., 9. Feb. 2019, 11:46 hat PrasanthMV1987 <notifications@github.com>
geschrieben:
