### ISSUE TITLE
Convert quill CSS to inline CSS

### ISSUE THREAD

**Issue by RscAnonymous** [KillerCodeMonkey/ngx-quill#337]
Is there a functionality to convert all the custom quill CSS to inline ones in order to make all the other editors (used by Gmail and outlook) understand it?

**Comment by KillerCodeMonkey** [comment]
dude one issue is enough... and those questions should be asked at the quilljs repo and not here.
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

**Comment by evgeny-ykm** [comment]
@KillerCodeMonkey  ok so you have posted a link that says to use this code:
```
var ColorClass = Quill.import('attributors/class/color');
var SizeStyle = Quill.import('attributors/style/size');
Quill.register(ColorClass, true);
Quill.register(SizeStyle, true);

// Initialize as you would normally
var quill = new Quill('#editor', {
  modules: {
    toolbar: true
  },
  theme: 'snow'
});
```
Clearly it is not angular way, so I don't really see how it solves the issue. 
Where this code should go, how to use it in context of angular?

**Comment by KillerCodeMonkey** [comment]
you just need to register the stylings first. After that all editors have those inline styling.

```TS
const ColorClass = Quill.import('attributors/class/color');
const SizeStyle = Quill.import('attributors/style/size');
Quill.register(ColorClass, true);
Quill.register(SizeStyle, true);
```

**Comment by evgeny-ykm** [comment]
@KillerCodeMonkey, Thanks for the quick answer. I just put it in the component right after the imports. Not sure if it is the right place, but it works !

**Comment by Noor0** [comment]
Is there a way to inline `indent` styles for list?

**Comment by angelaki** [comment]
Hey, wouldn't this option make sense as part of `QuillModule.forRoot()`?

**Comment by Bartosh-s** [comment]
`import * as Quill from 'quill';

const alignClass      = Quill.import('attributors/style/align');
const backgroundClass = Quill.import('attributors/style/background');
const colorClass      = Quill.import('attributors/style/color');
const directionClass  = Quill.import('attributors/style/direction');
const fontClass       = Quill.import('attributors/style/font');
const sizeClass       = Quill.import('attributors/style/size');

Quill.register(alignClass, true);
Quill.register(backgroundClass, true);
Quill.register(colorClass, true);
Quill.register(directionClass, true);
Quill.register(fontClass, true);
Quill.register(sizeClass, true);

`
