### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by mike-morr** [KillerCodeMonkey/ngx-quill#338]
I am not sure if this is an issue with StackBlitz or maybe a dependency version issue or what.

Could you take a look at this?  I tried to follow the example, but it's not working.

https://stackblitz.com/edit/angular-quill-syntax

**Comment by KillerCodeMonkey** [comment]
https://stackblitz.com/edit/angular-quill-syntax-6vk43c?file=src/index.html

just make sure your hightlightjs is loaded before your angular code...
try to write valid html files ;)

And if you would check the JS console + google you can avoid opening issues which are only a problem of the usage :)

**Comment by mike-morr** [comment]
When Stackblitz gave me an 'Angular CLI' app without an html, head, or body tag I assumed it was because it was already adding them.  My bad.

I also tried Google and didn't get any where.

BTW, I like how you say something rude and then follow it with a smily face.  If you want people to donate you might want to treat them with respect.

I apologize for wasting your valuable time.  :)

**Comment by KillerCodeMonkey** [comment]
thats not rude what i wrote. i think.
there are hints and tips in every sentence i wrote, like checking js console and before opening issues in general make sure it is not your fault or investigate deep enough and learn where to open issues or maybe use stackoverflow.

I often do not have time to create magnificent sentences and texts beside my full time job, but i want to answer all issues and help.

And when i use smileys i am not in a bad mood at all 🙃

But you are write - time is very valuable and even i appreciate very open source repo i am using that is well maintained!

And another hint to stackblitz and angular cli.
You can try to use highlight.js via package.json and put it in the scripts section of the angular.cli.

The problem with inde.htmls without header and body --> you do not know exactly where angular and your angular code is loaded (header or body). If you define scripts in a script tag you make sure they are loaded before the generated angular code.

**Comment by Sangram9693** [comment]
Nice article for [Code higligting](https://blog.almightytricks.com/2020/10/27/code-highlighting-ngx-quill/)
