### ISSUE TITLE
Module parse failed: Unexpected character '@' (5:0)

### ISSUE THREAD

**Issue by popoleeMaster** [KillerCodeMonkey/ngx-quill#339]
Hello, Sorry to disturb by creating another helping request.

I been struggling very hard trying to implement quill in my company app.
It's a old angularjs/4 hybrid app, using webpack.

I installed,  

npm install ngx-quill@1.6.0
npm install quill

Added the script to the index (do not know if needed

`      <script src="/node_modules/quill/dist/quill.min.js"></script>`

but I got the followind error.

```
ERROR in ./node_modules/ngx-quill/src/quill.module.ts
Module parse failed: Unexpected character '@' (5:0)
You may need an appropriate loader to handle this file type.
| import { QuillEditorComponent } from './quill-editor.component';
|
| @NgModule({
|   declarations: [
|     QuillEditorComponent
 @ ./node_modules/ngx-quill/index.js 1:0-35
 @ ./public/ts/app/app.module.ts
 @ ./public/ts/main.ts
 @ multi ./public/ts/main.ts webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=true
```

Am I doing something wrong ? 

I do have those two file quill.module.d.ts and quill.module.ts

the latter trigger this error 

```
import { NgModule } from '@angular/core';

import { QuillEditorComponent } from './quill-editor.component';

@NgModule({
  declarations: [
    QuillEditorComponent
  ],
  imports: [],
  exports: [QuillEditorComponent],
  providers: []
})
export class QuillModule { }

```

**Comment by KillerCodeMonkey** [comment]
uhhh. v1.6.0... i can not remember it... it is so long ago :D.

A recommendation... please upgrade your project.

angular v4 is not longer supported by angular and even angular 5 will be unsupported in may this year.

It could be that i changed the builds in this release.
Can you just try a version < 1.6.0?
it is mentioned in the readme:

v4 | < 1.6.0

But please use angular 6 at least. It is not that hard to upgrade ;)

**Comment by popoleeMaster** [comment]
that is lightning fast answer, I wish I could chose the version of angular of the project ahah.
I will check 1.5.1

**Comment by KillerCodeMonkey** [comment]
yeah... it was a long time ago and a little bit hazzle with server side renderung and so on. And i really do not know, what is (not) working. So i do not recommend to use it :D

**Comment by KillerCodeMonkey** [comment]
how is it going?

**Comment by popoleeMaster** [comment]
Sorry, I went out of job yesterday,

So I did installed 1.5.1 and quill, but still got the same issue, I do not want to investigate further atm (cause anyway I believe this is to old for you to fix anyway, there is no big use of it, and also it can be related to my project that is a mess ahah), I will try to find another lib for older angular, and use this as argument to try to convince my coworker to push to a newer version of angular soon. 

Thanks for your time

**Comment by KillerCodeMonkey** [comment]
A Last Idea. Check my ngx-quill-example Repo. Check the Tag or commit
History .

I started with plain webpack and angular instead of angular cli

Am Fr., 15. Feb. 2019, 00:28 hat popoleeMaster <notifications@github.com>
geschrieben:
