### ISSUE TITLE
Unable to work with language tool

### ISSUE THREAD

**Issue by nitesh61929** [KillerCodeMonkey/ngx-quill#341]
Language tool extension for google chrome append something like `<lt-div spellcheck="false" class="lt-highlighter__wrapper" style="width: 538px; height: 155px;"><canvas class="lt-highlighter__canvas" width="538" height="155" style="margin-top: 0px !important; margin-left: 0px !important;"></canvas></lt-div>` in the value for quill editor. 
Is there a way to fix this?

**Comment by KillerCodeMonkey** [comment]
try to remove it programmatically?

I do not have another idea :D.
Grab the quill editor instance and remove this content.

There are some quill issues with chrome addons:
https://github.com/quilljs/quill/issues/574

i can not do anything here, because it seems to be a general quilljs issue.
