### ISSUE TITLE
How to change to show or hide toolbar

### ISSUE THREAD

**Issue by khackskjs** [KillerCodeMonkey/ngx-quill#342]
How to change showing and hiding toolbar?

After editing article, I need to hiding toolbar and border to check whole page
This is success of hiding border`[style]="editting ? {height: '500px'} : {border: '0px'}"`
This is not working of changing toolbar status `[modules]="editting ? {toolbar: true} : {toolbar: false}"`

I think [modules] initialize just once when component loads and then keep out change.
should I use two quill-editor like below example code? give me some hint.

this code is working anyway
```
<div *ngIf="!editting">
  <quill-editor [(ngModel)] = "contentsHtmlString"
                [readOnly]  = "true"
                [style]     = "{ border: '0px' }"
                [modules]   = "{ toolbar: false }">
  </quill-editor>
</div>
<div *ngIf="editting">
  <quill-editor [(ngModel)] = "contentsHtmlString"
                [style]     = "{ height: '450px' }"
                [modules]   = "">
  </quill-editor>
</div>
```

**Comment by KillerCodeMonkey** [comment]
Its Not ment to be dynamic. In quilljs you have to initialize IT once.

I do not know If IT IS possible to Change modules Afterwards. I think you
have to use ngIf and Render another Editor instance without the toolbar

Am Mo., 18. Feb. 2019, 16:24 hat Robert Kim <notifications@github.com>
geschrieben:

**Comment by khackskjs** [comment]
@KillerCodeMonkey Wow~ awesome. how reallllly super fast answer it is!
Thank you. I'm gonna use what you recommend and I made a example.

**Comment by qialex** [comment]
for me it feels easier to `display:none;` a **toolbar** sometimes instead of dealing with 2 instances

**Comment by hemanntthreddy** [comment]
Hey, how can i change editting boolean value when i focussed on editor
