### ISSUE TITLE
Embed video rerender on window resize

### ISSUE THREAD

**Issue by epitomz** [KillerCodeMonkey/ngx-quill#344]
Hi,

I have a problem with the youtube video I add in my text editor.

Here is what I do:
```html
<quill-editor [(ngModel)]="sanitizedString" [modules]="myModules"></quill-editor>
<div class="output" [innerHTML]="sanitizedString"></div>
```

The output html for the video is:
```html
<iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.youtube.com/embed/Z9U2PIS9DGQ?showinfo=0"></iframe>
```
The problem is:
If you resize the window, all the generated html in my `output` div is rerendered and especially the video. On an iPhone it's not even possible to play the video because it's automatically put in fullscreen mode, the resize is called and the iframe is rerendered.

Have any clue on this?

By the way thanks for your work:)

**Comment by KillerCodeMonkey** [comment]
I think you should ASK this in the quilljs Repo :).

I do Not know how quill styles the Video.

In General you should use a quilleditor for the Output. Just disable
toolbar and Set readonly Mode.

This IS recommended by quilljs.

Quilljs provides the Option to Switch to Inline Styles. Maybe this gehelps.

Just search for "inline" in the quilljs documentation.

Am Di., 19. Feb. 2019, 22:06 hat epitomz <notifications@github.com>
geschrieben:

**Comment by epitomz** [comment]
Thanks for your anwser and sorry for the disruption

**Comment by KillerCodeMonkey** [comment]
No probs :). IS the Video correctly rendered inside the editor, when you
resize IT?



Am Di., 19. Feb. 2019, 22:12 hat epitomz <notifications@github.com>
geschrieben:

**Comment by epitomz** [comment]
In the editor there is no problem, so I will use your solution and also show the output in an readnonly editor but that's weird...

**Comment by KillerCodeMonkey** [comment]
Yeah in General quilljs recommends Not using HTML to Store IT in your
Database, because HTML very hard to Patch or migrate or Switch to another
Editor.

Quilljs Blot representation can be easym migrated.

Okay but you could try to load quilljs Styles globally, so the classes of
quill get applied to your div.

But you have to decide what solution fits your needs.



Am Di., 19. Feb. 2019, 22:18 hat epitomz <notifications@github.com>
geschrieben:

**Comment by epitomz** [comment]
I implemented a readonly editor with my own CSS classes to show the output and everything's fine:)
Thanks for your advise concerning the storage of the string.

I just found [this very interesting issue](https://github.com/quilljs/quill/issues/2276).

**Comment by KillerCodeMonkey** [comment]
Glad you solved your issue

**Comment by BOTOOM** [comment]
try use this https://www.npmjs.com/package/@botom/quill-resize-module
