### ISSUE TITLE
On Focus and On Blur

### ISSUE THREAD

**Issue by jziggas** [KillerCodeMonkey/ngx-quill#346]
Hello again!

I see there are several older issues closed regarding focus and blur events with this component but I didn't see anything that specifically addressed my issue.

We are upgrading from your older ng-quill to ngx-quill inside of a wrapper component. The wrapper component uses the onEditorCreated event to set up a couple of listeners for focus and blur:
```
onEditorCreated(editor) {
    editor.on('focus', (event) => { // Do some stuff }
    editor.on('blur', (event) => { // Do some stuff }
    ...
}
```

But these listeners don't seem to be working anymore. Any idea why? After all, the editor object is from the Quill library itself and not from ngx-quill right? I'll probably have set up a fiddle later to make sure it has nothing else to do with the wrapper component.

**Comment by KillerCodeMonkey** [comment]
Yep search through the issues Here.

Just Listen to onSelectionChanged. There you get the current and old Range.

If old Range is null then IT IS Something like a Focus. If the new Range is
null then IT IS a Blur.

Joshua Ziggas <notifications@github.com> schrieb am Di., 26. Feb. 2019,
21:02:

**Comment by jziggas** [comment]
Oh ok. So something with ngx-quill or Angular is messing with the QuillJS eventing to not work anymore? Does anything `editor.on('...')` work?

**Comment by KillerCodeMonkey** [comment]
I do Not think so, because ngx internally uses native quill Events for
text-change and selection-change.



Joshua Ziggas <notifications@github.com> schrieb am Di., 26. Feb. 2019,
21:07:

**Comment by KillerCodeMonkey** [comment]
So basically IT should Work. But i do Not know how Blur and Focus of
quilljs works.



Bengt Weiße <bengtler@googlemail.com> schrieb am Di., 26. Feb. 2019, 21:10:

**Comment by jziggas** [comment]
LOL ok. So something changed with the eventing on the editor object but we're not sure how or why yet. At least there is a work around. Thanks!

**Comment by jziggas** [comment]
Weird. I don't remember why I used `editor.on('focus', ...)` previously. Maybe something I found from QuillJS issues. In either case I can't stop using focus/blur eventing. We use it to "minimize" the editor on forum replies :) I did get your suggestion working so I'll go with that instead of further troubleshooting. Maybe it will help someone else too:

```
selectionChanged(event): void {
        if (event.range === null) {
            this.onBlur.emit({
                event: event,
                editor: this.editor,
            });
        } else if (event.oldRange === null) {
            this.onFocus.emit({
                event: event,
                editor: this.editor,
            });
        } else {
            this.onSelectionChanged.emit(event);
        }
    }
```

**Comment by KillerCodeMonkey** [comment]
Nice and thanks Mate for the Donation :).


Joshua Ziggas <notifications@github.com> schrieb am Di., 26. Feb. 2019,
21:36:

**Comment by jtomek** [comment]
Just to let you know, there is a case when the above code doesn't produce the desired output. I'm having quill in drag&drop elements. When I focus the editor and then click on a drag&drop area, it does't blur. I don't have a solution yet.

**Comment by KillerCodeMonkey** [comment]
@jziggas i added onFocus and onBlur outputs. But keep in mind to stay consistent with quilljs selectionChanged is also triggered in both cases

**Comment by jziggas** [comment]
Cool, thanks for the heads up.
