### ISSUE TITLE
Move the cursor to the beginning after updating data

### ISSUE THREAD

**Issue by SlavaSavul** [KillerCodeMonkey/ngx-quill#347]
Hello!
How can I dynamically update the data in the editor without moving the cursor to the beginning? I tried to use the writeValue method, I tried to change the binding to ngModel, but it did not help. I need to create a component in which the data will be updated at the process of writing. I tried to use the method quill.updateContents, but it does not update anything.

You can see an example here https://stackblitz.com/edit/ngx-quill-sdl3zt?file=src%2Fapp%2Fapp.component.ts

**Comment by KillerCodeMonkey** [comment]
i would simply set the selection to the end of the editor?
https://stackblitz.com/edit/ngx-quill-42p33d?file=src%2Fapp%2Fapp.component.ts

The hacky part is to retrieve the correct position you want to set the cursor.
If you want to set it at the end everytime or behind the inserted content is up to you :)
