### ISSUE TITLE
Toolbar buttons Hiding while adding text to the field in ionic v4

### ISSUE THREAD

**Issue by jawad-aziz-farhad** [KillerCodeMonkey/ngx-quill#348]
Hi, 
At first , I would like to appreciate your work. I'm having an issue in my ionic v4 app. When I click the quill-editor field for adding some text in **Real Android Device** (Samsung Galaxy A5), some of the toolbar buttons hide. I think it's a css issue. Its working fine in the browser if I run app with 
**ionic serve ---lab**

**Comment by KillerCodeMonkey** [comment]
could you inspect the dom with remote debugging?
And check what is happening there?

And i have a ionic v4 demo repo. Try to build this on and run it on your device.

**Comment by jawad-aziz-farhad** [comment]
ok. Let me check this. Thanks

**Comment by jawad-aziz-farhad** [comment]
I was using **quill-editor** inside **ion-item** which was causing the issue. using quill-editor directive stand alone solved the issue.

**Comment by KillerCodeMonkey** [comment]
Glad to here that.

Feel free to Close the issue :)

imFarhad <notifications@github.com> schrieb am Do., 28. Feb. 2019, 11:30:
