### ISSUE TITLE
ngModel only seems to update on input

### ISSUE THREAD

**Issue by netinc** [KillerCodeMonkey/ngx-quill#349]
I find that if I type a message in quill, then add an emoji, the emoji is lost. Unless I type text after it, which will update the ngmodel. Is there a way I could manually force the update before using the ngmodel (e.g. before I submit the form?

**Comment by KillerCodeMonkey** [comment]
I think in my ngx-quill Repo IS an example with the quill-mention Plugin.
In General you can add a custom handler for modules.

So after adding an Emoji Just use the quill Editor instance and add an
empty String with Source "User".

I think of external modules are inserting Something with a User interaction
they should add the change AS "User" and Not "api" or "silent".

I will add a config Option that you can deside wich Change you want Update
the Model.

netinc <notifications@github.com> schrieb am Sa., 2. März 2019, 01:53:

**Comment by KillerCodeMonkey** [comment]
added a pr: https://github.com/contentco/quill-emoji/pull/69

and i improved my quill-emoji example where you can see, how to quick fix this with `trackChanges` config
