### ISSUE TITLE
text color not working when formated

### ISSUE THREAD

**Issue by Dj-jom2x** [KillerCodeMonkey/ngx-quill#350]
```
on editor
<span style="color: rgb(230, 0, 0);">something</span> 

on binded variable
<span>something</span> 

the color is gone
```

**Comment by KillerCodeMonkey** [comment]
I do Not Unserstand your question or Problem.

Please try to describe IT better or create a codepen with an example of the
issue

Coloring Text is working fine in Demo

https://killercodemonkey.github.io/ngx-quill-example/

Dj-jom2x <notifications@github.com> schrieb am Mi., 6. März 2019, 20:38:

**Comment by Dj-jom2x** [comment]
i mean when i bind it to a variable the value inside the editor had color but on the binded variable ..
style color is being ignored .. it only show span and the text inside the color style is ignored..

btw i saw the json format.. how to convert that back to html ?

**Comment by Dj-jom2x** [comment]
try to go in Fomat - Text area and apply a color .. it doesnt work.. the color style is being ignore

**Comment by Dj-jom2x** [comment]
never mind xD i need custom pipes to show this

**Comment by KillerCodeMonkey** [comment]
ah okay. Glad you solve it.

the last editor uses text - as format so the binding contains only plain text without any html ;)

**Comment by gcamara** [comment]
@Dj-jom2x Can you tell me how did u solve it? I have the exact same problem. When you pick a color, the binded variable doesn't seem to be aware of color changing. Which pipes did u use?

@KillerCodeMonkey I saw your example page, but when I pick the color, the result has no colors.

![image](https://user-images.githubusercontent.com/4623526/82476296-2f791580-9aa4-11ea-9582-34f719010a83.png)

**Comment by KillerCodeMonkey** [comment]
if you read the heading "Format - Text" that means it is plain text ;-).

**Comment by Ev1lM4tt** [comment]
Hello,

@Dj-jom2x I had the same problem and I solved it marking my html as trusted with DomSanitizer like said in your documentation @KillerCodeMonkey.

I just created a new pipe using this solution [https://stackoverflow.com/a/40942179/11426025](https://stackoverflow.com/a/40942179/11426025) and applied it to my binded variable like that : 

`<div [innerHTML]="myVar | sanitizeHtml"></div>`

(I use ngx-quill v5.2.0 with Angular 5.2.7)

**Comment by Tran-Minh-Quang** [comment]
> Hello,
> 
> @Dj-jom2x I had the same problem and I solved it marking my html as trusted with DomSanitizer like said in your documentation @KillerCodeMonkey.
> 
> I just created a new pipe using this solution https://stackoverflow.com/a/40942179/11426025 and applied it to my binded variable like that :
> 
> `<div [innerHTML]="myVar | sanitizeHtml"></div>`
> 
> (I use ngx-quill v5.2.0 with Angular 5.2.7)

Can you shared your source code, i use sanitizeHtml but my code alert Cannot find name 'sanitizeHtml'
