### ISSUE TITLE
Editor textbox overflows the parent div when used with angular flex layout

### ISSUE THREAD

**Issue by NithinBiliya** [KillerCodeMonkey/ngx-quill#352]
Editor textbox overflows the parent div when used with angular flex layout.

The height of the editor (grey border) is overflowing the parent div (background in red).

[stackblitz](https://stackblitz.com/edit/angular-98pc2t)

**Comment by KillerCodeMonkey** [comment]
yeah but that has nothing to do with my angular wrapper of quill.
this comes from quilljs css.

just try to set height of `.ql-container` to `auto` in the style.css
```
.ql-container {
  height: auto;
}
```

https://stackblitz.com/edit/angular-98pc2t?file=styles.css

**Comment by NithinBiliya** [comment]
thanks!

**Comment by KillerCodeMonkey** [comment]
no probs 😎

**Comment by EonchGao** [comment]
After setting the auto attribute, when I copy and paste text, the page will jump up
