### ISSUE TITLE
Shorter image's source

### ISSUE THREAD

**Issue by VietHoangQuoc0902** [KillerCodeMonkey/ngx-quill#354]
Hi @KillerCodeMonkey !
Im creating post new post function using ngx-quill as text editor. I want the user can edit html tags too. But when import image, the image's source is too long so that user get hard to edit the html tags. How can i make it shorter?
Im just newbie so please guide me step-by-step.
Sorry about my English's grammar too :D
Thank you @KillerCodeMonkey

**Comment by KillerCodeMonkey** [comment]
how do you insert images?

if you are using the quilljs image toolbar format, try to add a custom imageHandler where you can edit the image content like using urls or add a url shortener and so on

**Comment by VietHoangQuoc0902** [comment]
thank for your soon answer @KillerCodeMonkey !
Im dev in angular 5 and using quill's toolbar for insert image. I have followed your answer but still do not know how to make short image's source :(

**Comment by KillerCodeMonkey** [comment]
you have to know, that i am not a quilljs expert :D.

I think you get an base64 string back if you insert an image?
If you want to have shorter images you need to upload the image somewhere else and insert the url. 

But this is not the default functionality of the default quilljs image blot.

So in that case you need to add a custom image upload.
just google for it or search through the quilljs issues.

**Comment by VietHoangQuoc0902** [comment]
Thank @KillerCodeMonkey ! 
My problem is that base 64 string back - you are right. 

Thank for your help!
