### ISSUE TITLE
How can i programmatically initiate copy/paste/cut?

### ISSUE THREAD

**Issue by AlexZanel** [KillerCodeMonkey/ngx-quill#355]
I redefined the context menu for the editor and i want the user to be able to call these functions from the my context menu.

**Comment by KillerCodeMonkey** [comment]
maybe this fullfills your needs:
https://quilljs.com/docs/modules/clipboard/

so this is more or less a quilljs question not ngx-quill ;).

quilljs has a clipboard module to handle copy and paste.
In other cases you could manually use quilljs selection and the quilljs api to insert stuff.
https://quilljs.com/docs/api/#content
https://quilljs.com/docs/api/#selection

with ngx-quill you have the `onSelectionChanged` output to get informed about selection changes.

**Comment by KillerCodeMonkey** [comment]
@AlexZanel any updates?

**Comment by AlexZanel** [comment]
No thanks.

**Comment by KillerCodeMonkey** [comment]
Because this is more a question and it is some days ago - i will close this one.

But feel free to let us know, if you make some progress or have questions
