### ISSUE TITLE
Insert custom html into quill editor

### ISSUE THREAD

**Issue by FranBor** [KillerCodeMonkey/ngx-quill#358]
I use ngx-quill for my send mail form and in my toolbar I have a drop down with the signatures. When I select a signature I have to insert custom and complex html code (formatted and with img) in the editor, when I change signature I have to replace inserted html code.

I inserted the code in a p tag specifing the id but ngx-quill cleans the code also deleting the id so i can't find the p tag.

I need to preserve the html code and the id.
Help me? Please.

**Comment by KillerCodeMonkey** [comment]
i am using "quill.clipboard.convert" which only allows things quill knows :).
The same thing does quill when you copy and past something in.

you should not use html at all.

In your case i would try to create a custom Blot or a placeholder for the signatures.
When you send the email or show a preview - replace it with your html :).

It is not recommended to use html format with quilljs.

**Comment by KillerCodeMonkey** [comment]
Something like that maybe? 
https://stackoverflow.com/questions/37796409/is-it-possible-to-create-a-custom-format-blot-with-complex-substructure

**Comment by FranBor** [comment]
Thanks for the quick answer,
the example is not compatible with my app, the signature must be editable
What should I use instead of html?

**Comment by KillerCodeMonkey** [comment]
Object representation but therefore you need to create a custom Blot. The
object representation IS an abstraction so you do Not need to handle html.
So you have a Data Set what is easy to migrate or Switch the whole Editor

If quill knows your custom Blot your html IS allowed / Transformed. Just
Take a Look in Myanmar example repo how json or object format Looks Like.
Additional Attributes are working AS Well.

FranBor <notifications@github.com> schrieb am Mi., 20. März 2019, 14:11:

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
Let us know if you have a solution or something else.
