### ISSUE TITLE
Nested Lists not showing up

### ISSUE THREAD

**Issue by seanmccaffery** [KillerCodeMonkey/ngx-quill#359]
Nested lists are getting converted into regular list items.  

For example:

![Screen Shot 2019-03-20 at 3 26 20 PM](https://user-images.githubusercontent.com/5065498/54713252-90b1fb80-4b24-11e9-9bd8-27180878948d.png)

Becomes:

![Screen Shot 2019-03-20 at 3 26 27 PM](https://user-images.githubusercontent.com/5065498/54713251-90b1fb80-4b24-11e9-889d-6f0b9e17672c.png)

**Comment by KillerCodeMonkey** [comment]
how do you use ngx-quill?
Do you have an example repo or a demo on stackblitz or codepen?

**Comment by KillerCodeMonkey** [comment]
@seanmccaffery keep in mind nesting elements are adding the quilljs class `class="ql-indent-1"`.

So if you want to print your editor content, keep in mind you need to load quilljs css or use inline styles 
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

Or just use a readonly editor without a toolbar to render and preview your content.

i added a little example here:
https://killercodemonkey.github.io/ngx-quill-example/

scroll down the last editor with formatHtml --> i added a numbered list into an ordinary list and the result html looks correct. :)

**Comment by seanmccaffery** [comment]
Unfortunately I don't have any examples, it's part of a large Angular project.

I see your example is working fine.  I'm not getting the indent classes added.  I'm not sure but maybe this is related to #53 where html gets stripped since I am also having issues with that.

Also, side question that's probably more of a Quill question but is it possible to set the list style through the toolbar (not through tabbing).

**Comment by seanmccaffery** [comment]
Also, I'm using form controls instead of ngModel like in your example.

**Comment by KillerCodeMonkey** [comment]
If you ask me, i do not know any option to set list styles other than that. But you could check quilljs source code and find the list format. It adds bindings for the "tab" key. Just add you own toolbarbuttons or formats and do the some the "tab"-binding does.

Just checkout my demo repo and replace ngModel with formControl.
But ngModel and formControl is the same (i do not have any special logic).

**Comment by seanmccaffery** [comment]
Alright then, doesn't look like it has anything to do with ngx-quill.  Thanks for the help.

**Comment by KillerCodeMonkey** [comment]
feel free to let us know, if and how you solved it. Hopefuly i guided you in the right direction :)

**Comment by seanmccaffery** [comment]
You nailed it.  It was a problem in two areas.  First, I had an element that would be a read only preview of the content in the quill-editor.  That content was added with innerHTML.   Second, the database is stripping the "ql-indent-" classes after I send up the proper html.

I switched the "preview" div element to a readOnly quill-editor element and removed all instances of innerHTML so now the two line up properly.  All the issues related to #53 are gone.  That just leaves me needing a workaround for the class issue if the front-end is the only option.

**Comment by KillerCodeMonkey** [comment]
For the Last Part Switch from classes to Inline Styling. I think i Linked
IT already in an earlier comment or search for Inline Styles in the quill
documentation .

Glad i helped you :)

Sean McCaffery <notifications@github.com> schrieb am Mi., 20. März 2019,
22:52:
