### ISSUE TITLE
How to style list?

### ISSUE THREAD

**Issue by alexzhao8326** [KillerCodeMonkey/ngx-quill#360]
How to change list's color with inline style? eg.
```javascript
<ul>
    <li style="color:#f00">
        <span>The test text.</span>
    </li>
</ul>
```

**Comment by KillerCodeMonkey** [comment]
you need to switch to inline styles then.
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

or you have to use the corresponding class of quill.
Simply check the output of `onContentChanged`, what quill does, when setting a color ;).

**Comment by alexzhao8326** [comment]
Those style classes are existing, they can style font-size and span's color and so on. But they can't style lists. :(

**Comment by KillerCodeMonkey** [comment]
yeah because in general you would style the text of the list items. :)

check my demo repo:
https://killercodemonkey.github.io/ngx-quill-example/

scroll to the `Fomat - HTML` editor an play around :).

if you want something like that you need to create a custom Blot/Format.

**Comment by alexzhao8326** [comment]
![image](https://user-images.githubusercontent.com/20720227/54976226-a7e56300-4fd4-11e9-879f-66c2c7ae4562.png)
I paste your code to my own ts, but it doesn't work. ahhhh

**Comment by KillerCodeMonkey** [comment]
just checkout the repo of the demo
https://github.com/KillerCodeMonkey/ngx-quill-example

i switched from p-tags to divs as wrapper block elements ;)

**Comment by alexzhao8326** [comment]
![image](https://user-images.githubusercontent.com/20720227/54976647-f6dfc800-4fd5-11e9-824b-688a44eb2c25.png)
Because of this? I add this to my code, still not work.

**Comment by KillerCodeMonkey** [comment]
yeah, but it should be enough, when you replace the divs with p-tags.
and please do not post useless screenshots. You can simply link the File and Codeline your (just click on a line number in a file on github and copy the url.

Or just copy the code and paste it as a code-block
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code ;)

**Comment by alexzhao8326** [comment]
Sorry about that. But it still does't work. :(

**Comment by KillerCodeMonkey** [comment]
what is not working? just select the list items in the editor and color them. Then you see the color is added to each span in the list. 

And go with it.

**Comment by alexzhao8326** [comment]
https://github.com/quilljs/quill/issues/2549?_pjax=%23js-repo-pjax-container
This is my question too. 
I can color the span, but I didn't figure out how to add inline-style to the list.
The toolbar does not offer this function.

**Comment by KillerCodeMonkey** [comment]
yeah but why would you do that?

And again. you can add custom formats and blots to quill if you need that ;)

**Comment by alexzhao8326** [comment]
My boss wants to.  :(
Thank you for help.

**Comment by KillerCodeMonkey** [comment]
just checkout this guide of quilljs:
https://quilljs.com/guides/how-to-customize-quill/#extending-blots

you can easy extend an existing blot like list items.

**Comment by deek13** [comment]
How to change the background color of 'codeblock' ??

**Comment by KillerCodeMonkey** [comment]
css?

just override the quilljs styling of the codeblock in you global css/scss

**Comment by deek13** [comment]
Thanks it helped. @KillerCodeMonkey
