### ISSUE TITLE
how to disable shortcut key like ctrl+b

### ISSUE THREAD

**Issue by Usama-Ibex** [KillerCodeMonkey/ngx-quill#361]
Hi,

i want to disable shortcut keys like ctrl+b. Is it possible or not.

Thank you

**Comment by KillerCodeMonkey** [comment]
read here:
https://quilljs.com/docs/modules/keyboard/#key-bindings

i would just overwrite the default binding, with an empty handler?

**Comment by Usama-Ibex** [comment]
are you able to give example how can i disable?

**Comment by KillerCodeMonkey** [comment]
nope. just try it on your own ;)

Here
https://quilljs.com/docs/modules/keyboard/#configuration

is an example ehere shift + b ist overriden with an empty handler. Just try this.
I will not solve your problems for you especially when it is not a problem with ngx-quill, but with quilljs.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by Usama-Ibex** [comment]
nope

**Comment by KillerCodeMonkey** [comment]
Let us know if you solved it :)

**Comment by Hamma111** [comment]
late to party but interested users can try this. keep adding more keyboard bindings here
``` js
  const modules = useMemo(() => {
    return {
      toolbar: false,
      clipboard: {
        matchers: [
          [
            '*',
            (node, delta) => {
              const ops = delta.ops.map((op) => {
                if (op.insert && typeof op.insert === 'string') {
                  return { insert: op.insert }; // remove formatting
                }
                return op;
              });
              return { ops };
            },
          ],
        ],
      },
      keyboard: {
        bindings: {
          bold: {
            key: 'B',
            shortKey: true,
            handler: () => {},
          },
          italic: {
            key: 'I',
            shortKey: true,
            handler: () => {},
          },
          // Add more bindings you want to disable here
        },
      },
    };
  }, []);
```
