### ISSUE TITLE
Unable to find Undo/Redo options in main Toolbar

### ISSUE THREAD

**Issue by Kiran-GitHuber** [KillerCodeMonkey/ngx-quill#362]
Unable to find Undo/Redo options in main Toolbar

**Comment by KillerCodeMonkey** [comment]
ööhhhm i do not know if there are toolbar buttons for that. 

Just checkout quilljs documentation and add them to your QuillModule.forRoot() configuration. ngx-quill exports the default toolbar so you can extend it ;).

**Comment by Kiran-GitHuber** [comment]
Thanks. It's working.

**Comment by Kiran-GitHuber** [comment]
Able to integrate the functionality, But still have some issues in placing the options in toolbar.

**Comment by drashti2277** [comment]
Can you please share how did you get it working? I'm trying to add undo redo options on the toolbar and figured out QuillJS  ' history module' has these functionality but I'm not able to link it. Can you please help as you have already implemented it!
Thanks in advance.

**Comment by VladislavKhlystun** [comment]
> Can you please share how did you get it working? I'm trying to add undo redo options on the toolbar and figured out QuillJS ' history module' has these functionality but I'm not able to link it. Can you please help as you have already implemented it!
> Thanks in advance.

If you using angular, you should get an instance of quill editor, like: 
```  <quill-editor (onEditorCreated)="editorCreated($event)"```

In your component you should store instance of quill editor: 
```editorCreated(quill: Quill) {
        this.quillEditor = quill;
    }
```
Then you can add custom button to the toolbar and handle click on it. In the handler you can write:
``` this.quill.history.redo() (or undo)```
, and you're done

**Comment by JorisDebonnet** [comment]
I got it working this way. My main difficulty was getting the icons to work ... so I ended up just inlining them, since I did not manage to load them from `node_modules/quill/assets/icons/`.

Relevant pieces of code:

```ts

@Component({/* ... */})
export class MyComponent implements OnInit {
  myEditorContent = new FormControl();

  @ViewChild(QuillEditorComponent, {static: true})
  editor: QuillEditorComponent;

  quillModules = {
    toolbar: {
      container: [
        ['undo', 'redo'],
      ],
      handlers: {
        'undo': () => this.editor.quillEditor.history.undo(),
        'redo': () => this.editor.quillEditor.history.redo(),
      }
    },
    history: {
      userOnly: true // leaves programmatical changes intact, including init'ing the content
    }
  };

  constructor(/* ... */) {
    // Load the Quill Editor toolbar icons for Undo and Redo
    const icons = Quill.import('ui/icons');
    icons['undo'] = '<svg viewbox="0 0 18 18"><polygon class="ql-fill ql-stroke" points="6 10 4 12 2 10 6 10"></polygon>' +
      '<path class="ql-stroke" d="M8.09,13.91A4.6,4.6,0,0,0,9,14,5,5,0,1,0,4,9"></path></svg>';
    icons['redo'] = '<svg viewbox="0 0 18 18"><polygon class="ql-fill ql-stroke" points="12 10 14 12 16 10 12 10"></polygon>' +
      '<path class="ql-stroke" d="M9.91,13.91A4.6,4.6,0,0,1,9,14a5,5,0,1,1,5-5"></path></svg>';
  }
}
```

```html
<quill-editor [formControl]="myEditorContent" [modules]="quillModules"></quill-editor>
```

**Comment by ArekSliwa** [comment]
there is easier way to provide undo, redo icons. You can use css classes which will be created for these buttons:

`<button type="button" class="ql-undo"></button>`
`<button type="button" class="ql-redo"></button>`
 If you use for example material icons you can do it like that:

`
quill-editor {
  ::ng-deep {
    .ql-toolbar {
      background: white;

      .ql-undo {
        &:after {
          content: 'undo';
          font-family: 'Material Icons';
        }
      }

      .ql-redo {
        &:after {
          content: 'redo';
          font-family: 'Material Icons';
        }
      }
    }
  }
}
`

**Comment by Jeremias-Nater** [comment]
Is there a way to disable / remove the undo/redo controls when there is nothing to undo/redo with one of these implementations?

**Comment by KillerCodeMonkey** [comment]
I think this is not possible in quilljs per Default, but you could build
your custom toolbar and hide / disable those buttons

Jeremias Nater ***@***.***> schrieb am Mi., 27. Apr. 2022,
15:34:

**Comment by VictorCubas** [comment]
> ```
>       handlers: {
>         'undo': () => this.editor.quillEditor.history.undo(),
>         'redo': () => this.editor.quillEditor.history.redo(),
>       }
> ```


Hello! Unfortunately this solution does not work in my case, if anyone has an alternative solution it would be welcome.
