### ISSUE TITLE
Is there a way to disable auto links linkified

### ISSUE THREAD

**Issue by ericel** [KillerCodeMonkey/ngx-quill#363]
I was wondering if there's any way to prevent auto linkified when a link is posted in the editor.

[Not really an Issue] Rather a [feature request]

**Comment by KillerCodeMonkey** [comment]
please Checkout the quilljs repo ;)

Oj Obasi <notifications@github.com> schrieb am So., 31. März 2019, 13:16:

**Comment by KillerCodeMonkey** [comment]
@ericel did you found something in the quilljs repo or documentations?

**Comment by KillerCodeMonkey** [comment]
There is a discussion to be able to auto format links: https://github.com/quilljs/quill/issues/109

Maybe you can solve your problem with a custom mather for the clipboard module an overwrite the existing behavior.

But this is a quilljs issue. This is only the angular wrapper :)

**Comment by ericel** [comment]
Thank you!
