### ISSUE TITLE
Rxjs Error

### ISSUE THREAD

**Issue by webrexRavi** [KillerCodeMonkey/ngx-quill#365]
ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.

**Comment by KillerCodeMonkey** [comment]
yeah as you say and see. this is an error in the rxjs and belogs to your project configuration. seems like you are linting/typechecking node_modules?

check my demo/example repo with angular cli. there is no error :).

**Comment by webrexRavi** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/34544558/55382146-893a1b80-5542-11e9-9d5b-6be196ba7500.png)
here what i have update in my project

**Comment by KillerCodeMonkey** [comment]
first of all the angular deps should be the same version like http, animations, common, ....

Check if you are using the correct peerDependencies to rxjs and typescript :)

**Comment by webrexRavi** [comment]
I have just followed the steps you have mentions

**Comment by KillerCodeMonkey** [comment]
yeah but this is not the place for general dependency/angular issues in your project.
So i am giving you some hints to solve it.

But i will not support any question around the base knowledges/technologies, where ngx-quill lives.

**Comment by webrexRavi** [comment]
okay, thanks for advice but before installing **ngx-quill** my project was working normally so my point is that I followed the steps for installing your package and got an error, thanks again man

**Comment by KillerCodeMonkey** [comment]
yeah thats right but for me it is basic knowledge if you are working in the angular universe you know that most of the angular packages are in the same repository - so you should upgrade the other libs as well.

And so i think you are using yarn/npm where you can see warnings for missing peerDependencies or version mismatches.
Sure in my readme you can only read the peer deps of ngx-quill. I am not using http module, so why i should mention it?

And so you are using angular and typescript i think you should know that angular has dependencies to most fixed rxjs and ts versions. :)

But okay... so you learned something new today :D

**Comment by webrexRavi** [comment]
Yeah, solved the issue, thanks for the such a good package and support
