### ISSUE TITLE
preserveWhitespace is not available like react-quill

### ISSUE THREAD

**Issue by abhishekbadola** [KillerCodeMonkey/ngx-quill#366]
> Some details or descriptions would be nice ;)

Actually When I am adding some extra tabs or extra spaces they are not preserved and they are changed to single spaces. I feel like react-quill has done by providing extra config to preserve whitespace.

https://github.com/zenoamaro/react-quill/commit/916a18e88cbe2111e19a02c27f20717b2c36dfbd

**Comment by KillerCodeMonkey** [comment]
Some details or descriptions would be nice ;)

**Comment by abhishekbadola** [comment]
> Some details or descriptions would be nice ;)

Actually When I am adding some extra tabs or extra spaces they are not preserved and they are changed to single spaces.

**Comment by KillerCodeMonkey** [comment]
Ah okay Feel free to create a PR. I do not know how fast i can implement it :).

**Comment by abhishekbadola** [comment]
> Ah okay Feel free to create a PR. I do not know how fast i can implement it :).

Actually I am new to it, so don't know how to proceed with it.

**Comment by KillerCodeMonkey** [comment]
Okay then, how urgent ist that to you ;)

**Comment by abhishekbadola** [comment]
> Okay then, how urgent ist that to you ;)

I am okay with whenever its implemented. :) Thanks.

**Comment by KillerCodeMonkey** [comment]
Thanks, i will let you know, when it is ready

**Comment by KillerCodeMonkey** [comment]
i added an input - documented in the readme and also an example (the last editor in the demo app).

v4.7.0

**Comment by abhishekbadola** [comment]
> i added an input - documented in the readme and also an example (the last editor in the demo app).
> 
> v4.7.0

Thank you very much Bengt Weiße :)
