### ISSUE TITLE
Quill Editor - Issue setting the cursor

### ISSUE THREAD

**Issue by marcelof00** [KillerCodeMonkey/ngx-quill#367]
I am having issues setting the cursor in a particular place.
This is what I have so far:

1) I am populating the editor by adding a 12 characters word using a javascript function that is executed on the body onload.

2) After that, the same javascript function has the following lines:
    quill.focus();    
    quill.setSelection(12, 0);

I tried putting quill.focus() after the setSelection and does not work either.

Any help is greatly appreciated.

**Comment by KillerCodeMonkey** [comment]
Could your complete code Share with a codepen oder Stackblitz?



marcelof00 <notifications@github.com> schrieb am Mi., 3. Apr. 2019, 18:28:

**Comment by marcelof00** [comment]
[Code.zip](https://github.com/KillerCodeMonkey/ngx-quill/files/3039952/Code.zip)

**Comment by marcelof00** [comment]
I uploaded the code here. It is very short.

**Comment by KillerCodeMonkey** [comment]
Please but IT in a codepen or Something like that. I will Not Download zips
;).

Another approach would be to Share a Public repository

marcelof00 <notifications@github.com> schrieb am Mi., 3. Apr. 2019, 19:19:

**Comment by marcelof00** [comment]
Here is the link of the repository: https://github.com/marcelof00/Quill.git

I also invited you as a collaborator

**Comment by KillerCodeMonkey** [comment]
Dude... you are wrong here. this is the repo for the angular wrapper of Quilljs.

You are using plain QuillJS so you have to ask this question here:
https://github.com/quilljs/quill
