### ISSUE TITLE
RROR Error: Syntax module requires highlight.js. Please include the library on the page before Quill.

### ISSUE THREAD

**Issue by simplew11** [KillerCodeMonkey/ngx-quill#368]
Hey KillerCodeMonkey,
![image](https://user-images.githubusercontent.com/25675703/55722273-5d360300-5a38-11e9-81af-b2960a008091.png)

AppComponent.html:65 ERROR Error: Syntax module requires highlight.js. Please include the library on the page before Quill.
    at new Syntax (quill.js:11072)
    at SnowTheme.addModule (quill.js:6057)
    at SnowTheme.addModule (quill.js:6701)
    at quill.js:6049
    at Array.forEach (<anonymous>)
    at SnowTheme.init (quill.js:6047)
    at new Quill (quill.js:1113)
    at QuillEditorComponent.push../node_modules/ngx-quill/fesm5/ngx-quill.js.QuillEditorComponent.ngAfterViewInit (ngx-quill.js:281)
    at callProviderLifecycles (core.js:20982)
    at callElementProvidersLifecycles (core.js:20956)
Thank!

**Comment by KillerCodeMonkey** [comment]
yeah and?

check the error message... everythinf is there... You are trying to use the syntax highlight module (code highlighting) and forgot to include highlight.js..

Check out my demo repo, there is an example and you see how to do it or checkout quilljs docu about syntax module.

**Comment by simplew11** [comment]
Please tell me what to install

**Comment by simplew11** [comment]
Please tell me what to install

**Comment by KillerCodeMonkey** [comment]
https://quilljs.com/docs/modules/syntax/#syntax-highlighter-module
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/index.html#L12
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/formula/formula.component.ts

**Comment by SibeeshVenu** [comment]
If you don't need a syntax highlighting, you can remove the `syntax: true` from the module configuration. This will fix the issue.

```
QuillModule.forRoot({
      modules: {
        toolbar: [['bold', 'italic', 'underline', 'strike'],
        [{ 'header': 1 }, { 'header': 2 }],
        [{ 'list': 'ordered' }, { 'list': 'bullet' }],
        [{ 'size': ['small', false, 'large', 'huge'] }],
        [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
        [{ 'font': [] }],
        [{ 'align': [] }],
        ['clean']
        ]
      }
    })
```

**Comment by KillerCodeMonkey** [comment]
but per default the syntax module should not be enabled?

**Comment by SibeeshVenu** [comment]
> but per default the syntax module should not be enabled?

Yes, I agree. But in my case, I didn't need that. And to fix this error I just had to remove `syntax: true`. Or at the safer side, I guess I should make it `false` instead of removing it.

**Comment by KillerCodeMonkey** [comment]
or simply not add the module to your config :D, when you do not what it is doing. 🤷‍♂️

Have a nice day

**Comment by SibeeshVenu** [comment]
> or simply not add the module to your config :D, when you do not what it is doing. 🤷‍♂️
> 
> Have a nice day

I had to do this `QuillModule.forRoot({` to make only needed options in my toolbar. Have a nice day to you too.

**Comment by augustoantunes** [comment]
> > mas, por padrão, o módulo de sintaxe não deve ser ativado?
> 
> Sim eu concordo. Mas no meu caso, eu não precisava disso. E para corrigir este erro, eu apenas tive que remover `syntax: true`. Ou pelo lado mais seguro, acho que devo fazê-lo em `false`vez de removê-lo.

Eu também removi e funcionou

**Comment by Juraj-Masiar** [comment]
For those of you facing this problem with TypeScript and Webpack, know that `syntax` accepts also object with `highlight` function. 
```
syntax: {
  highlight: (text: string) => hljs.highlightAuto(text).value,
},
```
https://codesandbox.io/s/nww9q0v67p?from-embed=&file=/src/index.js

**Comment by Sangram9693** [comment]
nice article for [code highlighting](https://blog.almightytricks.com/2020/10/27/code-highlighting-ngx-quill/)

**Comment by helen-andronova** [comment]
Use npm Package

If you install highlight.js as an npm package and don't want to expose it to window, you need to pass it to syntax module as an option:
```

import Quill from 'quill';
import hljs from 'highlight.js';

const quill = new Quill('#editor', {
  modules: {
    syntax: { hljs },
  },
});
```

**Comment by ayush-saini033** [comment]
`<div class="rounded-tl-lg border p-4">
  Top-left corner rounded
</div>
`
