### ISSUE TITLE
quill-image-drop-and-paste inclusion

### ISSUE THREAD

**Issue by queejie** [KillerCodeMonkey/ngx-quill#369]
Thanks for this module!

I'm unable to get the quill-image-drop-and-paste included into the modules for quill.  I've tried as below, and get the exception on the addModule() call in ngx-quill.  I tried to do something with onEditorCreated, but I couldn't figure out how to shoehorn it in there.  Am I doing something wrong, or will it not handle quill-image-drop-and-paste?

![image](https://user-images.githubusercontent.com/1616827/55833932-b52b4300-5ae6-11e9-8419-5ddc4b787494.png)

![image](https://user-images.githubusercontent.com/1616827/55833690-228aa400-5ae6-11e9-9add-4c973fffa6ad.png)

**Comment by KillerCodeMonkey** [comment]
ehhhm i do not know... i think this is not an ngx-quill question or error.
it is just how to register it correctly in ts for quilljs.

Just test it with native JS and Quilljs

I got the same error, but the mentioned works without a problem.
https://www.npmjs.com/package/quill-image-drop-module

So i think this is a problem with the module. 

Maybe the image drop module fullfils your requirements.

**Comment by KillerCodeMonkey** [comment]
@queejie i got it.

you have to import it correctly

`import { ImageDropAndPaste } from 'quill-image-drop-and-paste'`

```
import { Component } from '@angular/core'

import Quill from 'quill'
// tslint:disable-next-line:variable-name no-var-requires
import { ImageDropAndPaste } from 'quill-image-drop-and-paste'

Quill.register('modules/imageDropAndPaste', ImageDropAndPaste)

@Component({
  selector: 'app-image-drop-and-paste',
  templateUrl: './image-drop-and-paste.component.html'
})
export class ImageDropAndPasteComponent {
  content = ''
  modules = {
    imageDropAndPaste: {
      handler: () => console.log('test')
    }
  }
}
```

Template

```
<quill-editor
  [(ngModel)]="content"
  [modules]="modules"
>
</quill-editor>
```

**Comment by queejie** [comment]
Those imports do not work in a webpack/angular 7 app.  I ended up solving this by re-writing all the quill modules in Typescript.

**Comment by KillerCodeMonkey** [comment]
ehm i tested it with my demo-repo/app and it works ;)

If the typings are not found for that module just add a custom.d.ts to your project and declare it with an exported member of type any
