### ISSUE TITLE
Will not compile with "noImplicitAny"

### ISSUE THREAD

**Issue by vaags** [KillerCodeMonkey/ngx-quill#37]
Line 93 in "quill-editor.component.ts" throws an error when compiled with Typescripts "noImplicitAny" flag set.

"[ts] Element implicitly has an 'any' type because type 'Object' has no index signature."

The code:

    if (toolbarElem) {
      modules['toolbar'] = toolbarElem; // Throws error
    }

**Comment by KillerCodeMonkey** [comment]
feel free to create a pull request ;)

**Comment by vaags** [comment]
Created a PR now :)

**Comment by KillerCodeMonkey** [comment]
closed with PR #38
