### ISSUE TITLE
What is the correct way to modify modules and icons?

### ISSUE THREAD

**Issue by ArsalanSavand** [KillerCodeMonkey/ngx-quill#370]
Hello, I have used ng-quill on an Angularjs project and I was able to modify modules and icons and even add new handlers and buttons.

I'm now on an Angular 7 project, I was wondering how can I modify let's say icons. Do I have to use quilljs for it which is Javascript, or is there a way to modify icons in ngx-quill ?

This is what I wrote in a component called `WriteComponent` and I'm not sure if It's the correct way.

```ts
import { Component, OnInit } from '@angular/core';
const Quill = require('quill');

const icons = Quill.import('ui/icons');


@Component({
  selector: 'app-write',
  templateUrl: './write.component.html',
  styleUrls: ['./write.component.scss'],
})
export class WriteComponent implements OnInit {

  constructor() {
    icons['bold'] = '<ion-icon name="add"></ion-icon>';
  }

  ngOnInit() {
  }

}

```

I need `Quill` to add new handlers, modules, icons and registering them and so on.
This code works just fine, but I'm still not sure if I should do such code in Angular 7.

**Comment by KillerCodeMonkey** [comment]
eehm i do not know how you have did this with ng-quill. But in generel you should create a quilljs theme:

https://quilljs.com/docs/themes/#themes
or override the existing style with css or build a custom toolbar:

```
<quill-editor>
  <div quill-editor-toolbar>
    <span class="ql-formats">
      <button class="ql-bold" [title]="'Bold'"></button>
    </span>
    <span class="ql-formats">
      <select class="ql-align" [title]="'Aligment'">
        <option selected></option>
        <option value="center"></option>
        <option value="right"></option>
        <option value="justify"></option>
      </select>
      <select class="ql-align" [title]="'Aligment2'">
        <option selected></option>
        <option value="center"></option>
        <option value="right"></option>
        <option value="justify"></option>
      </select>
    </span>
  </div>
</quill-editor>
```

**Comment by ArsalanSavand** [comment]
I can override the existing styles or build a custom toolbar. The problem is if I add an icon inside a `button` element, it will be override by quill.

My question is not custom toolbar. I just want to know how can I for example import something from Quill in Angular 7.

This is how I did it in Angularjs:

```js
import Quill from "quill";

const BlockEmbed = Quill.import("blots/block/embed");
const Clipboard = Quill.import("modules/clipboard");
const icons = Quill.import("ui/icons");
```

**Comment by KillerCodeMonkey** [comment]
This should work the same with angular >2

Install the the quill typings and go an. in my demo repo i am using Quill.import to change fonts or change the default block element.

I never changed icons, but if this worked before i see no problem, why this should not work.

**Comment by ArsalanSavand** [comment]
Alright got it. Thanks for the quick response 👍

**Comment by srinivasthutika** [comment]
Arsalan,
do you have your working version of angular7 project where you changed icon.

**Comment by srinivasthutika** [comment]
Can you give working example on importing quill icons. I am looking to import table icons from assets.
This is how i am doing
 private getInsertTableButton() {
    const myButton = new QuillToolbarButton({
      **icon: 'TI'**
    });
    const table = this.table;
    myButton.onClick = function(quill) {
      table.insertTable(2, 2);
    };
    myButton.attach(this.quill);
  }

I am using text now. How can i add icon for the same. I can see table SVG icon in quill/assets/icons

**Comment by ArsalanSavand** [comment]
@srinivasthutika What icons are you using? FontAwesome?

**Comment by KillerCodeMonkey** [comment]
@ArsalanSavand why reopening this issue?

**Comment by ArsalanSavand** [comment]
@KillerCodeMonkey Sorry my bad, I will just commend. I will close it now.

**Comment by KillerCodeMonkey** [comment]
in general this is done like for plain quilljs.
So just search the issues in the quilljs repo.
https://github.com/quilljs/quill/issues/1099#issuecomment-258560326

**Comment by karlosmrez** [comment]
How can i overwrite the dropdown icon? This icon is not into icons.js.

**Comment by KillerCodeMonkey** [comment]
I do Not know what icon.js is. But in general overwrite The theme css and
use your own Icons / Icon Font.

Or Just build your own quilljs theme.

Or create a custom toolbar.

Modules configuration can be Passed via Input property or in the
quillmodules config.

If you want to Change The behavior of an existing module you Need to
implement your own Module.

In general your question is regarding quilljs. So Just ASK your question
there.

There is a Guide how to create custom modules and how to customize Formats.

Karlos Mrez <notifications@github.com> schrieb am Fr., 27. März 2020, 12:51:

**Comment by tihansen** [comment]
The current workaround is to remove the `Quill.import('ui/icons')`-part and call it in the root-project that imports all libraries. This isn't optimal since we wanted to hide this code, but it works and gets rid of the error.

I was able to make the code short by keeping the logic in the library. My application now has this code:

`app.component.ts`
```typescript
import {LibraryComponent} from '@some-org/some-lib';

ngOnInit() {
  // Initialize quill
  const icons: StringMap = Quill.import('ui/icons');
  LibraryComponent.initEditor(icons);
...
}
```

And in the library I have the following function:

`some-component.component.ts`
```typescript
  public static initEditor(icons: StringMap): void {
    icons.bold = '<i class="icon icon-bold" aria-hidden="true"></i>';
    icons.italic = '<i class="icon icon-italic" aria-hidden="true"></i>';
...
}
```
