### ISSUE TITLE
Quill mention

### ISSUE THREAD

**Issue by shivmourya98** [KillerCodeMonkey/ngx-quill#374]
I am using Angular 5 with 
"ngx-quill": "^4.8.0",
 "npm": "^5.8.0",
 "quill": "^1.3.6",
 "quill-mention": "^2.1.1"

but unable to run project in IE11.
Even demo available on Git is also not working.
NOTE - I have installed all the files from polyfills.ts

**Comment by KillerCodeMonkey** [comment]
Does IT work without quill mention? If so please Open an issue there

shivmourya98 <notifications@github.com> schrieb am Fr., 26. Apr. 2019,
14:02:

**Comment by KillerCodeMonkey** [comment]
Checkout this:
https://github.com/KillerCodeMonkey/ngx-quill/issues/241

And this - seems there is a missing polyfill:
https://github.com/afconsult/quill-mention/pull/47
