### ISSUE TITLE
Error with chrome 74

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [KillerCodeMonkey/ngx-quill#375]
After upgrading to chrome 74, I get the following error on all usages of ngx-quill:

"TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Index property setter is not supported"

This seems to be somehow because I set styles on the quill editor.
If I adapt to:
    <quill-editor [readOnly]="'true'" [(ngModel)]="text" [modules]="{toolbar: false}"
                  [style.flex-grow]="1" [style.padding-top]="'5px'" [style.background-color]="'rgba(0, 0, 0, .1)'" [style.max-height]="'385px'" [style.overflow-y]="'auto'"
                  [placeholder]="'No chat...'">
    </quill-editor>

so wrap each style property I want to set into angular, then it works again.

**Comment by KillerCodeMonkey** [comment]
should be fixed in 5.0.0. renamed the input property "style" in "styles". It collides with the native style property.
