### ISSUE TITLE
issue in adding 2 new custom toolbar style icon

### ISSUE THREAD

**Issue by preetha-kesavan** [KillerCodeMonkey/ngx-quill#376]
Hi, 

I have used the following code to add two new custom button in the toolbar.
```
let Inline = Quill.import('blots/inline');

class SpanBlock extends Inline {
  static blotName: string;    
  static tagName: string;
    static create(value){
        let node = super.create(value);
        node.setAttribute('class','spanblock');
        return node;    
    } 
}
SpanBlock.blotName = 'spanblock';
SpanBlock.tagName = 'div';
Quill.register(SpanBlock);

class SpanBlockRed extends Inline {    
  static blotName: string;    
  static tagName: string;
  static create(value){
      let node = super.create(value);
      node.setAttribute('class','spanblock-red');
      return node;    
  }
}
SpanBlockRed.blotName = 'spanblock-red';
SpanBlockRed.tagName = 'div';
Quill.register(SpanBlockRed);
```
And I have the following styles associated with it as below
```
.spanblock {
  border: 1px solid #000;
  padding: 6px 10px;
  border-radius: 3px;
  margin: 15px 0;
}

.spanblock-red {
    border: 1px solid #cc0000;
    padding: 6px 10px;
    border-radius: 3px;
    margin: 15px 0;
}
```
Everything works fine, clicking one button adds a black border box and clicking another adds a red border box. I store it in the database successfully and while reading back it loads the html string back into the quill editor. While doing so, the editor seems to change the style always to the latest registered button. For eg, in this case it chooses SpanBlockRed and I see only red box in the editor. If I save it back as it is, it saves correctly but only while viewing it back is shows the wrong class. Am I doing anything wrong in here?

![image](https://user-images.githubusercontent.com/38659830/56900124-021e8b80-6a8d-11e9-9dc9-9fa34ace2fb3.png)

whereas the actual html content is like below
`<h1><strong class="ql-font-monospace" style="color: rgb(230, 0, 0);"><em>1</em></strong></h1><h1><strong class="ql-font-monospace" style="color: rgb(102, 185, 102);"><em><div class="spanblock-red">22 </div></em></strong></h1><h1><strong class="ql-font-monospace" style="color: rgb(0, 102, 204);"><em><div class="spanblock">333</div></em></strong></h1><h1><br></h1>`

Please let me know how to fix this.

**Comment by KillerCodeMonkey** [comment]
please just ask this at the quilljs repository.
i am no a quill expert :)

**Comment by KillerCodeMonkey** [comment]
@preetha-kesavan i created a codepen with native quilljs.

https://codepen.io/anon/pen/xeeqRP?editors=1010

i register you formats and after editor initialisation i call `quill.clipboard.dangerouslyPasteHTML()` with some default content, setting a red and black block - it results in two red boxes.

So please create an issue in the quilljs/quill repo here on github :)

**Comment by preetha-kesavan** [comment]
Thanks, I will ask the quilljs team
