### ISSUE TITLE
ngModel can not detect when using insertEmbed

### ISSUE THREAD

**Issue by chuJianNi** [KillerCodeMonkey/ngx-quill#377]
I am trying insert image like this:
`this.editor.insertEmbed(index, 'image', img);`

it works. But ngModel can not detect this change unless input something in the editor manually after that. 

how to fix it. Thanks a lot!

**Comment by KillerCodeMonkey** [comment]
You have to Pass the source 'user' As source of the Change. Per Definition
of ngmodel and Formcontrol IT only handles real User Interactions and not
programmatically Changes.

There is also an Input Option to Track all Changes from any quill source ;)

chuJianNi <notifications@github.com> schrieb am Di., 30. Apr. 2019, 06:01:

**Comment by chuJianNi** [comment]
how to do that...

**Comment by KillerCodeMonkey** [comment]
just take a look in the quill api:
https://quilljs.com/docs/api/#insertembed

the last parameter is the source string ->  defaults to api ;).

And just pass a fourth parameter with the string 'user'
