### ISSUE TITLE
Is there a reason QuillConfig doesn't have 'format' ?

### ISSUE THREAD

**Issue by JoshuaNitschke** [KillerCodeMonkey/ngx-quill#378]
Hi,

I am following your recommendation and not storing the HTML in the database.  I am having a hard time deciding between json and object and would appreciate your thoughts if you have any on that, I saw another user specifically was wanting the JSON functionality so i have decided to go that route for now, but it seems it will take up a lot more space with the escaped quotes.

However, I am surprised that when setting up defaults using the forRoot() method described in the readme, there isn't an option to set the default 'format' .  Is this deliberate?  I am currently setting it on each implementation, but I would like to just set a global default and forget about it, especially as if I forget it will bite me badly later as I'll have to convert database records from HTML to Delta....

```
export interface QuillConfig {
  bounds?: HTMLElement | string
  debug?: 'error' | 'warn' | 'log' | false
  //format: ?  <--------------------------------------- no format here
  formats?: any
  modules?: QuillModules
  placeholder?: string
  readOnly?: boolean
  scrollingContainer?: HTMLElement | string | null
  theme?: string
  // Custom Config to track all changes or only changes by 'user'
  trackChanges?: 'user' | 'all'
}
```

**Comment by KillerCodeMonkey** [comment]
there is no global config for the format, yet. :)

I will add it, when i have the time

**Comment by KillerCodeMonkey** [comment]
should be working with release. 5.1.0

**Comment by JoshuaNitschke** [comment]
Thanks, this is working great for me now.
