### ISSUE TITLE
Default font size.

### ISSUE THREAD

**Issue by Kamczii** [KillerCodeMonkey/ngx-quill#379]
Is it possible to set default font size?
Because im using quill component to display data (readonly, without toolbar) and i think the text there is a little bit small.

`<quill-editor [styles]="{border: 'none', fontsize: '120%'}" [readOnly]="true" [modules]="displayConfig" [(ngModel)]="post.content">
`
This consctruction isnt working.

**Comment by KillerCodeMonkey** [comment]
try using the correct css attribute: 'font-size'

```JS
{ border: 'none', 'font-size': '120%' }
```

But you should check, if quilljs is overwriting this.

**Comment by KillerCodeMonkey** [comment]
tested it. It is working with the correct css-attribute :) --> closed
