### ISSUE TITLE
Bubble theme is not working with custom toolbar

### ISSUE THREAD

**Issue by SruthyJohn** [KillerCodeMonkey/ngx-quill#380]
Hello,
I have created a customised the toolbar to insert "WorkflowTypes" to the content from a dropdown. And it works perfectly with the default "snow" theme. But no success with bubble theme. Issue is bubble.css is not loading.

**Comment by KillerCodeMonkey** [comment]
how do you load the bubble theme?

**Comment by SruthyJohn** [comment]
` <quill-editor theme="bubble"
[modules]=options
(onEditorCreated)="onEditorCreated($event)"
(onContentChanged)="onQuillContentChanged($event,i,j,'approve')">
</quill-editor>`

**Comment by KillerCodeMonkey** [comment]
but you have to load the css on your own somewhere in your project global css as import as something like that.

in my demo repo you find them here:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/angular.json#L25

there is also a bubble editor example ;) 
https://killercodemonkey.github.io/ngx-quill-example/

checkout the "bubble editor"

**Comment by SruthyJohn** [comment]
![image](https://user-images.githubusercontent.com/11191927/57227552-539bbd00-702f-11e9-850b-38ac84d2f4a4.png)

Theme css are added in angular.json
`"styles": [
              "src/custom-theme.scss",
              "src/styles.css",
              "src/assets/css/material-modified.css",
              "node_modules/@swimlane/ngx-datatable/release/themes/material.css",
              "node_modules/quill/dist/quill.core.css",
              "node_modules/quill/dist/quill.bubble.css"
            ],`

**Comment by SruthyJohn** [comment]
> but you have to load the css on your own somewhere in your project global css as import as something like that.
> 
> in my demo repo you find them here:
> https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/angular.json#L25
> 
> there is also a bubble editor example ;)
> https://killercodemonkey.github.io/ngx-quill-example/
> 
> checkout the "bubble editor"

I have checked the bubble editor sample you did it works fine. The issue is only when we customise the toolbar.

**Comment by KillerCodeMonkey** [comment]
can you share your modules config?

**Comment by KillerCodeMonkey** [comment]
when i customize the toolbar with existing formats there is no error. even in my example so maybe you are using custom modules?
