### ISSUE TITLE
Problem using ngx-quill with ViewEncapsulation.ShadowDom

### ISSUE THREAD

**Issue by cmyksvoll** [KillerCodeMonkey/ngx-quill#381]
I am trying to use ngx-quill in a custom component (created using Angular Elements). The purpose is to create Angular based plugins to be hosted in another Angular application. To ensure that styles in my Angular Elements component will not affect the hosting application, I have set encapsulation to ViewEncapsulation.ShadowDom in my component (default is ViewEncapsulation.Emulated):
```
@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss'],
  encapsulation: ViewEncapsulation.ShadowDom
})
```
To make this work, I also import the quill css files in my test.component.scss instead of adding them to angular.json:
```
@import "~quill/dist/quill.core.css";
@import "~quill/dist/quill.bubble.css";
@import "~quill/dist/quill.snow.css";
```
My problem is that ViewEncapsulation.ShadowDom changes the behavior of the quill editor, especially for numbered lists and bullet lists. It is also not possible to use the tab key to change indent level for list items.

![quill](https://user-images.githubusercontent.com/7809052/57357055-49360c00-7172-11e9-9cdf-677f07272796.gif)

If I change the encapsulation back to ViewEncapsulation.Emulated, the editor works perfectly fine. But... then I risk leaking styles into the application that will host my custom component.

**Comment by KillerCodeMonkey** [comment]
If you use the default emulated encapsulation there should be nothing leaking in the host component.
Because each component and styling gets encapsulated by a custom data attribute.

**Comment by KillerCodeMonkey** [comment]
@cmyksvoll Seems like quilljs does not support shadow dom in the current stable version:

https://github.com/quilljs/quill/issues/2021
https://github.com/quilljs/quill/pull/2337
https://github.com/quilljs/quill/pull/1805
