### ISSUE TITLE
model format attribute on quill-editor component returns undefined

### ISSUE THREAD

**Issue by swapnilp0x00** [KillerCodeMonkey/ngx-quill#382]
I am operating editor in two different modes `HTML` and `text`.
At one point I need to check the currently active format of my editor.

I have defined source small editor like this
`<quill-editor [format]="format" #quillEditor>....</quill-editor>`

```(click)="openModal($event, quillEditor)">```

In openModal(), I need to know the current format of my quillEditor Component.

quillEditor.format returns undefined.
quillEditor.getFormat returns {}

**Comment by KillerCodeMonkey** [comment]
works fine for me, but keep in mind that the initial props of the "ViewChild" is set after the `ngAfterViewInit` lifecycle hook. there i get "text" or "html"

**Comment by KillerCodeMonkey** [comment]
any update?

**Comment by swapnilp0x00** [comment]
Yes it worked.  In my case i was passing a component that was not in dom because of ngIf on it.
Thanks for this excellent component.

**Comment by KillerCodeMonkey** [comment]
Glad You got it working :)

SwapnilP <notifications@github.com> schrieb am So., 12. Mai 2019, 06:36:
