### ISSUE TITLE
Not all styles get applied on element. 

### ISSUE THREAD

**Issue by cray2015** [KillerCodeMonkey/ngx-quill#383]
Hi the below HTML string was created. But many properties get stripped away. Also if we apply a class on this element then it strips the whole class from the element. 

`mc <span contenteditable="false" style="box-sizing: border-box;padding: 0 7px; font-variant: tabular-nums; list-style: none; -webkit-font-feature-settings: 'tnum'; font-feature-settings: 'tnum'; display: inline-block; height: 22px; font-size: 12px; line-height: 20px; white-space: nowrap; background: #fafafa; border: 1px solid #d9d9d9; border-radius: 4px; opacity: 1; transition: all .3s cubic-bezier(.215,.61,.355,1); color: #13c2c2; background: #e6fffb; border-color: #87e8de; width: 200px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" class="piped-question-tag">how do you like the things in your life?</span>`

when the element render the below HTML is generated.
`<p>mc <span style="color: rgb(19, 194, 194); background-color: rgb(230, 255, 251);">how do you like the things in your life?</span></p>`

I'm using the editor in bubble mode and the sanitize property is set to 'false' too. I dont know if we have done anything wrong here or it is the intended behavior?

**Comment by KillerCodeMonkey** [comment]
quill transforms the content in a form (also the attributes and formats) it knows. So all this props and a span-tagged  with contenteditable-attribute is not a content produced by quilljs ;).

**Comment by KillerCodeMonkey** [comment]
See here:
https://codepen.io/anon/pen/EzPNXr?=true

even native quilljs does it :)
