### ISSUE TITLE
Get Quill editor instance from child component?

### ISSUE THREAD

**Issue by mindpixel-labs** [KillerCodeMonkey/ngx-quill#384]
Hi, thanks for the great component!

I am creating a custom toolbar and everything has been going well so far. The only issue I am running into with the following setup is how to access the Quill editor instance to access its API via a `<child app-editor-toolbar>` component?

**Here is my following structure:**

```html
<quill-editor (onEditorCreated)="editorCreated($event)" theme="snow">
  <app-editor-toolbar quill-editor-toolbar></app-editor-toolbar>
</quill-editor>
```

I understand on the parent I can set it via the **onEditorCreated** Output but I can't gain access to that via the child component. 

What is the recommended approach for accessing the Quill API/editor instance to run history/formatting methods for a custom toolbar in this case when wrapping it inside another component?

**Comment by KillerCodeMonkey** [comment]
I do not know. I never Had this Type of defining a toolbar in my mind :).

I would try to add your toolbar component an Input for the Editor instance
and Pass the Editor instance you get in the oneditorcreated Hook.

So there is no implicit Magic happening. And in your toolbar Format Button
click listeners You can Access the Editor property and use IT.

Mind Pixel <notifications@github.com> schrieb am Fr., 10. Mai 2019, 20:09:

**Comment by KillerCodeMonkey** [comment]
@mindpixel-labs i tested it it is working like i described, but you need to workround the error in dev-mode, that the editor input has changed after view detection on intial load. But it is working.

Another approach would be not to nest the toolbar with `quill-editor-toolbar`.
Keep in mind you can pass [modules]="{toolbar: 'CSSSelector'}" to say quill, that the toolbar node is somewhere else ;)

**Comment by mindpixel-labs** [comment]
@KillerCodeMonkey That did the trick. Thank you so much for your help and a great library!

**Comment by KillerCodeMonkey** [comment]
no probs ;)
