### ISSUE TITLE
Not able to render Image in quill editor

### ISSUE THREAD

**Issue by gags88** [KillerCodeMonkey/ngx-quill#385]
Hi,
I am trying to save data which has an image uploaded. When try to fetch data from server and displaying in quill editor again, does not seem to work.
Data template is:
`<p>test 2 test</p><p>&nbsp;<img src=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD//gA8Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBxdWFsaXR5ID0gMTAwCv/bAEMAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAf/bAEMBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAf/AABEIBwgLQAMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AP5Q/ue+fw6fn60Z/wCmf6f/AFqD/wAs/wAP6UD/AJafj/WgCSo0HQeX68Y/+v8AyPvQPL/c+v4+/wCP9PxqVOv7v8PXr79+n9KAIv08j+n+ffr7VJRRQAuTv8z8P8n1/wD10lFR/wDLP/t4/wDZqAJKKj/5af5/u0H/AJZ/h/SgCSiox/y0/H+tH/LT/P8AdoAkoqP/AJZ/9vH/ALNUlABUfm/9M/1/+yo/d/53Ufu/87qAJKj83/pn+v8A9lRj/pp+v/16P3f+d1AElFR4/wCmn6//AF6P3f8AndQAeb/0z/X/AOyqSo/3f+d1GP8App+v/wBegA83/pn+v/2VSVH+7/zuox/00/X/AOvQBJUfm/8ATP8AX/7Kj93/AJ3Ufu/87qAJKKjx/wBNP1/+vSn7831/9lFAD6KjP/LP8P6UD/lp+P8AWgCSio/+Wn+f7tSUAFFMP35vr/7KKQ/8s/w/pQBJRUY/5afj/Wj/AJaf5/u0ASUUUw/fm+v/ALKKAH0VGf8Aln+H9KB/y0/H+tAElFR/8tP8/wB2pKACimH7831/9lFIf+Wf4f0oAkoqMf8ALT8f60f8tP8AP92gCSiimH7831/9lFAD6KjP/LP8P6UD/lp+P9aAJKKj/wCWn+f7tSUAFFMP35vr/wCyin0AFFFFABRRUf8A38oAkooooAKKKKACio/+/lSUAFFFFABRRUf/AH8oAkooooAKKKKACio/+/lSUAFFFFABRRUf/fygCSiiigAooooAKKj/AO/lSUAFFFFABRRUf/fygCSiiigAooooAKKj/wC/lSUAFFFFABRRUf8A38oAkooooAKKKKACio/+/lSUAFFFFABUf/fypKKAI/8Alp/n+7QP+WP+t/p3/X+lSUUARD7kv+t69/8APT09qX/43UlFAEf/AH8o/wCWn+f7tSUUARj/AJY/63+nf9f6Ug+5L/revf8Az09PapaKAI//AI3R/wB/KkooAj/5af5/u0D/AJY/63+nf9f6VJRQBEPuS/63r3/z09Pal/8AjdSUUAR/9/KP+Wn+f7tSUUARj/lj/rf6d/1/pSD7kv8Arevf/PT09qlooAj/APjdH/fypKKAI/8Alp/n+7QP+WP+t/p3/X+lSUUARD7kv+t69/8APT09qX/43UlFAEf/AH8o/wCWn+f7tSUUARj/AJY/63+nf9f6Ug+5L/revf8Az09PapaKAI//AI3R/wB/KkooAj/5af5/u0D/AJY/63+nf9f6VJRQBEPuS/63r3/z09Pal/8AjdSUUAR/9/KP+Wn+f7tSUUARj/lj/rf6d/1/pSD7kv8Arevf/PT09qlooAj/APjdH/fypKKAI/8Alp/n+7QP+WP+t/p3/X+lSUUARD7kv+t69/8APT09qX/43UlFAEf/AH8o/wCWn+f7tSUUARj/AJY/63+nf9f6Ug+5L/revf8Az09PapaKAI//AI3R/wB/KkooAj/5af5/u0D/AJY/63+nf9f6VJRQBEPuS/63r3/z09Pal/8AjdSUUAR/9/KP+Wn+f7tSUUARj/lj/rf6d/1/pSD7kv8Arevf/PT09qlooAj/APjdH/fypKKAI/8Alp/n+7QP+WP+t/p3/X+lSUUARD7kv+t69/8APT09qX/43UlFAEf/AH8o/wCWn+f7tSUUARj/AJY/63+nf9f6Ug+5L/revf8Az09PapaKAI//AI3R/wB/KkooAj/5af5/u0D/AJY/63+nf9f6VJRQBEPuS/63r3/z09Pal/8AjdSUUAR/9/KP+Wn+f7tSUUARj/lj/rf6d/1/pSD7kv8Arevf/PT09qlooAj/APjdH/fypKKAI/8Alp/n+7QP+WP+t/p3/X+lSUUARD7kv+t69/8APT09qX/43UlFAEf/AH8o/wCWn+f7tSUUARj/AJY/63+nf9f6Ug+5L/revf8Az09PapaKAI//AI3R/wB/KkooAj/5af5/u0D/AJY/63+nf9f6VJRQBEPuS/63r3/z09Pal/8AjdSUUAR/9/KP+Wn+f7tSUUARj/lj/rf6d/1/pSD7kv8Arevf/PT09qlooAj/APjdH/fypKKAI/8Alp/n+7QP+WP+t/p3/X+lSUUARD7kv+t69/8APT09qX/43UlFAEf/AH8of7//AC26f8B6d/f/AOtUlFAEf/fyj/v5UlRn/ln+H9KAEH3Jf9b17/56entS/wDfygf8tPx/rUlAEf8A38o/7+VJRQBH/wB/KQfcl/1vXv8A56entSn/AJZ/h/Sgf8tPx/rQAf8Afyj/AL+VJRQBH/38o/7+VJUZ/wCWf4f0oAQfcl/1vXv/AJ6entS/9/KB/wAtPx/rUlAEf/fyj/v5UlFAEf8A38pB9yX/AFvXv/np6e1Kf+Wf4f0oH/LT8f60AH/fyj/v5UlFAEf/AH8o/wC/lSVGf+Wf4f0oAQfcl/1vXv8A56entS/9/KB/y0/H+tSUAR/9/KP+/lSUUAR/9/KQfcl/1vXv/np6e1Kf+Wf4f0oH/LT8f60AH/fyj/v5UlFAEf8A38o/7+VJUZ/5Z/h/SgBB9yX/AFvXv/np6e1L/wB/KB/y0/H+tSUAR/8Afyj/AL+VJRQBH/38pB9yX/W9e/8Anp6e1Kf+Wf4f0oH/AC0/H+tAB/38o/7+VJRQBH/38o/7+VJUZ/5Z/h/SgBB9yX/W9e/+enp7Uv8A38oH/LT8f61JQBH/AN/KP+/lSUUAR/8AfykH3Jf9b17/AOenp7Up/wCWf4f0oH/LT8f60AH/AH8o/wC/lSUUAR/9/KP+/lSVGf8Aln+H9KAEH3Jf9b17/wCenp7Uv/fygf8ALT8f61JQBH/38o/7+VJRQBH/AN/KQfcl/wBb17/56entSn/ln+H9KB/y0/H+tAB/38o/7+VJRQBH/wB/KP8Av5UlRn/ln+H9KAEH3Jf9b17/AOenp7Uv/fygf8tPx/rUlAEf/fyj/v5UlFAEf/fykH3Jf9b17/56entSn/ln+H9KB/y0/H+tAB/38o/7+VJRQBH/AN/KP+/lSVGf+Wf4f0oAQfcl/wBb17/56entS/8Afygf8tPx/rUlAEf/AH8o/wC/lSUUAR/9/KQfcl/1vXv/AJ6entSn/ln+H9KB/wAtPx/rQAf9/KP+/lSUUAR/9/KP+/lSVGf+Wf4f0oAQfcl/1vXv/np6e1L/AN/KB/y0/H+tSUAR/wDfyj/v5UlFAEf/AH8pB9yX/W9e/wDnp6e1Kf8Aln+H9KB/y0/H+tAB/wB/KP8Av5UlFAEf/fyj/v5UlRn/AJZ/h/SgBB9yX/W9e/8Anp6e1L/38oH/AC0/H+tSUAR/9/KP+/lSUUAR/wDfykH3Jf8AW9e/+enp7Up/5Z/h/Sgf8tPx/rQAf9/KP+/lSUUAR/8Afyj/AL+VJUZ/5Z/h/SgBB9yX/W9e/wDnp6e1L/38oH/LT8f61JQBH/38o/7+VJRQBH/38pB9yX/W9e/+enp7Up/5Z/h/Sgf8tPx/rQAf9/KP+/lSUUAR/wDfyj/v5UlRn/ln+H9KAEH3Jf8AW9e/+enp7Uv/AH8oH/LT8f61JQBH/wB/KP8Av5UlFAEf/fykH3Jf9b17/wCenp7Up/5Z/h/Sgf8ALT8f60AH/fyj/v5UlFAEf/fyj/v5UlRn/ln+H9KAEH3Jf9b17/56entS/wDfygf8tPx/rUlAEf8A38o/7+VJRQBH/wB/KQfcl/1vXv8A56entSn/AJZ/h/Sgf8tPx/rQAf8Afyj/AL+VJRQBH/38o/7+VJUZ/wCWf4f0oAQfcl/1vXv/AJ6entS/9/KB/wAtPx/rUlAEf/fyj/v5UlFAEf8A38pB9yX/AFvXv/np6e1Kf+Wf4f0oH/LT8f60AH/fyj/v5UlFAEf/AH8o/wC/lSVGf+Wf4f0oAQfcl/1vXv8A56entS/9/KB/y0/H+tSUAR/9/KP+/lSUUAOT7w/H+RptR/8Afugf8tPx/rQAf9+iCP8AwJ/z/nAFHT3z/wCSv+ce3TtijH+z/wCTNS/6v0AA9zwT/>`

I am using reactive form and patching the data via formControl in standard way.
Can you please look into it?

**Comment by KillerCodeMonkey** [comment]
do you have inspected the editor content after patching?

what it results to?

**Comment by KillerCodeMonkey** [comment]
just take my example repo and change the "reactiveForm" example.
THere is a patchValue button.

I set the content with a valid html + base64image (this is the output of quilljs image handling):

```html
<div><img src=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD//gA7Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2NjIpLCBxdWFsaXR5ID0gNzAK/9sAQwAKBwcIBwYKCAgICwoKCw4YEA4NDQ4dFRYRGCMfJSQiHyIhJis3LyYpNCkhIjBBMTQ5Oz4+PiUuRElDPEg3PT47/9sAQwEKCwsODQ4cEBAcOygiKDs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7/8AAEQgAZABkAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A9W8w0nmGot9Jvryec7OUlaXYpZ2CqoySTwBVSy1jT9SLrY6hbXRT7whmV9v1wa4r4v3d7B4NC2jOqzXKJMUODtwxx+JArw/Tbqey1GC4tp5LeVJARJG20rz61vTpc8ea5nKXK7WPrDcaTcfWoFlDorK2QRkEHOaC9c3MbcpPvPrSFzUG+k31POPkJ91Jv96gL0m+lzj5CxvppeoPMpDJU+0K5CfzBRVbzKKXtB8hx8XxU0oqTNZXS467NrfzIqeD4peGJgS89xCB3eAn/wBBzVif4e+HJgQLSSLP9yZv6k1zWv8Awu0TTtEvtQtru9VrW3kmVGdWBKqSB93Pb1rpj7J6O5nLmWpmfEb4i2eq2L6LpUYuIJQGkuHQjnII2g89jnIrzGI7ZFcpvCsCVPQ+1OadmbPIHoDQCPNVZCQu75sc4HevRpwUFZHJKXM7n0v4f1q013Rre+s/lR1AaPvG2OVP0rRLVx3gjwfc+F7i8lfVBd21wF8lFUgY6hj74PauvzXi1LKT5Xod8L21FzSZpKSsrl2FzSE0hJpOaVyrC5ppNFJSHYM0UlFIot4NV76yi1CwuLKcExXETRPtODtYYOPzq5to2102sc1z5s8W6Pb+HtduLC3RyIXKhnOeD8y/jtI/HNYFdJ8Q75NQ8dapLGAFSXyuBjJQBSfzBrmwCTgda9qF+VXOCW+h9M+GnafwtpMzcl7KFj9SgrT21R8NWUmn+GdNs5mDSQ2saMVORkKOh7itPFeNOK5md0ZaIi2UmypcUYqOUrmItlJsqbFJilyj5iBgFGTUDzBYg3948Ul9cCOJn5Ozh1HUD1rmbrW3t2itpFy0rjy2PTb61FrvQ0TstTq1wR60Vy174eTU7k3b6rdwFwP3cZG0YGOKKajHqyW5di7p3xI8O3xVGvVikZ9oDgitiPxJoszFU1GAkNtxvHWvmKGRkkDDtWvDeb13EhSPevSlhrbM5I1E+hf8a6DP4b8XzGX57W6kaaGXqGRjyPqM4/XvXO38RivJPRjuGPf/ADitnVNYuL7TorO5nM0cTF49/JUkYIB9Ky7757W1l77Sp/D/AB5rrpt2VzGSSvY7PwR8UbvQRFp2rBrrTlAVGA/eQDtj1Ht+XpXri+LdCkt0uI9SgeKRdysHHSvmKnK7KMBiB6VnVw6nqtBwqcu59T2Wq2GoxtJaXMcqr1IPSnS6hbxTxQ7wzynACnOPrXzLYareWeVimkRG+8FYjNaqazIsizLdSK69G3HIrmlh5LqbxqRZ9FLcQSPsSVGb0Bp+K+eLTxHc2N0Lm3u5FlBznk5r0C3+LVi2nIsqOl2AAxKEqfU1lKlNdLlKUWdvqOnm5HmRNskA69j9a5HXLZkuNNMkYJ8wpuwcbiOOK0j8SvDKQgteszY5Cwt/hWRqPxA8L3CIqyzSFZVcFYmGMGseSd7pM1UlazZ09tCvkKH3sw4JAxRXG3fxS02KcpZ6dNcRAf6xvlJP0oqfq9V9Cvaw7njwY+35VKjEjk8VEqknmpOAOK91nmolX97L5aDljgUl80asLeJcBD8xPUmnlzZw8HE7+nVR/n+ftVWKMuC+fun86S01Bu+g5olEajGG7moSMEirZjBTHeq0ow5HpTTFJWHKTjrVkkDk81XRAUBzyf8AGpGAHBakylsPkfEpIPYfypEuGV9x+bNIY/MlULk5UdKsLabf4TUtpD1Hq3mKD046UibQCAO5qVEZRjZxTre3G9izAYfpUXRdiOOKRgSASM0VoxuFXCbQM96KjmZVjDgtJfPAlhfHcEEdqvCFreMNblElkQhlUksgPpnH6Go/PmdVwxJz0PNOjkmRSxcBAf8AP8q0bZmkjMFtIXI29P1qylpOEIKhQcYyQM1YwG4MoU9QevbpSFo2IMsu7cMHt0puTYlFIjjsbiXkFQP973qGexnWYgr04JPriru+ANwwVfWpHni3IGKMq/jxS55DcUyjHYTGAOwVVA4yQO9P/s2UjdkEY65qy0sRjcAkKTwD1qM3EauAFYbCT70c0mFkPgtvJbzTIuAuMdzVv9zkqzuTjqBwM9KptcRsQcMceppUuyCu0HcOM4B6/wBeahpspNIedw6yAHpjbznvTgsSAneTk54HX6VHHd+XuKgAlcc9frmmea7g4k28fmM/5/KizC5OHhx83mA+yZoqoQ2T8+R2JAop8oXFaFY3KKThQxH4H/61U5WwduBjP50UVojN7EsUrybtx/h7U9idi/MTx0P50UUDHxLvdUJwGbBxQiAqSSeHxRRUjGy4QbVUY/Gk43D5RRRSWwxJG2sAMdKB90+2KKKoQZypPGfpTC7bsZ4JoopgSBiMj3ooopDP/9k=\"></div>
```

and it is working
