### ISSUE TITLE
how do I remove an editor that I created programmatically?

### ISSUE THREAD

**Issue by grimace** [KillerCodeMonkey/ngx-quill#387]
I start an editor like this:
```
    this.editor = new Quill('#editarea', {
        modules: {
          toolbar: [
            [{ header: [1, 2, false] }],
            ['bold', 'italic', 'underline'],
            ['image', 'code-block']
          ]
        },
        placeholder: 'Enter Text Here...',
        theme: 'snow'  // or 'bubble'
      });

```
when I'm done, I'd like to remove the editor.  I can't seem to find a way to do that.

**Comment by KillerCodeMonkey** [comment]
You should also this in the correct Repo. This ist ngx-quill. An angular
wrapper.

If You are using plain quilljs ASK there.

For ngx-quill IT IS enough remove the component from the Dom.

I would Check If the quill object has a remove/deleted/destroy Method.




Gregory Mace <notifications@github.com> schrieb am Sa., 18. Mai 2019, 19:57:

**Comment by KillerCodeMonkey** [comment]
check this:
https://quilljs.com/guides/upgrading-to-1-0/#api

the destroy method was removed in version 1. so it is enough to set your variable to undefined and remove the eventlisteners and the garabage collector should do the rest.

**Comment by grimace** [comment]
I tried that, at least setting the angular editor to undefined does not appear to do anything.

**Comment by KillerCodeMonkey** [comment]
Show me some Code. And the other question is, what did You expect to happen

Gregory Mace <notifications@github.com> schrieb am So., 19. Mai 2019, 16:18:

**Comment by grimace** [comment]
It wasn't quite what I expected to happen, but what I wanted was the ability to toggle editing on and off, which IMHO, seems like a basic functionality.

This codepen in pure javascript/css/html, demonstrates how to achieve what I was looking for:

https://codepen.io/Joeao/pen/BdOGKV

I was able to make this technique work with ngx-quill.   This basically involves setting the editor to disabled
```this.editor.enable(false);```

and hiding  the ```ql_``` elements with this css:

```
.inactive .ql-editor {
  padding:0;
  line-height:inherit;
}

.inactive .ql-editor p {
  padding:inherit;
  margin-bottom:10px;
}

.inactive .ql-toolbar {
  display:none;
}

.inactive .ql-container.ql-snow {
  border:none;
  font-family:inherit;
  font-size:inherit;
}
```
but setting the editor to undefined basically had no effect what so ever.

**Comment by KillerCodeMonkey** [comment]
First If You are using angular Forms or reactiveforms. Just use the ability
of angular.

Set the disabled property of the Input dir template driven driven Forms.

If You are using formcontrols and reactive Forms Just disable IT.

If You do Not want to use the angular way of Forms ngx-quill has a readonly
property ;). Check the readme and the example Repo.

And in Addition to that You can simply can Set the Hidden property to Show
and hide the Editor Element or use ngStyle to Set Display None when You
want to hide the Editor without destroying IT.

Or Like in angular use ngIf to destroy (remove IT) and recreate the quill
component. When needed.

So yes IT IS a Basic functionality of angular and Javascript/CSS to hide or
remove Dom nodes. You only Need to know how to use your Tools ;).

Gregory Mace <notifications@github.com> schrieb am So., 19. Mai 2019, 17:59:

**Comment by KillerCodeMonkey** [comment]
And again: i am not the creater or maintainer of quilljs. I am the creator and maintainer of ngx-quill ;)

your codepen is using the plain javascript quilljs and you should open an issue here:
https://github.com/quilljs/
