### ISSUE TITLE
getComputedStyle error when double clicking outside of editor

### ISSUE THREAD

**Issue by IsaacSomething** [KillerCodeMonkey/ngx-quill#388]
I am getting a very unusual error when clicking, specifically double clicking on a element outside of the quill editor. I am not sure if this has to do with my specific setup. I get the error

> Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

When this happens the toolbar icons are also enlarged. As soon as i click on anywhere in the window it goes back to normal

Im using the latest quill installs and am on angular `7.2.15`

**Comment by KillerCodeMonkey** [comment]
i fixed this in version 5.0.0 for ngx-quill

Keep in mind chrome blocks the direct style attribute manipulation.

Are you getting this error in my demo repo:
https://killercodemonkey.github.io/ngx-quill-example/

This is using plain ngx-quill and there is also an editor setting the background style dynamically on button click.

**Comment by IsaacSomething** [comment]
This is the html
`<quill-editor class="quill-message"></quill-editor>`

And i have setup the quill options in the module

```
QuillModule.forRoot({
      modules: {
        toolbar: [
          ['bold', 'italic', 'underline', 'strike', 'blockquote'],
          [{ 'list': 'ordered' }, { 'list': 'bullet' }],
          [{ 'color': [] }, { 'background': [] }],
        ],
      },
      placeholder: 'Insert Message Here...'
    })
```
I have taken out the the class and removed any custom styles. The error does seem to go away, but the toolbar icons are still being enlarged on double click outside of the editor

![editor](https://user-images.githubusercontent.com/25283027/58082656-b9538180-7bb7-11e9-824b-1625ccb84c6e.gif)

I should mention that this is an ionic 4 project, maybe has something to do with that?

These are the two style imports
```
 {
     "input": "node_modules/quill/dist/quill.core.css"
 },{
     "input": "node_modules/quill/dist/quill.snow.css"
},
```
Im on `"ngx-quill": "^5.1.0",`

**Comment by KillerCodeMonkey** [comment]
Do you use any browser plugins? Like i said. I do not have this behavior in my demo repo in safari, chrome and firefox. ;)

**Comment by IsaacSomething** [comment]
I have the grid ruler extension and push to kindle ... I think there is maybe something wrong with my style setup because if i take out the `"input": "node_modules/quill/dist/quill.snow.css"` then the editor style is very broken. I will try figure it out. Thanks for the quick response.

**Comment by KillerCodeMonkey** [comment]
no props. feel free to head back or paste the solution if you got one :)

**Comment by IsaacSomething** [comment]
There seems to be a transition on the svg icons - I think this might be generated by ionic.
```
element.style {
    transition-duration: 300ms;
    transform: translate3d(0px, 0px, 0px) scale(1);
}
```

I just needed to add
```
.ql-container.ql-snow  svg {
    transform: none !important;
}
```

**Comment by KillerCodeMonkey** [comment]
i have an ionic4 example repo:
https://github.com/KillerCodeMonkey/ngx-quill-ionic-v4

but i cannot see this issue there?

**Comment by IsaacSomething** [comment]
I think i narrowed down the issue. I have the editor in an `ion-slide`. It should be mentioned that the slides are locked `this.slides.lockSwipes(true);`  If i take it out of the slide then there is no issues.

**Comment by KillerCodeMonkey** [comment]
Thank you for the details.
