### ISSUE TITLE
How to update bind data to editor (with custom Blot)

### ISSUE THREAD

**Issue by haotianzhu** [KillerCodeMonkey/ngx-quill#389]
I bind `data.content` to quill-editor, and I create a ImageBlot to insert image.
After I  `quill.insertEmbed` images, the data.content will not be updated until I insert other text.

Initially, I insert `1`, and both HTML and `data.content` change.
Then I insert an image, the `data.content` does not change, while the HTML does change.  
After I type `1` again, both HTML and `data.content` change.

![image](https://user-images.githubusercontent.com/17155218/58143317-a36dad00-7c07-11e9-9e68-adfda62417c1.png)

Here is HTML template:
```
<quill-editor id='contentEditor' 
  [modules]='quillconifg' 
  (onEditorCreated)="editorCreated($event)"
  (onContentChanged)="onContentChanged($event)"
  #content="ngModel"
  required 
  [(ngModel)]="data.content"
  [class.is-invalid]="content.invalid && content.touched"
  placeholder="Please Enter Your Post!">
</quill-editor>
```
I create a new imageBlot
```
export class ImageBlot extends BlockEmbed {
  static blotName: string;
  static tagName: string;
  static className: string;
  static create(value) {
    const imgnode = super.create();
    imgnode.setAttribute('alt', value.alt);
    imgnode.setAttribute('src', value.src);
    return imgnode;
  }
  static value(node) {
    return {
      alt: node.getAttribute('alt'),
      url: node.getAttribute('src')
    };
  }
}
```
add img handler

```
  editorCreated(quill: any) {
    this.quill = quill;
    const toolbar = this.quill.getModule('toolbar');
    toolbar.addHandler('image', this.imageHandler.bind(this));
  }

```

```
  imageHandler() {
    if (this.quill != null) {
      const range = this.quill.getSelection();
      if (range != null) {
        const input = document.createElement('input');
        input.setAttribute('type', 'file');
        input.setAttribute('accept', 'image/*');
        input.addEventListener('change', () => {
          if (input.files != null) {
            const file = input.files[0];
            if (file != null) {
              const reader = new FileReader();
              reader.readAsDataURL(file);
              reader.onerror = (error) => {
                console.log('Error: ', error);
              };
              reader.onloadend = () => {
                // Read complete
                if (reader.readyState === 2) {
                  const base64result = reader.result;
                  this.quill.insertEmbed(range.index, 'bimage', { src: base64result, alt: file.name });
                }
              };
            }
          }
        });
        input.click();
      }
    }
  }
```

**Comment by KillerCodeMonkey** [comment]
Read the readme carefully.

Per Default Definition Updates ngmodel and Formcontrol only and User
changes.

So my component Checks If the Update of the content is done by the quill
source "User".

So You could Set the source of insertEmbed to "User" or Set the config
property to Track all Changes (mentioned in the readme config section)


haotianzhu <notifications@github.com> schrieb am Mi., 22. Mai 2019, 04:43:

**Comment by haotianzhu** [comment]
Oh, I missed the hint.

> Ngx-quill updates the ngModel or formControl for every user change in the editor. Checkout the QuillJS Source parameter of the text-change event.
If you are using the editor reference to directly manipulate the editor content and want to update the model, pass 'user' as the source parameter to the QuillJS api methods.

Thank you!

**Comment by DevLaka** [comment]
@KillerCodeMonkey I am using react-quill and I have a problem with the source parameter. In the [codepen](https://codepen.io/quill/pen/QEPLrv) in the quill docs, the source is used as "Quill.sources.USER", but in the same documentation, it says the source should be "user", "api", etc. Can you tell me what is the correct approach?
I am asking this because I update (set an attribute) to an already inserted blot in the editor. And, it works (It adds the attribute to the blot). But the onChange event is not triggered and the changes are not saved.

**Comment by KillerCodeMonkey** [comment]
Quill.source.User is just a constant that holds The value "user".

So using The variable/constant just would be maybe better If the value may
Change.



DevLaka ***@***.***> schrieb am Fr., 6. Aug. 2021, 13:02:
