### ISSUE TITLE
How to focus the editor?

### ISSUE THREAD

**Issue by luksireiku** [KillerCodeMonkey/ngx-quill#39]
Is there any way to focus the text field with this module? I noticed that Quill has a .focus() method, but I don't know if I can use it or how to do it.

**Comment by KillerCodeMonkey** [comment]
use the `onEditorCreated` output. you get the editor instance as parameter on which you can call 

`editor.focus()`

```
<quill-editor (onEditorCreated)="setFocus(editor)"></quill-editor>

...

setFocus(editor) {
  editor.focus()
}
```

**Comment by luksireiku** [comment]
`TypeError: Cannot read property 'focus' of undefined`
Dunno why

**Comment by KillerCodeMonkey** [comment]
sorry my fault instead of `editor` use `$event` 

```
<quill-editor (onEditorCreated)="setFocus($event)"></quill-editor>
```

**Comment by luksireiku** [comment]
I didn't thought about that, now I feel a bit idiot, anyway thanks 👍

**Comment by yharaskrik** [comment]
I am using Angular 5 with the ngx-quill library and followed the steps above to get the editor to focus, it will focus the textbox for a second and then move the focus to the bold button (first button in toolbar)

`<quill-editor
            *ngIf="dataLoaded"
            [modules]="defaultModules"
            [formats]="formats"
            [theme]="'snow'"
            [(ngModel)]="value"
            [maxLength]="maxLength"
            (onContentChanged)="bodyChanged($event)"
            (onEditorCreated)="setFocus($event)"
    ></quill-editor>`

`setFocus(editor) {
        editor.focus();
    }`

Angular 5
ngx-quill 3.3.0

**Comment by BalazsNagyNET** [comment]
If you are using the quill editor inside an angular material dialog, set the property 'autoFocus' to 'false' on the dialog.

**Comment by Yogeshkad** [comment]
I am facing similar issue in bootstrap4 jQuery  i have multiple editor on screen if i click on editors focus doesn't appearing and user not able to type but when i click on Bold button focus appears  and user able to type. is there any onclick event where i can set focus ?

**Comment by devasagayam** [comment]
@Yogeshkad same issues am facing any solution?

**Comment by Yogeshkad** [comment]
> @Yogeshkad same issues am facing any solution?

Dont remember now how i solved this but editor.focus();  working for me even i have multiple editor on screen. Use editor object instance, check all the script reference on page and the loading sequence.

**Comment by devasagayam** [comment]
ok thanks

**Comment by tyagiggaurav** [comment]
Hello @Yogeshkad  and @devasagayam 
I am also facing the same issue. I get the focus only if I click any button from the toolbar(eg. bold, italic).
I tried to set the focus by calling the editor.focus() method but that also does not work.
Any idea how it could be resolved ?
Thanks.
