### ISSUE TITLE
Ionic - quill-editor.component.ngfactory.ts doesn't exist .js  Field 'browser' doesn't contain a valid alias configuration

### ISSUE THREAD

**Issue by ruchitaT** [KillerCodeMonkey/ngx-quill#391]
Hello,

I got an issue using quill-editor when building ionic app for production. 
Ionic version: v3

commands used for installing ngx-quill:
    npm install ngx-quill@1.6.0 --save
    npm install quill --save

  ionic-app-script task: "build"
 Error: ./src/components/text-editor/text-editor.ngfactory.js Module not found: Error: Can't resolve
            '../../../node_modules/ngx-quill/src/quill-editor.component.ngfactory' in
            'D:\ionic\EditorProject\src\components\text-editor' resolve
            '../../../node_modules/ngx-quill/src/quill-editor.component.ngfactory' in
            'D:\ionic\EditorProject\src\components\text-editor' using description file:
            D:\ionic\EditorProject\package.json (relative path: ./src/components/text-editor) Field 'browser' doesn't
            contain a valid alias configuration after using description file: D:\ionic\EditorProject\package.json
            (relative path: ./src/components/text-editor) using description file:
            D:\ionic\EditorProject\node_modules\ngx-quill\package.json (relative path:
            ./src/quill-editor.component.ngfactory) no extension Field 'browser' doesn't contain a valid alias
            configuration D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory doesn't
            exist .ts Field 'browser' doesn't contain a valid alias configuration
            D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.ts doesn't exist .js
            Field 'browser' doesn't contain a valid alias configuration
            D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.js doesn't exist .json
            Field 'browser' doesn't contain a valid alias configuration
            D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.json doesn't exist as
            directory D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory doesn't
            exist [D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory]
            [D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.ts]
            [D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.js]
            [D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.json]
            [D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory] @
            ./src/components/text-editor/text-editor.ngfactory.js 9:0-91 @
            ./src/pages/actionable-create-job-work/actionable-create-job-work.ngfactory.js @
            ./src/app/app.module.ngfactory.js @ ./src/app/main.ts
Error: ./src/components/text-editor/text-editor.ngfactory.js
Module not found: Error: Can't resolve '../../../node_modules/ngx-quill/src/quill-editor.component.ngfactory' in 'D:\ionic\EditorProject\src\components\text-editor'
resolve '../../../node_modules/ngx-quill/src/quill-editor.component.ngfactory' in 'D:\ionic\EditorProject\src\components\text-editor'
  using description file: D:\ionic\EditorProject\package.json (relative path: ./src/components/text-editor)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\ionic\EditorProject\package.json (relative path: ./src/components/text-editor)
    using description file: D:\ionic\EditorProject\node_modules\ngx-quill\package.json (relative path: ./src/quill-editor.component.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.json doesn't exist
      as directory
        D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory doesn't exist
[D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory]
[D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.ts]
[D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.js]
[D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory.json]
[D:\ionic\EditorProject\node_modules\ngx-quill\src\quill-editor.component.ngfactory]
 @ ./src/components/text-editor/text-editor.ngfactory.js 9:0-91
 @ ./src/pages/actionable-create-job-work/actionable-create-job-work.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at new BuildError (D:\ionic\EditorProject\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (D:\ionic\EditorProject\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (D:\ionic\EditorProject\node_modules\webpack\lib\Compiler.js:265:13)
    at Compiler.emitRecords (D:\ionic\EditorProject\node_modules\webpack\lib\Compiler.js:371:38)
    at emitAssets.err (D:\ionic\EditorProject\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (D:\ionic\EditorProject\node_modules\webpack\lib\Compiler.js:364:12)
    at next (D:\ionic\EditorProject\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\ionic\EditorProject\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (D:\ionic\EditorProject\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (D:\ionic\EditorProject\node_modules\webpack\lib\Compiler.js:361:9)
[ERROR] An error occurred while running subprocess ionic-app-scripts.

**Comment by KillerCodeMonkey** [comment]
please use a newer ngx-quill version <= 1.6.0 is for angular 4 and angular does not support maintain this version and i will not support any further issues for that old version.

checkout my ionic v3 demo repo:
https://github.com/KillerCodeMonkey/ngx-quill-ionic-v3/blob/master/package.json

**Comment by ruchitaT** [comment]
> please use a newer ngx-quill version <= 1.6.0 is for angular 4 and angular does not support maintain this version and i will not support any further issues for that old version.
> 
> checkout my ionic v3 demo repo:
> https://github.com/KillerCodeMonkey/ngx-quill-ionic-v3/blob/master/package.json

Hey, Thank you for the quick response. I have now installed latest version of ngx-quill and its working. Thank you
