### ISSUE TITLE
use ngModel with angular 7 reactive form

### ISSUE THREAD

**Issue by faresayyad** [KillerCodeMonkey/ngx-quill#392]
Hello 
Angular 7
I'm trying to set initial value for edit-form like this: 
in .HTML file:
```
<form [formGroup]="addJobOrderForm" (ngSubmit)="submitContent()" #f>

.
.
.

  <div class="form-group quill-edtr-mrgn">
          <label for="CustComTxt"> Customer complaint
            <div class="input-group mb-2">
              <quill-editor [style]="{height:'250px'}" id="CustComTxt" formControlName="CustComTxt"
                [(ngModel)]="custCompVal">
              </quill-editor>
            </div>
          </label>
        </div>
</form>
```

in .ts File:
```
addJobOrderForm;
custCompVal;
constructor(private fb: FormBuilder, ...)
{
// call my service to retrieve data from server...
let data = result["result"][0];
// Set quill-editor data
this.custCompVal = data.custComTxt;
}
```

when i run the project i got console warring

 

> It looks like you're using ngModel on the same form field as formControlName. 
>     Support for using the ngModel input property and ngModelChange event with 
>     reactive form directives has been deprecated in Angular v6 and will be removed 
>     in Angular v7.
>     
>     For more information on this, see our API docs here:
>     https://angular.io/api/forms/FormControlName#use-with-ngmodel:

**Comment by KillerCodeMonkey** [comment]
yeah and like you can see in the error and the mentioned link there:

You are missing templateDrivenForms and ReactiveForms.
Just remove ngModel if you are using reactive forms.
If you want to use ngModel you should switch to template driven forms

**Comment by faresayyad** [comment]
@KillerCodeMonkey  Yes but i'm using Reactive Forms and you mentioned that you support for angular 7 until 2020? so how can i put data retrieved from server into ngxQuill editor?

**Comment by KillerCodeMonkey** [comment]
Yeah then read the Docs for angular and forms/ reactiveforms IT IS Not
allowed to have ngModel and formControl in the Same Element. If You are
using reactive forms remove the ngModel...

Check my Demo Repo there are examples for that use cases.

faresayyad <notifications@github.com> schrieb am So., 26. Mai 2019, 00:42:
