### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by timothyyjoo** [KillerCodeMonkey/ngx-quill#395]
I'm experiencing this error message : 

```Module not found: Error: Can't resolve 'ngx-quill/src/quill-editor.component' in '/Users/fitrankingsjoo/projects/fitrankings-pro/src/app/shared/components'```

For some reason, its not importing properly from node modules. As per the Read Me instructions, i have installed all dependencies. Any help?

**Comment by KillerCodeMonkey** [comment]
I think You should Not import IT from the "SRC" folder ;). Checkout the
Demo Repo how to import and use the Module and component

Timothy Joo <notifications@github.com> schrieb am Di., 11. Juni 2019, 18:29:

**Comment by timothyyjoo** [comment]
As per your recommendation i've made the change to .
 
```import {QuillEditorComponent} from 'ngx-quill'; ```

which still returns this error : ```ERROR in ./src/app/shared/components/rich-text-editor.component.ts
Module not found: Error: Can't resolve 'ngx-quill' in '/Users/fitrankingsjoo/projects/fitrankings-pro/src/app/shared/components'```
ℹ ｢wdm｣: Failed to compile.
