### ISSUE TITLE
formControl reflect changes but doesn't render patched value

### ISSUE THREAD

**Issue by asifbakht** [KillerCodeMonkey/ngx-quill#396]
I have some issues on my part 
angular version: 5.x

quill version I am using in package.json

   "ngx-quill": "5.2.0",
    "quill": "2.0.0-dev.3",
 
So basically issue is that i have some dynamic quill components that I load using reactive form. Initially value that i want to set on quill does changes in form but it doesn't render changes on quill.
I have some other logics where data should be coming from server on runtime where I have to fetch rendered quill formControl using id and then patch its value. It does update new value on form but doesn't render that new data on quill so user should know whats new data came from server.

This was working in previous quill version "1.3.xxx" but it doesn't work in "2+" . I have to use updated  version that supports formatted excel data on paste.

**Comment by KillerCodeMonkey** [comment]
because i do not support dev versions ;)
