### ISSUE TITLE
Instance of editor passed to onEditorCreated seems to be different than in onContentChanged

### ISSUE THREAD

**Issue by ryanmcfall** [KillerCodeMonkey/ngx-quill#398]
I have an instance of a quill-editor in a template.  I've bound to the `onEditorCreated` event. .  The `onEditorCreated` event handler looks like this:

```
created(event) {
  this.editor = event.editor;
}
```

If I subsequently access the text of the editor in another method, like this:
```
console.log(`Editor text is ${this.editor.getText()}`);
```

I always get an empty string.

But if I change the created event to be the content changed event, everything is as expected.

With both events bound, if I look at the `$event.editor` instance within the `onContentChanged` handler, it's different than the one passed to `onEditorCreated`.

I noticed in #384 that you mentioned something about working around a bug in dev mode that sounds like this issue, but it occurs for me when I run `ng serve --prod` as well.

Any ideas?  Thanks for making this component available!

**Comment by KillerCodeMonkey** [comment]
checkout the readme and the example repo. 

The editor is passed directly for the `onEditorCreated` output, because there is no other data passed.

So `$event = editor` instance.

**Comment by ryanmcfall** [comment]
@KillerCodeMonkey Sorry, that was dumb.  It works as you mentioned.

**Comment by KillerCodeMonkey** [comment]
no probs ;).

I thought about a more "unified api", but then 🤷‍♂️ why, when there is no other data expected on creation.
