### ISSUE TITLE
Placeholder style

### ISSUE THREAD

**Issue by Nabelops** [KillerCodeMonkey/ngx-quill#399]
Not sure how to change the placeholder style. Specifically, I'm trying to change the color for a dark theme.  I've tried through CSS but can't seem to get it to change.  Any advice?

**Comment by KillerCodeMonkey** [comment]
i would guess you have to style it in you global styles. 
Because in an component the viewencapsulation attributes are added.

So just style it in your global css/scss with the selector
``.ql-editor.ql-blank::before`

**Comment by Nabelops** [comment]
That did the trick.  Thanks.

**Comment by HAJNEL** [comment]
That helped thanks! I had to add !important
