### ISSUE TITLE
Alignment not working in preview mode but works in edit mode.

### ISSUE THREAD

**Issue by ErHarinderSingh** [KillerCodeMonkey/ngx-quill#401]
Hello @KillerCodeMonkey  , how are you?

I am here because of an alignment issue.

See, when I set alignment of some text or image in editor it shows there.
![image](https://user-images.githubusercontent.com/22139572/59960200-59b40300-94e2-11e9-854a-1ed9fa0e01ab.png)

but when I bind it in html then it is not aligning, see image below.
![image](https://user-images.githubusercontent.com/22139572/59960206-7d774900-94e2-11e9-9879-a0b1299fd9d3.png)

But is the issue?

**Comment by KillerCodeMonkey** [comment]
did you checked out the section in the readme?

**Comment by ErHarinderSingh** [comment]
Add post :
```
 <quill-editor [modules]="editor_modules" (onContentChanged)="changeHTML($event)"  [(ngModel)]="postData.htmlPostContent" [required]="true">
    </quill-editor>
```
get it in next page and preview as:

```
<ion-content padding>
  <div [innerHTML]="postData.htmlPostContent">
  </div>
</ion-content>
```

**Comment by KillerCodeMonkey** [comment]
yeah then check if the quill css is loaded and the html is not stripped (mark you html as safe with the angular domsanitizer).

**Comment by ErHarinderSingh** [comment]
See: 
![image](https://user-images.githubusercontent.com/22139572/59960411-ac42ee80-94e5-11e9-81b9-d9e2955bfec8.png)

See, it's float style is showing when in edit mode. 
I tried using console.log(e.html)
But post preview still show image at default side.

![image](https://user-images.githubusercontent.com/22139572/59960467-33906200-94e6-11e9-9e3c-45f99396123a.png)

**Comment by ErHarinderSingh** [comment]
Yeah, it is giving a  WARNING: sanitizing HTML stripped some content

**Comment by KillerCodeMonkey** [comment]
yeah, but you should check the resulting html of innerHTML in the dom and the styling.

and of course: if the parent of has a small width you will not notice if the content is float right ;), because the parent container is only as width as the child content.

**Comment by ErHarinderSingh** [comment]
![image](https://user-images.githubusercontent.com/22139572/59960545-53745580-94e7-11e9-8e63-5ea582c863e1.png)

See, quill.snow.css is loading.

I also import quill.core.css but nothing works. still that issue.

**Comment by ErHarinderSingh** [comment]
Bold, italic, font size, image resize everything works fine but only alignment not working of each and everything (images, text, videos etc.)

**Comment by KillerCodeMonkey** [comment]
you also have to load quill.core.css
and like i said, you have to check the with of your parent element. Maybe the aligment stylings have no effect.

And again. you should check the html code to check if the css is working...

**Comment by ErHarinderSingh** [comment]
Styles are loading:
See:
![image](https://user-images.githubusercontent.com/22139572/59960629-a995c880-94e8-11e9-8b51-4b6c12187ed3.png)

And what means by this:-- like i said, you have to check the with of your parent element. Maybe the aligment stylings have no effect.

**Comment by KillerCodeMonkey** [comment]
1. you have inspect the dom and the dom-node if the css is really applied
2. the same goes for the html --> inspect the html in the developer inspector. There you can check how the html looks like. So you can see if all style attributes are set.
3. and also while inspecting the html check out the width of your element (where you set innerHTML). if this element does not have a width set or inherit, it is only as width as the content you created with ngx-quill. This means, that float right has no visual effect if the container is to small.

**Comment by ErHarinderSingh** [comment]
All 3 points are ok.

But see image, styles are striping from html content.
![image](https://user-images.githubusercontent.com/22139572/59961202-4872f280-94f2-11e9-832b-c47661419144.png)

![image](https://user-images.githubusercontent.com/22139572/59961206-60e30d00-94f2-11e9-9faa-4656dec50b05.png)

Tried bypasssecuirty too using domsanitizer but still not working.

**Comment by KillerCodeMonkey** [comment]
Show me some Code how You try to Bypass HTML sanitation.

Seems Like You doing IT wrong

Er. Harinder Singh <notifications@github.com> schrieb am Sa., 22. Juni
2019, 10:04:

**Comment by ErHarinderSingh** [comment]
I am trying like this:
Check link : https://medium.com/@swarnakishore/angular-safe-pipe-implementation-to-bypass-domsanitizer-stripping-out-content-c1bf0f1cc36b

**Comment by KillerCodeMonkey** [comment]
Could You please create a plunkr, Stackblitz or codepen.?



Er. Harinder Singh <notifications@github.com> schrieb am Sa., 22. Juni
2019, 10:08:

**Comment by KillerCodeMonkey** [comment]
hey i extended my example repo, demo and the readme section:

As you can see alignment works great:
https://killercodemonkey.github.io/ngx-quill-example/#html

Maybe i extend ngx-quill with a view-component :)

**Comment by bvtmsr** [comment]
Hello @KillerCodeMonkey , Plese help me .
 ngx-quill Editor in  ngx-smart-modal-popup . I am getting issue like 

Create Description:-
<p>One</p><p>Two</p><p>Three</p>

Reopen the Editor Getting like this .
<p>OneTwoThree</p>

https://stackoverflow.com/questions/67736075/problem-with-quill-js-in-angular-ngx-smart-modal-popup

thank you
