### ISSUE TITLE
Picture upload does not trigger data binding

### ISSUE THREAD

**Issue by VolcanoOves** [KillerCodeMonkey/ngx-quill#403]
When I upload pictures after success, direct access to the content of the rich text, found no pictures, so I try again once, upload pictures first, and then enter the one character at a time, to obtain the rich text content, image tag is found, the preliminary inference is your images without triggering presents data change, must need to text input to trigger the data update。

**Comment by KillerCodeMonkey** [comment]
could you build an example or describe it better?

I do not understand it.

when i use the image format in the toolbar here, the result is directly presented, so the model updates???
https://killercodemonkey.github.io/ngx-quill-example/#html

**Comment by VolcanoOves** [comment]
https://stackblitz.com/edit/angular-bvcvps?file=src%2Fapp%2Fapp.component.ts

**Comment by VolcanoOves** [comment]
You try to upload the image, click the button。Cannot get the correct rich text content，Missing picture tag。

**Comment by VolcanoOves** [comment]
Upload the image, and then type a random character，You can get normal results。

**Comment by KillerCodeMonkey** [comment]
ah okay, checkout https://github.com/KillerCodeMonkey/ngx-quill#config and then the `trackChanges` config.

the image modal in quilljs does not trigger the changes as source: "user". But angular models and controls should only update on real user changes. So ngx.quill checks for source: "user".

with the config you can set, if ngx-quill should track all changes.

A good workaround would be to add an imageHandler that adds an empty string after an image upload as source "user".

https://quilljs.com/docs/api/#text-change

**Comment by KillerCodeMonkey** [comment]
In your demo:

```HTML
<quill-editor [(ngModel)]="richContent" (onEditorCreated)="editorCreated($event)" trackChanges="all"></quill-editor>
```

**Comment by VolcanoOves** [comment]
thanks!!!
