### ISSUE TITLE
Cannot get html displaying in quill-editor

### ISSUE THREAD

**Issue by zpydee** [KillerCodeMonkey/ngx-quill#404]

**Comment by KillerCodeMonkey** [comment]
maybe some additional info like code, and what is happening?

**Comment by zpydee** [comment]
apologies. hit enter before I meant to. comilping message now...

**Comment by KillerCodeMonkey** [comment]
AAAAAAAAllllrighty then :D

**Comment by zpydee** [comment]
My app in Angular 7 currently.

the following screenshot is three components all linked to the same reactive forms control.

<img width="634" alt="Screenshot 2019-06-25 at 14 36 02" src="https://user-images.githubusercontent.com/6129162/60099188-79079600-9757-11e9-90bd-6c5101919e63.png">

- Component 1: Simple bound angular material text-area. As you can see, its being updated after having interacted with your component.
- Component 2: your `quill-editor` component
- Component 3: your `quill-view-html` component

if you look at components 2 and 3, you'll notice that only some of the html is being rendered correctly:
- sup is working
- font-face is working
- u is working
- strong is working\
- ul>li is **NOT WORKING**

i have experienced similar issues with `h1`, `h2` and other styles too.

I'm pretty sure the error is on my side - i must be using your lib incorrectly.

Pls advise.

My component is as simple as it can possibly be. (obviously want to get rid of `quill-view-html`....

## html

```
<form [formGroup]="form">
    <quill-editor [formControlName]="control"> </quill-editor>
    <quill-view-html [content]="form.value[control]"></quill-view-html>
</form>
```

## ts

```
import { Component, OnInit, Optional, Self, Input, ViewChild } from '@angular/core';
import { NgControl, FormGroup } from '@angular/forms';
import { QuillEditorComponent } from 'ngx-quill';

@Component({
    selector: 'forms-rich-text',
    templateUrl: './rich-text.component.html',
    styleUrls: ['./rich-text.component.css']
})
export class RichTextComponent {
    //// -------------------------------- ////
    //// Api
    //// -------------------------------- ////
    @Input() form: FormGroup;
    @Input() control: string;

    htmlString = '<h1>ping</h1>';
}
```

inputs passed from parent component:

## parent

```
<forms-rich-text [form]="form" control="description"></forms-rich-text>
```

**Comment by KillerCodeMonkey** [comment]
no probs the view components are really new, so i hacked them together on the last weekend. 

So it could be that i missed something.

just checkout my demo-repo and playaround with the view-html example component. if the problem is also existing there, so it is maybe a problem of mine.

**Comment by zpydee** [comment]
i don't want to be using `view-html`. would rather just use the `editor`. but its not behaving nicely.

**Comment by zpydee** [comment]
`view-html` is rendering everything. `editor` is not.

**Comment by KillerCodeMonkey** [comment]
aaahh you mean my view component is working, but the editor is not?

**Comment by zpydee** [comment]
correct.

**Comment by zpydee** [comment]
ps: love the real-time response dude.

**Comment by KillerCodeMonkey** [comment]
okay than i would guess you should check if some styles are overwritten by material?
because my view-html component just uses quilljs css and the output of the editor seems correct.

maybe material adds some style for something with an contenteditable attribute?

**Comment by zpydee** [comment]
my angular.json excerpt...


```
 "styles": [
                            "node_modules/quill/dist/quill.bubble.css",
                            "node_modules/quill/dist/quill.snow.css",
                            "libs/core/assets/themes.scss",
                            "libs/core/assets/icons.css",
                            "libs/core/assets/snackbar.css",
                            "libs/core/assets/styles.css",
                            "libs/shared/components/calendar/src/assets/styles.css",
                            "apps/papill-io/src/styles.css"
                        ],
```

**Comment by zpydee** [comment]
should i perhaps look for a ul > li style i'm overwriting?

**Comment by KillerCodeMonkey** [comment]
just inspect the editor element in your browser and check the css

right click on the page --> Inspect page. So you see the html and styling on the right.
select the editor element i think the div with the class .ql-editor and then check if there is something overriding the liststyling.

**Comment by zpydee** [comment]
if you look at your editor output, the `<ul><li>` is missing....

**Comment by KillerCodeMonkey** [comment]
https://killercodemonkey.github.io/ngx-quill-example/#html ??? i think there is everything in the editor. in the connected control/model and in the presentation..

**Comment by zpydee** [comment]
let me play some more...

**Comment by KillerCodeMonkey** [comment]
okay you passing the html from a database to the editor?

**Comment by zpydee** [comment]
yes, currently storing whatever your component outputs as a string (html)

**Comment by zpydee** [comment]
if you look at my "summay" field, that's exactly what I store....

**Comment by KillerCodeMonkey** [comment]
then maybe angular is stripping the html.

checkout the sanitize property of the editor component

**Comment by zpydee** [comment]
will do.

**Comment by zpydee** [comment]
PS: you should work on your docs a bit. It takes a long time to get to grips with the lib, and its a good one. You don't want to lose those users that aren't so committed to getting stuff right.

**Comment by KillerCodeMonkey** [comment]
i know... i know, but i am a single maintainer with a personal life and a full time job. ;)
So i am doing what i like and for what i want to invest my time.

That is why my docs in general are more "functional" :D.

Feel free to add a PR with a refactoring.

**Comment by zpydee** [comment]
if only I don't have my more that 16 hours a day dev job already :-)

**Comment by zpydee** [comment]
sanitize not helping. i'm going to have to explore. when I find the issue, i'll let you know. I'm sure it won't be an isolated issue, so maybe something you need to bullet proof.

**Comment by KillerCodeMonkey** [comment]
maybe you can create working example as stackblitz.

**Comment by zpydee** [comment]
cannot. app too complex to replicate. may well be an issue on my side though, so let me check...

**Comment by zpydee** [comment]
you've been really helpful, thank you.

**Comment by zpydee** [comment]
gonna close for now.

**Comment by KillerCodeMonkey** [comment]
feel free to post a solution if you got it!

**Comment by zpydee** [comment]
have inspected my code. sorry to say but i think you component is breaking the html. perhaps test lists? they render when modified in your component but not on reloads...

**Comment by KillerCodeMonkey** [comment]
but my demo repo is setting list code on load?

https://killercodemonkey.github.io/ngx-quill-example/#html

**Comment by zpydee** [comment]
i see that. don't know what to say, but not having joy.. i'll experiment a bit more later...

**Comment by KillerCodeMonkey** [comment]
try to reproduce the issue in a stackblitz. so i can easy take look over the code.

**Comment by zpydee** [comment]
<img width="1152" alt="Screenshot 2019-06-25 at 16 28 22" src="https://user-images.githubusercontent.com/6129162/60107267-e969e380-9766-11e9-9aee-cd129a73b2b7.png">


if you look at my elements, your component is quote clearly rendering a `<p>` tag even though the stored string contains `<ol><li>`.

this is not a css issue or an angular sanitize issue.

**Comment by KillerCodeMonkey** [comment]
could you check if your tags are correctly encoded? Maybe you database escapes or encodes them.

Did you tried to hard code the content you pass?

**Comment by KillerCodeMonkey** [comment]
And important: your editor format is html? Maybe you accidentally have set the format to text or something else

**Comment by zpydee** [comment]
none of the above. i'm using firebase and the stored variable is a simple string (as displayed in my "test" summary field. i'd expect that to be appropriately parsed by your component. would you expect the same?

**Comment by zpydee** [comment]
i've left all you `editor` defaults.

```
<form [formGroup]="form"><quill-editor [formControlName]="control"> </quill-editor></form>
```

**Comment by zpydee** [comment]
also, why would some html parse and others not?

ie, my `<u>`, `<strong>` tags work but the list  and heading tags do not?

**Comment by zpydee** [comment]
in my mind this tends to indicate an internal library error.

**Comment by KillerCodeMonkey** [comment]
yeah but please try it in a clean angular project or with a fixed string. 

and btw, when you are using formGroup just use formControlName and the name of the control instead of dynamic bindings :)

**Comment by KillerCodeMonkey** [comment]
So i tried a little bit around, even with formGroup and control + patching the control value after some time, everything works:

```TS
@Component({
  selector: 'app-format-html',
  templateUrl: './format-html.component.html'
})
export class FormatHtmlComponent {
  form: FormGroup = this.fb.group({
    html: new FormControl('<div>test</div><ul><li>1</li><li class="ql-indent-1">1-1</li><li>2</li><ol><li>numbered</li><li class="ql-indent-1">numbered-1</li></ol></ul><div><br></div>')
  })

  constructor(private sanitizer: DomSanitizer, private fb: FormBuilder) {}

  ngOnInit() {
    setTimeout(() => {
      this.form.get('html').patchValue('<ol><li><sup>test</sup></li></ol>')
    }, 4000)
  }

  byPassHTML(html: string) {
    return this.sanitizer.bypassSecurityTrustHtml(html)
  }
}
```

```HTML
<h3 id="html">Format - HTML</h3>
<pre>
  <code>
    {{ form.get('html').value }}
  </code>
</pre>

Presentation in HTML
<div class="ql-container ql-snow" style="border-width: 0;">
  <div style="width: 100%" class="ql-editor" [innerHTML]="byPassHTML(form.get('html').value)">.   </div>
</div>

<form [formGroup]="form">
  <quill-editor format="html" formControlName="html"></quill-editor>
</form>

```

**Comment by KillerCodeMonkey** [comment]
Just try to store the JSON string of the content in your database (format="json"), it is smaller an considered more stable + no XSS issues.

**Comment by zpydee** [comment]
ok, good news. i've reapplied my `rich-text-component`  (which uses your lib) in my `core` app environment and it seems to work.

the way we've architected is that all our apps work off a "core" base, which is all the features we need for the app shell, authentication, subscription management, etc and then we build app features on top of this. 

so, the problem is **definitely on my side**, for one of my specific apps.

I must tell you that the real-time support I've received from you over the last day is amazing. Never experienced this from any other lib provider. Well done!!

When I find the problem causing the issue in my app, I'll be sure to let you know what it was to help others prevent it as well.

**Comment by KillerCodeMonkey** [comment]
Nice. Hope you get it working soon :)

I close this issue, but feel free to inform me how you solved it

**Comment by zpydee** [comment]
so, this is a very interesting issue. it actually seems to be related to angular's async pipe. once I have more information, i'll send it to you

**Comment by zpydee** [comment]
i have the component working correctly now, but to be honest - I'm not sure why...

if you want I'm happy to jump on a skype call to show you what changes made the difference. I suspect there may be something internal that causing angular + rxjs to reject something within your lib.

**Comment by KillerCodeMonkey** [comment]
@zpydee 
x-files intro start playing

**Comment by zpydee** [comment]
lol

**Comment by zpydee** [comment]
there's definitely some sort of reactive issue. perhaps a race issue on a timeout? i noticed in your earlier code you sent me that you used a timeout.

**Comment by zpydee** [comment]
does you lib completely embrace observables?

**Comment by KillerCodeMonkey** [comment]
i added the timeout example to the ngx-quill-example repo.

I think so, because it implements the angular ControlAccessor and runs in there.
If there would be some issue, it should not update the content at all, but not stripping html tags

**Comment by zpydee** [comment]
yeah, it's a weird one. in my case, literally moving divs with `*ngIf="x$ | async; let x` up in the html made the component work.

Odd, no?

**Comment by KillerCodeMonkey** [comment]
i must say, i do not like the asyncPipe and i would never implement such stuff in a framework.

just subscribe in ngOnInit and unsubscribe in ngOnDestroy if you have uncompleted subscriptions.
So you know when your data is there and when it is gone.

No template logic and unit testable code.

**Comment by zpydee** [comment]
disagree with that. async pipe does exactly what you just described, with no extras. also, polluting ts with unnecessary OnInit and OnDestroy methods just pollutes components and makes them more difficult to maintain.

 the error i experienced may well be an inherent angular bug, but I hope my experience over the last two gives you some info about an advanced usage of your lib. mine is a big app. your demos are "theoretical". they represent the easiest usage of your lib, not necessarily real world applications.

i'd really suggest looking into the way you code consumes rxjs.

**Comment by KillerCodeMonkey** [comment]
my lib does not use anything from rxjs (explicit).
It just uses standard angular functionalities.

> disagree with that. async pipe does exactly what you just described, with no extras. also, polluting ts with unnecessary OnInit and OnDestroy methods just pollutes components and makes them more difficult to maintain.

Yeah, but most angular developers are not looking behind the scenes, what is really happening.

If you are using libs/frameworks with view caching - e.g. ionic - component are not destroyed in many cases, because they are cached. so you are polluting the dom and change detection cycles with unwanted data ;).

I like to see what is happening instead of pushing such things to the template.

Even the "maintain" argument is invalid. In most cases you are using this hooks beside the data fetching.

And it is only my opinion ;).

**Comment by zpydee** [comment]
nice working with you bud. and thanks for the wrapper. i'll use it in my app.

**Comment by eBitzu** [comment]
For me the problem was that using material design, kinda screw things up, so if you have like tabs and so on, please make them lazyload.

```
<mat-tab>
	<ng-template matTabContent>
		<quill-editor></quill-editor>
	</ng-template>
</ng-template>
```

**Comment by KillerCodeMonkey** [comment]
nice! thanks

**Comment by ersaurabh101** [comment]
I have tried the above code, it is still not taking styles like color

below is the code i am trying

```
    setTimeout(() => {
      this.form.get('html').patchValue('<p style="color:blue;">test.....</p>')
    }, 4000)
```

Its been 6 hours playing with this now, please help if possible

**Comment by KillerCodeMonkey** [comment]
you know quilljs uses class based styling per default. if you want to use inline css checkout the quilljs documentation https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

**Comment by ersaurabh101** [comment]
How do i make sure in line syles like this one - https://codepen.io/ersaurabh101/pen/YzywbgR , when i copy in quill looks same in ionic ? can you guide me what do i need to do in ionic ?

**Comment by AjeetEppa** [comment]
Hi, I tried this,
```
str = this._DomSanitizationService.bypassSecurityTrustHtml(
    `<p style="color: red;">anything</p>`
  );
```
```
<quill-editor
  [ngModel]="str"
  [sanitize]="'true"
></quill-editor>
```

Still not setting color to red, this maybe because of what you said above.
But could you pls state a way to get this working? because, this is how I will be getting my html and passing it to **quill-editor**

**Comment by KillerCodeMonkey** [comment]
Quill is using CSS classes dir Styling and mit inline Styling and in it
only allows known Formats / Tags.

So you cannot expect that every HTML Code is working.

Check quilljs documentation If you want to Switch from class based Styling
to inline Styling

Ajeet <notifications@github.com> schrieb am Fr., 17. Apr. 2020, 14:03:

**Comment by AjeetEppa** [comment]
Thanks for your response.
But How do I register it in Angular?
I belive this is where you wanted me to go
![image](https://user-images.githubusercontent.com/48122590/79569567-70f95800-80d5-11ea-947c-2277bdda6e57.png)

**Comment by KillerCodeMonkey** [comment]
You do IT The Same way. Check my Demo repo how i Register custom Formats or
add new fonts

Ajeet <notifications@github.com> schrieb am Fr., 17. Apr. 2020, 14:32:

**Comment by AjeetEppa** [comment]
Hi, 
Could pls take a look and tell what is going wrong?
![image](https://user-images.githubusercontent.com/48122590/79573027-96896000-80db-11ea-8735-8890f00fd813.png)

Html
![image](https://user-images.githubusercontent.com/48122590/79573991-195eea80-80dd-11ea-8580-feda1d213189.png)

**Comment by AhmadNetDevelper** [comment]
using Reactive Forms ......
 in HTML File  .......

<quill-editor  [formControl]="_FrmAddNew .get('EmailContentAr')"  [styles]="{height: '200px'}"  >
</quill-editor> 

in ts File ......
  ngInitialControlForm() {
    this._FrmAddNew = this.formb.group({
      Id: [0],
      EmailContentAr:['']
    });
  }

**Comment by KillerCodeMonkey** [comment]
@AhmadNetDevelper "thumbing up" your own comment, which i need to format... come on :D

**Comment by emanuelevivoli** [comment]
Hi @KillerCodeMonkey , really great project 😎. 
Actually I get this error both on the `quill-editor` and the `quill-view`.
Yes, I get my "stringified" html by promise, and the things is that I'd like to use it with runtime updates on it (the html stays on my db as string, and other people can change it at any time).

How do you suggest to manage it? 
Actually the html is correct but `quill-editor` and `quill-view` don't show the content properly.

<img width="1026" alt="Screenshot 2020-05-22 at 15 43 01" src="https://user-images.githubusercontent.com/9447991/82675597-5884dc00-9c45-11ea-84dc-c01b51e0345d.png">

wait for advice, thanks ✌️

**Comment by emanuelevivoli** [comment]
Hi, sorry, I though was understandable from the context, my fault. 
The error is that my html-string says something, but my quill-editor is not showing the same thing (as you can see, the first red row must be h1, and so on).

I try put some code to make it more understandable:

`reactive-form.component.ts`
```typescript
@Component({ ... })
export class ReactiveFormsComponent implements OnInit {
    @Input() data: BehaviorSubject<string>; // this is the html
    form: FormGroup;
  
    @ViewChild('matEditor', { static: true })
    matEditor: MatQuill;

    constructor(fb: FormBuilder) {
        this.form = fb.group({  matEditor: ['']  });
    }

    ngOnInit(): void {
        this.data.subscribe((data: string) => {
            this.form.get('matEditor').patchValue(data);
            // tried also -> this.form.controls.matEditor.setValue(data);
        });
    }
}
```

`reactive-form.component.html`
```html
<form [formGroup]="form">
    <quill-editor formControlName="matEditor"> </quill-editor>
    <!--  i tried also with *format="html"* -->
</form>

<pre>{{form.controls.matEditor.value}}</pre>
```

and the result is what you can see in the screenshot, the elements have their tag (like `<h1>`, `<ul>`, `<li>`) but none of those is rendered as it should be.
Actually all of those are as they were just `<div>`, in fact (as you can see from the screenshot below) after a change the formControl shows how they are rendered: just `<div>`

<img width="1026" alt="Screenshot 2020-05-22 at 20 20 45" src="https://user-images.githubusercontent.com/9447991/82697729-bfb48780-9c69-11ea-8fea-b1cb951fc429.png">

Btw, I'll work on setting up a stackblitz to see if I can reproduce it.

**Comment by KillerCodeMonkey** [comment]
Keep in mind, that quill only allows Tags and Formats or already knows. You
can Not Pass custom HTML and expect that quilljs renders IT correctly.

Just check IT Out in my Demo repo.




Immanuel <notifications@github.com> schrieb am Fr., 22. Mai 2020, 20:23:

**Comment by emanuelevivoli** [comment]
Hi, I'm using your Demo repo, actually I'm using the `reactive-form` and the `view-html` components. What I see is that the string to render is just composed by `<h1>`,  `<ol>`, `<li>` and `<span>` which I thought were html tag and not custom. 
In your example everything is working (with html-view), I set a time Interval where change the html string every sec, and it renders well.

Anyway, I changed in my example the format to `format='json'` and all worked perfectly. So I guess I had some formatting-html problem neither in the saving step nor in the fetching step, but somewhere in the presentational step. 

Thanks for your help, bye

**Comment by awais2080** [comment]
thanks @KillerCodeMonkey  such a great work, although i had to read all questions answers and going through different sources,

your htmlEditButton is great but lack proper documentation for angular.


so for those using this for angular 10 you just need to copy past these lines after installing quill and htmlEditButton.

app.module.ts


```

import { QuillModule } from 'ngx-quill';

import * as QuillNamespace from 'quill';
const Quill: any = QuillNamespace;
import { htmlEditButton } from 'quill-html-edit-button';
Quill.register('modules/htmlEditButton', htmlEditButton);

QuillModule.forRoot({
      modules: {
        htmlEditButton: {
          debug: false, // logging, default:false
          msg: 'Edit the content in HTML format',
          okText: 'Ok', // Text to display in the OK button, default: Ok,
          cancelText: 'Cancel', // Text to display in the cancel button, default: Cancel
          buttonHTML: '&lt;&gt;', // Text to display in the toolbar button, default: <>
          buttonTitle: 'Show HTML source',
          // Text to display as the tooltip for the toolbar button, default: Show HTML source
          syntax: false,
        },
      },
    }),


```

**Comment by ramzan-ali-suzan** [comment]
> I think it may have an incorrect ending tag. It will maybe...
> 
> ```
> <mat-tab>
> 	<ng-template matTabContent>
> 		<quill-editor></quill-editor>
> 	</ng-template>
> </mat-tab>
> ```

**Comment by dipandanny** [comment]
I am having the same issue. 
Here is my code,
In app.componnet.ts: 
`
  DirectionAttribute = Quill.import('attributors/attribute/direction');
  AlignClass = Quill.import('attributors/class/align');
  BackgroundClass = Quill.import('attributors/class/background');
  ColorClass = Quill.import('attributors/class/color');
  DirectionClass = Quill.import('attributors/class/direction');
  FontClass = Quill.import('attributors/class/font');
  SizeClass = Quill.import('attributors/class/size');
  AlignStyle = Quill.import('attributors/style/align');
  BackgroundStyle = Quill.import('attributors/style/background');
  ColorStyle = Quill.import('attributors/style/color');
  DirectionStyle = Quill.import('attributors/style/direction');
  FontStyle = Quill.import('attributors/style/font');
  SizeStyle = Quill.import('attributors/style/size');
    Quill.register(this.DirectionAttribute, true);
    Quill.register(this.AlignClass, true);
    Quill.register(this.BackgroundClass, true);
    Quill.register(this.ColorClass, true);
    Quill.register(this.DirectionClass, true);
    Quill.register(this.FontClass, true);
    Quill.register(this.SizeClass, true);
    Quill.register(this.AlignStyle, true);
    Quill.register(this.BackgroundStyle, true);
    Quill.register(this.ColorStyle, true);
    Quill.register(this.DirectionStyle, true);
    Quill.register(this.FontStyle, true);
    ngOnInit(): void {
        body = '<p><span style="background-color: rgb(255, 255, 0);">Test Test Tes</span></p>'
    }`

**Comment by KillerCodeMonkey** [comment]
santizing is a boolean value if you pass the string "false" it is truthy ;-)

`[sanitize]="false"`

**Comment by vokilam-d** [comment]
I'm having same issue. Narrowed it down to using `*ngIf` with content projection.
Have a repro example on stackblitz:
https://stackblitz.com/edit/angular-qvlzwv?file=src/app/spoiler.component.ts

1. `AppComponent` creates form control with html as value (4 paragraphs `<p>`)
2. `AppComponent` template inserts quill editor into child component  `SpoilerComponent`  using content projection
3. Inside  `SpoilerComponent` using `*ngIf` hide `<ng-content>` by default.
4. Show projected content providing truthy value to `*ngIf`.
5. See that html value in editor is now rendered as single-line text in 1 paragraph `<p>`

**Comment by ranickpatra** [comment]
> For me the problem was that using material design, kinda screw things up, so if you have like tabs and so on, please make them lazyload.
> 
> ```
> <mat-tab>
> 	<ng-template matTabContent>
> 		<quill-editor></quill-editor>
> 	</ng-template>
> </ng-template>
> ```

It also works for me
