### ISSUE TITLE
increasing lines breaks before lists

### ISSUE THREAD

**Issue by zpydee** [KillerCodeMonkey/ngx-quill#405]

**Comment by KillerCodeMonkey** [comment]
???

**Comment by zpydee** [comment]
not sure if this is an issue with quill itself?

if you have lists (ordered or not), and you add content to the editor, the componenet adds an extra break before the lists.

BEFORE:

<img width="713" alt="Screenshot 2019-06-26 at 15 48 01" src="https://user-images.githubusercontent.com/6129162/60185252-dc61f880-9829-11e9-9322-d735749bf06f.png">

AFTER:

<img width="872" alt="Screenshot 2019-06-26 at 15 48 51" src="https://user-images.githubusercontent.com/6129162/60185678-9ce7dc00-982a-11e9-9b42-3449ccfe8546.png">

Take note of extra space added before lists. An extra line is added each time I add content to the editor.

**Comment by KillerCodeMonkey** [comment]
this is a quill issue. 

My component does nothing really complex. it just wraps the default quilleditor and its events + some additional benefits like different format handling, but uses the internal quill methods for that.

So check the issues there. Thanks

**Comment by zpydee** [comment]
wlll do, thanks.

**Comment by zpydee** [comment]
[https://github.com/quilljs/quill/issues/2662](For your reference)

**Comment by KillerCodeMonkey** [comment]
check

https://github.com/quilljs/quill/issues/1483
https://github.com/quilljs/quill/issues/1712

the matchVisual does no exist in newer quill version. 
So this issues seems unresolved

**Comment by zpydee** [comment]
ok. thanks for that.i think i'll patch the issue by removing `<p><br></p>` from any editor onContentChange for the time being. anything else broken in quill I should be aware of that you know?

**Comment by KillerCodeMonkey** [comment]
only that when using the clipboard some browser like chrome stripping some tags i think. (but this maybe a browser thing)

And i think there are some issues using chinese or special language chars.

I have only simple use cases for quill like german or english language without any special stuff.

For you as a hint again. Just do not use html format in general like quill should be used.
Use the object or json representation.

**Comment by zpydee** [comment]
only learnt about quill yesterday. never needed a rich-text editor before. your advice is solid. i'll check out their api and stop bugging you :-)

**Comment by KillerCodeMonkey** [comment]
if you use json string or the object representation it is very simply to change the editor version or migrate to another editor/representation afterwards.

Patching html strings in your database is a mess and will be fail if you have complex documents.
If you store the object representation you simply have a list of commands with special attributes.

So you can write easy clean routines to change them.

**Comment by zpydee** [comment]
converted to `format="json"` and all good. thanks for your time.
