### ISSUE TITLE
Using toolbar module in forRoot does not display in mat-dialog

### ISSUE THREAD

**Issue by zpydee** [KillerCodeMonkey/ngx-quill#406]
have you tried using the quill-editor in a material dialog? In my case i can not get the toolbar to display with specified options in the forRoot method. I have to manually insert via a `quill-editor-toolbar` div.

**Comment by KillerCodeMonkey** [comment]
never tried it :)

Maybe you are creating another module instance in the modal, or overriding the config.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by zpydee** [comment]
I've implemented for the time being with your html config. For Root will not work with material dialog. You'll need to investigate that. Need to get beyond this quill stuff and back onto my app.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KillerCodeMonkey** [comment]
> You'll need to investigate that

i think i will not alone investigate that.
If you have an issue, it is on both of us. 

So feel free to do your part an create a stackblitz or a small demo repo where i can reproduce this.

**Comment by KillerCodeMonkey** [comment]
And checkout this one:
https://github.com/angular/components/issues/12891#issuecomment-417299731

Maybe the dialog module is lazy loaded or the module where you are using it.
So it gets a local instance and not the root one.

Could be a thing

**Comment by zpydee** [comment]
> If you have an issue, it is on both of us.

I think you may be confusing me as a contributor to your lib. I'm just a user trying yo give you feedback to improve it.

**Comment by KillerCodeMonkey** [comment]
Yeah, but when opening an issue. Then IT is Up to You to provide the
required information i Need ;). If Not i could simply Close the issue .
Contributing would be making a pull request , but Not providing an example
to Show the Problem... Something Like an evidence

zpydee <notifications@github.com> schrieb am Fr., 28. Juni 2019, 09:56:

**Comment by zpydee** [comment]
I have solved my implementation, so I'll close myself.

**Comment by KillerCodeMonkey** [comment]
And would You let me know the solution or the cause?

zpydee <notifications@github.com> schrieb am Fr., 28. Juni 2019, 10:03:

**Comment by zpydee** [comment]
I just implemented with the html using you `quill-editor-toolbar` attr. that worked fine. i've now created a  reusable`rich-text-editor-toolbar` component which  allows me to manage the quill toolbar across all my components that require it, and this solution seems to be universally working regardless of angular material constraints.

**Comment by zpydee** [comment]
as i said before, it seems that forRoot declarations seem to be conflicting with mat-dialog. i hope this gives you some direction. I apologize for not being able to give this more time.

**Comment by zpydee** [comment]
interestingly, `quill-mention` also doesn't like mat-dialog

**Comment by KillerCodeMonkey** [comment]
Thanks Mate :)

zpydee <notifications@github.com> schrieb am Fr., 28. Juni 2019, 10:16:

**Comment by zpydee** [comment]
following further investigation, seesm to be related to the mat-cdk overlay behaviour. again sorry i cannot work with you on this in real time but i'll continue trying to give you information.

thank you again for all the assistance you've given me.

**Comment by KillerCodeMonkey** [comment]
@zpydee seems like there was a problem how i defined the providers.

there was the forRoot method, but when used in a lazyloaded module QuillModule (without forRoot) provided another instance of the config.

try using 6.3.1

**Comment by developerant** [comment]
Having the same issue here. For me it works up till 9.2.0, and breaks at the project refactoring here:

https://github.com/KillerCodeMonkey/ngx-quill/releases/tag/10.0.0
