### ISSUE TITLE
使用angular8在进行import导入时报错

### ISSUE THREAD

**Issue by ynzy** [KillerCodeMonkey/ngx-quill#407]
在进行import导入时报错
import { QuillModule } from 'ngx-quill'
imports: [
    QuillModule
  ],
ERROR in ./node_modules/ngx-quill/fesm2015/ngx-quill.js
Module not found: Error: Can't resolve 'quill'

**Comment by KillerCodeMonkey** [comment]
Please in Englisch. Just follows the readme... Install quill AS dependency
..

张勇 <notifications@github.com> schrieb am Fr., 28. Juni 2019, 09:07:
