### ISSUE TITLE
html not displaying in editor when provided with data

### ISSUE THREAD

**Issue by ArnoMyOnlinePresence** [KillerCodeMonkey/ngx-quill#408]
Hey there

The html is working perfect when adding a list, but when providing it with the same data it outputs it doesn't work.

![image](https://user-images.githubusercontent.com/30623106/60388950-3b896c80-9ab9-11e9-80e7-1a8d347de7fc.png)
![image](https://user-images.githubusercontent.com/30623106/60388957-6673c080-9ab9-11e9-9d27-16dd325c4b2c.png)
![image](https://user-images.githubusercontent.com/30623106/60388961-83a88f00-9ab9-11e9-9715-0c68e47960c2.png)

It shows correct in the html preview but not the editor

**Comment by KillerCodeMonkey** [comment]
please check the already closed issues and the demo repo. there is an example with formControla nd html format

https://killercodemonkey.github.io/ngx-quill-example/#html

btw: there are new view-components in this module to print html or the other formats outside of the editor context.

Could you create a plunkr, codepen or stackblitz with a minimal example to reproduce this issue?

And please check the dom of the editor, which is the content of the editor

**Comment by ArnoMyOnlinePresence** [comment]
our client only wants the editor. They don't want the view component. I just added it for testing. setting a timeout of 75 milliseconds and doing control.patchValue(value) works, but why doesn't it work without it

**Comment by KillerCodeMonkey** [comment]
never had this issue. could you provide more code or a working example?

Or do you see some differences to my example repo code?

**Comment by ArnoMyOnlinePresence** [comment]
if you can provide me with a blank plunker with your library added i can try to replicate it. have never had much luck setting up my own plunker

**Comment by KillerCodeMonkey** [comment]
maybe you can use this one: https://stackblitz.com/edit/ngx-quill-qdywc2?file=package.json

Where did you store your html? maybe the backend encoded the <> chars to avoid security issues?
So it is correctly printed as html but quill can not transform the html?

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by ArnoMyOnlinePresence** [comment]
i haven't had the time to replicate it yet, will do it sometime this week and get back to you

**Comment by KillerCodeMonkey** [comment]
any updates? i will close this issue due to inactivity soon :).

Checkout latest versions ;)
