### ISSUE TITLE
ngModel does not update input html string after insertembedd with source 'user'

### ISSUE THREAD

**Issue by fokunn** [KillerCodeMonkey/ngx-quill#409]
IONIC3 project,
in .html , the code is:

` <quill-editor (onEditorCreated)="onEditorCreated($event)" (onContentChanged)="onContentChanged($event)" [(ngModel)]="content.htmlContent"
      [modules]="quillModules" [theme]="'bubble'" [placeholder]="placeHolder"></quill-editor>`

in .ts file the code is:
`  let range = this.quillEditor.getSelection(true);

   this.quillEditor.editor.insertEmbed(range.index, 'image', imageWebLocation,'user');`

then, the` content.html` does not updated after `insertEmbed`

the webview is wkwebview.

any idear? 
or I miss something ?

**Comment by fokunn** [comment]
`
 let range = this.quillEditor.getSelection(true);

this.quillEditor.editor.insertEmbed(range.index, 'image', imageWebLocation,'user');
let text = ""

 this.quillEditor.insertText(range.index + 1, text,  'user')`

The above code is what I got after some research. It seems `inserEmbed `will never trigger the `ngModel `to update the bound( or called 'binded') input.  But `insertText `does. So the solution is to just insert a blank or what ever text after inserting image. then the input will be updated. 

hope this.help someone  else.

**Comment by KillerCodeMonkey** [comment]
should be fixed with https://github.com/KillerCodeMonkey/ngx-quill/releases/tag/6.2.0
