### ISSUE TITLE
Not working in Safari. 

### ISSUE THREAD

**Issue by sublime392** [KillerCodeMonkey/ngx-quill#411]
I am pretty sure this was previously working in Safari, but I'm not 100% positive. Works fine in Chrome. Safari acts like there is no handlers connected to the DOM or something... no errors, everything is just unresponsive; static.

I am now on 6.3.1. I had the same behavior on 6.1.something, and possibly on an earlier version.

**Comment by sublime392** [comment]
I'll look a little closer because I see the plunk https://stackblitz.com/edit/ngx-quill-qdywc2?file=package.json is still working in the same Safari browser. So maybe disregard for a bit until I see what is going on.

**Comment by KillerCodeMonkey** [comment]
how do you import the quillmodule?

**Comment by KillerCodeMonkey** [comment]
argg.. i fixed something that leads to a breaking change -.-. sorry
you have to import `QuillModule.forRoot()` in your app module.

I will release a new major version with updated readme
