### ISSUE TITLE
Error 413 Payload Too Large

### ISSUE THREAD

**Issue by rafaelscosta** [KillerCodeMonkey/ngx-quill#42]
Hi, when I upload a image to the content, the error bellow happens:

Response {_body: "<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta char…s/cors/lib/index.js:185:7)</pre>↵</body>↵</html>↵", status: 413, ok: false, statusText: "Payload Too Large", headers: Headers, …}
headers
:
Headers {_headers: Map(12), _normalizedNames: Map(12)} ok : false
status : 413
statusText : "Payload Too Large"
type : 2
url :
"http://www.adrianabartolomucci.com.br/api/servicos/59370f9d6993d8381cd31694"
_body
:
"<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta charset="utf-8">↵<title>Error</title>↵</head>↵<body>↵<pre>Error: request entity too large<br> &nbsp; &nbsp;at readStream (/home/adrianabartolomucci/apps_nodejs/node_modules/body-parser/node_modules/raw-body/index.js:196:17)<br> &nbsp; &nbsp;at getRawBody (/home/adrianabartolomucci/apps_nodejs/node_modules/body-parser/node_modules/raw-body/index.js:106:12)<br> &nbsp; &nbsp;at read (/home/adrianabartolomucci/apps_nodejs/node_modules/body-parser/lib/read.js:76:3)<br> &nbsp; &nbsp;at jsonParser (/home/adrianabartolomucci/apps_nodejs/node_modules/body-parser/lib/types/json.js:127:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at /home/adrianabartolomucci/apps_nodejs/app.js:43:5<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/home/adrianabartolomucci/apps_nodejs/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at cors (/home/adrianabartolomucci/apps_nodejs/node_modules/cors/lib/index.js:185:7)</pre>↵</body>↵</html>↵"
__proto__
:
Body

**Comment by KillerCodeMonkey** [comment]
this has nothing to do with quill or ng-quill.

The body length is restricted by requests body parser middleware per default.
https://github.com/expressjs/body-parser#limit

**Comment by rafaelscosta** [comment]
Thank you, solved problem setting the limit: 

// Body Parser Middleware
app.use(bodyParser.json({limit: '50mb'}));
app.use(bodyParser.urlencoded({limit: '50mb', extended: true}));
