### ISSUE TITLE
quill:toolbar ignoring attaching to nonexistent format float 

### ISSUE THREAD

**Issue by quasiDigi** [KillerCodeMonkey/ngx-quill#427]
Hi,

First let me thank you for your sharing your work.

I do not know if I have to be here or at quilljs.

I'm using a custom toolbar placed in a component with html. Inside I want to buttons to align an image.
the code I use for on of those buttons is:
`<button class="ql-float" value="left" [title]="'Image to the left'"></button>`

In the console I get the message:

> quill:toolbar ignoring attaching to nonexistent format float ...

The funny thing is that the there is a different button generated for each of the values: left - center - right.
<img width="112" alt="Screenshot 2019-07-04 at 18 01 05" src="https://user-images.githubusercontent.com/26095252/60678805-f59c2200-9e85-11e9-83ab-45de8080a02c.png">

Here is a minimal reconstruction of it:
https://stackblitz.com/edit/ngx-quill-ql-align-test

Thx!

**Comment by KillerCodeMonkey** [comment]
that is because quilljs tries to map css classes to formats. And this format "float" does not exist.

;)

**Comment by quasiDigi** [comment]
hi KillerCodeMonky, thx for your fast reply!

So `<button class="ql-float" value="left">` generates a nice button but there's no format to back it up, right?
I have to admit that I am quite a newcomer to the angular scene (well, actually to everything that's code related). Could you, please, point me out how to make a custom format?

Also, is this the list of the official formats: https://quilljs.com/docs/formats/ ?

Thx

**Comment by KillerCodeMonkey** [comment]
Thats now the Point where You have to Switch over to quilljs. This hast
nothing To-Do with angular or ngx-quill. Just Checkout the quilljs Home
Page. There are good Guides about that.

If you Just want to Use the Default quill alignment functionality - inspect
the Default quilljs toolbar and Take the classnames and Override the
Styling with CSS or Just create a custom quilljs Theme where You replace
the Icons. Just Checkout quilljs Docs :)


quasiDigi <notifications@github.com> schrieb am Do., 4. Juli 2019, 19:16:

**Comment by quasiDigi** [comment]
ok, thanks again!
