### ISSUE TITLE
Triggering clipboard with initial model value

### ISSUE THREAD

**Issue by adaojunior** [KillerCodeMonkey/ngx-quill#43]
It seems like when a new instance of `quill-editor` is created it triggers an event on the clipboard.
This behavior doesn't happen in the original version of quilljs. AI looked into the code and seems like you're using `pasteHTML` to insert the initial value, which makes it trigger the `clipboard`.

Context: On my application I'm listening for content that is pasted into the editor so I can clean up the content being pasted, the problem is that every time a new instance of `quill-editor` is created, it triggers a clipboard event which ends up changing the format of the value being passed by ngModel.

Here's a code example:

```
    /// this should be triggered ONLY when a new text is pasted from the clipboard.
    quill.clipboard.addMatcher(Node.ELEMENT_NODE, (node, delta) => {
      return new Delta().insert(node.textContent);
    });
```

cc: @EunusHosen

**Comment by KillerCodeMonkey** [comment]
okay, do you know the clipboard module? is there the possibility to deactivate it and reactivate it after initialization has finished?

**Comment by adaojunior** [comment]
Why do you use `pasteHTML()` instead of `setContents()` to set the initial value ?

I see that Quill used `setContents()` [see](https://github.com/quilljs/quill/blob/develop/core/quill.js#L101-L102):

**Comment by KillerCodeMonkey** [comment]
Ah nice idea. does not know something like: ```this.clipboard.convert()``` exists, because setContent() only adds Parchment content and not plain html.

All in all --> i think calling ```this.history.clear();``` should be enough.

I will look into it.

**Comment by KillerCodeMonkey** [comment]
the new release is using history and clipboard module + clears history after setting initial value:
https://github.com/KillerCodeMonkey/ngx-quill/blob/develop/src/quill-editor.component.ts#L109

**Comment by adaojunior** [comment]
Thank you @KillerCodeMonkey, I'll test on my application and I'll let your know if it works for me.
