### ISSUE TITLE
Image Resize module alignment problem

### ISSUE THREAD

**Issue by AsanehProjects** [KillerCodeMonkey/ngx-quill#433]

**Comment by AsanehProjects** [comment]
Hi, image alignment has saved like

**<div class="ql-align-justify"><img src="./Tulips.jpg" width="419"></div>**

but after I opened it with quill-view tag as described in it's help to use it as below:
 <div class="ql-container ql-snow" style="border-width: 0;">
                    <div class="ql-editor" [innerHTML]="asset?.content">
 </div>
it doesn't take effect aligments!

**Comment by KillerCodeMonkey** [comment]
yeah then just inspect how the image is styled in the editor and what is the resulting html.

**Comment by KillerCodeMonkey** [comment]
and just try to use DomSanitizer to byPass sanitation of your html

**Comment by AsanehProjects** [comment]
onContentChanged() doesn't support alignment and to take effect, after alignment I should resize to set align attribute in <img>

**Comment by KillerCodeMonkey** [comment]
it would be nice if you could write whole and correct sentence so i can understand your intention ;)

**Comment by AsanehProjects** [comment]
Ok, after i imported image into editor, until I haven't resize image, onContentChanged() function doesn't show any thing and it does mean it doesn't update changes

**Comment by KillerCodeMonkey** [comment]
ah okay. thats because those modules are not working correctly or using the quill api not how they should. Inserting an image is something like a user interaction so they should trigger those changes as "user", but they are doing it as "api".

So checkout the readme about the `trackChanges` input property of the quill-editor compnent.

**Comment by AsanehProjects** [comment]
thank you
