### ISSUE TITLE
How can I work with Quill object inside component?

### ISSUE THREAD

**Issue by engineerpavel** [KillerCodeMonkey/ngx-quill#434]
Here is example for quill library (without ngx-quill) from [stackoverflow](https://stackoverflow.com/questions/49247878/how-to-add-css-class-to-a-quill-selection):
```
var quill = new Quill('#editor', {
  modules: {
    toolbar: toolbarOptions
  },
  theme: 'snow'
});

var spanBlockButton = document.querySelector('.ql-spanblock');

//event listener to spanblock button on toolbar
spanBlockButton.addEventListener('click', function() {

        var range = quill.getSelection();
        if(range){

            quill.formatText(range,'spanblock',true);
        }else{

        }

    }
);
```

But with ngx-quill how can I get access to quill instance to call **getSelection()** function? Do I need initialize Quill again by
`var quill = new Quill('#editor', {}` ?

**Comment by KillerCodeMonkey** [comment]
check the documentation and the demo repo linked in the readme.

there is an output onEditorCreated where you can grab the editor instance.
