### ISSUE TITLE
Custom toolbar select - ngFor not working on options

### ISSUE THREAD

**Issue by Yexan** [KillerCodeMonkey/ngx-quill#436]
Hello, 
I'm facing an issue with the ngFor directive on custom toolbar.

I'm building an app with multiple instance of the editor sharing a common custom toolbar.
I've changed the font size select to add more sizes. To do so I've :

```typescript
// available-font-sizes.ts
export const AvailableFontSizes = [
  ...Array(71).keys()
].map((x) => x + 6 + 'px' )
```
```typescript
// text-layer.component.ts
import { Component, OnInit } from '@angular/core'
import { AvailableFontSizes } from './../available-font-sizes'

@Component({
  selector: 'rm-editor-text-layer', ...
})
export class TextLayerComponent implements OnInit {
  ...
  modules = {
    toolbar: { container: '#rm-text-layer--toolbar', ... }
  }
  customOptions = [{
    import: 'attributors/style/size',
    whitelist: AvailableFontSizes
  }]
  ...
}
```
```html
<!-- text-layer.component.html -->
<div
  class="rm-text-layer"
  [ngStyle]=textLayerStyle()>

  <quill-editor
    class="rm-text-layer--editor"
    [placeholder]="content"
    format="html"
    [(ngModel)]="textHtmlFormatted"
    [modules]="modules"
    [customOptions]="customOptions"
    (onFocus)="focus()"
    (onBlur)="blur()">
  </quill-editor>

</div>
```
```typescript
// text-layer-toolbar.component.ts
import { Component, OnInit, OnDestroy, Input } from '@angular/core'
import { AvailableFontSizes } from './../available-font-sizes'

@Component({
  selector: 'rm-editor-text-layer-toolbar',...
})
export class TextLayerToolbarComponent implements OnInit, OnDestroy {
  ...
  availableFontSizes = AvailableFontSizes
  ...
}
```
```html
<!-- text-layer-toolbar.component.html -->
<div
  id="rm-text-layer--toolbar"
  class="rm-text-layer--toolbar"
  [ngClass]="toolbarClass()"
  cdkDrag
  cdkDragBoundary=".rm-editor--editor"
  [cdkDragFreeDragPosition]="dragPosition"
  (cdkDragEnded)="onDragDropped($event)">

  <!-- Add font size dropdown -->
  <select class="ql-size">

    <!-- <ng-container *ngFor="let size of availableFontSizes">
      <option [value]="size"></option>
    </ng-container> -->

    <option value="10px"></option>
    <option value="16px"></option>
    <option value="22px"></option>
    <option value="36px"></option>
    <option value="48px"></option>
    <option value="72px"></option>
  </select>
  <button class="ql-bold"></button>
  <button class="ql-increase">+</button>
</div>
```
```sass
@mixin add-quill-font-size($font-size)
  .ql-picker.ql-size .ql-picker-item[data-value="#{$font-size}"]::before,
  .ql-picker.ql-size .ql-picker-label[data-value="#{$font-size}"]::before
    content: '#{$font-size}'!important


@for $size from 6 through 76
  +add-quill-font-size('#{$size}px')
```

So, like this, it works, when I hardcode the options in the `.ql-size` select.
But, when I try to use `*ngFor` like in my comment (because here I have only hardcoded some of the options, I need all the size in px form 6 to 76, I'd prefer to use a clean ngFor and not hardcode 76 options by hand) it creates the DOM elements but also create the basic size select with small normal large and huge values.

In this exemple I've wrapper the options in a `ng-container`, I've tried without it, and to put an ngModel on the select. All of the above didn't worked.

I hope you can enlighten me on this issue, feel free to ask more details and thanks for the awesome lib :) 👍

**Comment by KillerCodeMonkey** [comment]
i think this will not work, because i literally take the quill-toolbar element and use it as the toolbar parameter quilljs accepts.

https://quilljs.com/docs/modules/toolbar/#container

And quilljs is just plain javascript and knows nothing about angular and so on.

**Comment by Yexan** [comment]
Oh, that was what I was "afraid" about :( 
Thanks for your quick reply. I have other issues with the shared toolbar, I think I might change a bit the way I organized this project.
Well, if I find a way around for this I'll let you and the community know, I hope my issue might help someone else :) (at least for the sass part)

**Comment by Yexan** [comment]
Just a hint : 
It might be a problem of angular digest, the toolbar is passed to quilljs before the loop is evaluated, I don't know if we can change when it's linked when we use custom toolbar or if it's a good choice to do so.

**Comment by KillerCodeMonkey** [comment]
I initialise quilljs after the content is init using
NgAfterContentInit Life cycle Hook ;)

Adrien Martinet <notifications@github.com> schrieb am Mi., 10. Juli 2019,
17:08:
