### ISSUE TITLE
Turn spellcheck off?

### ISSUE THREAD

**Issue by IsaacSomething** [KillerCodeMonkey/ngx-quill#438]
Is there any way to turn the spellcheck off? I have tried this with no success

```
 QuillModule.forRoot({
      modules: {
        toolbar: [
          ['bold', 'italic', 'underline', 'strike', 'blockquote'],
          [{ 'list': 'ordered' }, { 'list': 'bullet' }],
          [{ 'color': [] }, { 'background': [] }],
        ],
        spellcheck: false
      }
})
```

Im not too sure where in the configuration this option can be set

**Comment by KillerCodeMonkey** [comment]
there is no configuration in quilljs to do such things.

i do not even know, if this is possible, because quilljs uses a div with the  contenteditable attribute.
Just try to add `spellcheck="false"` to a parent element or the quill-editor element.

**Comment by IsaacSomething** [comment]
Oh wow, that worked, i did not think that would work. Thanks!

**Comment by KillerCodeMonkey** [comment]
no probs, you are welcome :)

**Comment by Bhaskar5959** [comment]
Hi, can we use spellcheck property for getting spelling suggestions in our own application? I thought spell check property is worked for only  web browsers not for own applications.
