### ISSUE TITLE
[style] property binding not working anymore

### ISSUE THREAD

**Issue by dklmuc** [KillerCodeMonkey/ngx-quill#439]
After upgrading to 7.0.2 (coming from 4.3.3) the style property Binding is not working anymore.

Testcode:

`<quill-editor [ngModel]="title" [style]="{ height: '350px', resize: 'vertical' }"></quill-editor>`

has no effect for ql-editor.

reproduction: https://github.com/dklmuc/ngx-quill-angular8

**Comment by KillerCodeMonkey** [comment]
Check the Docs. IT named Styles now to avoid conflicts with the native
Style attribute

Jaye <notifications@github.com> schrieb am Fr., 12. Juli 2019, 14:49:

**Comment by dklmuc** [comment]
Argh sorry you're right and I'm blind... Although I've hat a quick glance through the revisions but that seems to have been a bad idea for a friday.

Thanks for the quick answer and a nice weekend 👍
