### ISSUE TITLE
[Angular 5] Rendering issue

### ISSUE THREAD

**Issue by phenric** [KillerCodeMonkey/ngx-quill#440]
Hi,

I'm trying to use Quill with ngx-quill and Angular 5.
But I have an issue with the rendering as you can see:
![Screenshot 2019-07-12 at 18 20 30](https://user-images.githubusercontent.com/12801437/61143210-dc245700-a4d1-11e9-9b40-487c6d5acff7.png)

Did anyone had the same issue ?

**Comment by KillerCodeMonkey** [comment]
Quill Core an quill snow Theme are Not loaded or Not loaded correctly.
Check the readme and or my Demo Repo. And btw. Angular is Not longer
supported.

phenric <notifications@github.com> schrieb am Fr., 12. Juli 2019, 18:32:

**Comment by phenric** [comment]
Hi thx for your answer.
I updated my Angular to the version 8.
But I still have this issue. Also, I use Angular in a MEAN application with Express.js.
P.S.: I followed this tutorial [https://www.youtube.com/watch?v=Sh3_k_QPGzw](https://www.youtube.com/watch?v=Sh3_k_QPGzw)

**Comment by KillerCodeMonkey** [comment]
Yeah but Like i Said the CSS ist missing of quilljs. Check how to include
the quill Core and quill snow Theme CSS into this Tech stack. In General
You can follow the instructions in the readme. Maybe there is another
approach to load global Styles with the mean stack

phenric <notifications@github.com> schrieb am So., 14. Juli 2019, 14:48:

**Comment by KillerCodeMonkey** [comment]
please check the demo repo and the readme https://github.com/KillerCodeMonkey/ngx-quill#installation step.

And if it is special mean stack question try stackoverflow. ;)

In general if you are not using server side rendering, just add quill stylings to the angular.json (if you ae angular cli) or configure your build process in that way, that your vendor css is build and included as well.

But in generel it is enough to use css import of the css-file like it is mentioned in the readme.

An example using angular-cli and config via angular.json can be found in the demo repo.

There the styling is working ;)

**Comment by phenric** [comment]
Hi thx for your reply.
I resolved this issue by loading the styles with cdn in the HTML page of my MEAN project.
