### ISSUE TITLE
Add output for editor-changed event

### ISSUE THREAD

**Issue by fredgate** [KillerCodeMonkey/ngx-quill#441]
This is not a bug, but a feature request.
Like for the `text-change` and `selection-change` events, the component could have an output for the `editor-change` event.
See : https://quilljs.com/docs/api/#editor-change

**Comment by KillerCodeMonkey** [comment]
Yeah i thought about IT, but i find IT a little Bit redundant, because of
the two other Events.

Frédéric Barrière <notifications@github.com> schrieb am Sa., 13. Juli 2019,
18:27:

**Comment by KillerCodeMonkey** [comment]
part of 7.1.0
