### ISSUE TITLE
Loss of line breaks during initialization in Material Stepper

### ISSUE THREAD

**Issue by dintecom** [KillerCodeMonkey/ngx-quill#446]
I use the quill editor inside **mat-horizontal-stepper** with **reactive forms**.
Starting from version **6.2.0**, line breaks began to disappear when the component is loaded.
I set the form group control to `<p>line 1</p><p>line 2</p>` , and the quill yields the html
`<p>line 1line 2</p>`.
See the stackblitz example: https://stackblitz.com/edit/angular-aau2dz

**Comment by KillerCodeMonkey** [comment]
But it is working without material wrappers. So i would check material
functionaly first. ;)

Dintecom <notifications@github.com> schrieb am Mo., 15. Juli 2019, 15:07:

**Comment by dintecom** [comment]
It just started in version 6.2.0. As far as I understand, after transferring initialization from AfterViewInit to AfterContentInit (https://github.com/KillerCodeMonkey/ngx-quill/commit/1aa2ec72aa98b2834c0113802a9e1e11148f0baf).
Please tell me how `<p>line 1</p><p>line 2</p>` turns into `<p>line 1line 2</p>` so that I would understand where to look for the problem?

**Comment by KillerCodeMonkey** [comment]
strange.. i will check that. maybe the mat-components are doing some strange things? I need to use ngAfterContentInit, to avoid change detection errors, if there are model/control changes during initialisation.

**Comment by KillerCodeMonkey** [comment]
it is working if you add the editor after the view is init:
https://stackblitz.com/edit/angular-nzmt9n

Maybe the material stepper is using projection, too and there is some magic happen?

**Comment by shubham1501** [comment]
I am also facing the same issue...tried the above solution...but still not working.

**Comment by KillerCodeMonkey** [comment]
but then you have a different problem, because it is working in my stackblitz ;)

**Comment by shubham1501** [comment]
yeah...it is working there...let me check my code again

**Comment by KillerCodeMonkey** [comment]
and try v7.1.0

**Comment by shubham1501** [comment]
okay...

**Comment by dintecom** [comment]
Thanks a lot, version 7.1.0 works fine!
