### ISSUE TITLE
FormArray change not detected on insertEmbed

### ISSUE THREAD

**Issue by TolotraRam** [KillerCodeMonkey/ngx-quill#448]
Hi great works !

So i use Reactive Form with formArray to bind to a ngx-quill component and when i editor.insertEmbed (or editor.insertText) the view is update but i doesn't trigger formArray.valueChange() so the control inside formArray doesn't update the value.
PS : It work since i use ngx-quill@4.3.0 but doesn't on version 4.4.0 and above. 

Cheers

**Comment by KillerCodeMonkey** [comment]
so you have some code for me?

**Comment by KillerCodeMonkey** [comment]
and btw. do you pass the source "source" to you insertEmbed or inertText calls?
per definition formcontrols/models are only updated when the user change it.
So you have to pass the quill-source "user" as last argument of this function calls.

checkout readme about "trackAllChanges" option ;)

**Comment by TolotraRam** [comment]
Sorry no repo yet, try to make one.
BTW didn't pass the source will try it and get you back.
Thanks

**Comment by KillerCodeMonkey** [comment]
https://quilljs.com/docs/api/#inserttext
https://quilljs.com/docs/api/#insertembed

check the source parameter.

Per default ngx-quill only updates models/controls if the source is "user". so you could pass "user" s source or you set the `trackChanges` property of ngx-quills quill-editor component to `all`

**Comment by KillerCodeMonkey** [comment]
any update?

**Comment by TolotraRam** [comment]
Yes you are right, set 'user' as source track the changes, anyway why on version 4.3.0 i didn't set it but it always trach the changes ?

**Comment by KillerCodeMonkey** [comment]
Because of Changed in a later Version ;)

Tolotra Ramahatoraka <notifications@github.com> schrieb am Di., 16. Juli
2019, 14:57:

**Comment by TolotraRam** [comment]
Thx you are awesome !!!
