### ISSUE TITLE
Ability to add custom toolbar options through quill-editor-toolbar to existing toolbar

### ISSUE THREAD

**Issue by sharath1608** [KillerCodeMonkey/ngx-quill#45]
I'm trying to add additional options to the toolbar which contains syntax highlighting option. In other words, something like this does not work

```
<quill-editor [(ngModel)]="title"
              [maxLength]="5"
              [minLength]="3"
              [required]="true"
              [modules]="{syntax:true,toolbar: [['code-block']]}"
              (onContentChanged)="onContentChanged($event);">

  <div quill-editor-toolbar>
    <span class="ql-formats">
      <button class="btn-primary">save</button>
    </span>
  </div>

</quill-editor>
```

Is there a workaround for something like this?

**Comment by KillerCodeMonkey** [comment]
Hey there!

You can find an example to use a custom toolbar here:
https://killercodemonkey.github.io/ngx-quill-example/

The last editor on this page is a custom toolbar with a custom word counter module.

You can find the source code here:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app.component.ts

**Comment by KillerCodeMonkey** [comment]
any updates?
