### ISSUE TITLE
ngOnChanges bug with angular's virtual scroll.

### ISSUE THREAD

**Issue by itsUndefined** [KillerCodeMonkey/ngx-quill#451]
When using a quill-view inside a virtual scroll (with or without) caching the browser flickers and does not scroll properly. It probably has something to do with the fact that quill's setContent is not completely synchronous and does not finish before angular checks for changes.

**Comment by itsUndefined** [comment]
The problem is solved by completely destroying and using a new quill-view everytime the content changes by using a setTimeout with 0ms time but that is not a complete solution for every part of the application since there is a small flicker where the component is completely removed. Also it makes the component not work with a virtual scroll with dynamic height items since I have to set a constant height in order for the item not to collapse when the quill-view get's removed from the DOM for a millisecond.

**Comment by KillerCodeMonkey** [comment]
But i think i can not Change that

itsUndefined <notifications@github.com> schrieb am Mi., 17. Juli 2019,
18:25:

**Comment by itsUndefined** [comment]
Alright I'll try to investigate the quill project itself for a possible workaround

**Comment by KillerCodeMonkey** [comment]
Nice let me know If i Need to Change anything or Send an pr :)

itsUndefined <notifications@github.com> schrieb am Mi., 17. Juli 2019,
18:29:
