### ISSUE TITLE
Use of Mutation Events is deprecated. Use MutationObserver instead

### ISSUE THREAD

**Issue by emrade** [KillerCodeMonkey/ngx-quill#452]
I get the warning `'Use of Mutation Events is deprecated. Use MutationObserver instead'` in my console. Can i please know what that warning shows and how i can solve or stop it from showing?

**Comment by KillerCodeMonkey** [comment]
I do Not so any special with that. I think this comes  from angular or
quilljs.

Emmanuel Fache <notifications@github.com> schrieb am Mi., 17. Juli 2019,
18:53:

**Comment by KillerCodeMonkey** [comment]
https://github.com/quilljs/quill/issues/2030
https://github.com/quilljs/quill/issues/1768
