### ISSUE TITLE
Cannot get focus on IOS safari through onEditorCreated instance.

### ISSUE THREAD

**Issue by maddy2894** [KillerCodeMonkey/ngx-quill#453]
This issue looks similar to #86 but I guess that solution is outdated and it's not working as expected. It works perfectly in android and chrome browser but cannot get focus to the editor through the (onEditorCreated) output in IOS safari. Code as follows:

`onEditorCreated(quill) {`
  `  quill.setSelection(1);`
`}`

ngx-quill version - 7.1.0

**Comment by KillerCodeMonkey** [comment]
i think this is not a problem of ngx-quill.

https://github.com/quilljs/quill/issues/1871#issuecomment-386333940

**Comment by maddy2894** [comment]
Thank you for the quick response. None of the references provided above solved my issue.
