### ISSUE TITLE
TypeError when adding import quill

### ISSUE THREAD

**Issue by ggjersund** [KillerCodeMonkey/ngx-quill#458]
I'm trying to add a custom toolbar handler by importing `quill` as following in my core module:

```
import { Quill } from 'quill';
var toolbar = Quill.getModule('toolbar');
toolbar.addHandler('image', function() {
    console.log('Handler loaded');
});

@NgModule({
  imports: [
    BrowserModule,
    QuillModule.forRoot({
      modules: {
        toolbar: [
          ['bold', 'italic', 'underline', 'strike'],
          [{ 'size': ['small', false, 'large', 'huge'] }],
          [{ 'color': [] }, { 'background': [] }],
          [{ 'list': 'ordered'}, { 'list': 'bullet' }],
          [{ 'font': [] }],
          ['link', 'image', 'video'],
          ['clean']
        ]
      }
    }),
  ],
  exports: [
    BrowserModule,
    QuillModule,
  ],
  providers: []
})
export class CoreModule {
  constructor(@Optional() @SkipSelf() parentModule: CoreModule) {
    if (parentModule) {
      throw new Error('CoreModule is already loaded. Import it in the AppModule only');
    }
  }
}
```

I end up getting the error

```
TypeError: quill__WEBPACK_IMPORTED_MODULE_25__.Quill is undefined
```

Any idea how I can solve this?

**Comment by KillerCodeMonkey** [comment]
Add quill typings or try to import quill in this way

Import * as Quill from "quill"

Gjert Ingar Gjersund <notifications@github.com> schrieb am Fr., 19. Juli
2019, 23:27:

**Comment by ggjersund** [comment]
Tried `Import * as Quill from "quill"` without any luck. I'll try quill typings.

**Comment by ggjersund** [comment]
@KillerCodeMonkey Added quill typings, however there seems to be an issue referring to Quill before it is initalized by QuillModule. I can import in any sub module, however not in the core module.

Any suggestion on how I can add handlers that affect the global config?

**Comment by ggjersund** [comment]
I've found a possible reason for the error. Apparently @types/quill does not work with other than the `es2015` compilerOption. Angular requires `module: "esnext"` for the new lazy load import statement. So I have to use `import * as Quill from 'quill';` and dig out the `getModules()` function from this object.

**Comment by ggjersund** [comment]
@KillerCodeMonkey Issue solved. After reading through your repository code I found out how I can add handlers in the `forRoot()` configuration. I would suggest making a section about this in the docs, just to make it easier to figure out.

This is what adding custom handlers look like:

```
QuillModule.forRoot({
    modules: {
      toolbar: {
        container: [
            ['bold', 'italic', 'underline', 'strike'],
            [{ 'size': ['small', false, 'large', 'huge'] }],
            [{ 'color': [] }, { 'background': [] }],
            [{ 'list': 'ordered'}, { 'list': 'bullet' }],
            [{ 'font': [] }],
            ['link', 'image', 'video'],
            ['clean']
        ],
        handlers: {
            'image': function() { console.log('Handler loaded'); }
        }
    }
}
```
    }),

**Comment by KillerCodeMonkey** [comment]
Feel free to contribute and extend the readme section ;)

Gjert Ingar Gjersund <notifications@github.com> schrieb am Sa., 20. Juli
2019, 14:59:
