### ISSUE TITLE
Quill auto remove linebreak

### ISSUE THREAD

**Issue by huydau91** [KillerCodeMonkey/ngx-quill#459]
I have some content render from server like:
`<div>Sky Tour 2019 đánh dấu sự quay trở lại mạnh mẽ của Sơn Tùng M-TP,</div><div><br></div><div>ghi dấu bằng MV “Hãy Trao Cho Anh” ra mắt ngày 1/7</div>`

But when I see on Quill editor, `<div><br></div>` was removed.

Here is my code:
```
import { QuillEditorComponent } from 'ngx-quill';

@ViewChild('editor') editor: QuillEditorComponent;

this.editor.modules = {
      clipboard: {
        matchVisual: true
      }
 }
```

How can I fix this? (keep the linebreak). Thanks!

**Comment by KillerCodeMonkey** [comment]
Please provide a Stackblitz to reproduce this Problem.



Dau The Huy <notifications@github.com> schrieb am Sa., 20. Juli 2019, 07:06:

**Comment by ggjersund** [comment]
Could it be related to 
```
@Input()
  valueGetter = (quillEditor: any, editorElement: HTMLElement): string | any  => {
    let html: string | null = editorElement.querySelector('.ql-editor')!.innerHTML
    if (html === '<p><br></p>' || html === '<div><br><div>') {
      html = null
    }
```

at 161 in `quill-editor.component.ts`

**Comment by KillerCodeMonkey** [comment]
This is only to Check If the Editor is empty. IT does Not replace anything.
But If You do Not Pass any String quill automatically Inserts an empty
Block.

Gjert Ingar Gjersund <notifications@github.com> schrieb am Sa., 20. Juli
2019, 18:16:

**Comment by KillerCodeMonkey** [comment]
btw matchVisual will not work ;). if you want to preserve whitespaces, there is an preserWhitespace property - using a pre-tag as editor wrapper.

In general if such problems occur i recommend not using the html-format.

Use json or object and store the json operation string in your database. it is easy to migrate or to patch or switch to another editor.

**Comment by KillerCodeMonkey** [comment]
btw @huydau91 do you use really div-tags as block elements or the default p-tags?

**Comment by huydau91** [comment]
> btw @huydau91 do you use really div-tags as block elements or the default p-tags?
Yeah. I used div-tags. Here is the way I change tag:

```
const Parchment = Quill.import('parchment');
const Block = Parchment.query('block');
Block.tagName = 'DIV';
Quill.register(Block/, true);
```
I used Angular form, when I patchValue for form (has quill-editor: I had override a component to contain quill-editor for generic component):
```
<quill-editor id="{{editorName}}" #editor [style]="style" (onEditorCreated)="editorInit($event)" [formControl]="formControlData" (click)="parseTextToHtml($event)">

==>

<app-quill-editor [formControlData]="description"></app-quill-editor>
```
I still try to debug to fix this :(

**Comment by KillerCodeMonkey** [comment]
did you tried it without your wrapper component?

and could you share your component ts code?

**Comment by huydau91** [comment]
> did you tried it without your wrapper component?
> 
> and could you share your component ts code?

Yes, I tried without wrapper component (in my project) and it still happen (I try unwrapper quill-editor on stackblitz with version ngx-quill, quill I use in my project but it doesn't happen).
https://angular-csr8tf.stackblitz.io

**Comment by KillerCodeMonkey** [comment]
strange thing. :S. But then it seems like some project specific stuff?

**Comment by KillerCodeMonkey** [comment]
which ngx-quill version do you use?

**Comment by huydau91** [comment]
> strange thing. :S. But then it seems like some project specific stuff?

Yeah, I think it is project specific stuff.
I used:
"ngx-quill": "^3.6.0",
"quill": "^1.3.6"

**Comment by KillerCodeMonkey** [comment]
wow, are you able to update your ngx-quill version to the latest one?

**Comment by huydau91** [comment]
> wow, are you able to update your ngx-quill version to the latest one?

I use angular v6 (6.0.5), so I should use ngx-quill >= 3.0.0 right? I think it is specific stuff like you said. 😢

**Comment by KillerCodeMonkey** [comment]
the thing is i fixed many things until the latest release.

Maybe you get the latest release working with angular 6. Just try it

**Comment by erichideyuki** [comment]
Stackblitz reproducing the problem: https://stackblitz.com/edit/ngx-quill-line-break-bug

**Comment by BH-M87** [comment]
I met the same problem, `<div><br></div>` was removed.
