### ISSUE TITLE
Responsive Toolbar Collapse

### ISSUE THREAD

**Issue by jacobbutton** [KillerCodeMonkey/ngx-quill#46]
Feature Request

It would be nice if we could collapse the toolbar under a hamburger button to not take up so much room on small screens.

**Comment by KillerCodeMonkey** [comment]
This is more or less capsulated of this angular implementation of quilljs. It is more the requests for another theme or a responsive bubble/snow theme ;).
https://quilljs.com/docs/themes/

This will not be done here.
