### ISSUE TITLE
how to set id to an editor

### ISSUE THREAD

**Issue by sudoStatus200** [KillerCodeMonkey/ngx-quill#460]
Hi,
I want to create multiple editors dynamically(by a ngfor loop) and get value from editor and their index position.
I can't figure out how to do this. Simply adding id attribute does not work.
Thanks,

**Comment by KillerCodeMonkey** [comment]
Just Pass the Index of the Loop to the Editor Output handlers

Like:

<Quill-editor (onEditorCreated)="handleCreated($event, index)">

In the Same way You can do this for the other Outputs onContentChanged,
onSelectionChangend and so on

Rahul singh mawari <notifications@github.com> schrieb am So., 21. Juli
2019, 01:20:

**Comment by sudoStatus200** [comment]
Thanks, I missed very simple thing :(
I just added (keyup)="get($event,i)"


I am stylling editor with like this:
[styles]="{backgroundColor:backgroundColor} "
in ts:
 backgroundColor = 'rgb(255, 0, 0)'

But it's not effecting. Am i missing anythin? I saw this from reactive-form example of ngx-quill

**Comment by sudoStatus200** [comment]
Ok thanks for help :)
I was changing style using class .ql-editor{} in style.css  , that's why inline styling was not working. I removed that from style.css,  now changes are effected.
