### ISSUE TITLE
Addig link in toolbar is not working as requirred.

### ISSUE THREAD

**Issue by sudoStatus200** [KillerCodeMonkey/ngx-quill#462]
Hi ,
 I am trying to add a link to a word and create an hyperlink but it's not working.
This workig fine:
![link2](https://user-images.githubusercontent.com/51601150/61609607-437d9c00-ac74-11e9-88de-64de6b9291ba.gif)

I want this work too:
![link1](https://user-images.githubusercontent.com/51601150/61609643-5e501080-ac74-11e9-831a-e708a30c20e6.gif)

Thanks,

**Comment by KillerCodeMonkey** [comment]
please ask this in the quilljs repository :).
This is only the angular wrapper for it.

In general you need to create a custom module/format for it.
Checkout how quilljs implements the link module/format and extend it.
