### ISSUE TITLE
Format update not applied everywhere - ngModel

### ISSUE THREAD

**Issue by Yexan** [KillerCodeMonkey/ngx-quill#471]
Hi Bengt :) 

In my project I have a page with multiple `quill-view` to display some text layers and an instance of a `quill-editor` with a custom toolbar.

When I click on a `quill-view` the `quill-editor` is set at the same place with same content and styles (with an higher z-index), I use ngModel binding to the same object.
When I use the classic select for font / font sizes, etc. everything works correctly, the data is well shared and updated in both editor and standalone view.

So now let's come to the issue. :) 
I've added some custom buttons like `+` and `-` buttons to increase and decrease font-size using the `quill.format` to update the selection size. 
It works in the editor but the changes are not applied in the `quill-view`.
Note : If I change the size with this buttons then modify the text even add a space and remove it, my font-size changes will be well applied in the `quill-view`

Here is a visual exemple to help you understand what happen :

![2019-07-29 10 33 47](https://user-images.githubusercontent.com/5166810/62033514-6ec03800-b1ec-11e9-8d0f-e26ff2b31894.gif)

Have you a lead to share with me why the ngModel is not updated everywhere on manual update of the content with quill format ?

**Comment by KillerCodeMonkey** [comment]
huhu, i think you are not passing source "user" for your changes in your custom buttons.

per default models and controls in angular should only update on user interactions, so quill-editor listens only on quill source "user".

Or you can set the `trackChanges` property of the editor to "all"

**Comment by Yexan** [comment]
Sweet ! 
Thanks a lot, yeah if anyone wants more info about that it come from https://quilljs.com/docs/api/#format 
Source parameter is actually optional and set to `api` by default.

Thanks for your quick feedback ! 

If only quillJs lib was that well maintained !
I opened an issue there about line-height formatting last week, no answer yet.
It's not relative to angular but if you have to minutes to get an eye on it I post the link here :) 
https://github.com/quilljs/quill/issues/2697 

Have a nice day !

**Comment by KillerCodeMonkey** [comment]
no probs. And thanks
