### ISSUE TITLE
Can't customize line-height in custom toolbar

### ISSUE THREAD

**Issue by Yexan** [KillerCodeMonkey/ngx-quill#472]
Hi again Bengt :) 

I made a custom Attributor for line-height and try to increase and decrease when I click on a custom button.

I've open an issue on quillJS repo because it didn't worked on my angular environnement but it seems that when I do the exact same thing with plain quill it does actually work ! 
Here is working (quick) demo on plain quill https://codepen.io/Yexan/pen/ymgpOb 

Here is my original issue with more detailed code from my angular project https://github.com/quilljs/quill/issues/2697 

More infos : 
When I log `getCurrentFormat` every time I click on the button I got : 
- On plain quill : 
```javascript
{}
{line-height: "1.1"}
{line-height: "1.1"}
{line-height: "1.2"}
```
- on ngx-quill : 
```javascript
{align: "justify", size: "15px", font: "monospace"}
{align: "justify", size: "15px", font: "monospace"} 
{align: "justify", size: "15px", font: "monospace"}
```
As you can see it does not change 

Have you some ideas / leads to share with me ?

**Comment by KillerCodeMonkey** [comment]
and do you have a stackblitz example with ngx-quill for me?

**Comment by Yexan** [comment]
There you go : https://stackblitz.com/edit/angular-zif9vj?file=src%2Fapp%2Fconfig%2Fcustom-editor-actions.ts 
I haven't put any styles and all the features but you can see the issue

**Comment by KillerCodeMonkey** [comment]
check the logs: 

```
quill:toolbar

ignoring attaching to nonexistent format

increaseFontSize

HTMLButtonElement {tagName: "button", attributes: {…}, innerHTML: "+", nodeType: 1…}
```

i get this sometimes maybe there is something failing to register this formats?

**Comment by Yexan** [comment]
Oh man, I found why it didn't worked ...
```typescript
const lineHeightConfig = {
  scope: Parchment.Scope.BLOCK,
  whitelist: AvailableLineHeights
}
```
`AvailableLineHeights` is an array of numbers not strings.
I just had to replace the map to stringify the value .. 
```typescript
export const AvailableLineHeights = [
  ...Array(110).keys()
].map(
  (x) => `${(80 + x * 5) / 100}`
)
```

**Comment by Yexan** [comment]
Thanks for your investigation on my issue !
I hope the exemple can help someone who try to set custom buttons and attributors :) 
Have a nice day

**Comment by KillerCodeMonkey** [comment]
nice! Thanks for the wonderful examples, issues and solutions :)
