### ISSUE TITLE
editor adds space at the end up text

### ISSUE THREAD

**Issue by MrSnappingTurtle** [KillerCodeMonkey/ngx-quill#473]
I've switched from a regular `textarea` to using `ngx-quill`. However, I've noticed that an extra space (` `) started being added to the end of the value. I'm using the HTML type.

**Comment by MrSnappingTurtle** [comment]
Please let me know if this is something that a stackblitz would be needed for.

**Comment by KillerCodeMonkey** [comment]
Is IT really a space or a New Line. If i remember IT correctly quilljs adds
an empty newline.

Stackblitz would be nice or can You reproduce IT in my live Demo (linked in
the readme) ?

Dennis Subachev <notifications@github.com> schrieb am Di., 30. Juli 2019,
00:37:

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
blubb ?

**Comment by MrSnappingTurtle** [comment]
My bad, missed the notifications. I'll try to see if I can get something on Friday.

**Comment by MrSnappingTurtle** [comment]
Sorry, got stuck with issues at work today. New reproducible ETA is Monday.

**Comment by MrSnappingTurtle** [comment]
I tried playing with a StackBlitz but was unable to replicate it. Might have something to do with the fact I've stuck the RTE into an Angular Material form field or how protractor reads from the page. I'll close the issue and will reopen if I'm able to reproduce at a later time. Thanks.

**Comment by KillerCodeMonkey** [comment]
The Problem occurs in a protractor Test? If you only read the Text content,
quill adds new Line per Default at the end. In HTML it is a p Tag with a br.

If you only get the text it is also a New Line. Check my unit tests. There
are some for "Text" content. There im using Multiline Strings to handle
them :)

Dennis Subachev <notifications@github.com> schrieb am Di., 6. Aug. 2019,
00:20:

**Comment by MrSnappingTurtle** [comment]
Ahh, that must be it. Thank you for pointing me towards the tests! 🙏
