### ISSUE TITLE
can't paste new text

### ISSUE THREAD

**Issue by sudoStatus200** [KillerCodeMonkey/ngx-quill#475]
Hi,

I am using ngx-quill like this 
`                    <quill-editor [modules]="editor_modules" (keyup)="getPre($event,i)" [(ngModel)]="movie.pre_text" [styles]="{backgroundColor:'white'}">
`

I want add more text by pasting the text.
But i am facing the bug here. Idk its problem with library or with my implementation.

Here is gif:

Here i am tring to go into next line by typing enter to paste my text, but i cant do that

![link0](https://user-images.githubusercontent.com/51601150/62283056-55c6b980-b46e-11e9-93d1-daa1470e0cdf.gif)

Here I am was able be to go to next line but when paste my text. Editor gets empty on by own.

![link45](https://user-images.githubusercontent.com/51601150/62283108-7262f180-b46e-11e9-93c5-5468f9ae02af.gif)

I can't understant why its happening .

Thanks,

**Comment by sudoStatus200** [comment]
@KillerCodeMonkey

**Comment by KillerCodeMonkey** [comment]
You have a keyup listener there. What does IT?


If You can Not reproduce it, then it is a Problem in your Implementation ;)

Rahul singh mawari <notifications@github.com> schrieb am Do., 1. Aug. 2019,
11:42:

**Comment by sudoStatus200** [comment]
that keyup listener takes the everychanges using that $event argument.
@KillerCodeMonkey

**Comment by KillerCodeMonkey** [comment]
Could You share the Code of the function. In General You should Listen on
the "onContentChanged" Event provided by the component.

Or using "ngModelChange".

I think your keyup listener does Something Strange. Because there is No
issue pasting or editing the content in my demo App

Rahul singh mawari <notifications@github.com> schrieb am Do., 1. Aug. 2019,
16:54:

**Comment by sudoStatus200** [comment]
Hi,
Thanks for quick reply.
keyup function:
` getPre(e, i) {

    console.log(i)

    this.updateMovies[i].pre_text = e.target.innerHTML
    console.log(this.updateMovies)
  }`

**Comment by sudoStatus200** [comment]
Note:I am creating multiple editors with the help of ngFor

**Comment by KillerCodeMonkey** [comment]
But You are Sure You understand how angular Forms and ngModel works? There
is no Need to Set the content in your model manually in keyup.

Thats what ngModel does for You.

In your Case the quill Editor Changes the value on the Model and You are
changing the Model value on your own again.

So there is No Need for your keyup listener


Rahul singh mawari <notifications@github.com> schrieb am Do., 1. Aug. 2019,
17:15:

**Comment by sudoStatus200** [comment]
ok , thanks.
Actually , i am new to angular though ngModel is very basic in angular I should have known it:(

**Comment by KillerCodeMonkey** [comment]
No Probs. IT was only a hint :)

Rahul singh mawari <notifications@github.com> schrieb am Do., 1. Aug. 2019,
17:34:

**Comment by KillerCodeMonkey** [comment]
did you solved it?

**Comment by sudoStatus200** [comment]
@KillerCodeMonkey  yes, i was just waiting for it to go to live and if everything works fine their too.
