### ISSUE TITLE
customToolbarPosition="bottom" doesn't work

### ISSUE THREAD

**Issue by ThomasLohmann** [KillerCodeMonkey/ngx-quill#478]
Hi everyone, the customToolbarPosition="bottom" property doesn't work. Any idea why?

Here is my code: 

`
  <quill-editor placeholder="Text" customToolbarPosition="bottom" [modules]="quillConfig" formControlName="text">
  </quill-editor>
`

**Comment by KillerCodeMonkey** [comment]
Like it is written in the readme h customToolbarPosition Takes only affect
when You are using a custom html toolbar ;)

The Default quilljs toolbar can Not bei positionated.

ThomasLohmann <notifications@github.com> schrieb am Sa., 3. Aug. 2019,
13:36:

**Comment by ThomasLohmann** [comment]
@KillerCodeMonkey thanks for your quick feedback! So in other words, I have to do something like in this stackblitz example? https://stackblitz.com/edit/ngx-quill

**Comment by KillerCodeMonkey** [comment]
Yep or create your try to positionate the toolbar with CSS, e.g. flexbox du
Switch toolbar and Editor positions :)

ThomasLohmann <notifications@github.com> schrieb am Sa., 3. Aug. 2019,
14:10:

**Comment by jtomek** [comment]
This worked for me: 

```
quill-editor {
  display: flex;
  flex-direction: column-reverse;
}
```

**Comment by Santoshah** [comment]
I used this below css to make it upside down.

![image](https://user-images.githubusercontent.com/3863771/122537914-af750480-d043-11eb-9544-08dd3cb13944.png)


`.quill_editor {
  quill-editor {
    display: flex;
    flex-direction: column;
    .ql-editor.ql-blank::before {
      font-size: 14px;
      font-style: normal;
      color: $icons !important;
    }
    .ql-container .ql-editor {
      min-height: 120px;
      max-height: 120px;
      height: 120px;
    }
    .ql-snow .ql-picker.ql-expanded .ql-picker-options {
      display: block;
      margin-top: -1px;
      top: 100%;
      z-index: 1;
      top: auto;
      bottom: 100%;
    }
    .ql-snow + .ql-container.ql-snow {
      border: 1px solid $border;
      border-bottom: 0;
    }
    .ql-container {
      border-radius: 6px 6px 0 0;
      border-color: $border;
    }
    .ql-toolbar {
      order: 2;
      border-radius: 0 0 6px 6px;
    }
  }
}`

**Comment by soctrip** [comment]
**dss

'as
- sa
-**
