### ISSUE TITLE
Integration with module: mathquill4quill

### ISSUE THREAD

**Issue by leonelngande** [KillerCodeMonkey/ngx-quill#484]
@KillerCodeMonkey 

Would like to integrate [https://github.com/c-w/mathquill4quill](https://github.com/c-w/mathquill4quill) for easier math typing. 
Can this integration be done within ngx-quill (asking for your opinion) or instead I do a custom integration for what am working on..?

Am ok working on a pull request.

**Comment by leonelngande** [comment]
Just discovered MathQuill depends on jQuery [http://docs.mathquill.com/en/latest/Getting_Started/](http://docs.mathquill.com/en/latest/Getting_Started/) which might be a deal breaker for some people (me included). So closing the issue.

**Comment by KillerCodeMonkey** [comment]
I think there is already a formula Plugin / Format for quilljs using katex.

Leonel Elimpe <notifications@github.com> schrieb am Fr., 9. Aug. 2019,
11:56:

**Comment by leonelngande** [comment]
Yea have the formula format integrated, though was looking more into something where users don't have to learn to write katex, can just click on buttons (maybe) to insert the symbols. Still looking into it.

**Comment by KillerCodeMonkey** [comment]
And in general You can use every quill Module. Register it in quill, load
possible thirdparty requirements and Pass the Module to the ngx-quill
modules property

Leonel Elimpe <notifications@github.com> schrieb am Fr., 9. Aug. 2019,
12:18:

**Comment by leonelngande** [comment]
Ok @KillerCodeMonkey , thanks.
