### ISSUE TITLE
Punjabi Language issue

### ISSUE THREAD

**Issue by agrimsekhri** [KillerCodeMonkey/ngx-quill#487]
When copy pasting punjabi test in editor and pressing enter gives a below mentioned error.
DOMException: Failed to execute 'setStart' on 'Range': The offset 158 is larger than the node's length (156).

**Comment by KillerCodeMonkey** [comment]
Please Check If this issue also appears in native quilljs Editor .

I think this is Not an ngx-quill issue. More a quilljs issue

agrimsekhri <notifications@github.com> schrieb am Di., 13. Aug. 2019, 09:49:
