### ISSUE TITLE
Cannot disable saniatze using html format

### ISSUE THREAD

**Issue by Tsogodar** [KillerCodeMonkey/ngx-quill#493]
Hey

Is any way to disable html sanitazing for HTML tags such as <script>?

When i paste 
`<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>`
 ngModel get 
`<p>&lt;script src="https://code.jquery.com/jquery-3.4.1.min.js"&gt;&lt;/script&gt;</p>`
but I need send value with '<' and '>' symbols.

Set sanitaze to false in quill-editor do nothing. It is possible to do that without register custom format?

[Demo link](https://stackblitz.com/edit/angular-jkfcjo)

In my project I can't use any kind of angular safe pipe

**Comment by KillerCodeMonkey** [comment]
this hast nothing todo with sanitation. i think quilljs will not allow to paste scripttags in an editor where it is only allowed to insert styled content... it is a wysiwyg editor and not an editor to create page templates or inject whole script tags.

ask or search through the quilljs repo if it is possible to edit the "code" of the content. but this will not work.

As a possible solution: create a custom blob or format where you can paste in script tags
