### ISSUE TITLE
Don't set font-size

### ISSUE THREAD

**Issue by lellelskii** [KillerCodeMonkey/ngx-quill#497]
After upgrading ngx-quill to version 5.2.0, you cannot set the font-size in the old way.
```
<quill-editor
  [style]="styles"
</quill-editor>

public styles = {
    'font-size': '2rem'
 }
```
Tell me how to solve it. Thanks.

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/releases/tag/5.0.0

**Comment by lellelskii** [comment]
Thanks. It's worked.
