### ISSUE TITLE
Does this replace ng2-Quill?

### ISSUE THREAD

**Issue by rodneyjoyce** [KillerCodeMonkey/ngx-quill#5]
Hi,

I noticed another similar project (https://www.npmjs.com/package/ng2-quill   "ng2-quill": "0.0.6",) but this one looks more recent - I assume ngx is the latest for ng2? 

Thanks

**Comment by KillerCodeMonkey** [comment]
yep, i added a deprecated info and link to this repo, if you install ng2-quill ;)

the angular team changed their versioning, so there will be a angular 3 and 4 very soon.
So here is ngx ^^
