### ISSUE TITLE
Build Error 1.3.3

### ISSUE THREAD

**Issue by tonyhayes** [KillerCodeMonkey/ngx-quill#50]
I dialed back to 1.3.1 and everything is fine, so I'm thinking there might be an issue with a later release. (fyi ... I am not an AoT user)

node error;
build	06-Jul-2017 15:55:14	ERROR in [at-loader] ./node_modules/ngx-quill/src/quill-editor.component.ts:109:7 
build	06-Jul-2017 15:55:14	    TS2345: Argument of type '{ modules: any; placeholder: string; readOnly: boolean; theme: string; formats: string[]; bounds:...' is not assignable to parameter of type 'QuillOptionsStatic'.
build	06-Jul-2017 15:55:14	  Object literal may only specify known properties, and 'bounds' does not exist in type 'QuillOptionsStatic'.

**Comment by KillerCodeMonkey** [comment]
you have to check your installed @types/quill version --> it should be 0.0.31 i think. < 0.0.31 the bounds property was not there.

My tests are working, so it should be fine

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by tonyhayes** [comment]
Sorry. I dialed back to 1.3.1. If I were to guess, the error has something to do with NPM. If your latest on GitHub works, and the latest I got from my npm download didn’t - that might be something to look into.

My package file had the following;

> “nix-quill”: “^1.2.0”

so it would have downloaded the latest major version - which is your 1.3.3, but maybe not if your npm was pointing to a different repo (?). I don’t know how that part works.

**Comment by KillerCodeMonkey** [comment]
oh i forgot to push the tags

**Comment by tonyhayes** [comment]
i can run an update - this afternoon. I'll let you know.

Good work!

**Comment by tonyhayes** [comment]
I think you may have been referring to the types for quill previously - I didn't understand  - I did have 0.0.29 - but have just changed it to 0.0.31.

"@types/quill": "0.0.31",

**Comment by KillerCodeMonkey** [comment]
close the issue if it working for you

**Comment by tonyhayes** [comment]
it builds!

**Comment by tonyhayes** [comment]
.
