### ISSUE TITLE
New lines are not preserved when using format = 'text'.

### ISSUE THREAD

**Issue by swapnilp0x00** [KillerCodeMonkey/ngx-quill#500]
In my Application, I want to give user an option to switch between `html` and `text` format.

When I am using `html` format,  all the `\n` are converted to `<p><br></p>`
When I am in `text` mode. It actually stores `\n` also in value.
But when user adds `\n` in text mode and when he switches to `html` mode and edit something all `\n` is being lost.

**Comment by KillerCodeMonkey** [comment]
could you check, if this also happens with plain quilljs?

**Comment by swapnilp0x00** [comment]
quillJS doceumentation hasnt mentioned anything about  changing input mode. I guess it operates only in only in `html` mode.
 
https://stackblitz.com/edit/ngx-quill-xpcnhw?file=src/app/services/quillInitialize.service.ts

There is `[source]` button in toolbar to change the mode. On clicking i am toggling `this.format` variable which is given as `[format]` to quill-component.

Steps -
1. Initially, it is in HTML mode. you'll see two lines one after another in editor `ABC` and `XYZ`
2. Click source. format will be changed to TEXT and you can see and edit HTML code with two **p** tags with three `\n` between them. (All is good till here).
4. Click the source again. You'll be switched to HTML mode again. Make any change in this mode and at this point, all the `\n` added in TEXT mode are gone.
5. Now if you switch to TEXT mode and see both the p tags are on the same line and those three `\n` are gone.

**Comment by KillerCodeMonkey** [comment]
okay, i never intended that this will work, but in general you could check what happens, when you call:

```quill.clipboard.convert(content)```

that is what quill use to transform content to html, and that is what i am doing.

So when you paste in a string with `\n` what it is transformed in.

**Comment by KillerCodeMonkey** [comment]
Any updates?

**Comment by KillerCodeMonkey** [comment]
any?
