### ISSUE TITLE
clipboard convert function change 

### ISSUE THREAD

**Issue by jefjef** [KillerCodeMonkey/ngx-quill#502]
clipboard.convert gets called by ngx-quill with just the raw html text while in the newer quill it should be passed along with the text format. 

see [quill change commit](https://github.com/quilljs/quill/commit/0eb507e23f83416a04ca8924af668cf2f2a9817d)

**Comment by KillerCodeMonkey** [comment]
does this result in any bug?

If you are using format html, i do not know the text representation ;-)

**Comment by jefjef** [comment]
Yes, we can no longer set the content of the field (when using html format), it just stays empty.
[line that gives the problem](https://github.com/KillerCodeMonkey/ngx-quill/blob/master/src/quill-editor.component.ts#L302)

note to say that we were on the 2.0.0-dev.3 version of quill. so not the 1.3.6 stable.

**Comment by KillerCodeMonkey** [comment]
so, i do not support dev builds of quilljs. Sorry. And you should not use unstable builds in your project ;-).

The qiull api is not final and fixed, so i will try support it, when it is in RC state.
If you need tables as feature of quill, just google for some thirdparty modules that extend quill in this way.

**Comment by jefjef** [comment]
Ok no problem, we'll figure something out, ty for your time 😃
