### ISSUE TITLE
I want to upload image to my own server

### ISSUE THREAD

**Issue by dds-du** [KillerCodeMonkey/ngx-quill#508]
I want to upload the image to my own server and set the uri to img tag's src after the server return it.What can I do?

**Comment by KillerCodeMonkey** [comment]
1. use google :D
2. use issue search in this repo and in the repo of quilljs
https://github.com/quilljs/quill/issues/1089
https://github.com/quilljs/quill/issues/1400

In general you have to implement your own `image handler` 
https://quilljs.com/docs/modules/toolbar/#handlers
