### ISSUE TITLE
upload image from url 

### ISSUE THREAD

**Issue by qinqing3761** [KillerCodeMonkey/ngx-quill#51]
How can I upload image from url ?now this only upload image from local.I want both.

**Comment by KillerCodeMonkey** [comment]
therefore you need another module or third party plugin. it is not provided not out the box of quill.

ngQuill is only a wrapper of quilljs, so if quilljs does not support it - ng-quill will not support it, too.

You need to add a custom imageHandler for the toolbar:
https://github.com/quilljs/quill/issues/893
