### ISSUE TITLE
QuillViewComponent and QuillViewHtmlComponent not working on production build.

### ISSUE THREAD

**Issue by lcharanteja** [KillerCodeMonkey/ngx-quill#512]
I am receiving below warnings when building for production.

```
WARNING in ./node_modules/ngx-quill/ngx-quill.ngfactory.js
27:235-256 "export 'QuillViewComponent' (imported as 'i1') was not found in 'ngx-quill'

WARNING in ./node_modules/ngx-quill/ngx-quill.ngfactory.js
28:70-91 "export 'QuillViewComponent' (imported as 'i1') was not found in 'ngx-quill'

WARNING in ./node_modules/ngx-quill/ngx-quill.ngfactory.js
34:251-276 "export 'QuillViewHTMLComponent' (imported as 'i1') was not found in 'ngx-quill'

WARNING in ./node_modules/ngx-quill/ngx-quill.ngfactory.js
35:79-104 "export 'QuillViewHTMLComponent' (imported as 'i1') was not found in 'ngx-quill'
```

Dependencies : 

> "ngx-quill": "^7.3.0",
> "quill": "^1.3.7",
> "@angular/core": "6.0.1",
> "@types/quill": "^1.3.10",

**Comment by KillerCodeMonkey** [comment]
Could you Checkout my example Repo linked in the readme . I am using ng cli
production builds there for the gh-page/live preview

Charan Teja <notifications@github.com> schrieb am Di., 10. Sep. 2019, 18:15:

**Comment by KillerCodeMonkey** [comment]
checkout:

https://killercodemonkey.github.io/ngx-quill-example/ 
https://github.com/KillerCodeMonkey/ngx-quill-example
