### ISSUE TITLE
Cursor moving to beginning of line

### ISSUE THREAD

**Issue by arifsundrani** [KillerCodeMonkey/ngx-quill#52]
![ngx-quilltest](https://user-images.githubusercontent.com/9058183/28430092-d4a3303a-6d44-11e7-8364-f543a21e13ed.gif)

As seen above, whenever I first initiate the quill editor (with a null, '', or database value), the cursor automatically moves to the front and starts placing characters in front of it. 

quill version: "ngx-quill": "^1.3.3" (I've confirmed that 1.33 is installed by using the npm list --depth=0 command

HTML: 
`<quill-editor formControlName="answer" (onEditorCreated)="setFocus($event)"></quill-editor>`

The setFocus method is the same as you have in your demo. 

Any insights as to why this is happening? If you need more information, please let me know.

**Comment by KillerCodeMonkey** [comment]
i will look into it next week

**Comment by KillerCodeMonkey** [comment]
seems like the default behavior of quilljs:
https://codepen.io/anon/pen/qXWegR

even without ngx-quill focus sets the cursor at the beginning.

**Comment by arifsundrani** [comment]
You're correct, and I should have clarified a bit further. The cursor moving to the beginning of the line isn't that big of a deal, but rather how the characters are being typed after the cursor (the characters are going to the right of the cursor as seen in the .gif above).

**Comment by KillerCodeMonkey** [comment]
yeah than show me your code,

seems not to be happening in my demo. I even changed it locally that the `focus()` function is called after a timeout.

**Comment by KillerCodeMonkey** [comment]
any updates or demo code?

**Comment by arifsundrani** [comment]
I am working on the demo code now. I am hoping to have a working example sometime next week.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by arifsundrani** [comment]
I have been working on the sample app, yet everything I've added to the sample app to mirror the actual app has been working in that the cursor and character placement is correct. I am going to close this issue for now and re-open or create a new issue if the bug is reproducible within the sample app.

**Comment by arifsundrani** [comment]
I was finally able to reproduce the issue. A translate directive on the div surrounding the quill-editor tag was causing the cursor to move to the beginning. The translation library used: [angular-l10n](https://github.com/robisim74/angular-l10n).

**Comment by KillerCodeMonkey** [comment]
Ah okay.i think this is a general quilljs problem. There was something similar with a chrome translation/spelling check plugin.

Could you check this and add quilljs directly instead of using ngx-quill?

**Comment by caendekerk** [comment]
Hi,
i`m having a very similar Problem that the Cursor jumps to the beginning of the line during Angulars NGModel change detection/synchronization. 

The setup with 

`<form>
    <div class="form-group">
      <label for="notes">Campaign Info</label>
      <div class="campaign-info-editor form-control">
        <quill-editor
          #campaignInfoForm="ngModel"
          [(ngModel)]="campaign.info.notes"
          [disabled]="!campaign.id"
          [modules]="quillModules.minimal"
          name="info">
        </quill-editor>
      </div>
    </div>
  </form>`

and 

`constructor(@Inject(QUILL_MODULES) public quillModules) {}

  ngAfterViewInit() {
    if (this.campaignInfoForm) {
      this.changeSubscription = this.campaignInfoForm.valueChanges.debounceTime(1000).distinctUntilChanged().subscribe(() => {
        if (this.campaignInfoForm.dirty) {
          this.submit.emit(this.campaign);
        }
      });
    }
  }`

is actually quite vanilla.

**Comment by MHillier98** [comment]
@caendekerk did you ever find a fix for this? I'm encountering the same issue with ngModel.

**Comment by mlittrell** [comment]
Yeah having the same issue. The example provided by @caendekerk should be adequate to reproduce this. There's seems to be a way around this with the answer here: https://stackoverflow.com/questions/48678236/setting-the-cursor-position-after-setting-a-new-delta-in-quill, however I wouldn't consider this the most elegant way to handle this issue.

**Comment by jsdevtom** [comment]
@MHillier98 Could it be that your form's `valueChanges` is being listened to and the form's value being set again? E.g.  `formValue` => `model` => `formValue`.

**Comment by awais2080** [comment]
> @MHillier98 Could it be that your form's `valueChanges` is being listened to and the form's value being set again? E.g. `formValue` => `model` => `formValue`.

i have same problem and you are saying exactly right how to resolve this issue.

**Comment by awais2080** [comment]
@KillerCodeMonkey  dear how to solve this problem any solution any body let me know. basically i am using formcontrol

**Comment by MHillier98** [comment]
@awais2080 been forever since I thought about this, but I just looked back at what I did (back in July 2018). @jsdevtom mentioned the same solution as what I ended up doing.

**Comment by awais2080** [comment]
i have also solved this problem making form control binding to ngModel binding and using the changing the value when formcontrol value is being changed. using formControlField.valueChanges you need to subscribe it.

 <quill-editor
    class="content-box"
    [placeholder]="label"
    [(ngModel)]="htmlField"
    [maxlength]="field.restrictions.maxLength"
    (keydown)="check($event)"
    (onContentChanged)="onChange(htmlField)"
  >
  </quill-editor>



 onFieldChanges(): void {
    this.field.valueChanges.subscribe((val) => {
      this.htmlField = val;
    });
  }

**Comment by OhEmQ** [comment]
> 

Could you elaborate on your solution? I am quite lost on it

**Comment by Banditellius** [comment]
Seems this issue is not resolved yet. There is no proper solution to fix the cursor moving to beginning. This is happening in the latest versions of the ng-quill-editor.
