### ISSUE TITLE
Enhancement: Provide a way to track changes in editor

### ISSUE THREAD

**Issue by anuragd7** [KillerCodeMonkey/ngx-quill#524]
Hi
Thanks for a great repo. I needed a way to be able to track changes made to the text in the editor.  I found a simple approach for the quill editor [here](https://codepen.io/percipient24/pen/eEBOjG) - would be great if you could provide a way to achieve something similar with ngx-quill.
Thanks

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill#outputs

just listen to the output you want:
onContentChanged, onEditorChanged or just grab the editor instance in the onEditorCreated output and call getContent ;-)

**Comment by anuragd7** [comment]
Thanks so much for your prompt response. Your suggestion worked very well.
