### ISSUE TITLE
Reset the quill editor

### ISSUE THREAD

**Issue by Fayde** [KillerCodeMonkey/ngx-quill#53]
I'm using angular 4 + reactive forms and bringing rich text in from my api.  On initialization the quill editor puts the rich text in exact how I want, but if I overwrite the initialized editor it will strip all my markup inside the opening p and closing /p tags.  How can I make every patchValue replace the editor body with exactly what I want it to from the api?

**Comment by Fayde** [comment]
I tried replacing p with div tags like in the demo but that didn't work either

**Comment by KillerCodeMonkey** [comment]
Could you show me the code, what you are trying to do?

**Comment by Fayde** [comment]
`// modal dialog that is initialized when a button is pressed in the parent 
<form novalidate [formGroup]="editForm">
  <div class="form-group">
    <label>Body:</label>
    <quill-editor #editor formControlName="body"></quill-editor>
  </div>
</form>

// associated typescript file
export class EditDialogComponent implements OnInit, OnChanges {

  @Input() visible: boolean;
  @Input() contentUuid: string;
  @Output() visibleChange: EventEmitter<boolean> = new EventEmitter<boolean>();

  
  editForm: FormGroup;
  // example string that would be brought in by our api for a content piece
  bodyString = '<p dir="ltr">Hitting the lake? Exploring a music festival in the countryside? Whatever direction you’re headed in this summer, you’re going to need something to keep you cool!</p>

<p dir="ltr">Stop by your local Co-op Gas Bar/Convenience Store and try our NEW Big Cools flavour, Fanta Strawberry Lemonade, available now for a limited time. Sweet with a hint of tartness, it’s the perfect treat to beat the heat! Big Cools are slushy and icy cold, the ultimate boost to help keep you rolling on down the highway.</p>

<p dir="ltr">Your local Co-op Gas Bar/Convenience Store is your one-stop shop for all your summer adventures!</p>';

  ngOnInit() {
    this.editForm = new FormGroup({
      body: new FormControl()
    });
  }
  
  // when the modal becomes visible
  // simplified example that excludes the api call and subscribe to the result
  ngOnChanges(changes) {
    if (changes.visible.currentValue) {
	  this.editForm.patchValue({ body: this.bodyString});
	}
  }
  
  // close button on the dialog
  close() {
    this.visible = false;
    this.visibleChange.emit(this.visible);
  }
  
}`

here's a simple bit that excludes a lot of the detail but really shows the base of the issue. On the initialization the string will place itself in the editor exactly as I want it to, but when I close to modal and want to reinitialize the form fields it will strip bodyString to be:

`<p>Hitting the lake? Exploring a music festival in the countryside? Whatever direction you’re headed in this summer, you’re going to need something to keep you cool!Stop by your local Co-op Gas Bar/Convenience Store and try our NEW Big Cools flavour, Fanta Strawberry Lemonade, available now for a limited time. Sweet with a hint of tartness, it’s the perfect treat to beat the heat! Big Cools are slushy and icy cold, the ultimate boost to help keep you rolling on down the highway.Your local Co-op Gas Bar/Convenience Store is your one-stop shop for all your summer adventures!</p>`

**Comment by KillerCodeMonkey** [comment]
I changed a little thing in the 1.3.4 version. Maybe this helps. in other cases i do not know, if this has something todo with ngx-quill or simply quill or if there is some sanatizing on angular side.

Maybe you can create an example repo or plunkr.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
... one chance or closed :D

**Comment by Fayde** [comment]
@KillerCodeMonkey it did not fix the issue sadly, I am working around it by destroying the rich text editor whenever I close the modal and recreating it for the proper initial patch value.  I can't easily recreate the situation in a demo due to time constraints on my part, so we can probably close this issue in that case

**Comment by KillerCodeMonkey** [comment]
could you build a code example, where i can check the problem?

**Comment by Fayde** [comment]
ok I finally found a way to reflect a simplified version of my issue at https://embed.plnkr.co/yKMacEbofofO5PVQHuAU/

If you press the button to put the string into the box then toggle visibility off then on, and try to place the string again it will do my described issue

**Comment by KillerCodeMonkey** [comment]
okay strange. Might it possible that you test a little thing for me?

Could you add a console.log to your node_modules and the ngx-quill editor component.
There is a function `writeValue`. this function gets called everytime the model or control changes.
https://github.com/KillerCodeMonkey/ngx-quill/blob/develop/src/quill-editor.component.ts#L162

there you can log the value passed from the control to the editor.
Maybe angular is doing something strange because of some security mechanisms or if `currentValue` is exactly what you want - `this.quillEditor.clipboard.convert` strips the additional p-tags or `this.quillEditor.setContents` does it.

If some of the quill functions is a problem --> it is a native QuillJS problem.

**Comment by Fayde** [comment]
it's very strange I can console logging currentValue in writeValue function and find that on the second load it runs writeValue twice, once is exactly how I want it then the second time is the bad value that strips the p tags out in the middle

**Comment by Fayde** [comment]
![curentvalue](https://user-images.githubusercontent.com/6588523/28988621-e0e020de-792d-11e7-9b4c-1a37f26791d9.PNG)

these two writeValue console logs happen in a row on second load

**Comment by KillerCodeMonkey** [comment]
i added an example to my example repo, where you can hide/show an editor and patch the value:
https://killercodemonkey.github.io/ngx-quill-example/

**Comment by pavithramaduranga** [comment]
```
         <quill-editor placeholder ="Long Description in English"
                              formControlName="LongDescriptionEn" 
                              [readOnly] = isReadOnly    
                              [style]="{height: '300px'}"></quill-editor>
```

Worked for me!

**Comment by seanmccaffery** [comment]
I'm experiencing this same issue of html appearing fine but then getting a stripped down version after edits to the form are made and I close the slider the quill-editor exists in.  I thought of destroying the quill-editor to fix this like @Fayde 's solution but the slider is toggled by an *ngIf so it should be getting destroyed already and rebuilt when the slider comes back up.  This isn't happening however.  

What is the proper way to destroy the quill-editor?  Thanks.
