### ISSUE TITLE
angular production build is not working

### ISSUE THREAD

**Issue by vinodpasupathy** [KillerCodeMonkey/ngx-quill#530]
ngx-quill is working in ng-serve but when switching to prod build it result in error.Production build is working when buildOptimizer parameter is turned to false results in increased build size.

`main.a5110ac1477fe8c49bcd.js:1 ERROR TypeError: Super expression must either be null or a function, not undefined
    at main.a5110ac1477fe8c49bcd.js:1
    at main.a5110ac1477fe8c49bcd.js:1
    at Object.BfSu.t.exports (main.a5110ac1477fe8c49bcd.js:1)
    at e (main.a5110ac1477fe8c49bcd.js:1)
    at Object.BfSu.t.exports (main.a5110ac1477fe8c49bcd.js:1)
    at e (main.a5110ac1477fe8c49bcd.js:1)
    at Object.BfSu.t.exports (main.a5110ac1477fe8c49bcd.js:1)
    at e (main.a5110ac1477fe8c49bcd.js:1)
    at Object.BfSu.t.exports (main.a5110ac1477fe8c49bcd.js:1)
    at e (main.a5110ac1477fe8c49bcd.js:1)
_s @ main.a5110ac1477fe8c49bcd.js:1`

**Comment by KillerCodeMonkey** [comment]
i need more information. an example repo would be nice.

**Comment by KillerCodeMonkey** [comment]
i think this is more an error in your project/build configuration.
I am using production builds for my example/demo repo and it is working fine ;).

https://github.com/KillerCodeMonkey/ngx-quill-example
https://killercodemonkey.github.io/ngx-quill-example/

**Comment by Yexan** [comment]
Hi, 

Check your `ng test` 
It might not be related to ngx-quill issue.
`ng serve` doesn't pass your test, try it before to build in production mode. 
If it's building remotely on a deploy environment, try to just `ng build` locally to have a better view of where it actually breaks.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by vinodpasupathy** [comment]
i can't able to replicate the error in example repo, when i created a new project quill is working in production even with build optimizer is set to true.but it is breaking in my project.may be i don't know any dependency is breaking.find my package.json below...

`"dependencies": {
    "@angular-devkit/schematics": "^8.0.1",
    "@angular-material-extensions/link-preview": "^1.1.1",
    "@angular/animations": "^8.0.3",
    "@angular/cdk": "^8.0.0",
    "@angular/cli": "^8.0.1",
    "@angular/common": "^8.0.3",
    "@angular/compiler": "^8.0.3",
    "@angular/core": "8.1.0",
    "@angular/forms": "^8.0.3",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.0.0",
    "@angular/material-moment-adapter": "^8.0.0",
    "@angular/platform-browser": "^8.0.3",
    "@angular/platform-browser-dynamic": "^8.0.3",
    "@angular/router": "^8.0.3",
    "@aws-amplify/auth": "^1.2.25",
    "@aws-amplify/storage": "^1.0.31",
    "@fortawesome/angular-fontawesome": "^0.4.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.19",
    "@fortawesome/free-brands-svg-icons": "^5.9.0",
    "@fortawesome/free-solid-svg-icons": "^5.9.0",
    "@ngrx/effects": "^8.0.1",
    "@ngrx/entity": "^8.0.1",
    "@ngrx/router-store": "^8.0.1",
    "@ngrx/store": "^8.0.1",
    "@ngu/carousel": "^1.5.5",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@swimlane/ngx-datatable": "^15.0.1",
    "add": "^2.0.6",
    "aws-amplify": "^1.1.29",
    "babel-polyfill": "^6.26.0",
    "backoff-rxjs": "^6.3.2",
    "core-js": "^3.1.3",
    "date-fns": "^2.0.0-alpha.16",
    "default-passive-events": "^1.0.10",
    "error-stack-parser": "^2.0.2",
    "exceljs": "^1.15.0",
    "file-saver": "^2.0.2",
    "hammerjs": "^2.0.8",
    "memoize": "^0.1.1",
    "moment": "^2.24.0",
    "ng-pick-datetime": "^7.0.0",
    "ng2-pdf-viewer": "^5.3.2",
    "ngx-device-detector": "^1.3.11",
    "ngx-feature-toggle": "^7.0.0",
    "ngx-logger": "^3.3.13",
    "ngx-permissions": "^6.0.6",
    "ngx-plyr": "^1.2.2",
    "ngx-print": "^1.1.4",
    "ngx-quill": "^6.1.0",
    "ngx-spinner": "^8.0.3",
    "paper": "^0.12.0",
    "plyr": "^3.5.6",
    "pouchdb-adapter-idb": "^7.0.0",
    "quill": "^1.3.7",
    "rxdb": "^8.4.0",
    "rxjs": "^6.5.2",
    "terser": "^4.0.0",
    "workbox-sw": "^4.3.1",
    "yarn": "^1.16.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^8.0.2",
    "@angular-devkit/build-angular": "^0.801.2",
    "@angular/compiler-cli": "^8.0.3",
    "@angular/language-service": "^8.0.3",
    "@ngrx/schematics": "^8.0.1",
    "@ngrx/store-devtools": "^8.0.1",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "~3.3.13",
    "@types/jasminewd2": "~2.0.6",
    "@types/jest": "^24.0.13",
    "@types/node": "~12.0.4",
    "@types/paper": "^0.11.14",
    "codelyzer": "~5.1.0",
    "cypress": "^3.4.1",
    "grunt": "^1.0.4",
    "grunt-bump": "^0.8.0",
    "husky": "^2.4.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.8.0",
    "jest-canvas-mock": "^2.1.0",
    "jest-preset-angular": "^7.1.1",
    "lint-staged": "^8.1.7",
    "moment-locales-webpack-plugin": "^1.0.7",
    "prettier": "^1.17.1",
    "protractor": "~5.4.2",
    "ts-node": "~8.2.0",
    "tslint": "~5.17.0",
    "typescript": "3.4.5",
    "webpack-bundle-analyzer": "^3.3.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{ts,html}": [
      "npm run pretty",
      "git add"
    ]
  }`

@KillerCodeMonkey  i replicated your config in ngx-quill-repo too.but it is not working.

@Yexan  ng test is passing and it is working in normal build(ng build). i am not getting any error in console.

suggest me some way locate the error...

**Comment by KillerCodeMonkey** [comment]
just readd on dependency after another into a clean project. and check which breaks the build.

or check the repos of the other 3rd party repos for any similar problem.

i will not rebuild your project for you ;-)
