### ISSUE TITLE
Include 'tslint.json' into .npmignore

### ISSUE THREAD

**Issue by dasrick** [KillerCodeMonkey/ngx-quill#54]
when using ngx-quill as dependency in angular 2+ (in my case ^4.0.0) and try to run ´ng lint´ then you will get the following error:

`Failed to load /Users/foo/projects/bar/node_modules/ngx-quill/tslint.json: Could not find custom rule directory: /Users/foo/projects/bar/node_modules/ngx-quill/node_modules/codelyzer`

The tslint.json is needed for development but not as part of the distribution.

So, please add 'tslint.json' into .npmignore and publish a new version ... THX

**Comment by KillerCodeMonkey** [comment]
check release 1.3.5
