### ISSUE TITLE
Copying a table on a webpage has no style

### ISSUE THREAD

**Issue by qianyingoo** [KillerCodeMonkey/ngx-quill#540]
I copied a table from webpage and to paste it in this input, but it didn't have any table's style.
It can't insert table.

**Comment by KillerCodeMonkey** [comment]
yep because quilljs 1.x does not support tables ;-).

But the support should be availble per default in quilljs 2. you can google for table module or blot for quilljs

**Comment by qianyingoo** [comment]
OK, let me try~Thank you

**Comment by qianyingoo** [comment]
> yep because quilljs 1.x does not support tables ;-).
> 
> But the support should be availble per default in quilljs 2. you can google for table module or blot for quilljs
> 
> Just try to paste it in plain quilljs:
> https://quilljs.com/
> 
> it should not work either

It has been solved, using the latest quill2.0.0-dev.3 version.
It can work.
Thank you very much~!!!🎉
