### ISSUE TITLE
Table in ngx-quill

### ISSUE THREAD

**Issue by Exee03** [KillerCodeMonkey/ngx-quill#544]
Is this package support table? If yes, how can I use it?

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/540

my module depends on quilljs 1.x.
Table support will be in quilljs v2.

I officially does not support v2, because it is in "dev" stage, but just try it.
https://github.com/KillerCodeMonkey/ngx-quill/issues/540

**Comment by Exee03** [comment]
thanks man.. 👍

**Comment by knowledgepitara** [comment]
I want 'insert table' option in Quill editor. Some help please.

**Comment by connectedSoul** [comment]
Coming from [#546](https://github.com/KillerCodeMonkey/ngx-quill/issues/546), there was a solution here, but it has been deleted?

**Comment by marcosox** [comment]
Hi @KillerCodeMonkey, Quill v2 development seems to be [almost stagnant](https://github.com/quilljs/quill/issues/3521#issuecomment-1016096530).
Any chance you would reconsider your decision to wait for a stable v2 before porting (Maybe even just in a separate branch)?
I think it will be _very_ stable at this point :smile:

**Comment by KillerCodeMonkey** [comment]
Since there is no new V2 release for 2years I do not think it is really stable.

Still waiting for an RC, so we can be sure apis will not break ;-)

**Comment by marcosox** [comment]
I meant, joking, that you will be waiting forever since the quill code (and thus its APIs) will not change anymore :stuck_out_tongue_closed_eyes: 

Thanks anyway for your efforts and time spent for this project, cheers!

**Comment by amakhrov** [comment]
fwiw, quill repo seems to have some real-looking activity lately. 
given one of the recent commits is "Initial TypeScript setup", I wouldn't expect a stable 2.0 release too soon anyway

**Comment by devsfnn** [comment]
Hi @KillerCodeMonkey is there any support for table after the new release https://github.com/KillerCodeMonkey/ngx-quill/releases/tag/v25.0.0 ? 
Thanks!

**Comment by KillerCodeMonkey** [comment]
yes, it should be there, since it is part of quill 2 rc releases :)

**Comment by devsfnn** [comment]
is ngx-quill v25 compatible with angular 15?

**Comment by KillerCodeMonkey** [comment]
Nope

Am 21. Februar 2024 10:33:45 MEZ schrieb devsfnn ***@***.***>:

**Comment by eFMSDev** [comment]
What is the best version ngx-quill, quill for angular 15.x?

**Comment by KillerCodeMonkey** [comment]
v21, but there will be no quill v2 support ;-)
