### ISSUE TITLE
ngx-quill support table?

### ISSUE THREAD

**Issue by nosz** [KillerCodeMonkey/ngx-quill#546]
ngx-quill works fine; very good.

but i have a problem with table.
When i set table: true in the imports; an error come:
...
 QuillModule.forRoot({
      modules: {
        table: true,
        //without table: true it works fine.
      }
....

"quill Cannot import modules/table. Are you sure it was registered?"

What can I do?
Thank you.

**Comment by KillerCodeMonkey** [comment]
tables are in quilljs 2 and v2 is not yet stable.

ngx-quill requires quilljs 1.x, so it does not support tables at all.

just try to install quill 2-dev3 release of quill.

seems like somebody got it working.
https://github.com/KillerCodeMonkey/ngx-quill/issues/544

**Comment by pnrdk** [comment]
When are you planning to release v2?

**Comment by KillerCodeMonkey** [comment]
I will Support quilljs v2 when it is at least in RC state ;-)

pnrdk <notifications@github.com> schrieb am Mo., 10. Aug. 2020, 12:25:
