### ISSUE TITLE
Very large Icons of Quill editor in each kind of browser

### ISSUE THREAD

**Issue by anshumandikshit** [KillerCodeMonkey/ngx-quill#547]
I am using Angular 7 and I have tried in google chrome . Firefox and Edge browser .I have already tried by clearing the cache but still facing this Issue .Anyone can help me out??

Attachments are available
![Screenshot (278)](https://user-images.githubusercontent.com/12956424/65820448-d58ebb80-e246-11e9-869e-34f7b6a68226.png)

**Comment by KillerCodeMonkey** [comment]
dude there is no need to open another issue..
in general this is not even a problem with ngx-quill... if you do not know how to use a third party lib in angular correctly..

So just follow my hint in the other issue conversion.

import the quilljs css files correctly (it is mentioned in the readme and you can checkout the demo repo).

**Comment by carhur61** [comment]
Hey Anshuman. Did you solve this issue?  Exactly the same is happening to me. 

Salute from Colombia.

**Comment by anshumandikshit** [comment]
Yes I have solved it ....you need to import the css styles in you
angular.json
