### ISSUE TITLE
Global Config Never Followed

### ISSUE THREAD

**Issue by JaxonWright** [KillerCodeMonkey/ngx-quill#558]
### Description

I have the following set up in the imports for my main app module.

```
QuillModule.forRoot({
      readOnly: true,
      formats: ['bold','italic','link','strike','underline','list','header']
 }),
```

These config options _(and any other ones I have tried to add)_ are not followed in any of my `<quill-editor>` elements. I am able to edit contents and paste any kind of format, despite the config.

I tried finding a minimal Stackblitz example, but I can't find one. It would be useful to have one for people to use.

### Workaround

The only workaround seems to be defining config options directly on the `<quill-editor>` element, which is less than ideal.

### Versions
`ngx-quill:` `7.31`
`quilljs:` `1.3.7`
`angular:` `8.2.9`

**Comment by KillerCodeMonkey** [comment]
thanks for that:

should be fixed in 7.3.2. :)
