### ISSUE TITLE
Prepend protocol to inserted links

### ISSUE THREAD

**Issue by netopolit** [KillerCodeMonkey/ngx-quill#56]
Is there a way to prepend protocol to inserted links or make all link absolute? 
For example, if user enters google.com as a link Quill generates link with href="google.com" which opens it incorrectly as a relative link.

Thanks

**Comment by KillerCodeMonkey** [comment]
you should ask this question in the quilljs repository ;)

**Comment by netopolit** [comment]
Thank you
