### ISSUE TITLE
On ngx-quill toolbar. addHandler ('image', this. imageHandler. bind (this)); insertEmbed custom insert picture failed

### ISSUE THREAD

**Issue by HvanTao** [KillerCodeMonkey/ngx-quill#568]
EditorCreated(quill: any) {
    const toolbar = quill.getModule('toolbar');
    toolbar.addHandler('image', this.imageHandler.bind(this));
  }

  imageHandler() {
    const ths = this;
    ths['quill'].insertEmbed(0,'image','https://avatars2.githubusercontent.com/u/49151748?s=80&v=4','user');
}

This. imageHandler can call the value of pages TS if it uses. bind (this), but it cannot insert images normally. You can't use the value of TS without. bind (this), but you can insert the image normally.

![20191010153708](https://user-images.githubusercontent.com/49151748/66548798-89ac1280-eb74-11e9-875f-09c8cf2741e6.png)
![20191010153829](https://user-images.githubusercontent.com/49151748/66548799-8a44a900-eb74-11e9-88b2-db4fb538344b.png)

**Comment by KillerCodeMonkey** [comment]
could you describe your problem a little more in details. i do not really get it.

you have to add bind(this) because image handlers are inside of quilljs - native javascript and is not connected to your class or app. so sure, if you do not add bind(this) `this` inside of a third party lib is different... this is just the way javascript works.

**Comment by HvanTao** [comment]
At present, I am using angular 8. I want to upload Base64 pictures customized. But it was found that the binding toolbar. addHandler ('image', this. imageHandler); this in the imageHandler method became a toolbar object, which is not my current page's NewsDetailComponent. TS object. I can't call http.upload() custom upload picture

**Comment by KillerCodeMonkey** [comment]
could you create a little stackblitz or plunkr to demonstrate the problem?
Do you use ngModel or formControls?

**Comment by HvanTao** [comment]
No use. bind (this), ths ['quill']. insertEmbed (0,'image','https://avatars2.githubusercontent.com/u/49151748? S = 80&amp;v = 4','user');
Qull rich text on the page can successfully display pictures.

-- use   formcontrols

**Comment by KillerCodeMonkey** [comment]
yeah but i have a fulltime job, and you want to solve your specific case. so i think it is valid to provide a working example to reproduce your issue i can work on ;-).

**Comment by HvanTao** [comment]
That's fine. Thank you! I'm using stackblitz create demo.

**Comment by HvanTao** [comment]
hi, stackblitz :https://stackblitz.com/edit/angular-tbkt7e

I've done it, but I don't know why it's successful...

**Comment by HvanTao** [comment]
(；′⌒`)  I used the framework of Fuse - Angular 8 + Material Design Admin Template, which does not contain rich text. So I used ngx-quill. It's a little troublesome.

**Comment by KillerCodeMonkey** [comment]
yeah, but just checkout your Module or Component. there should be the differences i think, if you do not use editor somewhere else.

But it looks for me like some changedetection stuff.

**Comment by HvanTao** [comment]
![20191010181607](https://user-images.githubusercontent.com/49151748/66560605-55dbe780-eb8a-11e9-8262-004a58ee0250.png)

In fact, the editor - > delta of ngx-quill has the value of illustration pictures. Can we solve the problem of not showing pictures in this respect?

**Comment by KillerCodeMonkey** [comment]
but the correct behavior is to show images right?

why not showing them?

**Comment by HvanTao** [comment]
ohhhhhhhhhhhhhhhhhhhhh!~ Thank you for your advice.  I see that the value of formControl is the image I inserted. But I don't know how to update it so that it can be displayed in rich text.

**Comment by KillerCodeMonkey** [comment]
Than You have another Problem... If Editor instance and Control values are
correct.

So You have multiple quill components in that Page or something similar?
Maybe You are changing the wrong Editor?

Or Check If there are Errors in the js console

HvanTao <notifications@github.com> schrieb am Do., 10. Okt. 2019, 12:33:

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by HvanTao** [comment]
I'm sorry, but I may be excited and misread. Control has no value in editor

**Comment by KillerCodeMonkey** [comment]
then check if you have a special ChangeDetectionStrategy in your component or application.

**Comment by HvanTao** [comment]
![20191011014444](https://user-images.githubusercontent.com/49151748/66592978-b722ab80-ebc8-11e9-8f8f-b459368b2f28.png)

**Comment by KillerCodeMonkey** [comment]
and did you checked the differences in your project to the stackblitz where it is working?
And in your screenshot you does not pass the 'user' source as last parameter of `insertEmbed`

Per default ngx-quill only tracks user changes.

**Comment by HvanTao** [comment]
Yeah, I added'user'and it didn't work either.

Sorry, I'm at 1:47 a.m. in China. I feel very sleepy and need to go home to rest and sleep.  (⊙﹏⊙) 

But thank you very much for answering all the time. It takes me 8 to 9 hours to get to the company.

**Comment by KillerCodeMonkey** [comment]
yeah sleep well. maybe you see the problem after some rest ✌️.

But in general i think it has something to do with the your project. When it is working in the stackblitz.

**Comment by HvanTao** [comment]
Thank you. So are you.

**Comment by HvanTao** [comment]
Hey, I succeeded. The original reason is that the use of Control is not good, the change to ng-module is directly successful. But the quill. getSelection () gets null, and how to get the correct location for the insert picture

**Comment by KillerCodeMonkey** [comment]
in general you can listen to ngx-quill onSelectionChange there you get the old an new range of selected text.

just grab it from there.
