### ISSUE TITLE
Angular universal

### ISSUE THREAD

**Issue by SebastianPodgajny** [KillerCodeMonkey/ngx-quill#57]
Hi,

ngx-quill breaks universal

for example this line
`var elem = document.createElement('div');`

cause 
`ReferenceError: document is not defined`

**Comment by KillerCodeMonkey** [comment]
there is no document.create in ngx-quill. Maybe ng-quill uses this.

Could you give me more details?

The only usage of ngx-quill is `document.body`, which i can replace with the universal version.
But this has no effect if you build the quill dependencies with angular universal ;)

**Comment by KillerCodeMonkey** [comment]
any updates or further information?

**Comment by deepakpapola** [comment]
@SebastianPodgajny  hey did you solve the issue?

**Comment by KillerCodeMonkey** [comment]
check out this: https://github.com/KillerCodeMonkey/ngx-quill/issues/91#issuecomment-358903936
