### ISSUE TITLE
how to set the height of the editor ?

### ISSUE THREAD

**Issue by PhilFlash** [KillerCodeMonkey/ngx-quill#58]
Hi,
I'm using angular 4 + reactive forms. 
How to set the height of the editor ?

**Comment by KillerCodeMonkey** [comment]
with css?

i am using the snow quilljs theme, where the class `.ql-editor` sets the hieght to 100%. 

So you can overwrite the height property of the .ql-editor class or wrap the whole editor in another container with a fixed height

**Comment by PhilFlash** [comment]
OK, for me 2 solutions.
Solution 1:
If you use angular-cli and a html like this:
```
<div class="form-group row">
        <label for="discipline-qe" class="col-sm-12 col-md-2 col-form-label col-form-label-sm">Disciplines
         </label>
        <div class="col-sm-12 col-md-10">
          <quill-editor #disciplineQE id="discipline-qe"
                        placeholder="Vous disposez de 1 000 caractères pour décrire vos principales disciplines."
                        formControlName="discipline"></quill-editor>
        </div>
      </div>
```
The css for the component is:
```
:host #discipline-qe /deep/ .ql-container{
  height: 250px;
}

```

Solution 2
The component **editor** for prime-ng is based on quilljs.
[https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts](https://github.com/primefaces/primeng/blob/master/src/app/components/editor/editor.ts)

For the height, the library used style like this:
```
<p-editor formControlName="description" [style]="{'height':'320px'}"></p-editor>
```

To use this solution, I have patched **quill-editor.component.ts**
Add:
```
@Input() style: any; 
```
Replace 
```
 this.elementRef.nativeElement.insertAdjacentHTML('beforeend', '<div quill-editor-element></div>');
```
By:
```javascript
let qcstyle = ''; 
if (this.style) {
  for (const field in this.style) {
	if (this.style.hasOwnProperty(field)) {
	  qcstyle += '' + field + ': ' + this.style[field] + ';';
	}
  }
  qcstyle = 'style=\'' + qcstyle + '\'';
}
this.elementRef.nativeElement.insertAdjacentHTML('beforeend', '<div quill-editor-element ' + qcstyle + '></div>');
```

Usage:
```
<quill-editor #titleQE id="description-qe" [style]="{'height': '200px', 'background-color': 'lightgrey'}"
  	formControlName="description"></quill-editor>
```

Philippe

**Comment by KillerCodeMonkey** [comment]
i do not get it why you want to patch the component...
the `style` attribute is the default dom property for each dom element (this has nothing to do with angular).

you can 

simply set
`<quill-editor style="height: 250px"></quill-editor>` 

this will be the total height of the editor + toolbar.
and through the default `ql-editor` css class, the editor has a height of `100%` ... so simply set the height per css or property binding `[style]="{height: '250px'}"` only if you need set this value dynamically.

there is no need to change something at the ngx-quill source code?

**Comment by PhilFlash** [comment]
Hi,
here a plunker to test height
[https://embed.plnkr.co/Q2TbofVNoqqn3xbwadoi/](https://embed.plnkr.co/Q2TbofVNoqqn3xbwadoi/)

Description 1 use style="height: 300px" => no effect

Description 2 use css => OK
```
 :host #description2-qe /deep/ .ql-container {
          height: 250px;
        }
```

My patch is for change the height of the editor (quill-editor-element).
The plunker doesn't test the patch.

Philippe

**Comment by KillerCodeMonkey** [comment]
i released a new version 1.4.0 where you can set a style property and a hash of style properties.
I even added an example to my ngx-quill-example repo where i set the height.

**Comment by PhilFlash** [comment]
OK. Thanks

**Comment by 21511012** [comment]
bbbb

**Comment by manuchadha1979** [comment]
Hi

I wrote this `<quill-editor [style]="editorStyle" [modules]="editorConfig" id="hints" type="text" class="form-control" formControlName="hints" [ngClass]="validateField('hints')"></quill-editor>` but the edit area is going past the containing `div`.

The code is

<div class="control-div">
              <quill-editor [style]="editorStyle" [modules]="editorConfig" id="hints" type="text" class="form-control" formControlName="hints" [ngClass]="validateField('hints')"></quill-editor>
          </div>
.ts
editorStyle = {
    'height': '300px'
  }

Could you please tell me what I am doing incorrectly?

<img width="795" alt="quill_overshoot" src="https://user-images.githubusercontent.com/22738115/75578661-23108e00-5a5c-11ea-8515-860746ccf19b.png">

**Comment by manuchadha1979** [comment]
Example -  This works `<quill-editor [style]="editorStyle" [modules]="editorConfig" id="hints" type="text" class="form-control" formControlName="hints" [ngClass]="validateField('hints')"></quill-editor>`

The .ts code is

.ts editorStyle = { 'height': '300px' }

  editorConfig = {
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
      ['blockquote', 'code-block'],
      [{ 'header': 1 }, { 'header': 2 }],               // custom button values
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
      [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
      [{ 'direction': 'rtl' }],                         // text direction
      [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
      [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
      [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
      [{ 'font': [] }],
      [{ 'align': [] }],
      ['clean'],                                         // remove formatting button
      ['link']                         // link 
    ]
  };

**Comment by KillerCodeMonkey** [comment]
Seems Like The Editor has a height of 300px, but your Container around has
Not.

Pleased Check your other stylings.

I Set the height in my Demo repo in The Same way to 200px and IT is Wirkung.

manuchadha1979 <notifications@github.com> schrieb am Fr., 28. Feb. 2020,
20:06:

**Comment by prashanttanwar124** [comment]
.ql-editor {
    height: 100% !important;
}

.ql-container {
    height: auto !important;
}

**Comment by digitlimit** [comment]
CSS solutions didn't work for me.
I'm using the Vue version and this works for me.

```
	mounted() {
		setTimeout(() => {
			var quilEditor = document
				.getElementsByClassName('ql-editor')[0];
			quilEditor.style.cssText += 'height: 20rem;';
		}, 500);
	}
```

**Comment by franconeilglovasa** [comment]
Hi!

Anyone tries to successfully set the height? Nothing works for me except for the patch that PhilFlash showed. 

Styles and css wont work for me

```
<quill-editor style="height: 250px  !important" [modules]="editorModules" 
                      [(ngModel)]="data" placeholder="Description"
                      (ngModelChange)="this.debouncedUpdate.next($event)"
                     >
                    </quill-editor>
```

**Comment by b4nt0** [comment]
@franconeilglovasa 

```
<quill-editor
  ...
  [styles]="{'height': '500px'}"></quill-editor>
```

Notice **styles**, not style.

**Comment by Tavethiya** [comment]
I tried to set min-width and overflow scroll works fine 
```.ql-editor {
  overflow-y: scroll;
  min-height: 150px;
}```

**Comment by kperusi** [comment]
Cool
