### ISSUE TITLE
height prop can't work well

### ISSUE THREAD

**Issue by JasonWuuu** [KillerCodeMonkey/ngx-quill#580]
Hi ,

the detailled issue please see  the screen capture
![Untitled1](https://user-images.githubusercontent.com/19722003/66849785-165a3480-efaa-11e9-8292-d93ae4045aab.png)
![Untitled2](https://user-images.githubusercontent.com/19722003/66849792-19552500-efaa-11e9-9e29-66e0f0959670.png)

I am using below version, 
"ngx-quill": "^7.3.4",
 "quill": "^1.3.7",

many thanks

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill#config
check the readme. there is a `styles` property.

style is the default domNode property. so you are styling the component wrapper and not editor it self.

**Comment by JasonWuuu** [comment]
oh, that's right,  so fast feedback, thanks
