### ISSUE TITLE
is it possible to change the label in editor from P to DIV

### ISSUE THREAD

**Issue by JasonWuuu** [KillerCodeMonkey/ngx-quill#581]
please see the style on the left(screen capture) ,  another team has added the !important style, I can't change it, it overwrite my style, is it possible to change the label in editor from P to DIV in green?
![Untitled](https://user-images.githubusercontent.com/19722003/66904602-ee64e280-f036-11e9-8678-18fb9a7658d6.png)

**Comment by KillerCodeMonkey** [comment]
it is possbile with quilljs and i am doing it in my demo repo, but this change will be globally for all quill instances.

just add a unique id to your quill-editor component and make a more explicit css-selector to override the !important styles.

```HTML
<quill-editor id="my-editor"></quill-editor>
```

```CSS
#my-editor .ql-editor p span, #my-editor .ql-editor p {
  color: green;
} 
```

But if you are working on the same app.. you should talk to your projektmanager or with your team how the editor should be used in your app.. instead of overriding eachothers configs and layouts.

**Comment by JasonWuuu** [comment]
it's different app, if I add above code you provided, you color will be always green, I can't change it through font-color-picker, any further advice

**Comment by KillerCodeMonkey** [comment]
when it is a different project i do not know where the !important style comes from...
and it is only an example...

But in general remove the import style from the project...

and switching to divs can be done.

**Comment by JasonWuuu** [comment]
I can't remove the import style , the style managed by other team,   how to switch to divs?

**Comment by KillerCodeMonkey** [comment]
i am not stackoverflow just check my demo repo or quilljs documentation -.-'

**Comment by JasonWuuu** [comment]
is that possible to change below P to DIV?  label P auto generated by the editor

`
<div class="ql-editor" data-gramm="false" contenteditable="true" data-placeholder="Enter your description here…">
<p>CE.07 How is th<span style="color: rgb(230, 0, 0);">e cmitment</span>s? (All Service Groups)</p>
</div>
`

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/3a588ab37c856876803302dd1c477e224a07bc4c/src/app/app.component.ts#L7

**Comment by JasonWuuu** [comment]
awesome,  solved this issue referred to the link,  even if  this change will be globally for all quill instances

many many thanks guy

**Comment by JasonWuuu** [comment]
@KillerCodeMonkey  I found a bug, after I change the P to div,  the value of editor always has value even I clear the content,   i print value <div><br></div>,  and  i checked your code in line 167 of below link, I found the code miss a "/".  could you help fix this bug as soon as possible?

https://github.com/KillerCodeMonkey/ngx-quill/blob/7719b16ae048c7a78331c39b1f75f860e4c6a278/src/quill-editor.component.ts
if (html === '<p><br></p>' || html === '<div><br><div>') {

**Comment by KillerCodeMonkey** [comment]
should be fixed in 7.3.5

**Comment by JasonWuuu** [comment]
what time will the version issue about


thanks

**Comment by KillerCodeMonkey** [comment]
its already released...

**Comment by JasonWuuu** [comment]
just downloaded the latest version and test it again, the bug persists, see below, the class is "ng-valid"
![Untitled](https://user-images.githubusercontent.com/19722003/66991516-ce96f280-f0fa-11e9-81c3-d49cdab31b9a.png)

**Comment by JasonWuuu** [comment]
it works well now

thanks man
