### ISSUE TITLE
how to hidden/show the toolbar when focus/blur

### ISSUE THREAD

**Issue by JasonWuuu** [KillerCodeMonkey/ngx-quill#585]
Hi,
is that possible that when focus on editor , the toolbar will show , after blur, it will hidden

I have tried to add the custom toolbar, and add the property for show/hidden on that, the OnFocus will set the property to true,  OnBlur will set the property to false. but when I choose the font color on color panel float below toolbar, the toolbar disappeared.

is it there any better function to implement this case?

**Comment by KillerCodeMonkey** [comment]
please ask those things on stackoverflow...

You chould check the values in "onSelectionChanged" when selecting something in the toolbar.
Or just add a click listener to the quill-editor component and a global click listener on your page.
When the editor-clicklistener sets -> showToolbar to true and calls`event.stopImmidiatePropagation()` - so the event does not bubbles up the dom.

the global listeners set showToolbar to false.
