### ISSUE TITLE
ngx-quill image resize lag

### ISSUE THREAD

**Issue by claudioallphi** [KillerCodeMonkey/ngx-quill#586]
ngx-quill becomes incredible slow after resizing 2 images.

**Comment by KillerCodeMonkey** [comment]
check https://killercodemonkey.github.io/ngx-quill-example/

when i use the "Formula & image resize" editor everything works fast and as expected.

**Comment by claudioallphi** [comment]
> check https://killercodemonkey.github.io/ngx-quill-example/
> 
> when i use the "Formula & image resize" editor everything works fast and as expected.

I just tried your example and i have the same result, very slow.
I Just tried adding two images and i have resized them both and followed that up by typing a sentence underneath the two resized pictures.
Suddenly the editor becomes slow.

**Comment by KillerCodeMonkey** [comment]
whats the size of your image?

because keep in mind quill adds base64 images and if you are using formControls or ngModels every change triggers the onContentCHanged output with the content and the image.
So i think this is more because the editor content geeeets huge.

I used images around 350kb and nothing lags

**Comment by claudioallphi** [comment]
> whats the size of your image?
> 
> because keep in mind quill adds base64 images and if you are using formControls or ngModels every change triggers the onContentCHanged output with the content and the image.
> So i think this is more because the editor content geeeets huge.
> 
> I used images around 350kb and nothing lags

i am using an image that has a size of 3.61 mb

**Comment by KillerCodeMonkey** [comment]
okay.... you should not do that. or extend the image plugin to upload and optimize the image first

**Comment by claudioallphi** [comment]
> okay.... you should not do that. or extend the image plugin to upload and optimize the image first

okay, i'll give it a try. Thank you for your time.

**Comment by claudioallphi** [comment]
okay, it's fast when limiting the image size
