### ISSUE TITLE
DOMException: Failed to execute 'splitText' on 'Text'

### ISSUE THREAD

**Issue by raydvard** [KillerCodeMonkey/ngx-quill#588]
I am having issue when I am setting some texts to the quill editor.
The full error is : 
`DOMException: Failed to execute 'splitText' on 'Text': The offset 298 is larger than the Text node's length.`

In my html : 
        `<quill-editor 
              #editor 
              (onEditorCreated)="getEditorInstance($event)"
              [theme]="editorTheme" 
              [style]="editorStyle" 
              [placeholder]="editorPlaceholder" 
              formControlName="article_details_content" 
              [(ngModel)]="article_detail.article_details_content">
        </quill-editor>`

and I am setting value like this : 
`this.article_detail.article_details_content = element.article_details_content;`

**After giving this error the texts in my editor look jumbled and when I edit, I get null at the end.**

_**PS: I am using ngx-quill: 4.4.2 and It varies from language based texts such as bengali**_

How can I solve this? or what the error exactly means?

**Comment by KillerCodeMonkey** [comment]
you should never..really never mix up reactive and template driven forms.

so you have a formControl OR a ngModel connected...
there should be even a warning or error in your console.log about it.

**Comment by raydvard** [comment]
@KillerCodeMonkey  I don't have error on that before I am using angular 6 and I think because of its old version it allows me to do that. well, some of the specific features are done like that.

But I have tried only with fromControl also along with form validation, but I think that's not the source to my issue here.

**Comment by KillerCodeMonkey** [comment]
i think angular cli gives you an error when using both since version 2? 🤔

i think this error is not triggered my ngx-quill more of quilljs.

i do nothing with splittext and so on.
Are you doing some content manipulations? Seems like somewhere splitText is called with an invalid index.
