### ISSUE TITLE
Contradicting documentation of sanitize

### ISSUE THREAD

**Issue by djonn** [KillerCodeMonkey/ngx-quill#590]
In the README under "QuillEditorComponent -> Config" the following line can be found
`sanitize - uses angulars DomSanitizer to santize html values - default: true, boolean (only for format="html")`
However under "Security Hint" it is stated that it is deactivated per default

I believe the line in config is wrong, since from looking at the quill-editor-component the default value seems to be false.

**Comment by KillerCodeMonkey** [comment]
thanks man!
