### ISSUE TITLE
Can you please give an exam,ple of how to configure the Toolbar?

### ISSUE THREAD

**Issue by rodneyjoyce** [KillerCodeMonkey/ngx-quill#6]
Could you please give an exmple of how to configure the toolbar? I have added it to my module but not sure where the configuration goes, thanks

{```

  toolbar: [
    ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
    ['blockquote', 'code-block'],
...
    ['link', 'image', 'video']                         // link and image, video
  ]
};
```

**Comment by rodneyjoyce** [comment]
Ah, I see, it's in the HTML 👍 

```
   <quill-editor #description="ngModel" type="text" name="description" placeholder="Description" [(ngModel)]="restaurant.description" required maxlength="2000"
                                      [modules]="{toolbar: [['bold', 'italic', 'underline', 'strike']]}"></quill-editor>
```

**Comment by KillerCodeMonkey** [comment]
yeah, feel free to extend readme, if you think something is missing.

**Comment by dsjambekar** [comment]
What are the various available options?
Or where can I find them all at one place so I can choose only the ones I want?

**Comment by KillerCodeMonkey** [comment]
Check quilljs Documentation ;)

dsjambekar <notifications@github.com> schrieb am Mi., 3. Okt. 2018, 13:37:
