### ISSUE TITLE
Add scrollingContainer option

### ISSUE THREAD

**Issue by Lindvorn** [KillerCodeMonkey/ngx-quill#60]
Hello.
I need to specify scrollingContainer to restrict quill from growing.
Actually I want to do something like this: https://codepen.io/quill/pen/apmWXm

Thank you in advance.

**Comment by KillerCodeMonkey** [comment]
checkout https://killercodemonkey.github.io/ngx-quill-example/ the first editor. 

simple set a height or max-height for the editor element ;)

**Comment by Lindvorn** [comment]
Thank you. 
I've been at that uri.
What I need to do is to make editor fill free space. So I cannot set height or max height.
On a codepen link provided above I saw that this can be done using scrollingContainer property (at first I thought that "bounds" is what I need but then I saw that this property respects only left and right bounds).
I wouldn't want to use JS to set the height to fill free space and wrote here so if possible I get it working from the box =).
Therefore if it's possible to add I'd be grateful.

**Comment by KillerCodeMonkey** [comment]
sorry misunderstood this.

**Comment by Lindvorn** [comment]
Thank you alot!

**Comment by KillerCodeMonkey** [comment]
the feature has been landed in 1.5.0.
