### ISSUE TITLE
Locks all the events after one successful redirect.

### ISSUE THREAD

**Issue by drashti2277** [KillerCodeMonkey/ngx-quill#603]
I'm using ngx-quill in one of my project with angular 7 and it works great!! But I'm facing really weird error on which I'm stuck.
Description:-
There are two components . One is with ngx-quill editor and other is normal component with a table.
All events inside table works fine unless I go and comeback from component with ngx-editor. Somehow it disables all the links in side table component. I've tried removing ngx-quill editor with just normal text area and everything starts working fine!!
Please help me if there is some event in editor which needs to be taking care of to stop this behavior.
Sorry in advance if I missed anything.
Thanks.

**Comment by KillerCodeMonkey** [comment]
please provide a demo repo or a stackblitz where i can reproduce the issue.

without any example i can not help you :)

In general the components are encapsulated an does not change anything outside of its context.

**Comment by KillerCodeMonkey** [comment]
@drashti2277 any updates?

**Comment by drashti2277** [comment]
Hello,
No, I ended up using ngx-editor package because of time constraint. I think there was something internal triggering this behavior as my smart-table component have many ngIfs..
Thanks for your help and sorry for the delay... ^_^

**Comment by KillerCodeMonkey** [comment]
No Probs, feel free to Close the issue then

Drashti Solanki <notifications@github.com> schrieb am Mo., 28. Okt. 2019,
20:51:
