### ISSUE TITLE
blank value issue in ngx-quill

### ISSUE THREAD

**Issue by JasonWuuu** [KillerCodeMonkey/ngx-quill#606]
I will show you 3 cases:
1.  my page initize and nothing in the rich box, see below capture,  the default value is `<div><br></div>` in richbox, and the required msg is show, so I can't submit the form
![Untitled1](https://user-images.githubusercontent.com/19722003/67663813-4689d600-f9a1-11e9-8a21-0906a03c3c07.png)

2. and then, I type some a blank in the richbox, the value is `<div></div>` in richbox,   I have a try to type more than one blank, the value is always `<div></div>`, and the required msg  is hidden, so I can submit the form

3. after submit, I go back to see the value in richbox, the default value is `<div><br></div>` in richbox, and the required msg is show

summarize, the value only has blank can't be save

**Comment by KillerCodeMonkey** [comment]
this is not an ngx-quill issue. this is the default behaviour of quill.

But i fixed something in the latest ngx-quill version, where `<div><br></div>` triggers a model change.

**Comment by JasonWuuu** [comment]
i think if user type the value only contains blank, the required msg should always show, and the placehold should display, user can't submit the form at least.

**Comment by JasonWuuu** [comment]
I will have a try the latest version, thanks man

**Comment by KillerCodeMonkey** [comment]
yeah... in your use case. but if quilljs editor works like it works.

and keep in mind you can pass validators to the editor component (required, max and minLength) ;-)

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by JasonWuuu** [comment]
if the value only contains blank, is that possible to set the ngModel's Value to empty on your side?

**Comment by JasonWuuu** [comment]
see below, there are 3 blank in richbox
![Untitled1](https://user-images.githubusercontent.com/19722003/67667723-66bd9300-f9a9-11e9-9ff5-6f518f2fd530.png)

I think you can add the logic , if the value is `<div>                  </div>`,  set the html = null, just like the code you write below

https://github.com/KillerCodeMonkey/ngx-quill/blob/7719b16ae048c7a78331c39b1f75f860e4c6a278/src/quill-editor.component.ts   line 167
`if (html === '<p><br></p>' || html === '<div><br><div>') {`

**Comment by KillerCodeMonkey** [comment]
nope, because i want to keep the quilljs functionality. and this is some special handling you want.

you should validate the value, so if you send it to your backend, check if there are only blanks.
Maybe some other project, want to allow only blanks.

again you can insert multiple emptylines. this would be valid content. :).
So you have to implenent your own validation :).

e.g. the onContenChanged event of the quilleditor component passes the "text" value as well.
so you will simply get "      " as value.
Just listen on this event and check if there are only blanks -> show the message and disable submit.

Keep in mind that you should implement a serverside validation as well :)

**Comment by JasonWuuu** [comment]
@KillerCodeMonkey 
I have implemented the code based on your advice, see below code, if the editor's value only contains blank, I set the form control value to empty,  and call  updateValueAndValidity(),  but the line 77 doesn't effective, and the quill editor show a warning "addRange(): The given range isn't in document.", the second picture is the detailed error.
![Untitled](https://user-images.githubusercontent.com/19722003/67914147-3dc81880-fbca-11e9-9040-7e568d0baa17.png)

![Untitled2](https://user-images.githubusercontent.com/19722003/67914453-22114200-fbcb-11e9-8e41-cd0644f135c0.png)

**Comment by KillerCodeMonkey** [comment]
yeah i think the error is clear. Just check your range it is valid for your editor content. For example, if you editor is empty the range 0 to 20 would be invalid.

But i see you are using formcontols and checking for required and maxlength.
For those errors just, set the maxLength and required property of quill-editor. and you will get everything out of the box. Without your custom handling ;-).

I mentioned this already in earlier comments. You can access these form errors in your template and disable the submit button and show your error message.

**Comment by KillerCodeMonkey** [comment]
Keep in mind to use "maxLength" property and not the native "max-length" oder "maxlength".

I have a custom implementation, where i always use the text content of the editor for checking min and maxlength. 

The same with required --> check the code for it:
```

**Comment by ktmaxx** [comment]
> see below, there are 3 blank in richbox ![Untitled1](https://user-images.githubusercontent.com/19722003/67667723-66bd9300-f9a9-11e9-9ff5-6f518f2fd530.png)
> 
> I think you can add the logic , if the value is `<div>[blank][blank][blank]...</div>`, set the html = null, just like the code you write below
> 
> https://github.com/KillerCodeMonkey/ngx-quill/blob/7719b16ae048c7a78331c39b1f75f860e4c6a278/src/quill-editor.component.ts line 167 `if (html === '<p><br></p>' || html === '<div><br><div>') {`

using onTextChange($event: EditorTextChangeEvent) get $event.textValue you will get raw text
