### ISSUE TITLE
Compile Errors when using Angular 8 and Ivy

### ISSUE THREAD

**Issue by allen0977** [KillerCodeMonkey/ngx-quill#614]
Receiving the following error when compiling with Ivy enabled (angular core: 8.2.12, angular cli: 8.3.15)

Compiling ngx-quill : es2015 as esm2015

ERROR in No suitable injection token for parameter 'domSanitizer' of class 'QuillEditorComponent'.
no type or decorator

**Comment by KillerCodeMonkey** [comment]
do you changed your buildprocess? why ngx-quill build? You should not compile already compiled code from external modules.

**Comment by KillerCodeMonkey** [comment]
@allen0977 i updated my demo repo to use ivy, if you want to check it out

**Comment by allen0977** [comment]
I was using a later version for target (esnext), which does report the issue, but when I switched to es5, it compiled fine.

**Comment by Ismaestro** [comment]
and what happens if I can't switch to es5? :smile:
