### ISSUE TITLE
ERROR in ./node_modules/ngx-quill/fesm5/ngx-quill.js

### ISSUE THREAD

**Issue by Karbashevskyi** [KillerCodeMonkey/ngx-quill#619]
terminal: ng build --prod=true

![Screen Shot 2019-10-31 at 16 47 17](https://user-images.githubusercontent.com/31188317/67962981-2acf3b80-fbfe-11e9-8634-8eee5fbd9382.png)

Lazy load module

![Screen Shot 2019-10-31 at 16 48 54](https://user-images.githubusercontent.com/31188317/67963115-5f42f780-fbfe-11e9-954b-3e1649613e1e.png)

angular.json

![Screen Shot 2019-10-31 at 16 48 41](https://user-images.githubusercontent.com/31188317/67963116-5f42f780-fbfe-11e9-9c3e-74ef3c74edb0.png)

package.json

![Screen Shot 2019-10-31 at 16 48 33](https://user-images.githubusercontent.com/31188317/67963117-5f42f780-fbfe-11e9-85eb-cc759a68b820.png)

![Screen Shot 2019-10-31 at 16 48 22](https://user-images.githubusercontent.com/31188317/67963119-5f42f780-fbfe-11e9-872a-2424951fc34e.png)

**Comment by KillerCodeMonkey** [comment]
i would say, upgrade angular or check the compatibility of typescript. in most cases such errors are produced by TS stuff.

**Comment by Karbashevskyi** [comment]
Thanks for you answer, i did update angular from 7.2.0 to 7.2.15 (but angular/cli 7.3.9), it's did not help...

Angular.json: styles

![image](https://user-images.githubusercontent.com/31188317/67975152-e2227d00-fc13-11e9-934e-628b396cba02.png)

dependencies
![image](https://user-images.githubusercontent.com/31188317/67974940-940d7980-fc13-11e9-8b14-1b71c91930d0.png)

devDependencies
![image](https://user-images.githubusercontent.com/31188317/67974922-8a841180-fc13-11e9-9d88-8b114b5f3c7f.png)

**Comment by KillerCodeMonkey** [comment]
okay, could you share your angular.json (please not as screen shot)... never use screenshots to share code. 

And check if this is a typescript version could cause this or your angular cli version is incompatible with your other angular deps.

This is not produced by ngx-quill. more a project or build setting thing.

**Comment by KillerCodeMonkey** [comment]
check this issue: https://github.com/KillerCodeMonkey/ngx-quill/issues/573

**Comment by Karbashevskyi** [comment]
Ok, thanks, i find problem, problem in version ngx-quill, i am change version to 5.0.0 and it's work, i can build prod version :)

**Comment by sarancruzer** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/251#issuecomment-426259861
