### ISSUE TITLE
"Cannot use 'new' with an expression whose type lacks a call or construct signature."

### ISSUE THREAD

**Issue by cluskii** [KillerCodeMonkey/ngx-quill#62]
When trying to build the project with angular CLI 1.3.0 / Typescript 2.4.2, I encounter the following error when I run `ng build -dev`:

`ERROR in /builds/$project/node_modules/ngx-quill/src/quill-editor.component.ts (113,24): Cannot use 'new' with an expression whose type lacks a call or construct signature.
ERROR: Job failed: exit code 1`

I'm happy to create a pull request to try and solve the problem.

**Comment by cluskii** [comment]
I looked around the code, the problem is popping up from using:

`24: import * as Quill from 'quill';`  
in  
`113: this.quillEditor = new Quill(this.editorElem, {`

Building on my local machine seems to be ok, but when I try to build on my CI box the error appears.

**Comment by KillerCodeMonkey** [comment]
yep, because in a newer type (@types/quill) the import changed simply to `import Quill from 'quill'`

I also added a pr to definitelytyped for some further updates:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19801

But i will update these repo for newer types

**Comment by cluskii** [comment]
Thanks!

**Comment by KillerCodeMonkey** [comment]
möööp sadly the type the types does not match the quill editor -.-  constructor. so it has nothing to do with my repo --> use yarn for your ci. the deps defined in the yarn lock should be working

**Comment by KillerCodeMonkey** [comment]
i kicked our the types, could you please install the beta release and test it?

`npm install ngx-quill@beta`

**Comment by cluskii** [comment]
That worked! Thanks for your help :)

**Comment by KillerCodeMonkey** [comment]
thanks for the response, i released this fix in 1.4.1
