### ISSUE TITLE
the editor can't observe validations' changes such as required and maxLength 

### ISSUE THREAD

**Issue by JasonWuuu** [KillerCodeMonkey/ngx-quill#622]
I faced one case, isReq default value is true, but it may change by some logic, if the value to false, the both validations won't workable

`<quill-editor  maxLength="2000" [required]="isReq" ></quill-editor>`

`<div class="error"
                *ngIf="detailForm.get('description').hasError('requiredError')">description is required
              </div>`
`<div class="error" *ngIf="detailForm.get(['description').hasError('maxLengthError')">description exceeds maximum size (2,000 characters)
</div>
`

**Comment by KillerCodeMonkey** [comment]
i have an example in my demo repo
https://killercodemonkey.github.io/ngx-quill-example/
"Editor without toolbar + readonly, required and formControl + maxlength 10 chars"

maxLength and a toggler for required. everything works fine.

i guess maxLength should be a number, so pass it like an input prob: `[maxLength]="2000"`
