### ISSUE TITLE
emoji cannot load

### ISSUE THREAD

**Issue by wuaries** [KillerCodeMonkey/ngx-quill#633]
quill Cannot load emoji-toolbar module. Are you sure you registered it?
quill Cannot import modules/emoji-toolbar. Are you sure it was registered?
quill.js:2037 quill Cannot load emoji-textarea module. Are you sure you registered it?
quill Cannot import modules/emoji-textarea. Are you sure it was registered?
uill Cannot load emoji-shortname module. Are you sure you registered it?
quill.js:2037 quill Cannot import modules/emoji-shortname. Are you sure it was registered?

**Comment by KillerCodeMonkey** [comment]
Like the message says. You nee to correctly register the emoji module.

checkout my demo repo https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/emoji/emoji.component.ts

**Comment by wuaries** [comment]
My code looks like this:
   QuillModule.forRoot({
      modules: {
        toolbar: [
          ['bold', 'italic', 'underline', 'strike','blockquote','emoji'], 
          [{ 'list': 'ordered' }, { 'list': 'bullet' }],
          [{ 'script': 'sub' }, { 'script': 'super' }],     
          [{ 'indent': '-1' }, { 'indent': '+1' }],  
          [{ 'color': [] }, { 'background': [] }],  
        ],
        'emoji-shortname': true,
        'emoji-textarea': true,
        'emoji-toolbar': true,
      }
    })

But I still get the same error when I try to use the example code.

**Comment by wuaries** [comment]
> Like the message says. You nee to correctly register the emoji module.
> 
> checkout my demo repo https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/emoji/emoji.component.ts



My code looks like this:
QuillModule.forRoot({
modules: {
toolbar: [
['bold', 'italic', 'underline', 'strike','blockquote','emoji'],
[{ 'list': 'ordered' }, { 'list': 'bullet' }],
[{ 'script': 'sub' }, { 'script': 'super' }],
[{ 'indent': '-1' }, { 'indent': '+1' }],
[{ 'color': [] }, { 'background': [] }],
],
'emoji-shortname': true,
'emoji-textarea': true,
'emoji-toolbar': true,
}
})

But I still get the same error when I try to use the example code.

**Comment by KillerCodeMonkey** [comment]
yeah but you need to import quill emoji sources before the first quill editor is created.

**Comment by wuaries** [comment]
> yeah but you need to import quill emoji sources before the first quill editor is created.

Thanks！
I wrote import emoji.js of code to angular.json，but it has no problem  when I wrote to app.module.ts.  what happened?

**Comment by KillerCodeMonkey** [comment]
try it out :D
