### ISSUE TITLE
The reactive forms don't maintain whitespace in form value (Space/Tab characters)

### ISSUE THREAD

**Issue by benwinding** [KillerCodeMonkey/ngx-quill#641]
Hi There seems to be an issue where whitespace is not preserved in the output HTML in the _ReactiveFormControl_ value in this package.

It's easily reproducible using the advanced demo at https://killercodemonkey.github.io/ngx-quill-example/

- Normal behaviour (works as expected)
![image](https://user-images.githubusercontent.com/11782590/68734607-cfa03e80-062a-11ea-8567-6a2437baace2.png)

- Incorrect behaviour
![image](https://user-images.githubusercontent.com/11782590/68734574-b39c9d00-062a-11ea-8f16-4da4f833c275.png)

PS: Love the package and the amount of work you do maintaining it and keeping the project at zero issues!

**Comment by KillerCodeMonkey** [comment]
this has nothing todo with reactive forms, checkout the readme an the preserveWhitespace prop.

**Comment by benwinding** [comment]
Thanks @KillerCodeMonkey,

Here's how I fixed it if anyone is interested:

``` html
    <quill-editor
      [formControl]="testControl"
      [preserveWhitespace]="true"
    >
    ....
    <h5>HTML RENDERED</h5>
    <p style="white-space: pre;"  [innerHTML]="testControl.value"></p>
```

And everything works as expected!

**Comment by prajinpults** [comment]
I have similar issue when dynamically binding it. the tab and get stripped from api response
<quill-editor [formControl]="gramendments.controls[j]" [preserveWhitespace]="true" ></quill-editor>
