### ISSUE TITLE
Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by Eyegabry99** [KillerCodeMonkey/ngx-quill#642]
I installed the plugin image resize into my component in this way 

```
import {Quill} from 'quill';
import {ImageResize} from 'quill-image-resize';
Quill.register('modules/imageResize', ImageResize);
```
And binded with the following options 
```
modulesForQuill = {
    imageResize: {},
    toolbar: [
      [{'color': []}],  // dropdown with defaults from theme
      ['bold', 'italic', 'underline'],        // toggled buttons
      [{'script': 'super'}, {'script': 'sub'}], // superscript, subscript
      [{'align': []}], // let's test this
      [{'list': 'ordered'}, {'list': 'bullet'}], // various list
      ['link', 'image'], // miscellaneous
    ]
  };
```
I call it from my html in this way
`<quill-editor [modules]="modulesForQuill"></quill-editor>
`

1. Using ng serve it works fine the image resize. But when i try to run in production this plugin it give me this error: "Super expression must either be null or a function, not undefined"

**Expected behavior**:
Image resize working in production

**Actual behavior**:
Project not running, it crash at start of loading

**Platforms**:
Chrome
Windows 10

**Version**:

Angular version: 7
Quill version: 5.0.0

**Comment by KillerCodeMonkey** [comment]
checkout my example: https://github.com/KillerCodeMonkey/ngx-quill-example/blob/e7b0c27dfa7f50f0dda89712575a14005135f7d5/src/app/formula/formula.component.ts

I am using quill-image-resize-module it is a wrapper for image-resize plugin.

i have no problems with it. even in production builds

**Comment by KillerCodeMonkey** [comment]
did you solved the issue?
