### ISSUE TITLE
Incompatible with ivy ?

### ISSUE THREAD

**Issue by Ploppy3** [KillerCodeMonkey/ngx-quill#644]
This project seems to be incompatible with Angular Ivy.

It produces the following while in dev mode.

```
ERROR in ./node_modules/ngx-quill/__ivy_ngcc__/fesm2015/ngx-quill.js
Module not found: Error: Can't resolve 'quill' in '[...]\node_modules\ngx-quill\__ivy_ngcc__\fesm2015'
```

**Comment by KillerCodeMonkey** [comment]
my example repo is using ivy renderer and is working fine.

**Comment by Ploppy3** [comment]
I'm stupid, nevermind... Forgot to install quill, I thought it was included.

**Comment by KillerCodeMonkey** [comment]
no probs :)

**Comment by Ploppy3** [comment]
@KillerCodeMonkey May I ask you something completely unrelated.

Is it possible to add buttons with the Quill editor? Do you have to add plugins for this?

**Comment by KillerCodeMonkey** [comment]
what do you mean with "add buttons"? custom buttons to the toolbar or buttons to the content of the editor

**Comment by Ploppy3** [comment]
I mean adding html buttons to the content/text.

**Comment by KillerCodeMonkey** [comment]
okay then you need a custom module or Blot. Because quilljs only accepts formats and content it knows. so you need to define your button-content
