### ISSUE TITLE
Insert Formula at end by update contents

### ISSUE THREAD

**Issue by shashank-sharma** [KillerCodeMonkey/ngx-quill#65]
So far I discovered that quill editor have its own math editor rather than using mathquill. So if we want to insert any formula we can do that by:

this.editorInstance.updateContents([{ insert: { formula: 'x^2' } }]);

Now the problem is that the formula x^2 is getting pushed at position 0 and I want this to get inserted at given position like 1,2,3 or may be at last. So is it possible to updateContents at given position so that I can insert formula at last.

Also after inserting any formula is it possible to edit that formula by clicking it. As per my understanding it is not possible. And if I want to achieve this then I might need to integrate it with mathquill.
Thanks

**Comment by KillerCodeMonkey** [comment]
please ask quill question in the quill repository. I do not know everything about quill and it possibilities. You have the possibility to access the whole quill editor api through the editorInstance.

e.g. https://quilljs.com/docs/api/#getselection to retrieve current cursor position.

UpdateContents replaces the whole editor content.

Please check the documentation first:
https://quilljs.com/docs/api/#updatecontents

there is an example how to retain existing chars.
