### ISSUE TITLE
Quill editor does not display html 

### ISSUE THREAD

**Issue by Roxx93** [KillerCodeMonkey/ngx-quill#652]
Context :
- Angular 5 application
- The latest version of ngx-quill installed (7.3.9)

Problem
In my application, I use the quill editor to write some comments. The problem appears when someone writes a comment using nested list elements, like in this image:
![image](https://user-images.githubusercontent.com/7022700/69412446-2da9e180-0d0f-11ea-9cc3-d43109d2b3a9.png)

The HTML string below is the representation of the comment that is stored in my database.

Now, when this comment is saved, the preview looks fine :
![image](https://user-images.githubusercontent.com/7022700/69412550-66e25180-0d0f-11ea-906d-4980c9fa1237.png)

The style is the same, and this is ok.

Now, if I try to modify this comment, and so, pass it to quill editor, I get this weird visualization :
![image](https://user-images.githubusercontent.com/7022700/69412614-8e391e80-0d0f-11ea-8382-e9548dfc252d.png)

Despite the HTML string is exactly the same ad before, quill display it in a different way.

Here some snippets of my code :
![image](https://user-images.githubusercontent.com/7022700/69412732-c4769e00-0d0f-11ea-8c73-80c085f67f88.png)
Variable tempComment is exactly the HTML string stored in Database.

**Comment by KillerCodeMonkey** [comment]
In my example repo https://killercodemonkey.github.io/ngx-quill-example/ is an example with reactive forms  "Reactive Forms and patch value" is the title to find it on the page.

There i set such a list from a formcontrol and it is working fine. even after patching the formvalue.

And i see you are using ngModel and formControlName at the same time.. this is forbidden.. just use ngModel or formControls ;-)

**Comment by KillerCodeMonkey** [comment]
any updates

**Comment by Roxx93** [comment]
Yes sorry, wasn't at pc in these days. Now i'm checking your example, i'll keep you updated!

**Comment by Roxx93** [comment]
Your repo is very helpful!! I removed ngModel and leave just formControlName, and now it works.
Thanks :)
