### ISSUE TITLE
Can't overwrite CSS properties of quill-view

### ISSUE THREAD

**Issue by Lyro1** [KillerCodeMonkey/ngx-quill#653]
I use a `quill-view` to display the output generated by my Quill Editor. But I wan't the output to follow my custom CSS rules, and not any Quill themes. 

I tried to overwrite the Quill's default snow template rules, but it does not work, after inspecting the element, no rule is applied to the child elements of my `quill-view`.

How can I overwrite those default Quill CSS properties?

**Comment by KillerCodeMonkey** [comment]
Did your Styling applies to the quill Editor? You should know a wysiwyg
Editor should Look the Same it will Look Like when viewed.

So in General You would create a custom quill theme with your Styling and
Pass IT to the Editor and View component

Louis Dupont <notifications@github.com> schrieb am Fr., 22. Nov. 2019,
17:07:

**Comment by Lyro1** [comment]
I did not create a particular theme for Quill, but I maybe should take a look at it. But I don't understand why creating custom rules in my css files does not override the Quill's properties...

By using simply the scss files of my Angular modules, I am able at best to change the `<quill-editor>` bloc itself, nothing else (no custom design on the toolbar for example, and no custom design for the various elements inside my `<quill-view>` neither).

**Comment by KillerCodeMonkey** [comment]
quill styling is global --> so you need to override it in your global scss (app.scss?).
When you are doing this in a component your styling will be view encapsulated. So you are not able to override global css selektors :)

**Comment by Lyro1** [comment]
Perfect, that was the point I was missing!
Thanks a lot :)
