### ISSUE TITLE
Ivy support

### ISSUE THREAD

**Issue by zainniazi** [KillerCodeMonkey/ngx-quill#657]
ERROR in No suitable injection token for parameter 'domSanitizer' of class 'QuillEditorComponent'.
no type or decorator

**Comment by KillerCodeMonkey** [comment]
my example repo is using ivy and it is working fine

**Comment by KillerCodeMonkey** [comment]
check if you have all peer dependencies installed

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/614

**Comment by KillerCodeMonkey** [comment]
should be working with https://github.com/KillerCodeMonkey/ngx-quill/releases/tag/7.3.11
