### ISSUE TITLE
Refresh custom toolbar

### ISSUE THREAD

**Issue by Yexan** [KillerCodeMonkey/ngx-quill#662]
Hi Bengt,

When a custom toolbar is created, `select` elements are replaced by custom elements `span.ql-picker` and some `ql-picker-options`.

I would like to know how I can trigger an update of this content when selects are build with `*ngFor` values that could change.

I got 2 exemples to illustrate this implementations : 
 - https://stackblitz.com/edit/ng-quill-editor-2
In that case, you have one custom configuration, the font size and line height list doesn't change, everything works fine.

- https://stackblitz.com/edit/ng-quill-editor 
In that case, I tried to bind a different config for font size and line heights for each zones.
It can't work because toolbar DOM is already initialized and the `option *ngFor="..."` is replaced by the custom select.

I noticed that in order to work, I need the toolbar component to be in the DOM when my editor component is declared (because it uses `modules = { toolbar: '#domElem', ...`) so I can't just use a `*ngIf` on the toolbar or something like this to rebuild the toolbar automatically.

Note, by writing this, I had the idea to wrap only the content of the toolbar in an *ngIf : 
https://stackblitz.com/edit/ng-quill-editor-3
But still, looks like I need to trigger the transformation from `select` to `ql-picker-options` :) 

It's not a bug but more a question about the lifecycle of the component :) 

Thanks for your awesome help (and I didn't have the time to add exmples on ngx-quill-exemples repo yet but that's still on my mind :))
Cheers

**Comment by KillerCodeMonkey** [comment]
to be honest, i never tried such things, :) 

But i know, that, because QuillJS is written in native JavaScript the toolbar has to be completly rendered before the Quill instance is created.

The Quill instance in ngx-quill is done in the ngAfterViewInit lifecycle hook of angular.

But i think you can just try to create your toolbar programmatically:
https://github.com/quilljs/quill/blob/develop/modules/toolbar.js#L162

After onEditorCreated use the quill instance passed as parameter and get the toolbar module and add your controls :)

**Comment by Yexan** [comment]
Thanks for your reply.
The main issue for me is that the DOM of my toolbar need to change as the select options won't be the same, not only buttons.

I tried to recreate the toolbar that way https://stackblitz.com/edit/ng-quill-editor-4?file=src/app/editor/text-layer-editor.service.ts but doesn't seems to work as I use Parchment attributor styles it doesn't seems to declare them as Format. (Of course the doc of parchment is not very well documented :/)

I tried to use the methods your pointed out too but I might not have a good approach.

If you got any other leads I'm all ears :)
Thanks !

**Comment by KillerCodeMonkey** [comment]
Sorry but i think you tried everything i know :).

Maybe ask this question directly in the quill repo?

**Comment by KillerCodeMonkey** [comment]
@Yexan so can this issue here be closed?

**Comment by Yexan** [comment]
Well, I think a found a lead, I'm gonna share this if it could help someone later : https://stackblitz.com/edit/ng-quill-editor-5 

The idea was to wrap  the toolbar component and the editor component in an `ngIf` to make sure it will re-render every time and you can pass new config options every time on toolbar creation.
It's still a not 100% working on the exemple but I think I know how to fix that in my more complex project. :) 

Thanks for your time !

**Comment by tom999** [comment]
Had same problem with Plkaceholder Plugin.
Ans this solution worked for me with Vue.JS and v-if.
Thank
