### ISSUE TITLE
Quill editor showing the wrong character count

### ISSUE THREAD

**Issue by jayaramasaipavanmanda** [KillerCodeMonkey/ngx-quill#664]
I have entered only one character in quill and it is showing the length as 2. here is the stack blitz demo `https://stackblitz.com/edit/quill-editor-vesbcp?embed=1&file=src/app/app.component.ts`

Open the link enter a character and observe on the console, it is showing length as 2.

**Comment by KillerCodeMonkey** [comment]
Yes, this not a ngx-quill issue.

quill is adding a `\n`  at the end of the insert.

Even when the editor is empty, there is a `\n` in it
