### ISSUE TITLE
Syntax highlights of code not working

### ISSUE THREAD

**Issue by toshiro812** [KillerCodeMonkey/ngx-quill#665]
Hello! Check pls syntax highlight feature. It seems like not working.

**Config:**
angular 8.2.13
ngx-quill 7.3.11
quill 1.3.7
highlight.js 9.12.0

I checked advanced demo app. Same story.

Thanks!

**Comment by KillerCodeMonkey** [comment]
fixed it:
https://killercodemonkey.github.io/ngx-quill-example/

quilljs seems like it does not work with latest highlight.js ?!
and katex formula integration was broken. So i changed this also.
