### ISSUE TITLE
Create a custom toolbar for the editor

### ISSUE THREAD

**Issue by kolomu** [KillerCodeMonkey/ngx-quill#67]
Hello ,

first things first, the editor is very nice and it works like a charm! I really appreciate it.

I'm trying to create a custom toolbar. For elements like underline or bold it works. However I don't know how to handle the nested objects. E.g. creating a button for a bullet list.

My code is as follows:
```
 <quill-editor [style]="{height: '450px'}" [(ngModel)]="notesInput" name="notesInput">
        <div quill-editor-toolbar>
 <span class="ql-formats">
                <button class="ql-bold" [title]="'Bold'"></button>
              </span> <!-- // Works perfect -->
     <span class="ql-formats">
              <button class="ql-list ql-bullet" [title]="list-bullet"></button>
           </span> <!-- // This is probably wrong but I can't figure out  how it's correctly written. -->
</quill-editor>
```

Kind regards

**Comment by KillerCodeMonkey** [comment]
Did you checkout out my example repository?
https://killercodemonkey.github.io/ngx-quill-example/

the last editor has a custom toolbar with a custom font dropdown.

The source-repo: https://github.com/killerCodeMonkey/ngx-quill-example

and simply answer --> use a HTML-Select element ;)

```
<quill-editor>
  <div quill-editor-toolbar>
    <span class="ql-formats">
      <select class="ql-font">
        <option value="aref">Aref Ruqaa</option>
        <option value="mirza">Mirza</option>
        <option selected>Roboto</option>
      </select>
    </span>
  </div>
</quill-editor>
```
