### ISSUE TITLE
Not updating form valid state inside form tag

### ISSUE THREAD

**Issue by MichaelPruefer** [KillerCodeMonkey/ngx-quill#670]
When using 
```html
<form (ngSubmit)="saveTextTemplate()" #textTemplateForm="ngForm">
    <quill-editor [(ngModel)]="template" name="template" [required]="true" [maxlength]="4000"></quill-editor>
    <button type="submit" [disabled]="!textTemplateForm.form.valid">
</form>
```

the submit-button is never disabled. Neither when template is empty or template has more than 4000 characters.

How to embed quill-editor with an existing form with validation?

**Comment by KillerCodeMonkey** [comment]
here is an example:
https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/no-toolbar

you can find the live demo here:
https://killercodemonkey.github.io/ngx-quill-example/

the demo editor with the title:
Editor without toolbar + readonly, required and formControl + maxlength 10 chars

if the control is invalid the border is red and dashed :)

BTW: i have a custom maxlength property: `maxLength` with a uppercase L. and i would use reactiveForm when ever possible.

**Comment by MichaelPruefer** [comment]
Hi,

i know i can make the border red if I add css with `.ng-invalid: { border: 1px solid red }` 
But that is not what i want to achieve.

I have a Submit-Button and it should only be clickable/enabled if my entire form is valid
`<button type="submit" [disabled]="!textTemplateForm.form.valid">`
My current workaround is to set 
`<button type="submit" [disabled]="!textTemplateForm.form.valid || template.length === 0 || template.length > 4000">`
But this seems a bit odd.

Unfortunately i can not switch to reactive forms.

Changed `maxlength` to 'maxLength` with no changes in behavior.

**Comment by KillerCodeMonkey** [comment]
but if ng-invalid class is added correctly?

because then the form validation works.
If i have time i will try to check a template driven example.

**Comment by MichaelPruefer** [comment]
Yes the ng-invalid class is added correctly.

**Comment by KillerCodeMonkey** [comment]
added an example to my demo repo
https://killercodemonkey.github.io/ngx-quill-example

Editor with the title: NgModel + Validation
it is using required and maxLength, you can see that the form and model state valid states are changing, so everything is working as expected.
