### ISSUE TITLE
Difference of formatting / render between quill-editor and quill-view component

### ISSUE THREAD

**Issue by Yexan** [KillerCodeMonkey/ngx-quill#671]
Hi :)

I've got a pretty weird issue and would like to know if you could have some leads on that 😄

You already saw some exemples of what I'm building, with some `quill-view` to display multiple zones of content and a `quill-editor` popping on the top of a zone, on click, to modify the content.

My content is stored in DB (legacy) letter by letter with every style attribute attached to it.
I made a simple converter to wrap each letters in a `span` with the relative styling and wrap each sentences in `p` tags

Something like this : 
```html
<p style="text-align: center;">
  <span style="font-size: 35px; color: rgb(115, 115, 115);">H</span>
  <span style="font-size: 35px; color: rgb(115, 115, 115);">E</span>
  <span style="font-size: 35px; color: rgb(115, 115, 115);">L</span>
  <span style="font-size: 35px; color: rgb(115, 115, 115);">L</span>
  <span style="font-size: 35px; color: rgb(115, 115, 115);">0</span>
</p>
```

What's nice with quill is that when I open the `quill-editor` component, the content will be automatically transformed to a nice 

```html
<p style="text-align: center;">
  <span style="font-size: 35px; color: rgb(115, 115, 115);">HELLO</span>
</p>
```

Regrouping all the children element with the same styling together. Neat.

But, it does not seems to make this transform on the `quill-view`.
Or at least it replace things like this : 

```html 
<p class="ql-align-center">
  <span style="color: rgb(115, 115, 115);">HELLO</span>
</p>
```

So it transform inline style to classes and remove some of the style.
I thought it would be because the `quill-view` has not access to the modules, but I've set the `[modules]="modules"` on the component.

What's _fun_ is : when I arrive on the page, the style is broken, then if I open the editor component and modify the content or don't modify, close, change page and come back to this page, it's displayed correctly. (By page I don't mean browser page but in my app I have multiple pages with editable zones)

I tried to trigger manually some `quillEditor.clipboard.convert(value)` on it but well, with no success from now.

Tried to play around with `domSanitizer.sanitize(SecurityContext.HTML, value)` too but same result.

If you got some leads on that I'm all ears.
Thanks !

**Comment by KillerCodeMonkey** [comment]
if i can throw in a litte hint:

try to debug the values of the `valueSetter` methods of both components.

or you need to register the inline styles where you are using the view component again?

**Comment by KillerCodeMonkey** [comment]
And if you are using inline style just use quill-view-html component.

**Comment by Yexan** [comment]
Thanks ! I'm gonna dig into it and let you know !

**Comment by KillerCodeMonkey** [comment]
feel free to send me a PR if something is inconsistent between the editor and the view component

**Comment by Yexan** [comment]
Well, for now with the `quill-view-html` if I make some adjustment on my side It nearly works.
It's still formatted with every letters in different spans and not child elements grouped if they have the same style.

So it seems alright but it breaks a feature I had, to select the whole world, for exemple, when you click on an element. :S

**Comment by KillerCodeMonkey** [comment]
Then You have to check or debug the value settee functions.

In General If the Format is html i use the Clipboard Convert method to
transform the content to valid and quill-parsable HTML.



Adrien Martinet <notifications@github.com> schrieb am Do., 5. Dez. 2019,
17:26:

**Comment by Yexan** [comment]
Well, 
I tried a lot of things, my main issues were : 
 - _I can't succeed to format with the right inline style version regrouped as described earlier._
I tried to use a service to convert the data, it returns a Delta, not HTML so I insert it to an hidden editor, retrieved the content, but even if I load the same modules as in my editor, it did not recognize my formats so it remove things like font-family, etc.

 - _It's not really possible to have one toolbar for multiple editor_
Because if you click on a second editor zone with the same toolbar it will modify your old selection of the first editor.

 - _It's tricky to reload the toolbar to handle different format configs per selected zone._
I tried it, you can do it by wrapping your components in ngIf to recreate them on click with different configs. But then you can have some not found formats when you want to display things ¯\_(ツ)_/¯

So, for now, I'll try an other approach not something I really like but it will work, I won't have too much editor component at the same time (2 or 3 max) so it will be ok.

Here is an exemple :
https://stackblitz.com/edit/ng-quill-editor-7?file=src%2Fapp%2Fviewer%2Fviewer.component.html

(I haven't take the time to remove what's useless now) the main idea was to remove the quill view components,  and use some `quill-editor` and declare a toolbar for each editor zones.
Then I just have to show the right one. Basic but it'll work.

(At least I haven't try with different format configs for now)


Thanks for your leads and your always very fast replies ! 🙏🥇
If only quill js lib was that well maintained ... 😅
Cheers, and enjoy your weekend 😊

**Comment by KillerCodeMonkey** [comment]
but did you found any difference in how the quill-view and quill-editor handles your content?

**Comment by Yexan** [comment]
Well not really, I think It might be due to some issues with format registering.
It's the only way I could understand what happen.
