### ISSUE TITLE
Shift toolbar to bottom without using customtoolbar

### ISSUE THREAD

**Issue by JosiFan** [KillerCodeMonkey/ngx-quill#676]
I was looking for ways to have the toolbar at the bottom. There is the method of using a custom toolbar however I want the full toolbar functionality and at the same time do not want to declare all the explicit html elements for the custom toolbar. Can it be done by simply changing a setting?

**Comment by KillerCodeMonkey** [comment]
check out the readme:

customToolbarPosition - Input/Property and set it to "bottom" ;-)

**Comment by JosiFan** [comment]
That means that I would have to do this right.
`<quill-editor customToolbarPosition="bottom" [style]="{height: '200px'}" [(ngModel)]="quilled" name="campaignCreation">
                        <div quill-editor-toolbar></div>
  </quill-editor>`
Then how would I declare a custom toolbar with the full options

**Comment by KillerCodeMonkey** [comment]
without `<div quill-editor-toolbar></div>`

**Comment by JosiFan** [comment]
So the customToolbarPosition="bottom" wouldn't work if I am not using a custom toolbar. So if I wanted a toolbar with full options I would have to explicitly create a custom toolbar with each option in html code.

**Comment by KillerCodeMonkey** [comment]
`<quill-editor customToolbarPosition="bottom" [style]="{height: '200px'}" [(ngModel)]="quilled" name="campaignCreation"> </quill-editor>`

would render a toolbar with all default formats at bottom position.

You can configure toolbarmodules via the global config (check the readme) or with the modules-Input/Property (check the readme and the example repo), if some formats are missing.

There is no need to create a custom toolbar.

**Comment by JosiFan** [comment]
`<quill-editor customToolbarPosition="bottom" [style]="{height: '200px'}" [(ngModel)]="quilled" name="campaignCreation"> </quill-editor>`

Shucks this isn't working, I'll go take a look around. Thanks!

**Comment by KillerCodeMonkey** [comment]
sorry you are right. the custom position only works with a custom toolbar. because quilljs does not support toolbar positioning by default.

Shot to nothing ^^: try to style it with css - flexbox - flex-wrap-reverse. if the toolbar comes before the editor container in the dom, add display: flex to the parent container and add flex-wrap-reverse

**Comment by JosiFan** [comment]
Oh noes. Okay thanks!

**Comment by temideewan** [comment]
You could add a wrapper class to the parent div, set it as a flexbox and then change the order of the toolbar

```.wrapper_class{
display: flex;
flex-direction: column;
}
.wrapper_class .toolbar_class{
  order: 1;
}
.wrapper_class .content_class{
  order: 0;
}
```
