### ISSUE TITLE
Angular + Firefox + Quill + ImageResize = selection problem

### ISSUE THREAD

**Issue by kirilmitev** [KillerCodeMonkey/ngx-quill#685]
Hey there,

I stumbled upon the following peculiar problem:
1. Insert an image followed by some text
2. Select image and press DEL
3. The first letter after the image is selected

This non-empty selection after deleting an image is unexpected. 
You can test this on your examples-page where ImageResize is demonstrated.

Example:
Say the user wants to change the image with a different one. He selects the current image, presses the DEL and then clicks on the Toolsbar-Button "image" to add the new image. The result will be a missing first letter from our text. This first letter was replaced with the newly added image, because it was selected after deleting the old image.

The problem does not occur when:
1. Firefox + Quill + ImageResize (i.e. without Angular). You can test this with the example plunker of the ImageResizeModule.
2. Chrome + Angular + Quill + ImageResize. You can test this in your examples-page where ImageResize is demonstrated.

Looking at the code of ImageResize we have the following:
```
checkImage = (evt) => {
    if (this.img) {
        if (evt.keyCode == 46 || evt.keyCode == 8) {
            window.Quill.find(this.img).deleteAt(0);
        }
        this.hide();
    }
};
```
where Quill.find() returns a blot and deleteAt() deletes this blot. This looks OK to me, so I am not sure whether the problem is with ImageResize, or with Quill, or with Firefox, or maybe with Angular.

**Comment by KillerCodeMonkey** [comment]
This is the ngx-quill repo, and i only provide the angular wrapper for quill.

Soooo maybe you should ask that at the quilljs repo ?

**Comment by kirilmitev** [comment]
You are right, this is not the correct repo for my issue, I'm sorry. 
Actually, in our Angular project we are using pure QuillJS (i.e. without your wrapper) and have the described problem.

**Comment by KillerCodeMonkey** [comment]
it also happens with my wrapper.

But in general i think it is a image resize module problem.

**Comment by kirilmitev** [comment]
ImageResize has only 203 lines of code and I don't see anything wrong there, but maybe ...
Anyways, thank you for your quick responses!

**Comment by KillerCodeMonkey** [comment]
I think the "selection" is not done correctly.
So you are selecting the image and delete it, so the current selection should be reset.
