### ISSUE TITLE
The hasFocus() method does not return the right result

### ISSUE THREAD

**Issue by GitHubish** [KillerCodeMonkey/ngx-quill#686]
I have a @HostListener on my component allowing me to intercept the copy/paste in the editor in order to parse the text on the server side. And I use the ngx-quill hasFocus() method to know if the focus is on the editor in order to pass my function the cursor position. And I notice that systematically the method returns false. This result is always the same no matter where or when I call it. 

This is a bug, isn't it? Thanks

**Comment by KillerCodeMonkey** [comment]
The Output is called onFocus and it is only emitting a value when the
Editor Container gets the First selection.

In General You should use angulars isPlatformServer function to check If
You are on Serverside and If You are on Clientside You can simple use the
API  of quill to get the current selection in the Editor. If there is No
range Set, there is no Focus in the Editor


GitPublish <notifications@github.com> schrieb am Mi., 18. Dez. 2019, 16:18:

**Comment by GitHubish** [comment]
Ok I see indeed that the problem seems to be in QuillJs, when we try to call the hasFocus() method as in the example below, the return is always false.

`@ViewChild(QuillEditorComponent, { static: true }) editor: QuillEditorComponent;`
--
`something() {
   if (this.editor.quillEditor.hasFocus() ) {
     //we'll never get here even if the focus is on editor.
   }
}`

I'm going to create an issue on the QuillJS github. Unless I'm wrong?

**Comment by KillerCodeMonkey** [comment]
Yep this is the native quilljs API.

But You could simply listen on ngx-quill onFocus and onBlur and store IT in
your component.



GitPublish <notifications@github.com> schrieb am Mi., 18. Dez. 2019, 17:39:

**Comment by GitHubish** [comment]
Yes, I was able to have the behaviour I wanted without using this method. I close the ticket thanks
