### ISSUE TITLE
Show custom error message

### ISSUE THREAD

**Issue by allahyar** [KillerCodeMonkey/ngx-quill#690]
I want to show custom error messages from validator , use local variable but don't access to touched event and errors property.

```
<quill-editor
			[(ngModel)]="value"
			[placeholder]="placeHolder"
			[maxLength]="max"
			[minLength]="min"
			(change)="onChange($event)"
			(keyup)="onChange($event)"
			#el
			[required]="required"></quill-editor>

		<div *ngIf="el.touched && el.errors && el.errors.required" class="invalid-feedback">
			{{'VALIDATE.REQUIRED'|translate}}
		</div>
```

**Comment by KillerCodeMonkey** [comment]
if you want to access the errors and model state you need to grab the model reference and not the component element...

https://angular.io/api/forms/NgModel#using-ngmodel-within-a-form

https://killercodemonkey.github.io/ngx-quill-example/ - the NgModel + Validation example uses the ngModel ref to show if the model is valid or invalid.

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/model-validation/model-validation.component.html

**Comment by KillerCodeMonkey** [comment]
does it work? then feel free to close the issue

**Comment by KillerCodeMonkey** [comment]
did you solved it?
