### ISSUE TITLE
How to create a custom HTML tag?

### ISSUE THREAD

**Issue by aswinrajeev** [KillerCodeMonkey/ngx-quill#692]
I wanted to create a custom HTML tag to be interpreted by Nix-Quill. How can I do it? Can someone please help.

**Comment by KillerCodeMonkey** [comment]
Just Checkout the quill documentation how to create custom modules Formats
and blots.


Aswin Rajeev <notifications@github.com> schrieb am Sa., 21. Dez. 2019,
08:00:
