### ISSUE TITLE
How to add custom fonts?

### ISSUE THREAD

**Issue by nilamJadhavClarion** [KillerCodeMonkey/ngx-quill#698]
Hi, I am trying to provide custom font list but it is not working correctly.Please find below code snippet.

In ts:

```TS
  public editorModules = {
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'],
      [{ 'header': 1 }, { 'header': 2 }],
      [{ 'font': ['Arial','Arial Black','Calibri','Futura'] }],
    ]
  }
```

In html:

```HTML
 <quill-editor #quill  [styles]="{minHeight: '100px'}"  [modules]="editorModules"
   [(ngModel)]="letterText" (onContentChanged)="saveTextEditorContent($event)">
  </quill-editor>
```

![FontIssue](https://user-images.githubusercontent.com/56865581/71474236-6dfaf480-27d2-11ea-845f-4ae73440216c.PNG)

**Comment by KillerCodeMonkey** [comment]
Checkout the quilljs docs and the ngx-quill example repo linked in the readme.

You need to register this fonts first.

https://quilljs.com/guides/how-to-customize-quill/#customizing-attributors
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/8fbcde23bbce90b291a7c8881c72b556e9efd416/src/app/custom-toolbar/custom-toolbar.component.ts
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/5cd7d1450b6aa2d8f8f7d9a1a29d15a1cfcd485d/src/styles.css#L15

You need to whitelist custom fonts and then you need to add the generated quill format css classes for you font names.

**Comment by almas77abolfazl** [comment]
**First, you must define your fonts in the whitelist.**

    import Quill from 'quill';
    
    const FontAttributor = Quill.import('attributors/class/font');
    FontAttributor.whitelist = [
      'IRANSans',
      'roboto',
      'cursive',
      'fantasy',
      'monospace'
    ];
    Quill.register(FontAttributor, true);


**Then you have to add the fonts to the config inside your component.**

    quillConfig: QuillModules = {
        toolbar: {
          container: [
            ['bold', 'italic', 'underline', 'strike'],
            [{ size: ['small', false, 'large', 'huge'] }],
            [{ font: ['IRANSans', 'roboto', 'cursive', 'fantasy', 'monospace'] }],
            [{ align: [] }],
            ['clean'],
            ['link'],
          ]
        }
      };


**By applying these changes, your fonts will be added to the list of fonts and will get the data-value attribute.**


[![enter image description here][1]][1]

**After that, you need to add a series of styles to the app.**



    .ql-snow .ql-picker-options .ql-picker-item {
      font-family: #{attr(data-value)};
      &::before {
        content: attr(data-value) !important;
      }
    }

    .ql-snow .ql-picker.ql-font .ql-picker-label::before,
    .ql-snow .ql-picker.ql-font .ql-picker-item::before {
      content: attr(data-value) !important;
    }

Finally, to apply the font-family on the text inside the editor, you can use sass,sccs like this.


    $text-editor-fonts: 'IRANSans', 'roboto', 'cursive', 'fantasy', 'monospace';
    
    @each $text-editor-font in $text-editor-fonts {
      .ql-font-#{$text-editor-font} {
        font-family: $text-editor-font;
      }
    }

  [1]: https://i.stack.imgur.com/ERsEZ.png

**Comment by aagache** [comment]
For fonts with name containing spaces, it's worth having a look at https://github.com/quilljs/quill/issues/598 as well. Else, fonts like "Times New Roman" won't work with the implementation above.

**Comment by Samyssmile** [comment]
Fully working example with angular 18 and without need to customize html toolbar. 
[](https://github.com/Samyssmile/quill-angular-example)
