### ISSUE TITLE
rel="noopener noreferrer" on links when text is processed with ngx-quill

### ISSUE THREAD

**Issue by Cavayman** [KillerCodeMonkey/ngx-quill#699]
Hi there  😄 
Facing strange behaviour with ngx-quill.
I have text that includes links with already added attributes rel="noopener noreferrer".
When I try to edit somehow that text, ng quill removes all those attributes from links.
The issue that I am facing because of this behaviour:
I see different text length when editing that decreases after I add some charts.

I am using snow theme and found that issue with quilljs, but it was fixed in 1.3.7 as I understand.

I am using "ngx-quill": "7.3.2", also have "quill": "1.3.7"

**Comment by KillerCodeMonkey** [comment]
Okay but i think this is still a quill issue.

could you check if this problem occurs using simply quilljs without ngx-quill (just plain javascript and an editor reproducing the behavior)?

This is only a wrapper and i use the quill api to put model/control values in the editor.
So i think quill strips this additional attributes.

**Comment by KillerCodeMonkey** [comment]
Testet it and it works. 

I set

```HTML
<ol><li><sup>test</sup></li></ol>
<div><a href="https://google.de" rel="noopener noreferrer" target="_blank">asdfasdf</a></div>
```

as control value.

<img width="1092" alt="Bildschirmfoto 2019-12-26 um 15 51 51" src="https://user-images.githubusercontent.com/2264672/71480092-bb3d8d00-27f7-11ea-81d9-d87c718ab800.png">

**Comment by KillerCodeMonkey** [comment]
https://killercodemonkey.github.io/ngx-quill-example/

The Format - HTML editor. After a littel timeout this content is set and the rel attribute is not removed

**Comment by Cavayman** [comment]
> https://killercodemonkey.github.io/ngx-quill-example/
> 
> The Format - HTML editor. After a little timeout, this content is set and the rel attribute is not removed

Thanks, I see and actually strange text length behavior is more dealing with quill 1.3.7 that automatically adds rel. But few times when I tested it also showed me behaviour when quill removed that attribute automatically
