### ISSUE TITLE
Source code has linting errors

### ISSUE THREAD

**Issue by rodneyjoyce** [KillerCodeMonkey/ngx-quill#7]
Hi again,

When I include the SRC version, my AngularCLI (with strict linting) includes any issues found in the ngx-quill node module:

[](http://screencast.com/t/RM1sHaHeR)

I am not sure why it is doing it but no other node modules do this (my linting is set to exclude Node Modules). Perhaps it is something to do with the fact that it is using the source?

**Comment by KillerCodeMonkey** [comment]
How can i activate strict linting? Or if you want to participate --> fix the linting errors and make a PR

**Comment by KillerCodeMonkey** [comment]
there was one linting error about a missing whitespace. fixed that.

Please check the new version, if everything works for you

**Comment by rodneyjoyce** [comment]
Sorry, my screenshot of the actual errors seems to have been removed from my original post:

Here are the errors I get - with these stricter TS settings:
 "baseUrl": "",
    "declaration": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "noImplicitReturns": true,
    "skipLibCheck": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
in the  tsconfig.json file.

Here is the output
default] C:\Git\QueMesaAdmin\QueMesaAdminApp\node_modules\ngx-quill\src\quill\quill-editor.component.ts:52:10
    Object literal's property 'color' implicitly has an 'any[]' type.
[default] C:\Git\QueMesaAdmin\QueMesaAdminApp\node_modules\ngx-quill\src\quill\quill-editor.component.ts:52:27
    Object literal's property 'background' implicitly has an 'any[]' type.
[default] C:\Git\QueMesaAdmin\QueMesaAdminApp\node_modules\ngx-quill\src\quill\quill-editor.component.ts:53:10
    Object literal's property 'font' implicitly has an 'any[]' type.
[default] C:\Git\QueMesaAdmin\QueMesaAdminApp\node_modules\ngx-quill\src\quill\quill-editor.component.ts:54:10
    Object literal's property 'align' implicitly has an 'any[]' type.
[default] C:\Git\QueMesaAdmin\QueMesaAdminApp\node_modules\ngx-quill\src\quill\quill-editor.component.ts:95:46
    Parameter 'range' implicitly has an 'any' type.
[default] C:\Git\QueMesaAdmin\QueMesaAdminApp\node_modules\ngx-quill\src\quill\quill-editor.component.ts:102:41
    Parameter 'delta' implicitly has an 'any' type.
[default] C:\Git\QueMesaAdmin\QueMesaAdminApp\node_modules\ngx-quill\src\quill\quill-editor.component.ts:102:48
    Parameter 'oldDelta' implicitly has an 'any' type.
[default] C:\Git\QueMesaAdmin\QueMesaAdminApp\node_modules\ngx-quill\src\quill\quill-editor.component.ts:102:58

**Comment by KillerCodeMonkey** [comment]
sry, but could you guide how you lint your code?

i added the strict rules to my tsconfig and run `ng lint` .. no probs.

**Comment by rodneyjoyce** [comment]
Did you restart ng serve to pick up the new rules? It might also be related to how you have included it: I use  import { QuillModule } from 'ngx-quill/src/quill/quill.module';

**Comment by KillerCodeMonkey** [comment]
checkout v0.1.3 please and close issue, if the linting errors are gone

**Comment by rodneyjoyce** [comment]
Yes, all fixed - thanks for the quick response!
