### ISSUE TITLE
How to configurate scrollingContainer in ionic v4?

### ISSUE THREAD

**Issue by sid-ihycq** [KillerCodeMonkey/ngx-quill#701]
When I insert an image the editor will jump to the top of current page. 
It's simply to config the scrollingContainer arg with normal css selectors in angular web project. 

But in ionic v4, shadow dom is used everywhere. I tried to pass ion-content node and main.inner-scroll node in the shadow dom root, but both were wrong. 
Could anyone give some suggestion?

**Comment by KillerCodeMonkey** [comment]
https://quilljs.com/docs/configuration/#scrollingcontainer

it can be a dom element or css selector. just try to pass a css selector without class names or use a dom element instead of a css selector.

**Comment by sid-ihycq** [comment]
> https://quilljs.com/docs/configuration/#scrollingcontainer
> 
> it can be a dom element or css selector. just try to pass a css selector without class names or use a dom element instead of a css selector.

thanks very much. I found that I have already bind an ionScroll handler, so maybe the library's handler was covered. 
```

<ion-content scrollEvents="true" (ionScroll)="onScroll()">
    <my-component></my-component>
</ion-content>

@Component({
    selector: 'my-component',
    template: '<quill-editor [scrollingContainer]="scrollingNode"></quill-editor>',
})
class MyComponent {
    scrollingNode: Node;

    constructor(private eleRef: ElementRef){ }

    onEditorCreated(quill: Quill) {
        this.scrollingNode = (this.eleRef.nativeElement as HTMLElement).parentNode;
    }
}

```
i removed my ionScroll handler and then the problem disappeared.
so i have to bind my handler on another event:

`<ion-content scrollEvents="true" (ionScrollEnd)="onScroll()">`

now it's ok, except that my scroll handler has a little delay.
