### ISSUE TITLE
onFocus event not always triggered

### ISSUE THREAD

**Issue by bbottema** [KillerCodeMonkey/ngx-quill#707]
When you type in one Quill editor and keep typing while clicking in another Quill editor, the focus event doesn't trigger of the second editor.

Could be a bug in the Quill library, but I found it while using the `onFocus` binding.

`onBlur` always triggers though.

**Comment by KillerCodeMonkey** [comment]
In general the `onFocus` event is just a wrapper that listens on the quill event "selection-change".
If the new range is `null` a `onBlur` is triggered.
If the old range is `null` and there is a valid value for the new range `onFocus` is triggered.

This happens only when there are some observers for the Outputs in case of performance :-)

https://github.com/KillerCodeMonkey/ngx-quill/blob/master/src/quill-editor.component.ts#L361

Is it possible to share a stackblitz or demo ?

**Comment by bbottema** [comment]
Do you have a starter for me to edit, with Angular 8 and latest ngx-quill?

**Comment by KillerCodeMonkey** [comment]
i have my demo repo https://killercodemonkey.github.io/ngx-quill-example/

there is also a focus event on the first editor 
https://github.com/KillerCodeMonkey/ngx-quill-example

**Comment by bbottema** [comment]
Yeah a stackblitz starter would have been nice, but I made one myself which reproduces the problem:

- https://stackblitz.com/edit/angular-y6vzme

On focus, the top label will indicate the currently active one, A or B. When you type a lot and while typing click in the second editor the onFocus event doesn't fire and the label will indicate the wrong editor as being active.

**Comment by KillerCodeMonkey** [comment]
@bbottema i created a codepen with plain quilljs
https://codepen.io/KillerCodeMonkey/pen/PowOvmL

Listening on the selection-change event, and typing real quick while switching the editor the same behaviour occurs.
Check the console.log output.

**Comment by bbottema** [comment]
Ok, I raised issue [#2895](https://github.com/quilljs/quill/issues/2895) over at QuillJs.
