### ISSUE TITLE
Converting ngx-quill html text to an email html text

### ISSUE THREAD

**Issue by liubomyrskalskiy** [KillerCodeMonkey/ngx-quill#709]
I've got an task from an interview to create a simple mail service that provide sending emails, and it must have a Rich text editor, so i decided to use ngx-quill. I done my work but met an issue that emails i sent don't have proper formatting, for example if I make text align center, it doesn't appear in a mail I sent. I saw than ngx-quill provides it's own stile classes such as ql-align-center, but how should I convert it so I can normally see edited text in my mail

**Comment by liubomyrskalskiy** [comment]
P. S. I use Angular 8

**Comment by KillerCodeMonkey** [comment]
this is a quilljs topic, because ngx-quill is just a wrapper for quilljs.

You can switch from class based to inline styling.
https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline

Or you can just add quilljs core css file or the content of that file to your email.

✌️

**Comment by liubomyrskalskiy** [comment]
I already read it, but I don't understand how to properly switch it. (Maybe I'm stupid) I use quill-editor tag with no js code, just configs

**Comment by KillerCodeMonkey** [comment]
yeah but as you see here:
https://quilljs.com/playground/#class-vs-inline-style

You have to know, that in general quilljs produces content with "classes".
To change that you need to add 

```JS
var BackgroundClass = Quill.import('attributors/class/background');
var ColorClass = Quill.import('attributors/class/color');
var SizeStyle = Quill.import('attributors/style/size');
Quill.register(BackgroundClass, true);
Quill.register(ColorClass, true);
Quill.register(SizeStyle, true);
```

+ all other formats you need

where you placed your editor. Like import them in the component / page you use the quill-editor component.

**Comment by liubomyrskalskiy** [comment]
It throw me warning that it "Cannot find name 'Quill'"

**Comment by KillerCodeMonkey** [comment]
yeah... because you need to import it first...

**Comment by KillerCodeMonkey** [comment]
just checkout my demo repo how to import Quill and use Quill.import
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/e1bd33b5ac9dc6e219bddeeb89f449e7c766e197/src/app/app.component.ts

All other information you will get from the quill js documentations and the quill the repo
