### ISSUE TITLE
Angular Universal & Anguar-CLI minimal starter won't build with ngx-quill

### ISSUE THREAD

**Issue by helix46** [KillerCodeMonkey/ngx-quill#71]
ERROR in ./node_modules/ngx-quill/src/quill-editor.component.ts
Module build failed: Error: Typescript emitted no output for c:\temp\universal-starter-ngx-quill\node_modules\ngx-quill\src\quill-editor.component.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358

**Steps to reproduce:**
git clone https://github.com/helix46/universal-starter-ngx-quill.git
cd universal-starter-ngx-quill
npm i
npm run build:static

Much appreciate your time

**Comment by KillerCodeMonkey** [comment]
could you clarify this issue a little bit more to me?

i do not get it :).

aot and prod releases should working. I do not know much about angular universal.

**Comment by KillerCodeMonkey** [comment]
@helix46 you need to switch .ts and .js https://github.com/helix46/universal-starter-ngx-quill/blob/0038216fde93bc7b2916bc000a0475ff9c600a82/webpack.server.config.js#L14

you should load first the .js and then .ts files.

**Comment by helix46** [comment]
Thanks, this works for build:dynamic, which meets my needs

**Comment by yharaskrik** [comment]
@helix46 Do you still have the code for [ https://github.com/helix46/universal-starter-ngx-quill.git](this repo)? I would love to see how you solved the ngx-quill universal issue.

**Comment by helix46** [comment]
@yharaskrik 

[https://github.com/helix46/test-cli-quill](url)
