### ISSUE TITLE
Ionic4 syntax not working

### ISSUE THREAD

**Issue by sid-ihycq** [KillerCodeMonkey/ngx-quill#717]
In my angular.json:
```
"styles": [
	"node_modules/highlight.js/scss/monokai-sublime.scss",
	...
],
"scripts": [
	"node_modules/highlight.js/lib/highlight.js",
	...
]
```

In my code，i use
```
QuillModule.forRoot({
	modules: {
		syntax: true
	}
}),
<quill-editor [modules]="modules" ..></quill-editor>
<quill-view [content]="content"></quill-view>
```

and the modules is 
```
modules = {
	...
	syntax: true,
}

```
It seems to be fine before, and i just found it not working yesterday.
I change <quill-view> to div，it's working again（I use JQuery .html() to set the content but not innerHtml, and then i can get the dom tree）。
```
<div class="ql-container ql-snow" style="border-width: 0;">
	<div class="ql-editor" #qlEditor></div>
</div>

```
I tried to use hljs.configure() but it's also not working. 
And in my angular web the same code runs fine.

**Comment by KillerCodeMonkey** [comment]
Check my ngx-quill-example i updated how to integrate Syntax highlighting a
few weeks ago.

And please clearify what is Not working.

And what has this to do with Ionic 4?

sid-ihycq <notifications@github.com> schrieb am Mi., 8. Jan. 2020, 05:17:

**Comment by KillerCodeMonkey** [comment]
did you solved this. This is also not an ngx-quill issue, ... More how to integrate highlightjs with ionic or in an angular cli project

**Comment by KillerCodeMonkey** [comment]
any updates?
