### ISSUE TITLE
Dynamic Reactive Form Document missing 

### ISSUE THREAD

**Issue by jm06487** [KillerCodeMonkey/ngx-quill#720]
I have a dynamic reactive form in my angular project.  I had issues trying to get the control to display anything I set for the value.   
After reading through several issues and documents I finally resolved my issue. 
I would like to present a template that I used to get it working. 
All functions work now as if it was the reactive form example you had. 

```
<div
  [formGroup]="group">
 <quill-editor
      #editor
      [required]="true"
      [maxLength]="20"
      [style]="{ border: '1px solid #dadada' }"
      [formControlName]="field.name"
    >
</div>
```

**Comment by KillerCodeMonkey** [comment]
and what is exactly your problem?

**Comment by jm06487** [comment]
When I use the component in a dynamic reactive form. It does not show any values that I might have updated for the controller. Example;  `this.group.patchValue({'editor': 'anything'}) `will not render on the page. It is updated in the form controller value only.    

This only happens if you use `[formControl]="field.name"`
 but works when I use `[formControlName]="field.name"`

**Comment by KillerCodeMonkey** [comment]
Ah okay If You are using Formcontrol You have to Pass a real Form control
reference.

When using formControlName You Pass the real Name as String of the Control
in the formgroup linked in the Form tag

jm06487 <notifications@github.com> schrieb am Do., 9. Jan. 2020, 16:48:
