### ISSUE TITLE
min-height as style-option

### ISSUE THREAD

**Issue by connectedSoul** [KillerCodeMonkey/ngx-quill#730]
Is there a possibility to initialize the editor with "min-height", such as:
<quill-editor [styles]="{min-height: '200px'}"></quill-editor>

I really like the auto-expanding feature, when typing/inserting text. 
However i would like to start out with 200px of minimal height. 
Fixed height with [styles]="{height: '200px'} lacks the auto-expanding feature.

Is it something for ngx-quill, or should it first be supported bei QuillJS?

**Comment by KillerCodeMonkey** [comment]
just set the minheight in your global.css/scss for the .ql-editor class?

**Comment by connectedSoul** [comment]
Thanks, should have thought of that. It works like a charm :)
