### ISSUE TITLE
Cannot read property 'kind' of undefined in angular 8.2.14

### ISSUE THREAD

**Issue by nombrekeff** [KillerCodeMonkey/ngx-quill#731]
I updated my dependencies yesterday, and when building --prod, it throws the following error:
```
ERROR in ./node_modules/ngx-quill/fesm2015/ngx-quill.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/manolo/Documents/Dev/work/rec/rec-admin-ngcli/rec-admin/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
```
This started happening with Angular `v8.2.14` and ngx-quill `v7.3.12`
This did not happen with Angular `v8.1.3`

Going back to ngx-quill `v7.3.1` fixes the issue, though...

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/635
https://github.com/KillerCodeMonkey/ngx-quill/issues/708
https://github.com/KillerCodeMonkey/ngx-quill/issues/620
https://github.com/KillerCodeMonkey/ngx-quill/issues/573

This is not a ngx-quill issue. more an angular and typescript one.

try upgrading typescript.
My demo repo linked in the readme is using angular 8 with the latest ngx-quill version in prod and aot build.

**Comment by KillerCodeMonkey** [comment]
https://github.com/angular/angular-cli/issues/15703
https://github.com/microsoft/TypeScript/issues/35717

**Comment by nombrekeff** [comment]
Oh, ok! Sorry about that! I didn't think about updating Typescript, I will try this then!
Thanks!
