### ISSUE TITLE
form Array edit nothing is showing 

### ISSUE THREAD

**Issue by satish666** [KillerCodeMonkey/ngx-quill#737]
I want to edit using angular form array and quill but nothing is showing in the quill editor. Data is coming but not rendering. 
`  <form [formGroup]="exampleForm">
    <div class="" fxLayout="column">
   
    
    <quill-editor [modules]="editorModules" formControlName="exampleQuestion" format="object"></quill-editor>
   

        <div formArrayName="steps" *ngFor="let step of exampleForm.get('steps').controls; let i = index;">
            <mat-toolbar color="primary" mat-elevation-z8 style="height: 30px;margin: 5px 0px 4px 0px;font-size: 15px;"  fxLayout="row" >
            
                <div fxFlex="90"  >
                    <span  >Step {{i+1}} </span>
                </div>
                <div fxLayoutAlign="space-around center ">
                    <a  style="color: white;cursor: pointer;" (click)="removeSteps()"><i class="material-icons">clear</i></a>
                </div>
            </mat-toolbar>
            <div [formGroupName]="i" >
            
            <quill-editor formControlName="theSteps" [modules]="editorModules"  format="object"  >
            
            </quill-editor>
             </div>
        </div>
        <mat-toolbar color="primary" mat-elevation-z8 style="height: 30px;margin: 1px 0px 4px 0px;font-size: 15px;"  fxLayout="row" >
                        
        <div fxFlex="90"  >
            <span  >Add Solution Step Wise </span>
        </div>
        <div fxLayoutAlign="space-around center ">
            <a  style="color: white;cursor: pointer;" (click)="addSteps()"><i class="material-icons">add</i></a>
        </div>
        </mat-toolbar>

    <button style="margin-top: 5px;" mat-raised-button color="primary" (click)="addExample()" *ngIf="exampleForm.valid">Add</button>
  </div>
  </form>`

`But after patching value `theSteps are not rendering But data is coming .Input is working

**Comment by KillerCodeMonkey** [comment]
Is it possible to provide an example as stackblitz , codepen or anything
else?

satish666 <notifications@github.com> schrieb am Do., 23. Jan. 2020, 18:05:

**Comment by satish666** [comment]
i got the solution. i was pushing without ops.  
One thing i want to ask "\n" becomes null in database 
Thanks for reply

**Comment by KillerCodeMonkey** [comment]
Yeah but that's your business. :) I can not change your handling of new
lines in textes. In general databases can handle new lines. So check your
Backend Code if special chars are removed :)

satish666 <notifications@github.com> schrieb am Do., 23. Jan. 2020, 18:19:

**Comment by satish666** [comment]
Okay thank You very much for Quill 👍
