### ISSUE TITLE
Fails under angular 5.0.0

### ISSUE THREAD

**Issue by wupaz** [KillerCodeMonkey/ngx-quill#74]
I try to start a completely fresh new App with Angular-cli 

Add nqx-quill (follow you setup your instructions)

ng Serve 

Result :

ERROR in ./node_modules/ngx-quill/src/quill.module.ts
Module build failed: Error: C:\tests\testquill\node_modules\ngx-quill\src\quill.module.ts is not part of the compilation output. Please check the other error messages for details.

**Comment by KillerCodeMonkey** [comment]
I do not know what changed in angular 5 and the New cli Version. Maybe you
Have to define the external dependencies somewhere?

Am 02.11.2017 20:07 schrieb "wupaz" <notifications@github.com>:

**Comment by vaags** [comment]
Can confirm this error. Afaik there should not be any .ts files inside node_modules as per Angular guidelines.

**Comment by KillerCodeMonkey** [comment]
i will only be able to look into this today evening or this weekend. Feel free to create a pull request, if you solved it on your own ;)

**Comment by KillerCodeMonkey** [comment]
see version v2.0.0

tested without angular-cli, but with angular 5 and 4 --> everything is working. there are no .ts files in aot-build, now :)

Would be nice if someone could test it - Reopen this issue if there are some problems.

**Comment by mattmcsparran** [comment]
I'm having the same issue with this.

`ERROR in ./node_modules/ngx-quill/src/quill.module.ts
Module build failed: Error:node_modules\ngx-quill\src\quill.module.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/ngx-quill/index.js 1:0-35
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts`


i'm also running v2.0.0.

**Comment by KillerCodeMonkey** [comment]
Do you need to configure external deps in the cli? I Have a demo repo
without cli and everything is working with angular 5.0. :S

Am 05.11.2017 18:39 schrieb "Matthew McSparran" <notifications@github.com>:

**Comment by mattmcsparran** [comment]
@vaags @wupaz @KillerCodeMonkey 

Found a fix that gets it to not fail.

Since Bengt incorporated AOT with the package, you need to tell angular cli to do that.

ng serve --aot.

runs with no problems.

can I add a pull request with that new information?

**Comment by KillerCodeMonkey** [comment]
Sure :). But it should work also without aot .. Strange. Thought there
would be more probs with aot build :D

Am 05.11.2017 18:55 schrieb "Matthew McSparran" <notifications@github.com>:

**Comment by mattmcsparran** [comment]
I'm not sure why it doesn't. I kept getting that failure when I would try to run it. I did some digging and tried a couple of different things and this worked. As of now, I don't have any issues, if I come across one, I'll respond here. For a "minor release", this new version definitely messed some things up.

**Comment by KillerCodeMonkey** [comment]
@mattmcsparran 
i found this issue for angular cli:
https://github.com/angular/angular-cli/issues/8284

**Comment by KillerCodeMonkey** [comment]
Especially these post clears it out. angular cli does not bundle external libs i think so you need to add them to your tsconfig.app.json:

https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325

**Comment by mattmcsparran** [comment]
I saw both of those but wasn't 100% sure on how to add those to it. I did try to remove the TS files after it was compiled to see if it would default to the JS files, but then I received an error with a ts file not being found.

**Comment by KillerCodeMonkey** [comment]
@mattmcsparran could you install ngx-quill@beta in your project?
ng serve should work. but now i get a curious error when i run `ng serve --aot`

```
Unexpected value 'QuillModule in /Users/bengtler/dev/ng-test/node_modules/ngx-quill/src/quill.module.d.ts' imported by the module 'AppModule in /Users/bengtler/dev/ng-test/src/app/app.module.ts'. Please add a @NgModule annotation.
```

Do i have to change something if i want to use aot build?

**Comment by mattmcsparran** [comment]
@KillerCodeMonkey i didn't change anything. i just did --aot. i'll try installing the beta

**Comment by nitinht1988** [comment]
any update on this? I am also getting error with ng serve command. But it is working fine with ng serve --aot.

ERROR in ./node_modules/ngx-quill/src/quill.module.ts Module build failed: Error:node_modules\ngx-quill\src\quill.module.ts is not part of the compilation output. Please check the other error messages for details. at AngularCompilerPlugin.getCompiledFile (node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23) at plugin.done.then (node_modules\@ngtools\webpack\src\loader.js:467:39) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7) @ ./node_modules/ngx-quill/index.js 1:0-35 @ ./src/app/app.module.ts @ ./src/main.ts @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by KillerCodeMonkey** [comment]
i released 2.0.2 it is working for me with ng serve now. But now i get 

Unexpected value 'QuillModule in /Users/bengtler/dev/ng-test/node_modules/ngx-quill/src/quill.module.d.ts' imported by the module 'AppModule in /Users/bengtler/dev/ng-test/src/app/app.module.ts'. Please add a @NgModule annotation

if i try aot -.- do not know why. does not changed anything critical in my aot build (only removed the nested node_modules folder)

**Comment by nitinht1988** [comment]
Hi @KillerCodeMonkey ,

I wish i could help you out solving out your issue but i am very new to angular. 
so you mean to say version 2.0.2 still has some issue. So should i upgrade to newer version or should i wait till above issue get resolved.

**Comment by KillerCodeMonkey** [comment]
go for it! ^^

if it is not working downgrade.. ngx-quill is not such a big lib, so it should be easy to go back.

ng serve works for me. but ng serve --aot not. if you are using ng serve it should work.

Would be nice if you could test ng serve --aot and give me feedback.

**Comment by nitinht1988** [comment]
Sure. Let me upgrade and check --aot.

**Comment by nitinht1988** [comment]
Hi @KillerCodeMonkey ,

Using ng serve -aot i am getting this error. ng serve is working fine:

ERROR in Error: Unexpected value 'QuillModule in C:/xampp/htdocs/matngular-latest/node_modules/ngx-quill/src/quill.
module.d.ts' imported by the module 'UIComponentsModule in C:/xampp/htdocs/matngular-latest/src/app/components/ui-c
omponents.module.ts'. Please add a @NgModule annotation.

**Comment by KillerCodeMonkey** [comment]
released 2.0.3 all builds should be fixed.

<img src="https://media.giphy.com/media/3oKIPf3C7HqqYBVcCk/giphy.gif">

**Comment by nitinht1988** [comment]
@KillerCodeMonkey  Thanks a lot !!! It is working !!!

**Comment by mattmcsparran** [comment]
What was the fix?

**Comment by KillerCodeMonkey** [comment]
Seems like i Have to remove all TS files from build outout. And do not add
aot files to a special folder.

So long story short. I changed my buildprocess a little bit.

Seems like angular cli changed their behaviour which files they in include
to their build process.

But it should work know in and case, with or without cli.

Am 06.11.2017 13:41 schrieb "Matthew McSparran" <notifications@github.com>:

**Comment by mattmcsparran** [comment]
@KillerCodeMonkey just tried it and it worked. thanks! i appreciate your help. Thanks for working so hard to get it all resolved.
