### ISSUE TITLE
problem with ngx-quill

### ISSUE THREAD

**Issue by rezafadaei** [KillerCodeMonkey/ngx-quill#740]
Hello Dear KillerCodeMonkey,
first of all thanks for your project and your example for make the App more beutiful with a Rich Text
but i have a problem i do exactly what you did on your example but didn't work!!!
i upddate core-js and reinstall ngx-quill but not working (device and browser);
thank you for your solution
![css](https://user-images.githubusercontent.com/48349006/73142557-76c03e00-4090-11ea-9e6a-579916e6e366.jpg)

**Comment by KillerCodeMonkey** [comment]
i think you missed to load / include the quill.core.css or quill.snow.css, because your screenshot looks exactly like this.

checkout the angular.json:

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/angular.json#L26
