### ISSUE TITLE
Feature Request: pressing enter will make two space line on edit mode (similar to final output)

### ISSUE THREAD

**Issue by maddy2894** [KillerCodeMonkey/ngx-quill#741]
How about having two space line when enter is pressed on edit mode? It will be a good way to tell the user how it will be on reading mode.

**Comment by KillerCodeMonkey** [comment]
Please open such feature requests on the quilljs repo.

i will only provide a wrapper around quilljs without extending the basic formatting behaviour.

And in general there should not be an empty line between texts, when pressing enter.

**Comment by KillerCodeMonkey** [comment]
@maddy2894  btw the output should look like the editor content. Maybe some stylings are missing?

it is a wysiwyg editor ... so ^^ as definition it should look similar
