### ISSUE TITLE
Issue in parsing multi line text

### ISSUE THREAD

**Issue by amitnatani** [KillerCodeMonkey/ngx-quill#749]
I am using v7.3.9 of ngx-quill.
My need is to retain the formatting of the text inputted in the editor.
I have put this text in the editor
![Screenshot from 2020-01-30 20-12-34](https://user-images.githubusercontent.com/13010051/73460193-1423b680-439e-11ea-9000-a269656facc6.png)

When I am using "innerText" property it is returning me
"Hello

Hi"

Here, One newline is getting added extra.

The Html content is:
`"<p>Hello</p><p>Hi</p>"`.

**Comment by KillerCodeMonkey** [comment]
and why are you using innerHtml?

You get the content through an `ngModel` `formControl` or via the `onContentChanged` output.

**Comment by KillerCodeMonkey** [comment]
@amitnatani if you simply want to work with text -> set the format to text. The default is html.

If you want to present the content somewhere else you the "view" components or keep in mind to include the quill css there as well.

Please check my example repo:
https://killercodemonkey.github.io/ngx-quill-example/

there is an editor for using simple text, html, and so on.
The code can be found here: https://github.com/killerCodeMonkey/ngx-quill-example

**Comment by amitnatani** [comment]
I got the text property in onContentChanged callback. But in this text, the custom tags that we have used in the description to mention users are not getting tracked. (We have used our custom design of tags in this)

**Comment by KillerCodeMonkey** [comment]
yeah but you should know if you are using the "text" it is plain text... so there are no html tags or anything else in there.

**Comment by amitnatani** [comment]
`<p>Hello <span class="mention" data-index="2" data-denotation-char="" data-id="148" data-display_name="Amit Natani" data-value="<a class=&quot;tag-item-user&quot;><span class=&quot;label&quot;> <img class=&quot;&quot; src=&quot;../assets/images/default_avatar.png&quot;>Amit Natani</span></a> " data-image_url="../assets/images/default_avatar.png" data-type="User">﻿<span contenteditable="false"><span class="ql-mention-denotation-char"></span><a class="tag-item-user"><span class="label"> <img class="" src="../assets/images/default_avatar.png">Amit Natani</span></a> </span>﻿</span> </p>`

My HTML is like this in the description. So I hope I should get "Hello Amit Natani" as text.

**Comment by KillerCodeMonkey** [comment]
@amitnatani yep but thats a thing of quill-mention or quilljs

So i do not know how exactly quilljs `getText` function works, but it does not recognizes the content of quill-mention outputs.

Just ask at the quill-mention repo, that their output is not recognized as "text".
Or ask at the quilljs repo the same :)
