### ISSUE TITLE
Quill editor is not know element

### ISSUE THREAD

**Issue by ShiruJan** [KillerCodeMonkey/ngx-quill#751]
Hello!
I installed quill-editor for angular 8 following the instructions. When executing the project, it shows this error.  Could you help me with this problem? Thank you.
Annex some details. 

angular cli: 8.3.23
quill: 1.3.6
ngx-quill: 7.3.12 

Tested with chrome.
Message error: **Temp parse errors:'quill-editor' is not a known element**

![Captura de Pantalla 2020-01-31 a la(s) 12 26 07](https://user-images.githubusercontent.com/11635458/73564315-e6358500-4424-11ea-8611-ebaa28b1ace5.png)

![Captura de Pantalla 2020-01-31 a la(s) 12 27 40](https://user-images.githubusercontent.com/11635458/73564439-2b59b700-4425-11ea-8600-4c32f3ab3437.png)

![Captura de Pantalla 2020-01-31 a la(s) 12 29 25](https://user-images.githubusercontent.com/11635458/73564524-60660980-4425-11ea-9e42-4e4e9e7da70a.png)

![Captura de Pantalla 2020-01-31 a la(s) 12 28 41](https://user-images.githubusercontent.com/11635458/73564479-3f9db400-4425-11ea-81cf-55cbb247374c.png)

**Comment by KillerCodeMonkey** [comment]
Please use the QuillModule.forRoot() in your app.module :)

Charly <notifications@github.com> schrieb am Fr., 31. Jan. 2020, 19:31:

**Comment by ShiruJan** [comment]
Thanks, I tried it that way, but I have the same result =(

**Comment by KillerCodeMonkey** [comment]
Check my Demo repo. It is working.


If you have submodules you have to import QuillModule ad Well.
But without "forRoot()"

Charly <notifications@github.com> schrieb am Fr., 31. Jan. 2020, 20:11:

**Comment by KillerCodeMonkey** [comment]
Base (App) Module:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/app.module.ts#L58

ChildModule:
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/child-module/child-module.ts

**Comment by TyrannusRex** [comment]
I tried to  import { MatQuillModule } from './mat-quill/mat-quill-module' but it doesn't exist.
It's the same case when I tried with import { QuillApiEmbedComponent } from './quill-api-embed/quill-api-embed.component'.
 I need to install another library, actually I installed ngx-quill and quill

**Comment by KillerCodeMonkey** [comment]
there is no mat-quill in ngx-quill. if you check my links -  the mat quill implementation only exists in the demo repo.

So grab the code from there and customize it for your needs.

**Comment by soulmate1337** [comment]
@KillerCodeMonkey Nothing of ur comments are helpful man! I have same issue and all what u say is look in my code, its working there. Thats nice but not in our projects!

For me i dont use any child module atm only app.module cuz i dont have many components and other libs in use. 
Im using also Angular 8 and have same problem.

![image](https://user-images.githubusercontent.com/51851209/151454370-ac12318b-7f85-4e18-8bdb-5dd285f80a49.png)

This component is declared in app.module aswell, so why is it not working?

**Comment by soulmate1337** [comment]
@ShiruJan I fixed it now by doing "npm uninstall ngx-quill" and doing "npm install ngx-quill@7.4.0-0" this version works with Angular 8 and u need to have like this in ur angular.json

![image](https://user-images.githubusercontent.com/51851209/151455929-8b325a2d-e3de-46cc-bde8-1bb3a832057e.png)

Have fun!

**Comment by KillerCodeMonkey** [comment]
Hey there. My comments are helpful, because there is a readme with Installation hints and a full working demo repo where everything is setup and running.


But if you are using an outdated angular Version that is not maintained by the angular team neither by me for years... 

Sure things have changed and may not work as you expected.
