### ISSUE TITLE
Can't bind to 'content' since it isn't a known property of 'quill-editor'.

### ISSUE THREAD

**Issue by sukheja-varun** [KillerCodeMonkey/ngx-quill#757]
I am using the content property to pass  content to quill editor as shown below
```
<quill-editor
    [styles]="{ height: '200px' }"
    [content]="content"            
></quill-editor>
```

But I get below shown error
```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'content' since it isn't a known property of 'quill-editor'.
1. If 'quill-editor' is an Angular component and it has 'content' input, then verify that it is part of this module.
2. If 'quill-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          <quill-editor
            [styles]="{ height: '200px' }"
            [ERROR ->][content]="content"
            
          ></quill-editor>
"): ng:///PageModule/PageDynamicContentFormComponent.html@53:12
Error: Template parse errors:
Can't bind to 'content' since it isn't a known property of 'quill-editor'.
1. If 'quill-editor' is an Angular component and it has 'content' input, then verify that it is part of this module.
2. If 'quill-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
          <quill-editor
            [styles]="{ height: '200px' }"
            [ERROR ->][content]="content"
```

The same quill editor works with ng-model as
```
<quill-editor
    [styles]="{ height: '200px' }"
    [(ngModel)]="content"
></quill-editor>
```

**Comment by KillerCodeMonkey** [comment]
because there is no "content" input property?

Just use ngModel or fromControl

**Comment by andliang** [comment]
@KillerCodeMonkey  is right. The content property doesn't exist on`<quill-editor>` but it does on  `<quill-view-html>` .

**Comment by MeenalYengul** [comment]
I am trying to write test case. I get same error. 
```
	Error: Template parse errors:
	Can't bind to 'modules' since it isn't a known property of 'quill-editor'.
	1. If 'quill-editor' is an Angular component and it has 'modules' input, then verify that it is part of this module.
	2. If 'quill-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
	3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
	  <div mat-dialog-content>
	    <quill-editor style="height: 300px !important;" [ERROR ->][modules]="config" [(ngModel)]="news"></quill-editor>
	  <div style="margin-top: 10px;">
	    <mat-labe"): ng:///DynamicTestModule/AddNewsComponent.html@5:52
	'quill-editor' is not a known element:
```

`<div>
<div>
  <h2 mat-dialog-title class="title">New Announcement/News</h2>
  <div mat-dialog-content>

    <quill-editor style="height: 300px !important;" [modules]="config" [(ngModel)]="news"></quill-editor>
  <div style="margin-top: 10px;">
    <mat-label>Select Type</mat-label>
    <mat-select [(ngModel)]="newsselected" name="newsselected" placeholder="Select Type" style="width: 140px; margin-left: 90px;">
      <mat-option *ngFor="let t of types" [value]="t.value">
        {{t.viewValue}}
      </mat-option>
    </mat-select>
  </div>

  <div style="margin-top: 10px;">
    <mat-label>News expiry date</mat-label>
    <input matInput [matDatepicker]="myDatePicker" [(ngModel)]="myDatePickers" [min]="minDate" style="margin-left: 47px;">
    <mat-datepicker-toggle [for]="myDatePicker" matSuffix></mat-datepicker-toggle>
    <mat-datepicker #myDatePicker></mat-datepicker>
  </div>
  </div>
  <mat-dialog-actions style="margin-left: 300px; margin-top: 20px;">
    <button mat-raised-button (click)="addNewNews()">Add</button>
    <button mat-raised-button mat-dialog-close mat-dialog-close="false" style="margin-left: 10px;">Cancel</button>
  </mat-dialog-actions>
  
</div>
</div>
`

`fdescribe('AnnouncementComponent', () => {
    let facilityAPIs: FacilityAPIs;
    let component: AddNewsComponent;
    let fixture: ComponentFixture<AddNewsComponent>;

    beforeEach(async(() => {
        TestBed.configureTestingModule({
            imports: [
                HttpClientTestingModule,
                ApiModule,
                TableModule,
                BrowserModule,
                FormsModule,
                FlexLayoutModule,
                NgFacilityModule,
                MatDialogModule
            ],
            declarations: [
                AddNewsComponent
            ],
            providers: [
                {
                    //http call
                    // provide: APP_BASE_HREF,
                    // useValue: '/'
                    provide: FacilityAPIs
                }
            ]
        });
    }));

    beforeEach(() => {
        fixture = TestBed.createComponent(AddNewsComponent);
        component = fixture.componentInstance;
        facilityAPIs = TestBed.get(FacilityAPIs);
    });

    afterEach(inject([HttpTestingController], (httpMock: HttpTestingController) => {
        httpMock.verify();
    }));

    it('should create component', () => {
        expect(component).toBeTruthy();
    });`

can someone please help me?

**Comment by KillerCodeMonkey** [comment]
You do Not import The quill Module in your Testmodule....

Meenal Ganesh Yengul <notifications@github.com> schrieb am Do., 16. Apr.
2020, 01:02:

**Comment by vinoth23john** [comment]
Iam also facing same for quill-view @KillerCodeMonkey can you pls suggest me why this below error is coming
