### ISSUE TITLE
Problem (with context?) when trying to open MatDialog in custom quill handler

### ISSUE THREAD

**Issue by muellerdberlin** [KillerCodeMonkey/ngx-quill#760]
Servus and hey ;)
At first of all: thank you for the great Angular quill repo! Works very good but one little error I couldn't solve so far.

### Description:
I'm using the Bubble Editor to format text as bold, italic and underline. Additionally I'm using a custom format with a custom Blot. Let's call it "M" like "modal". When i click on the M format icon, I want the handler to open a MatDialog modal e.g. to setup some settings for this text part in the Delta.

![image](https://user-images.githubusercontent.com/34556236/73933367-98b19000-48dc-11ea-939a-1e51d3ef5f75.png)

### quill.html:
```html
<!-- Create toolbar container -->
<div id="toolbar">
  <button class="ql-bold"></button>
  <button class="ql-italic"></button>
  <button class="ql-modal" id="custom-button" value="modal">M</button>

</div>
<quill-editor (onContentChanged)="setNewValue($event)"
              theme="bubble"
              placeholder="add text..."
              [sanitize]="true"
              [modules]="modulesToShow"
              format="{{ format }}"
              [(ngModel)]="value"
              (onEditorCreated)="openEditor($event)" >
</quill-editor>
```

### quill.ts:
```javascript
import Quill from 'quill';
declare var Quill: any;

[...]

constructor(private dialog: MatDialog) {}

    modalHandler = value => {
        if (value) {
            // open modal
            this.dialog.open(ModalComponent);
        }
    };

    ngOnInit(): void {
        Quill.register(modalBlot);

        this.toolbarOptions = {
            container: '#toolbar',
            handlers: {
                'modalPlaceholder': this.modalHandler.bind(this)
            }
        };

        this.modulesToShow = {
            toolbar: this.toolbarOptions
        };
    }

    setNewValue(event) {
        this.change.next(event.content.ops);
        this.newValue = event.content.ops;
    }

    openEditor(event) {
        this.openedEditor = event;
    }
```

I also tried:
```typescript
// adding Handler in openEditor()
this.openedEditor.getModule('toolbar').addHandler('modal', this.modalHandler);
```

### Problem:
The MatDialog modal opens, BUT: There is a problem with mouseover events and click events. This is only when I call the dialog through the quill. In any other component there appears no problem.

**Example:** 
```html
<button (click)="test = !test">switch</button>
<span *ngIf="test">Yeah, you can see me!</span>
<span *ngIf="!test">Nope, I'm hidden</span>
```
**Result when opening in main context:**
![Bildschirmvideo-aufnehmen-2020-02-06-um-13 26 52](https://user-images.githubusercontent.com/34556236/73938747-2e9ee800-48e8-11ea-9b92-284fa08803c9.gif)

**Result when opening through quill modalHandler:**
![Bildschirmvideo-aufnehmen-2020-02-06-um-13 27 08](https://user-images.githubusercontent.com/34556236/73938758-32cb0580-48e8-11ea-9205-0b47be11a67a.gif)

I think this is a context problem but actually I have no idea how to solve this issue at the moment. Do you have any idea?
Thank you!

**Comment by muellerdberlin** [comment]
I found some solution for that. The problem was that I'm using lazy loading modules. If you try to use MatDialog in a lazy loaded Module you have to follow these instructions:

### LazyLoadedModule.ts
```typescript
@NgModule({
    declarations: [
        ...
        ModalComponent
    ],
    imports: [
        ...
    ],
    exports: [
       ...
    ],
    entryComponents: [ModalComponent],
    providers: [ModalService]
})

export class LazyLoadedModule{}
```

### ModalService.ts
```typescript
@Injectable({
    providedIn: 'root'
})
export class ModalService {

    constructor(private dialog: MatDialog) {}

    openModal(callback?) {

        const dialogConfig = new MatDialogConfig();
        dialogConfig.disableClose = false;
        dialogConfig.autoFocus = true;

        dialogConfig.data = {
         [...]
        };

        const dialogRef = this.dialog.open(ChooseOrCreateInputFieldComponent, dialogConfig);

        dialogRef.afterClosed().subscribe(
            data => console.log('Dialog output:', data)
        );
    }
}
```
see [angular-material-dialog-in-lazy-loaded-module](https://stackoverflow.com/questions/57831809/angular-material-dialog-in-lazy-loaded-module)

Nevertheless, elements like a selection input so lack a bit. I'll try to find a solution for that.

**Comment by KillerCodeMonkey** [comment]
i think everthing that comes out of native quilljs is running outside the angular zone (because it is native javascript).

so try to wrap your logic which opens the module in ngZone.run :)

**Comment by KillerCodeMonkey** [comment]
@muellerdberlin any updates 🙃

**Comment by muellerdberlin** [comment]
Thank you, @KillerCodeMonkey for your quick reply. Seems to work with the solution of my last answer. ngZone.run was not necessary. One more problem was the z-index of the selection menu.

**Comment by Empty-handedangularjs-fi** [comment]
> [@muellerdberlin](https://github.com/muellerdberlin) any updates 🙃





https://angulars.space/questions/personalization-of-settings-in-material-dialog
