### ISSUE TITLE
Don't work on safari with matTooltip 

### ISSUE THREAD

**Issue by sambaptista** [KillerCodeMonkey/ngx-quill#764]
Hi,

Although it works fine with chrome and firefox, when using matTooltip on quill-editor, I'm unable to move focus on component on safari (13.0.5 at least). 

~~~html
<quill-editor [(ngModel)]="data" matTooltip="comment"></quill-editor>
~~~

There are no errors in console.

**Comment by KillerCodeMonkey** [comment]
would be nice to have a stackblitz to check and reproduce this.
But in general i do not know what material components do.

I only implement a valid angular control value accessor with my component. So maybe tooltip are not compatible with those elements.
Even i scrolled through the source code and they do many things like adding additional event listeners, so maybe they collide with quilljs.
https://github.com/angular/components/blob/master/src/material/tooltip/tooltip.ts

I would ask at the material ui repo for help

**Comment by sambaptista** [comment]
Created a stackblitz that was working. I close until further investigation.

**Comment by KillerCodeMonkey** [comment]
wow, okay. Let me know when you found the problem :) Good Luck!
