### ISSUE TITLE
Restrict text to only lists

### ISSUE THREAD

**Issue by rohitmsaxena** [KillerCodeMonkey/ngx-quill#765]
What is the ngx-quill suggested way to restrict text so that it is only in lists? If you try to give it text that isn't a list, it automatically turns it into a list (or restricts you to do that action).

**Comment by KillerCodeMonkey** [comment]
Just ask this at the quilljs repo. Ngx-quill is Just an angular wrapper of
quilljs. If you find IT Out how to achieve this with quilljs you know how
to do it with ngx-quill.

In general you can restrict the usage to specific Formats, but i do Not
know If you can disable plain Text.

Just ask at quilljs repo.

Thanks

rohitmsaxena <notifications@github.com> schrieb am Di., 11. Feb. 2020,
22:27:

**Comment by KillerCodeMonkey** [comment]
@rohitmsaxena another idea:

1. use object/json model value format
1. only allow lists as format
2. listen onContentChanged output and add list format attribute when its plain text.

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
@rohitmsaxena did you solved it?
