### ISSUE TITLE
Pagination of modules within Bubble Theme

### ISSUE THREAD

**Issue by JamieBohannaWebDev** [KillerCodeMonkey/ngx-quill#770]
Is there any way that whilst using the Bubble theme, that it paginates into a 2nd page of the bubble theme to show additional formatting options (modules)?

I'm just looking at quite a lot of options on what's meant to be such a small bubble:

![paginate](https://user-images.githubusercontent.com/16854819/74332966-dc017800-4d8e-11ea-9def-0ee44ed6af2c.png)

**Comment by KillerCodeMonkey** [comment]
please ask this at the quilljs repository. i only provide the angular wrapper for it. The toolbar theme is part of quilljs.

But in general you can just override or extend the theme css in your project.

like giving the toolbar container a max-width or something like that :).

Thanks
