### ISSUE TITLE
How can I use content with blots? I passed the delta but it wouldn't render

### ISSUE THREAD

**Issue by dmlsthe1** [KillerCodeMonkey/ngx-quill#771]
How do I get the recommended method of using blots to work with ngx-quill? I have to pass html because content wouldn't work.
content equals the delta from quill
```<quill-view [content]="content" format="object" theme="snow"></quill-view>```

**Comment by KillerCodeMonkey** [comment]
There is no content property.. Check the readme use ngModel or formControl.

Devin Ledesma <notifications@github.com> schrieb am Fr., 14. Feb. 2020,
20:21:

**Comment by dmlsthe1** [comment]
Thank you for your quick response! I'll try passing the delta into ngModel.
p.s. Unless I'm looking at the wrong page, that is from the [https://github.com/KillerCodeMonkey/ngx-quill#quillviewcomponent-quillviewhtmlcomponent--how-to-present-the-editor-content](readme)

**Comment by KillerCodeMonkey** [comment]
Ah sorry. I thought you are using quill-editor component.

Devin Ledesma <notifications@github.com> schrieb am Fr., 14. Feb. 2020,
20:48:

**Comment by KillerCodeMonkey** [comment]
Check my Demo repo

https://github.com/KillerCodeMonkey/ngx-quill-example/tree/master/src/app/view

I use object and pass an quill content / Delta object. And it is working.


Bengt Weiße <bengtler@googlemail.com> schrieb am Fr., 14. Feb. 2020, 20:49:

**Comment by dmlsthe1** [comment]
I see where I went wrong now. Thank you so much!!
I was passing the delta as an object with property 'ops' (content was `{ops: [{insert: '...'}]}`). I should have been passing the array from 'ops'
