### ISSUE TITLE
Editing content Ctrl + Z deletes everything in IE 11 / Firefox 50.0.2

### ISSUE THREAD

**Issue by luisbirchenz** [KillerCodeMonkey/ngx-quill#78]
After implementing this component in my app I realized that when the user edits content, and the content is loaded into the component successfully, if the user presses crtl + z everything is deleted (the content loaded previously). Why this happens? Is there a workaround or setting to fix it?

Regards,
Luis.

**Comment by KillerCodeMonkey** [comment]
Strange i clear history in initial load to avoid this issue. Will check that

Am 13.11.2017 4:28 nachm. schrieb "luisbirchenz" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
This happens only if you use the ngModel approach and not reactive forms.
Checkout my example repo -->  if you are using reactive form everything works.

If you want to handle this with ngModel checkout this:

https://quilljs.com/docs/modules/history/#example

You can try to get there a workaround with configuring the history model. Or listen to the (onContentChanged) output of ngx-quill --> check if this is the first time called and you passed a init value --> clear history.
