### ISSUE TITLE
changing the existing text color random failed

### ISSUE THREAD

**Issue by zuo305** [KillerCodeMonkey/ngx-quill#780]
Steps to replicate:
1. open the example page:  https://killercodemonkey.github.io/ngx-quill-example/
2. type some text
3. select the existing text
4. click the text colour button in the toolbar
5. select any different colour 
6. the text colour sometimes not change

I already tried Chrome and Opera is issued. 
Firefox and Edge are fine. 

https://www.youtube.com/watch?v=LfHg1dVEz7E&feature=youtu.be

**Comment by KillerCodeMonkey** [comment]
but then i think this is a native quilljs issue, because toolbar and anything going on there is native quilljs.

Check this issue:
https://github.com/quilljs/quill/issues/2637
