### ISSUE TITLE
IE 11 click in heading 1 break the line

### ISSUE THREAD

**Issue by luisbirchenz** [KillerCodeMonkey/ngx-quill#79]
If I have this title setting as Heading 2:

My Title

When I enter to edit this content and I click in the "l" the final "e" moves to the next line.

This only happens in IE 11.

I hope you have a workaround for this.

Regards,

Luis.

**Comment by KillerCodeMonkey** [comment]
I think this is an issue with quilljs not my angular wrapper. Can you test
this issue kN quilljs.com ?

Am 13.11.2017 4:35 nachm. schrieb "luisbirchenz" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
could not reproduce this behavior. Maybe you can build a demo repo with demo data.
Check native quill and ngx-quill.

Does not happen to me.
