### ISSUE TITLE
big icons

### ISSUE THREAD

**Issue by chan18** [KillerCodeMonkey/ngx-quill#792]
I just installed a new angular app with ngx-quill editor on it.

the icons/svg are the way too big it covers all the screen.

[stackblitz ](https://stackblitz.com/edit/angular-naurqp)

**Comment by KillerCodeMonkey** [comment]
Please search The issued Here. This occurs when quill css and theme CSS is
missing

chan18 <notifications@github.com> schrieb am Mo., 2. März 2020, 21:42:

**Comment by chan18** [comment]
yes, I noticed that but. it doesn't have CSS related to quill editor.
i just installed with npm install ngx-quill, I think it also has to ship with CSS right?
or do I need to install CSS another way?

**Comment by chan18** [comment]
https://github.com/KillerCodeMonkey/ngx-quill/issues/331

**Comment by KillerCodeMonkey** [comment]
No but you have to include The CSS Front the quilljs node_module to your
global stylings or add them as Styles to your angular.json.

Just read The documentation and Check The Demo repo

chan18 <notifications@github.com> schrieb am Mo., 2. März 2020, 21:50:

**Comment by chan18** [comment]
after adding below .css and .js files to angular.json, everything worked.
             ""styles": [
              "./node_modules/quill/dist/quill.bubble.css",
              "./node_modules/quill/dist/quill.core.css",
              "./node_modules/quill/dist/quill.snow.css"
            ],
            "scripts": [
              "./node_modules/quill/dist/quill.min.js"
            ]

**Comment by KillerCodeMonkey** [comment]
Nice :)

chan18 <notifications@github.com> schrieb am Mo., 2. März 2020, 22:01:
