### ISSUE TITLE
Creating a custom blot from an angular component.

### ISSUE THREAD

**Issue by DoctorsInTech** [KillerCodeMonkey/ngx-quill#797]
I have spent the last 2 days attempting to create a blot that is a custom angular component. I have tried a number of method's including renderer to add the component directory in conjunction with ComponentFactoryResolver.

However, none of these has proven successful. Which leads me to believe that this may not in fact be possible.

Has anybody ever managed to inject a component into a custom blot in quill in either angular or react (preferably angular example). And if not, is this evening possible with quill's parchment and blot system.

**Comment by KillerCodeMonkey** [comment]
what is your use case?

**Comment by DoctorsInTech** [comment]
So my use case is I am creating a complex component that is able to view DICOM images (medical images). This component allows you to scroll through images, change exposure, and other medical-related things. To create this component in parchment would be almost impossible due to complexity. Therefore, I would like to build this as an angular component and then use this as a blot directly with the editor.

**Comment by KillerCodeMonkey** [comment]
okay i think that is not possible. All the quill stuff depends on plain html and native javascript. It will not work to but framework dependent stuff in there.

For example angular/react change detection will not work, because quilljs relays on native js events and api. 

but you could try to build a native webcomponent e.g. stencil and use it, because there is no additional magic happen (more or less).

**Comment by KillerCodeMonkey** [comment]
BTW: what are you using to view a dicom image?

**Comment by DoctorsInTech** [comment]
I am using this, haven't fully integrated it yet as I wanted to know if it was possible to integrate it into a blot in quill.

https://github.com/ivmartel/dwv

**Comment by KillerCodeMonkey** [comment]
that should be possible, because it is just plain JS, but not as an angular/react (framework specific) component.

i am using this one, too :D and keep this bug in mind: 
https://github.com/ivmartel/dwv/issues/705

**Comment by KillerCodeMonkey** [comment]
if you want a custom tag-name just check https://developer.mozilla.org/en-US/docs/Web/Web_Components

**Comment by KillerCodeMonkey** [comment]
any updates on this?

**Comment by Eraldo** [comment]
I am also interested in how best to create a custom blot from an angular component.

**Comment by falk-stefan** [comment]
I'm scratching my head over this. Everything I try fails with all kinds of errors. 

All I want to do is basically highlight text in a read-only quill editor. Is there a way to do this?

**Comment by KillerCodeMonkey** [comment]
i would just check some quill modules like quill-mention where some text is special highlighted and adapt it for your needs.

**Comment by kalluu-ck** [comment]
You can check this article for implementing custom blot
https://kalcancode.wordpress.com/2025/03/31/how-to-implement-custom-embed-blot-in-ngx-quill/
