### ISSUE TITLE
Where do I get quill.snow.css from?

### ISSUE THREAD

**Issue by rodneyjoyce** [KillerCodeMonkey/ngx-quill#8]
Hi again,

I don't want to use the Quill CDN for quill.snow.css and would like to reference it from the Node modules in my angualar-cli json file so it is packaged in WebPack. However, I can't seem to find it in ngx-quill or quill - where can I find it?

**Comment by KillerCodeMonkey** [comment]
You can find the minified css and js in `node_modules/quill/dist/`.

**Comment by rodneyjoyce** [comment]
Ah yes, sorry, my search didn't pick that up.

**Comment by anisabboud** [comment]
`quill.snow.css` can be added to `.angular-cli.json` like this:

          "styles": [
            "../node_modules/quill/dist/quill.snow.css",
            "styles.scss"
          ],

**Comment by hajderr** [comment]
Great should be added to README

**Comment by KillerCodeMonkey** [comment]
Feel free to send a PR. Because i will Not add this ;). Because i am Not
responsible to Guide You, how to Use Your Tools ;).

hajder <notifications@github.com> schrieb am Mi., 9. Mai 2018, 12:38:

**Comment by hajderr** [comment]
Isn't the CSS required for the editor to render correctly? Without it I couldn't get decent output in the browser.

**Comment by KillerCodeMonkey** [comment]
sure but adding it to the angular-cli.json is angular-cli specific.. if you have a simply webpack project, you could add it in the webpack.config or import it in your ts file. or import it in one of your stylesheets...

so many ways and i am not a babysitter to guide everyone, how to add 3rd party stylesheets to a project...

There are other buildtools like rollup, pascal.js... so it is not my business ;)

**Comment by KillerCodeMonkey** [comment]
read the readme carfully:
`do not forget to include quill + theme css in your buildprocess, module or index.html!`

**Comment by hajderr** [comment]
It's up to you if you'd like to include more guides in order to enhance the user experience for your lib :)

**Comment by KillerCodeMonkey** [comment]
And it is up to You to participate on an open Source project ;)

hajder <notifications@github.com> schrieb am Mi., 9. Mai 2018, 17:29:

**Comment by iamsagarsingh** [comment]
Update, If you are using vite, don't use ~ sign in styles.css.
