### ISSUE TITLE
Best practice how to import quill in lazy loaded modules

### ISSUE THREAD

**Issue by Benny739** [KillerCodeMonkey/ngx-quill#807]
In the readme I saw the following:
> for builds with angular-cli >=6 only add quilljs to your scripts or scripts section of angular.json, if you need it as a global :)!

What is the best practice importing quill in lazy loaded modules with angular v9?

**Comment by KillerCodeMonkey** [comment]
just import everything in the component/module you are using ngx-quill. keep in mind that the components that are using ngx-quill and import the quill css in its css files should not enable view encapsulation. ;-)

**Comment by KillerCodeMonkey** [comment]
any updates? did you solved it?

**Comment by Benny739** [comment]
Sorry for my late reply, everything works perfectly. Thanks :)
