### ISSUE TITLE
Font selection doesn't work even in the online example

### ISSUE THREAD

**Issue by wyshmily** [KillerCodeMonkey/ngx-quill#82]
Is this problem of quill or this repository?

**Comment by KillerCodeMonkey** [comment]
ah thanks. this is only an issue in the demo repo. i added an example of custom fonts (the last editor in the example page). So only this fonts are whitelisted.

Please check the last editor instance on https://killercodemonkey.github.io/ngx-quill-example/

**Comment by KillerCodeMonkey** [comment]
should be fixed
