### ISSUE TITLE
Angular 9 Compatibility issue

### ISSUE THREAD

**Issue by designersingh** [KillerCodeMonkey/ngx-quill#822]
Can't use it with Angular 9 project because of the ngcc I guess. 

ERROR in ./node_modules/ngx-quill/__ivy_ngcc__/fesm2015/ngx-quill.js
Module not found: Error: Can't resolve 'quill' in '/node_modules/ngx-quill/__ivy_ngcc__/fesm2015'
    
    ERROR in node_modules/ngx-quill/src/quill.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of ProductModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ngx-quill) which declares QuillModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    3 export declare class QuillModule {
                           ~~~~~~~~~~~
    src/app/pages/admin/product/product.module.ts:28:14 - error NG6002: Appears in the NgModule.imports of AdminModule, but itself has errors

**Comment by KillerCodeMonkey** [comment]
how do you import the quill module there?

my demo repo is using production build with ivy :)

https://killercodemonkey.github.io/ngx-quill-example/

**Comment by designersingh** [comment]
Oops. I should have read the docs fully. I was lazy loading the module and didn't add it in the root module. It's fixed now. Thank you for the prompt response! <3

**Comment by KillerCodeMonkey** [comment]
no probs. glad you got it working for you
