### ISSUE TITLE
any support for URL link preview into text editor 

### ISSUE THREAD

**Issue by santoshprakash** [KillerCodeMonkey/ngx-quill#835]
Can someone help me to use this to show  URL link preview into the text editor. "og tags"

**Comment by KillerCodeMonkey** [comment]
you should ask this at the quilljs repository. This is only the angular wrapper for the quilljs editor.

In general you need to create a new blot i think for link preview.
And add a custom handler when a link is added. After that you need something like a page "crawler" to get the html of the link and parse it for og-tags.

If you find any you have to add your custom blot with the "preview" to the editor.
