### ISSUE TITLE
Delta Json format secure?

### ISSUE THREAD

**Issue by andliang** [KillerCodeMonkey/ngx-quill#836]
> sanitize - uses angulars DomSanitizer to santize html values - default: false, boolean (only for format="html")

What if json (ie: delta) format is used? Will it be sanitized by default? Is it secure from XSS attacks? Thanks

**Comment by KillerCodeMonkey** [comment]
Good question never tried it. I thought when json or object is used, quill
strips all unknown Attributes, Formats and blots

andliang <notifications@github.com> schrieb am Di., 7. Apr. 2020, 04:04:

**Comment by KillerCodeMonkey** [comment]
you can check that on your own. i added an html sanitize example to the demo repo, just try to inject javascript to the json format :)

**Comment by andliang** [comment]
Sorry for the late reply. I haven't been able to try it myself yet because I'm experiencing other issues at the moment. I'll give it a shot when I get the chance. Thanks!
