### ISSUE TITLE
Can not copy and paste on ios.

### ISSUE THREAD

**Issue by asd969704376** [KillerCodeMonkey/ngx-quill#839]
I use it on angular/ionic.After package on android is ok but on ios i can not copy and paste.I do not know how it caused.

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill-ionic/issues/1

But in general it is not an ngx-quill issue. more quilljs thing.
https://github.com/quilljs/quill/issues/2778
https://github.com/quilljs/quill/issues/2787
