### ISSUE TITLE
Pre assign value in Quill js editor

### ISSUE THREAD

**Issue by ersaurabh101** [KillerCodeMonkey/ngx-quill#846]
I have added **Quill JS** on `home.html`. I am assigning it a value from a variable. It is showing the `pre assigned value`, but it is not showing its html property.

Here is my `home.html` code::

    <ion-content>
      <form [formGroup]="editorForm" (ngSubmit)="OnSubmit()">
        <div class="form-group">
          <label for="editor">
            <h3>Editor</h3>
          </label>
      <quill-editor [(ngModel)]="dhtml" formControlName="editor"></quill-editor>
    </div>
    <ion-button type="submit">Submit</ion-button>
    </form>
    </ion-content>

and `home.ts` code::

    export class DesigntemplatePage implements OnInit {
    
      loggedInusr;
      editorForm: FormGroup;
      dhtml = '<p><font color="red">This is some text!</font></p>';
    
      form: FormGroup = this.fb.group({
        html: new FormControl(null)
      })
      constructor(private fb: FormBuilder,private storage: Storage,private firestore: AngularFirestore) { }
    
      ngOnInit() {
        this.storage.get('loggedInUser').then((val) => {
          console.log('Your user ID is', val);
          this.loggedInusr = val;
        });
        this.editorForm = new FormGroup({
          'editor': new FormControl(null),
        })
      }
    
      OnSubmit(){
        console.log(this.editorForm.get('editor').value);
      }

It is showing text inside the editor, but not in red color, see image below -

[![enter image description here][1]][1]

Please guide.

**After using safe pipe, this is the result**::
I have created a **safepipe**, on adding it, i can see red text using `innerHtml` but this text is not showing inside the  Quill JS editor.

      <quill-editor [innerHtml]="dhtml| safe3: 'html'" formControlName="editor"></quill-editor>

see image below:

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/1uDfl.png
  [2]: https://i.stack.imgur.com/b3XNE.png

**Comment by KillerCodeMonkey** [comment]
1. never is `innerHtml`
2. you only have to use `ngModel` or `formControl`
3. check my answer at you question in another issue: inline vs class based styling - https://quilljs.com/guides/how-to-customize-quill/#class-vs-inline
4. you can not render not every html and css with quilljs. it only allows to use known formats (tags + styling)
