### ISSUE TITLE
Strongly type the Quill editor returned by event emitters

### ISSUE THREAD

**Issue by dsebastien** [KillerCodeMonkey/ngx-quill#849]
Hello.

Would it be possible to type the return value of event emitters that return an instance of the Quill editor?

**Comment by KillerCodeMonkey** [comment]
I had this, but most of the time quill typings where broken or inconsistent
:). So i left it as any

Am Do., 16. Apr. 2020 um 19:52 Uhr schrieb Sebastien Dubois <
notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
but maybe i will provide my own typings and export them. 🤔 I have to think about it.

**Comment by dsebastien** [comment]
Indeed, makes sense.

For now I've created some typings of my own. Not complete at all but at least it's something :)

**Comment by dsebastien** [comment]
The best would probably be for us to contribute improvements to the "official" quill typings in DefinitelyTyped

**Comment by KillerCodeMonkey** [comment]
ah and the problem is, when i import Quill SSR will not work, because when importing Quill something tries to access `document`, which does not exist on server side :(.

So in general custom typings would be the only solution for now, i think

**Comment by KillerCodeMonkey** [comment]
Done in 8.1.5

**Comment by KillerCodeMonkey** [comment]
please use 8.1.7 i fixed and extended some typings.
