### ISSUE TITLE
How can I insert HTML programmatically in an Editor?

### ISSUE THREAD

**Issue by coder-strange** [KillerCodeMonkey/ngx-quill#850]
[Question]: 
I have an Editor in which I can drag and drop some texts, I'm trying to add new node where the drop happened but it's converting it to simple string.

Here are the things I've tried.

1.
  ```
  var span = document.createElement('span');
    span.innerHTML = '<span>{{' + ev.dragData + '}}</span>';
    ev.nativeEvent.toElement.append(span);
```

2.
  ` this.quillInstance.clipboard.dangerouslyPasteHTML('<span>{{' + ev.dragData + '}}</span>');`

**Comment by KillerCodeMonkey** [comment]
Just ask this at the quilljs repo? Do Not use
dangerouslyPasteHTML . It is deprecated.there is a convert method (Check
The source of my quill-editor component) and keep in mind quill only allows
known Tags and Formats and strips everything which is Not allowed.

If you want to add new Tags you should Go for custom blots and modules for
quill.



TheTom <notifications@github.com> schrieb am Fr., 17. Apr. 2020, 16:16:

**Comment by KillerCodeMonkey** [comment]
Here is the line of code: https://github.com/KillerCodeMonkey/ngx-quill/blob/master/src/quill-editor.component.ts#L190

For custom blots and tags you can check this guide: https://quilljs.com/guides/cloning-medium-with-parchment/#adding-quill-core

**Comment by KillerCodeMonkey** [comment]
linked issue: https://github.com/quilljs/quill/issues/3009

**Comment by coder-strange** [comment]
Thanks for you supersonic reply that let me to my answer on the blots guide you suggested, and the reason of my issue was "Quill cannot support arbitrary DOM trees."

Eg. <p><span></span> and <p></p> are the same content. //Quoting Quill
