### ISSUE TITLE
The Editor Can't Get Focus On IOS Platform

### ISSUE THREAD

**Issue by nobage** [KillerCodeMonkey/ngx-quill#86]
Hello, I have integrated this plugin in Ionic3 project. It worked on Android platform, but the editor can't get focus on ios platform. Could you give some sugesstionto fix this problem? THX.

**Comment by KillerCodeMonkey** [comment]
Did you use your ionic project AS webapp or native APP. Please check if it
is working on IOS and Safari mobile with and without ionic.

If it is a native APP Problem try it without keyboard Plugin.

Am 21.12.2017 9:46 vorm. schrieb "nobage" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
any updates? Would be interesting if you get a solution.

**Comment by nobage** [comment]
KillerCodeMonkey, so sorry for my late reply. I got a solution of this question. 
Because of the input widget of quill editor is a 'div' with 'contenteditable=true', It can't work on IOS platform. I just add one css property on this 'div' like '-webkit-user-select:text'.

`<div class="ql-editor ql-blank" data-gramm="false" contenteditable="true" data-placeholder="placeholder text"></div>`

**Comment by KillerCodeMonkey** [comment]
Nice thanks for sharing the solution!

Am 03.01.2018 5:30 vorm. schrieb "nobage" <notifications@github.com>:

**Comment by robpaveza** [comment]
@KillerCodeMonkey Did you merge this fix into your project? I am having the same issue.

**Comment by KillerCodeMonkey** [comment]
Nope, because I am using quilljs and quilljs adds content editable to the div.

Please check the quilljs repository if there are any issues related to that.

I will not fix or workaround issues that are QuillJS issues ;)

**Comment by robpaveza** [comment]
Fair enough, but it's not clear to me that this is specific to QuillJS.  I can use the QuillJS playground on my iPhone just fine.

But yeah, I get it.  For anyone who runs into it: I fixed by just adding this:

```
.ql-editor {
    -webkit-user-select: text;
}
```

**Comment by KillerCodeMonkey** [comment]
Strange.. I only add a wrapper html-tag an no styling and nothing.
If you are using this with something like an ionic-app it is another case. Ionic disables user-select per default.

**Comment by bkarv** [comment]
@nobage @robpaveza  thanks for the solution had same issue testing on iOS (within ionic 4) this resolved the situation. However if I am writing text within the container, I am unable to select whole words within IOS, do you have the same issue?

**Comment by KillerCodeMonkey** [comment]
Die you checked Out the Ionic v3 example and the readme section with CSS
and user-select?

But keep in mind this is a wysiwyg Editor and The the usability is Always
Not the best on mobile because of selecting Things. It is very hard and
frustrating on mobile devices.




Am So., 27. Jan. 2019, 00:10 hat bkarv <notifications@github.com>
geschrieben:

**Comment by momja** [comment]
@robpaveza what did your html file look?

**Comment by BakshinderSingh** [comment]
> KillerCodeMonkey, so sorry for my late reply. I got a solution of this question.
> Because of the input widget of quill editor is a 'div' with 'contenteditable=true', It can't work on IOS platform. I just add one css property on this 'div' like '-webkit-user-select:text'.
> 
> `<div class="ql-editor ql-blank" data-gramm="false" contenteditable="true" data-placeholder="placeholder text"></div>`

This solution worked for my project also

**Comment by bvergara87** [comment]
I just tried this today in my code using the following in CSS

.ql-container,.ql-editor, .ql-editor.ql-blank, .ql-editor.ql-blank::before, .ql-editor.ql-blank::after {
  -khtml-user-select: text !important;
  -moz-user-select: text !important;
  -ms-user-select: text !important;
  user-select: text !important;
 -webkit-user-select: text !important;
}

no luck selecting on iOS 13 Chrome

**Comment by deepaklaller1988** [comment]
You can add class on click the quill-editor 
like:-
IN HTML
<quill-editor id="quilleditor" quill-editor-toolbar  (click)="quillclick()">
                        <div quill-editor-toolbar>
                            <button class="ql-bold" [title]="'Bold'"></button>
                            <button class="ql-italic" [title]="'italic'"></button>
                          </div>
                    </quill-editor>
In Ts:
 quillclick(){
     var quilleditor = document.getElementById('quilleditor')
     quilleditor.classList.add('newclass')
   }
In CSS
.newclass{
    -webkit-user-select: text;
}
