### ISSUE TITLE
Set the maximum length of the content.

### ISSUE THREAD

**Issue by ramprakashram** [KillerCodeMonkey/ngx-quill#861]
Is it possible to restrict user input by adding maxlength property or any other way ???

**Comment by KillerCodeMonkey** [comment]
just read the https://github.com/KillerCodeMonkey/ngx-quill#config or check the demo repo.

there are: maxLength minLength and required Inputs for validation

**Comment by WaldiirNeto** [comment]
Currently, maxLength doesn't even work in the demo itself, any tips on how we can make it work?

**Comment by KillerCodeMonkey** [comment]
why should it not work?

check the demo... there the formcontrols are required and max length is set.
if you not enter anything or >maxlength it is invalid. in other cases it is valid. so i guess it is working.

But it does not prevent users to enter more chars.

**Comment by WaldiirNeto** [comment]
> Por que não deveria funcionar?
> 
> verifique a demonstração... lá os controladores de formulário são necessários e o comprimento máximo é definido. se você não inserir nada ou >maxlength é inválido. em outros casos é válido. Então eu acho que está funcionando. pesquisar por "MaxLength + necessário" na página de demonstração ao vivo.
> 
> Mas isso não impede que os usuários insiem mais chars.

This is the point, how to stop the user from not typing if they hit the limit?

**Comment by KillerCodeMonkey** [comment]
use the onContentChanged output. or directly the quill api.
or just listen on NgModelChange or changes to your form control. So many possible ways.

and if the length of the model/content exceeds your limit just remove the last change.

**Comment by WaldiirNeto** [comment]
> use a saída onContentChanged. ou diretamente a api pena. ou apenas ouvir em NgModelChange ou alterações no seu controle de formulário. Tantas maneiras possíveis.
> 
> e se o comprimento do modelo/conteúdo exceder seu limite basta remover a última alteração.
> 
> é difícil bloquear a entrada do usuário em geral, uma vez que o editor de penas é apenas um div com conteúdoeditável e o conteúdo é html. então não há uma maneira fácil de fazer isso.
> 
> eu simplesmente não bloquearia para adicionar conteúdo mais longo, já que você pode bloquear salvar as alterações inválidas, já que o modelo/controle fica marcado como inválido.

I hadn't thought of that and it worked great! 
![image](https://user-images.githubusercontent.com/14873323/180835527-9ab4a7ed-565a-4a70-979c-07dbedf06bd1.png)

**Comment by WaldiirNeto** [comment]
for those who have any doubts just use it with onContentChanged
