### ISSUE TITLE
Editor not binding in Quill 2.0.0-dev.*

### ISSUE THREAD

**Issue by allahyar** [KillerCodeMonkey/ngx-quill#865]
Hi, 
I succeeded to add the following two modules, But then I found data is not binding to model.
It doesn't show at all.

"ngx-quill": "^8.0.0" and "^8.1.7" 
"quill": "^2.0.0-dev.*"
_"quill-better-table": "^1.2.8",
"quill-blot-formatter": "^1.0.5"_

**Comment by KillerCodeMonkey** [comment]
1. i am not supporting quill 2.0.0-dev
2. please provide a demo repo.

And this is because those modules are setting the content as 'api'  and it should be 'user' .. because the user triggers the changes. In general angular formscontrols should only update on real user changes.

You can bypass that:
there is the input `trackChanges` and set it to `'all'`

**Comment by allahyar** [comment]
If possible, apply a bypass method :
https://stackblitz.com/edit/angular-kgxl3d

thanks

**Comment by KillerCodeMonkey** [comment]
@allahyar the problem, that the initial value is not set is caused by quill 2.0. 

you can use everything without the "trackChanges" all stuff.

Just work around how you set the initial value:

1. wait for editor creation
2. use quilljs api to setContents/text/html and pass 'user' as source

**Comment by allahyar** [comment]
> @allahyar the problem, that the initial value is not set is caused by quill 2.0.
> 
> you can use everything without the "trackChanges" all stuff.
> 
> Just work around how you set the initial value:
> 
> 1. wait for editor creation
> 2. use quilljs api to setContents/text/html and pass 'user' as source

@KillerCodeMonkey It was a good tip, thank you.
Changes were made to the [example](https://stackblitz.com/edit/angular-kgxl3d).

**Comment by Vbboi24** [comment]
@allahyar , Hey how did you get the table inside the editor. I tried the example code shared. I am quite stuck here :
`Class constructor Container cannot be invoked without 'new'`
Would you mind sharing a stackblitz if possible ?
