### ISSUE TITLE
Metadata version mismatch for module d.ts, found version 4, expected 3, 

### ISSUE THREAD

**Issue by lmx-gowthamb** [KillerCodeMonkey/ngx-quill#867]
Metadata version mismatch for module E:/my-app/node_modules/ng2-file-upload/ng2-file-upload.d.ts, found version 4, expected 3, resolving symbol AppModule in E:/my-app/src/app/app.module.ts, resolving symbol AppModule in E:/my-app/src/app/app.module.ts
 
and

 Metadata version mismatch for module E:/my-app/node_modules/@ng-select/ng-select/ng-select.d.ts, found version 4, expected 3, resolving symbol AppModule in E:/my-app/src/app/app.module.ts, resolving symbol AppModule in E:/my-app/src/app/app.module.ts

 "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.4.3",
    "@angular/compiler": "^4.1.3",
    "@angular/compiler-cli": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.4.7",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/platform-server": "^4.1.3",
    "@angular/router": "^4.1.3",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.25",
    "@ng-select/ng-select": "^1.6.3",
    "@ngx-translate/core": "6.0.1",
    "@ngx-translate/http-loader": "^0.1.0",
    "amcharts3": "github:amcharts/amcharts3",
    "ammap3": "github:amcharts/ammap3",
    "angular-material": "^1.1.20",
    "angular2-datatable": "0.6.0",
    "angular2-datetimepicker": "^1.1.1",
    "angular2-image-zoom": "^1.2.1",
    "animate.css": "3.5.2",
    "bootstrap": "^4.0.0-alpha.6",
    "chart.js": "1.1.1",
    "chartist": "0.10.1",
    "chroma-js": "1.3.3",
    "ckeditor": "4.6.2",
    "core-js": "2.4.1",
    "easy-pie-chart": "2.1.7",
    "file-saver": "^1.3.3",
    "font-awesome": "4.7.0",
    "fullcalendar": "3.3.1",
    "google-maps": "3.2.1",
    "ionicons": "2.0.1",
    "jquery": "^3.2.1",
    "jquery-slimscroll": "1.3.8",
    "leaflet": "0.7.7",
    "leaflet-map": "0.2.1",
    "lodash": "4.17.4",
    "mydatepicker": "^2.0.14",
    "ng-pdf-make": "0.0.2",
    "ng-pick-datetime": "^5.1.3",
    "ng2-ckeditor": "1.1.6",
    "ng2-completer": "^1.3.1",
    "ng2-file-upload": "^1.4.0",
    "ng2-handsontable": "0.48.0",
    "ng2-select": "^2.0.0",
    "ng2-select-compat": "^1.3.1",
    "ng2-select2": "^1.0.0-beta.16",
    "ng2-slim-loading-bar": "4.0.0",
    "ng2-smart-table": "1.0.3",
    "ng2-toastr": "^4.0.1",
    "ng2-tree": "^2.0.0-rc.11",
    "ng2-zoomable": "^0.1.1",
    "ngx-toastr": "^11.3.3",
    "ngx-uploader": "2.2.5",
    "normalize.css": "6.0.0",
    "roboto-fontface": "0.7.0",
    "rxjs": "^5.5.7",
    "web-audio-player": "^1.3.3",
    "xlsx": "^0.11.3",
    "zone.js": "0.8.5"
  },
  "devDependencies": {
    "@angular/cli": "1.0.2",
    "@angular/compiler-cli": "4.1.0",
    "@types/fullcalendar": "2.7.40",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "2.0.41",
    "@types/jquery.slimscroll": "1.3.30",
    "@types/lodash": "4.14.61",
    "@types/node": "6.0.69",
    "angular-ide": "^0.9.31",
    "babel-core": "^6.10.4",
    "codelyzer": "2.0.0",
    "gh-pages": "0.12.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "npm-run-all": "4.0.2",
    "protractor": "5.1.0",
    "rimraf": "2.6.1",
    "standard-changelog": "1.0.1",
    "stylelint": "7.10.1",
    "ts-node": "2.0.0",
    "tslint": "4.5.0",
    "tslint-eslint-rules": "3.5.1",
    "tslint-language-service": "0.9.2",
    "typescript": "^2.3.2",
    "typogr": "0.6.6",
    "underscore": "1.8.3",
    "wintersmith": "2.2.5",
    "wintersmith-sassy": "1.1.0"
  }

**Comment by KillerCodeMonkey** [comment]
dude you are not even using ngx-quill.... 

Please, learn how to read error message and how to use google, stackoverflow and github...

**E:/my-app/node_modules/@ng-select/ng-select/ng-select.d.ts** 

the error occurs in ng-select.

And a little hint... angular 4 is years old and outdated... even angular 7 reached lts support end in april.
