### ISSUE TITLE
What I see in quill editor window is not export to other component

### ISSUE THREAD

**Issue by sankarumai** [KillerCodeMonkey/ngx-quill#868]
In quill editor, each line shown as paragraph tag(`<p>`) and it's margin set to 0px whereas converting quill editor content into html file sets its default margin value as 16px.  This results in different UX to quill editor vs other component. For example quill editor vs html.

To be noted, I loaded HTML content to quill editor but converts all the tag to `<p>`. How to retain same HTML content in quill editor and this will help me in converting to other format.

**Sample quill editor content**

![image](https://user-images.githubusercontent.com/37729024/80119533-74925080-85a7-11ea-9e0a-e2fc31c5898f.png)

**Sample HTML Page output generated from quill editor**

![image](https://user-images.githubusercontent.com/37729024/80119005-c5ee1000-85a6-11ea-8a6f-bf39268a0e4a.png)

**Comment by KillerCodeMonkey** [comment]
You should use the quill-view or quill-view-html compontent to view the result of the editor.

quilljs transforms html to only formats/blots it knows.

If you do not want to use p-tags you can switch to 'div'-tags like in my demo repo or described in the quilljs documentation:

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/app.component.ts#L5
