### ISSUE TITLE
Can we have any configuration to skip particular tag not to be enclosed with <p> tag.

### ISSUE THREAD

**Issue by sankarumai** [KillerCodeMonkey/ngx-quill#869]
As a example currently I have `<br>` tag even for this it is enclosed with `<p>` tag. I want to skip `<p>` tag should be excluded for this `<br>`  tag.

**Comment by KillerCodeMonkey** [comment]
you should ask this at the quilljs repo.

in my example you see how to switch from p-tags to brs. But in general ich new line is p-tag + br
An why not. the styling comes from quill.css. So there should be no problem.

**Comment by sankarumai** [comment]
I am not asking for tag replacement :)  . Dynamically it is adding `<p>` tag to `<br>` tag.  So I need to exclude this to avoid unnecessary `<p>` tags.

**Comment by KillerCodeMonkey** [comment]
yep and this you should ask at quilljs repo, because it is the default behavior. i though you have some styling issues when showing the editor content to the enduser somewhere, because you are getting extra space or such things.

But i think it is not that bad to have some extra p-tags
