### ISSUE TITLE
How to add Quill plugins?

### ISSUE THREAD

**Issue by soniar4i** [KillerCodeMonkey/ngx-quill#87]
Hello, 

Thanks for the awesome work you are doing to bring quill for angular. It's really great!

This is more a question than an issue, how do we include Quill plugins such as https://quilljs.com/docs/modules/syntax/ ngx-quill

Thanks! :)

**Comment by KillerCodeMonkey** [comment]
Like it is described there. Check if there are types for Highlight.JS
import quill and Highlight.JS pass the modules configuration to the
ngx-quill modules input.

If Highlight.JS is not already typed, declare it AS a global in your
webpack.conf. after that you can access it through the window-object.

Import the styles of hjs in you .CSS/.scss or add it AS additonal CSS in
you webpack, or add it in your index.HTML (not a good approach).

In the demo-repo is also an example of custom modules like word-count,
changing fonts and so on.

**Comment by soniar4i** [comment]
Thank you so much! What a great work your doing :)
