### ISSUE TITLE
Remove new line at the end

### ISSUE THREAD

**Issue by MickL** [KillerCodeMonkey/ngx-quill#875]
Somehow it always adds a new line to the end. So when I try to count the characters with `change.text.length;` it is always `n+1`:

<img width="239" alt="Bildschirmfoto 2020-04-28 um 13 46 03" src="https://user-images.githubusercontent.com/5103210/80483680-c72c8d80-8956-11ea-8aed-bba6ad687b2f.png">

**Comment by KillerCodeMonkey** [comment]
it is a thing quilljs does and i do not want to change the default behaviour. 

like in html representation you get `<p><br></p>` at the end
And this is the `\n` in the text.

I event need to hack around this for correct min and maxlength calculation
