### ISSUE TITLE
Register imageResize module using anuglar cli 

### ISSUE THREAD

**Issue by faresayyad** [KillerCodeMonkey/ngx-quill#88]
Hello 

I'm using ngx-quill using angular 4 CLI, i'm trying to add image resize module to the editor.

* What i have tried:
1- i tried to register the module in QuillEditorComponent
using this code:

import * as QuillNamespace from "quill";
```
let Quill: any = QuillNamespace;
import ImageResize from 'quill-image-resize-module';
Quill.register('imageResize', ImageResize);
```

Then i configure the defaultmodules to be:
```
defaultModules = {
    toolbar: [
      ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
      ['blockquote', 'code-block'],

      [{ 'header': 1 }, { 'header': 2 }],               // custom button values
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
      [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
      [{ 'direction': 'rtl' }],                         // text direction

      [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
      [{ 'header': [1, 2, 3, 4, 5, 6, false] }],

      [{ 'color': this.emptyArray.slice() }, { 'background': this.emptyArray.slice() }],          // dropdown with defaults from theme
      [{ 'font': this.emptyArray.slice() }],
      [{ 'align': this.emptyArray.slice() }],

      ['clean'],                                         // remove formatting button

      ['link', 'image', 'video']                         // link and image, video
    ],ImageResize
    
  };
```
But i got this error:
Cannot read property 'imports' of undefined.

i follow the instructions in this [issue](https://github.com/KillerCodeMonkey/ngx-quill/issues/23), but the error still appears.

Any one can help with this ?

**Comment by KillerCodeMonkey** [comment]
ImageResize needs Quill AS a global var. This is a known Problem and there
are similar issues about it here and in the resize repo.

So if you are using webpack. Declare quill AS global.

I cannot help you if you are not using webpack. ASK in the quill image
resize repo how to use it with typescript.

Am 29.12.2017 7:26 nachm. schrieb "faresayyad" <notifications@github.com>:

**Comment by faresayyad** [comment]
@KillerCodeMonkey 

So there's no way to configure this if i'm using Anuglar CLI ?

**Comment by KillerCodeMonkey** [comment]
Then you should check, how to add globals in the angular cli.

https://github.com/angular/angular-cli/wiki/stories-global-scripts

Am 31.12.2017 9:11 vorm. schrieb "faresayyad" <notifications@github.com>:

**Comment by faresayyad** [comment]
I don't know how to explain this, but i follow the link to declare Quill as global but every time i tries to 
register image resize using .register i got 
Cannot read property 'imports' of undefined. 

i'm wondering if any one who add the module can help ?

**Comment by faresayyad** [comment]
Hello
I'm trying to use image resize plugin inside angular 4 app.

i noticed that i should use a webpack and configure the webpack .config.js file in order to get rid of

Cannot read property 'imports' of undefined

so, i used the anulgar cli before i eject the webpack.config.js file using the following command:
`ng eject`

this produced the webpack.config.js file, i tried to modify it by inserting the following code "Base on the following issue and comments": #7 (comment)

i successfully added this

```
{
    test: /\.js$/,
    exclude: /node_modules(?!\/quill-image-drop-module|quill-image-resize-module)/,
    loader: 'babel-loader',
    query: {...}
  } 
```
to the modules in webpack.config.js file.

and the i added this to the plugins:

```
 new webpack.ProvidePlugin({
    'window.Quill': 'quill'
  })
```
but whenever i tried to build the app using

`npm run build`

it fails.

do you have any suggestions?

**Comment by KillerCodeMonkey** [comment]
did you checked this:
https://github.com/kensnyder/quill-image-resize-module/issues/7#issuecomment-304463415

i never tried it, but it seems to help others.
you should add the correct path to the quill.js file in your ProvidePlugin.

**Comment by faresayyad** [comment]
i tried it.

i don't know why it's so difficult to use the module >?

**Comment by KillerCodeMonkey** [comment]
maybe it is not well written? But it seems the project is not supported very well.

**Comment by KillerCodeMonkey** [comment]
@faresayyad i added an example to the demo-repo:

https://killercodemonkey.github.io/ngx-quill-example/
checkout the "Formula & image resize editor".

I globally defined window.Quill with ProvidePlugin in the webpack config.
And i have to handle ImageResize as default export of the quill-image-resize-module.

```
import ImageResize from 'quill-image-resize-module';
```

checkout the demo sourcecode :).

Hope that this finally helps

**Comment by lordUhuru** [comment]
Refer to the answer I provided here [Stackoverflow answer](https://stackoverflow.com/questions/46215559/quill-image-resize-for-angular-2-quill-module)

**Comment by allahyar** [comment]
It's okay in the serve mode error occurs after the build !

Angular: 8.2.13


> did you checked this:
> [kensnyder/quill-image-resize-module#7 (comment)](https://github.com/kensnyder/quill-image-resize-module/issues/7#issuecomment-304463415)
> 
> i never tried it, but it seems to help others.
> you should add the correct path to the quill.js file in your ProvidePlugin.
