### ISSUE TITLE
Formula render issue

### ISSUE THREAD

**Issue by ksabariraj** [KillerCodeMonkey/ngx-quill#880]
Good Day,

Getting the below error when trying to render multiple formulas.

HTML Content: 
```HTML
<div>
  <p>
    Consider the point P on the curve y = f (x) whose coordinates are (x, y) and another point Q where coordinates are (x + Δx, y + Δy). The slope of the line joining P and Q is given by:
  </p>
  <p>
    <span class=\"ql-formula\" data-value=\"\\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}\">
      \\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}
    </span>
    -------------------- (2)
  </p>
  <p>
    <br>
  </p>
  <p>
    Suppose now that the point Q moves along the curve towards P. In this process, Δy and Δx  decrease and approach zero; though their ratio
  </p>
  <p>
    <span class=\"ql-formula\" data-value=\"\\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}\">
      \\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}
    </span>
  </p>
will not necessarily vanish.</p>
<div>
```

<img width="599" alt="Screenshot 2020-05-02 at 4 55 02 PM" src="https://user-images.githubusercontent.com/3765085/80862903-2dd2e380-8c96-11ea-8d42-04fc8b662e8a.png">

Could you please help me with this?

Thanks.

**Comment by KillerCodeMonkey** [comment]
I think not. i guess you have some invalid formulars there.

Seems like the `after` element is not defined.

Did you correctly configured the formula module?
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/formula/formula.component.ts#L17

I updated your issue and formatted the html, and there is a missing p-tag?
See `will not necessarily vanish.</p>` at the end. i can not find the opening p-tag for that.

**Comment by ksabariraj** [comment]
Thanks for your quick reply.

I cross-checked int configuration and corrected the HTML. But still not rendering the second occurrence of formula, the first one renders properly. Please see the below attachment.

FYI, I used the same formula in both places.

HTML Content: `<p>
                              Consider the point P on the curve y = f (x) whose coordinates are (x, y) and another point Q where coordinates are (x + Δx, y + Δy). The slope of the line joining P and Q is given by:
                            </p>
                            <p>
                              <span class=\"ql-formula\" data-value=\"\\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}\">
                                \\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}
                              </span>
                              -------------------- (1)
                            </p>
                            <p>
                              <span class=\"ql-formula\" data-value=\"\\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}\">
                                \\tan\\theta = \\frac{\\triangle y}{\\triangle x}=\\frac{(y+\\triangle y)-y}{\\triangle x}
                              </span>
                              -------------------- (2)
                            </p>`

<img width="310" alt="Screenshot 2020-05-02 at 6 10 28 PM" src="https://user-images.githubusercontent.com/3765085/80864434-38927600-8ca0-11ea-9a56-bcffba293e4b.png">

**Comment by KillerCodeMonkey** [comment]
Did you tried to rebuilding your functions with a quill Editor and compared
the HTML with yours?

Sabariraj K <notifications@github.com> schrieb am Sa., 2. Mai 2020, 14:41:

**Comment by KillerCodeMonkey** [comment]
@ksabariraj 
i added you html to my demo repo and it is working fine:

https://killercodemonkey.github.io/ngx-quill-example/

check the editor for the heading: "Formula & image resize editor & Keybinding on 'b' and 'shift + b', CodeBlock + Syntax Highlighting"

**Comment by ksabariraj** [comment]
Fixed. Thanks for your valuable time and support.
