### ISSUE TITLE
9.2.0 Build error

### ISSUE THREAD

**Issue by pedrojrivera** [KillerCodeMonkey/ngx-quill#882]
Upgraded to latest version 9.2.0 and getting error during build.

Compiling ngx-quill : es2015 as esm2015

```
ERROR in node_modules/ngx-quill/src/quill-editor.component.d.ts:3:17 - error TS2614: Module '"C:/Users/pedro/Documents/Development/ussi/e-solutions/node_modules/@types/quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "C:/Users/pedro/Documents/Development/ussi/e-solutions/node_modules/@types/quill"' instead?

3 import Quill, { Delta } from 'quill';
```

**Comment by KillerCodeMonkey** [comment]
which version do you use?

**Comment by KillerCodeMonkey** [comment]
and did you installed @types/quill as dev dependency?

**Comment by pedrojrivera** [comment]
Downgrading to @types/quill": "^1.3.10" fixed it. Thanks!

**Comment by eng-dibo** [comment]
the same here

installed versions:
ngx-quill:  12.0.1 (requires quill v1.3.7)
quill: 1.3.7
quill-delta: 4.2.2
@types/quill: 2.0.4

**Comment by joshorvis** [comment]
I had same issue as @eng-dibo.  Downgrading to @types/quill ^1.3.10 worked for me.

**Comment by sjonibek** [comment]
For Angular 13. Downgrading to @types/quill ^1.3.10 worked for me.
