### ISSUE TITLE
Feature Proposal: SSR Compliance without Mocking window and document!

### ISSUE THREAD

**Issue by ansaries** [KillerCodeMonkey/ngx-quill#883]
## Problems in using `window` and `document` mock and loading quill on Server:
1. There are many third-party libraries using the `typeof window` checks to prevent certain code from running on the server.
2. Quill is a client-side editor, only required once it is loaded on the browser. The Quill-View-Html component does not rely on quill.js at all which can be rendered by server.
3. We can remove 430+Kb of Quill.js uncompressed javascript from the application bundle.

## Proposal
1. We can use the new `import()` for lazy loading the Quill to load only when its browser and remove it from the vendors bundle.
2. We can remove the Quill module registration from the `forRoot` method of QuillEditorModule and move it to the component.
3. I can do the refactoring and create a pull request if you have no further questions.

## Sample Code:
In quill-editor.component.ts
Instead of :
```
import Quill, { Delta } from 'quill'
// eslint-disable-next-line @typescript-eslint/no-var-requires
const QuillNamespace = require('quill')
```
We do this:
```
let QuillNamespace;
const QuillPromise = normalizeCommonJSImport(() =>
  import(/* webpackChunkName: "quill" */ 'quill')
);
```

and then refactor `ngAfterViewInit`
```
ngAfterViewInit() {
    if (isPlatformServer(this.platformId)) {
      return;
    }

    this.initEditor().then(() => console.log('Editor Initialized'));
  }
```
and create the `initEditor` as follows:

```
async initEditor() {
    QuillNamespace = await QuillPromise();
    
....
rest of the code from `ngAfterViewInit`
```
This way webpack will create a quill.js file separately in the dist folder and the `initEditor` will only load it which will never be called on SSR.

> For registering the custom config, we can create a service and call its init method in `initEditor` which will register them only once and remove Quill Custom Config Registration logic from `forRoot`.

This will produce something like:
![Lazy Quill](https://user-images.githubusercontent.com/19625307/81024610-53760d80-8e8d-11ea-91ca-e464be4b4df0.gif)

**Comment by KillerCodeMonkey** [comment]
sure :). just do it :D.

I thought those dynamic import things are not working for all build targets.

**Comment by ansaries** [comment]
Ok I have sent you the PR [here](https://github.com/KillerCodeMonkey/ngx-quill/pull/885#issue-413810139), please review my comments and let me know your opinions.

**Comment by KillerCodeMonkey** [comment]
please try v 10.0.0-0

**Comment by KillerCodeMonkey** [comment]
and v10.0.1 is released
