### ISSUE TITLE
Creation of QuillEditor creates valueChanges in form

### ISSUE THREAD

**Issue by jakobjoachim** [KillerCodeMonkey/ngx-quill#888]
When the quill editor is created with reactive forms it triggers value changes immediately. This should not happen as there is no change in the form.

I created a stackblitz with the minimal issue: https://stackblitz.com/edit/angular-ybjezc

**Comment by KillerCodeMonkey** [comment]
@jakobjoachim this is actually an angular issue:
https://github.com/angular/angular/issues/25749

i need to call angular validation manually after quill editor and content is init. 
This triggers the controls value changes observables.

So just listen on it with `distinctUntilChanged`

**Comment by jakobjoachim** [comment]
Alright, thank you very much anyway
