### ISSUE TITLE
ngx-quill toolbar.addhandler() click to open imagemodal but not showing image(show after click somewhere one) Angular 9

### ISSUE THREAD

**Issue by Vachnak** [KillerCodeMonkey/ngx-quill#889]
I try custom imagehandler but when I click it to open the image modal it won't show any image until I click somewhere one and it will show the image
my code:

     getEditorInstance(editorInstance: any) {
           const toolbar = editorInstance.getModule('toolbar');
           toolbar.addHandler('image', this.imageHandler.bind(this));
      }

      imageHandler() {
        this.loadGalleryImageModal();
        this.modal = this.modalService.open(this.imageModal, { size: 'lg', backdrop: 'static' });  
      }

**Comment by KillerCodeMonkey** [comment]
Everything quilljs does internally runs outside of the angular zone of performance reasons.

So when there is a custom dom event inside the editor which then triggers your image handler angular does not know about this.

Solution:
Inject the `ChangeDetectorRef` and trigger change detection on your own, by calling `this.changeDetectorRef.detectChanges()`.

**Comment by pavlovicnemanja** [comment]
@Vachnak did you managed to solve this?

**Comment by KillerCodeMonkey** [comment]
@pavlovicnemanja do you tried my suggestion?

**Comment by pavlovicnemanja** [comment]
Yep, but didn't help. Modal still opened without content inside... Really strange.

**Comment by KillerCodeMonkey** [comment]
okay but it opens, so this is working and the connection between quill/ngx-quill and your app is working. 

Everything else is more another topic. not related to ngx-quill.

But without a full example nobody can help you.
Your imageHandler is called and working.

But what does:

`this.loadGalleryImageModal();`

And what is the `this.imageModal` exactly.

**Comment by pavlovicnemanja** [comment]
Ok so, this is `getEditorInstance`:
```    getEditorInstance(editorInstance: any) {
        const toolbar = editorInstance.getModule('toolbar');
        toolbar.addHandler('image', this.imageHandler.bind(this));
    }```

and image handler should call upload modal:
```    imageHandler() {
        this.upload.call('upload');
}```

I have upload service which calls this modal:
```call(url: string) {
        return new Promise((resolve, reject) => {
            const modal = this.dialog.open(UploadComponent);

            modal.componentInstance.url = url;

            modal.afterClosed().subscribe(result => {
                if (result)
                    return resolve();

                return reject();
            });
        });
    }```

Everything works fine outside of quill toolbar, modal is opened as expected:
![image](https://user-images.githubusercontent.com/6507688/81682422-1ee9ef00-9455-11ea-83e9-ddebb1cd339c.png)

But if I called it from `toolbar.addHandler` it looks like this:
![image](https://user-images.githubusercontent.com/6507688/81682993-c2d39a80-9455-11ea-956a-f1f93777f0b7.png)

After clicking inside the modal, content is shown, but now I can't close modal.
![Screen Recording 2020-05-12 at 13 35 02](https://user-images.githubusercontent.com/6507688/81683157-029a8200-9456-11ea-9c32-8161ad13b2a5.gif)

**Comment by KillerCodeMonkey** [comment]
could you try to wrap your content of the image handline in `ngZone.run()` because editor creation is taking place outside of angular zone. so you have to reattach your angular code.

**Comment by pavlovicnemanja** [comment]
It WORKS! Thanks a lot:

This is a solution:
```
    imageHandler() {
        this.ngZone.run(() => {
            this.upload.call('upload');
        });
```
