### ISSUE TITLE
Not able to write any content if page is translated with Google auto-translate

### ISSUE THREAD

**Issue by MatviiStelmakh** [KillerCodeMonkey/ngx-quill#892]
STR:
1. open demo page https://killercodemonkey.github.io/ngx-quill-example/
2. right click - choose translate to ...(Russian in my case)
3. type any text

Problem: text is cleared once appears

Chrome Browser, Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by KillerCodeMonkey** [comment]
i do not have something like "choose translate to". Do you use any plugin for that?

and please check if this is working with native https://quilljs.com/

**Comment by KillerCodeMonkey** [comment]
@MatviiStelmakh i tested it with native quill. it occurs there as well. so it is a quilljs thing.

**Comment by MatviiStelmakh** [comment]
> @MatviiStelmakh i tested it with native quill. it occurs there as well. so it is a quilljs thing.
> [quilljs/quill#2286](https://github.com/quilljs/quill/issues/2286)
> 
> Possible solutions are in the issue:
> [quilljs/quill#2286 (comment)](https://github.com/quilljs/quill/issues/2286#issuecomment-451187905)

thanks a lot

**Comment by KillerCodeMonkey** [comment]
np
