### ISSUE TITLE
Is there a way to disable the editor?

### ISSUE THREAD

**Issue by pragatikerur** [KillerCodeMonkey/ngx-quill#893]
Hi, I want to disable the editor once the user is done entering the input, how can I achieve this? I tried with setting contentEditable to false it doesn't seem to work.
 Thanks

**Comment by KillerCodeMonkey** [comment]
just set the input `readOnly` to `true`

**Comment by iKrishnaSahu** [comment]
@KillerCodeMonkey 
If we set `readOnly` to `true`, the toolbar buttons are still enabled although the button clicks does not do anything.
Is this expected?

**Comment by KillerCodeMonkey** [comment]
It is that what the quill editor does if you disable i, guess
