### ISSUE TITLE
Error TS2614 when linting `ngx-quill@10.0.1`

### ISSUE THREAD

**Issue by KeithGillette** [KillerCodeMonkey/ngx-quill#896]
After updating to `ngx-quill@10.0.1`, I get the following linting error:

```
ERROR in node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:21 - error TS2614: Module '"../../@types/quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "../../@types/quill"' instead?

3 import QuillType, { Delta } from 'quill';
 ```

**Comment by KillerCodeMonkey** [comment]
install `@types/quill` 1.3.10 as dev dependency

**Comment by KeithGillette** [comment]
We are already using `"@types/quill": "2.0.3"`. Are you suggesting we need to downgrade?

**Comment by KillerCodeMonkey** [comment]
in general the `@typings` should match the real package version.

so `@types/quill` 2.0.3 are for quilljs 2.x
latest version for quilljs is 1.3.10 ;-)

**Comment by KeithGillette** [comment]
Oops, got it. Thanks so much for your fast, helpful replies—and for maintaining this library!

**Comment by revzo** [comment]
> általában meg `@typings`kell egyeznie a valódi csomag verzióval.
> 
> így a `@types/quill`2.0.3 a quilljs-re vonatkozik. 2.x a quilljs
> legújabb verziója az 1.3.10 ;-)
> 
> Mivel csak a stabil quill verziót szeretném támogatni, még nem támogatom a quilljs 2 dev verzióit.
> 
> szerintem a quilljs 1.3.7 és a @ type / quill 1.3.10 megoldja a problémát.

Thansk for the solution! :)

**Comment by sahilkumarsahoo** [comment]
it work properly in
**angular12**
**"@types/quill": "^1.3.10",**
**"ngx-quill": "^15.0.0",**
**"quill": "^1.3.7",**

**Comment by KillerCodeMonkey** [comment]
Why you are linting node modules?

And since v15 you should use angular v13

sahil kumar sahoo ***@***.***> schrieb am So., 5. Dez. 2021,
07:52:
