### ISSUE TITLE
The onEditorCreated event seems to take a long time to send out

### ISSUE THREAD

**Issue by GitHubish** [KillerCodeMonkey/ngx-quill#897]
It seems that I have some slowness which appeared a few days ago following an update of Ngx-Quill but I'm not sure.
To give a bit of background information, I have a Board (like Trello) where each card is editable with Quill. What I notice is that as soon as I have a few cards, it takes a long time before the editor is ready and I can manipulate Quill with the API to set my content. My content being rich content, not just text. 

Do you have any idea what could produce this slowness? The editor with the placeholder only appears a few seconds after I receive the event telling me that Quill is ready. Strange isn't it?

Thanks !

**Comment by KillerCodeMonkey** [comment]
I added async loading for quilljs (so quilljs is only loaded when needed and accessed -> fixing some things for server side rendering.

But in general it should not take seconds Oo.

so my demo-repo is containing a lots of editor instances, and it loads quite fast:
https://killercodemonkey.github.io/ngx-quill-example/

**Comment by KillerCodeMonkey** [comment]
And i have some logic in the service, that should check, if the editor is already "loading". maybe there is something wrong with it?

Could you check, how often quilljs is loaded in your app.
https://github.com/KillerCodeMonkey/ngx-quill/blob/master/projects/ngx-quill/src/lib/quill.service.ts#L17

**Comment by KillerCodeMonkey** [comment]
BTW: you should not instantiate so many editors on load of a card. I would just instantiate maybe 1 (to get quilljs loaded). And then aktive/instanciate an editor if you click on a card.

**Comment by GitHubish** [comment]
Thank you for this information. Yes I would like to be able to do this optimization but it is not yet developed. The reason is that using QuillJS everywhere means that you don't have several different codes for formatting the @mention but also other modules. Stupid question, if I use Quill-view for this part instead, would it change anything else ? Thank you for your reactivity

**Comment by KillerCodeMonkey** [comment]
quill-view just renders QuillJS without a toolbar and in readonly mode in general. So yes you can just replace quill-editor for it.

if you are storing the html-strings in your database you can even use quill-view-html component (it does not init quilljs at all).

**Comment by GitHubish** [comment]
Ok so if I understand, a priori with Quill-view I should have the same concern since the instantiation of QuillJs should take as much time as with the quill editor. 
No I store the json content in another format and use the Quill API to render it. On output I transform the Delta into my own format.

**Comment by KillerCodeMonkey** [comment]
@GitHubish could you check in which version you notice the increase of the loading (instantiation) time?

**Comment by KillerCodeMonkey** [comment]
in my demo repo i have 19-20 editors and it instantiate quite fast.

**Comment by GitHubish** [comment]
I see it in version 10.0.1 and version 8.13. I went down to version 8.0.0 I have the impression that the times are similar. Hard to say then. There are indeed a lot of editors on my example (more than 50).
I will try to replace QuillJS by a viewer readonly in these maps. I close the issue I do not see any regression directly attributable to NgxQuill. Maybe the last update of Angular in version 9 has introduced this slowness... Thank you again for your follow up!

**Comment by KillerCodeMonkey** [comment]
@GitHubish keep in mind that you in general should not use default change detections in your projects. use OnPush strategy :).

And let me know if you have some findings, or what i can change to boost performance.

**Comment by awais2080** [comment]
i am facing the same issue onEditorChange takes ages .

**Comment by awais2080** [comment]
and last character is cut and cursor moves to start of the line

**Comment by awais2080** [comment]
speed and last character can be improved by onContentChanged, but cursor moving to start of the line still remains the problem.

**Comment by GitHubish** [comment]
Personally I solved my slowness problem by replacing the editors with a read-only viewer. With only a few editors displayed at the same time I don't have a slowness problem. @awais2080 what's your problem with the cursor that goes at the beginning, I don't think I understood your problem ?

**Comment by awais2080** [comment]
I have made this as angular component and self save function is called.

And when th data is save , cursor goes to start of the line as i will still
want to change text.

**Comment by awais2080** [comment]
@GitHubish  dear i have auto save field (quill-editor) , so when some one does not type till 3 seconds. save function is called automatically to make api request. and after the success response the cursor moves to the start of the field (quill-editor)

![image](https://user-images.githubusercontent.com/39415658/95914178-c382ab00-0dbe-11eb-8e85-bf245ade1539.png)
