### ISSUE TITLE
Reactive forms and validation issues

### ISSUE THREAD

**Issue by koreem** [KillerCodeMonkey/ngx-quill#898]
How to add validation in combination with reactive forms in Angular?

I have a parent component and one child component. In the child component I'm using the quill editor. How can I set a maxLength? When I set maxLength in my parent component form and the maxLength property in the editor component, both are behaving different.

The format I use is json, so the maxLength validator on my form takes the extra json characters into account, where the maxLength on the editor it self only considers the typed in characters. 

I have the same issue with the required validator on my form, once I start typing there the form will never be invalid anymore regarding the required validation, because it will always have some json in there.

**Comment by KillerCodeMonkey** [comment]
You have to use the custom validation inputs / properties Provided by the
quill-editor component.

Check the readme and the Demo repo fit The usage.


   - maxLength - add validation for maxlength - set model state to invalid
   and add ng-invalid class
   - minLength - add validation for minlength - set model state to invalid
   and add ng-invalid class, only set invalid if editor text not empty -->
   if you want to check if text is required --> use the required attribute
   - trimOnValidation - trim trailing|leading newlines on validation run
   for required, min- and maxLength, default false
   - required - add validation as a required field - [required]="true" -
   default: false, boolean expected (no strings!)


Marc Koree <notifications@github.com> schrieb am Mo., 11. Mai 2020, 15:41:

**Comment by koreem** [comment]
Thanks for your fast answer. So I don't have to add any Validators to my form, but only have to work with the required or maxLength properties from the editor it self?

**Comment by KillerCodeMonkey** [comment]
Yep.

Marc Koree <notifications@github.com> schrieb am Mo., 11. Mai 2020, 15:55:

**Comment by koreem** [comment]
Aaah I don't have to use the form validators at all, but only have to set the validation properties on the editor. Thanks got it working now. Kudos for the library btw :)

**Comment by LuRojana14** [comment]
Hi!! I have the same problem, can i see how you have solved in the code? Thanks!!
