### ISSUE TITLE
Adding a Source Button to Toolbar

### ISSUE THREAD

**Issue by isaac2004** [KillerCodeMonkey/ngx-quill#90]
I came across this Issue on QuillJS

https://github.com/quilljs/quill/issues/128

And thought this is something that could be done inside of this module. It seems someone has done it already but it would need to be tested
https://codepen.io/anon/pen/ZyEjrQ

Not sure if there was a plan to add this feature as it is useful.

**Comment by KillerCodeMonkey** [comment]
Sorry but this should be done in an own custom module for quill.

It has nothing to do with this repo here. Ngx-quill is a wrapper to use
quilljs easy with angular.



Am 04.01.2018 3:50 nachm. schrieb "Isaac Levin" <notifications@github.com>:
