### ISSUE TITLE
Error while building production 

### ISSUE THREAD

**Issue by shivasurya** [KillerCodeMonkey/ngx-quill#911]
Using Angular ~8.1.1 version and Ngx-Quil 10.0.5 version.

While building production using ngx build --prod the corresponding issue occurs, is there any way to fix this please?

ERROR in : Directive QuillEditorBase in /projectpath/node_modules/ngx-quill/ngx-quill.d.ts has no selector, please add it!

Thank you.

**Comment by shivasurya** [comment]
Downgraded to ~5.2.0 and it;s working fine ( had a urgent requirement to fix )

**Comment by KillerCodeMonkey** [comment]
You should check your tsconfig. Everything works with Production build in
my Demo repo.

s.shivasurya <notifications@github.com> schrieb am Do., 14. Mai 2020, 11:23:

**Comment by KillerCodeMonkey** [comment]
@shivasurya seems like angular 8 does not allow abstract directives without a selector, but in angular 9 it is valid.

Are you able to upgrade to angular 9? i find it a little bit lame to introduce a "never-used" selector...

**Comment by KillerCodeMonkey** [comment]
@shivasurya there is no chance to get this working with angular 8, i released v11 and updated the readme + peer dependencies.

Angular 8 can only use ngx-quill <10. (keep in mind lts support of angular 8 ends in 6 months)

**Comment by shivasurya** [comment]
Thank you for the info. I'll have a look at it (y)
