### ISSUE TITLE
angular 9 ngx module registration

### ISSUE THREAD

**Issue by kiag0** [KillerCodeMonkey/ngx-quill#915]
For instance, using the image resize module, there is no webpack workaround

**Comment by jdgamble555** [comment]
Image Resize Module generally has caused a lot of pain for a lot of people, but yes, there is a [webpack workaround](https://github.com/KillerCodeMonkey/ngx-quill/issues/91#issuecomment-626223366).

**Comment by kiag0** [comment]
Yeah it exists but does not work on angular 9.

**Comment by jdgamble555** [comment]
The webpack workaround 100% does work on IVY.  You have to actually read my post, as I show you how to use it correctly.  Here is my [repo](https://github.com/jdgamble555/ngx-quill-ssr).  Also, make sure you use **image-resize** instead of **image-resize-module**.

**Comment by KillerCodeMonkey** [comment]
@kiag0 just check my demo repo. there are examples with image resize.

https://github.com/KillerCodeMonkey/ngx-quill-example

it has ivy enabled and uses angular 9 + ngx-quill latest version... no special workarounds.
https://killercodemonkey.github.io/ngx-quill-example/

If you are using angular universal for ssr you need to mock window and document to get it work.
