### ISSUE TITLE
'quill-view' is not a known element

### ISSUE THREAD

**Issue by jdgamble555** [KillerCodeMonkey/ngx-quill#916]
@KillerCodeMonkey I notice since the update, the **quill-editor** element does not seem to resolve in visual studio code.  It will compile, but Visual Studio does not recognize the 'quill-view' or 'quill-editor' elements.  Any thoughts?

![quill](https://user-images.githubusercontent.com/8333090/82153466-364a2300-982d-11ea-8dae-9eae90f82f3c.png)

**Comment by KillerCodeMonkey** [comment]
<img width="1285" alt="Bildschirmfoto 2020-05-17 um 18 48 32" src="https://user-images.githubusercontent.com/2264672/82154566-0d4a8200-986f-11ea-839d-467aa6f21dd0.png">

it is working for me -> my angular universal project + ngx-quill v11.

https://github.com/KillerCodeMonkey/ngx-quill-universal-example

**Comment by KillerCodeMonkey** [comment]
@jdgamble555 did you tried restarting vscode?

sometimes after running `npm install` / `yarn install` it does not recognize the typings.

**Comment by jdgamble555** [comment]
seems to be fixed after ```npm i ngx-quill@latest``` - I think it was a cached problem in VS Code.  Thanks.
