### ISSUE TITLE
how to add attachment with quill editor form data?

### ISSUE THREAD

**Issue by indrajithvenu007** [KillerCodeMonkey/ngx-quill#917]
i've used quill editor for composing email in my project. Now im in a situation where i need to add attachments along with this data.

**Comment by KillerCodeMonkey** [comment]
- just put a file input under the quill editor
- Or add a custom toolbar with an "attachment" button where you trigger a click on a hidden file input
- or build a custom blot https://quilljs.com/guides/how-to-customize-quill/#customizing-blots

But in general i would add a custom buttom to the toolbar and list the selected files under the editor.

**Comment by Rkumaran06** [comment]
1.

**Comment by boceksoft** [comment]
https://ckeditor.com/ckeditor-5/demo/mobile-support/
