### ISSUE TITLE
Upload pdf, any file extension

### ISSUE THREAD

**Issue by agam16** [KillerCodeMonkey/ngx-quill#92]
Sorry, i am asking a lot. But i need to upload any image, graph, pdf, excel file, word doc, link. How can i add the handler for that or how can i proceed using that?

**Comment by KillerCodeMonkey** [comment]
you could create an own quill module.
https://quilljs.com/guides/building-a-custom-module/

and checkout the implementation of the image and link module of quilljs. ;)

**Comment by agam16** [comment]
@KillerCodeMonkey Thanks, will try to create an module for that

**Comment by maggask** [comment]
@agam16 were you able to implement a custom module to add file upload? I'm in a similar situation and just wondering how much hassle it is.

**Comment by oneEyedSunday** [comment]
@agam16 @maggask did anyone get to do this?

**Comment by KillerCodeMonkey** [comment]
If i could make a shot^^

Just add a custom Blot or

Add a custom toolbarbutton with a clickhandler (triggering a Hidden
File-Input click). The Default system/Browser File Pickerl opens. Choose a
File - upload IT and Insert the result url/path at the current Index of the
selection.

I think when You search for File Upload through the quilljs issues in the
quilljs Repo You will find some examples


Idiakose O. Sunday <notifications@github.com> schrieb am Fr., 6. Sep. 2019,
20:22:
