### ISSUE TITLE
Can't paste image from Word in Chrome Browser

### ISSUE THREAD

**Issue by DavidFrancois** [KillerCodeMonkey/ngx-quill#923]
Hello, I have some issue working with ngx-quill and Chrome browser.

The library correctly allows one to copy/paste an image from MSWord (or any image file on the file system actually) when working with Firefox. Sadly it doesn't seem to work at all with Chrome.

After searching for a while I didn't see any library/issue to use as a workaround.

ImageDropAndPaste and ImageDropModule has already been tested.

I also tried to use add an Handler but it doesn't seem to be triggering at all (quill.addHandler('image', function) )

**Comment by KillerCodeMonkey** [comment]
You should ASK this at the quilljs repo ;-)

DavidFrancois <notifications@github.com> schrieb am Mo., 25. Mai 2020,
17:01:

**Comment by DavidFrancois** [comment]
Yeah it makes sense sorry.

Here is a link to the issue I opened on the official Quill github repo : 
https://github.com/quilljs/quill/issues/3047
