### ISSUE TITLE
Blob image is not rendering

### ISSUE THREAD

**Issue by satish666** [KillerCodeMonkey/ngx-quill#924]
I am using image upload. Before sending it to server i am casting image as Blob .
But blob url is not working.
data.url is complete blob address like 
```
blob:http://localhost:4200/27707e31-076d-47bc-a4d8-797d9ee827e5";

this.editorInstance.insertEmbed(this.editorRange, 'image', `${data.url}`,"user");
```

Some where i found this
```
var ImageBlot = Quill.import('formats/image');
        ImageBlot.sanitize = function (url) {
            return url;  // No sanitization
        };
```

**Comment by KillerCodeMonkey** [comment]
Just check quilljs repo ;-)

**Comment by satish666** [comment]
I do what they said but the src is like http: //0 .URL sanitization they suggests
