### ISSUE TITLE
Link does not accept file:///

### ISSUE THREAD

**Issue by aalbericio** [KillerCodeMonkey/ngx-quill#925]
Does NGX-QUILL support creating links to file:///?

It keeps on leaving the href as "about:blank"

Thanks

**Comment by KillerCodeMonkey** [comment]
if quilljs does not support it then ngx-quill neither ;-).

**Comment by KillerCodeMonkey** [comment]
maybe you need to implement your own link blot, e.g. https://github.com/quilljs/quill/issues/2277#issuecomment-417301993
