### ISSUE TITLE
Link popup is misplaced to the left

### ISSUE THREAD

**Issue by tommueller** [KillerCodeMonkey/ngx-quill#929]
Hi, when using the quill-editor in a modal, I have the issue that the positioning of the link popup is too far to the left, and then being cutoff.
![image](https://user-images.githubusercontent.com/2970691/83421429-63e7bc80-a428-11ea-8712-641a84798a4b.png)

Looking at the quill-demo, there it is positioned correctly, so I assume this is a problem with ngx-quill?

Thanks! Let me know if you need more info!

**Comment by KillerCodeMonkey** [comment]
It is working in my Demo.

You can Pass a bounds Input which is the Dom element everything is aligned
at.

Per Default it is document.body ;-).



Tom Müller <notifications@github.com> schrieb am Mo., 1. Juni 2020, 16:54:

**Comment by tommueller** [comment]
[bounds]="'self'" fixed it. Thanks!

**Comment by KillerCodeMonkey** [comment]
no probs, glad you fixed it :)
