### ISSUE TITLE
DI on custom modules

### ISSUE THREAD

**Issue by jeffyzxc** [KillerCodeMonkey/ngx-quill#930]
Hello, good day,

Question How can I inject service in custom modules?

thanks :D

**Comment by KillerCodeMonkey** [comment]
custom modules is there to pass custom quill modules and angular classes or services.

See https://github.com/KillerCodeMonkey/ngx-quill-example/blob/b52c7c926da4b03538843fbfc3ef13cf3fe3933f/src/app/app.module.ts#L68

and https://github.com/KillerCodeMonkey/ngx-quill-example/blob/7414f782973c4ecb763b0513c5644726a3e0f7fb/src/app/custom-toolbar/custom-toolbar.component.html#L6

So this has nothing to do with angular, just plain JS/TS classes.

**Comment by jeffyzxc** [comment]
thank you!
