### ISSUE TITLE
quill-editor not Working in IE

### ISSUE THREAD

**Issue by shohamyamin** [KillerCodeMonkey/ngx-quill#932]
in IE, the component of quill-editor  loaded but when try to write something it stuck the page
in chrome it work fine.
I try to fix it with some of the answers in the web include here and it still not work

package.json:
"@angular/cli": "^9.0.0-rc.0",
"ngx-quill": "^11.0.0",
    "quill": "^1.3.7",
    "quill-emoji": "^0.1.7",
    "quill-mention": "^2.2.5"

**Comment by KillerCodeMonkey** [comment]
my demo repo is working in browserling + IE11.

please try plain ngx-quill without emoji and mention.
Then paste the error if the problem still exists.

**Comment by shohamyamin** [comment]
I try youre repo(ngx-quill-example) and things thier going one on another in IE11
![Capture1](https://user-images.githubusercontent.com/45430879/83514370-33f9f100-a4dc-11ea-89d6-066eea53ae69.PNG)

 but still you can write inside the component so i dont think it's related, evene that I am change my polyfills.ts to be like youre polyfills.  I am not using  emoji or mention im my component, and my component dont throw enthing when I try to write something in the editor area it just stuck and the explorer freez.

**Comment by KillerCodeMonkey** [comment]
beside of the styling things (because.. come on it is IE11) nothing stucks there. you can type and nothing freezes (just scroll up to the first editor on the demo page).

or just clone the demo repo and just leave one test component in the app.component.ts.

It is working there.

You could even create a plain new angular cli projekt and add ngx-quill there. it works :)

**Comment by shohamyamin** [comment]
@KillerCodeMonkey In my case the problem(IE11 freez when trying to write in the component) was with the formControlName in the IE11, when I remove it the component work just fine. I fix the problem by using ngModel instend and set value to the formControl from the code directly
