### ISSUE TITLE
Chrome - Spell checker causes text disappear when set a color for the text

### ISSUE THREAD

**Issue by 985664960** [KillerCodeMonkey/ngx-quill#933]
Re-Produce Steps
1. input text "1sdlfsdjlfk sdflsdflsdfj foxx dfksdkf"
2. select all and select a color the the text
3. right click on "foxx" and select 'fox'(Spell check from chrome), then all the text disappear

**Comment by KillerCodeMonkey** [comment]
check if this occurs with plain quilljs as well. then please ask there for help ;-)

**Comment by KillerCodeMonkey** [comment]
https://github.com/quilljs/quill/issues/2387
https://github.com/KillerCodeMonkey/ngx-quill/issues/40

**Comment by 985664960** [comment]
OK, thank you
