### ISSUE TITLE
Behaviour of adding invalid link to video control

### ISSUE THREAD

**Issue by koreem** [KillerCodeMonkey/ngx-quill#934]
What is the expected behaviour of adding invalid link to video control? Right now it somehow embeds the whole web application again in the editor.

**Comment by KillerCodeMonkey** [comment]
do not know? 
i never changed the default handling for that.
how does quilljs is handling it?

if  i add the video format to the toolbar here:
https://quilljs.com/playground/

and it seems it adds the source to your current window.href.
So it seems a quilljs problem

**Comment by koreem** [comment]
Mmm indeed it seems like quilljs problem, will close this one.
