### ISSUE TITLE
Responsive videos

### ISSUE THREAD

**Issue by sebrojas14** [KillerCodeMonkey/ngx-quill#937]
When I inserted a YouTube video, and then use `quill-view-html` to show the content, the video embed appears small. The video size shouwld be setiable and responsive when displaying.

**Comment by KillerCodeMonkey** [comment]
i only use basic quilljs functionality. per default quilljs adds an iframe for the video with the css class `ql-video`. Thats it. This class sets only the max-width to 100%.
If you want to change the styling of it -> just style it :).

Or checkout this: https://github.com/quilljs/quill/issues/1707

I will not add special transformations/stylings for quilljs formats or blots. This should be done at the quilljs repo.
