### ISSUE TITLE
Aot Build issue

### ISSUE THREAD

**Issue by prabhpahul** [KillerCodeMonkey/ngx-quill#945]
With Angular 9 and Aot = true, not able to initialize Quill Editor.
Getting error below. I've a library which wraps quill-editor and I've followed exampled in this repo. Everything is working fine with aot=false but not able to get quilEditor instance with aot=true.

Thank you.
```
core.js:6228 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'register' of null```

**Comment by KillerCodeMonkey** [comment]
and how do you use ngx-quill in your project?

everything works building my example repo for production

**Comment by prabhpahul** [comment]
Thank you for quick response.
I was able to resolve it by turning on Ivy. With ivy false it was giving error on my custom form control build on the top of ngx quill editor.

**Comment by KillerCodeMonkey** [comment]
okay, so the error occurs in within your component not in ngx-quill? then feel free to close this issue :)
