### ISSUE TITLE
click event on the editor

### ISSUE THREAD

**Issue by chantimothy** [KillerCodeMonkey/ngx-quill#946]
Hello:

I was wondering if ngx-quill, or quill in the case support onClick event on images, I had been trying to look for a solution but can't seem to find one without resorting to display the innerHtml.

Thank you very much for your time and I really appreciate your work.

Regards,

Tim

**Comment by KillerCodeMonkey** [comment]
what do you wanna achieve?

in general you could extend the image blot of quilljs to pass a "click" handler to the inserted image.

the easiest way would be to just query all images in the editor content element and add your click handler.

**Comment by KillerCodeMonkey** [comment]
here is something similar -> click listener and checking if the target of type ImageBlot https://github.com/quilljs/quill/issues/2432#issuecomment-451517928
