### ISSUE TITLE
Changed initial value

### ISSUE THREAD

**Issue by yarik-vv** [KillerCodeMonkey/ngx-quill#947]
Hi, guys! I have a problem, when initializing the value in the quill editor I received a modified html (onContentChanged). 

Initial value with `ngModel`:
`<span style="background-color: rgb(213, 227, 227); color: rgb(0, 0, 0);">Hi</span>`

onContentChanged value html:
`<span style="color: rgb(0, 0, 0); background-color: rgb(213, 227, 227);">Hi</span>`

Why does such an effect occur and how can I get around this?

**Comment by KillerCodeMonkey** [comment]
this occurs, because when passing html i use quilljs api to "validate" transform the html.
I think quilljs does it.

maybe just do not use the html format. use Delta/Object format.
