### ISSUE TITLE
unable to sanitize quill-view

### ISSUE THREAD

**Issue by nstringham** [KillerCodeMonkey/ngx-quill#949]
I am able to set `[sanitize]="true"` in a quill-editor but not in a quill-view.

**My code:**
```html
<quill-view [content]="myContent" [sanitize]="true"></quill-view>
```

**Expected result:**

ngx-quill will sanitize myContent and then display it to the user

**Actual result:**

a compile error

**error message:**

> ERROR in <myComponent.html> - error NG8002: Can't bind to 'sanitize' since it isn't a known property of 'quill-view'.
    1. If 'quill-view' is an Angular component and it has 'sanitize' input, then verify that it is part of this module.  
    2. If 'quill-view' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component 
to suppress this message.
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by KillerCodeMonkey** [comment]
implemented in 11.1.0
