### ISSUE TITLE
Problems with inserting text

### ISSUE THREAD

**Issue by Flayovec** [KillerCodeMonkey/ngx-quill#95]
Hello, I have problems with inserting text... I have long text with many html tags and I need to put it into the editor, so I tried `editorInstance.insertText`, but this is only for some part of the text with same tags, so I tried `[ngModule]="content"` but this will throw error (Can't bind to 'ngModule' since it isn't a known property of 'quill-editor'), so I tried to put the text by using `editorInstance.content = this.content`, but this doesn't work too, can you help me ?  Thank for any help !

**Comment by KillerCodeMonkey** [comment]
the key is ngModel not ngModule ;)

quilljs api doc says: insertText only allows to insert text not an unsafe html-string.

You should be fine using the angular way with ngModel (template driven forms) or formControl (reactive forms).

**Comment by Flayovec** [comment]
If I use ngModel it throw same error :/

**Comment by KillerCodeMonkey** [comment]
okay then check out https://killercodemonkey.github.io/ngx-quill-example/ --> the example "without toolbar and ngModel"

the source can be found in my ngx-quill-example repo.

**Comment by Flayovec** [comment]
Thank you ! Now it works, I use reactive forms.
