### ISSUE TITLE
Angular v.10 support

### ISSUE THREAD

**Issue by Ksan8** [KillerCodeMonkey/ngx-quill#952]
I just upgraded my project from Angular v.9 to v.10, and notice that the content within `<quill-view>` elements display without the html tags removed, and when I click back into the editor to edit saved text, some of the styling (e.g., text color) has been stripped. Otherwise the editor seems to be working as expected, although I've not done a thorough check.

Do you have plans to support Angular v.10 soon?

**Comment by KillerCodeMonkey** [comment]
Yes, i am planning angular 10 Support. All in all Just an angular Upgrade
should Not lead to that behavior you describe.

Keep in mind i added sanitize Input to quill View in the latest Version.

Maybe IT has Something to do with stripped colors.



Kezia Wineberg <notifications@github.com> schrieb am Fr., 26. Juni 2020,
23:56:

**Comment by KillerCodeMonkey** [comment]
v12.0.1 supports angular 10 - breaking change, because ts >3.9, tslib 2 is needed
