### ISSUE TITLE
Quill Upgrade Errors

### ISSUE THREAD

**Issue by RoboZoom** [KillerCodeMonkey/ngx-quill#953]
Hi,

I have an angular application that was runing Angular 9 with ngx-quill version 7.x fine, but I upgraded both Angular and ngx-quill.  In my Quill upgrade, on compile I'm getting two new errors internal to ngx-quill:

1)  Module '".../node_modules/@types/quill/node_modules/fast-diff/diff"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

2)  Module '"../../@types/quill"' has no exported member 'Delta'. Did you mean to use 'import Delta from "../../@types/quill"' instead?

While I can try to go into the package to troubleshoot, it strikes me that the package isn't meant to fail this way, and something else may be wrong. Any ideas as to why this may be happening? 

Note: With Angular 10 and Quill 7.x, the application appeared to function normally.    

Partial pictures with files and line numbers, as well as my configuration shown below.  

Relevant Config:
```
"dependencies": {
    "@angular/animations": "^10.0.1",
    "@angular/cdk": "^10.0.0",
    "@angular/common": "^10.0.1",
    "@angular/compiler": "^10.0.1",
    "@angular/core": "^10.0.1",
    "@angular/forms": "^10.0.1",
    "@angular/localize": "^10.0.1",
    "@angular/material": "^10.0.0",
    "@angular/material-moment-adapter": "^10.0.0",
    "@angular/platform-browser": "^10.0.1",
    "@angular/platform-browser-dynamic": "^10.0.1",
    "@angular/router": "^10.0.1",
    "@types/quill": "^2.0.3",
    "ng2-charts": "^2.3.2",
    "ngx-quill": "^11.1.0",
    "quill": "^1.3.7",
}
```

Partial Screenshot:
![Quill Error](https://user-images.githubusercontent.com/56803986/85952513-d3719e80-b937-11ea-9a57-9ba90c62d1ff.jpg)

**Comment by KillerCodeMonkey** [comment]
Just install The correct quill typings. V1 quilljs requires V1 typings

RoboZoom <notifications@github.com> schrieb am So., 28. Juni 2020, 18:07:

**Comment by RoboZoom** [comment]
What package contains the v1 quilljs typings?  NPM is showing @types/quill version 2.0.3 being up to date.  Is there another version, or another package that I should be installing as a dependency?

**Comment by KillerCodeMonkey** [comment]
Nope... Just Install The V1 Version of the typings ... Using The latest
Version of a package does Not mean you are using The right Version ;-).

Just check the package.json of my Demo repo.


Quilljs 2.0 is Not releases , yet. Only a Dev Version. So The V2 typings
are for quill V2.

RoboZoom <notifications@github.com> schrieb am So., 28. Juni 2020, 18:31:

**Comment by RoboZoom** [comment]
That fixed it - thanks for the help!
