### ISSUE TITLE
Delta representation in nix-quill.

### ISSUE THREAD

**Issue by HTanke** [KillerCodeMonkey/ngx-quill#954]
Hi,
I'm trying to customize quill especially the module clipboard to improve editor behavior.
Therefore I need the object representation of _Delta_. In posted examples of _ngx-quill_ Deltas will be created manually by just creating a common object.
Is it possible to use the _Delta_ definition of _QuillJS_ instead? Or is there a TypeScript representation of _Delta_ which do not lead to crashes, because of a missing method?

I would really appreciate your help!
Hanke

**Comment by KillerCodeMonkey** [comment]
just install the @types/quill v1.3.7 There should be delta typings.
