### ISSUE TITLE
Keybinding for TAB not working Angular10

### ISSUE THREAD

**Issue by jakub-wisniowski** [KillerCodeMonkey/ngx-quill#956]
Thank you very much for developing ngx-quill!

My project was recently upgraded to Angular10. RIght now I'm using:

    "@types/quill": "1.3.10",
    "ngx-quill": "^12.0.1",
    "quill": "^1.3.7",
    "quill-delta": "^4.2.2",
In the previous version I used this snippet to make the tab key switch between editors instead of inserting a tab:
```

   @ViewChild('quillEditor')
   quillEditor: QuillEditorComponent;
   ...
   this.quillEditor.quillEditor.keyboard.bindings[9] = [];
```

but after upgrade I'm getting an error `property 'bindings does not exist on type 'Keyboard Static'`.

I've tried a different approach:
```
   // @ts-ignore
   this.quillEditor.quillEditor.keyboard.addBinding({key: 9}, () => {});
```

but it does not work, after clicking TAB I get a new TAB in the editor. It works fine for `key: 8`, backspace gets ignored. I've also tries changing `key: 9` to `key: 'tab'` and `key: 'TAB'`, because linters says that key should be a string, but it didn't help.

Any suggestions how to fix this issue?

**Comment by KillerCodeMonkey** [comment]
i did not tried to overwrite tab binding. And i do not know why it should not work with angular 10.

but there exists a default handler in quilljs for "tab". you can only overwrite it in the config of the editor and not afterwards.
`addBinding`, just adds another binding to the bindings list. So the default one is called before and stops propagating it. So your handler will never be called. Just add you listeners to the modules-config and it should work.

https://quilljs.com/docs/modules/keyboard/#configuration

Check our the whole bindings block. 

> Note: Since Quill’s default handlers are added at initialization, the only way to prevent them is to add yours in the configuration.
