### ISSUE TITLE
How to Cutsomize Editor.

### ISSUE THREAD

**Issue by GokulGnanam** [KillerCodeMonkey/ngx-quill#959]
I am in no need of some options available in quill like subscript x2 and superscript, how can we do it.

**Comment by KillerCodeMonkey** [comment]
Just check my Demo repo. Quill has a Formular Module. Just search for it.

In my Demo you See an example with Formulars enabled.

But you Need to Install / load katex.

Check The quilljs documentation for it.

GokulGnanam <notifications@github.com> schrieb am Sa., 4. Juli 2020, 09:42:
