### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by agam16** [KillerCodeMonkey/ngx-quill#96]
Hi
The required tag is working properly meaning it is attaching the class `invalid` but how can i show the message accordingly?

**Comment by KillerCodeMonkey** [comment]
Could you describe your question a little bit more please? How do you
validate and where do you want to show a message?

Am 10.01.2018 3:27 vorm. schrieb "agam16" <notifications@github.com>:

**Comment by agam16** [comment]
i am displaying the quill editor in for loop so on blur just like normal textbox, if its empty then we get the error in the object of that textbox but it doesn't happen in this. 

`<textarea [(ngModel)]="contentionObject.detail"
                  name="detail" #detail="ngModel"
                  required
                  class="form-control textarea-height-100"></textarea>`

`<label  class="form-control-feedback" *ngIf="detail.errors && detail.errors.required && detail.touched">
          <i class="fa fa-times-circle-o"></i> Contention Detail is required
        </label>`

In the above , i get the invalid in `detail` but not in case of quill editor.

**Comment by KillerCodeMonkey** [comment]
please use my custom required input correctly

`
[required]="true"
`
i expect an boolean to work correctly ;)

**Comment by aakashbumiya** [comment]
[required]="true" not working for me
