### ISSUE TITLE
Property 'forRoot' does not exist on type 'typeof QuillModule'.

### ISSUE THREAD

**Issue by nabeelalisajid** [KillerCodeMonkey/ngx-quill#961]
**Version Details**

Angular CLI: 1.7.4
Node: 10.16.0
OS: linux x64
Angular: 4.4.7
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, tsc-wrapped

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.3.4
webpack: 3.11.0

Any idea why this is happening?

**Comment by KillerCodeMonkey** [comment]
because i do not such old angular versions ;-). It is over 3 years old and even angular does not maintain such old versions. Just try to use an old ngx-quill version (< v1.6.0)
