### ISSUE TITLE
Placeholder is not updated on changes

### ISSUE THREAD

**Issue by hudzenko** [KillerCodeMonkey/ngx-quill#97]
Hello! First of all thanks for this great component. I have on small issue:

Placeholder is saving init value on changes.
Tempalte:
`<quill-editor [modules]="toolbarModules" [readOnly]="conversation?.isUserBlocked" formControlName="message" [placeholder]="getPlaceholderText()"></quill-editor>`

getPlaceholderText() function:
```
getPlaceholderText(): string {
    return (this.conversation && this.conversation.isUserBlocked) ? 'Unblock user to type him' : 'Click to start typing';
  }
```
readOnly is changing after (in my case) conversation.isUserBlocked change. But seems like placeholder get only initial value for a view.

**Comment by KillerCodeMonkey** [comment]
There is no way to update the placeholder after editor instantiation.
So i did not found something in the quilljs documentation.

The only way to update the placeholder is to reinstantiate the editor.

**Comment by hudzenko** [comment]
Got it, thanks! Is there a simple way to reinstantiate the editor?

**Comment by KillerCodeMonkey** [comment]
Remove and add it to the Dom again ^^, e.g. with *ngIf

**Comment by KillerCodeMonkey** [comment]
@hudzenko updating the placeholder is now working in v2.1.1

**Comment by hudzenko** [comment]
@KillerCodeMonkey great, thanks!
