### ISSUE TITLE
Set a "default" format on every text input / onContentChanged().html broken?

### ISSUE THREAD

**Issue by connectedSoul** [KillerCodeMonkey/ngx-quill#971]
I'd like to write only bold. But i cannot figure it out. Looked in the QuillJS documentation, but it is more aesthetic than helpful.

what i've tried so far:
in the template
```
<quill-editor
  formats="['bold']"
  [(ngModel)]="editorModel"
  format="html"
  [modules]="modules"
  (onContentChanged)="onContentChanged($event)">
</quill-editor
```
which has no effect at all. I guess because this is a "can" not a "should"

and in typescript:
```
  onContentChanged(event) {
    this.updatedContent = '<strong>'+event.html+'</strong>';
    this.updatedContentOutput.emit(this.updatedContent);
  }
```

using just event.html is what i do. Funny enough, if wrapping it inside the strong html tags, it is indeed bold. but when i type "hello world" it displays "dlrow olleh", basically typing backwards.

**Comment by KillerCodeMonkey** [comment]
i think you do not need this.

just listen to "onEditorCreated" or the first "selectionChanged" and use https://quilljs.com/docs/api/#format to activate bold per default

**Comment by connectedSoul** [comment]
Ok, that hint helped, here is my progress:

```
  onEditorCreated(quill) {
    quill.setText('Hello\nWorld!\n');
    quill.updateContents(new Delta()
      .retain(6)                  // Keep 'Hello '
      .delete(5)                  // 'World' is deleted
      .insert('Quill')
      .retain(1, { bold: true })  // Apply bold to exclamation mark
    );
  }
```

So with this i am able to get the quill instance. I set up an example from the docs:
SetText ist working, but for the new Delta(), i need the Delta definition, which i am not able to import.
`import {Delta} from 'quill'` is not working.

also tried the following:
example from docs: 

quill.format('color', 'red');
quill.format('align', 'right');

but what is the first or second parameter for bold? what I've tried:


```
  onEditorCreated(quill) {
    quill.format('bold');
    quill.format('bold', 'bold');
    quill.format('format', 'bold');
    quill.format('inline', 'bold');
    );
  }
```
