### ISSUE TITLE
Can't make patchValue working

### ISSUE THREAD

**Issue by Specialkha** [KillerCodeMonkey/ngx-quill#973]
Hello,

I can't find a way to use patchValue. I followed the exemple but it did not work.

    this.articleForm.patchValue({
      title: this.articleTitre
    });
    this.articleForm.get('contentArticle').patchValue({
      contentArticle: this.articles[0].contentArticle
    });

    console.log( this.articleForm.get('contentArticle').patchValue({
      contentArticle: this.articles[0].contentArticle
    }))

The first one is a classic patchValue to an input and it works.
The second one is the patchValue leading to the quill-editor tag but it returns undefined in the console while when I log this.articles[0].contentArticle I get the HTML.

The HTML part looks like this:

 <form *ngIf="isEdit" [formGroup]="articleForm"
                                (ngSubmit)=(update(articleForm.value,article.id))>
                                <div id="form">
                                        <div>

                                                <label for="title" class="inputField">Titre de l'article</label>
                                                <input type="text" formControlName="title" class="inputField"
                                                        id="title">

                                                <quill-editor formControlName="contentArticle" format="html">
                                                        <div quill-editor-toolbar>

I am quite new to Angular and programming overall and I would appreciate any help to make this work.
Thanks !

**Comment by KillerCodeMonkey** [comment]
I think there is an example about it in my Demo repo

Specialkha <notifications@github.com> schrieb am Fr., 17. Juli 2020, 10:15:

**Comment by Specialkha** [comment]
I did check it and find it before trying to implement it in my code, but I could not make it work.

Or maybe I got it wrong. If you get the link to that exemple so I can make sure I followed the right one.

Cheers

**Comment by KillerCodeMonkey** [comment]
https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/src/app/reactive-forms/reactive-forms.component.ts



Specialkha <notifications@github.com> schrieb am Fr., 17. Juli 2020, 10:36:

**Comment by Specialkha** [comment]
I did make it work with some dummy text so my source is not working. 

Thanks for the help !
Cheers
