### ISSUE TITLE
How to calculate length of pre filled content in json format?

### ISSUE THREAD

**Issue by koreem** [KillerCodeMonkey/ngx-quill#974]
I'm currently displaying a counter when a user is typing in the quill editor. For that I use the contentChanged() method and do content.text.length -1. That is working fine. I also have a use case where the quill-editor is being pre filled. How can I then count the length? Right now the length is way too high because it is in json format.

**Comment by KillerCodeMonkey** [comment]
AS i Remember correctly what i had build.

onContentChange gives you content in all Forms, plain Text, HTML, json
object.

For init/default values, listen to onEditorCreated and use the quill Editor
instance and quilljs api to get The current Text.



Marc Koree <notifications@github.com> schrieb am Fr., 17. Juli 2020, 14:36:

**Comment by koreem** [comment]
Thanks, any idea how to get the current text or where it is documented?

**Comment by koreem** [comment]
`  public editorCreated = (quill: any): void => {
    console.log(quill.getLength());
  };`

This works!
