### ISSUE TITLE
Quill Appears to be Grabbing Focus after Toolbar Button Press (v. 9.1.1)

### ISSUE THREAD

**Issue by vkoves** [KillerCodeMonkey/ngx-quill#976]
I recently upgraded from `ngx-quill` `7.3.2` to `9.1.1` and although it worked great overall, there was one issue that made us need to revert to the older version - the editor appears to be grabbing focus away from a modal on click of a tooltip button. Here's a GIF showing that the modal (which calls `.focus()` on its input) loses focus immediately to the editor:

![Peek 2020-07-21 08-35](https://user-images.githubusercontent.com/3187531/88061452-1dac0100-cb2d-11ea-8315-83f4b0c8e401.gif)

For some context, we're calling `toolbar.addHandler('formula', ourFunction);`. Our function then opens a Google Material modal, which uses an Angular CDK focus trap and the `cdkFocusInitial` directive to set focus. My immediate thought was that this issue was with Google Material or our usage of it, but reverting _only_ `ngx-quill` completely fixed the issue.

Was there some change that could be causing the Quill editor to grab focus upon a tooltip click?

**Comment by KillerCodeMonkey** [comment]
I have no Logic in there that Auto focus anything...

Viktor Köves <notifications@github.com> schrieb am Di., 21. Juli 2020,
15:36:

**Comment by vkoves** [comment]
@KillerCodeMonkey - I appreciate the quick response. I'll do more digging and post an update.

**Comment by KillerCodeMonkey** [comment]
maybe it is a timing issue, because clicking the toolbar button without the cursor in the editor will set the quill selection to 0 (so the start in your empty editor).

Maybe your modal gets the focus first and then loose it again, because everything in quilljs happens outside of the angular zone.

Do you use onPush change detection?

**Comment by vkoves** [comment]
We immediately were creating a FocusTrap with Angular CDK and then called `focusTrap.focusInitialElementWhenReady` - I'll come back to this at some point and will test a delay and see if that helps. For now though, I'll just close this issue since I haven't pinned down any change in this package that caused this. Thank you for your help!
