### ISSUE TITLE
Angular 9 with ngx-quill 11.1.0 not loading editor correctly

### ISSUE THREAD

**Issue by amrarick26** [KillerCodeMonkey/ngx-quill#980]
The ngx-quill editor is loading these svgs when I would expect the WYSIWYG editor to load

Dependencies:
"ngx-quill": "11.1.0"
"quill": "1.3.7"
"rxjs": "6.6.0"
"@angular/core": "9.1.12"
"@angular/forms": "9.1.12"
"@angular/common": "9.1.12"
"@angular/platform-browser": "9.1.12"

Included theme stylings in angular.json:
```"test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css",
              "node_modules/quill/dist/quill.core.css",
              "node_modules/quill/dist/quill.snow.css"
            ],
            "scripts": []
          }
        },
```

I added the QuillModule.forRoot() to the imports of the ngModule

[here's a repository](https://github.com/amrarick26/troubleshoot-ngx-quill) I created to reproduce the issue. 

here is a screen shot of what is loading in place of the editor
![ngx-quill](https://user-images.githubusercontent.com/17101525/88592944-6af40b00-d024-11ea-93d6-b8f46fc74c15.jpg)

Any guidance would be appreciated!

**Comment by KillerCodeMonkey** [comment]
I guess The stylings are Not applied because of the View encapsulation?



Alexa Snyder <notifications@github.com> schrieb am Mo., 27. Juli 2020,
23:22:

**Comment by KillerCodeMonkey** [comment]
btw: i think you added the stylings to the wrong step in your angular-json.

```JSON
"build": {
          "builder": "@angular-devkit/build-angular:browser",
          ...
}
```

you added them to the test runner

https://github.com/KillerCodeMonkey/ngx-quill-example/blob/master/angular.json#L13

**Comment by amrarick26** [comment]
🤦 thank you!
