### ISSUE TITLE
Change font as a datalist instead of a select

### ISSUE THREAD

**Issue by GRGueiros** [KillerCodeMonkey/ngx-quill#983]
Is it possible to use toolbar module in order to type directly the font size number, working as a datalist and not as a select? If the value is out of the default list, it would go to the last possible value.

**Comment by KillerCodeMonkey** [comment]
that is one question you should ask at the quilljs repo, but in general you can build your own formats and toolbar buttons/selects.

So you could create your own Module (e.g. the link module) or just add your an input to your custom toolbar, add a js listener when the value changes and change the fontsize of the current selection in the editor.
