### ISSUE TITLE
CSS not included in the package

### ISSUE THREAD

**Issue by umbertix** [KillerCodeMonkey/ngx-quill#99]
Would be great if you could add the css in the package so it can be integrated in the build process, otherwise have to manually pull it from the cdn and obv. it does not keep sync with the version in case that there is breaking changes.

Thx anyway for the library, looks great.

**Comment by KillerCodeMonkey** [comment]
What CSS? I do not have any CSS... All CSS comes from quilljs?

This is only a angular wrapper for quilljs

Am 14.01.2018 6:12 nachm. schrieb "Umbert" <notifications@github.com>:

**Comment by mmoravcik** [comment]
See this answer https://github.com/KillerCodeMonkey/ngx-quill/issues/8#issuecomment-271810481
