### ISSUE TITLE
Need help with error state in mat-quill

### ISSUE THREAD

**Issue by dgutoryan** [KillerCodeMonkey/ngx-quill#993]
Hello, thank you for great library.

I'm trying to use mat-quill from your examples. But I have some problem with error state. I would like to have behavior like mat-form-field: 

- touch the field => field has red border and error message
- submit invalid form => field has red border and error message

I've created [stackblitz repro](https://stackblitz.com/edit/angular-ivy-8gf6ew) 

Could you help me with that?

**Comment by KillerCodeMonkey** [comment]
sadly no, because i am not using material ui with angular. The mat-quill examples are created by @deavon . Just ask him maybe he can guide you.

Or use native ngx-quill and style the editor a little bit like mat ui.

**Comment by dgutoryan** [comment]
I can't send him a message for some reason.

**Comment by williamlambert-jc** [comment]
I was faced with the same issue and copy pasted the error management from [this stackoverflow issue](https://stackoverflow.com/questions/59962647/how-to-integrate-quill-editor-with-angular-material-impementing-a-custom-matform)

Basically I added  in the `_MatQuillBase` Directive :

- the `errorState` property
```typescript
errorState = false;
```
- this `ngDoCheck` hook
```typescript
ngDoCheck(): void {
    if (this.ngControl) {
      this.errorState = this.ngControl.invalid && this.ngControl.touched && !this.focused;
      this.stateChanges.next();
    }
  }
```
- `DoCheck` in the `implements` section

**Comment by Babeetlebum** [comment]
I was faced with the same issue and copy pasted the error management from [this stackoverflow issue](https://stackoverflow.com/questions/59962647/how-to-integrate-quill-editor-with-angular-material-impementing-a-custom-matform)

Basically I added  in the `_MatQuillBase` Directive :

- the `errorState` property
```typescript
errorState = false;
```
- this `ngDoCheck` hook
```typescript
ngDoCheck(): void {
    if (this.ngControl) {
      this.errorState = this.ngControl.invalid && this.ngControl.touched && !this.focused;
      this.stateChanges.next();
    }
  }
```
- `DoCheck` in the `implements` section
