### ISSUE TITLE
the editor isn't rendering correctly

### ISSUE THREAD

**Issue by zouchengtao** [KillerCodeMonkey/ngx-quill#996]
`<quill-editor formControlName="courseDesc" [styles]="{'height':'320px'}" [modules]="editorModules"></quill-editor>`
then
`courseDesc: new FormControl('<p>test</p><p>hello</p>')`
but the actual display effect is:
![image](https://user-images.githubusercontent.com/20035635/90113925-97c65300-dd84-11ea-9c23-06460feb8efe.png)
i dont know why

**Comment by KillerCodeMonkey** [comment]
Could you Checkout my Demo repo and IT Out there?

So you use p-tags or div Tags as block element

zouchengtao <notifications@github.com> schrieb am Do., 13. Aug. 2020, 10:47:

**Comment by KillerCodeMonkey** [comment]
any updates on this?

**Comment by zouchengtao** [comment]
sorry, I don't understand what you mean

**Comment by KillerCodeMonkey** [comment]
okay then, could you provide a demo repo or stackblitz example to reproduce the behaviour?

**Comment by zouchengtao** [comment]
I think it may be caused by using the form component of ng-zorro-antd，I just debugged on stackblitz and tried not to use the from component of ng-zorro-antd and found it was ok

**Comment by KillerCodeMonkey** [comment]
so first please ask there then for help :)
