### ISSUE TITLE
Bubble theme and Material design - color picker

### ISSUE THREAD

**Issue by pralthom** [KillerCodeMonkey/ngx-quill#999]
Hello,

First of all, thank you for your work, your project saved me a lot of time!

I think I found an issue with the color picker when it is used with Material Design and the Bubble theme.

You cannot select any color, the picker does not stay open when you click on the picker button:
![colorPickerProblem](https://user-images.githubusercontent.com/44721265/90377182-e7a06500-e077-11ea-933e-121841bd8d49.gif)

You can easily reproduce the problem on your demo project: https://killercodemonkey.github.io/ngx-quill-example/

Thank you in advance for your help

**Comment by KillerCodeMonkey** [comment]
Hey. Maybe :). But i am not officially support material ui stuff. the examples are just something like an example how it could look like. I do not even implemented those examples.  :S

**Comment by pralthom** [comment]
> Hey. Maybe :). But i am not officially support material ui stuff. the examples are just something like an example how it could look like. I do not even implemented those examples. :S

OK I understand, thank you for the quick answer.

**Comment by KillerCodeMonkey** [comment]
do you get around it?

**Comment by pralthom** [comment]
> do you get around it?

I need only one color in the picker, therefore I have implemented a custom Blot which add a <mark> tag. It is not perfect but it works.

Unfortunately I did not find a solution for this specific problem.

**Comment by KillerCodeMonkey** [comment]
strange. but as i do not give official material support. i will close this one, because it is working without the material ui stuff.
